### ISSUE TITLE
Quest Not Tracked: Garments of The Light

### ISSUE THREAD

**Issue by abennette32** [AeroScripts/QuestieDev#1]
The level 5 priest quest, Garments of the Light, is not tracked properly. It shows the quest objective as the quest giver as opposed to the guard at the lake to the east.

Quest Giver: Priestess Josetta

Objective NPC: Guard Roberts

**Comment by AeroScripts** [comment]
Interesting. It seems that the quest was edited to contain only one objective in burning crusade "Heal and fortify Guard Roberts" where as (as far as I can tell) vanilla has one for each "Heal Guard Roberts" and "Fortify Guard Roberts"

This affects every faction's priest quest. I've made aliases for heal/fortify so this should be fixed after commit 4db54b8ce6df8261b3850176dbb4f486ca08c98e

**Comment by abennette32** [comment]
Note that on Nostalrius, when completing things it says "Heal Guard Roberts 1/1" both times.
