### ISSUE TITLE
There should be an option to add available quests to the map

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#10]
Based on the player's level range. As far as I know there's no way to get the list of completed quests so this would require the use of savedvariables. 

Going to see if I can make a database for this.

**Comment by rsheep** [comment]
There are addons recording you quest history.

You could write your own db as well. Shouldn't be that hard.

**Comment by Schaka** [comment]
This is already in the making, actually. But if you can point us towards an addon that records the quest history, that'd be very helpful.

**Comment by rsheep** [comment]
right, QuestHistory:
http://addons.us.to/addon/questhistory
http://wow.curseforge.com/addons/project-50/
http://wow.curseforge.com/addons/project-1307/
http://wow.curseforge.com/addons/project-500/
http://wow.curseforge.com/addons/quest-history_felstone/

QuestHistoryMap (couldn't find a webpage, so I uploaded it):
http://www21.zippyshare.com/v/r3E7fX7p/file.html

**Comment by AeroScripts** [comment]
:o thanks for that, it might still be helpful only I JUST finished creating a system for this lol. It's based on the new quest hash system (adler32 checksums of the quest name + objective text + level). 

Taking the easy way out and just doing something along the lines of SavedVariable->SeenQuests and SeenQuests[hash] = time(), then just SeenQuests[hash] == nil to check. As far as I can tell itt'l be the least processing intensive way of doing it (important because these checks are done often and in large batches)



Also, on the original topic of this thread, the "available quests" function is added as of 470650940b2f5a8c5137fef6994e599a9e6d7c95 but it does not yet exclude quests you already have or have completed.

**Comment by Schaka** [comment]
Closing this, as it already works through our quest hash system.
