### ISSUE TITLE
TrackerFrame disappears in Dungeon, and I can not track quest in ZF at all.

### ISSUE THREAD

**Issue by ayrb13** [AeroScripts/QuestieDev#100]
TrackerFrame disappears in Dungeon, and I can not track quest in ZF at all.

**Comment by Schaka** [comment]
The disappearing is a bug, the rest is not.

**Comment by Schaka** [comment]
There is no point in showing the frame during dungeons, as no coordinates are available anyway.

**Comment by ayrb13** [comment]
I just want to track the count of quest items or how many mobs should i kill.
maybe I should disable questie in dungeons.
