### ISSUE TITLE
Hidden by user checkbox is not working correct

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#1000]
## Bug description

If you hide a quest the checkbox "Hidden by user" in the journey is not checked. If you check it the quest is shown afterwards though.

## Screenshots

![image](https://user-images.githubusercontent.com/33514570/64977864-821a8600-d8b4-11e9-8102-e9766881ecd7.png)

## Questie version

4.1

**Comment by BreakBB** [comment]
This has also been reported on [Curseforge](https://www.curseforge.com/wow/addons/questie?comment=395)

**Comment by Muehe** [comment]
Just FYI, I have a fix for this on my local branch. Will be pushed to master soon™
