### ISSUE TITLE
Add Classic Quest Log support

### ISSUE THREAD

**Issue by ShaunDreclin** [AeroScripts/QuestieDev#1001]
The new quest tracker doesn't work with [Classic Quest Log](https://wowinterface.com/downloads/info24937-ClassicQuestLogforClassic.html), shift clicking quests in that log doesn't track them.

**Comment by AeroScripts** [comment]
Doing some testing with this tonight, should be easy to make it compatible

**Comment by ShaunDreclin** [comment]
As of 4.1.1 shift-clicking to track/untrack works, but when using the Show in Quest Log Shortcut it still opens the default log instead of CQL.

**Comment by Gogo1951** [comment]
Hey @ShaunDreclin ,

Is this still relevant? If so, can you update with what's still broken? If not, let's close. Thanks!

**Comment by ShaunDreclin** [comment]
Still broken, clicking quests in the Questie tracker (the Show in Quest Log Shortcut) opens the Vanilla log instead of CQL

**Comment by BreakBB** [comment]
@ShaunDreclin Finally had the time to look into this and it was a really easy fix 👍 Will be in the next release.
