### ISSUE TITLE
New quest tracker anchor is wrong?

### ISSUE THREAD

**Issue by ssateneth** [AeroScripts/QuestieDev#1003]
## Bug description

The new quest tracker is nice, but i'm suspecting the anchor is wrong. What I mean is when new quests are added, the tracker expands up and down, instead of just down. With a lot of quests, it will expand over my minimap and quest time limit timer. It only seems to happen when the tracker is closer to the middle of the screen

## Screenshots

https://i.imgur.com/fWFdujJ.gifv

## Questie version

4.1.0

**Comment by ShaunDreclin** [comment]
Yeah it's anchored to `RIGHT`, I'd like an option to change it to `TOPRIGHT`. Not sure if this a bug or an oversight

**Comment by reaper666735** [comment]
same here :p

**Comment by BreakBB** [comment]
Merging this with #1019 We hope to get an update out soon to fix this! Sorry for the trouble
