### ISSUE TITLE
Moveable questlog

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#1004]
## Description

Suggested on [Curseforge](https://www.curseforge.com/wow/addons/questie?comment=404) it would be great to make the questlog movable.

**Comment by qwksilver** [comment]
and double pane window, see questguru_classic, but to use with out extra addons.

**Comment by Gogo1951** [comment]
I use Monkey Quest (https://www.curseforge.com/wow/addons/monkey-quest) to move the panel (I guess ElvUI now works too -- early on there was a placement bug and I needed Monkey Quest but I should prob evaluate that again), and I use Leatrix (https://www.curseforge.com/wow/addons/leatrix-plus-classic) to make the log wide. I'd drop Monkey Quest if Questie did this, but I don't think many people would drop Leatrix.

There's also Move Anything (https://www.curseforge.com/wow/addons/Move-Anything) which I think unofficially works with Classic.

Hey @BreakBB ,given that most anyone who wants to move the log already has a solution for it... is this still needed?

**Comment by BreakBB** [comment]
@Gogo1951 We don't want folks to have to install multiple questing addons. So yes, we should still add the possibility to move the quest log with just Questie installed.

**Comment by Gogo1951** [comment]
Yeah but, I think it's OK to not aim for an all-in-one though.

Let people mix and match and just make sure comparability isn't impacted. Leatrix for wide logs, ElvUI to move the tracker panel, Quest Announce to tell my party (who aren't on Questie) that I'm done, Quest Completist to be all OCD... Ha. Everyone's going to have different ideas of what they need and that's cool. We all play the game a little differently. (=
