### ISSUE TITLE
4.1.0 breaks Modern Quest Watch

### ISSUE THREAD

**Issue by olgavass** [AeroScripts/QuestieDev#1006]
## Bug description
Updating to 4.1.0 broke my current quest tracking, even after I turned off Questie tracker and all its options. Even if quests are tracked in the quest log, no tracker shows up. I'm using Modern Quest Watch. Reverting to Questie 4.0.18 fixed this issue and I'm able to see tracked quests again.

**Comment by AtairWoW** [comment]
Had the same problem. Would be great if Questie Tracker also supported options like Modern Quest Watch.

However, after unchecking "Enable the Questie Tracker" you currently have to reload your UI to make the hidden WoW quest tracker visible again.

**Comment by AeroScripts** [comment]
Yeah, disabling the tracker doesn't remove all the hooks, that requires a /reload. Looking in to a way to make that smoother

As for ModernQuestWatch, im doing some testing with this and other addons (Classic Quest Log and QuestGuru also have issues apparently)

We should be able to solve the issues by 4.1.1 which should be out in a day or two

**Comment by olgavass** [comment]
My bad on the /reload. I forgot that it existed and I thought I'd relogged after turning off the tracker, but I guess not. Modern Quest Watch does work if I update to 4.1.0 again now that my settings have Questie tracker turned off.

Please close if you think the fix for this is the same as for some of the other tracker issues you mentioned and you'd rather not have an extra open issue cluttering your feed.

**Comment by BreakBB** [comment]
This has already been fixed with the release of v4.1.1 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.1
