### ISSUE TITLE
"quests by zone" broken 4.1.0

### ISSUE THREAD

**Issue by ssateneth** [AeroScripts/QuestieDev#1007]
## Bug description

The player journey window is broken. . None of the dropboxes in quests by zone or advanced zone work the advanced search works, but thats it. if you click the empty area, it gives a dropdown, weird behavior

## Screenshots

https://i.imgur.com/Jk8xVk5.gifv

## Questie version

4.1.0

**Comment by AeroScripts** [comment]
Really strange, can you post your mod list and test if this happens with just questie? Will do some testing tonight

**Comment by ssateneth** [comment]
This has some bad interaction with AuctionMaster addon, maybe something to do with the libuidropdown library, because I always get these errors when i relodui with aucitonmaster running.

Message: Deferred XML Node object named Lib_UIDropDownMenuButtonTemplate already exists
Time: Mon Sep 16 15:00:03 2019
Count: 5

**Comment by AeroScripts** [comment]
Oh jeez that makes sense, ill push a fix shortly

**Comment by Muehe** [comment]
@AeroScripts This is fixed?

**Comment by BreakBB** [comment]
This can't be reproduced and since there hasn't been any response I will close this.
