### ISSUE TITLE
Error upon logout

### ISSUE THREAD

**Issue by ClownCake** [AeroScripts/QuestieDev#101]
I hear the "ding" of my improved error frame addon when logging out, (where can I see the error?)

I also get game studdering when hovering over some NPC's and players

**Comment by Schaka** [comment]
The stuttering should not be happening anymore since we cached quest hashes. Please make sure you use v2.0.9.
The logout error is probably some falsely routed event, that we still have going. I'm almost certain I removed that recently too.

**Comment by ClownCake** [comment]
I hadn't cleaned the WTF folder properly. Close.
