### ISSUE TITLE
Tanaris Quest Bug

### ISSUE THREAD

**Issue by grubbell** [AeroScripts/QuestieDev#1013]
Any time I zone into any zone through a loading screen and Questie trys to load quest objectives on the Map.

![image](https://user-images.githubusercontent.com/33514570/65017529-5389c300-d927-11e9-85b6-5132140d0c57.png)

4.1.0

**Comment by rasmuszimmer** [comment]
Confirmed getting the same.
![image](https://user-images.githubusercontent.com/5746348/65017777-ce52de00-d927-11e9-824d-65899f024295.png)
