### ISSUE TITLE
Swatter Error message popped up in chat.

### ISSUE THREAD

**Issue by Pr0digity** [AeroScripts/QuestieDev#1015]
Date: 2019-09-16 21:17:53
ID: 1
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (CompactRaidFrame3:ClearAllPoints()) during combat lockdown.
Debug:
   [C]: ClearAllPoints()
   ..\FrameXML\FlowContainer.lua:157: FlowContainer_DoLayout()
   ..\FrameXML\FlowContainer.lua:17: FlowContainer_ResumeUpdates()
   ...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185: CompactRaidFrameContainer_LayoutFrames()
   ...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130: CompactRaidFrameContainer_TryUpdate()
   ...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57: CompactRaidFrameContainer_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6420 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  Enchantrix, v8.2.6411 (SwimmingSeadragon)
  ExtVendorUIClassic, v1.0.3
  GatherMate2, v1.45
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixMaps, v1.13.30
  Questie, v4.1.0 BETA
  Recount, vv1.13.2c
  Scrap, v13.19
  ScrapOptions, v13.19
  ScrapSpotlight, v13.19
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=389)

**Comment by BreakBB** [comment]
Can you disable all other addons and try again? It seems like a conflict to another addon
