### ISSUE TITLE
Error on every reload and launch

### ISSUE THREAD

**Issue by t4p0ut** [AeroScripts/QuestieDev#1016]
## Bug description

Date: 2019-09-16 21:49:25
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\QuestieDev-master\Questie.lua line 2:
   Usage: NewAddon([object,] name, [lib, lib, lib, ...]): 'name' - Addon 'Questie' already exists.
Debug:
   [C]: ?
   ...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:119: NewAddon()
   QuestieDev-master\Questie.lua:2: in main chunk
Locals:
(*temporary) = "Usage: NewAddon([object,] name, [lib, lib, lib, ...]): 'name' - Addon 'Questie' already exists."

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AbarClassic, v
  AtlasLootClassic, vv1.1.11
  AucAdvanced, v8.2.6420 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  BagFreeSpaceCounter, v1.0.2
  Bagnon, v8.2.13
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BiSTracker, v1.2 
  ClassicCastbars, vv1.0.6
  ClassicCastbarsOptions, v
  ClassicThreatMeter, v1.06
  ClassPortraitsFinal, v
  DBMCore, v1.13.9
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Dismounter, v1.0.0
  ElitePlayerFrameEnhanced, v1.5.3
  EZJunk, v1.0.1
  FPSCounter, v1.1.r10
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LeatrixMaps, v1.13.30
  LortiUIClassic, v1.1.0
  OmniCC, v8.1.1
  outofrange13, vv1.3
  Prat30, v3.7.36
  Prat30Libraries, v
  Quartz, v3.5.1
  Questie, v4.1.0 BETA
  QuestieDevmaster, v4.0.9 BETA
  RealMobHealth, v2.11
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=516)

## Questie version

4.1.0

**Comment by BreakBB** [comment]
Looks like you have more than one version of Questie in your AddOns folder. Make sure to remove both and then paste the latest release feom [here](https://github.com/AeroScripts/QuestieDev/releases)

**Comment by t4p0ut** [comment]
That worked, my bad, Thanks.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
