### ISSUE TITLE
Tooltips and nameplates not working with localization

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#1018]
## Bug description

Reported on Discord.

On a french client neither the tooltips nor the nameplates are working. The user stated that this happens to him and his guild mates as well.
It matches with other reports.

## Screenshots

![image](https://user-images.githubusercontent.com/33514570/65018440-70bf9100-d929-11e9-94bb-762cb3fa6cbd.png)

## Questie version

4.1

**Comment by Doshilol** [comment]
Same for German client.

**Comment by BreakBB** [comment]
Yes this effects all clients using a language different to English. We're looking into what ever caused this and will have a solution for the next update

**Comment by kawo** [comment]
Hello Questie Team!

Can we help you in any way with this issue? A full debug/trace log? I have checked the "debug" mode but nothing so far.

I dont mind playing in english since release but sometime I love playing with my native language (french).

Anyway thanks for your amazing work!

**Comment by kawo** [comment]
With latest version (4.1.1) this issue is now resolved (for French anyway). Thank you!

![questieOK](https://user-images.githubusercontent.com/548404/65104617-27cc1300-d9e3-11e9-90aa-956c5d055f56.jpg)

**Comment by Doshilol** [comment]
Same for German, working now too. Thanks a lot!

**Comment by BreakBB** [comment]
Perfect, thanks foe coming back to report.
