### ISSUE TITLE
Game crashed on clicking on questracker to display arrow

### ISSUE THREAD

**Issue by MOUZU** [AeroScripts/QuestieDev#102]
using version 2.09

in the error message I found

0018FC80: 00 00 00 00  FE FF FF FF  44 42 47 3A  51 75 65 73  ........DBG:Ques
0018FC90: 74 69 65 54  72 61 63 6B  65 72 42 75  74 74 6F 6E  tieTrackerButton
0018FCA0: 4E 65 77 34  00 50 70 00  01 00 00 00  00 00 00 00  New4.Pp.........

I simply clicked on a quest in the tracker to display the arrow

**Comment by Pr1mu5** [comment]
encounter the same problem quite often, i thought its caused by moving the tracker but this might be the problem as well
