### ISSUE TITLE
Pterrordax location for quest in Un'Goro Crater "Shizzle's Flyer"

### ISSUE THREAD

**Issue by ssolidus** [AeroScripts/QuestieDev#1022]
## Description
There are 6 Pterrordax spawns at the clearing above the northern pylon at 56,11. Please add them to Questie.

EDIT: There's also 2 spawns at 50,10

**Comment by BreakBB** [comment]
We have those spawns in our data and they're linked to the quest. I will look into this 🤔

**Comment by ssolidus** [comment]
@BreakBB It might have been because I was on 4.0.18? Not sure. I've also had some very general problems for a while with certain markers just not appearing.
