### ISSUE TITLE
Faerie Dragon Muisek ect - tracker not updating

### ISSUE THREAD

**Issue by wanhoop** [AeroScripts/QuestieDev#1024]
## Bug description

quest chain in feralas for "muisec" some mobs - tracker not updating when use quest item
https://classic.wowhead.com/quest=3125/faerie-dragon-muisek

## Screenshots

![aab5d46350](https://user-images.githubusercontent.com/8421605/65030897-03bbf380-d949-11e9-8d15-11800903ef57.jpg)

## Questie version

4.1.

**Comment by BreakBB** [comment]
@wanhoop Please try v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2 and let me know if this isn't fixed with it
