### ISSUE TITLE
Captain Grayson (Alliance)

### ISSUE THREAD

**Issue by Nimbix-wow** [AeroScripts/QuestieDev#1025]
## Description

His quests are showing as available for Horde players. 

https://classicdb.ch/?quest=103
https://classicdb.ch/?quest=152
https://classicdb.ch/?quest=104

## Screenshots

![Captu1re](https://user-images.githubusercontent.com/46905100/65035288-133b3c80-d949-11e9-9146-b450f7c6e8a2.JPG)

## Questie version

v4.0.18

**Comment by Nimbix-wow** [comment]
Classic-WoWhead reports this as an Alliance only quest, so does Classicdb.

I did check this personally and his quests can be picked up by Horde players.

![2019-10-01 (6)](https://user-images.githubusercontent.com/46905100/65961169-4b1ca680-e456-11e9-856a-4cc13cd0e63e.png)

wow.gamepedia.com reports: 

"Even though he is faction-neutral, Grayson gives his quests only to Alliance adventurers. _**Before Cataclysm, Horde players were also able to do them**_."

**Comment by Nimbix-wow** [comment]
Btw, the quest CLUCK! can't be picked up by Horde players.

**Comment by drejjmit** [comment]
CLUCK! is hidden for both factions

**Comment by BreakBB** [comment]
Thanks for coming back to this. I reverted the changes.

**Comment by AeroScripts** [comment]
CLUCK is doable by horde, I know that for sure

It just takes a super long time for the quest to appear, same with ally

**Comment by Nimbix-wow** [comment]
> CLUCK is doable by horde, I know that for sure
> 
> It just takes a super long time for the quest to appear, same with ally. You also need to get the chicken feed via neutral auction house. But it is doable

Screenshot or it didn't happen. Tried it today and no quest was given from the chicken.
