### ISSUE TITLE
"The Scent of Lar'kowi" in Un'Goro Crater has no markers

### ISSUE THREAD

**Issue by ssolidus** [AeroScripts/QuestieDev#1027]
## Description

This quest does not have markers of the map for the locations of the Ravasaur Pheromone Glands. They are located at the following:
60, 72
62, 65
63, 77
67, 73
67, 67 

You run over the eggs and the Ravasaur Mates spawn. They drop the glands.

## Wowhead link

https://classic.wowhead.com/quest=4291/the-scent-of-larkorwi

## Questie version

4.1.0

EDIT:

I saw in this commit https://github.com/AeroScripts/QuestieDev/commit/0dd9877d559955f325a70d8c231be2644cf200d2 that you added the markers, but they aren't there.

![image](https://user-images.githubusercontent.com/14216632/65043198-ca61a300-d99d-11e9-968a-802a2571faaf.png)

**Comment by ssolidus** [comment]
"show icons" for that quest were turned off. They do appear.

**Comment by BreakBB** [comment]
I was kinda shocked for a moment. Glad you figured it out 👍
