### ISSUE TITLE
map doesnt update when acquiring quests

### ISSUE THREAD

**Issue by nycter79** [AeroScripts/QuestieDev#103]
as the topic says, when i acquire new quest, notes wont show on world map automaticaly, few days ago they showed up when i opened Q log, but now i have to click on "questie button" to hide all notes and click on it again to show those notes again + show the recently acquired quests notes

map addon: metamap

**Comment by nycter79** [comment]
but when I complete an objective, question mark appears immediately on the map O.o

**Comment by AeroScripts** [comment]
Just to verify, next time this happens try /reloadui and let me know if it fixes it.

If it does I'm fairly certain I know the cause/how to fix this

**Comment by nycter79** [comment]
/reload didnt help, but when i started tracking quest from q log (shift + click), notes appeared too. so the problem maybe is that the quests wont "start tracking" automaticaly.

**Comment by Schaka** [comment]
Duplicate of #88

**Comment by nycter79** [comment]
update: even if quest was added to track list immediately when i acquired it, notes doesnt show on minimap, so the problem will be somewhere else
