### ISSUE TITLE
Colored Map icons improved to be less subtle

### ISSUE THREAD

**Issue by MysticalOS** [AeroScripts/QuestieDev#1030]
## Description
Colored Map icons are a very nice feature, but to be honest the difference in color it generates between objects is WAY too subtle. It's still hard to tell some quests apart. I can't imagine how someone who's blue color blind feels about it literally favoring using as much of one color as possible instead of a larger fuller spectrum more aggressively. :)

**Comment by ShaunDreclin** [comment]
Switching to monochrome icons might help here rather than just tinting the existing ones

**Comment by MysticalOS** [comment]
I think just using a larger spectrum of color is enough. I have like 10 quests in zone, and all i have are 10 shades of blue. there are other colors on pallet :D

**Comment by Gogo1951** [comment]
Hey @MysticalOS ,

Would size and transparency help? 

https://github.com/AeroScripts/QuestieDev/issues/799#issuecomment-564583093

If that idea would suffice, can we close this issue?

**Comment by AeroScripts** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.

**Comment by Gogo1951** [comment]
Covered by #2500
