### ISSUE TITLE
Liquid Stone Shows Healing Potion on so many mobs

### ISSUE THREAD

**Issue by MysticalOS** [AeroScripts/QuestieDev#1032]
## Description
Another case of showing a rare drop on literally half the humanoid mobs in the game. Healing Potion needs filtering

## Wowhead link
https://classic.wowhead.com/quest=715/liquid-stone

## Questie version
4.1.0

**Comment by MysticalOS** [comment]
It's actually showing it on world map in a ton of places.

**Comment by AeroScripts** [comment]
Oh  jeez, will fix today thanks for reporting
