### ISSUE TITLE
Class quests are showing.

### ISSUE THREAD

**Issue by tehuno** [AeroScripts/QuestieDev#1036]
## Bug description
Level 50 class quests show in multiple major cities but they aren't in classic yet.

## Questie version
Latest. 4.1.1.

**Comment by BreakBB** [comment]
Please provide some more information. What quests do you mean?

**Comment by tehuno** [comment]
Seems like all the level 50 class quests that are coming in phase two that show in major cities.  My main is a mage so questie shows the quest Magecraft as available from trainer.  The rogue level 50 quest and warrior level 50 quest definitely show as all.   I believe they are the sunken temple level 50/52 quests that each class gets at their trainer in a major city (they all have different names).  The list is here: https://classic.wowhead.com/guides/sunken-temple-class-quests-classic-wow

**Comment by BreakBB** [comment]
Fixed with 21d045c6faf6deff995d4a3c68e190ab705f3509
