### ISSUE TITLE
[Russian localization] Trouble with display hints

### ISSUE THREAD

**Issue by ridik46** [AeroScripts/QuestieDev#1037]
The display of hints is incorrect on quests where you need to kill 2 types of different mobs, or pick up items from different mobs.

![44444444](https://user-images.githubusercontent.com/55483862/65132482-b2276d80-da09-11e9-8875-ff06926fcb87.png)

Latest version 4.1.1

**Comment by ridik46** [comment]
Any info?

**Comment by BreakBB** [comment]
Some translations are missing and therefore we can't show a tooltip. Is that what you mean?

**Comment by jk1895** [comment]
What he mean, I think is, that the quest title is repetitive. The title is displayed 3 times by a quest with 3 objectives. It very _spamy_ sometimes. (Is spamy a valid word in English? :) )
It looks this way is in my german client:
![WoWScrnShot_091819_221131](https://user-images.githubusercontent.com/20401451/65182580-e9296d80-da61-11e9-9780-55516a52ac54.jpg)

**Comment by ridik46** [comment]
I mean by the quest, for example, you need to drop peaces of meat from (boar, vulture and bear) on the boar and vulture there is no clue that the meat is drop from them, but on a bear it shows immediately and for a boar and a vulture. Due to the fact that there is a hint only on one of the three types of mobs, you have to read which mobs you need to kill in order to get an item

**Comment by Hitlock** [comment]
Let's say you need to kill three types of mobs: A, B, and C. You won't have any hints on A and B mobs, but C mobs will display hints for all three types at once. Like on the screenshot that jk1895 provided

**Comment by Hitlock** [comment]
I think it's the same as #1099 where a fix is provided. Also #861

**Comment by BreakBB** [comment]
Merging this with #1071
