### ISSUE TITLE
Repeatable as repeatable.

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#1038]
## Description
Mark repeatable as repeatable. Icon doesn't tell when they are grouped up like this.
![image](https://user-images.githubusercontent.com/15526476/65134165-219a5e80-da04-11e9-98c3-30dd2333efa8.png)

**Comment by Nimbix-wow** [comment]
Questie v4.1 does mark repeatable quests seperate.

**Comment by BreakBB** [comment]
This is fixed and will be included in the next update!
