### ISSUE TITLE
Map Icons not working

### ISSUE THREAD

**Issue by Schwank05** [AeroScripts/QuestieDev#1040]
Since the newest update the Map no longer shows Quest locations or objectives on the Map.

**Comment by BreakBB** [comment]
We need more information to help you. That is what the issue template you've removed is for.

Do you have multiple versions of Questie listed in "Addons"?
Did you update to Questie v4.1.1?
Did you check your config window if the checkboxes are enabled?

**Comment by BreakBB** [comment]
@Schwank05 Any news on this?

**Comment by Muehe** [comment]
Assumed solved, please create a new issue if you still have problems.
