### ISSUE TITLE
Gaffer Jacks in Darkshore missing

### ISSUE THREAD

**Issue by cloudbells** [AeroScripts/QuestieDev#1041]
## Description
Quest does not appear to be in the database as it does not show as as a ! and no markers for where to get the objectives show up on the map either. (Haven't tested if ? shows up when it's complete however.)

## Wowhead link
https://classic.wowhead.com/quest=1579/gaffer-jacks
This quest requires Fishing 30 apparently (varying accounts). I was able to pick it up with 68/150 fishing at lvl 60.

## Screenshots
_Quest available but not on minimap_
![Quest available but not on minimap](https://user-images.githubusercontent.com/17762911/65151927-510e9280-da27-11e9-9c30-ac1347fb0046.png)
_Quest also not showing on map_
![Quest also not showing on map](https://user-images.githubusercontent.com/17762911/65151973-608ddb80-da27-11e9-9c6c-ac313daf99b2.png)

## Questie version
4.1.0

**Comment by cloudbells** [comment]
I got the quest done relatively quickly at 36.7, 42.8.

The followup quest [Electropellers ](https://classic.wowhead.com/quest=1580/electropellers) also does not appear to be in the database.

**Comment by cloudbells** [comment]
Apparently it was in the database in 4.1.0 but it was still not showing up for me, even though I am showing all quests below level range.

**Comment by BreakBB** [comment]
We blacklisted all profession quests till 4.1.1 since we didn't check a player profession. This changed with 4.1.1 so all those quests should show up correctly.
