### ISSUE TITLE
missing reclaimed-treasures

### ISSUE THREAD

**Issue by xnilagor** [AeroScripts/QuestieDev#1042]
## Description
missing quest https://classic.wowhead.com/quest=2342/reclaimed-treasures on map/minimap

version 4.11 beta

**Comment by BreakBB** [comment]
Could you explain what exactly isn't/wasn't showing on the map? The quest itself or the objective?

**Comment by xnilagor** [comment]
The quest itself.

**Comment by BreakBB** [comment]
Did you know what level you had when encountering this quest? I just found out that this quest can be accepted with level 33, but is actually a level 43 quest. So with the default settings of "show quests 5 level above my own" this won't be shown

**Comment by BreakBB** [comment]
@xnilagor Any news on this?

**Comment by xnilagor** [comment]
I can not remember the level exactly. Maybe 39-41. I had the settings at +7 levels. Questie showed me the quest later when I was about 43/44.

**Comment by BreakBB** [comment]
I was finally able to test this and the quest is showing as expected.
