### ISSUE TITLE
Quest: An Imp's Request #8419

### ISSUE THREAD

**Issue by Nimbix-wow** [AeroScripts/QuestieDev#1044]
## Description

It showing as available but it wont be in game untill phase 3.

## Wowhead link

https://classic.wowhead.com/quest=8419/an-imps-request

## Screenshots

![2019-09-18 (3)](https://user-images.githubusercontent.com/46905100/65161266-8de28580-da37-11e9-8915-0701a5ccd729.png)

## Questie version

v4.1

**Comment by BreakBB** [comment]
Fixed with 21d045c6faf6deff995d4a3c68e190ab705f3509
