### ISSUE TITLE
Look To The Stars (Duskwood) multiple spawns ?

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#1047]
## Description

For said quest the addon objective marker is not where i have seen him spawn twice already, i saw him in the middle chamber on a raised stone about 35-80 once you enter the cave, and others also reported the back chamber around 36-84, so or he has 3 possible spawn locations where he randomly appears or blizz likes to change with patches :p

## Wowhead link

Quest: https://classic.wowhead.com/quest=181/look-to-the-stars#see-also 

NPC: https://classic.wowhead.com/npc=300/zzarc-vul#drops 

## Screenshots

forgot to make one :(

## Questie version

v4.1.1

**Comment by BreakBB** [comment]
Thanks for your report! I added two possible spawns :)
