### ISSUE TITLE
[14] As the Water Cascades

### ISSUE THREAD

**Issue by rheaumep** [AeroScripts/QuestieDev#1049]
Once I filled the moonwell water tube at the auberdine moonwell. The questie location did not change to the next step "investigate the red crystal along darkshores eastern mountain wall". Nor did Questie mark the "moonwell water tube 0/1" as "moonwell water tube 1/1" once filled.

## Wowhead link
 https://classic.wowhead.com/quest=4812/as-water-cascades

## Questie version
 V.4.1.1

**Comment by BreakBB** [comment]
Just to make sure: The objectives were shown correctly on the map, but the tracker and Questie in general didn't update correctly, yes?

**Comment by BreakBB** [comment]
@rheaumep Any news on this?

**Comment by BreakBB** [comment]
Assuming this is fixed
