### ISSUE TITLE
Quest "A Good Friend" in Shadowglen not being shown.

### ISSUE THREAD

**Issue by shapeless79** [AeroScripts/QuestieDev#1050]
## Description
In Shadowglen the quest "A Good Friend" from NPC Dirania Silvershine is not being shown by Questie.

## Wowhead link
https://classic.wowhead.com/quest=4495/a-good-friend

## Screenshots
![WoWScrnShot_091819_202105](https://user-images.githubusercontent.com/55509937/65177541-2805f600-da57-11e9-9fd2-e9258e55b458.jpg)

## Questie version
V4.1.1

**Comment by BreakBB** [comment]
Sorry for the late response, but I can't find any issue in our data. Did you try `/reload` and are you sure it's 4.1.1 you're using?

**Comment by BreakBB** [comment]
I just leveled a nightelf to level 2 without doing any quest and A Good Friend showed up on the map. So this is working on the latest master commit and will be fixed with the next release
