### ISSUE TITLE
CallbackHandler-1.0 error

### ISSUE THREAD

**Issue by Praws** [AeroScripts/QuestieDev#1051]
## Bug description
The moment I log in my character on nighthaven I get an error msg saying something about an unexpected symbol and when I checked the log file I see this:
9/18 22:12:21.005  Loading add-on Questie
9/18 22:12:21.005  ** Loading table of contents Interface\AddOns\Questie\Questie.toc
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\embeds.xml
9/18 22:12:21.005  Error loading Libs\LibStub\LibStub.lua
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.xml
9/18 22:12:21.005  ...nterface\AddOns\Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: unexpected symbol near `...'
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:101: unexpected symbol near `...'
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: unexpected symbol near `...'
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua:41: unexpected symbol near `...'
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceDB-3.0\AceDB-3.0.xml
9/18 22:12:21.005  ...nterface\AddOns\Questie\Libs\AceDB-3.0\AceDB-3.0.lua:45: attempt to index global `LibStub' (a nil value)
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceLocale-3.0\AceLocale-3.0.xml
9/18 22:12:21.005  ...\AddOns\Questie\Libs\AceLocale-3.0\AceLocale-3.0.lua:7: attempt to index global `LibStub' (a nil value)
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceConsole-3.0\AceConsole-3.0.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Libs\AceConsole-3.0\AceConsole-3.0.lua:43: unexpected symbol near `...'
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceGUI-3.0\AceGUI-3.0.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Libs\AceGUI-3.0\AceGUI-3.0.lua:101: unexpected symbol near `...'
9/18 22:12:21.005  Error loading widgets\AceGUIContainer-BlizOptionsGroup.lua
9/18 22:12:21.005  Error loading widgets\AceGUIContainer-DropDownGroup.lua
9/18 22:12:21.005  Error loading widgets\AceGUIContainer-Frame.lua
9/18 22:12:21.005  Error loading widgets\AceGUIContainer-InlineGroup.lua
9/18 22:12:21.005  Error loading widgets\AceGUIContainer-ScrollFrame.lua
9/18 22:12:21.005  Error loading widgets\AceGUIContainer-SimpleGroup.lua
9/18 22:12:21.005  Error loading widgets\AceGUIContainer-TabGroup.lua
9/18 22:12:21.005  Error loading widgets\AceGUIContainer-TreeGroup.lua
9/18 22:12:21.005  Error loading widgets\AceGUIContainer-Window.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-Button.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-CheckBox.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-ColorPicker.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-DropDown.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-DropDown-Items.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-EditBox.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-Heading.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-Icon.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-InteractiveLabel.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-Keybinding.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-Label.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-MultiLineEditBox.lua
9/18 22:12:21.005  Error loading widgets\AceGUIWidget-Slider.lua
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceConfigQuestie-3.0\AceConfig-3.0.xml
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceConfigQuestie-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.xml
9/18 22:12:21.005  ...ibs\AceConfigQuestie-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:47: unexpected symbol near `...'
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceConfigQuestie-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.xml
9/18 22:12:21.005  ...\Questie\Libs\AceConfigQuestie-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:67: unexpected symbol near `...'
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceConfigQuestie-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.xml
9/18 22:12:21.005  ...ie\Libs\AceConfigQuestie-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:80: unexpected symbol near `...'
9/18 22:12:21.005  ...\Questie\Libs\AceConfigQuestie-3.0\AceConfig-3.0.lua:15: attempt to call global `LibStub' (a nil value)
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceComm-3.0\AceComm-3.0.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Libs\AceComm-3.0\ChatThrottleLib.lua:213: unexpected symbol near `...'
9/18 22:12:21.005  Interface\AddOns\Questie\Libs\AceComm-3.0\AceComm-3.0.lua:65: unexpected symbol near `#'
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\AceSerializer-3.0\AceSerializer-3.0.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:125: unexpected symbol near `...'
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\LibUIDropDownMenuQuestie\LibUIDropDownMenu.xml
9/18 22:12:21.005  ...\Libs\LibUIDropDownMenuQuestie\LibUIDropDownMenu.lua:16: attempt to index a string value
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Libs\LibUIDropDownMenuQuestie\LibUIDropDownMenuTemplates.xml
9/18 22:12:21.005  ...UIDropDownMenuQuestie\LibUIDropDownMenuTemplates.lua:8: attempt to index a string value
9/18 22:12:21.005  Interface\AddOns\Questie\Libs\LibUIDropDownMenuQuestie\LibEasyMenu.lua:39: unexpected symbol near `#'
9/18 22:12:21.005  ...AddOns\Questie\Libs\LibUIDropDownMenuQuestie\AceGUIWidget-LQDropDown.lua:21: unexpected symbol near `...'
9/18 22:12:21.005  Error loading Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua
9/18 22:12:21.005  Error loading Libs\LibCompress\LibCompress.lua
9/18 22:12:21.005  Error loading Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua
9/18 22:12:21.005  Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-2.0.lua:144: unexpected symbol near `#'
9/18 22:12:21.005  Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:483: unexpected symbol near `...'
9/18 22:12:21.005  Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Migrate.lua:46: `)' expected near `'Pins-2.0.lua
9/18 22:12:21.005  Interface\AddOns\Questie\Modules\QuestieStream.lua:114: unexpected symbol near `...'
9/18 22:12:21.005  Interface\AddOns\Questie\Database\QuestieDB.lua:1: unexpected symbol near `...'
9/18 22:12:21.005  Interface\AddOns\Questie\Database\questDB.lua:36: attempt to index global `QuestieDB' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Database\objectDB.lua:7: attempt to index global `QuestieDB' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Database\spawnDB.lua:15: attempt to index global `QuestieDB' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Database\zoneDB.lua:2: unexpected symbol near `...'
9/18 22:12:21.005  Interface\AddOns\Questie\Database\corrections.lua:27: attempt to index global `QuestieDB' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Database\itemDB.lua:8: attempt to index global `QuestieDB' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\QuestieLocale.lua:53: unexpected symbol near `...'
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Locale\enUS\locale.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\enUS\config.lua:1: attempt to index global `QuestieLocale' (a nil value)
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Locale\esES\locale.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\esES\config.lua:1: attempt to index global `QuestieLocale' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\esES\lookupNpcs.lua:7416: attempt to index global `LangNameLookup' (a nil value)
9/18 22:12:21.005  ...nterface\AddOns\Questie\Locale\esES\lookupQuests.lua:4165: attempt to index global `LangQuestLookup' (a nil value)
9/18 22:12:21.005  ...terface\AddOns\Questie\Locale\esES\lookupObjects.lua:724: attempt to index global `LangObjectLookup' (a nil value)
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Locale\deDE\locale.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\deDE\config.lua:1: attempt to index global `QuestieLocale' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\deDE\lookupNpcs.lua:7416: attempt to index global `LangNameLookup' (a nil value)
9/18 22:12:21.005  ...nterface\AddOns\Questie\Locale\deDE\lookupQuests.lua:4165: attempt to index global `LangQuestLookup' (a nil value)
9/18 22:12:21.005  ...terface\AddOns\Questie\Locale\deDE\lookupObjects.lua:959: attempt to index global `LangObjectLookup' (a nil value)
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Locale\zhCN\locale.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\zhCN\config.lua:1: attempt to index global `QuestieLocale' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\zhCN\lookupNpcs.lua:7416: attempt to index global `LangNameLookup' (a nil value)
9/18 22:12:21.005  ...nterface\AddOns\Questie\Locale\zhCN\lookupQuests.lua:4165: attempt to index global `LangQuestLookup' (a nil value)
9/18 22:12:21.005  ...terface\AddOns\Questie\Locale\zhCN\lookupObjects.lua:64: attempt to index global `LangObjectLookup' (a nil value)
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Locale\zhTW\locale.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\zhTW\config.lua:1: attempt to index global `QuestieLocale' (a nil value)
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Locale\frFR\locale.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\frFR\config.lua:1: attempt to index global `QuestieLocale' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\frFR\lookupNpcs.lua:7416: attempt to index global `LangNameLookup' (a nil value)
9/18 22:12:21.005  ...nterface\AddOns\Questie\Locale\frFR\lookupQuests.lua:4165: attempt to index global `LangQuestLookup' (a nil value)
9/18 22:12:21.005  ...terface\AddOns\Questie\Locale\frFR\lookupObjects.lua:986: attempt to index global `LangObjectLookup' (a nil value)
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Locale\koKR\locale.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\koKR\config.lua:1: attempt to index global `QuestieLocale' (a nil value)
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Locale\ptBR\locale.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\ptBR\config.lua:1: attempt to index global `QuestieLocale' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\ptBR\lookupNpcs.lua:7416: attempt to index global `LangNameLookup' (a nil value)
9/18 22:12:21.005  ...nterface\AddOns\Questie\Locale\ptBR\lookupQuests.lua:4165: attempt to index global `LangQuestLookup' (a nil value)
9/18 22:12:21.005  ...terface\AddOns\Questie\Locale\ptBR\lookupObjects.lua:498: attempt to index global `LangObjectLookup' (a nil value)
9/18 22:12:21.005  ++ Loading file Interface\AddOns\Questie\Locale\ruRU\locale.xml
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\ruRU\config.lua:1: attempt to index global `QuestieLocale' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Locale\ruRU\lookupNpcs.lua:7416: attempt to index global `LangNameLookup' (a nil value)
9/18 22:12:21.005  ...nterface\AddOns\Questie\Locale\ruRU\lookupQuests.lua:4165: attempt to index global `LangQuestLookup' (a nil value)
9/18 22:12:21.005  ...terface\AddOns\Questie\Locale\ruRU\lookupObjects.lua:1080: attempt to index global `LangObjectLookup' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Modules\QuestieTooltips.lua:184: attempt to call method `HookScript' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Modules\QuestieFramePool.lua:1: unexpected symbol near `...'
9/18 22:12:21.005  Interface\AddOns\Questie\Modules\QuestieMap.lua:1: unexpected symbol near `...'
9/18 22:12:21.005  Interface\AddOns\Questie\Modules\QuestieQuest.lua:1: unexpected symbol near `...'
9/18 22:12:21.005  Interface\AddOns\Questie\Modules\QuestieCoordinates.lua:11: unexpected symbol near `#'
9/18 22:12:21.005  Interface\AddOns\Questie\Modules\QuestieJourney.lua:209: unexpected symbol near `#'
9/18 22:12:21.005  Interface\AddOns\Questie\Modules\QuestieComms.lua:344: attempt to index global `QuestieStreamLib' (a nil value)
9/18 22:12:21.005  Interface\AddOns\Questie\Modules\QuestieTracker.lua:804: unexpected symbol near `#'
9/18 22:12:21.005  Interface\AddOns\Questie\Modules\QuestieProfessions.lua:1: unexpected symbol near `...'
9/18 22:12:21.005  Interface\AddOns\Questie\Questie.lua:3: unexpected symbol near `...'

## Questie version
 Version 4.1.1

**Comment by BreakBB** [comment]
Did you restart WoW completely? And could you disable all other addons and try again?

**Comment by Praws** [comment]
I have already tried that and I still got the same error, the log I sent here is the latest one I got after I restarted wow and had only questie active

**Comment by BreakBB** [comment]
Have to tried to delete the Questie folder and grab a fresh copy?

**Comment by Praws** [comment]
true I didn't try that, I'll do it tomorrow and tell you if anything's changed or not

**Comment by BreakBB** [comment]
Perfekt, looking forward to it and hope that it fixes this issue :pray:

**Comment by Praws** [comment]
Sry for the delay but I trued a clean install out and nothing changed, I still got the same error

**Comment by Praws** [comment]
the thing is it says that questie is out of date, which was something it didn't say before

**Comment by Praws** [comment]
the wow server is at v 1.2.1 I think so maybe questie 4.1.1 is for a newer or older version???

**Comment by BreakBB** [comment]
Ohhhhh!

You're not on Classic but on a private server?

**Comment by BreakBB** [comment]
For server on 1.12 you have to use a totally different version. https://github.com/AeroScripts/QuestieDev/releases/download/v3.7.1/Questie-v3.7.1.zip

We're not actively supporting other versions than Classic anymore so that version is most likely the last one for 1.12

**Comment by Praws** [comment]
ohhh ok ty 
<3

**Comment by BreakBB** [comment]
Let me.know if this fixed your issue or simlly close this issue if it does :)

**Comment by Praws** [comment]
It fixxed the issue ty<3
