### ISSUE TITLE
My journey (Hidden Quests)

### ISSUE THREAD

**Issue by Nimbix-wow** [AeroScripts/QuestieDev#1056]
## Description

Wishing for a seperate list that show quests that I have hidden from the map. So I can unhide them with ease. Unhiding quests is from what I can tell not an option.

**Comment by BreakBB** [comment]
You currently can only use the search function of your journey to unhide quests. You go to search, enter the name/ID of the quest and uncheck "Hide by user".

I agree that this is far from perfect and having a separate tab with all hidden quests is a good suggestion :+1:

**Comment by Nimbix-wow** [comment]
After I've hidden a quest with the "Hide by user" option, then go back again to unhide it the checkbox is empty. Maybe a bug, but for me its hidden without the option to show it again.

**Comment by Muehe** [comment]
Hide by user is fixed on master, see #1000

**Comment by AeroScripts** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.
