### ISSUE TITLE
Quest #3741 Shows as available for Horde

### ISSUE THREAD

**Issue by Nimbix-wow** [AeroScripts/QuestieDev#1057]
## Description

The quest Hilary's Necklace shows as being available for Horde players.

## Wowhead link

https://classicdb.ch/?quest=3741

## Questie version

v4.1.1 Beta

**Comment by BreakBB** [comment]
Duplicate of #840 Comments on Wowhead state that this quest is indeed available as a Horde player. Can you prove the opposite @Nimbix-wow ? It would be great to clarify this!
