### ISSUE TITLE
Quest #6282 - Harpies Threaten

### ISSUE THREAD

**Issue by wow-classic** [AeroScripts/QuestieDev#1063]
## Description
"Harpies Threaten" show only marker for one type of harpy. And one type of harpy shows a tooltip for 4 types, but the other 3 types do not show a tooltip.
(In the Russian version. Сan’t see the non-Russian version)

## Wowhead link
https://classic.wowhead.com/quest=6282/harpies-threaten

## Questie version
4.1.1 BETA

**Comment by BreakBB** [comment]
Merging this with #1071
