### ISSUE TITLE
A Grim Task (Wetlands) multiple spawns

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#1064]
## Description

Balgaras the Foul has multiple spawn points and in a couple of days i have always seen him in Dun Modr by the "Tavern" on the left after you enter the town and the "Forge room" in the middle up the small hill instead of the tents Questie is showing us, might be worth adding/changing more icons ;)

## Wowhead link

Quest: https://classic.wowhead.com/quest=304/a-grim-task
NPC: https://classic.wowhead.com/npc=1364/balgaras-the-foul#comments

## Screenshots

none

## Questie version

v4.1.1

**Comment by puschie286** [comment]
can confirm that - https://classic.wowhead.com/npc=1364/balgaras-the-foul#comments:id=24703:reply=2930
he always respawn on a different location than he die
