### ISSUE TITLE
Steelsnap not showing up on the minimap

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1065]
Title says it all really.

https://classic.wowhead.com/quest=1131/steelsnap

![WoWScrnShot_091919_214631](https://user-images.githubusercontent.com/54936174/65276044-3f141900-db27-11e9-8154-97e854d701d2.jpg)

Questie 4.1.1

**Comment by Cerby3BR** [comment]
I should probably mention it also doesn't show up on the map.

**Comment by BreakBB** [comment]
Which Questie version?

**Comment by Cerby3BR** [comment]
4.1.1

**Comment by BreakBB** [comment]
Could you check `IsQuestFlaggedCompleted(1130)`?

**Comment by Cerby3BR** [comment]
I have indeed not completed Melor Sends Word. Looks like the breadcrumb isn't necessary.

**Comment by BreakBB** [comment]
Thanks for the information! It will be an easy fix then 👍
