### ISSUE TITLE
Missing cloth donation quests

### ISSUE THREAD

**Issue by ssateneth** [AeroScripts/QuestieDev#1066]
## Description

I haven't seen any of the Donation of <cloth> quests for alliance. Are these implemented?

## Wowhead link

Too many to list.
https://classic.wowhead.com/quest=7807/a-donation-of-wool

## Questie version

4.1.1

**Comment by effolkronium** [comment]
+

**Comment by BreakBB** [comment]
This has been fixed with fbd306bafae1b0a894337d8e2c39892772d060d5 

Note that those quests are marked for level 60 so you might not see them early on even though you can potentially donate.

**Comment by kendinikertenkelebek** [comment]
I'm 12 level gnome and quest is here and don't marked by questie.

**Comment by drejjmit** [comment]
Requires level 12 but recommended level is 60. We can currently only show quests 10 levels above your current level. This is a special case and will most likely not be supported.
