### ISSUE TITLE
Searing Gorge Quest "Caught!"

### ISSUE THREAD

**Issue by TheRealKraggy** [AeroScripts/QuestieDev#1067]
## Bug description
Something of a trivial bug but I'm reporting it for completeness.

This quest requires you to kill 8 Dark Iron Dwarfs and collect 15 Silk Cloths.  It seems that Questie is expecting the cloth to be dropped from these mobs and correctly counts those that do but it isn't aware of any cloth you may acquire by other means, such as from one's bank.

## Questie version
4.1.1

**Comment by BreakBB** [comment]
Thanks for this report. You're right, this still is an issue and we're looking for a proper way to fix it. Merging it with #722 since the solution will be the same
