### ISSUE TITLE
Quest #1790 - The Symbol of Life

### ISSUE THREAD

**Issue by carsono311** [AeroScripts/QuestieDev#1068]
The only remaining issue I have seen with this quest/chain is that it is still shown in the "Quests by Zone" tab even though it is complete.  The quest is a repeatable, auto-complete quest that is only available when quest # 1786 is accepted and in-log.  Once quest # 1786 is complete, quest # 1790 is no longer available, completed or not.

https://classic.wowhead.com/quest=1790/the-symbol-of-life

![WoWScrnShot_091919_210808](https://user-images.githubusercontent.com/54785647/65293985-be531e00-db22-11e9-8ed1-e7948908a59e.jpg)

Originally noticed this in v4.1.0, but it is still present in v4.1.1.

Thanks for all the hard work!  Loving it!

**Comment by carsono311** [comment]
Also worth mentioning, it did correctly show as a blue exclamation, repeatable quest on the minimap while it was available to me.  It obviously shows as yellow in the "Quests by Zone" listing.  I am honestly not sure if that was changed or not, but just pointing that out as well.  Thanks again!

**Comment by BreakBB** [comment]
Thanks for your report on this! We haven't updated the journey to use that new repeatable data/logic yet so repeatable quests will still show up as available.
We will fix this in a future update!

**Comment by BreakBB** [comment]
Repeatable quests will now be shown in a separate list fc14f300bf84ae9dbff3055266849659f971091e
