### ISSUE TITLE
Weird behavior when clicking below the quest tracker

### ISSUE THREAD

**Issue by ShaunDreclin** [AeroScripts/QuestieDev#1069]
## Screenshots
https://i.imgur.com/wnDBUrG.gif (gif too big for github)

## Questie version
4.1.1

**Comment by BreakBB** [comment]
To make sure I understand your GIF correctly: You move the cursor out of the questlog, click once and when you move the cursor up and down you scroll the questlog?

I can't reproduce this issue... Could you check if it might be connected to another addon?

**Comment by ShaunDreclin** [comment]
Ah no I was constantly clicking while moving the mouse up and down.

**Comment by ShaunDreclin** [comment]
Just checked, it happens while questie is the only addon I have enabled. Figured out how to reproduce it, shift-click to track a bunch of quests and then do it again to untrack some of them (keep at least one tracked)

**Comment by ShaunDreclin** [comment]
Fixed as of 4.2.1
