### ISSUE TITLE
multiple q notes in npcs tooltip

### ISSUE THREAD

**Issue by nycter79** [AeroScripts/QuestieDev#107]
![image](https://cloud.githubusercontent.com/assets/10027713/7756390/2b87bdc6-fffb-11e4-80f5-54559085fa6c.png)

happens rarely

**Comment by Logonz** [comment]
Yeah, it has to do with how we try and support other tooltip mods... i have tried fixing it but it seems to happen sometimes anyways... Either we have to live with this potentially happening or we take over the tooltip and forsake other mods which i really don't wanna do
