### ISSUE TITLE
Quest Tracker missed quest trigger

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#1072]
## Bug description

i got a quest completed and the questie tracker did not register the event :) 

Quest: https://classic.wowhead.com/quest=921/crown-of-the-earth#see-also

## Screenshots

as you can clearly see i have it completed in the log but the tracker is still waiting for it and minimap icon is still on "acquiring"
  
https://imgur.com/eRO1jB5

## Questie version

v4.1.1

**Comment by BreakBB** [comment]
Did this happen for the other follow up quests as well?

**Comment by reaper666735** [comment]
no it only happened on that quest so far, all i can say is you needed to fill a phial @ the moonwell near shadowglen so might be a special trigger Questie did not see, or some random bug 

Empty phial: https://classic.wowhead.com/item=5185/crystal-phial
Filled phial : https://classic.wowhead.com/item=5184/filled-crystal-phial

**Comment by BreakBB** [comment]
Related to #1071
