### ISSUE TITLE
Quest #1147 - The Swarm Grows

### ISSUE THREAD

**Issue by wow-classic** [AeroScripts/QuestieDev#1073]
## Description
"The Swarm Grows" not show all markers and tooltips for all types.
And not show marker "?" for complete the quest.
(In the Russian version. Сan’t see the non-Russian version)

## Wowhead link
https://classic.wowhead.com/quest=1147/the-swarm-grows

## Screenshots
![WoWScrnShot_092019_214112](https://user-images.githubusercontent.com/55049724/65351336-7ef30300-dbf0-11e9-93bd-5a7acd26683a.png)

## Questie version
4.1.1 BETA

**Comment by BreakBB** [comment]
This is linked to #1071 Sorry for your issues :/
