### ISSUE TITLE
Quest #1175 - A Bump in the Road

### ISSUE THREAD

**Issue by wow-classic** [AeroScripts/QuestieDev#1074]
## Description
"A Bump in the Road" not show all markers and tooltips for all types.
(In the Russian version. Сan’t see the non-Russian version)

## Wowhead link
https://classic.wowhead.com/quest=1175/a-bump-in-the-road

## Screenshots
![WoWScrnShot_092019_212418](https://user-images.githubusercontent.com/55049724/65351650-4bfd3f00-dbf1-11e9-92d4-cefa3327d978.png)

## Questie version
4.1.1 BETA

**Comment by BreakBB** [comment]
Merging this with #1071
