### ISSUE TITLE
Add ability to move the quest timers window

### ISSUE THREAD

**Issue by ShaunDreclin** [AeroScripts/QuestieDev#1076]
## Description
Either having it individually movable or just added to the tracker would be good

**Comment by SpareSimian** [comment]
I ran into this today with the Hunters Challenge in Thelsamar. The first quest in the tracker is on top of the timer window for the quest. I think the timer is a built-in so it will require capturing it and embedding it in the list frame.

Meanwhile, is there a way to reposition the list? The config screen has a button to reset the position, suggesting that there's some super-secret way to move the whole tracker frame.

**Comment by ShaunDreclin** [comment]
You can hold ctrl to move it or right click and unlock it

**Comment by silverhawke249** [comment]
seconding this feature request, or at least make the questie tracker go under the quest timer.

**Comment by BreakBB** [comment]
In the next release the timer will be included somehow similar to this:

![image](https://user-images.githubusercontent.com/33514570/68254259-6d43ae80-002a-11ea-8312-5f6f394707ce.png)

It might be changed how exactly it is displayed though.
