### ISSUE TITLE
Quest Icon showing while Map is closed

### ISSUE THREAD

**Issue by bolerro** [AeroScripts/QuestieDev#1077]
## Bug description
When a new quest is accepted and is located in a different zone, the icon will show up on screen without the map open. Opening and closing the map will not remove the quest icon if you are not in the same zone as the quest.

Once you enter the zone that the quest is located in, you can open/close the map and the icon will disappear along with the closing of the map.

This appears to be a visibility trigger that isn't set correctly when the new quest has been accepted.

## Screenshots
Sorry, no screenshot available

## Questie version
v4.1.1

**Comment by BreakBB** [comment]
Have you tried to disable all other addons to check if this might be a conflict to another addon?

**Comment by BreakBB** [comment]
Also related to #631 I think

**Comment by bolerro** [comment]
I will be disabling all but questie today and report back. As for #631 , it's possible it is a similar issue, but I'm seeing it happen only when getting a new quest or when one shows up in another zone after handing in a quest. I haven't seen it happen when the map is open and then closed, but I will check that as well and report to #631 with my findings for that

**Comment by bolerro** [comment]
Ok, I determined this is actually being caused by Azeroth Autopilot addon. They are placing waypoints that are the same as the quest icons. They are aware of the issue on their end.
