### ISSUE TITLE
Galen's escape - says completed instead of failed

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1078]
## Description
I lost Galen along the way and he died, I failed the quest, but questie says I completed it

## Wowhead link
https://classic.wowhead.com/quest=1393/galens-escape

## Screenshots
![](https://i.imgur.com/GyzBQwu.jpg)

## Questie version
4.1.1

**Comment by Muehe** [comment]
Fixed by 1f6e17575531b51242a0346f827d69c8a3edbec8
