### ISSUE TITLE
Quest 'Simple Request' shows as available even if it's not.

### ISSUE THREAD

**Issue by istepanko** [AeroScripts/QuestieDev#1079]

**Comment by BreakBB** [comment]
And again, please fill in some details. It will help us to speed up the fix for your issue.

**Comment by xCharg** [comment]
According to top comment on wowhead https://classic.wowhead.com/quest=8233/a-simple-request#comments this quest simply does not exist in classic wow.

**Comment by BreakBB** [comment]
Fixed with 21d045c6faf6deff995d4a3c68e190ab705f3509
