### ISSUE TITLE
Quest 'Senir's Observations' shows in available for Horde but its alliance only

### ISSUE THREAD

**Issue by istepanko** [AeroScripts/QuestieDev#1080]

**Comment by BreakBB** [comment]
Thanks for the report, but filling in some details would really help us.

**Comment by BreakBB** [comment]
Both quests
https://classic.wowhead.com/quest=282
and
https://classic.wowhead.com/quest=420/senirs-observations

are marked for Alliance only on the current build. What version of Questie are you using?

**Comment by istepanko** [comment]
Hello, I am using latest version. But I think we are looking in different places. I see this quest in the list of 'Available quests' by zone. Here is a screenshot.
<img width="1048" alt="Screen Shot 2019-09-22 at 3 16 50 PM" src="https://user-images.githubusercontent.com/14187183/65395179-2a649a80-dd4c-11e9-8275-cfba3a4d2cd2.png">

**Comment by BreakBB** [comment]
Ohhh yeah. Okay I didn't look at the journey. That needs more logic to handle such cases. Nothing you can change about this atm :/

We haven't touched the journey in a long time but will soon! Thanks for your report :) We will keep you updated!

**Comment by BreakBB** [comment]
@istepanko Is this still an issue? I can't reproduce it with the latest version.

**Comment by BreakBB** [comment]
Assuming this is solved.
