### ISSUE TITLE
Add an option to ignore quest

### ISSUE THREAD

**Issue by xCharg** [AeroScripts/QuestieDev#1086]
## Description

Sometimes you don't want to see a specific quest or few of them because you're not going to do them anyways. But mark still appears on map and on a quick look it looks like location has tonns of quests, while they're all you've skipped.

An option to ignore quest (either by name or some kind of ID) would be great.

**Comment by BreakBB** [comment]
You can shift + leftclick the exclamation marks on the map to add a quest to your ignore list.
