### ISSUE TITLE
Quest sunken treasure - Quest Objects marker make quest harder to do

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1087]
## Description
The quest "sunken treasure" currently is harder to finish with questies icons enabled, because they overlay the important yellow circle of the quest.
Of course questie shows all spots where they can appear, but it doesn't show you if there currently is one of the stones availble if you get close to them.

Maybe you could combine the icons or highlight the cog/gear icon, when it is available.

Currently you're searching but don't find anything. You wouldn't see the yellow circle unless it is available.

## Wowhead link
https://classic.wowhead.com/quest=665/sunken-treasure

## Screenshots
Without questie icons:
![](https://i.imgur.com/C1xZP4K.jpg)
With questie icons:
![](https://i.imgur.com/osA2qeL.png)
You get these goggles, without them the yellow circles don't appear on the map.
![](https://i.imgur.com/A7v7ZCp.png)

## Questie version
4.1.1

**Comment by Gogo1951** [comment]
Hey @Djfe ,

Changing transparency would help, yeah?

https://github.com/AeroScripts/QuestieDev/issues/799#issuecomment-564583093

If so, can we close this issue?

**Comment by Djfe** [comment]
maybe, though people would need to know/assume by themselves, that the quest has it's own icons one the map that just aren't visible, when questie is in use.

the linked issue sounds like a general sliders (not a config based on a quest)

it might help more if questie does this on it's own (for this one quest, maybe there are others where it helps that I don't know of, yet.)

**Comment by Gogo1951** [comment]
I mean, if you want to write dynamic code that's going to adjust transparency based on quest... that's cool. (= But that sounds like a lot of work. Especially since we're really only talking about this one quest. I did this quest a few weeks back, and you can sort of see a yellow dot in the gear when the gem is there vs. not. It's not totally easy to spot, but after a few I got the hang of it.

**Comment by Djfe** [comment]
ups pressed that button accidentally.

anyways

I'm happy other people develop this mod.
I don't ask for this feature, I'm just happy providing feedback here :)
It's up to you devs to decide whether you want to implement a feature or not.
The thing is: the devs don't have time to play the full game so they rely on feedback from users.
therefore I report anything I notice that could be improved and let you decide. (might be a bit lazy, since I know how to code, but I don't have the time and rather play the game instead ^^)

**Comment by BreakBB** [comment]
For now the return of investment isn't really great for this issue. I encountered two quests having this "problem", but as already suggested you should reduce the transparency or simply disable Questie for these quests.

Thanks for all the feedback and ideas you provide @Djfe !
