### ISSUE TITLE
Quest #624 - Cortello's Riddle

### ISSUE THREAD

**Issue by bitingsock** [AeroScripts/QuestieDev#1089]
## Description
The item that starts the quest is not indicated on the map. I can spawn in several places among the Bloodsail Buccaneers ships.

## Wowhead link
https://classic.wowhead.com/object=2554/cortellos-riddle
https://classic.wowhead.com/quest=624/cortellos-riddle

## Screenshots
![image](https://user-images.githubusercontent.com/6302101/65368853-09406480-dbfb-11e9-9818-271f60ab45f5.png)
![image](https://user-images.githubusercontent.com/6302101/65368861-1d846180-dbfb-11e9-8c92-3f4f6eaea2ee.png)
![image](https://user-images.githubusercontent.com/6302101/65368876-4dcc0000-dbfb-11e9-98ad-246ab89ce713.png)
![image](https://user-images.githubusercontent.com/6302101/65368881-545a7780-dbfb-11e9-8959-575707577093.png)

## Questie version
v4.1.1beta

**Comment by Djfe** [comment]
I mentioned that on discord a couple days back.
Afaik there are loads of quests that are started by items that mobs can drop or lie around somewhere.
Marking all of them on the map (especially all mobs like defias) might be a bit over the top.

But there are probably ways around that (opt-in)

**Comment by bitingsock** [comment]
Similar problem to https://classic.wowhead.com/object=2560/half-buried-bottle that starts Message in A Bottle. Would light up the whole beach.

**Comment by Djfe** [comment]
Maybe color the area in which quest items are available (in red or something)
then place a marker somewhere on it (! or ?) but in a different color than blue or yellow to show it's an area quest

the area's color should be very slight (not disturbing)
obviously the area needs to be colored only slightly (opaque or with a texture that is dithered between a color and transparent)

**Comment by BreakBB** [comment]
Yes, we're still lacking the function to hint users about item drops which start a quest. We're very limited in time atm so adding features isn't easy.

Especially "drawing areas" is not a trivial task. And as already stated on Discord we obviously don't want to flood the map with icons.

As a first step we will most likely simply add the hint to the tooltip of a mob if can drop an item starting a quest.

For objects from which you can loot an item we've haven't found a similar "easy" solution.

It will be included in a future update though! :)

**Comment by BreakBB** [comment]
Related to #317

**Comment by BreakBB** [comment]
Merging with #317
