### ISSUE TITLE
The reward from "Theocritus' Retrieval" causes an error when moused over in the quest log

### ISSUE THREAD

**Issue by kennyj2369** [AeroScripts/QuestieDev#109]
The reward is [Restoring Balm] and when I run my cursor over it in the quest log, I get this error in my chat window:  

    Error occured while running hooks for: GameTooltip.SetQuestLogItem 
    Invalid quest item in SetQuestLogItem("type",index") 
    Call Chain: 
     (tail call): ? 
    [string "QuestLogItem1:OnEnter"]:4: in main chunk

I am using the latest -master release (I think) if that makes a difference.

**Comment by AeroScripts** [comment]
Are you using EQL3?

**Comment by Schaka** [comment]
I think it's not even an EQL3 problem, but rather that the quest has been patched on Nostalrius to have different rewards than it actually does in 1.12 - yet they didn't quite do it 100%, causing these issues.

**Comment by nycter79** [comment]
Also happens to me time to time, for various quest - rewards, not using EQL3 or any similar addon, playing on Kronos (no modified quests).

**Comment by kennyj2369** [comment]
I have Extended QuestLog 3.6.1 disabled and I am playing on Kronos. Are you implying EQL3 would fix the problem? Or were you trying to confirm it wasn't causing problems?

**Comment by AeroScripts** [comment]
The thing that confuses me though is "Error occured while running hooks for: GameTooltip.SetQuestLogItem" isn't something that questie it's self could generate. it doesn't contain anything that would print "Error occured while running hooks for"

Gotta figure out what's causing it

**Comment by Schaka** [comment]
Since I've seen that same message and I'm running Enchantrix and other tooltip addons - are you running some of these maybe?

**Comment by nycter79** [comment]
Yes - EnhTooltip, Enchantrix, Informant

**Comment by Schaka** [comment]
There you have it.

**Comment by AeroScripts** [comment]
Maybe I can add something in !QuestieCompat to fix these issues, going to do some testing
