### ISSUE TITLE
missing objective marker on mobs

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1091]
## Description
A bump in the road quest
Worth Its Weight in Gold
Two quests where not all affected mobs have markers

## Wowhead link
https://classic.wowhead.com/quest=1175/a-bump-in-the-road
https://classic.wowhead.com/quest=691/worth-its-weight-in-gold (clicking on the required items on wowhead -> gets you a list of required mobs that drop them)

## Screenshots
![](https://i.imgur.com/wn6CSKa.jpg)

## Questie version
4.1.1

**Comment by Djfe** [comment]
another one:
https://classic.wowhead.com/quest=1452/rhapsodys-kalimdor-kocktail
at least for (Grizzled) Ironfur Bears the markers are missing
![](https://i.imgur.com/HFcy6hp.jpg)

**Comment by Djfe** [comment]
another one:
https://classic.wowhead.com/quest=7729/job-opportunity-culling-the-competition#english-comments
Dark Iron Taskmaster don't have a marker/tracker, that shows that they are part of the quest "JOB OPPORTUNITY: Culling the Competition"

![](https://i.imgur.com/RN3ZrPZ.jpg)

**Comment by Djfe** [comment]
https://classic.wowhead.com/quest=3442/the-flawless-flame

At least inferno and blazing elementals aren't marked, maybe other mobs, too

blazing elemental is marked
![](https://i.imgur.com/q8KQauF.jpg)
Inferno isn't marked, magma elemental is
![](https://i.imgur.com/47nXfeD.jpg)

**Comment by Djfe** [comment]
https://classic.wowhead.com/quest=7728/stolen-smithing-tuyere-and-lookouts-spyglass
Dark Iron Lookout have a marker
![](https://i.imgur.com/lgul9OJ.jpg)

Dark Iron Steamsmith don't have a marker
![](https://i.imgur.com/6fOu3wG.jpg)

**Comment by Djfe** [comment]
The star, the hand and the heart:
Only heart has a marker so far
https://classic.wowhead.com/quest=735/the-star-the-hand-and-the-heart
star is in alterac:
![](https://i.imgur.com/f6gJ2MF.jpg)

the hand in theramore:
![](https://i.imgur.com/LilGRnr.jpg)

**Comment by BreakBB** [comment]
Thanks for those updates! Actually it is all connected to the same issue we have/had with Non-English clients.
On the master branch there is a fix for this and it will be included in the next release.

Merging this with #1071
