### ISSUE TITLE
"Defenders of Darrowshire" Not Appearing On Map

### ISSUE THREAD

**Issue by TheRealKraggy** [AeroScripts/QuestieDev#1092]
## Bug description
This quest is given by Carlin Redpath at Light's Hope and I can get it from him but it isn't marked on the map, unlike "Zaeldarr The Outcast" given by Caretaker Alen only a few feet away.

## Questie version
4.1.1

**Comment by BreakBB** [comment]
This has been reported in #983 and has been fixed, but not released yet. It will be included in the next release!
