### ISSUE TITLE
Mouse Flyover generates constant spam in the General Chat Window

### ISSUE THREAD

**Issue by ViciousBobKatts** [AeroScripts/QuestieDev#1096]
At numerous points (e.g. Mouse over a quest item in a bag, mouse over a beastie that *drops* a quest item, etc.) my General Chat window starts scrolling with item names - and Questie is doing it. When I reload without Questie enabled, no chat messages... re-enable and chat messages come back. I'm sure this has to be a toggle in the settings somewhere, but I can't find it...?

/dump QuestieGetVersionString() = 4.0.17

**Comment by BreakBB** [comment]
First of all: You should update your Questie versions :)

Secondly, you want to disable this checkbox:

![image](https://user-images.githubusercontent.com/33514570/65379233-22ade300-dcc5-11e9-9330-ddd2d706615c.png)

**Comment by ViciousBobKatts** [comment]
Debug is not on. What's the current Classic questie version?

**Comment by Kopo942** [comment]
You can find the latest version [here.](https://github.com/AeroScripts/QuestieDev/releases/latest) Also, remember to **restart** your game after updating the addon, /reload just causes more problems.

**Comment by BreakBB** [comment]
@ViciousBobKatts Is this fixed for you with the latest release?

**Comment by Muehe** [comment]
Assumed solved, please create a new issue if you still have problems.
