### ISSUE TITLE
Questie is deleting the global error() function!

### ISSUE THREAD

**Issue by ssateneth** [AeroScripts/QuestieDev#1098]
## Bug description

After a few seconds from loading UI, the error() function gets nil'd out. This is BAD and breaks a number of other addons I use that also use the error() function.

## Screenshots

![error](https://user-images.githubusercontent.com/2127021/65382139-33aa2480-dcc4-11e9-88b8-9bf770c579a0.png)

## Questie version

4.1.1 dev version edd4de0

**Comment by ssateneth** [comment]
seems your error has something to do with lines 1246 and 1257 in modules\questietracker.lua. you didn't localize them, they are global!

`    if Questie.db.char.TrackerLocation then
        -- we need to pcall this because it can error if something like MoveAnything is used to move the tracker
        result, error = pcall(frm.SetPoint, frm, unpack(Questie.db.char.TrackerLocation))
        if not result then
            Questie.db.char.TrackerLocation = nil
            print(QuestieLocale:GetUIString('TRACKER_INVALID_LOCATION'))
            result, error = pcall(frm.SetPoint, frm, unpack({QuestWatchFrame:GetPoint()}))
            if not result then
                Questie.db.char.TrackerLocation = nil
                frm:SetPoint("CENTER",0,0)
            end
        end
    else
        result, error = pcall(frm.SetPoint, frm, unpack({QuestWatchFrame:GetPoint()}))
        if not result then
            Questie.db.char.TrackerLocation = nil
            print(QuestieLocale:GetUIString('TRACKER_INVALID_LOCATION'))
            frm:SetPoint("CENTER",0,0)
        end
    end
`

**Comment by BreakBB** [comment]
Thanks for your report! You're correct that this is a really bad bug and a result of a bad code styling.
We've already fixed this issue on a different branch which we're testing currently. We want to get the changes together with quest fixes out very soon. Keep an eye out for 4.1.2

**Comment by AeroScripts** [comment]
Not code styling https://github.com/AeroScripts/QuestieDev/commit/76d679e0e88594764222bceb7f8c9679f56efc61#diff-f96cec2a70dc3e6b62b0e1b4cb445acd

a mistake
