### ISSUE TITLE
Quest title repeated in tooltip

### ISSUE THREAD

**Issue by kuletco** [AeroScripts/QuestieDev#1099]
## Bug description
When I move mouse point to a quest monster, the quest title is repeated, and objectives is different.

## Screenshots
![图片](https://user-images.githubusercontent.com/8363656/65382759-495c3000-dd3e-11e9-930b-83fecd1f108d.png)

## Questie version
Questie-master

**Comment by kuletco** [comment]
I fix this bug like this. Please check.
![图片](https://user-images.githubusercontent.com/8363656/65382807-0ea6c780-dd3f-11e9-81ad-c38cc13a24d5.png)

**Comment by h671g** [comment]
Thank you, I resolved my issue https://github.com/AeroScripts/QuestieDev/issues/861 with this

**Comment by Eveigh** [comment]
Works for me too.

**Comment by BreakBB** [comment]
Merging this with #1071
