### ISSUE TITLE
Multiple quests with the same name can point to the wrong finisher

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#11]
If there are multiple quests with the same name, it's possible they might point to the wrong finisher. This is because the quest finishers are done using a name-based lookup. This doesn't affect objectives, but ideally things should be changed to use the quest id.

**Comment by abennette32** [comment]
Definitely should be using the Quest ID, as there are TONS of quests with the same name in Vanilla, especially in neutral zones and end-game areas.

**Comment by AeroScripts** [comment]
Yeah, only thing is unfortunately there's no way to get the quest ID in vanilla. I've come up with a hash system that uses the quest name, quest level, and quest objective text that should fix this, it should be implemented fairly soon.

**Comment by AeroScripts** [comment]
Hopefully fixed after afd23aa83e7352de2ded37378533465d17138356
