### ISSUE TITLE
Attempt to index a nil value in function 'IsDoable'

### ISSUE THREAD

**Issue by kuletco** [AeroScripts/QuestieDev#1100]
## Bug description
1x Questie\Modules\QuestieQuest.lua:1180: attempt to index a nil value
Questie\Modules\QuestieQuest.lua:1180: in function `IsDoable'
Questie\Modules\QuestieQuest.lua:1240: in function `CalculateAvailableQuests'
...rfaceQuestie\Modules\QuestieEventHandler.lua:88: in function <...rfaceQuestie\Modules\QuestieEventHandler.lua:83>

Locals:
self = <table> {
 1 = "Questie"
 2 = <table> {
 }
 IsDoable = <function> defined @Questie\Modules\QuestieQuest.lua:1146
 DrawAvailableQuest = <function> defined @Questie\Modules\QuestieQuest.lua:1025
 CheckExclusivity = <function> defined @Questie\Modules\QuestieQuest.lua:1218
 GetLeaderBoardDetails = <function> defined @Questie\Modules\QuestieQuest.lua:995
}
questObject = <table> {
 Description = "和克兰诺克·马克雷德谈一谈。"
 startedBy = <table> {
 }
 ObjectiveData = <table> {
 }
 HiddenObjectiveData = <table> {
 }
 NextQuestInChain = 1719
 RequiredRaces = 0
 Sort = 81
 Ends = <table> {
 }
 questFlags = 8
 Level = 30
 ObjectiveText = <table> {
 }
 nextQuestInChain = 1719
 requiredRaces = 0
 RequiredClasses = 1
 Finisher = <table> {
 }
 GetColoredQuestName = <function> defined @Questie\Database\QuestieDB.lua:139
 Id = 1718
 MinLevel = 30
 requiredClasses = 1
 questLevel = 30
 finishedBy = <table> {
 }
 Starts = <table> {
 }
 Name = "岛民"
 objectivesText = <table> {
 }
 requiredLevel = 30
 name = "The Islander"
 zoneOrSort = -81
 objectives = <table> {
 }
}
allFinished = true
hasValidNPC = false
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
}
(for control) = 1
_ = 1
id = <table> {
 1 = 3041
 2 = 3354
 3 = 4595
 4 = 5113
 5 = 5479
}
(*temporary) = nil
(*temporary) = <table> {
 1 = "Questie"
 2 = <table> {
 }
 FactionGroup = "Alliance"
 _NPCCache = <table> {
 }
 GetQuestsByName = <function> defined @Questie\Database\QuestieDB.lua:477
 _ZoneCache = <table> {
 }
 questKeys = <table> {
 }
 _GetSpecialNPC = <function> defined @Questie\Database\QuestieDB.lua:395
 Levenshtein = <function> defined @Questie\Database\QuestieDB.lua:573
 itemKeys = <table> {
 }
 npcKeys = <table> {
 }
 GetQuestsByZoneId = <function> defined @Questie\Database\QuestieDB.lua:520
 npcData = <table> {
 }
 objectData = <table> {
 }
 objectKeys = <table> {
 }
 deleteClasses = <function> defined @Questie\Database\QuestieDB.lua:656
 itemData = <table> {
 }
 deleteGatheringNodes = <function> defined @Questie\Database\QuestieDB.lua:611
 questData = <table> {
 }
 GetNPC = <function> defined @Questie\Database\QuestieDB.lua:428
 GetNPCsByName = <function> defined @Questie\Database\QuestieDB.lua:500
 ItemLookup = <function> defined @Questie\Database\QuestieDB.lua:67
 GetObject = <function> defined @Questie\Database\QuestieDB.lua:76
 _ObjectCache = <table> {
 }
 Initialize = <function> defined @Questie\Database\QuestieDB.lua:54
 GetQuest = <function> defined @Questie\Database\QuestieDB.lua:143
 _ItemCache = <table> {
 }
 GetItem = <function> defined @Questie\Database\QuestieDB.lua:108
 _QuestCache = <table> {
 }
}
(*temporary) = <table> {
 1 = 3041
 2 = 3354
 3 = 4595
 4 = 5113
 5 = 5479
}
(*temporary) = "attempt to index a nil value"

## Screenshots
![图片](https://user-images.githubusercontent.com/8363656/65382843-87a61f00-dd3f-11e9-8c1e-6808de9e2e14.png)

## Questie version
Questie-master

**Comment by kuletco** [comment]
I add a nil check, please check the code.
![图片](https://user-images.githubusercontent.com/8363656/65382920-1e72db80-dd40-11e9-880e-df6cdaf58cf3.png)

**Comment by BreakBB** [comment]
I made a bad correction and therefore a table was used instead of a number. If we would add a `nil` check it would be harder to recognize such issues. Thanks for your report though :)

**Comment by kuletco** [comment]
> 
> 
> I made a bad correction and therefore a table was used instead of a number. If we would add a `nil` check it would be harder to recognize such issues. Thanks for your report though :)

Waiting your fix :)
