### ISSUE TITLE
Quest tracker blocking ESC while using wide questlog.

### ISSUE THREAD

**Issue by Dajova** [AeroScripts/QuestieDev#1103]
Clicking on a quest in the quest tracker (so the questlog opens up) seems to break the ESC button when using a wide quest log mod (tried with both Wide Quest Log and Enhanced Quest Log option in Leatrix Plus). 
Meaning that you cant press ESC to exit the window and you have to either press the keybind for the questlog itself or manually press the X button.

Here's a video i made that shows how it looks like: [Here](https://streamable.com/0p9xf)

**Comment by BreakBB** [comment]
Merging this with #1033
