### ISSUE TITLE
An option to hide ALL repeatable quests from both the map AND the log

### ISSUE THREAD

**Issue by Gldpittol** [AeroScripts/QuestieDev#1105]
Basically what's in the title. As a completionist, it kinda bugs me to check the log, go to Elwynn forest and see "51/52 quests completed", because I'm missing that one repeatable quest everytime the addon is reloaded. It's also annoying to have to hide every blue quest mark from the log one by one, and having them still appearing on the log.

**Comment by BreakBB** [comment]
@Gldpittol Sorry for taking to long. Bugs had a higher priority than feature requests.

So in the mean time we've already updated the Journey to group the quests in more than just "completed" and "available".
Moreover you can now disable to show repeatable quests in the Config!
