### ISSUE TITLE
'The Hunter's Way' quest shown for all classes (should be hunters only)

### ISSUE THREAD

**Issue by istepanko** [AeroScripts/QuestieDev#1109]

**Comment by BreakBB** [comment]
According to Wowhead [The Hunter's Way](https://classic.wowhead.com/quest=861/the-hunters-way) the quest is for every class and not just hunters. I think you're mistaken it to "The Hunter's Path" which is the level 10 pet taming quest.

**Comment by istepanko** [comment]
However, I completed all quests in Mulgore but this one is not available for pickup. Also in the comments on wowhead you can see that a lot of people are hunters. I think this is a mistake on wowhead.

**Comment by Cerby3BR** [comment]
No, I completed The Hunter's Way as a druid. We are talking about the quest where you "bring 4 Flatland Prowler Claws to Melor Stonehoof in Thunder Bluff", right?

**Comment by BreakBB** [comment]
@Cerby3BR Yes, that is "The Hunter's Way".

@istepanko Mayebe the quest doesn't show up for you on the map because your level is too high now? Or have you been at the NPC to check?

**Comment by istepanko** [comment]
<img width="343" alt="Screen Shot 2019-09-23 at 12 08 58 PM" src="https://user-images.githubusercontent.com/14187183/65455133-715d9900-ddfb-11e9-9384-e60a67771097.png">
![Uploading Screen Shot 2019-09-23 at 12.09.15 PM.png…]()

**Comment by istepanko** [comment]
<img width="343" alt="Screen Shot 2019-09-23 at 12 08 58 PM" src="https://user-images.githubusercontent.com/14187183/65455169-85a19600-ddfb-11e9-998d-6585b2a22b38.png">
<img width="1232" alt="Screen Shot 2019-09-23 at 12 09 15 PM" src="https://user-images.githubusercontent.com/14187183/65455179-8d613a80-ddfb-11e9-9738-2f384b1012fc.png">

<img width="500" alt="Screen Shot 2019-09-23 at 12 13 41 PM" src="https://user-images.githubusercontent.com/14187183/65455203-9a7e2980-ddfb-11e9-88e9-be146f447d86.png">

**Comment by EMcCormack** [comment]
Please see comment here: https://classic.wowhead.com/quest=861/the-hunters-way
By Taijitu (1,665 –  4·18)  25 days ago (Classic) 
This quest appears to be Tauren-only (or at least unavailable to Undead).

This quest is considered an optional preqrequisite to Sergra Darkthorn and therefore you cannot see this quest if you have started that, Plainstrider Menace, or any other part of that quest line. Abandoning Plainstrider Menace quest will make this one available.

**The issue appears to be that if you have any quests in the Serga Darkthorn line, then you cannot claim this one. If you've completed the Serga Darkthorn line, you cannot claim this quest.**

**Comment by BreakBB** [comment]
@EMcCormack Thanks for looking into this! Fix was easy with this information
