### ISSUE TITLE
Error "Cannot destroy note "659309" at "Loch Modan" if it does not exist

### ISSUE THREAD

**Issue by littlemadness** [AeroScripts/QuestieDev#111]
Please help every time I use questie and open up my quest log Error "Cannot destroy note "659309" at "Loch Modan" if it does not exist this is in a vanilla server 1.12.1 please help.

**Comment by Schaka** [comment]
We do not support Questie 1.0 anymore. Please update to 2.0.

If you don't want to update, please go to your WTF folder and clear all Questie and Cartographer files
