### ISSUE TITLE
Having many quests accepted decreases FPS substantially

### ISSUE THREAD

**Issue by brndd** [AeroScripts/QuestieDev#1111]
## Bug description

Having Questie running with many tracked quests causes significant FPS loss. I have noticed this problem in both Westfall and Lakeshire with most of the available quests accepted. In Westfall my FPS was decreased by half.

For the record other quest tracking addons like ClassicCodex do not have such FPS issues.

## Screenshots

**Questie disabled: 176 FPS**

![WoWScrnShot_092319_023804](https://user-images.githubusercontent.com/5822375/65396141-c40f6480-ddab-11e9-86e2-f0e582824bc3.jpg)

**Questie enabled: 128 FPS**

![WoWScrnShot_092319_023835](https://user-images.githubusercontent.com/5822375/65396148-cffb2680-ddab-11e9-93c6-75e58e2ea835.jpg)

**View of the map in the same spot as above screenshot**

![WoWScrnShot_092319_023826](https://user-images.githubusercontent.com/5822375/65396153-dbe6e880-ddab-11e9-95d7-8f0e64beb676.jpg)

**All addons disabled: 216 FPS**

![WoWScrnShot_092319_024447](https://user-images.githubusercontent.com/5822375/65396175-354f1780-ddac-11e9-9b01-df7f02181c6d.jpg)

**All addons except Questie disabled: 148 FPS**

![WoWScrnShot_092319_024504](https://user-images.githubusercontent.com/5822375/65396177-3aac6200-ddac-11e9-8e2d-7931ab5ced16.jpg)

## Questie version

4.1.1

**Comment by huylv** [comment]
Enabling minimap icons drops fps significantly. I have to disable it.

**Comment by BreakBB** [comment]
@brndd @huylv Please checkout v4.1.2! We've majorly increased our performance
