### ISSUE TITLE
Sweet Amber

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1113]
## Description
The sakc of Barley and the Sack of Corn aren't marked on the map, yet. (they are at different places, only the Rye is in The Hinterlands

## Wowhead link
https://classic.wowhead.com/quest=49/sweet-amber

## Questie version
4.1.1

**Comment by BreakBB** [comment]
To make sure this is a different issue: Where all objectives shown on the same place/icon? And are you on a client different to English?

**Comment by Djfe** [comment]
all at the same place, client german

**Comment by BreakBB** [comment]
Then this is linked to #1071 as well (merging). You can grab a pre release of 4.1.2 from Discord to fix such issues!
