### ISSUE TITLE
Witherbarg Cages

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1114]
## Description
Cage 3 is at the marker questie currently shows: Hiri'Watha

Cage 1 and 2 are at a different ruin though: Zun'Watha
which is west of cage 3

## Wowhead link
https://classic.wowhead.com/quest=2988/witherbark-cages

## Questie version
4.1.1

**Comment by BreakBB** [comment]
To make sure this is a different issue: Where all objectives shown on the same place/icon? And are you on a client different to English?

**Comment by Djfe** [comment]
all objectives where shown on the same marker and I'm running on a German client

**Comment by BreakBB** [comment]
Linked to #1071
