### ISSUE TITLE
Quest tracker not registering quest complete

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#1115]
I have found a few cases where the quest tracker does not immediately register a quest as complete.
1) Quests where you have to fill something, like a bowl or a vial with water from somewhere (like the As Water Cascades quest in Darkshore).
2) Quests where you might receive some items in the mail (from alts) to complete a quest, like 6x Darkshore Grouper for a quest in Darkshore.
3) Quests where you create something yourself to complete the quests. Like "Elixir's for the Bladeleafs", where you create potions.

In both cases a /reload will fix it.

EDIT; I think #1 also applies to the icons on the map, they are not removed upon completion until you do a /reload.

Questie v4.1.1

**Comment by reaper666735** [comment]
i can confirm this, i already made another issue about this here: https://github.com/AeroScripts/QuestieDev/issues/1072 

basically the same as Painstormx any "use" item that needs to be filled mostly phials never get the trigger event registered by Questie, another i recently noticed was the Gnogaine quest in Gnomeregan

Quest: https://classic.wowhead.com/quest=2926/gnogaine
Quest items: https://classic.wowhead.com/item=9283/empty-leaden-collection-phial ; https://classic.wowhead.com/item=9284/full-leaden-collection-phial

and on the second topic of items via mail or traded by users the tracker never seems to recognise them in your bags (only your loot) the map icons they do register it and count up BUT if the last item required to complete a quest is from said source (trade/mail) then it bugs on maxed out and wont show you the delivery spot  :)

**Comment by BreakBB** [comment]
We're currently testing changes to our event code. If you want to help us, you could checkout the dev-branch and report specific problems for that branch on Discord :)

**Comment by BreakBB** [comment]
With the release of v4.1.2 we've updated our event system and at least quests where you "create" a quest item instead of looting it is fixed with it. Please report back if the others are as well! @Painstormx @reaper666735

**Comment by Painstormx** [comment]
Where do you download v4.1.2?
The version on Curse is still v4.1.1

**Comment by BreakBB** [comment]
You can grab it at the [releases](https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2). We haven't uploaded it to Curseforge yet to get some feedback before releasing it to general public

**Comment by BreakBB** [comment]
@Painstormx Could you test this with v4.1.2 and report back? It is released on Twitch now as well

**Comment by Painstormx** [comment]
Been testing 4.1.2 the past 10 days and so far I haven't seen any quest tracker problems :)

**Comment by BreakBB** [comment]
@Painstormx Thanks for the report. Assuming this is fixed.
