### ISSUE TITLE
Quest item from email not registered

### ISSUE THREAD

**Issue by SpareSimian** [AeroScripts/QuestieDev#1116]
When I retrieve a quest item from mail, it's not registered in the tracker. The tracker still thinks I have zero items. Right now I'm seeing this with the Westfall Stew and Goretusk Liver Pie quests, where I've sent the required items from characters that have already completed those quests and had extras. 

The tracker does update once I acquire an item from a mob, and includes the counts of items I already had from the mail. So it just needs to monitor the mail looting event.

**Comment by SpareSimian** [comment]
The tracker also reports the items if I log out and back in, but I expected that. Another possible path to check is whether it sees them received through trade or vendor purchase.

**Comment by Kopo942** [comment]
This seems to be a known issue (see #722), and devs are looking for a proper way to fix it.
