### ISSUE TITLE
Quest #553 - Helcular's Revenge (part 2)

### ISSUE THREAD

**Issue by wow-classic** [AeroScripts/QuestieDev#1117]
## Description
Quest objectives are not marked on the map (in the Russian version. Сan’t see the non-Russian version).

## Wowhead link
https://classic.wowhead.com/quest=553/helculars-revenge

## Questie version
4.1.1 BETA

**Comment by BreakBB** [comment]
I did this quest just yesterday on the latest master branch and it was working fine. Keep an eye out for the upcoming release for a fix of this! Thanks for your report.
