### ISSUE TITLE
"Erion's Behest" not shown on map

### ISSUE THREAD

**Issue by mirror3000** [AeroScripts/QuestieDev#1119]
## Description
The quest "Erion's Behest" is not being show on my map.

## Wowhead link
https://classic.wowhead.com/quest=2260/erions-behest

## Questie version
4.1.1

**Comment by BreakBB** [comment]
Could you run the following commands to provide some information for us?

`/dump IsQuestFlaggedCompleted(2259)`
`/dump IsQuestFlaggedCompleted(2260)`

**Comment by BreakBB** [comment]
@mirror3000 Any news on this?

**Comment by BreakBB** [comment]
The data is looking correct on our side an there has been no other report. Closing this for now.
