### ISSUE TITLE
CrazyArrow sometimes points to the quest finisher when there are still objectives to complete

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#112]

**Comment by Schaka** [comment]
This happens when you pick up a new quest. It doesn't update any of the objective points, JUST the finisher. So you don't get any objectives and the arrow points to the only one available.
Pressing Questie toggle on the map twice solves it.

**Comment by Schaka** [comment]
Fixed in 13a4f6c0767a27443dba1ee13b3599d7f07990cb
