### ISSUE TITLE
"A Lesson to Learn" (Druid quest) shows on map for my Rogue

### ISSUE THREAD

**Issue by mirror3000** [AeroScripts/QuestieDev#1120]
## Description
This quest is shown on the map for my Night Elf Rogue in Darnassus.
However the level 16 Rogue quest is not shown on my map:
https://github.com/AeroScripts/QuestieDev/issues/1119

## Wowhead link
https://classic.wowhead.com/quest=26/a-lesson-to-learn

## Questie version
4.1.1

**Comment by BreakBB** [comment]
Merging this with #1035
