### ISSUE TITLE
Add language support for zone names

### ISSUE THREAD

**Issue by LasterOfDesaster** [AeroScripts/QuestieDev#1122]
## Description

I have forked QuestDev on my own [repo](https://github.com/LasterOfDesaster/QuestieDev/tree/localization)  and added localization for zone names in german. Would be great if there additional languages, so the user doesn't have to search and translate them by themselfe.

**Comment by BreakBB** [comment]
@LasterOfDesaster Are you referring to the zone names in the Journey? Some has already been translated. Others need the translations in the `/Locale/<lang>/lookupZones.lua`.

**Comment by BreakBB** [comment]
This issue is being closed because some or all of the requested functionality has already been addressed in other features or fixes.
