### ISSUE TITLE
[12] Tomb of Divinity ( Brandur Ironhammer )

### ISSUE THREAD

**Issue by MightyGreymane** [AeroScripts/QuestieDev#1124]
## Description
I am in Ironforge, because my Questie said: "This quest is available from Brandur Ironhammer called [12] Tomb of Divinity, you should do this, quest." I came over here to do it, but he had no quest for me. Then, I thought to myself for a couple minutes... I realized I had already done that quest. It has a human version in Stormwind & I finished it already.

Also, I finished Tomb of Divinity in Stormwind before I downloaded & turned on Questie. So, I thought to myself maybe that was why it thinks I haven't finished it? The quest isn't displaying in Stormwind. It knows I did it in Stormwind. So, essentially it should not think I still have to do it in Ironforge.

Just wanted to bring this to your attention Questie Developers! Also, because I am the type who does all the quests, seeing this finished one here mocks me. Haha, so, a fix for this registration issue would be pleasant. ~ Thanks again, MightyGreymane. (The Human Paladin)

## Wowhead link
https://classic.wowhead.com/quest=1642/the-tome-of-divinity
( Stormwind )
https://classic.wowhead.com/quest=1646/the-tome-of-divinity
( Ironforge)
Hopefully that linked the 2 different spots for this quest.

## Screenshots
Not Applicable. ( It probably is, I just don't know how to screen shot something like this. )

## Questie version
Questie v4.1.1 Beta
(v4.1.1 is green)
(Beta is red)

**Comment by BreakBB** [comment]
Thanks for your detailed report! Most of such breadcrumb quests should have been fixed for 4.1.1, but I think we've missed some. This should be good with the upcoming release 👍

**Comment by BreakBB** [comment]
@MightyGreymane Could you report back if this is fixed?

**Comment by MightyGreymane** [comment]
Yeah, the quest was properly removed & has registered as completed.

This has been really appreciated & reassuring. I will make sure to continue
reporting bugs effectively now that I know you have such a pleasant
responsive team!
( Sorry, for the delayed response. The add-on has been doing wonders for
me! )

May I also ask, will there ever be a setting to toggle on / off that will
show drop chance related quests drops?

**Comment by BreakBB** [comment]
@MightyGreymane Thanks for coming back to this and helping out! We really appreciate every report we get so we can improve Questie step by step 👍
