### ISSUE TITLE
Quest from Daio the Decrepit

### ISSUE THREAD

**Issue by Nimbix-wow** [AeroScripts/QuestieDev#1125]
## Description

Quests are in game, but Questie is not showing them.

## Wowhead link

https://classicdb.ch/?quest=7581
https://classicdb.ch/?quest=7582

## Screenshots

![Capture](https://user-images.githubusercontent.com/46905100/65505047-abe13780-dec8-11e9-8c9a-cfd3cb04953d.JPG)

## Questie version

v4.1.1

**Comment by drejjmit** [comment]
What quests can you accept there? Aren't [60] The Prison's Bindings a Dire Maul quest? "The blood of the Wildspawn satyr that occupy Dire Maul"

**Comment by Nimbix-wow** [comment]
I can accept the quests I linked, see top right corner of the screenshot.

**Comment by drejjmit** [comment]
We can unhide them but are you sure they are completable before Dire Maul?

**Comment by Nimbix-wow** [comment]
[60] The Prison's Bindings is a Dire Maul quest and the Satyr Blood is only lootable inside Dire Maul. [60] The Prison's Casing maybe completeable, I'll heading towards Winterspring to find out.

**Comment by Nimbix-wow** [comment]
Hello again

Quest #7582 can be completed.
