### ISSUE TITLE
Verigan's Fist component quests still shown on map (Bailors Ore Shipment/Seeking the Kor Gem)

### ISSUE THREAD

**Issue by LucasAvis** [AeroScripts/QuestieDev#1126]
## Description
**Bailors Ore Shipment** (https://classic.wowhead.com/quest=1655/bailors-ore-shipment) and **Seeking the Kor Gem** (https://classic.wowhead.com/quest=1442/seeking-the-kor-gem) quest starters are still shown on the map long after having completed them and their master quest - The Test of Righteousness (stage 2) (https://classic.wowhead.com/quest=1654/the-test-of-righteousness)

## Screenshots
![Bailor Stonehand](https://user-images.githubusercontent.com/31852022/65508529-59a01680-dec8-11e9-9fc3-677e26310665.png)
![Kor Gem](https://user-images.githubusercontent.com/31852022/65508530-5a38ad00-dec8-11e9-9122-d04f376aebc5.png)

## Questie version
4.1.1

**Comment by carsono311** [comment]
Had this issue as well...

**Comment by BreakBB** [comment]
Thanks for your report 👍  This has been fixed with 76087787325bb375b822bedbddd47ae29d535612 and will be included in the upcoming release!
