### ISSUE TITLE
Questie should show what amount of XP you can expect from a quest

### ISSUE THREAD

**Issue by LasterOfDesaster** [AeroScripts/QuestieDev#1127]
## Description

Looking up the amount of XP from a quest in WoWHead or other databases is kinda boring and time consuming. I have seen a screenshot in a video, where, - based on the different font that is used - in the questlog at the end of the quest text after the reward, the amount XP the quest offers is shown. Questie should have (IMHO) the same feature.

**Comment by 7Krown7** [comment]
This work now. But not past lvl 70. Make me sad :(
