### ISSUE TITLE
Jungle Secrets (Stranglethorn Vale) wrong pick up location

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#1128]
## Description

so basically to obtain this quest you need to wait for Private Thorson to move out of Rebel Camp and go on patrol, after awhile around point 40-8 on the road he will get ambushed by Kurzen NPC's, and after you saved him he will allow you to take it, so to remove confusion maybe put the icon @ that spot ^^

## Wowhead link

Quest: https://classic.wowhead.com/quest=215/jungle-secrets
NPC: https://classic.wowhead.com/npc=738/private-thorsen#starts

## Screenshots

as you can see on the minimap, Questie is showing i can take the quest in the Rebel camp, but having Private Thorson in front of me i have 0 quests :p

https://imgur.com/QG3O7xk

## Questie version

v4.1.1

**Comment by BreakBB** [comment]
Known issue since #869
