### ISSUE TITLE
LUA error in game

### ISSUE THREAD

**Issue by calidonwestfall** [AeroScripts/QuestieDev#1130]
Message: Interface\AddOns\QuestieDev-master\Questie.lua:2: Usage: NewAddon([object,] name, [lib, lib, lib, ...]): 'name' - Addon 'Questie' already exists.
Time: Tue Sep 24 10:24:35 2019
Count: 1
Stack: Interface\AddOns\QuestieDev-master\Questie.lua:2: Usage: NewAddon([object,] name, [lib, lib, lib, ...]): 'name' - Addon 'Questie' already exists.
[C]: ?
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:150: in function `NewAddon'
Interface\AddOns\QuestieDev-master\Questie.lua:2: in main chunk

Locals: (*temporary) = "Usage: NewAddon([object,] name, [lib, lib, lib, ...]): 'name' - Addon 'Questie' already exists."
Message: (null)
Time: Tue Sep 24 10:24:36 2019
Count: 3

Message: ...ddOns\QuestieDev-master\Modules\QuestieNameplate.lua:25: Usage: GetNamePlateForUnit(unitToken[, includeForbidden])
Time: Tue Sep 24 10:36:35 2019
Count: 7
Stack: ...ddOns\QuestieDev-master\Modules\QuestieNameplate.lua:25: Usage: GetNamePlateForUnit(unitToken[, includeForbidden])
[C]: in function `GetNamePlateForUnit'
...ddOns\QuestieDev-master\Modules\QuestieNameplate.lua:25: in function `getFrame'
...nterface\AddOns\Questie\Modules\QuestieNameplate.lua:112: in function <...nterface\AddOns\Questie\Modules\QuestieNameplate.lua:88>
[C]: ?
...igs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...igs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...igs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ce\AddOns\Details\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\AddOns\Details\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by BreakBB** [comment]
You have more than one version of Questie installed. Have a look into your AddOns folder and delete one of the Questie folders!
