### ISSUE TITLE
All along the watchtowers shows only 1 tower

### ISSUE THREAD

**Issue by Magissia** [AeroScripts/QuestieDev#1135]
## Description

Questie shows only one tower out of 4 on the map

## Wowhead link

https://classic.wowhead.com/quest=5097/all-along-the-watchtowers

## Screenshots

Quest completed,cannot take screenshot

## Questie version

4.1.1

**Comment by BreakBB** [comment]
Is your clients language different to English?

**Comment by Magissia** [comment]
Yes

**Comment by BreakBB** [comment]
Then this is related to #1071 and fixed with the release of v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2
