### ISSUE TITLE
Arcanes runes, only one rune is shown

### ISSUE THREAD

**Issue by Magissia** [AeroScripts/QuestieDev#1137]
## Description

Only one rune out of 4 is shown on the map

## Wowhead link

https://classic.wowhead.com/quest=3449/arcane-runes

## Questie version

4.1.1

**Comment by BreakBB** [comment]
I'll ask here again: Are you using a Non-English client?

**Comment by Magissia** [comment]
Yes

**Comment by BreakBB** [comment]
Then this is related to #1071 and fixed with the release of v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2
