### ISSUE TITLE
Questie (classic) not updating quest objectives

### ISSUE THREAD

**Issue by mpoirier** [AeroScripts/QuestieDev#1138]
Recently, I have been having issues with Questie (classic) not updating quest objectives. On multiple occasions (or every occasion, as far as I can recall) quest objectives will not update after trading (non-soulbound) quest items with players. I issue the /reload command to force objectives to update.

**Comment by BreakBB** [comment]
Yes, this is a known issue and we will fix this in a future update. Merging this with #722
