### ISSUE TITLE
Quest: Wandering Shay

### ISSUE THREAD

**Issue by ayrb13** [AeroScripts/QuestieDev#114]
I was doing this quest with some mates, when i move my mouse to Shay, there must be a error occured
![qq 20150530003237](https://cloud.githubusercontent.com/assets/3375743/7887405/6d92b608-0663-11e5-9045-bbb63aadcd12.png)

**Comment by ayrb13** [comment]
Questie version: v2.0.10

**Comment by AeroScripts** [comment]
I'll look into this shortly
