### ISSUE TITLE
After update quest "Ignition" doesn't appear on the map and minimap (Alliance)

### ISSUE THREAD

**Issue by Amazonka** [AeroScripts/QuestieDev#1141]
## Description
After updating addon to version 4.1.1 quest "Ignition" doesn't appear on map and minimap on alliance side. Followup quest The Escape appears properly. For some reason, Wowhead shows quest as Horde-only, but both factions can do it.

## Wowhead link
https://classic.wowhead.com/quest=858/ignition
https://classic.wowhead.com/quest=863/the-escape

## Screenshots
Cannot provide screenshot, because already completed both quests.

## Questie version
4.1.1
4.1.0

**Comment by BreakBB** [comment]
[This comment](https://classic.wowhead.com/quest=858/ignition#comments:id=3127752) states the same. Thanks for your report!
