### ISSUE TITLE
Filter faction/active quests in the journey

### ISSUE THREAD

**Issue by alucardu** [AeroScripts/QuestieDev#1142]
I enjoy using the questie journey to see what quests are (still) available for me, but the fact that I see both factions quests, and also the quests already in my quest log make it a bit hard to use. Any chance of setting filters on the journey?

**Comment by BreakBB** [comment]
@alucardu Do you still have issues with faction specific quests? I can't reproduce it with the latest release.

Quests already in the quest log are not filtered yet and I don't think that is a good idea, because the quest can still be completed.

**Comment by BreakBB** [comment]
Assuming this is fixed.
