### ISSUE TITLE
Panther Mastery missing many Panther spawns

### ISSUE THREAD

**Issue by Ultroman** [AeroScripts/QuestieDev#1144]
## Description
I'm finding a lot of Panther spawns where no spawn points are marked. At least 2 around 30.9, 9.6. In fact, I'm only seeing a single Panther spawn marker on the entire map around 45.5, 10.0. That's definitely not right.

## Wowhead link
https://classic.wowhead.com/quest=191/panther-mastery

## Questie version
Newest branch, 09/26-2019

**Comment by BreakBB** [comment]
It's not easy for us to get the exact spawns of every mob and moreover we don't want to add too many markers.
I've added the ones from Wowhead for the [Panther](https://classic.wowhead.com/npc=736/panther)
