### ISSUE TITLE
Ragnar Thunderbrew

### ISSUE THREAD

**Issue by Leithmorien** [AeroScripts/QuestieDev#1149]
Simply questie doesn't show the quest as available from the NPC (Enohar Thunderbrew in Nethergarde Keep, Blasted Lands). Requires lvl 50 to be available.

https://vanilla-twinhead.twinstar.cz/?quest=4128

Questie v.  4.1.1 Beta

**Comment by BreakBB** [comment]
I can't find any issue in our data for this quest. Could you check your config setting about "show quest above my level" and at which position this is? Even though this quest is available at level 50 it is a level 55 quest so you need have the slider set correctly.

**Comment by BreakBB** [comment]
Closing this due to missing response.
