### ISSUE TITLE
With Questie toggled off, quest tracker is still visible but doesn't update

### ISSUE THREAD

**Issue by vexis58** [AeroScripts/QuestieDev#115]
I really love the quest tracker design and was hoping to be able to use this mod for just that, but turn off all the stuff on the map so I have a more "vanilla" experience.

Finally found the map button and thought I had a solution. The quest tracker was still visible but all the map stuff was gone.

Unfortunately, the quest tracker doesn't actually update any of the quest objectives while the mod is toggled off, even though it's still visible. If the quest tracker isn't supposed to work with the mod toggled off, it should go away entirely so as not to get my hopes up =(

![image](https://cloud.githubusercontent.com/assets/12679905/7900813/f217bb22-0720-11e5-9eb3-ff7aed2e5487.png)

**Comment by Schaka** [comment]
If you just want the quest tracker design, you could get MonkeyQuest, it's fairly similar.
Our tracker depends on existing nodes because it's meant to supply the user with the arrow, amongst other functionalities not yet implemented

**Comment by AeroScripts** [comment]
That and there's a couple bugs currently causing it to not update properly still.
