### ISSUE TITLE
Marauders of Darrowshow

### ISSUE THREAD

**Issue by ssateneth** [AeroScripts/QuestieDev#1151]
## Description

Objective doesn't update count or completion when quest items increment from using Mystic Crystal on a Fetid Skull

## Wowhead link

https://classic.wowhead.com/quest=5206/marauders-of-darrowshire

## Questie version

4.1.1

**Comment by BreakBB** [comment]
The problem here is the same as with other quests where you "create" an item instead of looting it: We don't track such events correctly in the latest release. It will be fixed in the next release though!

**Comment by BreakBB** [comment]
This is fixed with the release of v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2 Please let us know if it isn't
