### ISSUE TITLE
(2.0.9 BETA bug) NPC Tooltip in Darkshore quest 'The Sleeper Has Awakened'.

### ISSUE THREAD

**Issue by landofcake** [AeroScripts/QuestieDev#116]
This quest involves escorting an NPC to one of the small settlements in Ashenvale.

While escorting the NPC, hovering the mouse over him causes a bug in Questie at:

QuestieAstro.lua:435.

The variable 'indx' is resolving to nil here.

**Comment by Schaka** [comment]
Thank you for the report. Please update to 2.0.10 and see if the bug persists, as we made some changes with tooltip hooking.

**Comment by landofcake** [comment]
It's a little tricky to reproduce, as at this point I've foolishly completed the quest without considering the implications for bug reproducibility. Do you have a prescribed method for testing bugs?

**Comment by Schaka** [comment]
Generally, always update to the latest version before posting a report. Other than that, we have our own test server. But it's not always easy to reproduce a "real world example", especially as properly scripted servers differ very much from stock mangoszero. 

Therefore, if you encounter a bug, make sure you have the latest release - and if you do and the bug persists, please feel free to report!

**Comment by landofcake** [comment]
Thanks Schaka.

At this stage, I can't reproduce this due to having finished the quest, so I'll leave it to you to decide whether to keep this open or not. I'm happy to do the needful and test this on your Questie test server to confirm/dismiss the bug if it's an option that's available to anyone outside of the dev team.

**Comment by AeroScripts** [comment]
Just having the line number should make this easy to fix. At the very least I can easily implement a nill check there.

**Comment by landofcake** [comment]
As it turns out I do actually have a character of similar level on another server which -hasn't- completed the quest, so I'll test this again in the next few days.

**Comment by ayrb13** [comment]
I think this bug is same as [that i submitted](https://github.com/AeroScripts/QuestieDev/issues/114)
That was also a escort quest

**Comment by landofcake** [comment]
I can confirm that this bug is still present in 2.0.10. I don't know how much difference the backend of the server makes, but this was tested on Feenix's Emerald Dream server.

**Comment by nycter79** [comment]
![image](https://cloud.githubusercontent.com/assets/10027713/7948942/0dde85c4-0989-11e5-9ac4-152f8f0a19b8.png)
