### ISSUE TITLE
The Warsong Reports (quest id 821)

### ISSUE THREAD

**Issue by digitalmuze** [AeroScripts/QuestieDev#1161]
## Description
When quest completed, yellow "?" does not appear on map in The Barrens.

## Wowhead link
https://classic.wowhead.com/quest=821

## Screenshots
n/a

## Questie version
v4.11

**Comment by BreakBB** [comment]
Thanks for your report! This has already been fixed in 0eac56ea7341983793a7b6c7a9b5fcd889e2e8e6 and will be included in the next release!
