### ISSUE TITLE
Call to Arms Horde Quest missing marker

### ISSUE THREAD

**Issue by silverclaw** [AeroScripts/QuestieDev#1162]
## Description
The quest exclamation mark is not showing (quest giver).

## Wowhead link
https://classic.wowhead.com/quest=677/call-to-arms

## Screenshots
I'll attach a screenshot. Quest giver is "Drum Fel" (Hammerfall - Arathi Highlands) at coords 74.25, 33.92.

## Questie version
the dump command returns "4.1.1"

**Comment by silverclaw** [comment]
![DrumFel](https://user-images.githubusercontent.com/2333395/65816706-21197900-e1f7-11e9-9678-6fad56e58b36.png)
![Hammerfall](https://user-images.githubusercontent.com/2333395/65816707-21197900-e1f7-11e9-987d-a14a00a321e2.png)

**Comment by BreakBB** [comment]
@silverclaw Could you run `/dump IsQuestFlaggedCompleted(676)` and report the output?

**Comment by silverclaw** [comment]
![Untitled](https://user-images.githubusercontent.com/2333395/66719623-6d191000-edea-11e9-9a89-a7efa1c5af61.png)
Here it is :)
