### ISSUE TITLE
Quest icon color differences

### ISSUE THREAD

**Issue by Treedot** [AeroScripts/QuestieDev#1166]
I'm not entirely sure if this is possible, but it would be nice to have the quest icons above the NPCs be different colors depending on what level they are.

Like, I have Questie set to only show me quests 2 levels above mine on the minimap, but those quest givers still have the [!] symbol above their heads, so I have to reference the mini map before taking quests.

Is it possible to make the [!] symbol red or something if it's above my level?

**Comment by BreakBB** [comment]
@Treedot Sorry to tell you, but an addon can't change/hide the icons over the head of an NPC ☹️
