### ISSUE TITLE
Missing Quest

### ISSUE THREAD

**Issue by BobStarlin** [AeroScripts/QuestieDev#1167]
Just wanted to let you know, there is a quest missing from your addon.
Between Arathi Highlands and Wetlands there is a dead dwarf (sully baloo) crushed under some rocks in the river under the bridge. He has a "waterlogged note" that starts a quest back to iron forge. This quest leads through a chain that goes to Southshore / Arathi Highlands.

**Comment by BreakBB** [comment]
Thanks for your report. It would be great if you could use the template the next time :)

This is also a duplicate of #909
