### ISSUE TITLE
[23] Dig Rat Stew, the horde cook quest's limitation is wrong.

### ISSUE THREAD

**Issue by kaikaiiiiiii** [AeroScripts/QuestieDev#1169]
## Bug description

[23] Dig Rat Stew. The horde cook quest, have some cook skill level limitation to bee seen and to be accepted. But now it showed on map when only 1 skill point, which actually can't be accept there.

Detail can be found here. They say "you have to be at least a journeyman cook to get this" 
https://classic.wowhead.com/quest=862/dig-rat-stew#comments

## Questie version
4.1.1 Beta

**Comment by BreakBB** [comment]
Thanks for your report :) This is a known issue since we don't handle the training level of a profession yet (meaning Journeyman, Artisan etc). As far as we know there're just a few profession quests which require a training level instead of a specific skill level.

**Comment by AeroScripts** [comment]
v6.0.5
