### ISSUE TITLE
Error when mousing over a map/minimap icon that shouldn't exist (failed to get removed)

### ISSUE THREAD

**Issue by MysticalOS** [AeroScripts/QuestieDev#1170]
## Bug description
Did the pre quests to unlock Noggenfogger elixers which basically involves turning couple quests into him really fast. The speed of turnins probably caused the breakage. When mousing over ? on minimap or world map (for a quest that was already turned in) it threw this error. Mind you, line number might be off slightly because of modifications I have to my local copy, but my modifications had no bearing on error (besides shifting line number by 1)

6x ...ddOns\QuestieDev-master\Modules\QuestieFramePool.lua:476: attempt to index field 'data' (a nil value)
...ddOns\QuestieDev-master\Modules\QuestieFramePool.lua:476: in function `Questie_Tooltip'
...ddOns\QuestieDev-master\Modules\QuestieFramePool.lua:239: in function <...ddOns\QuestieDev-master\Modules\QuestieFramePool.lua:239>

Locals:
self = <table> {
 1 = "QuestieDev-master"
 2 = <table> {
 }
 lastTooltipShowHack = 1049121.732000
 usedFrames = <table> {
 }
 Questie_Click = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:598
 addonPath = "Addons\QuestieDev-master\"
 QuestieCreateFrame = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:185
 _lastMiniInside = false
 Questie_Tooltip = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:445
 numberOfFrames = 1248
 IsMinimapInside = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:418
 unusedFrames = <table> {
 }
 allFrames = <table> {
 }
 _lastMiniInsideCheck = 1049121.414000
}
self = QuestieFrame893 {
 glowLogicTimer = <table> {
 }
 glow = QuestieFrame893Glow {
 }
 BaseOnUpdate = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:290
 FakeUnhide = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:399
 FakeHide = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:384
 texture = <unnamed> {
 }
 fadeLogicTimer = <table> {
 }
 BaseOnShow = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:295
 BaseOnHide = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:309
 FadeLogic = <function> defined @QuestieDev-master\Modules\QuestieMap.lua:198
 0 = <userdata>
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:313
 GlowUpdate = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:278
 FadeIn = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:371
 FadeOut = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:357
}
Tooltip = GameTooltip {
 0 = <userdata>
 SetHyperlink = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 hasMoney = 1
 questOrder = <table> {
 }
 SetCraftItem = <function> defined =[C]:-1
 comparing = false
 TopOverlay = <unnamed> {
 }
 npcOrder = <table> {
 }
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetCraftSpell = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 updateTooltip = 0.012000
 SetInventoryItem = <function> defined =[C]:-1
 _owner = QuestieFrame893 {
 }
 SetLootRollItem = <function> defined =[C]:-1
 canAddRestStateLine = 1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetAction = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
maxDistCluster = 1
mid = 1446
already = <table> {
}
alreadyUnique = <table> {
}
headers = <table> {
}
footers = <table> {
}
contents = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'data' (a nil value)"
_QuestieFramePool = <table> {
 1 = "QuestieDev-master"
 2 = <table> {
 }
 lastTooltipShowHack = 1049121.732000
 usedFrames = <table> {
 }
 Questie_Click = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:598
 addonPath = "Addons\QuestieDev-master\"
 QuestieCreateFrame = <function> defined @QuestieDev-master\Modules\QuestieFramePool.lua:185
 _lastMiniInside = false
 Questie_Tooltip = <function> d

## Questie version
QuestieGetVersionString doesn't exist anymore, but it's a direct dev download from github from earlier today

**Comment by BreakBB** [comment]
This is fixed with the release of v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2
