### ISSUE TITLE
Allow tracking of arbitrary NPCs/Mobs by ID (or name?)

### ISSUE THREAD

**Issue by TobalJackson** [AeroScripts/QuestieDev#1171]
## Description

Allow the player to specify an ID of a mob/npc/other that will allow questie to track and show on the minimap/worldmap.

**Comment by Gogo1951** [comment]
Hey @TobalJackson 

This issue seems like a dupe of https://github.com/AeroScripts/QuestieDev/issues/1075

Can we close this?

**Comment by BreakBB** [comment]
This is not a duplicate, since this is about simply marking them on the map while #1075 is about a macro (meaning fast way) to show the current target on the map.

But from what I've seen this issue is already completed, closing it for now. @Muehe Might reopen it if he has further ideas.
