### ISSUE TITLE
Invalid Quest Marker: Bungle in the Jungle

### ISSUE THREAD

**Issue by proksch** [AeroScripts/QuestieDev#1177]
## Description

The world map is showing the quest [Bungle in the Jungle](https://classic.wowhead.com/quest=4496/bungle-in-the-jungle), even if the prerequisite [March of the Silithid](https://classic.wowhead.com/quest=4493/march-of-the-silithid) has not been  completed yet.

## Wowhead link

[Bungle in the Jungle](https://classic.wowhead.com/quest=4496/bungle-in-the-jungle)
[March of the Silithid](https://classic.wowhead.com/quest=4493/march-of-the-silithid)

## Questie version

4.1.1

**Comment by BreakBB** [comment]
Fixed with 83fc2af1d014c8f46ccd20f22b1703596a4b99be
