### ISSUE TITLE
Invalid Quest Marker: A Short Incubation

### ISSUE THREAD

**Issue by proksch** [AeroScripts/QuestieDev#1179]
## Description

The map is showing a possible hand-in for [A Short Incubation](https://classic.wowhead.com/quest=3842/a-short-incubation) at [Quentin](https://classic.wowhead.com/npc=9238), even after handing in the quest and accepting the follow-up [The Newest Member of the Family](https://classic.wowhead.com/quest=3843/the-newest-member-of-the-family). I think the follow-up is alliance only, which might break the internal detection logic... the two items are called differently though [Unhatched Sprite Darter Egg](https://classic.wowhead.com/item=11102/unhatched-sprite-darter-egg) vs. [Fragile Sprite Darter Egg](https://classic.wowhead.com/item=11471/fragile-sprite-darter-egg).

## Wowhead links

* [A Short Incubation](https://classic.wowhead.com/quest=3842/a-short-incubation)
* [Quentin](https://classic.wowhead.com/npc=9238) (Questgiver)
* [The Newest Member of the Family](https://classic.wowhead.com/quest=3843/the-newest-member-of-the-family)

## Questie version

4.1.1

**Comment by BreakBB** [comment]
Hey @proksch Thanks you very much for all your reports, they're very appreciated!

Could you tell me what you mean with "even after handing in the quest"? Was there still a `?` shown on the map?

**Comment by proksch** [comment]
Yes, Questie was showing a yellow question mark, as if I could still hand-in the quest, even after having handed in the quest... The marker only vanished after handing in the follow-up in the Hinterlands.

On an unrelated side-note, I would be happy to help out with more than just reports about buggy quests, but I found it hard to get started with the code base. For example, it did not really become clear to me how the internal database is structured, like which data is actually being stored about quests, or how the progress between different quest steps is tracked. Do you have an up-to-date getting started guide for new contributors?

**Comment by BreakBB** [comment]
If just the ? stayed that means an update went wrong or missed by Questie. Improvements in the latest versions should prevent this.

We're all very limited in time, but I will have some more time soon and want to write some more stuff together in [the wiki](https://github.com/AeroScripts/QuestieDev/wiki) to help others getting starting in the code 👍
