### ISSUE TITLE
Questie removes extra chat panes when opening world map.

### ISSUE THREAD

**Issue by landofcake** [AeroScripts/QuestieDev#118]
Present on 2.0.10.

It appears that Questie somehow removes any chat windows that aren't the main one when opening the world map.

Is this a known issue?

**Comment by Schaka** [comment]
Are you sure it's Questie? I use more than one chat window and haven't had that issue. In fact, I use a chat window called questiedebug, which caches all the debug logging and that never gets removed.

Is this a constant issues you were able to reproduce? If yes, we'll definitely look into it.

**Comment by landofcake** [comment]
I will do some extra testing to be 100% sure, but in a brief test the issue appears to disappear when questie is disabled.

**Comment by landofcake** [comment]
I've done a lot more testing on this and this bug only seems to appear when Questie is enabled. It also only seems to happen when in a city.
