### ISSUE TITLE
Quest 'Desert Recipe' is not available but shows as it is.(might not be in the game or require Cenarion rep)

### ISSUE THREAD

**Issue by istepanko** [AeroScripts/QuestieDev#1180]
## Description
This quest most likely is not in game. I have 300 cooking and completed every quest possible in the game and this is not available.

## Wowhead link
https://classic.wowhead.com/quest=8307/desert-recipe#comments

## Screenshots
<img width="1193" alt="Screen Shot 2019-09-29 at 1 19 07 PM" src="https://user-images.githubusercontent.com/14187183/65838805-d01f8880-e2bb-11e9-9aa4-16fd2bae7e61.png">

## Questie version
4.1.1

**Comment by BreakBB** [comment]
Thanks for your report. This has been fixed with the release of v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2
