### ISSUE TITLE
Alliance quest 'Salve via hunting' shows for Horde even if Horde one completed

### ISSUE THREAD

**Issue by istepanko** [AeroScripts/QuestieDev#1181]
## Screenshots
<img width="704" alt="Screen Shot 2019-09-29 at 1 57 02 PM" src="https://user-images.githubusercontent.com/14187183/65839343-24793700-e2c1-11e9-8c86-393c7b084e77.png">

**Comment by BreakBB** [comment]
Actually there is a [repeatable version](https://classic.wowhead.com/quest=4108/salve-via-hunting) of this quest. This is indicated by the blue exclamation mark as well :)
