### ISSUE TITLE
Quest 'Another Power Stone' shows as available even after 'Tanaris Field Sampling' complete and turned in

### ISSUE THREAD

**Issue by istepanko** [AeroScripts/QuestieDev#1182]
## Wowhead link
https://classicdb.ch/?quest=841
https://classicdb.ch/?quest=654

## Screenshots
<img width="1238" alt="Screen Shot 2019-09-29 at 3 13 50 PM" src="https://user-images.githubusercontent.com/14187183/65840284-0533d700-e2cc-11e9-9ec3-e7a9e72bf5ba.png">

## Questie version
4.1.1

**Comment by BreakBB** [comment]
Thanks for your report! This has been fixed with v4.1.2 https://classic.wowhead.com/quest=4108/salve-via-hunting as well
