### ISSUE TITLE
Hippogryph Muisek

### ISSUE THREAD

**Issue by raato** [AeroScripts/QuestieDev#1183]
## Description
Marker's for quest "Hippogryph Muisek" are not showing in the map. Guide says: "Now go west along the road until you hit the bridge. Cross it, then head southwest. Pass the yeti cave and keep going south until you find hippogryphs in the Frayfeather Highlands."

## Wowhead link
https://classic.wowhead.com/quest=3124/hippogryph-muisek

## Screenshots
https://i.imgur.com/EIZLPMw.jpg

## Questie version
4.1.1

**Comment by BreakBB** [comment]
This has been fixed with the release of v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2
