### ISSUE TITLE
Quest #3124, #3125 and #3126

### ISSUE THREAD

**Issue by Nimbix-wow** [AeroScripts/QuestieDev#1184]
## Description

Objective not showing on map. Also quest completion marker ist also not showing.

## Wowhead link

https://classicdb.ch/?quest=3124
https://classicdb.ch/?quest=3125
https://classicdb.ch/?quest=3126

## Screenshots

![Capture](https://user-images.githubusercontent.com/46905100/65873779-51dae900-e384-11e9-8902-d574d6edb0e2.JPG)

## Questie version

v4.1.2 Beta

**Comment by BreakBB** [comment]
The Hippogryph quest has been fixed with v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2 I'll look into the other one
