### ISSUE TITLE
Soothing Turtle Bisque

### ISSUE THREAD

**Issue by Mookeys** [AeroScripts/QuestieDev#1187]
## Description

Questie is not seeing that the Soothing Spices have been picked up for the quest Soothing Turtle Bisque.

Screen shot I have provided shows the spices in my bag, shows the quest is ready to be turned in and shows Questie not seeing that I picked up the spices
![wow](https://user-images.githubusercontent.com/55995888/65900408-f1e44280-e383-11e9-8f48-97e20d9a1428.PNG)

/

**Comment by BreakBB** [comment]
This is fixed with v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2
