### ISSUE TITLE
Lonebrow's Journal

### ISSUE THREAD

**Issue by Zardilann** [AeroScripts/QuestieDev#1189]
Lonebrow's Journal isn't showing up on the map.

https://classic.wowhead.com/quest=1100/lonebrows-journal

Questie version 4.1.1

**Comment by BreakBB** [comment]
This quest is started by an item and there it is linked to #317

**Comment by Mosik** [comment]
This quests shows up on the map in STV. running Questie 4.3.0. It's not correct right?

![Capture](https://user-images.githubusercontent.com/4305716/67197951-305aa380-f3fe-11e9-9e1e-d2721c16a469.PNG)

**Comment by BreakBB** [comment]
Damn, looks like I used the wrong zoneID. Will fix it soon :tm: @Mosik

**Comment by Mosik** [comment]
Thanks :) I actually went there :D
