### ISSUE TITLE
Lord Banehollow Quest

### ISSUE THREAD

**Issue by dabachel0r** [AeroScripts/QuestieDev#1190]
## Description
Quest Giver: Gorzeeki Wildeyes in the Burning Steppes.
This quest should not be available until Phase 2 since it is a quest of the Warlock Epic Mount. It also has a prerequesite quest.

## Wowhead link
Quest: https://classic.wowhead.com/quest=7623/lord-banehollow#comments
Pre-Quest: https://classic.wowhead.com/quest=7564/wildeyes
Start of the Quest Chain: https://classic.wowhead.com/quest=7562/morzul-bloodbringer

## Screenshot
![image](https://user-images.githubusercontent.com/1662544/65918186-57165300-e3d9-11e9-8235-eb17afdd0af7.png)

## Questie version
Questie v4.1.1 Beta

**Comment by BreakBB** [comment]
This quest will be available with the upcoming opening of Dire Maul according to [Wowhead](https://classic.wowhead.com/guides/classic-wow-warlock-felsteed-dreadsteed-mounts) and therefore it shouldn't be hidden anymore.
