### ISSUE TITLE
Unexpected "?" shows at the end of the quest objective text

### ISSUE THREAD

**Issue by tytannial** [AeroScripts/QuestieDev#1193]
## Bug description
There is a unexpected "?" at the end of the quest objective text.
Language zhcn

## Screenshots
![20191001090728](https://user-images.githubusercontent.com/11215623/65927157-1e06ce80-e42b-11e9-893d-ad516b5cb749.png)

## Questie version
Questie-v4.1.2_BETA-dff5a12

**Comment by tytannial** [comment]
Caused by conflict with quester Quester. Sorry :(
https://www.curseforge.com/wow/addons/Quester

**Comment by SqiChiu** [comment]
有解决方法吗？

**Comment by BreakBB** [comment]
@tytannial Does this also happen if you have just Questie active?

**Comment by tytannial** [comment]
> @tytannial Does this also happen if you have just Questie active?

Only Questie actived. Seems the lua "string.sub" using a wrong index. Caused by double byte code. :(

**Comment by tytannial** [comment]
Questie-v4.3.0_37acad5
![20191018193441](https://user-images.githubusercontent.com/11215623/67091114-66214180-f1de-11e9-8875-64e26b7cc957.png)

quest=6805
![20191018193454](https://user-images.githubusercontent.com/11215623/67091116-66214180-f1de-11e9-9111-bbf92e262f13.png)

quest=6023
![20191018193556](https://user-images.githubusercontent.com/11215623/67091167-86e99700-f1de-11e9-89d4-3690aa2b5327.png)
Objective text

**Comment by kuletco** [comment]
You can try my fix for Chinese client https://github.com/AeroScripts/QuestieDev/issues/1358#issuecomment-544076161

**Comment by tytannial** [comment]
See #1358
