### ISSUE TITLE
Massive lag breastplate of the chromatic flight

### ISSUE THREAD

**Issue by ssateneth** [AeroScripts/QuestieDev#1196]
## Bug description

I picked up quest "Breastplate of the Chromatic Flight" and "Legplates of the Chromatic Defier". Whenever I am on a map that has "blood of heroes" gear icons and I move, my FPS tanks from 250 to 20. The FPS tank only happens when I move. I should add, at the time, I was in a group for scholomance, dead, and running back from the graveyard to the scholomance dungeon entrance. When I stepped on the scholomance stairs, the lag instantly went away. Walking off the stairs = lag is back.

## Questie version

4.1.1

**Comment by drejjmit** [comment]
I can't replicate this with 4.1.2 (Available in [Releases](https://github.com/AeroScripts/QuestieDev/releases), should be on Curse soon)

**Comment by BreakBB** [comment]
@ssateneth Do you still have performance issues?

**Comment by ssateneth** [comment]
I had dropped the quest because of the issues but i'll check it out again soon. It's hard to reproduce as it seems rnadom when it starts and reload ui fixes it

**Comment by BreakBB** [comment]
@ssateneth Any news on this? Did you try it again and with just Questie active?

**Comment by ssateneth** [comment]
Sorry, I haven't. May as well just close it and if I come into the issue again, i'll re-open with more details. IIRC, it was random. Sometimes if I reload ui, the lag stopped happening, and I dont know what causes it to start happening again.

**Comment by BreakBB** [comment]
@ssateneth Alright. Feel free to always come back to this or open a new issue if you have problems.
