### ISSUE TITLE
Supplies from Darkshire (Duskwood)

### ISSUE THREAD

**Issue by tonyxc600** [AeroScripts/QuestieDev#1197]
## Description
"Supplies from Darkshire" available to accept in Duskwood, but not shown on Questie

## Wowhead link
https://classic.wowhead.com/quest=148/supplies-from-darkshire

## Screenshots
![WoWScrnShot_100119_155156](https://user-images.githubusercontent.com/56020611/65946409-6d73eb80-e479-11e9-8646-ac3a63d24040.jpg)

## Questie version
Version: 4.1.2 BETA 121 dff5a12

**Comment by tonyxc600** [comment]
Possibly linked to #1199

**Comment by BreakBB** [comment]
Related to #1173 and fixed. Will be included in the next release
