### ISSUE TITLE
Game tooltip should be hooked to include objective text when applicable

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#12]
The tooltip that appears when mousing over NPCs should be hooked to include objective text when applicable, similar to this: http://www.blogcdn.com/wow.joystiq.com/media/2009/03/questtooltips.jpg

I've already looked into how the tooltip (GameTooltip) works, it shouldn't be too hard to do.

**Comment by AeroScripts** [comment]
Added after a5601c1e5ca5e31ce9cad0aa91baee2f5b9d82cd because it's awesome

**Comment by Schaka** [comment]
Works on objects as of https://github.com/AeroScripts/QuestieDev/commit/958d42da883e128560e63cc4eba62e5f47b307d8
