### ISSUE TITLE
Faded Icons

### ISSUE THREAD

**Issue by Ravuhn** [AeroScripts/QuestieDev#1200]
## Bug description
I have been using questie for nearly the entirity of my classic experience and love it.  However yesterday I noticed that all of my map icons have become extremely faded out and do not know how to fix them.  I have reinstalled questie twice, but this doesnt fix anything.  The only other AddOn I use is better vendors.  I hope this helps!

## Screenshots
![file](https://user-images.githubusercontent.com/56033544/65968389-121e0b00-e431-11e9-8189-9795f42cec47.jpeg)

## Questie version
Questie-v4.1.1.zip

**Comment by DigitalHype** [comment]
Same issue happened for me when Tomtom is installed.

**Comment by Muehe** [comment]
Not sure if this is a bug, or the new "Focus" feature working as intended. As a temp-fix right-click a quest in the tracker and select "Focus Quest", then right-click it again and select "Unfocus Quest". This should make all notes un-fade.

**Comment by BreakBB** [comment]
@Ravuhn @DigitalHype Any news on this?

**Comment by Ravuhn** [comment]
Yeah sorry, focusing and unfocusing a quest worked perfectly!  Completely forgot to update this.
