### ISSUE TITLE
Gnome Improvement (Gnomeregan/Ironforge) icons over the world

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#1201]
## Description

Hello, so this quest starts in the Gnomeregan dungeon from a random dropped item and eventually points you towards Ironforge and several items to gather to "upgrade" a Ring, Questie is showing several icons in multiple zones that i don't even see the logic for since it's Trade/Mining items you need (Silver Bar / Moss Agathe) and/are randomly dropped :p

## Wowhead link

Start Quest: https://classic.wowhead.com/quest=2945/grime-encrusted-ring#comments 
Transition Quest: https://classic.wowhead.com/quest=2947/return-of-the-ring#comments
Item 'upgrade' Quest: https://classic.wowhead.com/quest=2948/gnome-improvement#comments

## Screenshots

https://imgur.com/UP7fJ92

https://imgur.com/bt21J3N

https://imgur.com/slLkGtH

## Questie version

v4.1.1

**Comment by BreakBB** [comment]
The objectives you've seen were "Battered Chests" which could contain Silver Bars. The item will be blacklisted in the next release. Thank you very much for this and all the other issues you report! It's very appreciated 👍
