### ISSUE TITLE
The Hunter's Charm showing, but not available

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#1202]
Questie v4.1.1

Quest:
https://classic.wowhead.com/quest=8151/the-hunters-charm

Not sure how/if you can control it, but that quest is apparently not coming until a later phase, so it shouldn't be shown now on the map.

**Comment by BreakBB** [comment]
Fixed with 21d045c6faf6deff995d4a3c68e190ab705f3509
