### ISSUE TITLE
Salve via Hunting/Salve via Mining

### ISSUE THREAD

**Issue by dabachel0r** [AeroScripts/QuestieDev#1203]
## Description
The Salve via Hunting quest is still marked as yellow although I completed it once. I know that it is a repeatable quest but then it should be blue and not yellow. The Salve via Mining quest I also completed once. I don't know if this could be related to the following ticket: #1181 

## Wowhead link
https://classic.wowhead.com/quest=4103/salve-via-hunting

## Screenshots
![image](https://user-images.githubusercontent.com/1662544/65990666-4c68c600-e48c-11e9-8b77-56cc5fcf0481.png)

## Questie version
Version: 4.1.2 BETA 121 dff5a12

**Comment by BreakBB** [comment]
@dabachel0r Could you run the following command and report the output please:

`/dump IsQuestFlaggedCompleted(4103)`

It might be our data is wrong on this and 4103 is repeatable just like 4108

**Comment by dabachel0r** [comment]
The output is false. But I wonder why. I am pretty sure that I completed this quest. Well, I try these days another time. Maybe I just do remember it wrong

**Comment by BreakBB** [comment]
Fixed with d7ceed2af533c9943022d12673d20bfdebc27f27
