### ISSUE TITLE
4.1.2 Beta - quests by zone - available quests [ 0 ] for all zones

### ISSUE THREAD

**Issue by taishoDev** [AeroScripts/QuestieDev#1206]
The title says it all, I downloaded the recent version 4.1.2 Beta and struggle with this problem that didn't exist in previous versions. Off topic: the other changes are great, though I heard that this 10-20 sec random screen freeze that I'm sometimes having since the start of the vanilla is caused by Questie.

**Comment by Muehe** [comment]
The "Quests by Zone" bug is fixed as of 15b9fedd416d7f510d872121d030430e6f3ff7d2

The freeze is really unusual, first time I ever heard about it. Could be another addon or a bug that is really hard to reproduce, not sure.
