### ISSUE TITLE
Questie icons on minimap don't move smoothly with rotate minimap enabled

### ISSUE THREAD

**Issue by OskarOskar** [AeroScripts/QuestieDev#1207]
## Bug description
With Questie's icons enabled on the minimap, and rotate minimap enabled in interface options. When rotating your character, and the minimap, the icons don't move very smooth, as they did in previous versions.

![rotat](https://user-images.githubusercontent.com/6757518/66012734-8ce63500-e4c8-11e9-9a83-6717fa8a8352.PNG)
needs to be enabled (interface options->display)

## Screenshots
**Smooth**. Questie Version: 4.1.1 BETA
https://i.imgur.com/W3es3Aw.mp4

**Not smooth**. Questie Version: 4.1.2 BETA 121 dff5a12
https://i.imgur.com/ESlMt18.mp4

Might be a little hard to tell from these recordings, but it's a very clear difference in-game.

**Comment by BreakBB** [comment]
@OskarOskar Sorry for not coming back to this earlier. I just confirmed this is still happening with v5.1.0. But from my perspective it is not that bad in the current version.

We're always trying to improve performance though :)
