### ISSUE TITLE
Quest does not exist in Classic 9063 - Torwa Pathfinder

### ISSUE THREAD

**Issue by Serinus1** [AeroScripts/QuestieDev#1208]
https://classic.wowhead.com/quest=9063/torwa-pathfinder#comments

This quest does not yet exist in Classic.

Questie version 4.11

**Comment by Elehiggle** [comment]
Confirmed

**Comment by BreakBB** [comment]
Fixed in 3463feeeb2535f6abfc91c39bc23a5bd1e3392b7 and already released as part of v4.1.2
