### ISSUE TITLE
4.1.2, The Lost Tablets of Mosh'aru shows only one objective

### ISSUE THREAD

**Issue by Magissia** [AeroScripts/QuestieDev#1209]
## Description

Questie shows only one objective out of two
## Wowhead link

https://classic.wowhead.com/quest=5065/the-lost-tablets-of-mosharu

## Screenshots

Quest completed,cannot take screenshot

## Questie version

4.1.2 (Using `/dump QuestieGetVersionString()` just shows `Dump: value=QuestieGetVersionString()` )

**Comment by Magissia** [comment]
I am not using the english client.

**Comment by BreakBB** [comment]
Related to #1071
