### ISSUE TITLE
Soothing Turtle Bisque Horde

### ISSUE THREAD

**Issue by Tzumie** [AeroScripts/QuestieDev#1210]
Not sure if it's me or Questie but I am unable to pick up Soothing Turtle Bisque on horde in Classic

**Comment by BreakBB** [comment]
Please follow our template for issue reports. We need to know which version of Questie you're using and if you provide a link to the quest it will speed up fixes

**Comment by Tzumie** [comment]
Questie-v4.11.zip for patch 1.13.2 https://vanillawowdb.com/?quest=7321

**Comment by BreakBB** [comment]
Sorry for the late response @Tzumie The quest is a cooking quest so you need that profession. And with v4.1.1 the logic has been added. Did you have cooking back then?

**Comment by BreakBB** [comment]
Assuming this is no longer an issue.
