### ISSUE TITLE
Disabling automatic quest tracking does not save

### ISSUE THREAD

**Issue by klishb** [AeroScripts/QuestieDev#1213]
## Bug description

I've tried disabling the "automatically track all quests" option 3 times.  It won't keep the setting.  Not sure if logging off is causing it to turn back on or what that happens.

**Comment by BreakBB** [comment]
Can you check that this is not caused by any other addon? And which version of Questie to you use?

**Comment by hardtofin** [comment]
I am losing automatically track quests in the middle of playing.  So i will just lose the tracker totally and have to re-enable the button to get it to track again.

**Comment by klishb** [comment]
> Can you check that this is not caused by any other addon? And which version of Questie to you use?

I turned off all other addons just now and the problem still occurs.  When I uncheck the option all quests being tracked disappear, but as soon as I toggle one using shift-click then they kind of reset and come back.  If I turn the option off and immediately go back in to the interface options the box is already checked again.  Version is 4.1.1 Beta

**Comment by BreakBB** [comment]
@klishb @hardtofin Can you update to the latest version and check if you still have issues with this?

**Comment by klishb** [comment]
I'm now running 5.01 and it produces the same result.  If I turn the option off and immediately go back in to the interface options the box is already checked again.

**Comment by klishb** [comment]
I just fiddled with turning off Questie tracking completely and now it seems to keep the automatic option off. I logged off and it stayed off when I got back in.  Not sure if I have to relaunch the entire client for that to be a good test or not.

**Comment by BreakBB** [comment]
@klishb @hardtofin I can't reproduce this issue. Please update to v5.1.0 and try again.

If I enable auto tracking the interface option shows the same. After a restart it stays like that and vice versa for disabling.

**Comment by tcaswell** [comment]
I'm getting the same issue described here. I just downloaded Questie so I'm on v5.1.0.

I also noticed that the "show icons on minimap" setting keeps turning itself back on as well even though I keep turning it off. So it seems like there's some issue with settings not sticking.

**Comment by BreakBB** [comment]
@tcaswell So you checked that the "automatic quest tracking" is not caused by any other addon? As I already said I can't reproduce this issue.

The "Show Icons on Minimap" settings is something different, so I have to investigate this...

**Comment by tcaswell** [comment]
I think I figured out the automatic quest tracking problem. Unchecking it in the questie settings did NOT uncheck it in the blizzard interface settings. So I think there was a setting conflict there, so on reload questie was just taking whatever the blizzard interface setting had. After unchecking it in the blizzard interface settings the problem seems to have resolved.

The "Enable Minimap Icons" uncheck being ignored is more sporadic (I only encountered it twice since I downloaded the addon a few hours ago). So it's harder for me to figure out what might be causing it :P

**Comment by BreakBB** [comment]
@klishb @tcaswell Can this be closed or are you still experiencing issues? I still can't reproduce the described behavior.

**Comment by hardtofin** [comment]
Can be closed now, one of the recent builds fixed the issue.  Many thanks!

**Comment by BreakBB** [comment]
Great, thanks for the fast response 👍
