### ISSUE TITLE
Caravan Quest in Desolace

### ISSUE THREAD

**Issue by East113** [AeroScripts/QuestieDev#1214]
## Description
The two caravan quest in Desolace have bad start locations on the current map. Currently the both show as starting midway along the route, but one starts at one end and the other at the other end of route. Would be a lot better if this was reflected on the map.

Gizelton Caravan and Bodyguard for Hire.

## Wowhead link
https://classic.wowhead.com/quest=5821/bodyguard-for-hire
https://classic.wowhead.com/quest=5943/gizelton-caravan

**Comment by BreakBB** [comment]
Thanks for your report! I fixed this just yesterday with 90e2f192d76123a35728c3c5e4246e5a3a3d5689 so it will be included in our next release
