### ISSUE TITLE
Quest: The Flawless Flame & A Taste Of Flame showing quest items available from incorrect mobs

### ISSUE THREAD

**Issue by mclift7425** [AeroScripts/QuestieDev#1216]
## Bug description
<https://classic.wowhead.com/quest=3442/the-flawless-flame>
Quest is picked up in Searing Gorge from Kalaran Windblade. The objects of the quest are: Heart Of Flame and Golem Oil. Questie marks Dark Iron dwarves in the area as being sources for these quest items, but Wowhead verifies the dwarves do not drop these items. NOTE: The image provided below does not display these quest items because I had completed this quest when the pic was taken.

<https://classic.wowhead.com/quest=4022/a-taste-of-flame>
Quest is picked up in Burning Steppes from Cyrus Therepentous. The object of the quest is Black Dragonflight Molt. Questie marks Dark Iron dwarves, elementals & War Golems in Searing Gorge as being sources for these quest items, but Wowhead verifies these mobs do not drop this item.

![WoWScrnShot_100219_235601](https://user-images.githubusercontent.com/56107048/66105662-e30eb300-e570-11e9-913d-5a738b0a69bd.jpg)
![WoWScrnShot_100219_235646](https://user-images.githubusercontent.com/56107048/66105663-e30eb300-e570-11e9-8c08-3b29f6ee9d66.jpg)

## Questie version
<## Version: 4.1.1 BETA>

**Comment by BreakBB** [comment]
Thanks for your report! I will look into this
