### ISSUE TITLE
Console commands to mark quest as complete

### ISSUE THREAD

**Issue by jmell** [AeroScripts/QuestieDev#1218]
## Description

Currently, where there are errors in the database, there is no way to correct this in game.  For example, the quest https://classic.wowhead.com/quest=165/the-hermit becomes unavailable if you speak to the target first.  Although we can fix that quest specifically, it would be nice to be able to do something like:
/questie markDone 165

**Comment by BreakBB** [comment]
The thing is that we get all completed quests from the Blizzard API. We don't store them on our side. But whenever a quest isn't handled correctly on our side we appreciate a report of it, so we can fix the requirements.

Moreover you can shift + leftclick a quest to hide it (which is basically what you need :) )
