### ISSUE TITLE
A Reliquary of Purity not available until Phase 2

### ISSUE THREAD

**Issue by dabachel0r** [AeroScripts/QuestieDev#1219]
## Description
This quest should not be available until Phase 2. Thank you for the good work!

## Wowhead link
https://classic.wowhead.com/quest=5527/a-reliquary-of-purity#comments

## Screenshots
![image](https://user-images.githubusercontent.com/1662544/66131055-0aa65f80-e5f3-11e9-98cc-ff7e691ece1b.png)

## Questie version
Version: 4.1.2 BETA 104

**Comment by BreakBB** [comment]
This quest is available if you have been to Dire Maul once. Check [this comment](https://classic.wowhead.com/quest=5527/a-reliquary-of-purity#comments:id=3155054:reply=1329712).

But such events are really hard to track for us
