### ISSUE TITLE
Unable to use Questie :(

### ISSUE THREAD

**Issue by tylershatto** [AeroScripts/QuestieDev#122]
Questiequest.lua attempt to call global "questiecompat_getquestlogtitle" a nil value

Every time I try to use Questie, I get this error on login. (referencing line 264). When I click OK, I get the same error, this time referencing line 157. That one doesn't going away when I click OK, making questie unusable for me. :( Maybe I don't have QuestieCompatibility installed in the right place? I tried installing it in interface/addons/ and interface/addons/questie and it didn't work either way.

Thanks for all your wonderful efforts!

**Comment by Schaka** [comment]
When you download it, there are 2 files in the zipped archive. You put both ofthem in your Interface\AddOns folder. That's all there is to it. It's just 2 addons.
