### ISSUE TITLE
Showing lower level quests

### ISSUE THREAD

**Issue by jmartinez46** [AeroScripts/QuestieDev#1220]
Would it be possible to add the ability to see lower level quests beyond 10 levels below current level. I think it would be helpful for anyone who is a bit of a completionist or if there is a specific reward from a lower level quest that is wanted and it is beyond 10 levels below current level. In particular class quests that are skipped for ease of leveling and time come to mind.

**Comment by BreakBB** [comment]
For showing all low level quests there ready exists the "show all below level" checkbox in the general tab, just above the level sliders.
