### ISSUE TITLE
When picking up loot in Dun Morogh it is not going into the bags unless you have them open.

### ISSUE THREAD

**Issue by Malumunus** [AeroScripts/QuestieDev#1221]
## Bug description

If your questing and you go to look an object, it does not go into your bag, It gives the brief hint of something being looted, the sound of picking something up but no loot goes into the bag.

If you open the bags first, then loot, the items show up. I disabled Questie and it works normal.

**Comment by BreakBB** [comment]
Could you disable all other addons except Questie and try again?

Will the item stay in the mob? Because some mobs simply don't drop anything, but you can "loot" them.
