### ISSUE TITLE
My Journey in chronological order

### ISSUE THREAD

**Issue by carsono311** [AeroScripts/QuestieDev#1222]
Currently, the month listing in My Journey is listed (I assume) alphabetically.  This might be wrong, since I do not have August listed, only October, then September.  I would argue that it is more natural and useful to have it displayed chronologically, so September, then October.  Thank you for your time and effort with this wonderful project!

**Comment by BreakBB** [comment]
@carsono311 So your journey doesn't look like this?

![image](https://user-images.githubusercontent.com/33514570/67801756-271aa800-fa8a-11e9-8d96-669f0867e7f2.png)

**Comment by carsono311** [comment]
To be honest, I deleted my original character and can no longer verify the issue.  I would assume however that since yours is correct, it must have been fixed.  Thank you.
