### ISSUE TITLE
Quest #3123 Testing the Vessel

### ISSUE THREAD

**Issue by Aloki** [AeroScripts/QuestieDev#1227]
## Description
Quest objective not showing. https://classic.wowhead.com/npc=2927/vicious-owlbeast, https://classic.wowhead.com/npc=2928/primitive-owlbeast and https://classic.wowhead.com/npc=2929/savage-owlbeast NPC are suitable for this quest.

## Wowhead link
https://classic.wowhead.com/quest=3123/testing-the-vessel

## Questie version
4.1.2 BETA 140 87c6ed0

**Comment by shkabo** [comment]
I wil ltag along on this issue, that whole quest chain is not counted when objectives are completed, also in tanaris quest https://classic.wowhead.com/quest=654/tanaris-field-sampling has the same issue.
In general all those quests have ITEM ON USE to get progress, and questie is not counting those objectives as completed when criteria is met. Reloading UI updates tracker, or detracking/tracking quest again also updates it. 
Questie version: 4.1.1 BETA (from curse client), wow EN client

**Comment by BreakBB** [comment]
@shkabo 
Please grab the release v4.1.2 from [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2). We haven't released this version on Twitch/Curseforge yet, but it fixed the issues you encounter with using or creating queat items
