### ISSUE TITLE
Group announce of objectives

### ISSUE THREAD

**Issue by teodias** [AeroScripts/QuestieDev#1228]
Would be cool if QUESTIE could (enabled/disabled in options) announce objectives to the group.

I was with some randoms for ours camping mobs for shredder manual pages.

It would be cool to announce my and see others status on which page completed and which missing.

We shared the pages to complete every members set.

Also would be cool if I can psot by a modifier+mouse click which pages I have spare and which I need :)

Like:
page 5: missing
page 6: found
page 7: found
page 8: missing

so if I mod+click this entry it will post this to a chat channel and my mates can read this

also like:

head of A: missing
claw of B: found
talo of C: missing

or
human skulls: 15/30

**Comment by Gogo1951** [comment]
Hey @teodias ,

With the addition of party-member progress tracking to the tooltips, is this still needed?

Quest Announce https://www.curseforge.com/wow/addons/quest-announce-3 is a great addon for announcing your progress. 

Can we close this?

**Comment by Gogo1951** [comment]
Reversed thinking on this. Should look into pulling code from Quest Announce into Questie.

Suggestion...

Only have the announce at the end of a quest, literally every time someone has it announce incrementally I want to strangle them. (=

And so a bit of advertising with announce.

> Questie | Completed 7 Small Spider Legs for Recipe of the Kaldorei!

> Questie | Completed {count needed} {item needed} for {quest name}!

Output options should be in party, raid, or say (default to party).

**Comment by Gogo1951** [comment]
Hey @BreakBB,

I think that Questie has a huge market share, but I think one small thing that could improve it would be adding this quest completion notice to party chat. I run another addon, called "Quest Announce 3" (previously mentioned in comments) and with it I'm constantly asked, "Hey, where did you get that quest, is it sharable?" It's a great reminder to get a bit more XP, and people dig XP.

Would like to encourage you to bump up priority on this. (=

**Comment by Gogo1951** [comment]
This should use the new links! It'll be so cool to have a link, ideally with quest rewards, pop up for others to see what they are missing if they aren't on the quest. (=

**Comment by Gogo1951** [comment]
This was added a while back. Closing it. (=
