### ISSUE TITLE
Iron Coral doesn't show

### ISSUE THREAD

**Issue by Zardilann** [AeroScripts/QuestieDev#1230]
## Description
The quest Iron Coral doesn't show on the map.

## Wowhead link
https://classic.wowhead.com/quest=1708/iron-coral

## Questie version
411

**Comment by BreakBB** [comment]
@Zardilann At what level did you accept this quest? It is a level 29 quest so with the default Questie settings this quest won't show up if you're not at least level 22.

**Comment by Zardilann** [comment]
I accepted the quest at level 35.

**Comment by BreakBB** [comment]
You mean the quest itself I guess? And did you enable the option to show low level quests? By default Questie shows quests only 5 level below your own.

**Comment by Zardilann** [comment]
Aye, it was the quest itself that didn't show. I had Questie set up to show all quest levels.

**Comment by BreakBB** [comment]
@Zardilann Could you run `/dump IsQuestFlaggedCompleted(1704)` and report the output?

**Comment by Zardilann** [comment]
[1]=false

**Comment by BreakBB** [comment]
Thanks, we had a pre quest listed which seems not be required in Classic.

**Comment by SpareSimian** [comment]
Fire Hardened Mail is required. I'm level 30 and haven't turned that in (still have to run RFK). The ! for Iron Coral is showing on the map and minimap for Ironforge but the quest giver doesn't offer it.

**Comment by SpareSimian** [comment]
Completing this quest is supposed to unlock all the other warrior armor quests:

https://classic.wowhead.com/quest=1701/fire-hardened-mail
