### ISSUE TITLE
Sunscorched Shells doesn't show

### ISSUE THREAD

**Issue by Zardilann** [AeroScripts/QuestieDev#1231]
## Description
The quest Sunscorched Shells doesn't show on the map.

## Wowhead link
https://classic.wowhead.com/quest=1710/sunscorched-shells#comments

## Questie version
411

**Comment by BreakBB** [comment]
The quest itself or the objective for it?

**Comment by Zardilann** [comment]
The quest itself didn't show. I had Questie set to show all quest levels.

**Comment by BreakBB** [comment]
@Zardilann Could you run `/dump IsQuestFlaggedCompleted(1703)` and report the output?

**Comment by Zardilann** [comment]
[1]=false

**Comment by BreakBB** [comment]
Same as with the other issue. Pre quest isn't required.
