### ISSUE TITLE
Missing map markers for quest

### ISSUE THREAD

**Issue by teodias** [AeroScripts/QuestieDev#1235]
no map markers for this quest?

![image](https://user-images.githubusercontent.com/51795821/66270999-8275c380-e859-11e9-955b-81066ceb5895.png)

**Comment by teodias** [comment]
also no tooltip info on the mobs

**Comment by teodias** [comment]
after some time (10minutes?) everything worked again?

**Comment by teodias** [comment]
now i didn't get the marker for an available quest:
![image](https://user-images.githubusercontent.com/51795821/66271465-91ab4000-e85e-11e9-90f7-87ef47398cf0.png)

**Comment by BreakBB** [comment]
Please update Questie and check again. Those quests has been working for me.

**Comment by BreakBB** [comment]
Assume this is fixed.
