### ISSUE TITLE
Wasteland quest not shown on map

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#1236]
Questie v4.1.2
Hunter level 55.

This quest is not shown on map even though I can pick it up:
https://classic.wowhead.com/quest=1124/wasteland

/reload doesn't help.

**Comment by BreakBB** [comment]
@Painstormx Could you run the following command and report the output please:

`/dump IsQuestFlaggedCompleted(1123)`
`/dump IsQuestFlaggedCompleted(6762)`

**Comment by Painstormx** [comment]
1123 - false
6762 - true

**Comment by BreakBB** [comment]
This has been fixed with 4a1fcabf45c1f5b6be65291fb92e5ddff2370e30 and will be included in v4.1.3
