### ISSUE TITLE
Quest Tracker Suggestion

### ISSUE THREAD

**Issue by hazlema** [AeroScripts/QuestieDev#1237]
Instead of creating a quest tracker from scratch, why not just modify a version of MonkeyQuest to send events to Questie for creation of the arrow,

**Comment by BreakBB** [comment]
Relying on another addon would result in a dependency to it and that would have multiple downsides:

1) We are limited to the license of the addon
2) We might be limited by the features of MonkeyQuest and it would be harder to add new stufd
3) It won't integrate in our code very well and might be harder to maintain

And moreover our tracker hasn't really been written from scratch, but has been ported from vanilla to Classic.
We now we're lacking some really useful features that are available elsewhere, but they're already on our list. We also hope to have more time/people soon :tm: for features :+1:
