### ISSUE TITLE
Lost my arrow

### ISSUE THREAD

**Issue by Doowaadiddy** [AeroScripts/QuestieDev#124]
So I was just clicking around and managed somehow to pull my arrow off screen and now cannot get it back.  Is there a way to reset the arrow to the default position?

**Comment by Schaka** [comment]
It gets stored in your SavedVariables.txt, which stores all icon positions of default blizzard frames AND some frames whose position isn't specifically stored externally.

**Comment by SpareSimian** [comment]
I have no SavedVariables.txt. Did you mean some lua file under wtf\Accounts\account-name\SavedVariables? Or in wtf\Config.wtf? I don't see such a setting in the latter file and the Questie.lua file is quite large. I'm losing my minimap player arrow when I switch back and forth between Carbonite and Questie and a reloadui doesn't restore it, but a full restart of the game does.
