### ISSUE TITLE
Opening quest log from tracker means log can't be closed with escape

### ISSUE THREAD

**Issue by yarko1967** [AeroScripts/QuestieDev#1240]
## Bug description
If the quest log is closed, and I use the quest tracker to open a quest in the quest log, for example, by right-clicking the quest title in the tracker and selecting Show in Quest Log, the proper quest opens in the quest log as expected. However, I am unable to close the quest log with the escape key as I am able to when I open the quest log normally.

## Screenshots
N/A

## Questie version
4.1.1 BETA

**Comment by BreakBB** [comment]
This is fixed with v4.1.2
