### ISSUE TITLE
arcane feedback in iron forge doesn't disappear upon completion of follow up quest (until /reload )

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1241]
## Description
I just got arcane feedback in Stormwind's cathedral and noticed the quest arcane feedback in iron forge right after. (which simply sends you to stormwind, I found out later on)
I went there but couldn't accept the quest anymore.
I used the deeprun tram to get there. The quest still showed up on the map.
Only /reload made the marker disappear.

I guess, you just need to check for a certain trigger to update the list of available quests right after arcane feedback.

## Wowhead link
https://classic.wowhead.com/quest=5677/arcane-feedback

## Screenshots
https://i.imgur.com/jMls7CG.png

## Questie version
4.1.1

**Comment by BreakBB** [comment]
With the latest improvements to our code such issues shouldn't happen any more (or at least less) :)

I checked the data on our side and the quests are correctly marked as exclusive to each other.
