### ISSUE TITLE
Seasoned Wolf requires cooking skill of 50

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1242]
## Description
Seasoned Wolf Quest shows up on the map even though I don't have the required cooking skill of 50, yet.

## Wowhead link
https://classic.wowhead.com/quest=90/seasoned-wolf-kabobs#english-comments

## Questie version
4.1.1

**Comment by BreakBB** [comment]
This is fixed by eb3da88954c0c27758fcd78d5b5443fd8f434698 and will be included in v4.1.3
