### ISSUE TITLE
Addition to #1228

### ISSUE THREAD

**Issue by teodias** [AeroScripts/QuestieDev#1244]
Hi,

if #1228 is realized, then an cool addition could be listing the status of objectives of group members.

Example:

Human Skulls: 12/30 (PlayerA 9/30, PlayerB 22/30, PlayerC 18/30)

Or:
Shredder operating manual page 1: 0 (PlayerA 2, PlayerB 4, PlayerC 0)
Shredder operating manual page 2: 3 (PlayerA 0, PlayerB 2, PlayerC 4)
Shredder operating manual page 3: 2 (PlayerA 3, PlayerB 1, PlayerC 0)
Shredder operating manual page 4: 5 (PlayerA 0, PlayerB 1, PlayerC 0)

So we can see who needs which object and we can share.

**Comment by BreakBB** [comment]
With the release of v5.0.0 QuestieComms has been integrated which show you the objectives of quest members like this:

![image](https://user-images.githubusercontent.com/33514570/67801897-7234bb00-fa8a-11e9-946e-2d1f83effd9a.png)
