### ISSUE TITLE
Quest #585 - Speaking with Nezzliok

### ISSUE THREAD

**Issue by wow-classic** [AeroScripts/QuestieDev#1247]
## Description
One of the three marks is not set correctly.

## Wowhead link
https://classic.wowhead.com/quest=585/speaking-with-nezzliok

## Questie version
Version: 4.1.2 BETA 121 dff5a12

**Comment by BreakBB** [comment]
@wow-classic Could you tell us which marker is not correct? Our data matches the ones listed on Wowhead

**Comment by iron217** [comment]
> @wow-classic Could you tell us which marker is not correct? Our data matches the ones listed on Wowhead

Zul'Mamwe Trophy 47.6, 39.5 only this one is displayed now
 
questie 4.2.1 ruru client

**Comment by BreakBB** [comment]
Our data looks good on this:

```lua
[2891] = {"Balia'mah Trophy Skulls",nil,nil,{[33]={{46.13,32.33},},},33,},
[2892] = {"Ziata'jai Trophy Skulls",nil,nil,{[33]={{42.21,36.11},},},33,},
[2893] = {"Zul'Mamwe Trophy Skulls",nil,nil,{[33]={{47.65,39.54},},},33,},
```

So I guess this is related to a tooltip bug we currently have. This should be fixed in the next release.

**Comment by BreakBB** [comment]
This should be fixed with the latest releases. Please report back if it's not.
