### ISSUE TITLE
Remove map marker for [Signal for Pickup]

### ISSUE THREAD

**Issue by AnnaManiac** [AeroScripts/QuestieDev#1249]
## Description
This quest marker should be hidden from the map.  The quest is only for someone who accidentally uses up the item or gets rid of it and needs a replacement.

## Wowhead link
https://classic.wowhead.com/quest=3483/signal-for-pickup

## Screenshots
![WoWScrnShot_100719_172955](https://user-images.githubusercontent.com/54857214/66350004-27f76880-e928-11e9-8067-dab3b3b1e3df.jpg)

## Questie version
Version: 4.1.2 BETA

**Comment by BreakBB** [comment]
Hmmm... This should be fixed with 4.1.2.

You're sure you're not on the quest "Signal for Pickup" belongs to?

**Comment by AnnaManiac** [comment]
> 
> 
> Hmmm... This should be fixed with 4.1.2.
> 
> You're sure you're not on the quest "Signal for Pickup" belongs to?

I did the quest in Azshara like 2 weeks ago.  The map marker is now stuck permanently on the map.  You can't even talk to the dwarf that this marker belongs to any more.

**Comment by BreakBB** [comment]
Okay, thanks for the report. I will look into it! For now you can simply shift + leftclick to ignore the quest icon

**Comment by BreakBB** [comment]
Closing this in favr of #1256
