### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by Cafnio** [AeroScripts/QuestieDev#125]
Hi there.

I'm dropping an image, so its easyer to see:

http://i.gyazo.com/332b260bb3d11f2b955d4b736fd17d2b.png

- This error appeared as soon as I entered into silithus
- There's a problem with quest tracker
- On questlog, if I shift click a quest, it only appears on questie if there is no "check" icon. If there is, it doesnt show (should be other way arround).
- Some quests I can't put in there.

Sugestions:
- Add an anchor to move it easly

Guses that's all. Cheers and keep the good work

**Comment by Schaka** [comment]
We do not support Questie 1.0 anymore.
