### ISSUE TITLE
Map marker for [They Call Him Smiling Jim] forever stuck on the map

### ISSUE THREAD

**Issue by AnnaManiac** [AeroScripts/QuestieDev#1250]
## Description
Alliance starts with [James Hyal] and the followup [James Hyal]  OR  [They Call Him Smiling Jim] (you can do only one of the prerequisites).  If you did the [James Hyal] prerequisite, then the map marker for [They Call Him Smiling Jim] is stuck on the map forever.

## Wowhead link
https://classic.wowhead.com/quest=1282/they-call-him-smiling-jim

## Screenshots
![WoWScrnShot_100719_174809](https://user-images.githubusercontent.com/54857214/66351107-ff24a280-e92a-11e9-9820-52502a8f69b9.jpg)

## Questie version
Version: 4.1.2 BETA

**Comment by Ben1220** [comment]
I am having this issue as well

**Comment by lifeingote** [comment]
I am also having this issue.

**Comment by BreakBB** [comment]
Actually as stated in #875 it should be possible to complete both quests. Can you ensure this is not the case?

**Comment by BreakBB** [comment]
Fixed with 1698b260632ea658f040b25656c2b896fe798c22
