### ISSUE TITLE
Get Me Out Of Here no showing up anywhere

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1251]
The Desolace escort quest Get Me Out Of Here! isn't showing up in the minimap, map, or Quests by Zone list.

https://classic.wowhead.com/quest=6132/get-me-out-of-here

![WoWScrnShot_100719_235208](https://user-images.githubusercontent.com/54936174/66351622-3791a400-e95e-11e9-9f53-e2779f335e62.jpg)

V4.1.1

**Comment by Cerby3BR** [comment]
![WoWScrnShot_100819_000130](https://user-images.githubusercontent.com/54936174/66353792-3151f680-e963-11e9-904b-e3fe3e985aff.jpg)

Also for some reason it shows up as complete in the tracker even though it isn't.

**Comment by drejjmit** [comment]
This quest was hidden for hordes due to a report that it was alliance only. But as you show it's available for hordes as well.

**Comment by BreakBB** [comment]
Related to d6d01838136740590547f39a249b6dad61058036
