### ISSUE TITLE
The God of Hakkar - filling the egg is not tracked

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1253]
## Description
Questie doesn't update/trigger the quest The God Hakkar upon filling the egg with the essenz.

## Wowhead link
https://classic.wowhead.com/quest=3528/the-god-hakkar
https://classic.wowhead.com/spell=12735/fill-the-egg-of-hakkar#used-by-item

## Screenshots
![](https://i.imgur.com/dYhUA3B.png)

## Questie version
4.1.1

**Comment by BreakBB** [comment]
Issues where you have to use or "create" quest items are already fixed with v4.1.2. You can grab a copy here on Github. It will be released on Twitch very soon as well
