### ISSUE TITLE
Alliance quests showing for Horde

### ISSUE THREAD

**Issue by GeekBoyMN** [AeroScripts/QuestieDev#1254]
2 Alliance quests https://classic.wowhead.com/quest=3741/hilarys-necklace in Redridge Mountains and https://classic.wowhead.com/quest=103/keeper-of-the-flame in Westfall are showing on my level 15 Horde mage's map. 

![WoWScrnShot_100819_105545](https://user-images.githubusercontent.com/56312968/66412037-5f165a00-e9ba-11e9-9e00-9603eafd45fb.jpg)

![WoWScrnShot_100819_105550](https://user-images.githubusercontent.com/56312968/66412049-66d5fe80-e9ba-11e9-9e30-7a43f54378e3.jpg)

**Comment by BreakBB** [comment]
Combination of #840 and #1025 

These quests can indeed be completed by Horde players
