### ISSUE TITLE
Crystals of Power

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1258]
## Description
The quest Crystals of Power at Ungoro has 4 equal items you need to find. All valid spots, Questie has, are valid for all 4 colors, but each crystal is still marked as one color, meaning if you only need yellow crystals, then only 1/4 of the crystal locatons show up on the map (the others are hidden already). Also: the crystal color isn't correct most of the time, since they are spawned randomly.

## Wowhead link
https://classic.wowhead.com/quest=4284/crystals-of-power

## Questie version
4.1.2

**Comment by Muehe** [comment]
Similar to #1257 this has been disabled intentionally.

Remove from `Database/corrections.lua`:

```
    [11184] = {"Blue Power Crystal",{4284,4382,4384,4386},{},{164658,164778}},
    [11185] = {"Green Power Crystal",{4284,4381,4382,4383},{},{164659,164779}},
    [11186] = {"Red Power Crystal",{4284,4383,4384,4385},{},{164660,164780}},
    [11188] = {"Yellow Power Crystal",{4284,4381,4385,4386},{},{164661,164781}},
```

We should really add a config option for this...

**Comment by Djfe** [comment]
what has been disabled exactly?
or do you mean questie would display 4 lootbags on top of each other, if you show all 4 colors?

**Comment by BreakBB** [comment]
The thing is that the objects you interact with are not the same. Like a Blue Power Crystal (item) is contained in a Blue Color Crystal (object), but not in the other objects.

Are you sure the spawns of the crystals it random so a Blue Power Crystal can spawn where a yellow one was before? If so we could duplicate all the spawns to the objects so each crystal is shown at each position

**Comment by BreakBB** [comment]
@Muehe Couldn't we just take all the spawns for the different color crystals and add them to each crystal? So that every crystal has the same spawns as the others? Because if it is random one spawn point could be every color

**Comment by Djfe** [comment]
I took screenshots of two crystals close too the Flight Point at Un'Goro.
first crystal, no change, the two times it was ready to harvest:
![Wow_2019-10-11_23-19-23](https://user-images.githubusercontent.com/5685512/66793539-1bfa4080-eefe-11e9-9f65-0274315714a2.jpg)
![Wow_2019-10-14_01-24-13](https://user-images.githubusercontent.com/5685512/66793542-20265e00-eefe-11e9-8082-6c8686a088ca.jpg)

the second one was blue, green and red so far:
![Wow_2019-10-11_23-20-25](https://user-images.githubusercontent.com/5685512/66793490-ee14fc00-eefd-11e9-87ed-ce01604a0c5d.jpg)
![Wow_2019-10-12_00-27-21](https://user-images.githubusercontent.com/5685512/66793493-f0775600-eefd-11e9-9602-8309df7b991c.jpg)
![Wow_2019-10-14_01-24-57](https://user-images.githubusercontent.com/5685512/66793502-f1a88300-eefd-11e9-8353-73cb78f091d2.jpg)


I'll take more screenshots the next time, I'm there

**Comment by BreakBB** [comment]
@Djfe Thank you very much for coming back to this and providing such screenshots! It's very hard for us to test since most of us are not even close to max level.

I will fix this now and you'll find the fix in the next release 👍

**Comment by Djfe** [comment]
no problemo ^^ :)
