### ISSUE TITLE
Another bug report

### ISSUE THREAD

**Issue by AfxousaAjagara** [AeroScripts/QuestieDev#1261]
## Bug description

Date: 2019-10-09 18:35:32
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\QuestieTooltips.lua line 80:
   Usage: UnitGUID("unit")
Debug:
   [C]: UnitGUID()
   Questie\Modules\QuestieTooltips.lua:80:
      Questie\Modules\QuestieTooltips.lua:75
   [C]: ?
   ...face\AddOns\Quester\libs\AceHook-3.0\AceHook-3.0.lua:95:
      ...face\AddOns\Quester\libs\AceHook-3.0\AceHook-3.0.lua:87
   [C]: SetUnit()
   ..\FrameXML\UnitFrame.lua:291: UnitFrame_UpdateTooltip()
   ..\FrameXML\UnitFrame.lua:277: UnitFrame_OnEnter()
   ...nterface\AddOns\ShadowedUnitFrames\modules\units.lua:530: OnEnter()
   ...nterface\AddOns\ShadowedUnitFrames\modules\units.lua:517:
      ...nterface\AddOns\ShadowedUnitFrames\modules\units.lua:515
Locals:
(*temporary) = nil

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.01.11302
  AtlasBattlegrounds, vv1.45.00.11302.00
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasTransportation, vv1.45.00.11302.00
  AtlasLootClassic, vv1.2.2
  AtlasLootClassicDungeonsAndRaids, vv1.2.2
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  ClassicAuraDurations, v
  ClassicCastbars, vv1.1.0
  ClassicCastbarsOptions, v
  ClassicCodex, v1.2.2
  ClassicSpellActivations, v
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.14
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  FindParty, v1.3 Classic-fanfix
  GatherMate2, v1.45.5
  GTFO, v4.50.1
  Immersion, v1.2.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LeatrixMaps, v1.13.34
  LeatrixPlus, v1.13.34
  OmniCC, v8.2.5
  Quester, v1.13.2.1
  Questie, v4.1.2 BETA 121 dff5a12
  RealMobHealth, v2.13
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11302-1.0.7
  VendorPrice, v1.2.9
  WeakAuras, v2.15.2
  BlizRuntimeLib_koKR v1.13.2.11302 <none>
  (ck=6ee)

## Questie version
Up-to-date version

**Comment by drejjmit** [comment]
Same error as your previous report: https://github.com/AeroScripts/QuestieDev/issues/1259

**Comment by BreakBB** [comment]
Duplicate of #1255
