### ISSUE TITLE
Rescue OOX quests

### ISSUE THREAD

**Issue by badtoaster** [AeroScripts/QuestieDev#1264]
## Description

"Rescue OOX-22/FE!" and "Rescue OOX-17/TN!" shows as active even if completed. 
And I think (but not tested) "Rescue OOX-09/HL!" is broken too.

## Wowhead link

https://classic.wowhead.com/quest=2767/rescue-oox-22-fe
https://classic.wowhead.com/quest=648/rescue-oox-17-tn
https://classic.wowhead.com/quest=836/rescue-oox-09-hl

## Screenshots

![17](https://user-images.githubusercontent.com/49612688/66489929-60a95600-ea7e-11e9-8488-00a45ee1b739.PNG)
![22](https://user-images.githubusercontent.com/49612688/66489930-60a95600-ea7e-11e9-8099-f2c58a4dcef6.PNG)

## Questie version

Questie-v4.1.2_BETA-dff5a12

**Comment by BreakBB** [comment]
Just to make sure I understand you correctly: You did these quests and once you completed them Questie didn't update (no ? was shown)?

**Comment by BreakBB** [comment]
@badtoaster Any news on this?

**Comment by skink-in-trees-shade** [comment]
@BreakBB I've encountered this issue with all 3 quests too. The problem is that these quests, while being completed (but not turned in yet!), still are displayed as active, i.e. with the search icon.

If I remember correctly, /reload fixes this until the next logon.
