### ISSUE TITLE
Quests by zone problem

### ISSUE THREAD

**Issue by Chrifen** [AeroScripts/QuestieDev#1267]
## Bug description
My questie have a problem after update yesterday with the quest by zone menue. I can no longer see quests that are not completed in the drop down menue. The quests that are completed are still showing up.

## Screenshots

![WoWScrnShot_100919_214334](https://user-images.githubusercontent.com/56366806/66514782-22dc1a00-eade-11e9-874b-67a80a29ea6c.jpg)

## Questie version
V4.1.2_dff5a12 BETA

**Comment by BreakBB** [comment]
Thanks for your report and sorry for the trouble. This has already been fixed and will be included in the upcoming v4.1.3, which will be ready very soon ™️
