### ISSUE TITLE
Cartographer Compatiblity

### ISSUE THREAD

**Issue by jasskin** [AeroScripts/QuestieDev#127]
I am unable to see quest makers and such from questie with Cartographer running is there a setting or is it just not compatible?

**Comment by Schaka** [comment]
Please make sure you are running Questie 2.0.10. Questie 2 works perfectly with Cartographer or any other map addon. I have personally not even used it without Cartographer except when developing.

**Comment by jasskin** [comment]
I am running 2.0.10.

**Comment by jasskin** [comment]
I turned off every mod  except Cartographer and Questie still don't have any nodes on the map.

**Comment by Schaka** [comment]
If Questie shows no notes, are you sure you're even tracking any quests? If no quests are being tracked (anything in your tracker window?) it will not show you anything.

**Comment by jasskin** [comment]
yeah all the quest are in the tracking window they show on the minimap just not the Main map

**Comment by Schaka** [comment]
Try enabling Questie as your only addon and see if the issue persists. If it does, delete all Questie files from your WTF folder. If not, you know for a fact you have another addon that messes with Questie in some way.

**Comment by jasskin** [comment]
The map icons show up with just questie on, but they also show up with all mods on and just cartographer turned off.

**Comment by Schaka** [comment]
This is where I got mine, it should work just fine: http://dl.dropbox.com/u/5665491/Addons/Cartographer.zip

**Comment by jasskin** [comment]
Yeah that is the same one I have still doesn't work with the overlay for me. If I figure it out Ill post it.

**Comment by jasskin** [comment]
Well I am feel bad just realized that the nodes are linked to the transparency option that I was turned down. Thank you for taking the time to work with me and I hope I didn't take up to much tip with a silly question.
