### ISSUE TITLE
Quest #4496 Bungle in the Jungle

### ISSUE THREAD

**Issue by Aloki** [AeroScripts/QuestieDev#1270]
## Description
Quest objective Gorishi Scent Gland marked as contained in Un'Goro Dirt Pile, but it is dropped from mobs.

## Wowhead link
https://classic.wowhead.com/quest=4496/bungle-in-the-jungle
https://classic.wowhead.com/item=11837/gorishi-scent-gland

## Questie version
4.1.2 BETA

**Comment by BreakBB** [comment]
Is your WoW client in a language different to English?

**Comment by Aloki** [comment]
@BreakBB No, I use the English locale.

**Comment by Aloki** [comment]
@BreakBB This seems to be a Questie bug. It was the same with quest #1299, and now with quest #3442 The Flawless Flame. This time I did an add-on reload and the bug disappeared.
