### ISSUE TITLE
Demon Dogs - Missing tooltip/nameplate info

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#1273]
Questie v4.1.2
https://classic.wowhead.com/quest=5542/demon-dogs

The Plaguehound Runt mobs have no info Questie in their tooltip or nameplate.

**Comment by BreakBB** [comment]
This could already be fixed with 4.2.0, but will definitely be fixed in the next release. We're currently changing the way to determine how we determine which "names" are needed for a quests and how they're matched on our data.
