### ISSUE TITLE
Clicks not registering and wont move camera sometimes

### ISSUE THREAD

**Issue by Tehomen89** [AeroScripts/QuestieDev#1274]
When I am running around the map, some of my clicks wont register and either the camera won't move, or I am unable to click on mobs. I disable my add-ons individually and found that Questie was the causing the issue.

## Questie version
v4.1.2_dff5a12

**Comment by BreakBB** [comment]
Could you try to disable all addons except Questie and see if the issue still occurs? This sounds like a conflict to another addon

**Comment by BreakBB** [comment]
@Tehomen89 Any news on this?

**Comment by BreakBB** [comment]
Assuming this is fixed.
