### ISSUE TITLE
Missing Available Quests

### ISSUE THREAD

**Issue by bobbyj9** [AeroScripts/QuestieDev#1275]
Available quests for every zone says 0.

v4.1.2

**Comment by TexFromHell** [comment]
I have the same issue, also does not show which quests are completed but lists them all from the zones as complete.

**Comment by drejjmit** [comment]
This is fixed in the upcoming version :)

**Comment by dknight** [comment]
Same issue, they just dissappered

**Comment by BreakBB** [comment]
Duplicate of #1239
