### ISSUE TITLE
how do I deactivate the automatic quest assumption?

### ISSUE THREAD

**Issue by delaware1999** [AeroScripts/QuestieDev#1277]
## Question

how do I activate the automatic quest assumption?

I Used Questi 1 month ago.. There was a setting to deactivate the automatisch Quest Assumption.

Now I startet a new char and installed the questi.. But I cant not find this option and can not deactivate it.. Everytime I speak with a Quest giver my new char takes the Quest and I cant read it.. How can I change that to normal ? I searched the complete settings and cant find it..

Please help

**Comment by BreakBB** [comment]
@delaware1999 If you have a look at the [FAQ](https://github.com/AeroScripts/QuestieDev/wiki/FAQ) you'll see that automatically accepting/completing quests is not a feature of Questie and never has been! It is most likely related to AAP, Leatrix or Quest Codex.

**Comment by delaware1999** [comment]
yes ok but I dont have them installed !  What is AAP   and Leatrix or Quest Codex.. I dont know them.. Is the auto accept maybe a funvtion from the stock settings of WOW ?

**Comment by BreakBB** [comment]
No, there has to be another addon. Azeroth Auto Pilot is AAP.

**Comment by delaware1999** [comment]
Ok this was my fault.. I had installed  Quest codex.. sorry
