### ISSUE TITLE
Persistent Quest Available Marker: Seasoned Wolf Kabobs (Duskwood)

### ISSUE THREAD

**Issue by Syst3mSh0ck** [AeroScripts/QuestieDev#1279]
## Description
The quest available marker (exclamation mark) on both the world/regional map and mini-map shows for this quest even though I've already completed it. The quest is given by Chef Grual (73.8, 43.6) in Darkshire. He is also involved with 2 other quests ie Dusky Crab Cakes and Return to Jitters.

## Wowhead link
https://classic.wowhead.com/quest=90/seasoned-wolf-kabobs

## Questie version
4.1.1 BETA (didn't try 4.1.2 due to regressions already reported)

Thanks for all you're hard work. It is much appreciated by all! :)

**Comment by BreakBB** [comment]
This is fixed with v4.2.0
