### ISSUE TITLE
Get the Gnomes/Goblins Drunk

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1280]
Get the Gnomes Drunk and Get the Goblins Drunk are exclusive to each other: once you accept one, the other becomes unavailable, and permanently so once completed. This isn't reflected in Questie; Get the Goblins Drunk is still tagged as available on the map even though I completed the Gnomes one.

https://classic.wowhead.com/quest=1120/get-the-gnomes-drunk
https://classic.wowhead.com/quest=1121/get-the-goblins-drunk

Questie 4.1.2

**Comment by BreakBB** [comment]
@Cerby3BR Can you grab v4.2.1 and see if the quest is still shown? The quests are already marked exclusive to each other in our data.

**Comment by Cerby3BR** [comment]
Sorry, I completed the next quest in the line and both markers aren't on the map anymore, so inconclusive. As of 5.0.1, Get the Goblins Drunk is still in the Available Quests list though.

**Comment by BreakBB** [comment]
Fixed with e40e496f90af93d88d9c468cdcecd483e9b9a44d
