### ISSUE TITLE
[9] Frostmane Hold

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#1283]
## Bug description
Not showing up.
I don't think #881 is correct. 

## Screenshots
![image](https://user-images.githubusercontent.com/15526476/66699346-6012f880-ece6-11e9-9437-61b5eff47224.png)

## Questie version
v4.1.2_1ffcec5

**Comment by AeroScripts** [comment]
A friend said this wasn't showing for him on the latest release, so I'm reopening this for now

**Comment by Gogo1951** [comment]
I was able to verify that this quest shows up on the minimap as available, and the objectives show up once the quest is accepted. This issue should be closed.
