### ISSUE TITLE
[10] Mirror Lake

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#1286]
## Description
No marker at 28.6, 61.4 in Elwynn Forest

## Wowhead link
https://classic.wowhead.com/quest=1861/mirror-lake

## Questie version
4.1.2

**Comment by drejjmit** [comment]
Also when completing this you can no longer pick up [[10] Mage-tastic Gizmonitor](https://classic.wowhead.com/quest=1880/mage-tastic-gizmonitor)

![image](https://user-images.githubusercontent.com/15526476/66703139-b0528080-ed0f-11e9-911e-552d3d306bd5.png)

**Comment by BreakBB** [comment]
Exclusivity has been fixed in fb5fa6dec8263e6542306113e620029abee076b8
