### ISSUE TITLE
Alliance Quest "Shadowshard Fragments" not showing up 

### ISSUE THREAD

**Issue by hopdenakker** [AeroScripts/QuestieDev#1288]
## Description
The alliance quest Shadowshard Fragments is not showing up (my level: 39)

## Wowhead link
https://classic.wowhead.com/quest=7070/shadowshard-fragments

## Questie version
4.1.2 BETA 121 dff5a12

**Comment by drejjmit** [comment]
Do you mean objectives not showing up or the available quest marker not showing up?

![image](https://user-images.githubusercontent.com/15526476/66707007-b0b44100-ed3a-11e9-87c8-ecb70753f80a.png)
For me

**Comment by hopdenakker** [comment]
Aha, I see ... I was talking about that "available questmarker", and that's showing up for me as well (in Theramore).

For me though, Archmage Tervosh is located at the first tower outside of Theramore. But maybe that's only because I was on the "Missing Diplomat" quest that has you talking to him...

Maybe this can be closed...

**Comment by BreakBB** [comment]
@hopdenakker I had a quick look at our data for this quest and you're right. We had just one spawn for the Archmage listed in our data. I added two more spawns.

**Comment by AstroCat00** [comment]
I'm getting him in Ironforge now!

**Comment by BreakBB** [comment]
Yeah I used the wrong ID for it, sorry. It is already patched on the master branch.

**Comment by AstroCat00** [comment]
Thanks for the reply and love the mod. No worries! :)
