### ISSUE TITLE
Find Agmond quest missing

### ISSUE THREAD

**Issue by kernighan** [AeroScripts/QuestieDev#1289]
## Bug description
Alliance only quest, Find Agmond (https://classic.wowhead.com/quest=738/find-agmond) does not show up via Questie.  Found it by accident when running someone through the Loch Modan quests.

**Comment by kernighan** [comment]
Questie version 4.2.0

**Comment by kernighan** [comment]
Note: Character level 39 (In case it's in the DB but with the wrong pickup level requirement)

**Comment by BreakBB** [comment]
Can you run `/dump IsQuestFlaggedCompleted(707)` and report the output please?

**Comment by kernighan** [comment]
```
[11:09:03] Dump: value=IsQuestFlaggedCompleted(707)
[11:09:03] [1]=false
```

**Comment by kernighan** [comment]
Looks like 707 is a bread crumb

**Comment by BreakBB** [comment]
Yes this is correct. Thanks for your report, it is very appreciated! A fix will be in the next release 👍
