### ISSUE TITLE
A taste of flamme

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1291]
## Description
I just started "a taste of flamme", but questie still shows the yellow question mark on the map.
/reload makes the question mark disappear, so some sort of trigger is missing.

## Wowhead link
https://classic.wowhead.com/quest=4022/a-taste-of-flame

## Screenshots
![](https://i.imgur.com/9WKrbw6.jpg)

## Questie version
4.1.2

**Comment by BreakBB** [comment]
Could be related to #860 Since a `/reload` removes the mark this is most likely fixed with 4.2.1 or the next release! Thanks for your report (again) 👍
