### ISSUE TITLE
Error in the quest [Demon Dogs]

### ISSUE THREAD

**Issue by SubbyDK** [AeroScripts/QuestieDev#1294]
The quest [[Demon Dogs]](https://classic.wowhead.com/quest=5542) are showing the wrong mobs.

When your holding the mouse over [Plaguehound Runt](https://classic.wowhead.com/npc=8596) it's not showing that you have to kill them, but if your holding the mouse over the [Plaguehound](https://classic.wowhead.com/npc=8597) they are shown as kill on both of them.

**EDIT**
Just discovered that there is the same problem with the quest [[Night Web's Hollow]](https://classic.wowhead.com/quest=380)

[Young Night Web Spider](https://classic.wowhead.com/npc=1504) don’t show tooltips, but [Night Web Spider](https://classic.wowhead.com/npc=1505) show for them both.

**Comment by BreakBB** [comment]
Please use the issue template next time. We need to know which version of Questie you're using.

**Comment by SubbyDK** [comment]
Sorry, is not 100% sure how this is working, first time user.

I'm using version: 4.1.2 BETA 121 dff5a12

**Comment by BreakBB** [comment]
Related to #1273 This should be already fixed or will be in the next release.
