### ISSUE TITLE
Tracker Position Not Releasing

### ISSUE THREAD

**Issue by brianfreytag** [AeroScripts/QuestieDev#1295]
## Bug description
When I click on the tracker, the cursor grabs it, but then it never lets go of it. I can't click on anything else, and can't do anything with the mouse. The only way to get it stop is by tabbing out of the game and closing the WoW window by right clicking it in the task bar and restarting the game.

## Questie version
v4.2.0

**Comment by Skinner927** [comment]
You can also type `/reload ui` but you still can't move the tracker at all.

**Comment by brianfreytag** [comment]
Downgrading to 4.1.2 resolves this. I accidentally click the tracker so often that this makes questing a pain, so it's not even worth it lol
