### ISSUE TITLE
UI Error with Questie Icons

### ISSUE THREAD

**Issue by Lythanas** [AeroScripts/QuestieDev#1296]
## Bug description
When looking around in WoW, icons from Questie's map and mini map show on my screen when my map is closed and when it is open it also shows outside the map. 

## Screenshots
![image](https://user-images.githubusercontent.com/56493789/66709654-915aeb00-ed1d-11e9-8772-c408c4f8cc62.png)
![image](https://user-images.githubusercontent.com/56493789/66709656-ab94c900-ed1d-11e9-9a66-217b38eeea4b.png)
![image](https://user-images.githubusercontent.com/56493789/66709659-bc453f00-ed1d-11e9-9a90-3ce8722e80d7.png)

## Questie version
The Questie version I am using is V4.2.0_3bf27b9

**Comment by Muehe** [comment]
Not a bug, this is the new DBM HUD feature. You can disable it or enable even more types of notes in the Questie Settings.

**Comment by Macfe** [comment]
> Not a bug, this is the new DBM HUD feature. You can disable it or enable even more types of notes in the Questie Settings.

Where exactly?

**Comment by drejjmit** [comment]
DBM HUD tab in ``/questie`` settings

**Comment by Macfe** [comment]
> DBM HUD tab in `/questie` settings

Found it - thank you :)
