### ISSUE TITLE
Zenn's Bidding

### ISSUE THREAD

**Issue by Zardilann** [AeroScripts/QuestieDev#1297]
## Bug description
Zenn's Bidding requires you to kill 3 different mob types to gather items. It only shows the requirements in one the mobs' tooltips.

https://classic.wowhead.com/quest=488/zenns-bidding

## Screenshots
![WoWScrnShot_101319_040658](https://user-images.githubusercontent.com/167260/66709963-14586180-ed6f-11e9-88b5-8dea7a2b64c3.jpg)
![WoWScrnShot_101319_040954](https://user-images.githubusercontent.com/167260/66709976-71541780-ed6f-11e9-9343-ab3084a2af7b.jpg)

## Questie version
4.2

**Comment by BreakBB** [comment]
Merging with #1071
