### ISSUE TITLE
Minimap doesn't display anything since cartographer

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#13]
Since the switch to Cartographer over MapNotes (commit f9e26846889a98db0d49e286e395fe6eb5a22694) the minimap hasn't shown anything (Cartographer doesn't have a minimap thing)

I'm currently working on a new implementation for this, that will allow for multiple notes on the minimap and more direct control over their behavior. I'll post back here with progress

**Comment by Schaka** [comment]
Implemented as of [bea7b92d](!https://github.com/AeroScripts/QuestieDev/commit/bea7b92d5c9c8252c1f8ff28f12804abe011e04c). Needs some more fine tuning eventually.
