### ISSUE TITLE
Mouseover lag/stutter

### ISSUE THREAD

**Issue by frozenreddy** [AeroScripts/QuestieDev#130]
Hi,
I'm using questie and I have identified it via, disabling/enabling various addons, as the cause of some mouseover stutter/lag when I mouseover certain NPCs and mobs. When I mouseover guards or the flight master in Ironforge, for example, there is a split-second stutter and momentary FPS drop. 
Do you know why this is happening and/or do you have any suggestions for fixing it?

**Comment by Schaka** [comment]
related to #107

**Comment by frozenreddy** [comment]
It seemed related to the Alliance quest "Items of Some Importance." Once I finished that quest it stopped. I didn't notice multiple notes in the tooltips.

**Comment by jam3s121** [comment]
Still an issue, i noticed the same problem frozenreddy. Though my gtx 970 was to blame
