### ISSUE TITLE
New questie bug 13/10/19

### ISSUE THREAD

**Issue by Tronadin** [AeroScripts/QuestieDev#1301]
## Bug description

Opened up my minimap when i first logged into the game this morning to see that the quest markers and repeatable quest markers were floating around my screen once i had closed the map down.

## Screenshots

![Questie bug](https://user-images.githubusercontent.com/56500687/66712446-a757c280-ed94-11e9-9566-5681b6f1283c.PNG)

## Questie version

Newest version as i just updated it.

**Comment by BreakBB** [comment]
Have another look at the changelog of v4.2.0. This is a new feature in combination with the DBM addon to show quests and their objectives as a HUD. You can configure it in the "DBM" tab.

**Comment by BreakBB** [comment]
Also a duplicate of #1296
