### ISSUE TITLE
Feathermoon Stronghold: Courier Hammerfall

### ISSUE THREAD

**Issue by dabachel0r** [AeroScripts/QuestieDev#1304]
## Description
There is an exclamation mark in Ironforge that I can do this quest. But I think I did it already and I think I started the quest in Darnassus.
Thanks for the great work!

## Wowhead link
https://classic.wowhead.com/quest=7494/feathermoon-stronghold

## Screenshots
![Feathermoon_Stronghold_1](https://user-images.githubusercontent.com/1662544/66713349-112e9700-edaa-11e9-9fa7-a5c7aa57600c.png)
![Feathermoon_Stronghold_2](https://user-images.githubusercontent.com/1662544/66713351-14298780-edaa-11e9-94c3-77e80bfd6f5b.png)

## Questie version
Version: 4.2.1 0 0f28ee6

**Comment by drejjmit** [comment]
This is a Dire Maul quest. We wanted to unhide them for the release of Dire Maul this upcoming week. Should be available in a few days :)
