### ISSUE TITLE
Error on logging in with 4.2.1

### ISSUE THREAD

**Issue by b-morgan** [AeroScripts/QuestieDev#1305]
2x Questie\Modules\QuestieQuest.lua:18: attempt to index global 'QuestieReputation' (a nil value)
Questie\Modules\QuestieQuest.lua:18: in function `Initialize'
...rfaceQuestie\Modules\QuestieEventHandler.lua:27: in function <...rfaceQuestie\Modules\QuestieEventHandler.lua:22>

Locals:
self = <table> {
 1 = "Questie"
 2 = <table> {
 }
 GetQuestLogHashes = <function> defined @Questie\Modules\QuestieQuest.lua:1090
 ToggleNotes = <function> defined @Questie\Modules\QuestieQuest.lua:43
 AbandonedQuest = <function> defined @Questie\Modules\QuestieQuest.lua:362
 CompleteQuest = <function> defined @Questie\Modules\QuestieQuest.lua:339
 UnhideQuest = <function> defined @Questie\Modules\QuestieQuest.lua:262
 GetAllQuestIdsNoObjectives = <function> defined @Questie\Modules\QuestieQuest.lua:436
 Math_random = <function> defined @Questie\Modules\QuestieQuest.lua:829
 UpdateObjectiveNotes = <function> defined @Questie\Modules\QuestieQuest.lua:499
 Initialize = <function> defined @Questie\Modules\QuestieQuest.lua:13
 GetAllLeaderBoardDetails = <function> defined @Questie\Modules\QuestieQuest.lua:1169
 ForceToMap = <function> defined @Questie\Modules\QuestieQuest.lua:676
 ClearAllNotes = <function> defined @Questie\Modules\QuestieQuest.lua:101
 GetAllQuestIds = <function> defined @Questie\Modules\QuestieQuest.lua:411
 AcceptQuest = <function> defined @Questie\Modules\QuestieQuest.lua:296
 HideQuest = <function> defined @Questie\Modules\QuestieQuest.lua:257
 PopulateQuestLogInfo = <function> defined @Questie\Modules\QuestieQuest.lua:886
 GetAllQuestObjectives = <function> defined @Questie\Modules\QuestieQuest.lua:907
 SmoothReset = <function> defined @Questie\Modules\QuestieQuest.lua:172
 ShouldQuestShowObjectives = <function> defined @Questie\Modules\QuestieQuest.lua:455
 PopulateObjectiveNotes = <function> defined @Questie\Modules\QuestieQuest.lua:850
 UpdateHiddenNotes = <function> defined @Questie\Modules\QuestieQuest.lua:210
 AddAllNotes = <function> defined @Questie\Modules\QuestieQuest.lua:141
 Math_randomseed = <function> defined @Questie\Modules\QuestieQuest.lua:826
 GetRawLeaderBoardDetails = <function> defined @Questie\Modules\QuestieQuest.lua:268
 RemoveQuestHash = <function> defined @Questie\Modules\QuestieQuest.lua:1120
 CalculateAvailableQuests = <function> defined @Questie\Modules\QuestieQuest.lua:1419
 DrawAllAvailableQuests = <function> defined @Questie\Modules\QuestieQuest.lua:1295
 CompareQuestHashes = <function> defined @Questie\Modules\QuestieQuest.lua:1125
 PopulateObjective = <function> defined @Questie\Modules\QuestieQuest.lua:706
 GetCurrentHashes = <function> defined @Questie\Modules\QuestieQuest.lua:1116
 isCompleteByQuestId = <function> defined @Questie\Modules\QuestieQuest.lua:476
 AddFinisher = <function> defined @Questie\Modules\QuestieQuest.lua:511
 AddNewQuestHash = <function> defined @Questie\Modules\QuestieQuest.lua:1109
 GetQuestHash = <function> defined @Questie\Modules\QuestieQuest.lua:1078
 NotesHidden = false
 availableQuests = <table> {
 }
 IsComplete = <function> defined @Questie\Modules\QuestieQuest.lua:495
 _IsCompleteHack = <function> defined @Questie\Modules\QuestieQuest.lua:466
 UpdateQuest = <function> defined @Questie\Modules\QuestieQuest.lua:393
 Reset = <function> defined @Questie\Modules\QuestieQuest.lua:156
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 15
(*temporary) = 25
(*temporary) = 1
(*temporary) = 15
(*temporary) = "Defense"
(*temporary) = "attempt to index global 'QuestieReputation' (a nil value)"
_QuestieQuest = <table> {
 1 = "Questie"
 2 = <table> {
 }
 IsDoable = <function> defined @Questie\Modules\QuestieQuest.lua:1312
 DrawAvailableQuest = <function> defined @Questie\Modules

**Comment by BreakBB** [comment]
Make sure you have only one Questie folder in your addon folder. Moreover you have to restart WoW after you updated!

**Comment by b-morgan** [comment]
There is (and has been for quite a few updates) only one Questie folder and I did restart WoW after the update (actually, WoW was not running when the update happened).

Therefore, your assumptions used to close this issue were incorrect. I'll open another issue if it still happens.

**Comment by BreakBB** [comment]
That error states that a Questie file wasn't loaded and therefore it couldn't access the stated object "QuestieReputation". Yes, let me know if this still is an issue :)

**Comment by BreakBB** [comment]
@b-morgan Any news on this?

**Comment by b-morgan** [comment]
I haven't had any recurrence in a few days so I think we can close this.

**Comment by BreakBB** [comment]
Thanks for reporting back @b-morgan 😃
