### ISSUE TITLE
! ! ! All over my screen after updating

### ISSUE THREAD

**Issue by Mrhgb** [AeroScripts/QuestieDev#1307]
## Bug description
Quest markers are showing up all the time.

## Screenshots
https://i.imgur.com/NE2LInb.jpg

## Questie version
4,2,1

**Comment by BreakBB** [comment]
Have a look at [the changelog](https://github.com/AeroScripts/QuestieDev/releases/tag/v4.2.1). This is the new DBM HUD feature which you can access in the Questie config.
