### ISSUE TITLE
Manually set a quest as done.

### ISSUE THREAD

**Issue by malkaviano** [AeroScripts/QuestieDev#131]
Some people just started playing before getting questie.

Please, add an option to set a quest as done.

Ty.

**Comment by BraynStorm** [comment]
Please do! It could be something as simple as
/questie add_done "Rude Awakening"

**Comment by Logonz** [comment]
We should add logic that recursivly sets required quests to complete if you
accept one that has requirements

**Comment by BraynStorm** [comment]
Yep :)

**Comment by AeroScripts** [comment]
Will be up in the next version, just do /questie complete <quest name>

It will prompt you if there are multiple quests with the same name. Ex "/questie complete the missing diplomat"
