### ISSUE TITLE
Luna unit frames issue

### ISSUE THREAD

**Issue by lilypure604** [AeroScripts/QuestieDev#1312]
## Bug description

Message: Interface\AddOns\Questie\Modules\QuestieTooltips.lua:80: Usage: UnitGUID("unit")
Time: Sun Oct 13 15:47:03 2019
Count: 4
Stack: Interface\AddOns\Questie\Modules\QuestieTooltips.lua:80: Usage: UnitGUID("unit")
[C]: in function `UnitGUID'
Interface\AddOns\Questie\Modules\QuestieTooltips.lua:80: in function <Interface\AddOns\Questie\Modules\QuestieTooltips.lua:75>
[C]: ?
[C]: ?
[C]: in function `SetUnit'
Interface\FrameXML\UnitFrame.lua:291: in function `UnitFrame_UpdateTooltip'
Interface\FrameXML\UnitFrame.lua:277: in function `UnitFrame_OnEnter'
Interface\AddOns\LunaUnitFrames\modules\units.lua:501: in function `OnEnter'
Interface\AddOns\LunaUnitFrames\modules\units.lua:488: in function <Interface\AddOns\LunaUnitFrames\modules\units.lua:486>

Locals: (*temporary) = nil

**Comment by BreakBB** [comment]
This is fixed in the latest releases. Please update Questie :)
