### ISSUE TITLE
donation quests yellow quest icon

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1314]
## Description
Donation quests for cloth are yellow again instead of blue

## Screenshots
![](https://i.imgur.com/RT57SuV.jpg)

## Questie version
4.2.1

**Comment by BreakBB** [comment]
These aren't repeatable. Only the last one [Additional Runecloth](https://classic.wowhead.com/search?q=additional+runecloth) is repeatable.
