### ISSUE TITLE
Troubled Spirits of Kel'Theril

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1316]
## Description
In Troubled Spirits of Kel'Theril all relic fragments are marked on the same spot of the first relic fragment.

The other coordinates are listed on WoW-Head

## Wowhead link
https://classic.wowhead.com/quest=5245/troubled-spirits-of-keltheril

## Screenshots
![](https://i.imgur.com/kLIDHhB.jpg)

## Questie version
4.1.2

**Comment by BreakBB** [comment]
This could be related to missing translations. I think you already finished this quest?

Moreover you should update to 4.2.1 which contains more translations. I will check these items.

**Comment by Djfe** [comment]
I took the screenshot when 4.2.1 wasn't available, yet.
this issue was created one day afterwards ^^
I reported with the accurate version number to avoid confusion in-case this was fixed by 4.2.1

I can' t retest this since I finished the quest by now, yes :/

**Comment by BreakBB** [comment]
Ye sure, it's totally correct the version number in which the issue was encountered. So I just checked and the translations for this items are included.

We're currently rewriting our code to determine objectives, so this should either already be fixed with 4.2.1 or will be with the next release.
