### ISSUE TITLE
Since Update, a lot of Tooltips are broken

### ISSUE THREAD

**Issue by Dastano** [AeroScripts/QuestieDev#1318]
## Bug description
Thelsamar Blood Sausages as example show all 3 Tooltips on the Spider but no Boar /Bear Tooltip, this happen to a damn lot of Quests since Questie got updated.

## Screenshots
(N

## Questie version
4.2.1 0f28ee6

**Comment by BreakBB** [comment]
We made some more improvements before 4.2.0 about the code finding the right correct objectives. Unfortunately that improvements didn't make it in a release yet. But they're on the master branch now and will be in the next release!

Just to make sure: You're on an English client?

**Comment by Aloki** [comment]
A bug is still present. I use the master branch, not release versions.

**Comment by kdotnogi** [comment]
sorry my english skill poor.

maybe itemDB.lua's itemData table # sorting problem. (koKR client)
i tested same quest's item db sort to correct.

i suggest itemDB table # sort to ascending(0 → ex 10000) in next version.

**Comment by BreakBB** [comment]
@kdotnogi Yeah that would "fix" it, but we don't want to trust the sorting of the DB.

**Comment by BreakBB** [comment]
@Aloki Some quests are just missing translations which could result in wrong tooltips. With which quests do you issues and what language are you using?

**Comment by Aloki** [comment]
@BreakBB But just reloading the addon fixes the bug. I use English.

**Comment by BreakBB** [comment]
@Aloki After each update (`git pull`) you should restart the Wow client completely so all files and data is loaded correctly :)

**Comment by BreakBB** [comment]
@Dastano @Aloki Please check out our latest release and report back if this is still an issue.

**Comment by BreakBB** [comment]
Assuming this is fixed.
