### ISSUE TITLE
Overlord Mok'Morokk's Concern objective markers misplaced

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1322]
All three objective markers on the minimap are stacked on the one that's correct for the Strongbox, even though they're actually in three separate locations.

https://classic.wowhead.com/quest=1166/overlord-mokmorokks-concern

![WoWScrnShot_101419_190719](https://user-images.githubusercontent.com/54936174/66769642-e6316980-eeb5-11e9-97a3-429672ab3606.jpg)

Version 4.2.0

**Comment by BreakBB** [comment]
The data of these items is correct in our data. But we're currently rewriting our code how we determine the objectives of quests. This should be fixed with the next release.
