### ISSUE TITLE
Low level quests shown as yellow

### ISSUE THREAD

**Issue by Calleh12** [AeroScripts/QuestieDev#1323]
## Bug description
Quests that are more than two levels lower is shown as yellow in the map, minimap and tracker, when they should be green. I noticed it first in release 4.2.1. I have tried 4.2.0, 4.1.2 and 4.1.1. I don't have the issue on release 4.1.1. On release 4.2.1 I deleted my WTF folder and removed all addons but quests were still shown as yellow.

## Screenshots
![WoWScrnShot_101419_194733](https://user-images.githubusercontent.com/1598428/66771868-ac636180-eebb-11e9-93f2-b95f7cf9b1f0.jpg)
![WoWScrnShot_101419_194618](https://user-images.githubusercontent.com/1598428/66771876-b1281580-eebb-11e9-9b71-14b9f45119f7.jpg)

## Questie version
4.1.1 BETA
4.2.1 0 0f28ee6

**Comment by BreakBB** [comment]
Yes, this is a known issue and already fixed on our branch. It will be fixed with the next release!
