### ISSUE TITLE
The Bloodsail Buccaneers 

### ISSUE THREAD

**Issue by iron217** [AeroScripts/QuestieDev#1324]
## Description
assign each npc a coordinate point:

Captain Stillwater slain 33, 82.2 (now she’s only here)
Captain Keelhaul slain 29.2, 88.4
Fleet Master Firallon slain 30.6, 90.4

## Wowhead link
https://classic.wowhead.com/quest=608/the-bloodsail-buccaneers

## Questie version
4.2.1

**Comment by BreakBB** [comment]
Are you using a client language different to English?

**Comment by iron217** [comment]
> Are you using a client language different to English?

Ruru client

**Comment by BreakBB** [comment]
Merging with #1071
