### ISSUE TITLE
Pick up: Lost Deathstalkers

### ISSUE THREAD

**Issue by Tuek83** [AeroScripts/QuestieDev#1325]
## Description
Questie is stuck on "Pick up: Lost Deathstalkers" quest. I completed the partial chain before Questie was updated, now it's stuck on that after I've finished the whole thing. How can I get passed this bug so I can continue to use Questie?

https://classic.wowhead.com/quest=428/lost-deathstalkers

## Questie version
v4.2.1

**Comment by LemonBreezes** [comment]
I am also having this issue :(

**Comment by drejjmit** [comment]
This is a Azeroth Auto Pilot problem.
/aap skip
