### ISSUE TITLE
tracker doesn't consider items that are in your bank

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1326]
## Bug description
Unlike WoW's native tracker, Questie doesn't consider items from your bank, yet.
Is it actually possible for add-ons to access this data?

## Screenshots
![](https://i.imgur.com/VeJ41J0.jpg)

## Questie version
4.2.1

**Comment by BreakBB** [comment]
Could you check that again after a `/reload`. Afaik neither the Wow quest log nor the tracker count bank items.

**Comment by BreakBB** [comment]
@Djfe Any news on this? I wasn't able to test this yet.

**Comment by BreakBB** [comment]
I was able to test this and it is a bug of the Blizzard API. When storing an item on the bank the native quest log doesn't consider quest items. Moreover when grabbing an item from the back no quest related event is fired and therefore we can't know about the update.

**Comment by Djfe** [comment]
thanks a lot for testing! I haven't had the chance to test the game ui myself, I haven't done a quest for  hunting drops in a while. ^^

**Comment by BreakBB** [comment]
Closing this since it is a bug on Blizzard's side.

**Comment by SpareSimian** [comment]
Could this be a feature request that sniffs another addon's bank data? (I use TSM and Auctioneer Suite, both of which track bank, mail, and bags.) I was grinding for the longest time on an infrequently-used alt for troll ears in STV before I discovered I'd put some in the bank long ago. (Now I know to check the bank when parking one alt and resuming another that's resting, but it would be nice to show the banked quest items in parentheses next to the ones returned by the quest APIs.)

**Comment by SpareSimian** [comment]
Even hotter would be sniffing all alts' possessions for non-soulbound quest items. I'll have to look over the code to see how hard that would be to implement, perhaps with a tooltip to show which alts have the item and where.

**Comment by Gogo1951** [comment]
Tagging #2515
