### ISSUE TITLE
Moving the quest tracker sometimes locks it to the mouse

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1327]
Basically, when I move the tracker with CTRL+left click, if I happen to let go of CTRL before I let go of the mouse button, the tracker stays glued to the mouse and I can't click on anything else, even the menus. In this state the only thing left to do is force-quit WoW and start it up again.

Version 4.2.0

**Comment by Muehe** [comment]
Update to 4.2.1 please, see #1295
