### ISSUE TITLE
[16] Investigate the Blue Recluse

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#1328]
## Description
Does not require breadcrumb [[15] Report to Jennea](https://classic.wowhead.com/quest=1919/report-to-jennea)

## Wowhead link
https://classic.wowhead.com/quest=1920/investigate-the-blue-recluse

## Questie version
4.2.1

**Comment by drejjmit** [comment]
Also 
[Chest of Containment Coffers](https://classic.wowhead.com/item=7247/chest-of-containment-coffers) for this quest should be added to:
38.6,79.4
38.6,79.5
39.7,84.2
39.6,86.5
40.4,87.5
40.4,90.3
40.3,91.8
40.7,92.7
41.4,88.0
41.3,90.4

**Comment by BreakBB** [comment]
Spawns are added with 8e6391857ff39813eb71a1fa44b6dd98f07e1c74
