### ISSUE TITLE
The Sparklematic 5200!

### ISSUE THREAD

**Issue by iron217** [AeroScripts/QuestieDev#1333]
## Description
assignment doubled in English and Russian

## Wowhead link
https://classic.wowhead.com/quest=2951/the-sparklematic-5200

## Screenshots
<img width="1440" alt="Снимок экрана 2019-10-15 в 19 08 36" src="https://user-images.githubusercontent.com/46353863/66849886-63291580-ef80-11e9-9974-6d5bf41419da.png">

## Questie version
4.2.1 Ruru client

**Comment by BreakBB** [comment]
Merging with #1287
