### ISSUE TITLE
Claim Rackmore's Treasure!

### ISSUE THREAD

**Issue by Ulidan** [AeroScripts/QuestieDev#1337]
## Description
"Claim Rackmore's Treasure" involves finding 2 keys:
Rackmore's Silver Key - Found on Drysnap Crawler
Rackmore's Golden Key - Found on Naga.

Questie points that both keys are found on Naga, both in tooltips and on map.

## Wowhead link
[https://classic.wowhead.com/quest=6161/claim-rackmores-treasure](url)

## Screenshots
Irrelevant

## Questie version
V4.2.1_0f28ee6

**Comment by BreakBB** [comment]
Merging with #1071
