### ISSUE TITLE
[7] Thunderhorn Totem

### ISSUE THREAD

**Issue by ClemensDegasper** [AeroScripts/QuestieDev#1339]
## Description

quest in mulgore [7] Thunderhorn Totem 
Stalker Claws drops from Prairie Wolf arent shown on the hover over name plate thingy.
but the cougars are shown to drop both items needed for the quest.

## Wowhead link

https://classic.wowhead.com/quest=756/thunderhorn-totem

## Screenshots

![questie](https://user-images.githubusercontent.com/2102634/66935515-6681d700-f03c-11e9-929e-f75f8c9c4997.png)

## Version: 4.2.1 0 0f28ee6

**Comment by BreakBB** [comment]
This is linked to #1071 and will be fixed in the next release. Sorry for the trouble and thank you for the report! :)
