### ISSUE TITLE
Map - Only show objectives of active/tracked quests

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1340]
It would be nice to have an option to only show quest objectives of tracked quests on the world map/minimap

![](https://i.imgur.com/xI6GyCe.jpg)
I have trouble differentiating between the items of two quests here.
The Wildlife Suffers Too
https://classic.wowhead.com/quest=4984/the-wildlife-suffers-too
Unfinished Business (circled in red)
https://classic.wowhead.com/quest=6025/unfinished-business

especially since unfinished business uses two different colors, while wildife and unfinished business use almost the same color for their objectives.

alternative suggestion: make inactive quests objectives more opaque.

**Comment by BreakBB** [comment]
@Djfe Do you already know about the "Focus" feature of the tracker? It allows you to fade out all quests except one.

**Comment by Djfe** [comment]
No, I didn't. thx for the recommendation.
Though it doesn't work for all objectives, yet.

example: the annals of darrowshire
https://classic.wowhead.com/quest=5154/the-annals-of-darrowshire
Without focus:
![](https://i.imgur.com/JxVo9lu.jpg)
With focus:
![](https://i.imgur.com/rSsMweD.jpg)

Yes, it's the small gear icon in there (Andorhal), but all of those loot bags are still at 100% opacity

**Comment by Djfe** [comment]
I'm actually wondering whether it's still worth implementing. (icons are more transparent nowadays)

Also: I just noticed the feature to hide questicons of one particular quest. (so you can pretty much achieve this, either with questfocus or hiding single quests)

**Comment by BreakBB** [comment]
@Djfe I think it would still be an improvement. Having an option to show only tracked quests by default would increase the user experience.

**Comment by Gogo1951** [comment]
We'll be addressing this in #2500; closing this as a stand alone issue.
