### ISSUE TITLE
An error appears after enabling quest tracker. 

### ISSUE THREAD

**Issue by ximikavt** [AeroScripts/QuestieDev#1344]
## Bug description
An error appears after enabling quest tracker. And Quest tracker does not work

## Error log
Message: Interface\AddOns\Questie\Modules\QuestieQuest.lua:496: attempt to index local 'Quest' (a nil value)
Time: Thu Oct 17 12:49:55 2019
Count: 1
Stack: Interface\AddOns\Questie\Modules\QuestieQuest.lua:496: attempt to index local 'Quest' (a nil value)
[C]: ?
Interface\AddOns\Questie\Modules\QuestieQuest.lua:496: in function `IsComplete'
Interface\AddOns\Questie\Modules\QuestieTracker.lua:1017: in function `Update'
...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:88: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:84>

Locals: 

Locals: <none>

## Questie version
4.2.1

**Comment by ximikavt** [comment]
Tried everything, restarting, cleaning wtf folder, turning off all other addons. Seems like some of my quests are causing it.

**Comment by BreakBB** [comment]
Please grab the `QuestieDB.lua` file from the ZIP below and copy it into `Questie/Database` replacing the old file. Then start again and share a screenshot of the output in the chatframe. I just added a some debug messages to get a lead on this issue. Seems really like corrupted quest data, but can't tell which it might be.

[QuestieDB.zip](https://github.com/AeroScripts/QuestieDev/files/3738620/QuestieDB.zip)

**Comment by BreakBB** [comment]
Oh and please run `/dump QuestiePlayer.currentQuestlog` and also report the output!

**Comment by ximikavt** [comment]
![image](https://user-images.githubusercontent.com/11026310/67000346-5de2dc80-f0e0-11e9-8709-3d639a3efa36.png)
That's all shown in chat

**Comment by BreakBB** [comment]
Thanks, that already helped. Please do the same again with this file:

[QuestieDB.zip](https://github.com/AeroScripts/QuestieDev/files/3738676/QuestieDB.zip)

**Comment by ximikavt** [comment]
rawdata is nil for questID: 7668

**Comment by BreakBB** [comment]
Congratulation @ximikavt You found a quest we don't have in our data! 😮 

[The Darkreaver Menace](https://classic.wowhead.com/quest=7668/the-darkreaver-menace) is not in our data. I will fix this and send you a copy so at least for now it will be working for you :)

**Comment by ximikavt** [comment]
Thank you for the very fast response!

**Comment by BreakBB** [comment]
Sorry for talking this long. There you go:

[Questie-v4.2.1_107-61ed7db.zip](https://github.com/AeroScripts/QuestieDev/files/3738862/Questie-v4.2.1_107-61ed7db.zip)

**Note that this version includes other new stuff as well**

**Comment by BreakBB** [comment]
There you go, sorry for taking so long. It was the first time for me fixing such an issue, but you should be fine. I hope it is tracked correctly as well.

[Questie-v4.2.1_108-015bbd4.zip](https://github.com/AeroScripts/QuestieDev/files/3738915/Questie-v4.2.1_108-015bbd4.zip)

**Note that this version also include other changes made since the last release**
