### ISSUE TITLE
"Frostsaber Provisions" missing mob info

### ISSUE THREAD

**Issue by Nixxen** [AeroScripts/QuestieDev#1347]
## Description
The quest "Frostsaber Provisions" in Winterspring shows that both the Shardtooth Meat and the Chillwind Meat drops from the Chillwind Ravagers.
Shardtooth Meat drops from bears in Winterspring, but mostly the Shardtooth named ones since they are nearby.

## Wowhead link
Quest link: https://classic.wowhead.com/quest=4970

## Screenshots
N/A

## Questie version
v4.2.1_0f28ee6

**Comment by BreakBB** [comment]
This is related to #1071 And should be fixed with v5.0.0. Please report back if this is still an issue.
