### ISSUE TITLE
Swatter error: attempt to index local 'Quest' (a nil value)

### ISSUE THREAD

**Issue by mfsoup** [AeroScripts/QuestieDev#1351]
## Bug description

Error appears after starting the game. Map tracker still works. I restarted game fully after updating Questie.

## Swatter debug report

Date: 2019-10-17 20:41:51
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\QuestieQuest.lua line 496:
   attempt to index local 'Quest' (a nil value)
Debug:
   Questie\Modules\QuestieQuest.lua:496: IsComplete()
   Questie\Modules\QuestieTracker.lua:1031: Update()
   ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:98:
      ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:94
Locals:
self = <table> {
 1 = "Questie"
 2 = <table> {
 }
 GetQuestLogHashes = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:1163
 ToggleNotes = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:43
 AbandonedQuest = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:362
 CompleteQuest = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:339
 UnhideQuest = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:262
 GetAllQuestIdsNoObjectives = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:436
 Math_random = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:882
 UpdateObjectiveNotes = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:499
 Initialize = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:13
 GetAllLeaderBoardDetails = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:1258
 ForceToMap = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:729
 ClearAllNotes = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:101
 GetAllQuestIds = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:411
 AcceptQuest = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:296
 HideQuest = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:257
 PopulateQuestLogInfo = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:939
 GetAllQuestObjectives = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:960
 SmoothReset = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:172
 ShouldQuestShowObjectives = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:455
 PopulateObjectiveNotes = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:903
 UpdateHiddenNotes = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:210
 AddAllNotes = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:141
 Math_randomseed = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:879
 GetRawLeaderBoardDetails = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:268
 RemoveQuestHash = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:1193
 CalculateAvailableQuests = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:1591
 DrawAllAvailableQuests = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:1467
 CompareQuestHashes = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:1198
 PopulateObjective = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:759
 GetCurrentHashes = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:1189
 isCompleteByQuestId = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:476
 AddFinisher = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:511
 AddNewQuestHash = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:1182
 GetQuestHash = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:1151
 NotesHidden = false
 availableQuests = <table> {
 }
 IsComplete = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:495
 _IsCompleteHack = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:466
 UpdateQuest = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:393
 Reset = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:156
}
Quest = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Quest' (a nil value)"
Counthack = <function> defined @Interface\AddOns\Questie\Modules\QuestieQuest.lua:460

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.5
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  ClassicThreatMeter, v1.10
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  GatherMate2, v1.45
  IceHUD, v1.12.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixMaps, v1.13.31
  LetMeCast, v1.3
  OmniCC, v8.1.1
  Questie, v4.3.0 0 37acad5
  QuestLogEx, v1.2
  Recount, vv1.13.2d
  Scrap, v13.19
  ScrapSpotlight, v13.19
  ServerFriendsOnly, v1.1.14
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  VendorPrice, v1.1.4
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=3e5)

## Questie version

Questie v4.3.0_37acad5

**Comment by mfsoup** [comment]
Forgot to mention: error started happening after I collected more than 100 termites for the quest "A Plague Upon Thee (part 1) https://classic.wowhead.com/quest=5903/a-plague-upon-thee

**Comment by BreakBB** [comment]
@mfsoup  It could be there is another quest missing in our data. Could you enable debug messages  and check the output after a relog. There should be something like "Quest is nil for questID: 5903"

**Comment by JamesShiels** [comment]
I got the same error after logging in and the seasonal quests had become available, if that helps

whats the cmd for debug messages and i can do this also

**Comment by mfsoup** [comment]
Unfortunately the issue fixed itself after I completed a few more quests and reloaded. It happened before the seasonal event had started. If you still need the bug report, I can still post it but it probably won't have the error anymore.
