### ISSUE TITLE
STOLEN: Smithing Tuyere and Lookout's Spyglass #7728

### ISSUE THREAD

**Issue by occam-oc** [AeroScripts/QuestieDev#1353]
## Description
Tooltip does not indicate that Smithing Tuyere drops from Dark Iron Steamsmiths. This mob is the ONLY one that drops this item.

## Wowhead link
https://classic.wowhead.com/quest=7728/stolen-smithing-tuyere-and-lookouts-spyglass

## Questie version
4.3.0 0 37acad5

**Comment by BreakBB** [comment]
The data on our side looks fine for this. It has been mostly related to #1071 and should be fixed with the latest releases. @occam-oc Please report back if this is still an issue or if you encounter a similar issue with the latest release :)
