### ISSUE TITLE
The Flawless Flame # 3442

### ISSUE THREAD

**Issue by occam-oc** [AeroScripts/QuestieDev#1354]
## Description
The quest items can drop from Magma Elementals, Inferno Elementals, Blazing Elementals, or Heavy War Golems. Heart of Flame appears to ONLY drop from the elementals. Golem Oil ONLY from the Magma Elementals and Heavy War Golems (possibly Tempered War Golems according to Wowhead). The tooltip doesn't indicate this (I wish I could remember which was missing I know Inferno and Blazing Elementals for sure).

## Wowhead link
https://classic.wowhead.com/quest=3442/the-flawless-flame

## Questie version
 4.3.0 0 37acad5

**Comment by BreakBB** [comment]
This should also be fixed with the latest releases. There was an issue with the objectives shown on the wrong mobs. Please report back if you ever find anything similar 👍
