### ISSUE TITLE
Quest Colors Incorrect

### ISSUE THREAD

**Issue by ganiden** [AeroScripts/QuestieDev#1355]
## Bug description
The quest colors shown by Questie in the tooltips and tracker don't match the colors indicated in game. This is important due to the reputation and xp reduction you get as you begin to outlevel your quests. I like to know when quests are turning green in game so I can do them first, so the visual feedback is useful. In particular, the range for which quests are yellow in Questie appears to be +/- 4, whereas in game it is +/- 2. I believe the conditional should look like:

Red = (Level + 5) and higher
Orange = (Level + 3) to (Level + 4)
Yellow = Level +/- 2
Green = (Level - 3) to (Level - 5)
Grey = (Level - 6) and lower

But I'm not positive about the transition from Orange to Red.

## Questie version
4.3.0

**Comment by ganiden** [comment]
It looks like the issue has either been addressed in 4.3.0, or it is working for some quests and not others. I'm now seeing the correct color ranges for the quests I currently have.

**Comment by BreakBB** [comment]
Yes  this has been fixed with v4.3.0

If you still have issues please report back :)
