### ISSUE TITLE
Muisek Quest line

### ISSUE THREAD

**Issue by zerker6** [AeroScripts/QuestieDev#1356]
Hey guys, when doing the quest line in Ferelas for all of these quests, there is not info displayed on downed mobs or live mobs for collecting, nor are there any map/minimap icons denoting what to kill to get the quest done. and on a side note my quest tracker is not auto updating with total number of items collected for this quest or some other ones. thanks for the work love this addon.

**Comment by BreakBB** [comment]
@zerker6 Please follow our issue template next time.

What version of Questie are you using? The last releases contained some fixes for this quest line, but I think only the latest one released today should fix all of them. Could you check again or did you already finished the quest line?

**Comment by BreakBB** [comment]
Assuming this is fixed after checking the DB.
