### ISSUE TITLE
It would be better to add a zone label to the quest tracker

### ISSUE THREAD

**Issue by kuletco** [AeroScripts/QuestieDev#1361]
## Description
I think it would be better to add zone label to the quest tracker, especially if zone label support folding as quest log frame.

like MonkeyQuest:
![图片](https://user-images.githubusercontent.com/8363656/67142816-70ebdd00-f297-11e9-9329-3ff8a7d8f04f.png)

**Comment by rbpaiett** [comment]
Perhaps to add to that have a feature that groups quests by zone with headers like:

**Active Quests:**
+ **Searing Gorge**
     - Blah Quest
     - Blah Blah Quest
     - etc.
+ **Ashenvale**
     - Yada Quest
     - YadaYada Quest
     - etc.

Where next to the zone names, you could click an icon to toggle maximized/minimized thus:

**Active Quests:**
+ **Searing Gorge**   <-----  Minimized
+ **Ashenvale**
     - Yada Quest
     - YadaYada Quest
     - etc.

If you know what I mean ...

**Comment by BreakBB** [comment]
@kuletco @rbpaiett THis has been added to the Tracker on the master branch and will be released very shortly with v6.0.0.
