### ISSUE TITLE
[57+] Fragments of the Past

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#1364]
## Description
This should be in Dire Maul and not Feralas. Outside the instance but in the zone Dire Maul. 42.7 68.6

## Wowhead link
https://classic.wowhead.com/quest=5247/fragments-of-the-past

## Screenshots
![image](https://user-images.githubusercontent.com/15526476/67148354-253d3180-f29f-11e9-9f0b-34dd19cace51.png)

![image](https://user-images.githubusercontent.com/15526476/67148376-50c01c00-f29f-11e9-88f6-06f6596c5ac9.png)

## Questie version
4.3.0

**Comment by Djfe** [comment]
Almost opened another issue for this

some further information:
## Description
There is no marker on the map for the quest Fragments of the past for the vial of dire water/the dire "pool".
Objective: "Find the dire pool along Eldreth Row at Dire Maul in Feralas, and fill this vial."
as you can see there is no pool in eldreth row, but you can fill the vial if you stand close to the wall lol.
According to wowhead this is a glitch, sometimes the object shows up sometimes it's invisible.

The coordinates are 42.7 68.6
Though the feralas map has different coords for whatever reason ^^
I marked where I stand in dire maul/feralas on the map and where the cursor would have to be for those coords.



## Wowhead link
https://classic.wowhead.com/item=16973/vial-of-dire-water#english-comments
https://classic.wowhead.com/quest=5247/fragments-of-the-past


## Screenshots
![](https://i.imgur.com/mPYxiFs.jpg)
![](https://i.imgur.com/KHYkxUX.jpg)
![](https://i.imgur.com/0RrztIa.jpg)


## Questie version
4.2.1_0f28ee6




also what happened to the fix in #1156 ?

**Comment by drejjmit** [comment]
42,68 is where it's currently located (in the water). We need the Feralas location (Hold your cursor over you char in Feralas map)
