### ISSUE TITLE
DBM HUD always showing; even when option turned off

### ISSUE THREAD

**Issue by SirFreud** [AeroScripts/QuestieDev#1365]
## Bug description

The DBM HUD feature is always showing, even after turning it off in the /questie settings. 

## Screenshots

![Questie_Bug_2](https://user-images.githubusercontent.com/7471649/67149375-22771800-f270-11e9-8f81-4c54b95ae9bf.png)

## Questie version

Version 4.3.0_37acad5

**Comment by BreakBB** [comment]
I don't see any icons in your screenshot. Could you share another one showing the option off and where the icons still show?

**Comment by SirFreud** [comment]
It's the Quest Log on the right side of the HUD. I was trying to turn that off. The option of "Show DBM HUD" is off, I thought the Quest Log on the right was what that pertained to?

**Comment by BreakBB** [comment]
The list on the right is the Questie Tracker, not the DBM HUD...

**Comment by BreakBB** [comment]
@SirFreud Any news on this?

**Comment by BreakBB** [comment]
Assuming this is solved.
