### ISSUE TITLE
since update

### ISSUE THREAD

**Issue by whiskyamy** [AeroScripts/QuestieDev#1366]
two bugs when i updated today. i had the issue with everything float on the screen before.

Date: 2019-10-19 17:00:01
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Questie.lua line 30:
   attempt to index global 'QuestieOptionsDefaults' (a nil value)
Debug:
   Questie\Questie.lua:30:
      Questie\Questie.lua:29
   [C]: ?
   ...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:613:
      ...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:605
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  DBMCore, v1.13.16
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  GTFO, v4.51
  HealBot, v1.13.2.7
  Identity2, v4.0.4
  Questie, v4.2.1 0 0f28ee6
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=304)

second bug:

Date: 2019-10-19 17:00:06
ID: 2
Error occured in: Global
Count: 2
Message: ..\AddOns\Questie\Modules\QuestieTooltips.lua line 77:
   attempt to index field 'db' (a nil value)
Debug:
   Questie\Modules\QuestieTooltips.lua:77:
      Questie\Modules\QuestieTooltips.lua:75
   [C]: ?
Locals:
self = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 SetHyperlink = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 SetTradeSkillItem = <function> defined =[C]:-1
 hasMoney = 1
 SetCraftItem = <function> defined =[C]:-1
 SetQuestRewardSpell = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 comparing = false
 Show = <function> defined =[C]:-1
 SetPetAction = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 SetQuestLogItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetTalent = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 SetTradePlayerItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 __tamedCounts = false
 updateTooltip = 0.185000
 SetInventoryItem = <function> defined =[C]:-1
 SetCraftSpell = <function> defined =[C]:-1
 default = 1
 SetLootRollItem = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetAction = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetShapeshift = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 SetHyperlink = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 SetTradeSkillItem = <function> defined =[C]:-1
 hasMoney = 1
 SetCraftItem = <function> defined =[C]:-1
 SetQuestRewardSpell = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 comparing = false
 Show = <function> defined =[C]:-1
 SetPetAction = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 SetQuestLogItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetTalent = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 SetTradePlayerItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 __tamedCounts = false
 updateTooltip = 0.185000
 SetInventoryItem = <function> defined =[C]:-1
 SetCraftSpell = <function> defined =[C]:-1
 default = 1
 SetLootRollItem = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetAction = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetShapeshift = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
 SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*tempor
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  DBMCore, v1.13.16
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  GTFO, v4.51
  HealBot, v1.13.2.7
  HealBotTips, v1.13.2.7
  Identity2, v4.0.4
  Informant, v8.2.6374 (SwimmingSeadragon)
  Questie, v4.2.1 0 0f28ee6
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11302-1.0.7
  VendorPrice, v1.2.9
  WeakAuras, v2.15.4
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=3b7)

**Comment by whiskyamy** [comment]
bug 3:

Date: 2019-10-19 17:00:05
ID: 3
Error occured in: Global
Count: ∞
Message: ..\AddOns\Questie\Modules\QuestieTooltips.lua line 119:
   attempt to index field 'db' (a nil value)
Debug:
   Questie\Modules\QuestieTooltips.lua:119:
      Questie\Modules\QuestieTooltips.lua:118
   Questie\Modules\QuestieTooltips.lua:193:
      Questie\Modules\QuestieTooltips.lua:189
   [C]: ?
Locals:
name = "Haunch of Meat"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'db' (a nil value)"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  DBMCore, v1.13.16
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  GTFO, v4.51
  HealBot, v1.13.2.7
  HealBotTips, v1.13.2.7
  Identity2, v4.0.4
  Informant, v8.2.6374 (SwimmingSeadragon)
  Questie, v4.2.1 0 0f28ee6
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11302-1.0.7
  VendorPrice, v1.2.9
  WeakAuras, v2.15.4
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=3b7)

**Comment by BreakBB** [comment]
@whiskyamy  This looks like you either didn't restart the WoW client after updating or you have more than one Questie folder in your addons folder.

**Comment by BreakBB** [comment]
Assuming this is fixed.
