### ISSUE TITLE
Villains of Darrowshire

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1368]
## Description
Villains of Darrowshire
Horgus' Skull is in Blackwood Lake at 51.1, 49.9 and not in Pestilent Scar.

it is currently shown at the same coordinates as the Shattered Sword of Marduk.
Maybe a translation issue again?

## Wowhead link
https://classic.wowhead.com/object=176208/horgus-skull#contains
https://classic.wowhead.com/quest=5181/villains-of-darrowshire

## Screenshots
![](https://i.imgur.com/L5Fdm73.jpg)

## Questie version
4.2.1

**Comment by BreakBB** [comment]
Yes, this should be the translation issue.

The data looks good on our side:

```lua
[176208] = {"Horgus' Skull",nil,nil,{[139]={{51.11,49.93},},},139,},
```
