### ISSUE TITLE
FR: Strikeout completed quest parts in tracker

### ISSUE THREAD

**Issue by Kilmatar** [AeroScripts/QuestieDev#1374]
In case of multiple objectives in quest can we have a strikeout line of text for completed quest parts intracker?
This will allows to more easily see what's is already completed and what's not.

Original: 
![11](https://user-images.githubusercontent.com/4357221/67161306-d99f8c00-f361-11e9-9473-21e84e74a3c6.jpg)

Suggested:
![22](https://user-images.githubusercontent.com/4357221/67161312-df956d00-f361-11e9-806d-944f8cce0d0e.jpg)

**Comment by BreakBB** [comment]
@Kilmatar Sorry for the late response on this. I think what would help you is the setting for coloring the objectives based on their completeness:

In the Tracker tab you have this option:

![image](https://user-images.githubusercontent.com/33514570/70432953-b4d1b600-1a80-11ea-8fd9-bf70369e18da.png)

That will color the objectives red with no progress and will change it's color step by step to green, which marks them as complete.
