### ISSUE TITLE
Quest #608 - The Bloodsail Buccaneers

### ISSUE THREAD

**Issue by wow-classic** [AeroScripts/QuestieDev#1377]
## Description
Fleet Master Firallon ( https://classic.wowhead.com/npc=2546/fleet-master-firallon ) not marked in tooltip. **And he has the wrong coordinates on the map.**
(In the Russian version WoW)

## Wowhead link
https://classic.wowhead.com/quest=608

## Screenshots
![Questie - 2](https://user-images.githubusercontent.com/55049724/67162709-4e2cf780-f36f-11e9-94a4-9c6433d18028.png)

## Questie version
Version: 4.3.0 0 37acad5

**Comment by BreakBB** [comment]
The data on our side looks totally fine and therefore I assume this is related to #1071 . Please update to the latest Questie version, which has a lot of improvements towards such issues.
