### ISSUE TITLE
Add options to remove objectives and mob locations

### ISSUE THREAD

**Issue by howardkent** [AeroScripts/QuestieDev#138]
It would be a good feature to just show where quests available are, but not where to go to complete them. For those that like the challenge of the game, but not clicking all NPCs to find quests not yet completed but are low level

**Comment by howardkent** [comment]
Thinking on this - it would be even more beneficial if it was possible to globally toggle them off, then, say Ctrl-click a quest to enable them specifically for that quest only. If you're stuck on it.

**Comment by AeroScripts** [comment]
I could easily create a slash command, at first at least

**Comment by howardkent** [comment]
Yes. That would be great. Part of the charm of vanilla is the lack of spoon feeding. What is not so great is that low level quests simply disappear from quest givers.

A slash command to enable objectives on a specific quest, similar to how I assume quest complete works in, would be ok too for toggling on/off individual quest objectives.

**Comment by Muehe** [comment]
Coincidentally, some what you want is already in the addon. 

You should have a "ToggleQuestie" button on the top of your map. If you press it, nothing is displayed, then change the map zone, e.g. from Teldrassil to Darnassus (just reopening the map won't work), and you have start points displayed, but not targets and end points. 

"It's not a bug, it's a feature!"™ Just make sure you have the "/questie lowlevel" option set.

**Comment by Khayla** [comment]
More toggling options would be great because, as said before, it's the spoon-feeding that really ruined WoW questing (at least for me). I'm only interested in the addon showing the available quests on the main map and the quest objectives in the tooltip. Although I won't be using it until I can remove the other features, your work is still much appreciated!
