### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by ZehelFenris** [AeroScripts/QuestieDev#1384]
## Description

I would really love to have profiles because on my alts i would like to set it up in another way than what im doing on my main

**Comment by HumbleKagu** [comment]
I was wondering if anyone else felt like they needed this! I second this as I have my main where I only turn on quest givers and quest turn ins, while on my alts I turn on all objective icons.

**Comment by BreakBB** [comment]
@ZehelFenris @HumbleKagu We've been shifting a lot of options from global to character wide, so this should either be fixed or at least partly. Feel free to open another issue if you want to have specific options changed.

**Comment by vallantv** [comment]
I'd like to see this revisited. In particular the Tracker font sizes would be nice to have character specific. I multi box and I need questie for those toons but smaller when I'm not multiboxing.

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/90698320-06eced00-e246-11ea-86ba-2c55784fff7f.png)

Sort of added. You can share settings across all toons.
