### ISSUE TITLE
Questlevel adjustment for displaying quests with a specific questlevel

### ISSUE THREAD

**Issue by GitHub-Mourn** [AeroScripts/QuestieDev#1386]
I'd like to get an option to display only a specific questlevel or something like a full range from [1-60] to [1-60].
Actually it's quite difficult to find quests at a specific level since you have to mouseover all available icons to find a matching questlevel. If you are out of range (actually max. 25 levels below your current level) you only have the option to enable all low level quests at all.
In case you are wondering, but i like to do all quests with all my chars. So i do all lvl 1-5 in one zone and then move to another zone for the next lvl 1-5 quests and so on. Allowing me to filter for those specific questlevels would make my questing experience much easier.

Thanks for reading.
Mourn

**Comment by BreakBB** [comment]
In the general tab there are already sliders to adjust the level of quests you want to see on the map. You can use the "Show all quests below level" checkbox to see all the quests below your own level or use the sliders to see only quests below/above your own level.
With v4.3.0 the sliders have been updated to support the full range of 1-60.

I am not sure if you're thinking about something else.

**Comment by GitHub-Mourn** [comment]
I was thinking of something like this: My char is level 50 and wants to do all the low level quests he's actually missing. Since there are a lot of them i'd probably get a messy worldmap full of ! icons if i'd choose to enable "Show all quests below level". So i want to select a specific range of quests to display, eg. all quests from level 20-25. Actually i can only set to display levels from 20-50 (my current level) but not 20-25.

Hope that makes sense now. ;)

**Comment by BreakBB** [comment]
Thanks for reporting back. Yes, this makes sense and I now understand what you mean.

**Comment by MatKier** [comment]
Not quite sure, but isn't this also covered by #1809 ?

**Comment by BreakBB** [comment]
@MatKier Not completly, because on a low level there is currently no way to display quests which are more than X quests above your own. Yes there are the sliders for it, but these need to be checked for low level as well.
