### ISSUE TITLE
LUA Error: QuestieQuest.lua:55: attempt to index field 'data' (a nil value)

### ISSUE THREAD

**Issue by puggan** [AeroScripts/QuestieDev#1387]
## Bug description
When clicking the show/hide questie on the map, I get this LUA-error:

Message: ...ce\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:55: attempt to index field 'data' (a nil value)
Time: Mon Oct 21 20:03:43 2019
Count: 4
Stack: ...ce\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:55: attempt to index field 'data' (a nil value)
...ce\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:55: in function `ToggleNotes'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: self = <table> {
 1 = "QuestieDev-master"
 2 = <table> {
 }
 GetQuestLogHashes = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:1046
 ToggleNotes = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:42
 AbandonedQuest = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:318
 CompleteQuest = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:295
 UnhideQuest = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:218
 GetAllQuestIdsNoObjectives = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:392
 Math_random = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:785
 UpdateObjectiveNotes = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:455
 Initialize = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:13
 GetAllLeaderBoardDetails = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:1125
 ForceToMap = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:632
 ClearAllNotes = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:76
 GetAllQuestIds = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:367
 AcceptQuest = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:252
 HideQuest = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:213
 PopulateQuestLogInfo = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:842
 GetAllQuestObjectives = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:863
 SmoothReset = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:146
 ShouldQuestShowObjectives = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:411
 PopulateObjectiveNotes = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:806
 UpdateHiddenNotes = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:182
 AddAllNotes = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:116
 Math_randomseed = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:782
 GetRawLeaderBoardDetails = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:224
 RemoveQuestHash = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:1076
 CalculateAvailableQuests = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:1373
 DrawAllAvailableQuests = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:1251
 CompareQuestHashes = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:1081
 PopulateObjective = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:662
 GetCurrentHashes = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:1072
 isCompleteByQuestId = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:432
 AddFinisher = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:467
 AddNewQuestHash = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:1065
 GetQuestHash = <function> defined @Interface\AddOns\QuestieDev-master\Mod

## Questie version
Version: 4.1.2 BETA 137 6596a3b

**Comment by BreakBB** [comment]
@puggan  Please update your Questie version and report if this is still an issue!

**Comment by puggan** [comment]
Ah, for some reson Questie wassn't found by twitch, and so wasn't notifed about updates.
