### ISSUE TITLE
Thunderhorn Totem Quest - Missing Icons From Target Enemies

### ISSUE THREAD

**Issue by GeodesicDragon** [AeroScripts/QuestieDev#1389]
## Description
Prairie Stalkers need to be killed to gather Stalker Claws for the 'Thunderhorn Totem' quest in Mulgore; the relevant icon is missing from these enemies.

## Wowhead link

Quest: https://classic.wowhead.com/quest=756/thunderhorn-totem
Prairie Stalker: https://classic.wowhead.com/npc=2959/prairie-stalker

## Screenshots

Missing Info From Tooltip (also shows I am still needing to gather claws): https://i.imgur.com/V6uIGNX.jpg
Missing Icon From Relevant NPC: https://i.imgur.com/jmFm2di.jpg

## Questie version

4.3.0 0 37acad5

**Comment by BreakBB** [comment]
Our data is correct on this, so is related to #1071 and should be fixed with the latest release.
