### ISSUE TITLE
Can't disable tooltips

### ISSUE THREAD

**Issue by Dezaimasu** [AeroScripts/QuestieDev#1390]
## Bug description
Option "Enable Tooltips" is not working for items in your inventory. Tried to enable-disable and reload ui multiple times after each change, tried to disable all addons except Qustie, tried "Reset Questie" button, tried to completely delete Questie addon folder and all Questie.lua files from WTF folder. No result.

## Screenshots
![67246120-40a66900-f466-11e9-8f77-80bd17285b01](https://user-images.githubusercontent.com/1636242/67310044-b4e41980-f505-11e9-8340-b507dbc0b123.jpg)

## Questie version
4.3.0 0 37acad5

**Comment by Logonz** [comment]
Thank you for reporting! We seems to have missed this! Fixed in master.
