### ISSUE TITLE
When I turn off auto accept quest through addons or mini map it doesnt work. It still auto completes and I cant click in to quests to talk to the NPC or buy stuff from them, or sell/repair if they have quests!

### ISSUE THREAD

**Issue by Menelle2019** [AeroScripts/QuestieDev#1392]

**Comment by BreakBB** [comment]
We can't help you if you just fill in the "title". We have specific issue templates which lists the information you have to provide.

What version of Questie do you use and did you try to turn off all addons except Questie to check the issue comes from Questie?

**Comment by Menelle2019** [comment]
Sorry for that, I did not see a template requesting any other information.

I am using the latest version of Questie and yes I have disabled all my
other add-ons besides Questie.

What other information would be useful.


thanks,

<http://www.masergy.com> <https://www.masergy.com>
<https://www.masergy.com>[image:
Masergy Logo] <https://www.masergy.com>

Walter Suksta, CISSP

Director Security Operations Center

p: 469-291-8033

<https://www.linkedin.com/ADDYOURIDHERE/>
<https://www.linkedin.com/company/16604/>
<https://www.linkedin.com/company/16604/>[image: LinkedIn]
<https://www.linkedin.com/company/16604/>
<https://www.twitter.com/ADDYOURTWITTERHANDLE>
<https://twitter.com/masergy>[image:
Twitter] <https://twitter.com/masergy>

**Comment by Menelle2019** [comment]
Questie-v5.0.0_7-fb7c60e.zip


thanks,

<http://www.masergy.com> <https://www.masergy.com>
<https://www.masergy.com>[image:
Masergy Logo] <https://www.masergy.com>

Walter Suksta, CISSP

Director Security Operations Center

p: 469-291-8033

<https://www.linkedin.com/ADDYOURIDHERE/>
<https://www.linkedin.com/company/16604/>
<https://www.linkedin.com/company/16604/>[image: LinkedIn]
<https://www.linkedin.com/company/16604/>
<https://www.twitter.com/ADDYOURTWITTERHANDLE>
<https://twitter.com/masergy>[image:
Twitter] <https://twitter.com/masergy>

**Comment by BreakBB** [comment]
@Menelle2019 Please update to v5.1.0 and let us know if you still experience issues.

**Comment by Menelle2019** [comment]
Thank you, I figured out the issue and it was not Questie


thanks,

<http://www.masergy.com> <https://www.masergy.com>
<https://www.masergy.com>[image:
Masergy Logo] <https://www.masergy.com>

Walter Suksta, CISSP

Director Security Operations Center

p: 469-291-8033

<https://www.linkedin.com/ADDYOURIDHERE/>
<https://www.linkedin.com/company/16604/>
<https://www.linkedin.com/company/16604/>[image: LinkedIn]
<https://www.linkedin.com/company/16604/>
<https://www.twitter.com/ADDYOURTWITTERHANDLE>
<https://twitter.com/masergy>[image:
Twitter] <https://twitter.com/masergy>
