### ISSUE TITLE
Shizzle's Flyer

### ISSUE THREAD

**Issue by TehFraginator** [AeroScripts/QuestieDev#1393]
## Description

Webbed Diemetradon Scale drops do not appear correctly on the map, or on tooltips.  The tooltips display for Pterrodaxes instead of Diemetradons.
![WoWScrnShot_102219_050418](https://user-images.githubusercontent.com/56868325/67271993-a821e000-f489-11e9-9c6a-3e978389f17a.jpg)

## Wowhead link

https://classic.wowhead.com/item=11830/webbed-diemetradon-scale

**Comment by BreakBB** [comment]
What version of Questie do you use?

**Comment by TehFraginator** [comment]
v4.3.0, this is for Classic WoW

**Comment by BreakBB** [comment]
This is related to #1071 and fixed with v5.0.0
