### ISSUE TITLE
After Update, extreme Fps Drops and Stutter

### ISSUE THREAD

**Issue by ervox** [AeroScripts/QuestieDev#1394]
Hey,

first i wanna thank you for this cool addon, so i had a problem with the latest version of questie.

i have my fps locked on 137, never had any problems with older Questie Versions , but with the latest Version i drop about 50 frames and have massive Stutters while playing, its like im playing on a 50 hz monitor with low frames, its just not smooth.

Hopefully there is a fix, to that point im gonna play with the older version,

mfg

**Comment by Logonz** [comment]
What version are you on?
Check the Questie.toc to find out.

This is strange because the older versions of questie are much less optimized and require a hell of a lot more processing power.

**Comment by ervox** [comment]
im on version 4.2.1 now and the version 4.3.0 is just buggy on my pc,
8700k
16gb ram
2080
m2 ssd

**Comment by StoumTheCat** [comment]
I second this. The issue occured on 4.3.0 and 5.0.0, downgrade to 4.2.1 made the problem go away. 
Drops and stutters happen regardless of graphic settings, or fps locks, **but only when you are moving in game**, when you stand still it's fine. I usually lock fps @144, and it drops to around 100, but stutters nonetheless, even with g-sync enabled. 
Ryzen 1700
16GB RAM 
2080 super
game's on ssd

**Comment by patmoffett** [comment]
Same issues described above,
i6700k
980ti
64gb ram

Only started after I got to marshall's refuge in Ungoro, went away when I had all the crystals for the quest "Crystals of Power"

**Comment by StoumTheCat** [comment]
Location for me is ungoro too, crystals of power is active, but I haven't collected any yet.

**Comment by Logonz** [comment]
Try the latest version, we optimized the minimap logic a lot!

**Comment by BreakBB** [comment]
@ervox @StoumTheCat @patmoffett Please update to v5.1.0 and report if you still experience issue!

**Comment by BreakBB** [comment]
Merging this with #1493
