### ISSUE TITLE
Collapseable quest tracker

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#1397]
Would be really nice if you could collapse/expand the quest tracker, like with a small button in the upper corner.
In dungeons I really don't want to see the long list of quests, and the tracker also seem to stay on top of every bar/window that pops up in the same location.

**Comment by reaper666735** [comment]
yes!, this is certainly a worthy addition, sometimes you just have the need to hide the tracker :p,

and a simple  +/-  in the right-hand corner of the tracker like the Retail version would be more then sufficient ^^

**Comment by BreakBB** [comment]
ae4f80d7eb0a9d8ef207c1e7771d1696339c3d00 adds collapsing/expanding buttons to each quest. Not the hole tracker yet (time was very limited for the upcoming release), but will be included in the next release!

![image](https://user-images.githubusercontent.com/33514570/70548639-37d33900-1b73-11ea-87ac-0652369e8529.png)

**Comment by Painstormx** [comment]
Thanks, that does help a bit.
But really looking forward to next release where I can hide the whole list in dungeons/raids :)

**Comment by BreakBB** [comment]
Yeah, the next release will be a big one! Just released v5.3.0 so we can unhide the PvP quests.
