### ISSUE TITLE
Error for quest The Restless Soul

### ISSUE THREAD

**Issue by isitLoVe** [AeroScripts/QuestieDev#1399]
## Bug description
Login, see error

## Screenshots
![Capture](https://user-images.githubusercontent.com/20051956/67334704-def80480-f522-11e9-84ae-362416657feb.PNG)

## Questie version
Version: 5.0.0 7 fb7c60e

**Comment by Djfe** [comment]
is this quest dependent or a general thing? it also happened to me at the start of the Fordring quest "in dreams" (the escort part)

**Comment by BreakBB** [comment]
This has been a general issue and is fixed with d42b132

We'll release the fix soon :tm:

**Comment by rbpaiett** [comment]
I applied your fix until you release it, thanks!

**Comment by BreakBB** [comment]
@isitLoVe @Djfe @rbpaiett v5.1.0 has just been released and this issue should be fixed now.
