### ISSUE TITLE
Cartographer notes can "zombie"

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#14]
Currently, it's possible for cartographer notes to "zombie," which basically means they're on the map, but Questie doesn't realize it, so they'll never get removed.

A quick fix is to remove all notes created by Questie on mod init, but there doesn't seem to be a function for this in Cartographer. This is probably going to need a bit of "black magic"

**Comment by AeroScripts** [comment]
This seems to have been fixed at some point (I could be wrong)

**Comment by Schaka** [comment]
It should be fixed with the current system in place actually, yeah. I'll close it.

**Comment by AeroScripts** [comment]
Reopening this because people have reported it again (or at least something extremely similar)

**Comment by valmarkuristik** [comment]
All quests remain on the map when you've completed the objective, showing no completion on map.

For example you may have 12 Raptor Heads in your inventory, but the map notes for getting them are still there and showing 0/12.

The map also offers you to get quests you are currently already on, bug haven't completed yet.

**Comment by Logonz** [comment]
1.1 is very close, closing to clean up the tracker
