### ISSUE TITLE
Don't include green quests in low-level quests

### ISSUE THREAD

**Issue by anzz1** [AeroScripts/QuestieDev#140]
Green quests are actually the most recommended quests to make as they are easy and give normal experience. Currently Questie shows only yellow and red quests in normal mode, and shows green and gray quests also in low level mode. Please include green quests in the normal mode, as it makes the most sense.

**Comment by AeroScripts** [comment]
I'll adjust the min level then, I just picked a number at random that seemed good

**Comment by AeroScripts** [comment]
So I've changed the default to 12 levels below current level instead of 6, and you can manually tweak this value with the new /questie minlevel <number> sub-command, which is a savedvariable.
