### ISSUE TITLE
Error during quest 'Clamlette Surprise'

### ISSUE THREAD

**Issue by tonyxc600** [AeroScripts/QuestieDev#1405]
## Bug description
Error in chat log when accepting Artisan Cooking quest 'Clamlette Surprise'. Quest is otherwise functional.

## Screenshots
![WoWScrnShot_102319_193212](https://user-images.githubusercontent.com/56020611/67373833-05be4580-f5cc-11e9-9c0d-34fbce2ff6f6.jpg)
![WoWScrnShot_102319_193227](https://user-images.githubusercontent.com/56020611/67373836-05be4580-f5cc-11e9-854a-98349bce6038.jpg)

## Questie version
5.0.0 7 fb7c60e

**Comment by Logonz** [comment]
Fixed in v5.0.1 hopefully!
