### ISSUE TITLE
Error on Login with new viersion

### ISSUE THREAD

**Issue by OnceWasPerfect** [AeroScripts/QuestieDev#1407]
I get the following error on log in:

Questie: [ERROR] [QuestieQuest]: There was an error populating objectives for The Power of Pine 8373 1 Interface\AddOns\Questie\Modules\QuestieQuest.lua:931: attempt to index field '?' (a nil value)

## Version: 5.0.0 7 fb7c60e

**Comment by mandie722** [comment]
<img width="541" alt="Screen Shot 2019-10-23 at 8 15 25 AM" src="https://user-images.githubusercontent.com/1380215/67391885-88fc7e80-f56d-11e9-9b38-92d6a15cb973.png">
Same error, different quest for me today.
Questie-v5.0.0_7-fb7c60e

**Comment by BreakBB** [comment]
Merging this with #1399 Already fixed on our master branch and will be released soon.
