### ISSUE TITLE
FrameLevel going negative

### ISSUE THREAD

**Issue by SpareSimian** [AeroScripts/QuestieDev#1408]
I suspect another addon is reducing Questie's frame level to zero, so the code in the OnShow handler (QuestieFramePool.lua line 314) tries to set the FrameLevel to -1. 

	self.glow:SetFrameLevel(self:GetFrameLevel() - 1)

I changed it to this:

	local oldFrameLevel = self:GetFrameLevel()
	if oldFrameLevel > 0 then self.glow:SetFrameLevel(oldFrameLevel - 1) end

**Comment by Logonz** [comment]
Are the frames still sorting in a correct manner?

**Comment by SpareSimian** [comment]
I don't know which frames are involved here, and what's being sorted. Is this to keep the tracker window floating above or below other windows?

**Comment by Logonz** [comment]
Added the safety code to atleast keep it from erroring out, more research is probably needed to figure out the root of the problem.
