### ISSUE TITLE
"Group" info settings

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#1409]
## Description
Hello,

i like the new addition of showing group information on the World map and NPC tooltips :D, but i was hoping for a bit more customisations options or else if you go in a group with 5 people your just going to be swamped with lines and lines of text :p, 

for example, having the ability to show/hide said information on the World map and/or Tooltips, 

or enabling/disabling the class colours used with player names ... 

ty :)

**Comment by AeroScripts** [comment]
v6.0.6
