### ISSUE TITLE
Bug on Login with newest update

### ISSUE THREAD

**Issue by bjhinkel** [AeroScripts/QuestieDev#1410]
Date: 2019-10-22 20:45:34
ID: -3
Error occured in: Global
Count: 3
Message: ..\AddOns\Questie\Modules\QuestieTooltips.lua line 149:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   [C]: pairs()
   Questie\Modules\QuestieTooltips.lua:149: GetTooltip()
   Questie\Modules\QuestieTooltips.lua:212:
      Questie\Modules\QuestieTooltips.lua:198
   [C]: ?
   [C]: ?
Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BadBoy, vv1-classic
  BagBrother, v
  Bagnon, v8.2.16
  Bartender4, v4.8.8
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  ClassicClassColors, v1.0.0
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.17
  DBMDefaultSkin, v
  DBMMC, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1302r031
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  GTFO, v4.51
  Informant, v8.2.6374 (SwimmingSeadragon)
  NeatPlates, v1.13.2.40
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v1.5
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniCC, v8.2.5
  orbSellAndRepair, v1.0.1
  Peggle, v2.2.4
  QuestGuru, v2.1.7
  Questie, v5.0.0 7 fb7c60e
  RealMobHealth, v2.13
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  SimpleDing, vv1.1.1
  SpeedyAutoLoot, v2.0.24
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TFTB, v1.10
  TomTom, vv11302-1.0.7
  totalRP3, v1.6.7.1
  totalRP3Data, v
  VendorPrice, v1.2.9
  VuhDo, v3.107-classic
  VuhDoOptions, v3.107-classic
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=6f1)

**Comment by DigitalHype** [comment]
Same bug on login, and with each quest log update. This started with the most recent update.

**Comment by Logonz** [comment]
It should not be on each quest log update because that code is only when hovering over things with the tooltip. Ill add a check for it and release it with 5.0.1 tonight.
Please report back to me if you find any strange errors after that.

**Comment by BreakBB** [comment]
Assuming this is fixed.
