### ISSUE TITLE
Bug when logging in 10-23-19

### ISSUE THREAD

**Issue by ReptarRevised** [AeroScripts/QuestieDev#1411]
-  Date: 2019-10-23 06:14:46

ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\QuestieDev-master\Questie.lua line 2:
   Usage: NewAddon([object,] name, [lib, lib, lib, ...]): 'name' - Addon 'Questie' already exists.
Debug:
   [C]: ?
   [C]: ?
   ...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:119: NewAddon()
   QuestieDev-master\Questie.lua:2: in main chunk
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AbarClassic, v
  AdvancedInterfaceOptions, v1.3.3
  AtlasLootClassic, vv1.3.2
  AtlasLootClassicData, vv1.3.2
  AtlasLootClassicDungeonsAndRaids, vv1.3.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoCarrot, v1.13.4
  BagBrother, v
  Bagnon, v8.2.16
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  CharacterStatsClassic, v2.4.1
  ClassicAuraDurations, v
  ClassicCastbars, vv1.1.2
  ClassicCastbarsOptions, v
  ClassPortraitsFinal, v
  DBMCore, v1.13.17
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.4
  Details, v
  DetailsTinyThreat, v
  eAlignClassic, vClassic
  EZJunk, v1.0.1
  GatherMate2, v1.45.5
  LeatrixPlus, v1.13.36
  LetMeCast, v1.3
  LibSharedMedia30, v3.0-113
  LortiUIClassic, v1.1.0
  OmniCC, v8.1.1
  Plater, v
  Quartz, v3.5.2-5-g582d62a
  Questie, v5.0.0 7 fb7c60e
  QuestieDevmaster, v4.0.9 BETA
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=53e)

**Comment by Logonz** [comment]
Did you read the error?
Usage: NewAddon([object,] name, [lib, lib, lib, ...]): 'name' - Addon 'Questie' already exists.
Do not try to install more than one questie

**Comment by BreakBB** [comment]
@ReptarRevised As Logonz already said, you have more than one version of Questie installed. Check [the  FAQ](https://github.com/AeroScripts/QuestieDev/wiki/FAQ#21-i-have-an-error-saying-something-about-usage-newaddonobject-name-lib-lib-lib--name---addon-questie-already-exists).
