### ISSUE TITLE
Show if Quest is part of "Series" 

### ISSUE THREAD

**Issue by Ultroman** [AeroScripts/QuestieDev#1412]
It would be awesome if one could see whether a quest is part of a quest line, and if so, show which number it is in the quest line.

I often skip quests because they look boring, only to later find out they were part of the main quest line in the area :)

On a related note, it would be awesome if you could see prerequisite quests for a given quest. Not sure if those are already in the search engine you made. Just thought of this on the train :)

Thanks for the absolutely madlad work you've done on the addon. It's just amazing the features you've been dishing out lately.

**Comment by Gogo1951** [comment]
Through the "Required" quest IDs, couldn't we piece together Quest Series, and then at least be able to show a number indicating what step you are on in the title?

* Warlord's Command (1 of 10)
* Eitrigg's Wisdom (2 of 10)
* For The Horde! (3 of 10)
* What the Wind Carries and The Champion of the Horde (4 of 10)
* The Testament of Rexxar (5 of 10)
* Oculus Illusions (6 of 10)
* Emberstrife (7 of 10)
* The Test of Skulls (8 of 10)
* Ascension... (9 of 10)
* Blood of the Black Dragon Champion (10 of 10)

**Comment by Gogo1951** [comment]
May be partially handled by #2498 - TBD, but closing as this isn't a high priority.
