### ISSUE TITLE
Map objective markers for "Kim'jael Indeed!" quest are not accurate

### ISSUE THREAD

**Issue by arphox** [AeroScripts/QuestieDev#1413]
## Description
Map objective markers (I was watching them on minimap) for the quest [**Kim'jael Indeed!**](https://classic.wowhead.com/quest=3601) are not accurate, and there are too few.
Considering the map on the wowhead page of the [**Kim'jael's Equipment**](https://classic.wowhead.com/object=153123) object, that seems a lot more accurate, but as i saw, questie does not use these locations.

## Questie version
5.0.1 2 e2e80b7

## Note
To solve this, I think the the coordinates for the `Kim'jael's Equipment` object (id=153123) should be modified in the `objectDB.lua` file.

**Comment by AndrewVBragg** [comment]
I updated the list of coordinates in objectDB.lua and made a PR here: https://github.com/AeroScripts/QuestieDev/pull/1414
Just linking here so hopefully, nobody invests time solving a solved issue, :)
