### ISSUE TITLE
Clickable quest interactive items on tracker

### ISSUE THREAD

**Issue by rbpaiett** [AeroScripts/QuestieDev#1415]
## Description

I've seen this in other quest addon trackers where if you have to click on an item you received when you accept a quest, it appears as a clickable icon at the beginning of that quest in the quest tracker.  For instance if you need the pine cleaner for removing a stinkbomb from southshore, the item appears on the quest tracker and you can just click on it, rather than having to put the item on the toolbar or having to open your inventory to click on it.  Hope my explanation is clear enough.

**Comment by rbpaiett** [comment]
For instance here:

![Questie Tracker Quest Item](https://user-images.githubusercontent.com/1621701/67432198-ae53b180-f59a-11e9-8cd2-a64fb4ebb02b.jpg)

**Comment by reaper666735** [comment]
+1  :)

**Comment by Muehe** [comment]
Added in 4a942c5ca5cb9ddeb0ba4e490c39002041776740

**Comment by rbpaiett** [comment]
I didn't see this in the latest version.  When is this slated to be released?

**Comment by Muehe** [comment]
It will be included in the next release, currently it's only on the master branch.
