### ISSUE TITLE
Sacred Flame Quest #1196 

### ISSUE THREAD

**Issue by Nimbix-wow** [AeroScripts/QuestieDev#1416]
## Description

Quest objective still showing on the map after completion. 

## Wowhead link

https://classic.wowhead.com/quest=1195/the-sacred-flame

## Screenshots

![github](https://user-images.githubusercontent.com/46905100/67433766-03b6af80-f5e9-11e9-80bb-5e7fd02f8633.JPG)

## Questie version

v5.0.1 2 e2e80b7

**Comment by BreakBB** [comment]
Fixed with 12623cec5de792ebb4077d3bbb74bf607afb3491
