### ISSUE TITLE
Thorium Brotherhood reputation quests.

### ISSUE THREAD

**Issue by Orome123** [AeroScripts/QuestieDev#1417]
## Description
There are 4 repeatable quests showing as available, when there aren't available anymore due to reputation increase. The quests are:

- Restoring Fiery Flux Supplies Via Kingsblood
- Restoring Fiery Flux Supplies Via Heavy Leather
- Restoring Fiery Flux Supplies Via Iron

All 3 quests above are only available when you are neutral with Thorium Brotherhood, but they still show as available in questie after getting friendly and honored (haven't reached revered yet to know if they show as available while revered).

- Gaining Acceptance

This quest is only available while friendly, and stops being available when you are honored. It still shows in questie while I'm currently honored.

## Wowhead link

https://classic.wowhead.com/quest=7736/restoring-fiery-flux-supplies-via-kingsblood
https://classic.wowhead.com/quest=8242/restoring-fiery-flux-supplies-via-heavy-leather
https://classic.wowhead.com/quest=8241/restoring-fiery-flux-supplies-via-iron
https://classic.wowhead.com/quest=7737/gaining-acceptance

## Screenshots

![WoWScrnShot_102319_182148](https://user-images.githubusercontent.com/56611266/67435367-5761d280-f5c2-11e9-9041-2075169772e3.jpg)

![WoWScrnShot_102319_182118](https://user-images.githubusercontent.com/56611266/67435372-592b9600-f5c2-11e9-86b1-2af711cb5634.jpg)

## Questie version

5.0.1

**Comment by BreakBB** [comment]
The max value of a reputation isn't handled yet, but we already have the required data. I will add the logic for this soon :tm: and will let you know.

**Comment by BreakBB** [comment]
@Orome123 I've just added the logic for ma reputation. Could you test the following version an report if it's working for you?

[Questie-v5.0.1_59-b942a8c.zip](https://github.com/AeroScripts/QuestieDev/files/3782681/Questie-v5.0.1_59-b942a8c.zip)

**Comment by Orome123** [comment]
It does work! The 4 quests aren't showing anymore :D

**Comment by BreakBB** [comment]
@Orome123 Perfect, thank you very much for testing this and reporting the result! Feel free to keep using the current version. The fix in general will be included in the next release!
