### ISSUE TITLE
Lokhtos Darkbargainer Thorium Brotherhood quests.

### ISSUE THREAD

**Issue by Orome123** [AeroScripts/QuestieDev#1418]
## Description

The same group of repeatable reputation quests show as available in 2 different points of the map. It's not a big deal, but it would look cleaner if they only showed in 1 place.

## Wowhead link

https://classic.wowhead.com/npc=12944/lokhtos-darkbargainer

## Screenshots

![WoWScrnShot_102319_183039](https://user-images.githubusercontent.com/56611266/67435875-7dd43d80-f5c3-11e9-9ce9-2c3eacf64abe.jpg)

![WoWScrnShot_102319_183044](https://user-images.githubusercontent.com/56611266/67435885-8167c480-f5c3-11e9-94d2-8a91f6927518.jpg)

## Questie version

5.0.1

**Comment by BreakBB** [comment]
This is simply because of the two entrances to MC. One from the Burning Steppes and the other from The Searing Gorge. Not much we can do about it and I think this is not a big deal.

Closing this for now but I am open for suggestions.
