### ISSUE TITLE
Quests that aren't there.

### ISSUE THREAD

**Issue by waffleprince** [AeroScripts/QuestieDev#1423]
## Bug description
Quests are listed on the map and minimap that are not there. With some digging I found that these are quests from wow patch 1.13, but wow classic is set to 1.12. It would be very helpful to remove these quests from the database.

**Comment by Muehe** [comment]
We already do that, if you notice anything wrong please tell us the exact quests, or we can't do anything about it.

Btw. I think you got your numbers backwards, old WoW was version 1.12 (which is what our Database is for) and new WoW that is currently live is version 1.13. In any case, there shouldn't be any differences in the quests available, except for phasing (dungeons/raids opening up progressively).
