### ISSUE TITLE
Witherbark Cages icons stack on 3rd cage (Hinterlands)

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#1424]
## Description

so basically there are 3 cages you need to interact with for this quest, and questie is stacking the icons with the locations for all 3 on the last one (3rd cage), while the first two are in another camp @ 23, 58 

the third one is obviously good @ 31, 57 :p

## Wowhead link

Quest: https://classic.wowhead.com/quest=2988/witherbark-cages#comments
First cage: https://classic.wowhead.com/object=144066/first-witherbark-cage#comments
Second cage: https://classic.wowhead.com/object=144067/second-witherbark-cage#comments
Third cage: https://classic.wowhead.com/object=144068/third-witherbark-cage#comments

## Screenshots

Questie stacking on 3rd location: https://imgur.com/Pn0Uec6

both cages in other camp: https://imgur.com/xhqSaIf

as you can see on the minimap of both screenshots we are not in the same place

## Questie version

v5.0.1_2

**Comment by Logonz** [comment]
Hmm i noticed this on a Searing Gorge quest where you burn the towers also, will look into it!
