### ISSUE TITLE
Troll Necklace Bounty, missing repeatable (Hinterlands)

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#1425]
## Description

after you complete the "normal" quest for troll necklaces, you unlock the repeatable version for Wildhammer rep farm, it is not shown by Questie :) 

## Wowhead link

normal quest: https://classic.wowhead.com/quest=2880/troll-necklace-bounty#comments

repeatable version: https://classic.wowhead.com/quest=2881/troll-necklace-bounty#comments

## Screenshots

none required

## Questie version

v5.0.1_2

**Comment by Logonz** [comment]
Thanks for the report!
Fixed #1426
