### ISSUE TITLE
Repeatable quests in Feralas not showing up anywhere

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1426]
The repeatable quests Again With the Zapped Giants and Refuel for the Zapping aren't marked as available, both on the map/minimap and in the Quests by Zone list for Feralas, even though I can do them.

https://classic.wowhead.com/quest=7725/again-with-the-zapped-giants
https://classic.wowhead.com/quest=7726/refuel-for-the-zapping

![WoWScrnShot_102419_234506](https://user-images.githubusercontent.com/54936174/67527921-66c34780-f6b8-11e9-88fb-828871b098e1.jpg)

Version: 5.0.1

**Comment by Logonz** [comment]
This is because they where blacklisted before we had the repeatable "!" implemented, removing them!
