### ISSUE TITLE
ElvUI Questie Error

### ISSUE THREAD

**Issue by foulfish** [AeroScripts/QuestieDev#1429]
Hey,
since I've started using ElvUI, everytime I log in I get error message (posted belowe) and my quest tracker doesn't show up. Anyone know what to do about it? I'm using up to date Questie from twitch addons menu.

Error message:

**Date: 2019-10-25 12:11:00
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\Libs\QuestieLib.lua line 246:
   attempt to index local 'quest' (a nil value)
Debug:
   Questie\Modules\Libs\QuestieLib.lua:246: CacheItemNames()
   Questie\Modules\Libs\QuestieLib.lua:239: CacheAllItemNames()
   ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:21:
      ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:19
Locals:
self = <table> {
 PrintDifficultyColor = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:24
 ProfileFunction = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:209
 CacheItemNames = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:244
 GetQuestObjectives = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:95
 CacheAllItemNames = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:228
 GetDifficultyColorPercent = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:44
 SanitizePattern = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:347
 GetColoredQuestName = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:126
 Count = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:338
 AddonPath = "Interface\AddOns\Questie\"
 PlayerInGroup = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:305
 Remap = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:273
 Maxdist = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:269
 CalculateWaypointMidPoint = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:170
 GetAddonVersionInfo = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:279
 Euclid = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:263
 IsResponseCorrect = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:69
 ProfileFunctions = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:217
}
questId = 7670
quest = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 7670
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "[CRITICAL]"
(*temporary) = "[QuestieDB:GetQuest] rawdata is nil for questID:"
(*temporary) = 7670
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 minimapConfigIcon = <table> {
 }
 Colorize = <function> defined @Interface\AddOns\Questie\Questie.lua:265
 Enable = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceConsole-3.0\AceConsole-3.0.lua:85
 GetClassColor = <function> defined @Interface\AddOns\Questie\Questie.lua:283
 EnableModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 configFrame = <unnamed> {
 }
 UnregisterComm = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:172
 Deserialize = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceSerializer-3.0\AceSerializer-3.0.lua:246
 UnregisterChatCommand = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceConsole-3.0\AceConsole-3.0.lua:111
 RegisterBucketEvent = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceBucket-3.0\AceBucket-3.0.lua:184
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:160
 Printf = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceConsole-3.0\AceConsole-3.0.lua:69
 baseName = "Questie"
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 debug = <function> defined @Interface\AddOns\Questie\Questie.lua:343
 Debug = <function> defined @Interface
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnSkins, v4.31
  AdvancedInterfaceOptions, v1.3.3
  AtlasLootClassic, vv1.3.2
  AtlasLootClassicData, vv1.3.2
  AtlasLootClassicDungeonsAndRaids, vv1.3.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BiSTracker, v1.4 
  CharacterStatsClassic, v2.4.1
  ClassicAuraDurations, v
  ClassicCastbars, vv1.1.2
  ClassicCastbarsOptions, v
  ClassicSpellActivations, v
  DBMCore, v1.13.17
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  ElvUI, v1.15
  ElvUIBenikUIClassic, v1.05
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  Immersion, v1.2.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixMaps, v1.13.36
  Pawn, v2.3.9
  Questie, v5.0.1 2 e2e80b7
  Scrap, v13.19
  ScrapSpotlight, v13.19
  ShowMeMyHeal, v0.6.0
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TownsfolkTracker, v1.0.7
  WeakAuras, v2.15.4
  WIM, v3.8.2
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=54c)**

**Comment by Logonz** [comment]
It actually seems to be related to the quest :
https://classic.wowhead.com/quest=7670/lord-grayson-shadowbreaker

It doesn't seem to exist in the database! 
@BreakBB can you look into this?

**Comment by BreakBB** [comment]
I will, but don't have the time right now. I will on Monday.

**Comment by BreakBB** [comment]
Fixed with c7c3aeab63d9f3d0635342e5b889e6dbea36f01f
