### ISSUE TITLE
Problem loading

### ISSUE THREAD

**Issue by Alvena1201** [AeroScripts/QuestieDev#1430]
![image](https://user-images.githubusercontent.com/57019636/67605411-380ba680-f776-11e9-8b32-7e19ae3f8d18.png)

Date: 2019-10-25 22:23:56
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Locale\frFR\lookupObjects.lua line 1:
   unexpected symbol near 'char(1)'
Debug:
   
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.3.2
  AtlasLootClassicData, vv1.3.2
  AtlasLootClassicDungeonsAndRaids, vv1.3.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoTrackQuests, v1.2
  BagBrother, v
  Combuctor, v8.2.10
  DBMCore, v1.13.17
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Questie, v5.0.1 2 e2e80b7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=347)

getting the attached error since updating.

not able to load? 

thanks

**Comment by BreakBB** [comment]
@Alvena1201 If you've had a closer look at the screenshot you posted, you could have find the reason yourself:

![image](https://user-images.githubusercontent.com/33514570/68143227-4fdee980-ff31-11e9-818b-da37906246ce.png)

**Comment by Alvena1201** [comment]
Haha thanks but of course I already did that :) it's working now though so it's fine. Keep up the good work. Great add on :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
