### ISSUE TITLE
Improvements to the quest tracker

### ISSUE THREAD

**Issue by kernighan** [AeroScripts/QuestieDev#1431]
## Description

I use monkeyquest for a quest tracker right now, so was curious to try out the Questie tracker that now is included.  Unfortunately I had to switch back to MonkeyQuest because the current Questie tracker lacks some useful functionality:

a) It cannot track quests that have no objectives ("The missing courier" in feralas is an example)

b) It doesn't organize quests (or at least have an option to do this) by zone, like they're found in the quest interface.  Nor can they be expanded/collapsed by zone (obviously)

c) No way to control/move around the tracker interface

d) no way to control how the tracker expands as quests are added

See screenshots for examples.

![monkeyquest](https://user-images.githubusercontent.com/1541600/67607360-1b9d4900-f739-11e9-9896-b4731c1421b3.png)
![questie](https://user-images.githubusercontent.com/1541600/67607365-1d670c80-f739-11e9-95bf-47a3d3fd66f4.png)

**Comment by kernighan** [comment]
Note how with MonkeyQuest I can locate my tomtom coordinates right above it, but with questie, it displays on top of the coordinate block

**Comment by kernighan** [comment]
Note again how with MonkeyQuest, the feralas courier quest shows up in its tracker, but not in questie

**Comment by Hantunaar** [comment]
Also Questie quests tracker put very long objectives on a single line, which sometimes put the whole thing way too far on the middle of the screen.

**Comment by BreakBB** [comment]
Yes these features are on our list.

Even though c) has been implement from the beginning. You can move the tracker with `CTRL + left click`. And for d) there should be a config option if I remember correctly (can't check right now).

**Comment by Malevola** [comment]
> ... And for d) there should be a config option if I remember correctly (can't check right now).

There is no option to load the tracker from bottom-to-top instead of top-to-bottom, which is what I think the OP was requesting.

**Comment by AeroScripts** [comment]
Many of these features have been added with the recent tracker rework, it's unlikely we will be revisiting the tracker for some time so I'm closing this for now.
