### ISSUE TITLE
tracker not showing up

### ISSUE THREAD

**Issue by kylerr8282** [AeroScripts/QuestieDev#1432]
## Bug description

The Questie tracker is not working and its not showing in the map.

## Screenshots

![buggeru 2](https://user-images.githubusercontent.com/57025243/67613578-9621a380-f7e1-11e9-988d-1dbc4710c258.png)
![buggeru](https://user-images.githubusercontent.com/57025243/67613579-991c9400-f7e1-11e9-94cc-d217cadb207e.png)

## Questie version

Questie, v5.0.1 2 e2e80b7

**Comment by BreakBB** [comment]
@kylerr8282 Could you enable debugging (in the advanced tab) and report what is printed im the chat? There should be something like "raw is nil for quest ID: ..."

**Comment by kylerr8282** [comment]
Date: 2019-10-26 14:42:21
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\Libs\QuestieLib.lua line 246:
   attempt to index local 'quest' (a nil value)
Debug:
   Questie\Modules\Libs\QuestieLib.lua:246: CacheItemNames()
   Questie\Modules\Libs\QuestieLib.lua:239: CacheAllItemNames()
   ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:21:
      ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:19
Locals:
self = <table> {
 PrintDifficultyColor = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:24
 ProfileFunction = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:209
 CacheItemNames = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:244
 GetQuestObjectives = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:95
 CacheAllItemNames = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:228
 GetDifficultyColorPercent = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:44
 SanitizePattern = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:347
 GetColoredQuestName = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:126
 Count = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:338
 AddonPath = "Interface\AddOns\Questie\"
 PlayerInGroup = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:305
 Remap = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:273
 Maxdist = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:269
 CalculateWaypointMidPoint = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:170
 GetAddonVersionInfo = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:279
 Euclid = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:263
 IsResponseCorrect = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:69
 ProfileFunctions = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:217
}
questId = 7670
quest = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 7670
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "[CRITICAL]"
(*temporary) = "[QuestieDB:GetQuest] rawdata is nil for questID:"
(*temporary) = 7670
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 minimapConfigIcon = <table> {
 }
 Colorize = <function> defined @Interface\AddOns\Questie\Questie.lua:265
 Enable = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:85
 GetClassColor = <function> defined @Interface\AddOns\Questie\Questie.lua:283
 EnableModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 configFrame = <unnamed> {
 }
 UnregisterComm = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:172
 Deserialize = <function> defined @Interface\AddOns\Details\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 UnregisterChatCommand = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
 RegisterBucketEvent = <function> defined @Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:184
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:160
 Printf = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 baseName = "Questie"
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 debug = <function> defined @Interface\AddOns\Questie\Questie.lua:343
 Debug = <function> defined @Interface\AddOns\Questie\Questie.lua:325
 error = <function> defined @Interface\AddOns\Questie\Questie.lua:314
 name = "Questie"
 Error = <function>

**Comment by kylerr8282** [comment]
ah found it, rawdata is nil for questID: 7670

**Comment by BreakBB** [comment]
Yep, that quest is missing in our DB >_>

I will fix it soon :tm:

**Comment by kylerr8282** [comment]
thanks!, hopefully it can be fixed

**Comment by BreakBB** [comment]
Don't worry, it can and it is quite easy as well. I simply don't have the time right now :/

**Comment by kylerr8282** [comment]
will it work normally if i just complete the quest?

**Comment by BreakBB** [comment]
@kylerr8282 Yes, sorry about the trouble.
