### ISSUE TITLE
Tracking of repeatable quest (Winterfall Intrusion) not being updated

### ISSUE THREAD

**Issue by Knuten** [AeroScripts/QuestieDev#1433]
## Bug description
Tracking of the quest Winterfall Intrusion is not updated after the first completion after the game has loaded (a reload makes it work again for one turn-in).
Stopping and starting tracking of the quest updates the tracjer to the current progress but new progress is not tracked.

## Screenshots
![image](https://user-images.githubusercontent.com/57028188/67615165-2dc6c800-f7c9-11e9-8834-30a181ae5350.png)

## Questie version
5.0.1 2 e2e80b7

**Comment by BreakBB** [comment]
@Knuten Could you try the version below and report if the issue still exists? I can't test this at this point.

[Questie-v5.0.1_191-7487c4a.zip](https://github.com/AeroScripts/QuestieDev/files/3805211/Questie-v5.0.1_191-7487c4a.zip)

**Comment by BreakBB** [comment]
@Knuten Did you update to v5.1.0 and still experience issues?

**Comment by Knuten** [comment]
@BreakBB Sorry, forgot to respond to your first post. 

I am done with the rep farm so I am no longer doing these quests. If I am in Winterspring with some spare time on my hands I will test it with the latest updated questie and let you know if it works or not.

**Comment by BreakBB** [comment]
@Knuten That would be very great!

**Comment by coneone** [comment]
@BreakBB I tried it with 5.1.0 and the issue is still happening.
