### ISSUE TITLE
Freezes when loaded with AQT

### ISSUE THREAD

**Issue by Aiue** [AeroScripts/QuestieDev#1436]
## Bug description
I've been getting [reports](https://github.com/Aiue/AQT/issues/57) of Questie and AQT freezing when being run together in the koKR client. I've as of yet been unable to reproduce it myself, running the English client.

> The conflict with 'Questie' was that only two addons were used while the quest list was full and all other addons were disabled for testing. The symptom is that the screen freezes as soon as the computer is racking up during the game.
_Originally posted by @chkmyid in https://github.com/Aiue/AQT/issues/56#issuecomment-546560061_

I'll be taking a look at the code of both addons to see if I can find something that might be causing this, but being unable to reproduce it myself could make it rather troublesome to figure out a cause, or determine if a fix is at all functional. It seems reasonable we both should be aware of this and see if we can determine what might be causing this.

## Questie version
Unknown.

**Comment by Aiue** [comment]
While it probably has nothing at all to do with this, I did find something else:

https://github.com/AeroScripts/QuestieDev/blob/28fbd4c3052ffaed80f9553dad9a2ea62d7cf0dc/Modules/QuestieQuest.lua#L283
https://github.com/AeroScripts/QuestieDev/blob/28fbd4c3052ffaed80f9553dad9a2ea62d7cf0dc/Modules/QuestieQuest.lua#L304

Nope. Should not be needed, as you can pass the index as an optional second argument to GetQuestLogLeaderBoard(). Should be a much cleaner way of doing it.

**Comment by BreakBB** [comment]
@Aiue Can you tell if this is still an issue?

**Comment by BreakBB** [comment]
This issue is being closed due to lack of information. It will remain archived in GitHub should more information become available.
