### ISSUE TITLE
Enable Map Icon toggles off v5.0.1

### ISSUE THREAD

**Issue by watsonthecat** [AeroScripts/QuestieDev#1437]
Map icons keep disappearing. Try Shift + Left Click to reload and go into settings to ensure 'Enable Map Icon' is checked. Had to click it on/off and got Map Icons to display again. Recurring issue.

**Comment by BreakBB** [comment]
Please follow our issue template next time.

This could be related to #1248 

Do you use Leatrix?

**Comment by BreakBB** [comment]
Closing because of the lack of information.
