### ISSUE TITLE
Current version not working with classic?

### ISSUE THREAD

**Issue by biznatch112** [AeroScripts/QuestieDev#1438]
## Bug description
Addon is active, can change settings, even after several reloads and even reinstalls it still is not working as intended. suddenly happened while playing yesterday. cannot work out a fix after following all standard trouble shooting methods

[WoWScrnShot_102719_073353](https://user-images.githubusercontent.com/57048142/67625626-36340700-f88c-11e9-893a-4cec0ae1c632.jpg)
![WoWScrnShot_102719_073400](https://user-images.githubusercontent.com/57048142/67625627-36cc9d80-f88c-11e9-883f-044d8732be06.jpg)

# Commit hash: 
## SavedVariablesPerCharacter: QuestieConfigCharacter

embeds.xml
Libs\HereBeDragons\HereBeDragons-2.0.lua
Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua
Libs\HereBeDragons\HereBeDragons-Migrate.lua

#stream module (used by DB)
Modules\QuestieStream.lua

#Databases
Database\TEMP_questie2events.lua
Database\questDB.lua
Database\objectDB.lua
Database\spawnDB.lua
Database\zoneDB.lua
Database\TEMP_questie4items.lua
Database\TEMP_repprof.lua
Database\specialspawns.lua
Database\corrections.lua
Database\functionsDB.lua

#Localization
Locale\QuestieLocale.lua
Locale\enUS\locale.xml
Locale\esES\locale.xml
Locale\deDE\locale.xml
Locale\zhCN\locale.xml
Locale\zhTW\locale.xml
Locale\frFR\locale.xml
Locale\koKR\locale.xml
Locale\ptBR\locale.xml
Locale\ruRU\locale.xml

#Modules
Modules\QuestieTooltips.lua
Modules\QuestieEventHandler.lua
Modules\QuestieFramePool.lua
Modules\QuestieMap.lua
Modules\QuestieQuest.lua
Modules\QuestieNameplate.lua
Modules\QuestieCoordinates.lua
Modules\QuestieJourney.lua
Modules\QuestieComms.lua

#Main
Questie.lua

**Comment by BreakBB** [comment]
Please update Questie from v4.0.10 to v5.0.1 and report if it helps

**Comment by BreakBB** [comment]
Assuming this is solved.
