### ISSUE TITLE
Incorrect target mobs for "Reagents for Reclaimers Inc."

### ISSUE THREAD

**Issue by proksch** [AeroScripts/QuestieDev#1439]
## Description

While issue #777 might have solved part of the problem with the quest chain [Reagents for Reclaimers Inc.](https://classic.wowhead.com/quest=1458/reagents-for-reclaimers-inc), I found the tool tips for the follow-up steps to be incorrect/misleading. For [Step 2](https://classic.wowhead.com/quest=1459/reagents-for-reclaimers-inc) of the chain, only a fraction of the qualifying Scorpashi mobs are marked on the map and the Aged Kodos are marked in a hut, instead of at the Kodo graveyard.

For [Step 3](https://classic.wowhead.com/quest=1466/reagents-for-reclaimers-inc) of the chain, Questie says that all reagents drop from [Doomwarder Captains](https://classic.wowhead.com/npc=4680/doomwarder-captain), which only drop [Doomwarder Blood](https://classic.wowhead.com/item=6252/doomwarder-blood) though. [Felhound Brain](https://classic.wowhead.com/item=6250/felhound-brain) and [Nether Wings](https://classic.wowhead.com/item=6251/nether-wing) drop from other mobs.

## Questie version

4.2.0 (3bf27b9)

**Comment by BreakBB** [comment]
@proksch Please update to the latest Questie version 5.0.1 and check again.

**Comment by proksch** [comment]
Sorry, too late. I have already finished the quests.

**Comment by BreakBB** [comment]
I assume then this is fixed, since we changed the logic how objectives are found and marked on mobs. The referenced PR will add some more spawns for the Aged Kodos.
