### ISSUE TITLE
Artifact in !Questie.toc

### ISSUE THREAD

**Issue by Muehe** [AeroScripts/QuestieDev#144]
Just a cleanup issue, but the QuestieTracker.xml is still listed in the !Questie.toc, besides not being present in the folder anymore. I assume the file has been deleted.

On a sidenote, is there some better way to contact you for asking questions? Like some forum or reddit thread?

**Comment by AeroScripts** [comment]
I try to check the issue tracker but you can also post to https://forum.nostalrius.org/viewtopic.php?f=63&t=2820 or PM the original poster of that thread.
