### ISSUE TITLE
Quest #5651 - In Favor of Darkness

### ISSUE THREAD

**Issue by wow-classic** [AeroScripts/QuestieDev#1445]
## Description
This quest is not shown on the map. (In the Russian version WoW)

## Wowhead link
https://classic.wowhead.com/quest=5651

## Questie version
Version: 5.0.1 2 e2e80b7

**Comment by BreakBB** [comment]
@wow-classic With what character did you do this quest? It is listed as only be available for Undead Priests.

**Comment by wow-classic** [comment]
> @wow-classic With what character did you do this quest? It is listed as only be available for Undead Priests.

I was an undead priest, but I did not see this quest on the minimap.

**Comment by BreakBB** [comment]
Correctly shown on v5.2.2 at level 5 with an undead priest:

![image](https://user-images.githubusercontent.com/33514570/69237378-dcc2ad80-0b95-11ea-9f06-9fd6116c87b1.png)
