### ISSUE TITLE
Quest log overwrite timer quests

### ISSUE THREAD

**Issue by teyasio** [AeroScripts/QuestieDev#1448]
When ever there is a timed quest. The tracker quest list overlays on top of it

**Comment by BreakBB** [comment]
You can move the tracker with `CTRL + left click` and I think you can also move the timer.

**Comment by kwdreas** [comment]
Would be helpful if you could hook the Quest Timer frame to make it movable or replace it with your own and make that movable.

**Comment by BreakBB** [comment]
In the next release the timer will be included somehow similar to this:

![image](https://user-images.githubusercontent.com/33514570/68254259-6d43ae80-002a-11ea-8312-5f6f394707ce.png)

It might be changed how exactly it is displayed though.
