### ISSUE TITLE
Quest 7669 - Again Into the Great Ossuary

### ISSUE THREAD

**Issue by dimsno** [AeroScripts/QuestieDev#1449]
## Description
The quest is not showing up on map and does not seem to be in the database.

## Wowhead link
https://classic.wowhead.com/quest=7669/again-into-the-great-ossuary

## Questie version
Questie v5.0.1

**Comment by BreakBB** [comment]
@dimsno Do you refer to the Shaman quest to get the [Skyfury Helm](https://classic.wowhead.com/item=20134/skyfury-helm) or some other quest? I am not sure if the quest with ID 7669 is in the game.
