### ISSUE TITLE
Wrong quest completion location (Fiora Longears)

### ISSUE THREAD

**Issue by Edupop** [AeroScripts/QuestieDev#145]
In vanilla wow, Fiora Longears was erroneously placed in the Theramore inn. Her location was corrected in one of the BC patches.

The quest "Fiora Longears" should complete at 66, 45

**Comment by AeroScripts** [comment]
Thanks for the info, I'll update the value in the database. I should probably go through and pull in all new data for quest NPC locations, that's the only thing thats still taken directly from questhelper for BC
