### ISSUE TITLE
Duplicate Related-quest lines on Item Tooltips that share names with GameObjects

### ISSUE THREAD

**Issue by StrangelyTyped** [AeroScripts/QuestieDev#1451]
## Bug description
Relating to the quest [A Noble Brew](https://classic.wowhead.com/quest=335/a-noble-brew), the two items relating to the quest have duplicate entries on their tooltips showing the quest they relate to (see screenshot below). I've done some debugging and this appears to be due to the fact that these two items are both looted from GameObjects of the same name. The tooltip-related code in QuestieTooltips.lua appears to perform a GameObject lookup-by-name in every OnUpdate call without checking if the tooltip relates to an item or unit, resulting in it finding a related GameObject by name (since the items share the GameObject's name) and also then finding the related item information. The GameObject code also unconditionally resets the last tooltip type to 'object' every OnUpdate regardless of whether a matching object was found (not technically relevant in this case since a matching object would have been found regardless, but probably sub-optimal). 

If there is some way to check if a tooltip relates to an item or unit before doing a GameObject lookup (e.g. by calling :GetItem or :GetUnit on the tooltip as the item/unit code does) that that would seem to solve the problem, but my UI dev is far too rusty to write and submit such a patch.

## Screenshots
![WoWScrnShot_102719_234149](https://user-images.githubusercontent.com/16519546/67644246-b81d4200-f917-11e9-832c-40a0a4999fd0.jpg)

## Questie version
v5.0.1_e2e80b7

**Comment by Logonz** [comment]
Good explanation! Ill look into it!

**Comment by StrangelyTyped** [comment]
I still have the quest, I tested your patch and it appears to resolve the issue

**Comment by BreakBB** [comment]
@StrangelyTyped Thank you very much for keeping the quest and reporting back on this! Glad it could be fixed this easy 👍
