### ISSUE TITLE
All "Talismans of Merit" quests are missing from questDB

### ISSUE THREAD

**Issue by WoWBoi653** [AeroScripts/QuestieDev#1453]
## Description
QuestDB is missing all "Talismans of Merit" quests.

## Wowhead link(s)
[Lv 15](https://classic.wowhead.com/quest=8289/talismans-of-merit)
[Lv 25](https://classic.wowhead.com/quest=7921/talismans-of-merit)
[Lv 35](https://classic.wowhead.com/quest=7887/talismans-of-merit)
[Lv 45](https://classic.wowhead.com/quest=7888/talismans-of-merit)
[Lv 55](https://classic.wowhead.com/quest=7886/talismans-of-merit)
[Lv 60](https://classic.wowhead.com/quest=8292/talismans-of-merit)

## Screenshots
N/A

## Questie version
5.0.1

**Comment by Muehe** [comment]
@WoWBoi653 They are in the DB now, but we have no starting and finishing NPC/object/item in either the cmangos DB or on Wowhead. Can you tell us where they start?

**Comment by BreakBB** [comment]
@AndrewVBragg listed [Sentinel Farsong](https://classic.wowhead.com/npc=14733/sentinel-farsong) as starting and ending NPC. [Wow-Frekz](https://www.wow-freakz.com/quest_helper.php?quest=8289) also list the Sentinel as ending NPC.

**Comment by BreakBB** [comment]
This should be fixed.
