### ISSUE TITLE
Mastering the Elements (and possibly other related quests)

### ISSUE THREAD

**Issue by silverhawke249** [AeroScripts/QuestieDev#1456]
## Description
the quest Mastering the Elements, given by Bath'rah the Windwatcher in Alterac Mountains, appears on the map but it's not actually available (apparently it's only for Phase 4?)

## Wowhead link
Link to a related quest, comments explaining why it's not in Classic WoW
https://classic.wowhead.com/quest=8410/elemental-mastery

## Questie version
Version: 5.0.0 7 fb7c60e

**Comment by BreakBB** [comment]
The quest should already been blacklisted:

https://github.com/AeroScripts/QuestieDev/blob/25a8776f9ab6eae22acc864f5ec5ba4d018d4ef9/Database/Corrections/QuestieQuestBlacklist.lua#L629

**Comment by BreakBB** [comment]
Nevermind, I found another version of the quest and blacklisted it.
