### ISSUE TITLE
QuestID: 6543 - The Warsong Reports

### ISSUE THREAD

**Issue by rbpaiett** [AeroScripts/QuestieDev#1458]
## Description
 After receiving all 3 reports, the game itself indicates that all 3 subquests are complete and ready for turn-in.  However, the quest tracker indicates that the reports have not been received as yet.

--edit:  Later on, I went to turn it in and 'continue' is pressed, then the tracker shows 'Quest Complete'.  So, this is a matter whether the tracker shows it completed and ready to turn in when you receive the reports or the quest giver receives them.  It's just done a different times between the game quest system and Questie's system.

## Wowhead link
https://classic.wowhead.com/quest=6543/the-warsong-reports

## Screenshots

<img width="776" alt="Questie - The Warsong Reports" src="https://user-images.githubusercontent.com/1621701/67664288-97a7b480-f924-11e9-9b25-291c98fdcdd1.png">

## Questie version
 ver. 5.0.1 release.

**Comment by BreakBB** [comment]
Fixed with 326761c8a6c6ab7407096196df99887298d866de
