### ISSUE TITLE
Water Pouch Bounty, repeatable not being shown (Tanaris)

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#1459]
## Description

Questie is simply not showing the repeatable version of this quest as part of the Gadgetzan rep farm after doing the "normal" version :) 

## Wowhead link

normal quest: https://classic.wowhead.com/quest=1707/water-pouch-bounty#comments
repeatable version: https://classic.wowhead.com/quest=1878/water-pouch-bounty#comments

## Screenshots

none required

## Questie version

v5.0.1

**Comment by drejjmit** [comment]
This is already fixed on master. Will be included in the next release.
https://github.com/AeroScripts/QuestieDev/commit/003b2860e25b2080691ec82eeb6c5065d4f6e299
