### ISSUE TITLE
Item price text becomes darker after using Questie

### ISSUE THREAD

**Issue by weirddan455** [AeroScripts/QuestieDev#146]
After a while of using Questie (sometimes just talking to an NPC triggers the bug but it almost always occurs after completing a quest) the text of the price of an item becomes much darker and hard to see.  The two places I've noticed this is selling an item to a vendor and buying a flight from a flight master.  When you first start the game, the text looks like this:

![questiebug2](https://cloud.githubusercontent.com/assets/8128047/9720329/a377b938-5552-11e5-864e-aafa2f04d09d.jpg)

After playing for a little bit, the text changes to look like this:

![questiebug1](https://cloud.githubusercontent.com/assets/8128047/9720340/be9e6ec8-5552-11e5-92dc-b3300410bfe2.jpg)

This happens every time I use Questie.  I removed all my other addons to make sure Questie was at fault (and this doesn't happen when Questie is disabled.)  Fairly minor bug but thought I would report it in any case.

EDIT:  I'm using version 2.0.12.

**Comment by AeroScripts** [comment]
Yeah, I thought I fixed this issue, the old one is #128 but apparently it's still not. I'll look into this again (it has to do with frame layering)

**Comment by Wieners** [comment]
So has this been fixed?I have the same problem and idk how to use this site to search if it got fixed.
