### ISSUE TITLE
unchecking "Enable Tooltips" does not disable item tooltips

### ISSUE THREAD

**Issue by horsedge** [AeroScripts/QuestieDev#1460]
## Bug description
In the general tab of questie settings, the button "Enable Tooltips" when unchecked, successfully removes tooltips from mobs, but not items. Item tooltips cannot be turned off.

## Screenshots
![image](https://user-images.githubusercontent.com/57139212/67767484-e7ae7600-fa0d-11e9-88a9-b32add176f61.png)
![image](https://user-images.githubusercontent.com/57139212/67767506-f137de00-fa0d-11e9-94f5-aa55100913eb.png)

## Version: 5.0.1 2 e2e80b7

**Comment by BreakBB** [comment]
Fixed on master and will be included in the upcoming release! Thanks for the report @horsedge 👍
