### ISSUE TITLE
High executor derrington quests

### ISSUE THREAD

**Issue by lawdon85** [AeroScripts/QuestieDev#1463]
## Description
i am now at 2 quests completed yet questie shows the same two still available from High Executor Derrington at The bulwark.

Quests linked below, note that the 'Key to scholomance' quest is given by Apothecary Dithers. once i handed it in to him and completed, questie then showed the same quest available but fro Derrington

## Wowhead link
https://classic.wowhead.com/quest=5511/the-key-to-scholomance

https://classic.wowhead.com/quest=5238/mission-accomplished

**Comment by BreakBB** [comment]
@lawdon85 Sorry for the late response on this. Could you run the following commands and report the output:

`/dump IsQuestFlaggedCompleted(5505)`
`/dump IsQuestFlaggedCompleted(5511)`
`/dump IsQuestFlaggedCompleted(5238)`
`/dump IsQuestFlaggedCompleted(5237)`
`/dump IsQuestFlaggedCompleted(5236)`
`/dump IsQuestFlaggedCompleted(5226)`

**Comment by BreakBB** [comment]
Closing because of the lack of information.
