### ISSUE TITLE
Patrolling lines don't work with Leatrix maps

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#1465]
## Bug description

Reported on Discord.

When using Leatrix maps in non fullscreen mode the lines of patrolling NPCs aren't drawn correctly. Resizing the map to fullscreen helps though.

## Screenshots

![image](https://user-images.githubusercontent.com/33514570/67866761-b88d2700-fb29-11e9-8a00-a7760195207d.png)

## Questie version

v5.0.1 115 0d67199

**Comment by Logonz** [comment]
Thats not leatrix maps?
I use leatrix map in non-fullscreen mode exclusively.

**Comment by harveysingh1** [comment]
Just saw this whilst I was going through the same issue. Looks like it's not Leatrix but Tomcat's Tours which is another map addon. Just posting if anyone else has the same issue

**Comment by BreakBB** [comment]
There is an open issue on [Tomcat's Tours(https://www.curseforge.com/wow/addons/tomcats/issues/19) which addresses this issue. Other map addons work fine (like Leatrix) with Questie so it is not on us to fix this.
