### ISSUE TITLE
Simple Subterfugin' (Rogue) shown but not available

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#1466]
Questie v4.3.0
https://classic.wowhead.com/quest=2238/simple-subterfugin

Human rogue.
Quest is shown in Ironforge, but it's not available.
You can only do 1 of the city chains (see Wowhead link) and I've already completed the one in Stormwind.

**Comment by Nerillida** [comment]
I have done all three chains, you need to pick up the prerequisites, for this it's Road to Salvation, for the Self version, it's The Apple Falls. You have to sell your blade of whatever as it's unique, before turning subsequent versions.

**Comment by BreakBB** [comment]
@Nerillida Since I have no Rogue to test this and there are just a few comments on Wowhead, could you explain in detail how the quest work and which require which?

**Comment by Nerillida** [comment]
OK. Take rogue thru one quest chain, any really. get the reward. The original guy did the human chain,
Seek out SI: 7, Snatch and Grab. You get the Blade of Cunning, it's unique.
Go to Kharanos, pick up Road to Salvation, then Simple Subterfugin, then Onin's Report. Before turning in Onin's Report, sell the Blade of Cunning.
Repeat for The Apple Falls, Destiny Calls.

I did not test if Seek out SI: 7 unlocked  Simple Subterfugin etc

**Comment by BreakBB** [comment]
@Painstormx @Nerillida  Could you please run the following commands and report the output:

`/dump IsQuestFlaggedCompleted(2205)`
`/dump IsQuestFlaggedCompleted(2218)`
`/dump IsQuestFlaggedCompleted(2241)`

`/dump IsQuestFlaggedCompleted(2206)`
`/dump IsQuestFlaggedCompleted(2238)`
`/dump IsQuestFlaggedCompleted(2242)`

`/dump IsQuestFlaggedCompleted(2239)`

**Comment by Painstormx** [comment]
2205 - true
2218 - false
2241 - false
2206 - true
2238 - false
2242 - false
2239 - false

**Comment by Nerillida** [comment]
2205 - true
2218 - true
2241 - true
2206 - true
2238 - true
2242 - true
2239 - true

Some Wowhead discussion seems to support the idea of doing all three chains.

**Comment by BreakBB** [comment]
As it seems you can do all three quests as long as you don't have the [Blade of Cunning](https://classic.wowhead.com/item=7298/blade-of-cunning) on you, as it is unique.

I removed some exclusivity on the breadcrumb quests (thanks @Nerillida ).

@Painstormx You should check if you really can't do the quests and report back if possible. I'll leave a current version which includes the fix:

[Questie-v5.0.1_196-59e38ef.zip](https://github.com/AeroScripts/QuestieDev/files/3806539/Questie-v5.0.1_196-59e38ef.zip)

**Comment by Nerillida** [comment]
You can do all the quests, you just can't turn in the chain ends without getting rid of the unique weapon. I,e, stop at the vendor before talking to the turn-in guy.
Anyway, Iamsure your fix will work.
