### ISSUE TITLE
LUA error after completion of Scythe of Elune

### ISSUE THREAD

**Issue by fireboy92k** [AeroScripts/QuestieDev#1468]
## Bug description
The following LUA error appeared as I was turning in the quest.

Date: 2019-10-30 22:51:38
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\Map\QuestieMap.lua line 184:
   attempt to index field 'data' (a nil value)
Debug:
   Questie\Modules\Map\QuestieMap.lua:184:
      Questie\Modules\Map\QuestieMap.lua:162
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:
self = <table> {
 _callback = <function> defined @Interface\SharedXML\C_TimerAugment.lua:14
}
mapDrawCall = <table> {
 1 = <table> {
 }
 2 = QuestieFrame209 {
 }
 3 = 1431
 4 = 0.753200
 5 = 0.490200
 6 = 3
}
minimapDrawCall = <table> {
 1 = <table> {
 }
 2 = QuestieFrame217 {
 }
 3 = 1431
 4 = 0.753200
 5 = 0.490200
 6 = true
 7 = true
}
frame = QuestieFrame209 {
 glowLogicTimer = <table> {
 }
 glow = QuestieFrame209Glow {
 }
 BaseOnUpdate = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:283
 FakeUnhide = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:407
 FakeHide = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:392
 texture = <unnamed> {
 }
 BaseOnShow = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:288
 BaseOnHide = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:305
 0 = <userdata>
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:309
 GlowUpdate = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:271
 FadeIn = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:379
 FadeOut = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:365
}
(*temporary) = nil
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 minimapConfigIcon = <table> {
 }
 Colorize = <function> defined @Interface\AddOns\Questie\Questie.lua:265
 Enable = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:85
 GetClassColor = <function> defined @Interface\AddOns\Questie\Questie.lua:283
 EnableModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 configFrame = <unnamed> {
 }
 UnregisterComm = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\DBM-Core\Libs\AceTimer-3.0\AceTimer-3.0.lua:172
 Deserialize = <function> defined @Interface\AddOns\DBM-Core\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 UnregisterChatCommand = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
 RegisterBucketEvent = <function> defined @Interface\AddOns\DBM-Core\Libs\AceBucket-3.0\AceBucket-3.0.lua:184
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\DBM-Core\Libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface\AddOns\DBM-Core\Libs\AceTimer-3.0\AceTimer-3.0.lua:160
 Printf = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 baseName = "Questie"
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 debug = <function> defined @Interface\AddOns\Questie\Questie.lua:343
 Debug = <function> defined @Interface\AddOns\Questie\Questie.lua:325
 error = <function> defined @Interface\AddOns\Questie\Questie.lua:314
 name = "Questie"
 Error = <function> defined @Interface\AddOns\Questie\Questie.lua:310
 IsEnabled = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\DBM-Core\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 OnEnable = <function> defined @Interface\AddOns\Questie\Questie.lua:197
 OnDisable = <function> defined @Interface\AddOns\Questie\Questie.lua:201
 QuestieSlash = <function> defined @Interface\AddOns\Questie\Questie.lua:205
 OnUpdate = <fu
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.3.3
  AtlasLootClassicData, vv1.3.3
  AtlasLootClassicDungeonsAndRaids, vv1.3.3
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  Bartender4, v4.8.8
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  DBMCore, v1.13.18
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemTooltipProfessionIcons, v1.1.3
  QuestCompletist, v109.25
  Questie, v5.0.1 2 e2e80b7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11302-1.0.7
  WeakAuras, v2.15.5
  WeaponSwingTimer, v4.1.0
  WideQuestLog, v
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=4fa)

## Questie version
  Questie, v5.0.1 2 e2e80b7

**Comment by BreakBB** [comment]
Related to #1475 and already fixed!
