### ISSUE TITLE
Tracked quests don't match up with the checkmarks on EQL3 quest log

### ISSUE THREAD

**Issue by weirddan455** [AeroScripts/QuestieDev#147]
When I start the game, Questie will already be tracking some quests.  If I go into the quest log and shift-click one of those quests, EQL3 puts a checkmark by it indicating it's tracked while Questie untracks it.  This is only true for the quests that Questie tracks at game launch.  The others match up with EQL3.

Perhaps Questie could communicate with EQL3 which quests are being tracked so the checkmarks match up.

Again, another minor bug and maybe the fault lies with EQL3 but I couldn't find a GitHub for that project.  I know Questie has already done some compatibility fixes for EQL3 though so maybe put this as a feature request?

EDIT:  I'm using version 2.0.12.

**Comment by AeroScripts** [comment]
I'll see if I can make some more integration with EQL3 to support this

**Comment by Schaka** [comment]
There is some EQL3 support already, but it broke with further updates. Maybe you can find it in Questie v1.0 or even leftovers in 2.0

**Comment by Logonz** [comment]
This is an important issue, EQL is used by most people, the support needs to be top notch, going to add this as a milestone for 3.0

**Comment by Logonz** [comment]
Fixed in 3.0
