### ISSUE TITLE
Misplaced marker for KILL ON SIGHT: High Ranking Dark Iron Officials

### ISSUE THREAD

**Issue by silverhawke249** [AeroScripts/QuestieDev#1471]
## Description
When quest is completed, turn-in marker points at the notice board. It should be on Warlord Goretooth, who is at the top of a nearby tower

## Wowhead link
https://classic.wowhead.com/quest=4082/kill-on-sight-high-ranking-dark-iron-officials

## Questie version
Version: 5.0.1 2 e2e80b7

**Comment by BreakBB** [comment]
A screenshot would have been good for such a case, but thanks for the report!

The NPC is listed correctly in our DB with spawn at `5.81 , 47.52`, but had bad waypoints, which might have lead to this issue.

**Comment by silverhawke249** [comment]
yeah, i realized i should have took a screenshot, but i only realized i should report it after turning it the quest, oops.

**Comment by BreakBB** [comment]
@silverhawke249 No worries! We're happy for every report and help we get 😄
