### ISSUE TITLE
Questie LUA when I log on or reload UI

### ISSUE THREAD

**Issue by woofpup** [AeroScripts/QuestieDev#1472]
Date: 2019-10-31 15:52:40
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\Map\QuestieMap.lua line 183:
   attempt to index local 'mapDrawCall' (a nil value)
Debug:
   [C]: ?
   Questie\Modules\Map\QuestieMap.lua:183:
      Questie\Modules\Map\QuestieMap.lua:162
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Auctionator, v8.1.0
  BagBrother, v
  ClassicQuestLog, v1.4.5-Classic
  ClassicCodex, v1.2.2
  Combuctor, v8.2.10
  Dominos, v8.2.30
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  EasyFishingClassic, v1.2
  GFWFeedOMatic, v8.0
  LeatrixMaps, v1.13.36
  LeatrixPlus, v1.13.37
  Questie, v5.0.1 2 e2e80b7
  SellJunk, v3.0.20
  SexyMap, vv3-classic
  Stubby, v8.2.6376 (SwimmingSeadragon)
  Titan, v5.17.1.80100
  TitanBag, v5.17.1.80100
  TitanClock, v5.17.1.80100
  TitanGold, v5.17.1.80100
  TitanLocation, v5.17.1.80100
  TitanMail, v7.35
  TitanPerformance, v5.17.1.80100
  TitanReloadUI, v1.0
  TitanRepair, v5.17.1.80100
  TitanShard, v4.3.1.30300
  TitanVolume, v5.17.1.80100
  TitanXP, v5.17.1.80100
  TomTom, vv11302-1.0.7
  TradeSkillMaster, vv4.8.20
  TradeSkillMasterAppHelper, vv4.0.4
  VendorPrice, v1.2.9
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=50e)

**Comment by BreakBB** [comment]
Please follow our issue template so we get all the required information.

What version of Questie do you use?

**Comment by BreakBB** [comment]
Related to #1475 and already fixed.
