### ISSUE TITLE
questie tracker doesn't showing any text

### ISSUE THREAD

**Issue by fullmetalnayce** [AeroScripts/QuestieDev#1474]
## Bug description
1. questie is working well
2. i can see quest icons in mini map and world map 
3. quest tracker of questie are floating in my screen, so i can see tracker's black box 
4. but tracker doesn't showing any text, quest name, quest object, anything

my issue occurs yesterday, until now
i reinstall wow classic twice, reinstall questie addon many time, uninstall and reinstall other addons several times, but same problem repeat

## Screenshots
![WoWScrnShot_110119_133223](https://user-images.githubusercontent.com/57245424/68002440-3aa55900-fcac-11e9-8220-48c0fbba03da.jpg)

my tracker option

![WoWScrnShot_110119_132907](https://user-images.githubusercontent.com/57245424/68002441-3b3def80-fcac-11e9-9c2f-a859c52001b8.jpg)
![WoWScrnShot_110119_132915](https://user-images.githubusercontent.com/57245424/68002442-3b3def80-fcac-11e9-9dcb-02936350d377.jpg)
![WoWScrnShot_110119_132920](https://user-images.githubusercontent.com/57245424/68002443-3b3def80-fcac-11e9-92d3-0553ea5c72d8.jpg)
![WoWScrnShot_110119_132927](https://user-images.githubusercontent.com/57245424/68002444-3b3def80-fcac-11e9-9589-51ebadeb491d.jpg)

i can see quest icons in maps, so addon working very well

![WoWScrnShot_110119_132929](https://user-images.githubusercontent.com/57245424/68002516-9243c480-fcac-11e9-93ec-35e72c6b50f7.jpg)

tracker also working so i can see black box in red circle, but that is not showing any text.
that is my problem

## Questie version
Questie-v5.0.1_2-e2e80b7.zip

**Comment by fullmetalnayce** [comment]
i fix it

[CRITICAL] [QuestieDB:GetQuest] rawdata is nil for questID: 7670

this quest is 100% faster ride reward for paladin, 
"Lord Grayson Shadowbreaker"

i give up this quest, tracker working well.
i receive that quest again, tracker being empty again.

**Comment by BreakBB** [comment]
Already fixed with c7c3aeab63d9f3d0635342e5b889e6dbea36f01f

Will be included in the next release :)
