### ISSUE TITLE
Random Global Lua

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#1475]
## Bug description

got this one just randomly after going back to my corpse

Date: 2019-11-01 15:37:57
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\Map\QuestieMap.lua line 184:
   attempt to index field 'data' (a nil value)
Debug:
   Questie\Modules\Map\QuestieMap.lua:184:
      Questie\Modules\Map\QuestieMap.lua:162
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:
self = <table> {
 _callback = <function> defined @Interface\SharedXML\C_TimerAugment.lua:14
}
mapDrawCall = <table> {
 1 = <table> {
 }
 2 = QuestieFrame255 {
 }
 3 = 1439
 4 = 0.443900
 5 = 0.763100
 6 = 3
}
minimapDrawCall = <table> {
 1 = <table> {
 }
 2 = QuestieFrame256 {
 }
 3 = 1439
 4 = 0.443900
 5 = 0.763100
 6 = true
 7 = true
}
frame = QuestieFrame255 {
 glowLogicTimer = <table> {
 }
 glow = QuestieFrame255Glow {
 }
 BaseOnUpdate = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:283
 FakeUnhide = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:407
 FakeHide = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:392
 texture = <unnamed> {
 }
 BaseOnShow = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:288
 BaseOnHide = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:305
 0 = <userdata>
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:309
 GlowUpdate = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:271
 FadeIn = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:379
 FadeOut = <function> defined @Interface\AddOns\Questie\Modules\QuestieFramePool.lua:365
}
(*temporary) = nil
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 minimapConfigIcon = <table> {
 }
 Colorize = <function> defined @Interface\AddOns\Questie\Questie.lua:265
 Enable = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:85
 GetClassColor = <function> defined @Interface\AddOns\Questie\Questie.lua:283
 EnableModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 configFrame = <unnamed> {
 }
 UnregisterComm = <function> defined @Interface\AddOns\Armory\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\DBM-Core\Libs\AceTimer-3.0\AceTimer-3.0.lua:172
 Deserialize = <function> defined @Interface\AddOns\DBM-Core\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 UnregisterChatCommand = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
 RegisterBucketEvent = <function> defined @Interface\AddOns\DBM-Core\Libs\AceBucket-3.0\AceBucket-3.0.lua:184
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\DBM-Core\Libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface\AddOns\DBM-Core\Libs\AceTimer-3.0\AceTimer-3.0.lua:160
 Printf = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 baseName = "Questie"
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 debug = <function> defined @Interface\AddOns\Questie\Questie.lua:343
 Debug = <function> defined @Interface\AddOns\Questie\Questie.lua:325
 error = <function> defined @Interface\AddOns\Questie\Questie.lua:314
 name = "Questie"
 Error = <function> defined @Interface\AddOns\Questie\Questie.lua:310
 IsEnabled = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\DBM-Core\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 OnEnable = <function> defined @Interface\AddOns\Questie\Questie.lua:197
 OnDisable = <function> defined @Interface\AddOns\Questie\Questie.lua:201
 QuestieSlash = <function> defined @Interface\AddOns\Questie\Questie.lua:205
 OnUpdate = <f
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ACP, v3.5.6 
  AdvancedInterfaceOptions, v1.3.3
  Armory, vv1.2
  Atlas, vv1.45.01.11302
  AtlasBattlegrounds, vv1.45.00.11302.00
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasTransportation, vv1.45.00.11302.00
  AtlasLootClassic, vv1.3.3
  AtlasLootClassicDungeonsAndRaids, vv1.3.3
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.11.55
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BadBoy, vv1-classic
  BasicChatMods, vv4-classic
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  ClassicQuestLog, v1.4.5-Classic
  DBMCore, v1.13.18
  DBMCountPackHotS, v1.7.3
  DBMCountPackOverwatch, v1.4.7
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DBMVPVEM, v9.0.0
  DejaClassicStats, v1302r037
  DressUp, v3.2.0-classic
  GTFO, v4.51
  HealBot, v1.13.2.9
  HealBotTips, v1.13.2.9
  InFlightLoad, v1.13.003
  Informant, v8.2.6374 (SwimmingSeadragon)
  LetMeCast, v1.3
  LFGShout, v11302.17
  LibClassicMobHealth10, v1.0
  LibSharedMedia30, v3.0-113
  Mapster, v1.8.5
  MarkMe, v0.9.7
  OmniCC, v8.2.5
  orbSellAndRepair, v1.0.1
  Poisoner, v1.13.2.15-classic
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v5.0.1 2 e2e80b7
  RealMobHealth, v2.13
  SaySapped, v2019-08-27
  SimpleUnitFrames, v11302-5
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TooltipItemIcon, v1.77
  VendorPrice, v1.2.9
  WhatsTraining, v1.8.7
  ZoneDetails, v1.0.1
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=761)

## Questie version

v5.0.1

**Comment by BreakBB** [comment]
This is already fixed on the master branch and will be included in the next release. Thanks for another report @reaper666735 🎉
