### ISSUE TITLE
The Touch of Zanzil (Rogue) missing icons in SW

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#1476]
## Description

while doing the Klaven's tower quest in Westfall for the Rogue class quest you get poisoned, following the chain you learn how to make poisons but also a quest to "Cure" yourself, one of the items you need to buy in in the Flower shop in SW @ 64, 60  but no icon is shown on map or tooltip for the NPC's

also you might want to add an icon for the Bronze tube with Billibub Cogspinner (55, 7) in the Dwarven district, he sometimes has some for sale otherwise people will have to hit the AH :p

## Wowhead link

Quest: https://classic.wowhead.com/quest=2609/the-touch-of-zanzil#comments
Item: https://classic.wowhead.com/item=3421/simple-wildflowers
NPC's: https://classic.wowhead.com/npc=1302/bernard-gump  /  https://classic.wowhead.com/npc=1303/felicia-gump

tube NPC: https://classic.wowhead.com/npc=5519/billibub-cogspinner

## Screenshots

Flowers from NPC: https://imgur.com/ynD50Ek

me in front of shop with map open (before buying): https://imgur.com/SauS8xc

bronze tube: https://imgur.com/Qbt3HUM

## Questie version

v5.0.1

**Comment by xEvilgrin** [comment]
sorry to contradict... the vendor Herbie Baubbletump next to the questgiver offers the tube as well
https://classic.wowhead.com/npc=3133/herble-baubbletump

**Comment by reaper666735** [comment]
well your right :) , 

but unfortunately he's mostly out of stock from the  https://classic.wowhead.com/quest=174/look-to-the-stars#comments  quest in Darkshire (what i think your referring to since it's not the Rogue quest i mentioned lol ^^), but yes if your lucky and SW is out of goods it's a good secondary :)
