### ISSUE TITLE
I Got Nothin' Left! 

### ISSUE THREAD

**Issue by EyeSage** [AeroScripts/QuestieDev#1482]
## Description
This quest is not in Questie 

## Wowhead link
https://classic.wowhead.com/quest=6609/i-got-nothin-left

## Screenshots
Quest is not in Questie - should be available at level 35, I was level 36.

**Comment by BreakBB** [comment]
Since you're using the master branch please update Questie to the latest commit and check again. It is included in our DB.

**Comment by EyeSage** [comment]
I get my version from Twitch.  There is nothing for me to update.   I can't try again as I have already finished the quest.  We can assume it's in your database but doesn't show for an unknown reason.

**Comment by BreakBB** [comment]
Oh I see, then I am mistaken about that version, sorry.

I checked our data again and yes, you can pick up the quest at level 35, but it is actually a level 45 quest.
By default Questie only shows quests 7 levels above your own, so that was most likely the reason you didn't see the quest on your map. Or did you change those sliders?

**Comment by EyeSage** [comment]
Thanks for your reply.  I wonder if there is any way for you to show the quest without, messing up the entirety of Questie.  The Quest should actually show.  I was able to complete the quest without, being level 45.  In fact, my druid healer is quite weak.   Perhaps there is nothing you can do.  Perhaps Questie should show the quest based on what level it can be picked up rather than based on the level of the quest.   If you can't fix it, it will be a permanent little issue for questie.  No big deal.  I will never forget the quest myself at this point lol.

**Comment by BreakBB** [comment]
Closing this. Follow #1568 for the change you requested.
