### ISSUE TITLE
The Tower of Althalaax: Highborne soul in Satyrnaar objective missing

### ISSUE THREAD

**Issue by beornlake** [AeroScripts/QuestieDev#1483]
## Description
For the quest [The Tower of Althalaax](https://classic.wowhead.com/quest=1140/the-tower-of-althalaxx), there's a quest step where you need to free the Highborne souls in Night Run and Satyrnaar. The Satyrnaar location is missing from the map.

## Wowhead link
https://classic.wowhead.com/quest=1140/the-tower-of-althalaxx

## Questie version
5.0.1 2 e2e80b7

**Comment by BreakBB** [comment]
We've had a problem with quests which objectives are a bit strange:

For your quest the text says: "Free the Highborne soul in Night Run", but actually an object is meant. We've already fixed this and it will be included in the next release!
