### ISSUE TITLE
The Stave of Equinex, missing Monolith icon (Feralas)

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#1487]
## Description

you get a staff from the NPC, go to the Ruins of Ravenwind and find 4 Braziers to get Flames, then go to said Monolith to "charge" the staff with the items, and that Monolith (@ 39, 13) has no icon on the current build :p

## Wowhead link

Quest: https://classic.wowhead.com/quest=2879/the-stave-of-equinex

Monolith: https://classic.wowhead.com/object=144063/equinex-monolith#ends

## Screenshots

not required

## Questie version

v5.1.0

**Comment by BreakBB** [comment]
@reaper666735 Thank you very much for another great report 😄
