### ISSUE TITLE
Incorrect minimum level for quest [Retrieval for Mauren]

### ISSUE THREAD

**Issue by blaho** [AeroScripts/QuestieDev#149]
According to http://db.vanillagaming.org/?quest=1078 this quest needs level 19. The addon has it as level 17 (quest hash: 4145215277).
I can confirm that as level 17 the questgiver had a silver !

**Comment by AeroScripts** [comment]
I'll update the data for this specifically but the problem is the data differs from server to server. Available quest levels are taken from stock mangoszero, which isnt always the same as nost or kronos.


Feel free to continue to report these issues though, a fix is a fix.

**Comment by blaho** [comment]
I see. My findings (about quest giver silver ! at level 17) is from Nostalrius.

**Comment by Muehe** [comment]
Kronos has level 17:
https://vanilla-twinhead.twinstar.cz/?quest=1078
as well as WoWWiki:
http://wowwiki.wikia.com/wiki/Quest:Retrieval_for_Mauren?oldid=818689
This is likely to be correct.

**Comment by blaho** [comment]
the twinstar you linked shows 19

But also
http://www.thottbot.com/quest=1078/retrieval-for-mauren
http://www.wowdb.com/quests/1078-retrieval-for-mauren

show 17.

I agree with you, 17 looks correct.

**Comment by Muehe** [comment]
Whoops, my bad. I also checked classicdb, that had 17.
