### ISSUE TITLE
Hide Questie button on world map causes error

### ISSUE THREAD

**Issue by yarko1967** [AeroScripts/QuestieDev#1492]
## Bug description
When I open the world map and click the "Hide Questie" button, an error occurs. The only other addons loaded are BugGrabber and Bugsack.

Here is the error from BugSack:

1x [string "Questie_Toggle:OnClick"]:1: attempt to index global 'QuestieQuest' (a nil value)
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
self = Questie_Toggle {
 0 = <userdata>
 Text = Questie_ToggleText {
 }
 Right = <unnamed> {
 }
 Middle = <unnamed> {
 }
 Left = <unnamed> {
 }
}
button = "LeftButton"
down = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'QuestieQuest' (a nil value)"

## Screenshots
Nothing visual to show

## Questie version
5.1.0

**Comment by BreakBB** [comment]
@yarko1967 Thanks for this report. We've already noticed and fixes this with ff44a21af77e1ffe7f49301582e901f17baa70cd. Will be included in the next release 👍
