### ISSUE TITLE
Silver Heart wrong level?

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1495]
The quest Silver Heart is tagged as level 55 in Questie but 54 on Wowhead. What is the truth?

https://classic.wowhead.com/quest=4084/silver-heart

Version 5.1.0

**Comment by BreakBB** [comment]
Other websites list it as 54 as well. The only way to test this is to check when the quest changes its color in the default quest log (e.g. becomes green)
