### ISSUE TITLE
Get the Goblins Drunk

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1496]
In the Quests by Zone tab, the quest Get the Goblins Drunk (Thousand Needles quest) is simultaneously showing in the Available and Unobtainable lists. As I already completed it's alternative Get the Gnomes Drunk, it should only be in the Unobtainable list.

https://classic.wowhead.com/quest=1121/get-the-goblins-drunk

![WoWScrnShot_110619_135008](https://user-images.githubusercontent.com/54936174/68299803-b3d1f100-009c-11ea-94bf-cc84a4537a24.jpg)

Version 5.1.0

**Comment by BreakBB** [comment]
@Cerby3BR I think I already found the issue, but can't test this myself. Please place the file from the ZIP below in `Questie/Modules/Journey` (replace the existing one), do a `/reload` and report if this issue still exists.


[QuestieJourney.zip](https://github.com/AeroScripts/QuestieDev/files/3819839/QuestieJourney.zip)

**Comment by BreakBB** [comment]
@Cerby3BR Nevermind I was just able to test this myself on the same quests. Fixed!
