### ISSUE TITLE
Abandon Quests

### ISSUE THREAD

**Issue by Eziair** [AeroScripts/QuestieDev#1497]
I abandoned a few quests the other day but have gone back to pick them up.
Questie is not showing them now on the tracker. new quests show just fine.

I have reset Questie/reinstalled

**Comment by BreakBB** [comment]
@Eziair Please follow our issue template next time (from where did you reach the issue page?). We need at least to know which version of Questie you use.

Can you shift + click them to add them to the tracker?

**Comment by BreakBB** [comment]
Closing because of the lack of information.
