### ISSUE TITLE
Update failed to activate in classic

### ISSUE THREAD

**Issue by duskwithoutdawn** [AeroScripts/QuestieDev#1499]
## Bug description
I updated the addon on 6 Nov 2019 the addon now fails to appear in WoW Classic. Prior to the update it was working well. I undated the addon through twitch.

**Comment by BreakBB** [comment]
@duskwithoutdawn Have a look at our [FAQ](https://github.com/AeroScripts/QuestieDev/wiki/FAQ). YOu might have more than 1 version of Questie installed or didn't restarted the game.

**Comment by BreakBB** [comment]
Assuming this is fixed.
