### ISSUE TITLE
Young Crocolisk Skins not on minimap

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1501]
The quest isn't showing up on the map/minimap even though it's available.

https://classic.wowhead.com/quest=484/young-crocolisk-skins

Version 5.1.0

**Comment by Doxxer** [comment]
Faced this issue in v.5.6.0. Changing to nil (instead of empty table) value by key minRep makes this issue gone.
PR #1749

**Comment by Doxxer** [comment]
See also: #1757
