### ISSUE TITLE
certain zones have seen bugs that drop FPS rapidly.

### ISSUE THREAD

**Issue by chkmyid** [AeroScripts/QuestieDev#1503]
## Bug description

certain zones have seen bugs that drop fps rapidly.
I've experienced symptoms of my screen frame rate dropping to a single digit.
This is a very serious bug and needs to be corrected quickly.

## Questie version
v5.1.0

**Comment by BreakBB** [comment]
@chkmyid Please provide some more information on this. Have you tried to disable all other addons to make sure it is Questie? In which zones did you experience such issues and with which quests active?

**Comment by chkmyid** [comment]
The area where the issue occurred is the 'Un'Goro Crater'.
There are a total of three quests in the 'Un'Goro Crater' area present in my quest log, two of them can be performed in Un'Goro Crater the one being carried out is "[Muigin and Larion](https://classic.wowhead.com/quest=4141)" and the other was "[Volcanic Activity](https://classic.wowhead.com/quest=4502)" quest.
I reloaded the console except Questie to complete the Muigin and Larion quest.

I think it is possible that this issue originated from #1504

**Comment by mw108** [comment]
Same here. Issue exists since Questie 5.1.0. Installed Questie 5.01 and the problem is gone.

Lakeshire / Redridge Mountains. Stuttering starts as soon as I enter the zone. When I stand still, turn the camera, jumping, fighting, looting, etc. no stuttering at all. As soon as I move in any direction, FPS drops from 100 to 7-8. When I exit the zone, FPS also goes up again. When I enter the zone, FPS goes down.

One thing to note: With Questi 5.0.1 I have constantly 100 FPS. With Questie 5.1.0 I had ~50-70 FPS as soon as I started moving, even outside Redridge Mountains.

Questie 5.1.0
https://youtu.be/6Q6ic_pD04w

Questie 5.0.1
https://youtu.be/F-BTu9EoqgU

**Comment by chkmyid** [comment]
@mw108 Wow~ The youtube video is the same as what I experienced I was very tired at the time, so I couldn't capture the video.

**Comment by chkmyid** [comment]
@BreakBB 
> Have you tried to disable all other addons to make sure it is Questie?

Yes, of course I had to spend a lot of time disabling all the addons, and then enabling them one by one. With Questie at the end, it was a more arduous task. ;-)
It was night and I had to do some detection to look at the addons that caused the cause while I was very tired.

**Comment by BreakBB** [comment]
@mw108 Thanks for the videos! It looks indeed unplayable at this state. Could you try to disable all addons except Questie and see if that helps with v5.1.0?

**Comment by BreakBB** [comment]
@chkmyid @mw108 Could you try the latest state of our master branch and see if that helps? We've had a change to the FramePool which led to another issue as well.

[Questie.zip](https://github.com/AeroScripts/QuestieDev/files/3827318/Questie.zip)

**Comment by mw108** [comment]
Thanks for the fast reply. :)

I found out that the official version 5.1.0 of Questie interferes with the "**MinimapButtonBag**" addon. When I disable it, Questie 5.1.0 works fine in Redridge Mountains area. When I enable it, the FPS drops.

However, the latest version 5.1.0_511f212, which you attached, seems to solve the problem again. I have no FPS drops in Redridge Mountains area anymore, even with MinimapButtonBag enabled.

Great work!

**Comment by BreakBB** [comment]
@mw108 Yeah, we have some difficulties with MMB (still not sure if those come only from our side or if they changed something recently). Great you figured that out! 👍 Some user on Discord also reported that 5.1.0_511f212 fixed his FPS problems.

**Comment by chkmyid** [comment]
The test was conducted for about 4 hours.
Although the quest was not in the same environment as when the problem occurred, there was no FPS drop from the modified version.
