### ISSUE TITLE
QuestieComms.lua Error occurring when joining party

### ISSUE THREAD

**Issue by kwdreas** [AeroScripts/QuestieDev#1507]
## Bug description
Date: 2019-11-06 18:45:09
ID: -4
Error occured in: Global
Count: 1
Message: ...face\AddOns\Questie\Modules\Network\QuestieComms.lua line 388:
   attempt to compare number with string
Debug:
   ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:388:
      ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:373
   [C]: ?
   ...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...ace\AddOns\DBM-Core\Libs\AceComm-3.0\AceComm-3.0.lua:264:
      ...ace\AddOns\DBM-Core\Libs\AceComm-3.0\AceComm-3.0.lua:246
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AQT, v1.1.6-r3
  Atlas, vv1.45.01.11302
  AtlasBattlegrounds, vv1.45.00.11302.00
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasTransportation, vv1.45.00.11302.00
  AtlasLootClassic, vv1.3.3
  AtlasLootClassicData, vv1.3.3
  AtlasLootClassicDungeonsAndRaids, vv1.3.3
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BagnonScrap, v8.2.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  Chinchilla, vv2.10.0
  DBMCore, v1.13.18
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Dominos, v8.2.30
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FishingBuddy, v0.6 Beta 2
  GatherMate2, v1.45.5
  HandyNotes, vv1.5.9
  HandyNotesDungeonLocationsClassic, v1.03
  HandyNotesFlightMastersClassic, v1.06
  HandyNotesNPCsClassic, v1.21
  HandyNotesTravelGuideClassic, vv2.1.5b
  HandyNotesWorldMapButton, v11302.02-Classic
  Healium, v
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  Mapster, v1.8.5
  MoveToolTip, v1.0.6
  OmniCC, v8.2.5
  QuestAnnounce, v8.0.2.1
  Questie, v5.0.1 2 e2e80b7
  Scrap, v13.19
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpinxFocus, v1.0
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WideQuestLog, v
  WideQuestLogLevels, v
  ZoneDetails, v1.0.1
  ZPerl, v5.8.7
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=840)

**Comment by BreakBB** [comment]
Have a look at our [FAQ](https://github.com/AeroScripts/QuestieDev/wiki/FAQ#22-i-get-an-error-about-attemt-to-compare-numer-with-string-when-joining-a-group). This error occures when you join a group with someone using the latest version of Questie (v5.1.0) and you're still using v5.0.0 and v5.0.1.

Please update Questie and the error will go away. Questie works fine with the error though :+1:
