### ISSUE TITLE
Locations to return completed quests don't show on map

### ISSUE THREAD

**Issue by JamesDeline** [AeroScripts/QuestieDev#1508]
## Bug description
All features are working fine except it won't show me where I can turn in completed quests.

## Questie version
5.1.0

**Comment by BreakBB** [comment]
@JamesDeline Could you check the follow config checkbox to make sure it is enabled:

![image](https://user-images.githubusercontent.com/33514570/68529196-3d332e80-02fc-11ea-80a0-b8233ac062dc.png)

**Comment by JamesDeline** [comment]
worked! thank you! now I feel stupid :-)
