### ISSUE TITLE
Error after completing quest

### ISSUE THREAD

**Issue by chkmyid** [AeroScripts/QuestieDev#1513]
## Description
The following quest has been completed and an error message has been displayed:

`1x Questie\Modules\QuestieQuest.lua:382: attempt to call method 'RemoveQuest' (a nil value)
Questie\Modules\QuestieQuest.lua:382: in function `CompleteQuest'
...rfaceQuestie\Modules\QuestieEventHandler.lua:132: in function `CompleteQuest'
...rfaceQuestie\Modules\QuestieEventHandler.lua:110: in function <...rfaceQuestie\Modules\QuestieEventHandler.lua:104>
[C]: ?
...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
AQT\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <AQT\libs\AceEvent-3.0\AceEvent-3.0.lua:119>`

## Wowhead link
https://classic.wowhead.com/quest=2866

## Screenshots
None.

## Questie version
v5.1.0

**Comment by chkmyid** [comment]
The same error occurred in the following link quests:
https://classic.wowhead.com/quest=2867

**Comment by chkmyid** [comment]
If this is due to the modified module, you may close the issue after the patch.

**Comment by BreakBB** [comment]
@chkmyid Yes, there must be something wrong with the modified files you already grabbed from other issues. Sorry about that. Here is a "full release" of the current master:

[Questie.zip](https://github.com/AeroScripts/QuestieDev/files/3827335/Questie.zip)
