### ISSUE TITLE
Quest #7489 - Lethtendris's Web

### ISSUE THREAD

**Issue by wow-classic** [AeroScripts/QuestieDev#1514]
## Description
This quest is not shown on the map. (In the Russian version WoW)

## Wowhead link
https://classic.wowhead.com/quest=7489

## Screenshots
![Questie -  3](https://user-images.githubusercontent.com/55049724/68534316-2ca6a680-0344-11ea-9b82-cd7bcf7fbc64.png)

## Questie version
Version: 5.1.0

**Comment by BreakBB** [comment]
@wow-classic Thanks for the report. Could you run the following command and report the output:

`/dump IsQuestFlaggedCompleted(7492)`

**Comment by wow-classic** [comment]
> /dump IsQuestFlaggedCompleted(7492)

![Questie - 4](https://user-images.githubusercontent.com/55049724/68542717-abd9c000-03c0-11ea-93db-41bd965648bf.png)
