### ISSUE TITLE
Ancient Spirit

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1516]
## Description
Questie shows three start points in Irontree wood. Those are the same as for another quest, where you need something from those little green water ponts.
The actual quest doesn't start there but at (49.7,30.7), look at the 2nd and 3rd screenshots
That is where you need to use the flute, you got for starting this quest.

## Wowhead link
https://classic.wowhead.com/quest=4261/ancient-spirit

## Screenshots
![](https://i.imgur.com/S3L2oDp.jpg)
![](https://i.imgur.com/T9c0ZOl.jpg)
![](https://i.imgur.com/3URIebc.jpg)

## Questie version
5.1.0

**Comment by BreakBB** [comment]
From [this comment](https://classic.wowhead.com/quest=4261/ancient-spirit#comments:id=3159944) on Wowhead I could read that our markers seem totally fine.
You can use the flute on every of those 3 statues to summon the starting NPC [Arei](https://classic.wowhead.com/npc=9598/arei).

**Comment by Djfe** [comment]
which 3 statues there is only one? ^^

> 
> Confirmed, works in classic.
> 
>     Complete prequest Purified! to get Flute of the Ancients
>     KEEP  Flute of the Ancients
>     Go to 49,31 and stand in front of the statue
>     Use the Flute of the Ancients multiple times (had to use it 5x until Arei appeared for me)
>     Turn around, Arei a giant spirit ancient will be standing in front of you.
>     If Arei doesn't spawn, he could be sitting at 50,15 from the last escort. Wait for spirits to despawn and try to use the flute again
>     Start his escort quest Ancient Spirit
>     Follow him while he fights everything in the path. He's quite strong. He only travels as far as the path (which takes 3 minutes)
> 
> You can also choose to NOT complete this quest. This way you get to keep Flute of the Ancients and start the escort quest over and over again. Everytime you start the escort, there are 3 additional toxic horror spawns for water essence farming.

that's the comment, you linked

50,15 is just the spot, where he stands after the quest, but I think you can only start the quest at 49,31
you have to wait for him to despawn there first

at none of the three spots is a statue/ruin

the lowest spot of questie is close to 49,26 (first screenshot) and not 49,31

**Comment by Djfe** [comment]
are these the 3 coords?
if so: there are no statues, that's only where enemies are spawned in (event) during the escort quest

> Requires Flute of the Ancients from quest Purified!.
> 
> Use flute at 50,31 near the statue in the ruins.
> 
> If Arei doesn't spawn, he could be sitting at 50,15 from the last escort. Wait for spirits to despawn and try to use the flute again.
> 
> Arei spawns at 50,30 and walks around the Iron Tree woods until reaching the road.
> 
> At 50,26 3 Toxic Horror's spawn.
> 
> At 50,15 3 Iron Tree Stompers spawn.
> 
> Overall, pretty easy. He can solo an Irontree Stomper on his own so easy to kill 2 then the third.

**Comment by BreakBB** [comment]
@Djfe Thank you very much for updating this and explaining it in more detail. I haven't done every quest so I heavily rely on Wowhead and detailed reports like yours 👍
