### ISSUE TITLE
when i select show quest level on Tracker, my tracker always as [60?]questName,it should be [60D]questName    Language zhcn

### ISSUE THREAD

**Issue by suyunxiu** [AeroScripts/QuestieDev#1522]
![image](https://user-images.githubusercontent.com/35566441/68565898-d6467e80-048f-11ea-8a00-2dad3bd9bce8.png)

**Comment by BreakBB** [comment]
@suyunxiu Please follow our issue template next time! Which version of Questie do you use?

**Comment by suyunxiu** [comment]
thank you for your reply , v5.2.0

**Comment by BreakBB** [comment]
Merging with #1358
