### ISSUE TITLE
Quest #6069 - The Hunter's Path

### ISSUE THREAD

**Issue by wow-classic** [AeroScripts/QuestieDev#1523]
## Description
I am Troll Hunter 10 lvl. The addon incorrectly shows the NPS who are starting the quest.
Screen 1 - this NPC really gives the quest. But in the addon there is no mark on the map "!".
Screen 2 - The addon has a mark on the map, but the NPC does not give the quest.
(In the Russian version WoW)

## Wowhead link
https://classic.wowhead.com/quest=6069/the-hunters-path

## Screenshots
![Questie - 5](https://user-images.githubusercontent.com/55049724/68607402-97c9b780-04c1-11ea-92de-8bbaf7aa986b.png)

![Questie - 6](https://user-images.githubusercontent.com/55049724/68607425-a4e6a680-04c1-11ea-885b-049e518913fc.png)

## Questie version
Version: 5.1.0

**Comment by BreakBB** [comment]
@wow-classic Thanks for the report! Yes, the level 10 hunter quests are really not correct in our data, but very hard to test.
