### ISSUE TITLE
Quest objective text does not break when you SHIFT + hover over a ! in minimap

### ISSUE THREAD

**Issue by Arkanius84** [AeroScripts/QuestieDev#1525]
## Bug description
When you open the Map and hover with SHIT over a quest that has a very long objective text the text will not break.

## Screenshots
![WoWScrnShot_111119_184644](https://user-images.githubusercontent.com/57637189/68609229-094f3900-04b5-11ea-8a81-fb39cfe9374f.jpg)

## Questie version
Questie-v5.2.0.zip

**Comment by BreakBB** [comment]
Duplicate of #1093 Ther is a bigger change required for this to be fixed.
