### ISSUE TITLE
Update on manual complete

### ISSUE THREAD

**Issue by WolfGaming** [AeroScripts/QuestieDev#153]
When I use the /questie complete <questname> command it doesnt update the minimap until I relog.

**Comment by AriinPHD** [comment]
@WolfGaming It doesn't update automatically. no, but you don't have to relog for the update to occur. Do this: Open your world-map, zoom out with right-click. If you close the world-map now everything should be updated.

**Comment by Logonz** [comment]
This is fixed in questie 3.0 (Believe me 3.0 is muuuuch better so hold out!)
