### ISSUE TITLE
Beware of Pterrordax incorrectly listed as available at level 49

### ISSUE THREAD

**Issue by kernighan** [AeroScripts/QuestieDev#1530]
## Bug description

The quest "Beware of Pterrordax" shows up in Un'Goro crater as being available to pick up when you hit level 49.  However it is at least level 50, as the NPC who gives the quest has a grey exclamation point rather than a yellow one.

**Comment by BreakBB** [comment]
@kernighan Could you please report back when you reached the level to accept this quest? It is listed to be available at level 49 [on Wowhead](https://classic.wowhead.com/quest=4501/beware-of-pterrordax) as well.

Please check if you can accept it on level 50! And it would be great if you could include a screenshot as well 👍

**Comment by kernighan** [comment]
Will do!

**Comment by kernighan** [comment]
I'm incorrect, you can get the quest, it's from the sign /next/ to spraggle rock, who also has a greyed out quest on his head.  Sorry for the noise. :)
