### ISSUE TITLE
Feature Request: Quest progress in group chat

### ISSUE THREAD

**Issue by idl0r** [AeroScripts/QuestieDev#1531]
Hi,

it would be handy to have a feature to show the quest progress in /s, /p or even raid (not sure if really useful but adding support for raid chat should be fairly easy when /s and /p is already supported).
Something like:
1/5 someitem
or
someitem 1/5

Like you need some claws and you want others who help to see that progress without having to hover over the mobs or something:
claw 1/5
...

There should be a toggle option for on/of and an option for /s, /p and /ra. It should default to /p. For /p and /ra there should be a check, to verify the user is in either a group or a raid.

There should be also a completed message like
Example quest completed

**Comment by BreakBB** [comment]
Related to #1228

**Comment by AeroScripts** [comment]
Closing this but feel free to discuss in #1228
