### ISSUE TITLE
 bug report

### ISSUE THREAD

**Issue by hahlinban** [AeroScripts/QuestieDev#1532]
## Bug description
Date: 2019-11-12 18:01:09
ID: 1
Error occured in: Global
Count: 1
Message: ...face\AddOns\Questie\Modules\Network\QuestieComms.lua line 388:
   attempt to compare number with string
Debug:
   ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:388:
      ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:373
   [C]: ?
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:29:
      ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:25
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:64: Fire()
   ...face\AddOns\Questie\Libs\AceComm-3.0\AceComm-3.0.lua:218: OnReceiveMultipartLast()
   ...face\AddOns\Questie\Libs\AceComm-3.0\AceComm-3.0.lua:256:
      ...face\AddOns\Questie\Libs\AceComm-3.0\AceComm-3.0.lua:246
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  CharacterStatsClassic, v2.5
  ClassicCastbars, vv1.0.7
  ClassicCastbarsOptions, v
  ColoredInventoryItems, v1.4
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  Informant, v8.2.6374 (SwimmingSeadragon)
  OmniCC, v8.2.4
  Questie, v5.0.1 2 e2e80b7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  VendorPrice, v1.2.6
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=35c)

**Comment by drejjmit** [comment]
This is fixed in 5.1.0+
Please update to latest version (currently 5.2.1)
