### ISSUE TITLE
Warrior Quests "Brutal ***" Reappear

### ISSUE THREAD

**Issue by RogueZair** [AeroScripts/QuestieDev#1533]
## Bug description
The Warrior Quests "Brutal Armor", "Brutal Leggards", "Brutal Gauntlets", and "Brutal Helm" reappear on the map just after completion. /reload clears the error. 

## Screenshots

![Brutal Error 2](https://user-images.githubusercontent.com/36722410/68739767-77bbf600-059e-11ea-83b4-76133fb5e7aa.jpg)

## Questie version
v5.2.1

**Comment by BreakBB** [comment]
Related to #860 Sorry for the trouble. Future releases will fix this!
