### ISSUE TITLE
Desolace - Befouled by Satyr from Takata Steelblade

### ISSUE THREAD

**Issue by RogueZair** [AeroScripts/QuestieDev#1536]
## Description
Desolace - The quest "Befouled by Satyr" from Takata Steelblade is appearing on the map and minimap (from Questie), but is not available in game. 

## Wowhead link
https://classic.wowhead.com/quest=1434/befouled-by-satyr 

## Screenshots
![WoWScrnShot_111319_052850](https://user-images.githubusercontent.com/36722410/68768435-57f4f400-05d7-11ea-952c-90487ae380f2.jpg)
![WoWScrnShot_111319_052914](https://user-images.githubusercontent.com/36722410/68768439-59beb780-05d7-11ea-9534-4719026e7665.jpg)

## Questie version
v5.2.1

**Comment by drejjmit** [comment]
This quest requires https://classic.wowhead.com/quest=1432/alliance-relations according to wowhead comments
