### ISSUE TITLE
Key override for auto accept/turnin quests

### ISSUE THREAD

**Issue by pqee** [AeroScripts/QuestieDev#1537]
Can you add an option to have an override key for the auto accept/turn in quests?  (ctrl, alt, shift, etc...)

This would let us override the auto part for quests where we want/need to read the text, or npcs that are vendors as well as quest givers, where the auto quest prevents you from using them as a vendor etc...

**Comment by Gogo1951** [comment]
@BreakBB Can we bump this up? It's a real pain to turn in AD rep quests right now. I have to disable Questie all together. It gets stuck on the first item, and if I don't have any of the minion stones it stalls me out on that quest turn in screen. It won't go to the next items.

There needs to be a check on the turn in screen, if you don't have the item, go back and try a different quest. I forget what addon I used back in the day, but it was seamless here. You just talk to the guy and it would turn in all your stuff smoothly.

**Comment by Gogo1951** [comment]
I think I used https://github.com/lure/AutoTurnIn back in the day.
