### ISSUE TITLE
The Binding

### ISSUE THREAD

**Issue by thebohster** [AeroScripts/QuestieDev#1542]
## Description

I attempted to do both "The Binding" quests for Voidwalker simultaneously. I ended up having to drop one (Orgrimmar) to do the one in Undercity. Now the marker in Orgrimmar stays up even though I completed the Undercity one. I assume the same applies the other way around if I abandoned the Undercity on and completed the Orgrimmar one.

## Wowhead link

https://classic.wowhead.com/quest=1504/the-binding

## Questie version

v5.2.1

**Comment by BreakBB** [comment]
@thebohster Thanks for the report. This should be easy  to fix :+1:
