### ISSUE TITLE
Hide Quest Tracker In Combat

### ISSUE THREAD

**Issue by perdere** [AeroScripts/QuestieDev#1545]
## Description

It would be nice to have an option where the Quest Tracker can hide away when in combat. If you're tracking a number of quests the screen real estate can get up there, which is fine for running about, but in-combat having a less busy screen is often ideal :)

Having the quest tracker be collapsible is a good alternative too. Having a manual collapse option AND an in-combat toggle to automatically collapse it would be good there.

**Comment by Malevola** [comment]
Or just have the option to shutter the tracker whenever you want? Please?

**Comment by SpockAce** [comment]
Any News on this Feature request?
