### ISSUE TITLE
Option to show Un'goro Soil

### ISSUE THREAD

**Issue by Draftinger** [AeroScripts/QuestieDev#1554]
## Provide a slash command (i.e. "/quesite soil") to show the item locations of Un'goro soil mounds outside of having the associated quests.
Add a slash command to manually show the soil spawn locations. I implemented a janky half-understanding version of this with the following put into "Questie:QuestieSlash()":

    -- /questie soil
    if input == "soil" then
        QuestieQuest:ForceToMap("item", 11018, "Un'Goro Soil")
        return;
    end

I understand that this is outside the normal scope of Quesite but would be a fairly simple implementation and extremely useful.

**Comment by BreakBB** [comment]
You can use the search function of the Journey (right click on the Minimap icon) to mark manual NPCs/objects on the map :+1:

**Comment by BreakBB** [comment]
@Draftinger Just for others might seeing this: You use the "Advanced Search", enter "Un'Goro Dirt Pile" and then press "Show on Map" to add all the spawns to the map.

![image](https://user-images.githubusercontent.com/33514570/69267892-5b3b4180-0bce-11ea-9c97-aadce5901c4a.png)

**Comment by Draftinger** [comment]
Hi BreakBB,

Thanks for the secondary reply.  I was attempting to use the search functionality but my mistake was searching for the term "Un'Goro Soil" which showed the quest and item but not the object "Un'Goro Dirt Pile" which is what I needed to be looking for.  Thankyou for clarifying!

**Comment by BreakBB** [comment]
@Draftinger Yeah, maybe we should make it possible to search for an item and "show sources" on the map.
