### ISSUE TITLE
Add Option to hide Objective Icons on Minimap

### ISSUE THREAD

**Issue by Holmelund** [AeroScripts/QuestieDev#1556]
## Description
As it is now you can only either show objective icons for both map nad minimap, or none. I feel like they clutter the minimap, but like having them on the world map.

**Comment by Gogo1951** [comment]
Hey @Holmelund ,

Would this suffice?

https://github.com/AeroScripts/QuestieDev/issues/799#issuecomment-564583093

Can we close this issue as a duplicate?

**Comment by Holmelund** [comment]
Yes, that would be perfect.
