### ISSUE TITLE
A Call to Arms: The Plaguelands!

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#1560]
## Description
These are exclusive to each other. You can only complete one.

## Wowhead link
https://classic.wowhead.com/search?q=+A+Call+to+Arms%3A+The+Plaguelands

## Questie version
v5.2.1

**Comment by BreakBB** [comment]
These quests are already correctly marked as exclusive to each other. And `IsDoable` correctly checks the field for it.

There might be some other problem 🤔

**Comment by BreakBB** [comment]
I can't reproduce this on the latest master commit. It might already been fixed. Please check again.

**Comment by drejjmit** [comment]
only teposting the report from curse. You can close the issue.

**Comment by BreakBB** [comment]
I see, thanks for checking Curseforge as well 👍
