### ISSUE TITLE
Tracker autohides on instance entering (v3.7.1)

### ISSUE THREAD

**Issue by Mige5** [AeroScripts/QuestieDev#1561]
Hey

Noticed that the quest tracker autohides when I enter dungeon. cant find a setting to disable that. (using questie 3.7.1 and wow client 1.12.1.. i think thats the latest version of questie for that client?)

Working fine if I revert to questie v3.3. (havent tried if theres some newer version that it would still work fine)

**Comment by BreakBB** [comment]
@Mige5 Sorry to tell you, but with the release of Classic we don't support WoW 1.12 anymore :/
