### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by witchpiggie** [AeroScripts/QuestieDev#1562]
## Bug description
Swapping between characters, this pops up when I load in. This started right after updating Questie.

## Error Text
Date: 2019-11-19 09:38:01
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Questie.lua line 150:
   attempt to call method 'SetIcons' (a nil value)
Debug:
   (tail call): ?
   Questie\Questie.lua:150:
      Questie\Questie.lua:148
   [C]: ?
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:613:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.3.4
  AtlasLootClassicData, vv1.3.4
  AtlasLootClassicDungeonsAndRaids, vv1.3.4
  ATTClassic, v0.1.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  Bartender4, v4.8.8
  BetterVendorPrice, vv1.10.00
  CEPGP, v
  DBMCore, v1.13.18
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  GatherLite, v1.3.3-classic
  InFlightLoad, v1.13.003
  ItemRack, v
  LeatrixMaps, v1.13.36
  LeatrixPlus, v1.13.37
  MarkMe, v0.9.7
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  MonkeySpeed, vv3.4.0
  OmniCC, v8.2.5
  Plater, v
  Questie, v5.2.1
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=52d)

## Questie version
5.2.2

**Comment by drejjmit** [comment]
Did you restart the client? Still says Questie, v5.2.1 on your addon list.

**Comment by BreakBB** [comment]
@witchpiggie You restarted the Wowclient, yes?

**Comment by Gogo1951** [comment]
Getting a similar issue, and it's preventing me from clicking on loot rewards when I finish a quest. 

I'm on the Alpha version of Questie.

**Comment by BreakBB** [comment]
@Gogo1951 This doesn't look like a Questie issue. Could you disable all other addons and try again?

**Comment by Gogo1951** [comment]
Will do, but this issue for me started happening with the latest Questie alpha, and when I disable Questie the issue goes away.

I’ll see what else I can find.

Thanks for making this awesome add on!

**Comment by BreakBB** [comment]
@Gogo1951 It could be a conflict with another addon then. Or maybe it really is just another addon.

**Comment by BreakBB** [comment]
Assuming this is fixed.
