### ISSUE TITLE
Please add 2 Booty Bay Quests

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1564]
## Description

https://classic.wowhead.com/quest=594/message-in-a-bottle - starts from green bottles on the East Coast outside of Booty Bay.

https://classic.wowhead.com/quest=8552/the-monogrammed-sash - starts from sash dropped by Mokrash (https://classic.wowhead.com/npc=1493/mokrash) off the docks in Booty Bay.

**Comment by BreakBB** [comment]
@Gogo1951 Thanks for the report! For "Message in a bottle" we can't yet add it, since the hole beach would be flooded with icons. See #317 

The other one might be possible. I will investigate!

**Comment by Gogo1951** [comment]
I know this is closed, but also:

https://classic.wowhead.com/item=4056/cortellos-riddle

**Comment by BreakBB** [comment]
@Gogo1951 Cortello's Riddle has already been added to the map 👍
