### ISSUE TITLE
Icon Clutter Reduction

### ISSUE THREAD

**Issue by Crumdidlyumshis** [AeroScripts/QuestieDev#1565]
## Description

Would be great to simulate the experience that QuestHelper brought by making a item or mob icon just 1, but with a x/y coodinate overlay that appears when mousing over icons.

Take a look at this comment made in a previous issue I made: https://github.com/AeroScripts/QuestieDev/issues/1559#issuecomment-555681976

The video will explain it. Cheers!

**Comment by Gogo1951** [comment]
Will be handled as part of #2500
