### ISSUE TITLE
Stoley's Shipment

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1566]
## Description
Stoley's Shipment is missing (no marker on the map)
(67.1,24.0)

## Wowhead link
https://classic.wowhead.com/quest=2873/stoleys-shipment

## Screenshots
![](https://i.imgur.com/A601yVl.jpg)

## Questie version
5.2.1

**Comment by BreakBB** [comment]
@Djfe Could you check if the pre quest is required by running:

`/dump IsQuestFlaggedCompleted(2872)`

**Comment by Djfe** [comment]
does that still work after I completed stoley's shipment?

**Comment by Djfe** [comment]
I think Stoley's Debt is just a bread crumb quest, but I will still execute the command in a few minutes

**Comment by BreakBB** [comment]
@Djfe Yeah that command is to check if you completed the "bread crumb" quest. So if you didn't complete 2872, but 2873 that means we have to mark it correctly.

**Comment by Djfe** [comment]
![](https://i.imgur.com/g89sNrZ.png)
I didn't complete it

**Comment by BreakBB** [comment]
@Djfe Perfect, thank you very much. Will fix it now so it's in the next release.
