### ISSUE TITLE
Show quests based on pickup level rather than quest level

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#1568]
## Description

Currently Questie shows quests based on the level the quest is listed for instead of using the level at which you can pick it up.

I think this should be changed to remove some confusion while leveling, but it will also require to rethink the max level slider for shown quests.

**Comment by Gogo1951** [comment]
2 examples that will cause a bit of clutter for lowbies... but we should be able to negate those by changing settings in DB to match level to enter dungeon.

https://classic.wowhead.com/item=13250/head-of-balnazzar - Level 48

https://classic.wowhead.com/item=12780/general-drakkisaths-command - Level 55
