### ISSUE TITLE
missing Questmob to Quest ID 4513

### ISSUE THREAD

**Issue by Ischtaratu** [AeroScripts/QuestieDev#1570]
## Bug description
missing Questmob to Quest ID 4513

The Quest needs 2 different Mobs;
Cursed Ooze ID 7086
Tainted Ooze ID 7092

But Questie marks the Cursed Ooze for both objektives ... 

## Questie version
v5.2.2

**Comment by BreakBB** [comment]
@Ischtaratu Quest with ID 4513 is the quest for Un'Goro: https://classic.wowhead.com/quest=4513/a-little-slime-goes-a-long-way

The Cursed and Tainted Ooze are both for the quest in Felwood. I guess you confused some number?

**Comment by BreakBB** [comment]
Could you also share a screenshot for this?

Because this is our data on the required items:

```lua
        [11947] = { -- #1315
            [QuestieDB.itemKeys.name] = "Filled Cursed Ooze Jar",
            [QuestieDB.itemKeys.relatedQuests] = {4512},
            [QuestieDB.itemKeys.npcDrops] = {7086},
            [QuestieDB.itemKeys.objectDrops] = {},
        },
        [11949] = { -- #1315
            [QuestieDB.itemKeys.name] = "Filled Tainted Ooze Jar",
            [QuestieDB.itemKeys.relatedQuests] = {4512},
            [QuestieDB.itemKeys.npcDrops] = {7092},
            [QuestieDB.itemKeys.objectDrops] = {},
        },
```

**Comment by Ischtaratu** [comment]
At First: 
Quest: 4512 ... you are right ... my misstake ... not 4513

Second:
no Screen, because i had finished the quest, but i'm sure the cursed Ooze had both tags and the Tainted Ooze none. But if you say, the data are right, than must be ... something else.

**Comment by BreakBB** [comment]
@Ischtaratu Yeah must be something else then...

Are you on an English client?

**Comment by BreakBB** [comment]
@Ischtaratu Are you on an English client?

**Comment by BreakBB** [comment]
Closing because of the lack of response.
