### ISSUE TITLE
Nathanos Blightcaller quests

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1572]
In the Eastern Plaguelands, Nathanos Blightcaller has a few quests that are tagged as available on the map but aren't yet ingame, specifically The Corpulent One and The Call to Command. Will come back with further details as to how these all intertwine.

https://classic.wowhead.com/quest=6136/the-corpulent-one
https://classic.wowhead.com/quest=6144/the-call-to-command

![WoWScrnShot_112019_165114](https://user-images.githubusercontent.com/54936174/69254323-64201900-0bb6-11ea-81d4-6007445a180a.jpg)

Version 5.2.2

**Comment by BreakBB** [comment]
@Cerby3BR Thanks for the report. There is a pre quest to those two quests as stated in [this comment](https://classic.wowhead.com/quest=6144/the-call-to-command#comments:id=3158426).

Gonna be fixed in the next release!

**Comment by Cerby3BR** [comment]
Ok, can confirm the questline goes like the comment says, with The Call to Command requiring both The Corpulent One and Duskwing, Oh How I Hate Thee...
