### ISSUE TITLE
Show Mobs that Always Drop Quest Items as Quest Givers on Map

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1573]
## Description

Some items that start quests drop off of random mobs, like the distress beacons. No point in trying to track those, would just add clutter. Example:

https://classic.wowhead.com/item=8705/oox-22-fe-distress-beacon

Other quest starting items always drop off a specific mob. If I gave you a list of all the mobs, and their general coordinates (like you do for other quest givers that pat), would it be possible to add these mobs to the map? Maybe a different icon of some sort, like a Golden Sword, for "Kill to Start Quest" kind of thing? Will let you work out UX.

Few mobs for example...

https://classic.wowhead.com/npc=5833/margol-the-rager 

https://classic.wowhead.com/npc=3204/gazzuz

https://classic.wowhead.com/npc=3253/silithid-harvester

https://classic.wowhead.com/npc=10617/galak-messenger

https://classic.wowhead.com/npc=5477/noboru-the-cudgel

https://classic.wowhead.com/npc=3472/washte-pawne

https://classic.wowhead.com/npc=3474/lakotamani

Let me know what data you'd need, and the format, and I'll work to generate the full list.

**Comment by BreakBB** [comment]
@Gogo1951 Sorry for the late response on this. We're all pretty busy atm.

Thanks for this request. It really is a good idea to add such mobs as starting NPC for quests, if they drop it by 100%.

If you wanna submit a PR for it let me know. The format for corrections in the `QuestieQuestFixes.lua` is:

```lua
[<questID>] = {
    [QuestieDB.questKeys.startedBy] = {{<npcID>},ni,{<itemID>}},
},
```

It should be straight forward if you have a look in the corrections file.

**Comment by Gogo1951** [comment]
Hey @BreakBB ,

You're doing good work, and the game is a lot more fun because of this addon.

Easier for me to create a PR, or just paste here?

```

[6564] = {
    [QuestieDB.questKeys.startedBy] = {{4802},ni,{16790}},
},

[1392] = {
    [QuestieDB.questKeys.startedBy] = {{5477},ni,{6196}},
},

[23] = {
    [QuestieDB.questKeys.startedBy] = {{12678},ni,{16303}},
},

[24] = {
    [QuestieDB.questKeys.startedBy] = {{12677},ni,{16304}},
},

[3513] = {
    [QuestieDB.questKeys.startedBy] = {{5797},ni,{10621}},
},

[7761] = {
    [QuestieDB.questKeys.startedBy] = {{9046},ni,{18987}},
},

[3181] = {
    [QuestieDB.questKeys.startedBy] = {{5833},ni,{10000}},
},

[2] = {
    [QuestieDB.questKeys.startedBy] = {{12676},ni,{16305}},
},

[1918] = {
    [QuestieDB.questKeys.startedBy] = {{12759},ni,{16408}},
},

[883] = {
    [QuestieDB.questKeys.startedBy] = {{3474},ni,{5099}},
},

[522] = {
    [QuestieDB.questKeys.startedBy] = {{2434},ni,{3668}},
},

[885] = {
    [QuestieDB.questKeys.startedBy] = {{3472},ni,{5103}},
},

[5123] = {
    [QuestieDB.questKeys.startedBy] = {{10738},ni,{12842}},
},

[897] = {
    [QuestieDB.questKeys.startedBy] = {{3253},ni,{5138}},
},

[884] = {
    [QuestieDB.questKeys.startedBy] = {{3473},ni,{5102}},
},

[770] = {
    [QuestieDB.questKeys.startedBy] = {{3056},ni,{4854}},
},

[939] = {
    [QuestieDB.questKeys.startedBy] = {{10648},ni,{11668}},
},

[4881] = {
    [QuestieDB.questKeys.startedBy] = {{10617},ni,{12564}},
},

```

**Comment by Gogo1951** [comment]
I'm going to add a few more... I see there's an option for multiple quest starters...

There are items like this https://classic.wowhead.com/item=3317/a-talking-head that can drop from up to 5 mob types... ugh, I think that adds a lot of clutter.

And there are items like this that drop from a unique and there are items like this that can drop from a named, or another mob... I think those are OK, but probably just list the named as the source. https://classic.wowhead.com/item=5179/moss-twined-heart What's the convention here?

**Comment by BreakBB** [comment]
We don't want to clutter the map too much, so it would be best to add them one by one and see if it will be too much.

For me it would be easier if you could create a PR even though that might delay a release of the changes. A PR would allow us to work on other things while you focus on such changes.

If you want to add multiple starting NPCs/Objects simply add them separated by a comma, like:

```[1423] = {
	[QuestieDB.questKeys.startedBy] = {nil,{28604,12343,5892,12},{6172,},},
},```

**Comment by Gogo1951** [comment]
Agreed, I will hold off on adding items that drop from multiple mobs. Odds are people won't miss them if they do other quests anyway. 

It would be nice to have a ! on the item once it hits my bag though https://github.com/AeroScripts/QuestieDev/issues/1613 (=

PR created, you can close this issue once merged. Thanks!

https://github.com/Gogo1951/QuestieDev/commit/1a68406ffdeef74cecfdd9c84e582c7e19c1d166

**Comment by Gogo1951** [comment]
Oh... but let me know if you need good mob locations, some of these tend to wander a bit. (=

**Comment by Gogo1951** [comment]
We can close this, there will always be more quests to add... but the bulk of them are in.
