### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by iron217** [AeroScripts/QuestieDev#1575]
## Bug description
errors come out
 
1

4x ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:557: attempt to index field 'data' (a nil value)
...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:557: in function <...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:527>

Locals:
self = QuestieFrame417 {
 0 = <userdata>
 glow = QuestieFrame417Glow {
 }
 BaseOnUpdate = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:188
 FakeUnhide = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:350
 FakeHide = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:334
 texture = <unnamed> {
 }
 FadeLogic = <function> defined @Questie\Modules\Map\QuestieMap.lua:481
 BaseOnShow = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:194
 glowLogicTimer = <table> {
 }
 BaseOnHide = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:218
 FadeOut = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:306
 UpdateTexture = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:222
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:257
 GlowUpdate = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:170
 FadeIn = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:320
 frameId = 417
}
r = 0.999998
g = 0.999998
b = 0.999998
a = 0.999998
Tooltip = GameTooltip {
 0 = <userdata>
 alink = "|cffffffff|Hitem:2589::::::::7:::::::|h[Льняной материал]|h|r"
 SetHyperlink = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 _owner = QuestieFrame417 {
 }
 Hide = <function> defined =[C]:-1
 questOrder = <table> {
 }
 SetCraftItem = <function> defined =[C]:-1
 comparing = false
 TopOverlay = <unnamed> {
 }
 npcOrder = <table> {
 }
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 4
 canAddRestStateLine = 1
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 hasMoney = 1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetCraftSpell = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 miniMapIcon = true
 updateTooltip = 0.065000
 SetInventoryItem = <function> defined =[C]:-1
 manualOrder = <table> {
 }
 __tamedCounts = false
 SetLootRollItem = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetAction = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetAuctionItem = <function> defined =[C]:-1
}
maxDistCluster = 1
mid = 1420
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'data' (a nil value)"
_QuestieFramePool = <table> {
 1 = "Questie"
 2 = <table> {
 }
 unusedFrames = <table> {
 }
 lastTooltipShowHack = 4810.847000
 GetEventObjectiveTooltip = <function> defined @Questie\Modules\FramePool\QuestieFramePool.lua:428
 Questie_Click = <function> defined @Questie\Modules\FramePool\QuestieFramePool.lua:744
 Questie_Tooltip = <function> defined @Questie\Modules\FramePool\QuestieFramePool.lua:527
 GetObjectiveTooltip = <function> defined @Questie\Modules\FramePool\QuestieFramePool.lua:439
 GetAvailableOrCompleteTooltip = <function> defined @Questie\Modules\FrameP

2
4x ...ceQuestie\Modules\FramePool\QuestieFrame.lua:127: attempt to index field 'data' (a nil value)
...ceQuestie\Modules\FramePool\QuestieFrame.lua:127: in function <...ceQuestie\Modules\FramePool\QuestieFrame.lua:116>

Locals:
self = QuestieFrame417 {
 0 = <userdata>
 glow = QuestieFrame417Glow {
 }
 BaseOnUpdate = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:188
 FakeUnhide = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:350
 FakeHide = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:334
 texture = <unnamed> {
 }
 FadeLogic = <function> defined @Questie\Modules\Map\QuestieMap.lua:481
 BaseOnShow = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:194
 glowLogicTimer = <table> {
 }
 BaseOnHide = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:218
 FadeOut = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:306
 UpdateTexture = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:222
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:257
 GlowUpdate = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:170
 FadeIn = <function> defined @Questie\Modules\FramePool\QuestieFrame.lua:320
 frameId = 417
}
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined @Pawn\Pawn.lua:268
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 alink = "|cffffffff|Hitem:2589::::::::7:::::::|h[Льняной материал]|h|r"
 SetHyperlink = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 _owner = QuestieFrame417 {
 }
 Hide = <function> defined =[C]:-1
 questOrder = <table> {
 }
 SetCraftItem = <function> defined =[C]:-1
 comparing = false
 TopOverlay = <unnamed> {
 }
 npcOrder = <table> {
 }
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 4
 canAddRestStateLine = 1
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 hasMoney = 1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetCraftSpell = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 miniMapIcon = true
 updateTooltip = 0.065000
 SetInventoryItem = <function> defined =[C]:-1
 manualOrder = <table> {
 }
 __tamedCounts = false
 SetLootRollItem = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetAction = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'data' (a nil value)"

## Questie version
5.2.3

**Comment by iron217** [comment]
enable icon limit solved a problem, there were many icons on the map

**Comment by BreakBB** [comment]
Merging this with #1584
