### ISSUE TITLE
Minimap icons do not load if quest tracker and map icons are disabled.

### ISSUE THREAD

**Issue by pamposzek** [AeroScripts/QuestieDev#1576]
## Bug description
If Questie quest tracker is disabled, minimap icons do not load upon reload when map icons are disabled as well (re-enabling minimap icons fixes that). While having either map icons or quest tracker enabled, reload correctly loads minimap icons.

## Questie version
5.2.3

**Comment by Gogo1951** [comment]
Hey @pamposzek ,

Would this change help?

https://github.com/AeroScripts/QuestieDev/issues/317#issuecomment-564613358

If so, can we close this issue as a duplicate? Thanks!

**Comment by pamposzek** [comment]
I don't know if it would help, but feel free to close as duplicate. As workaround you can have quest tracker enabled but disable automatic quest tracking or something.

**Comment by AeroScripts** [comment]
v6.0.5
