### ISSUE TITLE
Quest Tracker Stuck to Mouse

### ISSUE THREAD

**Issue by seitzcasey** [AeroScripts/QuestieDev#1578]
## Bug description
Quest tracker gets stuck to mouse cursor.

1. Hold Left Click on quest tracker.
2. Hold Right Click on quest tracker.
3. Move quest tracker
4. Wait a few seconds.
5. Release Left Click.
6. Release Right Click.
7. Quest tracker is stuck to mouse cursor.

## Questie version
5.2.3

**Comment by BreakBB** [comment]
@seitzcasey Sorry for not coming back to this earlier. Is this still an issue? I just tried and can't reproduce it. Though the moving isn't quite smooth.

**Comment by Dirtsleeper** [comment]
Yes it is still an issue. You can also not click through the tracker while it is minimized.

**Comment by drejjmit** [comment]
@Dirtsleeper "click through the tracker while it is minimized." is fixed with 118bc4706602ce312c609bf64cf2730ce9e86a6e and will be included in next release.
