### ISSUE TITLE
Quest timer is shown twice

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1579]
## Bug description
quests with timers:
it shows the timer twice, the second one is the same time but only updates on /reload or when you travel by teleport/ship/etc.

this happened to me during
The Newest Member of the Family
https://classic.wowhead.com/quest=3843/the-newest-member-of-the-family

## Screenshots
![](https://i.imgur.com/EL8Gqge.jpg)

## Questie version
5.2.2

**Comment by BreakBB** [comment]
Fixes with 4b9aa6d6bd80b8f7f13912983f24683af1bd90f5
