### ISSUE TITLE
Elmore's Task

### ISSUE THREAD

**Issue by iron217** [AeroScripts/QuestieDev#1580]
## Description
no ending for quest (Grimand Elmore)

## Wowhead link
https://classic.wowhead.com/quest=1097/elmores-task

## Screenshots

<img width="640" alt="Снимок экрана 2019-11-22 в 17 51 16" src="https://user-images.githubusercontent.com/46353863/69436338-412a6c00-0d52-11ea-88f3-a208cb1159e4.png">

## Questie version
5.2.3

**Comment by Nerillida** [comment]
Shows for me, latest version.

**Comment by BreakBB** [comment]
Most likely related to #860
