### ISSUE TITLE
Red Linen Goods

### ISSUE THREAD

**Issue by iron217** [AeroScripts/QuestieDev#1581]
## Description
there are no target icons on the map, but tomtom it can put a point on the farm through tracking

## Wowhead link
https://classic.wowhead.com/quest=83/red-linen-goods

## Screenshots

<img width="640" alt="Снимок экрана 2019-11-22 в 18 10 57 1" src="https://user-images.githubusercontent.com/46353863/69437209-e85bd300-0d53-11ea-96cb-91aab1d74693.png">

## Questie version
5.2.3

**Comment by BreakBB** [comment]
@iron217 Did you try `/reload` for this? Could also be related to the desync bug... The data looks fine on our side.

**Comment by iron217** [comment]
now everything shows a visible error was in something else, how can I verify this for sure?

**Comment by BreakBB** [comment]
@iron217 Well if it showing fine now it was the desync issue...

**Comment by iron217** [comment]
how to fix it? normal reboot then did not help, completely close the game?

**Comment by BreakBB** [comment]
I might have misunderstood you then: Are the icons showing for you or not?

**Comment by iron217** [comment]
now show

**Comment by BreakBB** [comment]
Then there is nothing really to fix. It was bad luck and the chance will be reduces with future updates. Sorry for the trouble.

**Comment by iron217** [comment]
yes there is nothing to apologize for, thanks for your work
