### ISSUE TITLE
malin's request

### ISSUE THREAD

**Issue by garypicher** [AeroScripts/QuestieDev#1587]
## Description
Questie shows Archmage Malin (in the Stormwind Mage District) offering a quest called Malin's Request, but I cannot interact with Archmage Malin at all.  According to wowhead, Malin's Request unlocks Worth It's Weight In Gold, which I've already completed.  Presumably that's why Malin's Request is no longer available, but I don't know for sure.

## Wowhead link
https://classic.wowhead.com/quest=690/malins-request

## Screenshots
I don't have one available right now, but could provide one if needed.

## Questie version
5.2.3

**Comment by BreakBB** [comment]
@garypicher Thanks for the report. I will look into this! Also would it be great if you use an issue template next time so we have all the information we need.

**Comment by garypicher** [comment]
Hi @BreakBB , sorry about that - not sure how I missed the templates when I opened it.  I updated the original comment to include the template text.  Thanks!
