### ISSUE TITLE
[3.0] Nil error when leaving mouseover

### ISSUE THREAD

**Issue by Muehe** [AeroScripts/QuestieDev#159]
Version b54c8976156594a2f6e89a111a6605e25a77a7cf
```
!Questie\Questie.lua:900: attempt to index field `data' (a nil value)
!Questie\Questie.lua:900: in function <Interface\AddOns\!Questie\Questie.lua:895>
```

When leaving mouseover of Crier Goodman in Stormwind City (he has an area overlay (due to waypoints?)). Doesn't happen when mousing over while viewing Elwynn and the exclamation mark has wrong position seen from there.

**Comment by Logonz** [comment]
Replied to your other post seems to be some kind of underlying issue here
as i said ill look into it when i get home from work. As i said probably
has something to do with the polygon data is incorrect and the data var is
where the icons customdata is handled if i remember corretly offhand

**Comment by Logonz** [comment]
There can be a very easy fix for this error... but it doesn't fix the underlying problem... but ill push a fix so atleast you dont get the error or tooltipbugs.

**Comment by Muehe** [comment]
Not sure if related, haven't gotten around to trying your fix yet:

```lua
!Questie\Questie.lua:893: attempt to index field `data' (a nil value)
!Questie\Questie.lua:893: in function <Interface\AddOns\!Questie\Questie.lua:882>
```
