### ISSUE TITLE
link in chat

### ISSUE THREAD

**Issue by iron217** [AeroScripts/QuestieDev#1597]
## Description
you can add a link to the name of the quest in the chat by clicking on the icon on the map or minimap

**Comment by Gogo1951** [comment]
You can link the name from your tracker window. Is that sufficient? I don't think clicking on the map or minimap is great, since there's already a click functionality tied to the minimap -- creates the "ping" sound. Could be annoying for others in party.

**Comment by iron217** [comment]
this is to quickly find a group while running to the quest
