### ISSUE TITLE
[50] Jonespyre's Request

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#1599]
## Description
![image](https://user-images.githubusercontent.com/15526476/69833114-2f553700-1232-11ea-8ec4-fd74aecbf6c7.png)

## Wowhead link
https://classic.wowhead.com/quest=3787/jonespyres-request
https://classic.wowhead.com/quest=3788/jonespyres-request

## Questie version
Unknown

**Comment by BreakBB** [comment]
Tested and working. Must be related to #860
