### ISSUE TITLE
[3.0] Weird display for [The Touch of Zanzil] (2609)

### ISSUE THREAD

**Issue by Muehe** [AeroScripts/QuestieDev#160]
Version b54c8976156594a2f6e89a111a6605e25a77a7cf
Quest: [The Touch of Zanzil](https://vanilla-twinhead.twinstar.cz/?quest=2609)
Notes:
 - Already aquired first two items (Simple Wildflowers and Leaded Vial) before installing 3.0
 - Required items can be bought from vendor (Bronze Tube) or looted from gameobject (Spool of Light Chartreuse Silk Thread)
 - All the little bags seen are from this quest, except the one in Westfall

![wowscrnshot_102515_194321](https://cloud.githubusercontent.com/assets/8838573/10717242/ab7e987a-7b51-11e5-8b8e-73f04f2e62e0.jpg)
![wowscrnshot_102515_194526](https://cloud.githubusercontent.com/assets/8838573/10717244/bcba5aca-7b51-11e5-8b3e-bd01841ab66a.jpg)

**Comment by Logonz** [comment]
Thanks for the report!
Will regenerate the dB and remove bronze tube!

**Comment by Muehe** [comment]
Sure this is the cause of the error here? Seems to me the addon tries to display things together, which it shouldn't. Would be nice to see the vendor positions when you have this quest or others like it.

**Comment by Muehe** [comment]
P.S. this might be connected to #161, as I found some normal displays when viewing single zones (e.g. Alterac Mountains).

**Comment by Logonz** [comment]
hmm you are right Muehe... seems to be some kind of underlying error here totally... probably the framedata not being reset correctly when reusing the frame OR the centerzone for the hotzones is calculated wrongly. Will look into both, 
Also when you see errors like this printsceen your Qlog as well so we can create the exact same usecase

**Comment by Muehe** [comment]
[A Simple Request](https://vanilla-twinhead.twinstar.cz/?quest=8233)
[The Defias Brotherhood](https://vanilla-twinhead.twinstar.cz/?quest=142)
[The Missing Diplomat](https://vanilla-twinhead.twinstar.cz/?quest=1274)

A screenshot wouldn't have done you any good with this quest names :wink: Don't think it matters though.

Done some more testing. When I delete the quest items they get added to the tooltip of the bag icons. If I click one of them, chat says (4 times):

rawDataIndex : [1-4]
Objective : table: 180D07[0/2/4/6]8
Qid : 2609
InteractType : Item

I also checked [Zenn's Bidding](https://vanilla-twinhead.twinstar.cz/?quest=488), it had all quest objectives in one tooltip too (no bugs though). So I guess you calculate hotzones for all quest items/mobs in a range? Pretty sure this is why the display bugs for "The Touch of Zanzil". Maybe just deactivating hotzones on world/continent maps would solve this?

**Comment by Muehe** [comment]
This seems fixed. Some targets are displayed in Dalaran though, which can not be entered...
