### ISSUE TITLE
Show or Hide Quests in Objective Tracker based on Zone

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1602]
## Description

It would be great if Questie show or hid quests based on if they had objectives in the zone you were currently in. Often my quest panel gets really long and cluttered, be nice to just streamline it.

**Comment by Gogo1951** [comment]
https://www.curseforge.com/wow/addons/butter-quest-tracker has the functionality to track by zone. It's not perfect... if a quest has objectives in a zone, but is listed as being part of another zone (like this one https://classic.wowhead.com/quest=735/the-star-the-hand-and-the-heart) it's not tracking correctly. Ideally it should do a check to see if any objectives are in the zone you're in, and if so then show the quests.

**Comment by weust1979** [comment]
This is a feature I really miss too. Glad I am not the only one.

I am not sure if Gogo1951 means only showing quests in a zone you're in, or dividers per zone in the total overview of quests. The latter would have my preference, with the ability to have - and + next to the zone name to show/hide the quests.

**Comment by walshta** [comment]
I agree it would be great if Questie could auto track/untrack quests in the objective tracker based on zone. It can be cumbersome to do this manually and the tracker gets cluttered when you get close to the quest limit.
