### ISSUE TITLE
The Treasure of the Shendralar

### ISSUE THREAD

**Issue by PlayfulPan** [AeroScripts/QuestieDev#1605]
## Description
I think there is an incorrect quest ID for the quest "The Treasure of the Shendralar" in Dire Maul. This is causing it to show as available after I have already completed it. 

Wowhead shows 2 versions of this quest, I believe one is a duplicate. 

The correct version is 
https://classic.wowhead.com/quest=7877/the-treasure-of-the-shendralar
which Wowhead correctly shows as me having completed. 

The duplicate is
https://classic.wowhead.com/quest=7462/the-treasure-of-the-shendralar
and this matches the quest ID 7462 which questie has listed for this quest.

So I think all that needs to be done is to update the quest ID for this one.

## Screenshots
![image](https://user-images.githubusercontent.com/58372586/69905333-084c5180-1367-11ea-9ff6-31122f719a06.png)

## Questie version
Questie V. 5.2.3

**Comment by gto112112** [comment]
I can confirm that I am also experiencing this issue

**Comment by BreakBB** [comment]
Fixed with 108a7cfad1049d150ed0daccb55522d768cb61ff Will be in the next release 👍
