### ISSUE TITLE
Warrior Kinship

### ISSUE THREAD

**Issue by PlayfulPan** [AeroScripts/QuestieDev#1606]
## Description
"Warrior Kinship" 
https://classic.wowhead.com/quest=8423/warrior-kinship
is incorrectly shown as available. It should be added in a later phase. Check the Wowhead comments.

## Questie version
Questie V 5.2.3

**Comment by BreakBB** [comment]
Fixed with a99cca7a3383ac9edfa6f3e489bc61415a70d046
