### ISSUE TITLE
Non grey icons don't get clipped when using leatrix zoom

### ISSUE THREAD

**Issue by teyasio** [AeroScripts/QuestieDev#1607]
When you're zoomed in and start panning.  Grey quest icons will clip properly and not draw outside of the map, yellow quest icons will draw outside of a zoomed in map.

**Comment by martinboy1974** [comment]
https://imgur.com/sUZJYqI

**Comment by martinboy1974** [comment]
Why is this issue closed? Doesnt look fixed?
