### ISSUE TITLE
Quest already completed: Manaweave Robe.

### ISSUE THREAD

**Issue by Remendador** [AeroScripts/QuestieDev#1608]
Questie-v5.2.3.zip

Hi there, thanks for the great addon.

I have just completed the mage quest Manaweave Robe and it still shows on the map and the minimap as if it's still available to get. Eventually I used /reload and it was removed from my maps. I don't know if it's an issue but I wanted to report that case.

**Comment by BreakBB** [comment]
Thanks for the report, but since a `/reload` helped this is related to #860
