### ISSUE TITLE
How to reset hidden quests

### ISSUE THREAD

**Issue by gto112112** [AeroScripts/QuestieDev#1609]
## Question

I hid some quests and was wondering how I can reset that to show them?

**Comment by BreakBB** [comment]
@gto112112 Sorry for the late response on this. If you want to unhide all quests you can run:

`/run Questie.db.char.hidden = nil` and do a `/reload` afterwards.

If you just want to unhide specific quests you have to search them in the Journey and uncheck the "Hidden by user" checkbox:

![image](https://user-images.githubusercontent.com/33514570/70456269-18bea380-1aae-11ea-9fe7-a6a82b6ff8dd.png)
