### ISSUE TITLE
[3.0] NPC position changes

### ISSUE THREAD

**Issue by Muehe** [AeroScripts/QuestieDev#161]
Version b54c8976156594a2f6e89a111a6605e25a77a7cf

When a NPC has an overlay its display position changes when viewed from another zone (also reported in #159)
![wowscrnshot_102515_200951](https://cloud.githubusercontent.com/assets/8838573/10717331/df4e3d10-7b54-11e5-8169-093436f055ff.jpg)
![wowscrnshot_102515_200959](https://cloud.githubusercontent.com/assets/8838573/10717335/e9f68cf4-7b54-11e5-89d2-776191048104.jpg)

**Comment by Logonz** [comment]
Hmm thats fucked up probably has to do with the hotzones center code...
Will look into it

**Comment by jasskin** [comment]
I don't know if it is 100% related but i had a similar issue it turned out to be caused by another add-on called Detattched mini buttons ver. 0.9.22
