### ISSUE TITLE
Add a hotkey to temporarily hide other quest markers

### ISSUE THREAD

**Issue by wodim** [AeroScripts/QuestieDev#1610]
Even with different colours, this is a mess:

![image](https://user-images.githubusercontent.com/1001553/70177480-be52cb00-16da-11ea-8a0f-b098f028be23.png)

My suggestion: if I put the mouse on one of the quest markers and I hold some key like Control, the rest of quest markers become translucent or disappear.

**Comment by BreakBB** [comment]
@wodim You can use the tracker to "focus" a quest/objective, which will fade out all others. With the next release the objectives for one quest will also be highlighted when you mouseover them

**Comment by wodim** [comment]
>With the next release the objectives for one quest will also be highlighted when you mouseover them

Oh, then that's it. Thanks.
