### ISSUE TITLE
Wrong markers for Bloodpetal Trappers

### ISSUE THREAD

**Issue by wodim** [AeroScripts/QuestieDev#1611]
Bloodpetal Trappers appear to the left side of the map: https://classic.wowhead.com/npc=6512/bloodpetal-trapper

Bloodpetal Lashers appear to the right side of the map:
https://classic.wowhead.com/npc=6509/bloodpetal-lasher

But, when you are doing [Larion and Muigin](https://classic.wowhead.com/quest=4145/larion-and-muigin), somehow Trappers and Lashers are marked as the same NPC:

![image](https://user-images.githubusercontent.com/1001553/70352604-c5f5a980-186b-11ea-93c0-50b5b51b5834.png)

And on the map, Trappers appear to the right, when they should be to the left:

![image](https://user-images.githubusercontent.com/1001553/70352677-f76e7500-186b-11ea-9bb9-d9c563e05c34.png)

## Questie version
Questie v5.2.1

**Comment by BreakBB** [comment]
@wodim Did you try a `/reload` with this? It really is strange.

**Comment by wodim** [comment]
I don't remember. Maybe. It's too late to check now, I'm afraid.

**Comment by BreakBB** [comment]
I can't find a reason for this to happen and afaik it was working for me a while back 🤔

**Comment by wodim** [comment]
It's probably not a bug in the DB but a bug in the addon. Anyway I can't debug it anymore so let's forget about it.

**Comment by BreakBB** [comment]
Logon is currently rewriting a lot of logic which should prevent such issues. He's streamlining a lot of code parts which should make everything easier to understand and saver as well.
