### ISSUE TITLE
Quest objective text not wrapping

### ISSUE THREAD

**Issue by apo619** [AeroScripts/QuestieDev#1612]
With quests that have really long objective descriptions, the text does not wrap within the normal boundary defined by the tracker frame. It instead expands the tracker frame to fit the unwrapped text. See attached image for an example. This is occurring with v5.2.3 but has been happening with quests with similar long objectives since I began using Questie at the start of WoW Classic. I use the Twitch client to download and update my addons. Thanks!
![quest_tracker_nowrap](https://user-images.githubusercontent.com/58638526/70379663-33452100-18e4-11ea-9c4c-51ac1c420639.png)

**Comment by BreakBB** [comment]
@apo619 This has been fixed partly on the master branch. You can now resize the tracker and it will cut off the objectives if it is too long. We have #1093 to add general line wrapping.

The fix for this will be released very shortly with v6.0.0

**Comment by dlecina** [comment]
Sorry to comment on this old issue.

Is this supposed to be working in Classic? I cannot find any way to unlock or resize the tracker.

**Comment by BreakBB** [comment]
Hey @dlecina Yes on Classic Era and BCC you can resize the Tracker so it cuts off too long objectives.

The solution isn't perfect yet, but we are planning to rewrite the Tracker entirely to include other nice adjustments as well. If you have issues with Questie feel free to contact us on Discord or open up a new ticket.

**Comment by HaGGi13** [comment]
Any Updates on this?
