### ISSUE TITLE
Show ! on items that start quests in your bags

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1613]
## Description

At some point they added this to the game by default, but seems like ArkInventory is adding a gold coin to gear you can safely vend so it should be possible to add a gold "!" to gear that starts a quest you haven't done yet? Minor quality of life thing... I was in a group in Swamp of Sorrows and my party friends couldn't find the cudgel quest. "Look at your trash items." Pause... "Oh there it is!" Easier if we had a ! on the items.

**Comment by Crumdidlyumshis** [comment]
ElvUI has this feature built in, so if this feature gets added to just make sure its compatible. :)

**Comment by Gogo1951** [comment]
Cool, I use ElvUI, but I turn off their bags since i use ArkInventory.

**Comment by Gogo1951** [comment]
Gonna close this, doesn't see like it's high value.
