### ISSUE TITLE
Travel Log Quest by Continent/Zone Filter not translated

### ISSUE THREAD

**Issue by woopydalan** [AeroScripts/QuestieDev#1617]
Hi,

In the Travel log where you can filter all the quest you have completed/not completed by zone, the names of the zones and continents are not translated. Can those be updated to show the names of zones/continents in the local client language?

**Comment by BreakBB** [comment]
Have a look a [the German version](https://github.com/AeroScripts/QuestieDev/blob/master/Locale/deDE/lookupZones.lua) for the lookupZones. We need such a file with all the translations for every language so it is translated.

**Comment by drejjmit** [comment]
eda6cb803b769f32f6c96cac1d7032b0583cddf4
