### ISSUE TITLE
[3.0] Shift+Ctrl clicking quest giver only completes one quest

### ISSUE THREAD

**Issue by Muehe** [AeroScripts/QuestieDev#162]
Version b54c8976156594a2f6e89a111a6605e25a77a7cf

When a questgiver has more than one quest to offer and you Shift+Ctrl click him, only one of the quests is offered for completion. Maybe make a cascading menu like Cartographer to choose the right quest?

**Comment by Logonz** [comment]
Ive been thinking about it i really like the simplicity of the ctrl shift
and to be honest the case where you need to complete one quest and not the
other is rare and when that is the case people can overcome it by talking
the quest they dont wanna complete. You think the work will be worth the
effort?

**Comment by Muehe** [comment]
Yes, I think it will. But seeing as the UI is still kind of basic anyway, maybe we should shelve this problem, until the backend logic is working completely? Still under a lot of stress right now but when I have the time I can take a look at this, so just leave this unassigned for now. A pointer where I can find the tooltip code would be nice though, so I can start reading.
