### ISSUE TITLE
AV Errors

### ISSUE THREAD

**Issue by addohm** [AeroScripts/QuestieDev#1621]
## Bug description
Doesn't work at all in AV.  Lots of errors in chat to do with the AV quests.

## Screenshots
![WoWScrnShot_121119_170559](https://user-images.githubusercontent.com/25333107/70607130-dbd2e800-1c38-11ea-86dc-f4e39f439c20.jpg)

## Questie version
5.3.0

**Comment by BreakBB** [comment]
We weren't able to test any of these quests before release, sorry for the trouble. We're on it to fix those errors asap.

**Comment by BreakBB** [comment]
Fixed with 64cdbd2815a380b75ef700cbfdaa5f7e6c7bef17
