### ISSUE TITLE
Extended status of quests not shown on tooltip when the tooltip is seen for the first time

### ISSUE THREAD

**Issue by wodim** [AeroScripts/QuestieDev#1624]
When you hover over an available quest, if it's an elite/dungeon quest and it's the first time you see the tooltip, the + sign and "dungeon" remark is not displayed:

![image](https://user-images.githubusercontent.com/1001553/70629482-5b0cef80-1c2a-11ea-9420-ca3ca4e6d6dc.png)

Then, if you move the mouse away and look at the tooltip again, the tooltip is correctly displayed:

![image](https://user-images.githubusercontent.com/1001553/70629513-65c78480-1c2a-11ea-80b3-19fdf44547db.png)

From then on, the correct tooltip will be displayed always, even after a /reload of relog.

**Comment by wodim** [comment]
v5.2.3

**Comment by wodim** [comment]
v5.3.1

**Comment by BreakBB** [comment]
@wodim I can't reproduce this and I assume this has been a caching problem with the API. Feel free to open a new issue if this is still a problem.

**Comment by wodim** [comment]
It still happens. And yes, it seems a caching problem. 

![image](https://user-images.githubusercontent.com/1001553/83331714-0d4b7880-a298-11ea-9f12-ab5d6a70fc9f.png)

![image](https://user-images.githubusercontent.com/1001553/83331716-13415980-a298-11ea-9870-70bea7000a89.png)

**Comment by wodim** [comment]
I assume the entire quest database  comes with the addon but the elite/dungeon/etc status is requested from the server once the tooltip is displayed and is therefore not available until the tooltip is drawn a second time? How about 1) storing that status along with the list of quests in the database or 2) requesting the elite/dungeon/etc status when the ! symbol is drawn so by the time the user looks at the tooltip the status is (hopefully) already in cache?

**Comment by BreakBB** [comment]
You assume right and I have to dig deeper into the code when exactly the information about the type is acquired.

Any specific hints about how to reproduce this? Yes, maybe we should request the data earlier to allow it to be cached.

**Comment by wodim** [comment]
Entirely remove the quest cache (or the entire WTF folder...) and hover over a dungeon quest.
