### ISSUE TITLE
Alterac Tal quests errors

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1626]
## Description
The three quests of Durgen Stormpike (Alterac Valley) lead to errors

## Wowhead link
https://classic.wowhead.com/npc=13777/sergeant-durgen-stormpike#english-comments
https://classic.wowhead.com/alterac-valley

## Screenshots
![](https://i.imgur.com/kH535y3.png)
![](https://i.imgur.com/WZ0IFrC.png)
![](https://i.imgur.com/Eb78OZl.png)

## Questie version
5.3.0

**Comment by Gogo1951** [comment]
This is a duplicate of https://github.com/AeroScripts/QuestieDev/issues/1621

**Comment by BreakBB** [comment]
And already fixed with v5.3.1
