### ISSUE TITLE
The Graveyards of Alterac

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1627]
The PvP quest The Graveyards of Alterac (Horde side) isn't present on the map/minimap or in the journey.

No wowhead link unfortunately, it appears wowhead hasn't updated it yet.

![WoWScrnShot_121219_011149](https://user-images.githubusercontent.com/54936174/70671509-87515c00-1c7c-11ea-8e5e-346e9d9990a7.jpg)

Version 5.3.1

**Comment by BreakBB** [comment]
@Cerby3BR This is the WoWhead link: https://classic.wowhead.com/quest=7082/the-graveyards-of-alterac

And that quest shows up for me:

![image](https://user-images.githubusercontent.com/33514570/70674911-b8835980-1c87-11ea-9bf6-5084788aacd3.png)

Buuut, it is marked as repeatable. So maybe you disabled repeatable quests?

We will also add another list of "Battlefields" to the Journey, so they will show up separately.

**Comment by Cerby3BR** [comment]
It is indeed tagged as a repeatable quest, my bad. Is it really repeatable though?
