### ISSUE TITLE
error populating objectives for Ledger from Tanaris 4450

### ISSUE THREAD

**Issue by tecnobrat** [AeroScripts/QuestieDev#1628]
## Description
Receive the following error when I load into the world:

`Questie: [ERROR] [QuestieQuest]: v5.3.1 - There was an error populating objectives for Ledger from Tanaris 4450 4 ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:757: attempt to perform arithmetic on field 'x' (a table value)`

## Wowhead link
https://classic.wowhead.com/quest=4450/ledger-from-tanaris

## Questie version
`## Version: 5.3.1` from the toc

**Comment by tecnobrat** [comment]
No idea if this is helpful, but from my SavedVariables:

```
				{
					["Event"] = "Quest",
					["SubType"] = "Accept",
					["Level"] = 46,
					["Quest"] = 4450,
					["Timestamp"] = 1575234549,
				},
```

**Comment by BreakBB** [comment]
@tecnobrat Thanks for this report. It is not easy for us to test, so it would be great if you could answer a few questions:

- Does this error appears every time you log in or relog?
- Are the objectives showing up correctly nevertheless?

**Comment by Gogo1951** [comment]
Hey @BreakBB ,

Oddly enough, I had this quest and got the same issue.

Showed as an error, as described.

Objectives didn't show on the map. I had done 3/4 before the patch, and the last one I had was no longer visible once I got the error.

https://classic.wowhead.com/quest=4450/ledger-from-tanaris

Goodsteel Ledger (DONE BEFORE PATCH)
Solid Crystal Leg Shaft (20) (DID NOT SHOW ON MAP)
Overdue Package (DONE BEFORE PATCH)
Goodsteel's Balanced Flameberge (DID NOT SHOW ON MAP)

When I was done it did show where to turn in though.

**Comment by BreakBB** [comment]
I checked the corrections and found the issue for this! 🎉 I "corrected" the spawns for "Jarquia" which drops "Goodsteel's Balanced Flameberge", but actually added corrupted data as well. Should be good now. Thanks @tecnobrat and @Gogo1951 for the help and report!
