### ISSUE TITLE
icons on the mini map

### ISSUE THREAD

**Issue by PinkiePie86** [AeroScripts/QuestieDev#1631]
## Questie mini map icons

when i first dowloaded questie icons would show up on the mini map. now it doesnt do that. i reset questie. then did an update. still nothing

**Comment by BreakBB** [comment]
@PinkiePie86 Just to make sure. You've the following settings enabled?

![image](https://user-images.githubusercontent.com/33514570/70787147-6416d180-1d8e-11ea-8d9f-0cad992a2e9d.png)

Moreover in Alterac Valley we are not able to draw quest icons on the minimap.

**Comment by baconfat** [comment]
I have the following set but I still don't see the mini map icons. I have disabled all other addons and only have Questie loaded.

**Comment by baconfat** [comment]
Going back to version v5.2.3, I see the mini-map icons.

**Comment by BreakBB** [comment]
@baconfat If you don't care about your Journey you can try to delete all settings of Questie. These are located in the WTF folder and are named "Questie.lua" and "Questie.lua.bak"

**Comment by baconfat** [comment]
@BreakBB, with v5.4.0 installed I deleted "Questie.lua" and "Questie.lua.bak" from:
```
C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\<account>\SavedVariables
C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\<account>\<server>\<character>\SavedVariables
```
I disabled all other addons and reloaded the UI but I still don't see the icons on the mini map. When I revert to v5.2.3 the icons are visible

**Comment by BreakBB** [comment]
@baconfat Where exactly do you grab your copy of Questie from? Do you use the Twitch client?

I've had another user on Discord with a similar (or the same) issue and I actually have no clue which this happens.

Oh I have another idea: Delete the following files (with WoW closed) and then try again:

Global settings:
```
World of Warcraft\_classic_\WTF\Account\<yourAccount>\SavedVariables\Questie.lua
```
```
World of Warcraft\_classic_\WTF\Account\<yourAccount>\SavedVariables\Questie.lua.bak
```

Per character settings:
```
E:\Battle.net\World of Warcraft\_classic_\WTF\Account\<yourAccount>\<yourServer>\<yourCharacter>\SavedVariables\Questie.lua
```
```
E:\Battle.net\World of Warcraft\_classic_\WTF\Account\<yourAccount>\<yourServer>\<yourCharacter>\SavedVariables\Questie.lua.bak
```

I think we never listed the global settings anywhere so I have to add that to the FAQ.

**Comment by baconfat** [comment]
@BreakBB I typically install with the Twitch client. However to simplify things, I downloaded v5.4.0 from GitHub. After deleting the Questie.lua and Questie.lua.bak files I still don't see the icons on the mini map. Version 5.2.3 continues to defy the odds and shows the mini map icons for me. I normally run with ElvUI. I am not sure if that makes a difference. Thank you for all the help thus far.

Cheers!

**Comment by BreakBB** [comment]
@baconfat This is indeed very very odd :thinking: Me and others don't have a problem so I can't reproduce this issue.

Can you try the following:
1. Log into WoW and disable all addons except Questie (with 5.4.0)
2. Close WoW
3. Delete the 4 files listed above
4. Start WoW
5. Report if it works or not

**Comment by baconfat** [comment]
@BreakBB that worked! Unfortunately when I load a second AddOn the mini map icons vanished. Questie on it's own is working for me but since I want to use other AddOns I will continue with version 5.2.3 as a workaround. Thank you

**Comment by BreakBB** [comment]
@baconfat Which other minimap addon are you using? Looks like we have a conflict with another addon which we might be able to solve on our side!

**Comment by baconfat** [comment]
@BreakBB, I guess it is a timing issue when the UI renders. The AddOn I loaded is HealBot, which I don't think affects the minimap icons. After loading the second AddOn, my minimap icons disappeared. However, if I zoom in and out of the minimap, the icons reappear! (I don't know why I didn't try this earlier). I can load all my AddOns and run Questie v5.4.1 from Twitch, and everything is displaying as expected. Thank you for the excellent work and apologies for leading you on this wild goose hunt. 

Happy New Year!

**Comment by baconfat** [comment]
Update: The minimap icons are appearing but I noticed the overlay on the minimap is missing. I no longer get these helpful tips.

![image](https://user-images.githubusercontent.com/623881/71727747-42e35700-2e09-11ea-8a0e-22f02a0416d3.png)

**Comment by BreakBB** [comment]
@baconfat Thanks for coming back to this. Yes we are having an issue with the tooltip since v5.3.0. But I am very sure I just found the reason for it and a fix as well. Keep an eye out for the next release.
