### ISSUE TITLE
Marker missing for The Missing Diplomat (16) after failing

### ISSUE THREAD

**Issue by wodim** [AeroScripts/QuestieDev#1632]
https://classic.wowhead.com/quest=1324/the-missing-diplomat

I started it, and he killed me. The quest was subsequently marked as failed. I abandoned it so I could take it again, but the ! marker did not come back.

![image](https://user-images.githubusercontent.com/1001553/70839691-2d809b80-1e0e-11ea-9db6-0bd0da914232.png)

5.3.1

**Comment by drejjmit** [comment]
Fixed with f35b84a7a736fa279cc59179a1c030a16fd01da3
