### ISSUE TITLE
Disabled minimap icons only hide until reload/restart

### ISSUE THREAD

**Issue by Luckyone961** [AeroScripts/QuestieDev#1636]
## Bug description
The option "Enable Minimap Icons" disables the minimap icons only until next reload or restart.
As you can see in the following screenshot, I disabled them, reloaded and they still show up.
This happens with only ElvUI (1.19) + Questie (v5.3.1) enabled and also on default Blizzard UI.

## Screenshots
![WowClassic_ah9hJewX7t](https://user-images.githubusercontent.com/5923203/70865811-12bf3b80-1f62-11ea-89fe-167948b61820.png)

## Questie version
Version: 5.3.1

**Comment by BreakBB** [comment]
Just tested this on v5.10.0 and I can no longer reproduce this. Feel free to comment again if this is still an issue.
