### ISSUE TITLE
Lost Necklace not showing !

### ISSUE THREAD

**Issue by fireboy92k** [AeroScripts/QuestieDev#1637]
Lost Necklace from 'Auntie' Bernice Stonefield is not showing a '!' marker.  I went in and made sure I have low level quests on just in case, but still didn't show.  Leveling a gnome warlock at lvl 12 currently.  Running latest release versions of game and Questie.

**Comment by BreakBB** [comment]
@fireboy92k Please use one of our issue templates next time when reporting something. That will help us to investigate more quickly :)

**Comment by BreakBB** [comment]
Moreover the data looks perfect in our DB 🤔 Can you share a screenshot? Are you on an English client?

**Comment by fireboy92k** [comment]
Yeah I thought the template didn’t look right from a previous one I had turned in. Sorry about that. 

I also didn’t take a screen shot. I’ll make sure to do that next time as well.   

We can close if nobody else has seen.
