### ISSUE TITLE
Quest Tracker Background

### ISSUE THREAD

**Issue by Comicus** [AeroScripts/QuestieDev#1638]
## Description

Is there a way or can there be a way to change the lighting of the background of the Tracker.?

**Comment by BreakBB** [comment]
@Comicus The latest release doesn't have a background at all 🤔 But we want to add more options for this.

**Comment by Gogo1951** [comment]
Hey @Comicus ,

In the short term, https://www.curseforge.com/wow/addons/butter-quest-tracker or https://www.curseforge.com/wow/addons/monkey-quest can help you customize your tracker layout.

**Comment by BreakBB** [comment]
@Comicus This has been added on the master branch and will be released very shortly with v6.0.0
