### ISSUE TITLE
Questie shouldn't trigger on players

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1641]
## Description

Funny post on Reddit today.

https://old.reddit.com/r/classicwow/comments/eb8aji/this_level_14_druid_is_named_ishamuhale_i/

![ugdvpuo1iw441](https://user-images.githubusercontent.com/55365231/70944472-bff48b00-2018-11ea-9eae-96f9a7262b2f.jpg)

Questie should check to see if the target isn't a player before loading tooltips for quest objectives. (=

**Comment by BreakBB** [comment]
We've already seen that and it must have been a really old version of Questie. We're already checking `if name and type=="Creature" ` so it is not a player.
