### ISSUE TITLE
Add mob level in quest tooltips when you hold shift

### ISSUE THREAD

**Issue by wodim** [AeroScripts/QuestieDev#1642]
When you hold shift while you look at a quest tooltip, the name of the mob that you have to kill (or that drops the quest item) is shown. I think it would be nice to include the level range of that mob next to the mob name. Sometimes the level range of the mob is very different from the quest level, or some mobs that drop the same item are of very different level ranges and it's more convenient to go for the lower level ones.

**Comment by BreakBB** [comment]
@wodim How about something like this?

![image](https://user-images.githubusercontent.com/33514570/71044069-e86fa880-2130-11ea-91f0-0f894ac98ce9.png)

**Comment by wodim** [comment]
Looks great. Thanks.

**Comment by wodim** [comment]
To extend this: would it also be possible to add whether mobs are elite 
or not? Something like: (39-40+)

**Comment by BreakBB** [comment]
Added in 60d09c8d5a8154a69ae534af32e6afda26fc2a1b

**Comment by wodim** [comment]
Oh thanks buddy.
