### ISSUE TITLE
Ledger from Tanaris

### ISSUE THREAD

**Issue by Canidomini** [AeroScripts/QuestieDev#1645]
Questie: [ERROR] [QuestieQuest]: v5.3.1 - There was an error populating objectives for Ledger from Tanaris 4450 4 ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:757: attempt to perform arithmetic on field 'x' (a table value)

**Comment by BreakBB** [comment]
@Canidomini Please use one of our issue templates next time. What version are you on? This should be fixed with v5.3.1 afaik.

**Comment by Canidomini** [comment]
I am using 5.3.1, and the bug pops up upon login; it’s the only quest I’ve ever noticed an error on.  I can certainly update and/or close my item and open it properly if it helps.

**Comment by BreakBB** [comment]
Oh I know why this seemed so familiar. It was already reported in #1628 and is fixed with d1289674033277779faefe1ab748b8b9a7211462

The fix will be in the next release which will come out really soon,
