### ISSUE TITLE
The Scent of Lar'Korwi

### ISSUE THREAD

**Issue by databoose** [AeroScripts/QuestieDev#1647]
## Bug description
The map markers for the mobs are there and generally seem to be correct, however the actual mobs the quest item "Ravasaur Pheromone Gland" are not at all marked when actually moving my mouse over them, they are not recognized as a quest mob that i need to kill to get the item

Presumably, all ravasaur's drop this quest item, however i can't test to make sure at this point because i had already done the quest

I am using an older version of questie, **however** i have checked the changelog and have searched for this same issue, and i can't find anything else pertaining to it.

## Screenshots
![index](https://user-images.githubusercontent.com/7876395/71077817-04794700-213d-11ea-877a-6e6a1e178b66.png)

## Questie version

Questie v.5.2.3

**Comment by BreakBB** [comment]
@databoose It would be great if you could update your Questie version and try again. The latest release is v5.3.1

**Comment by BreakBB** [comment]
You won't lose any progress or anything when updating, so you should fear it ;)

**Comment by BreakBB** [comment]
Oh I checked the quest and it is absolutely correct that "Ravasaur" are not marked.

https://classic.wowhead.com/quest=4291/the-scent-of-larkorwi

Only [Lar'korwi Mate](https://classic.wowhead.com/npc=9683/larkorwi-mate) drop those items which spawn when you step on the eggs.
