### ISSUE TITLE
Gelkis Alliance (Horde) - Doesn't complete and missing ? on map when completed

### ISSUE THREAD

**Issue by JBRadio** [AeroScripts/QuestieDev#1652]
## Description
When your reputation with the Gelkis centaur clan is Friendly, Questie does not update the quest in the log to complete, nor does the ? show on the map. However, if you look at your quest log instead of Questie, you can see it completed.

I only play as Horde so I would recommend reproducing the issue as that faction. This has happened for undead, orc, troll, and tauren.

## Questie version
Questie version 5.3.1

**Comment by BreakBB** [comment]
@JBRadio Thanks for letting us know. I think is most likely because of Blizzard don't fire specific events for some quest (objectives) so I am not sure if we can do something about it. Did you try a `/reload` to see if that helps?

**Comment by JBRadio** [comment]
@BreakBB Thank you for responding. I haven't tried the /reload and now I don't have the quest anymore. It makes sense that public Blizzard API may not be able to tell you everything about what's going on in realtime. I wanted to report it in case it could be worked on. I haven't confirmed yet if the other reputation quests (ex: Timbermaw, Argent Dawn) also show the same issue. Thank you again.

**Comment by BreakBB** [comment]
@JBRadio Most of those things are really hard to test for us so we heavily rely on complete report of the users.

Newly available quests should work though. If I remember correctly we're calculating all the available quests up new whenever the reputation changed (same as with profession skilllevel).
