### ISSUE TITLE
When a tooltip shows several quest givers, the first one uses a bigger font

### ISSUE THREAD

**Issue by wodim** [AeroScripts/QuestieDev#1653]
Nitpick: 

![image](https://user-images.githubusercontent.com/1001553/71269201-06b2ef80-234f-11ea-9b02-952eccb295f5.png)

Here "Crank Fizzlebub" has a bigger font than the rest of quest givers, but he's not more important... I suppose this happens because his name is interpreted by the code as the header of the tooltip. I think either all quest givers should have that font size, or none at all.

**Comment by wodim** [comment]
v5.4.0

**Comment by BreakBB** [comment]
This is unfortunately simply how the GameTooltip works and we can't do anything about it. The first line will always be bigger than others thanks to Blizzard 😞
