### ISSUE TITLE
Toggle for PvP Quests

### ISSUE THREAD

**Issue by xDemoN** [AeroScripts/QuestieDev#1654]
## Description
Similar to the feature request for dungeon quests in #1625 and the already implemented toggle for repeatable quests.

**Comment by Gogo1951** [comment]
While I don't love the idea about turning off Dungeon Quests, I love the idea of being able to ignore PVP quests. Ha, go figure. I just shift + right click on all the PVP quests until they go away. Ha.

**Comment by Coreston** [comment]
> While I don't love the idea about turning off Dungeon Quests, I love the idea of being able to ignore PVP quests. Ha, go figure. I just shift + right click on all the PVP quests until they go away. Ha.

I second this.  I don't do PvP and would like to not see them.
