### ISSUE TITLE
Possible issue updating addon for new patch - class quest

### ISSUE THREAD

**Issue by Zhme-Kakarot** [AeroScripts/QuestieDev#1655]
## Description

Used the addon quite regularly before the recent patch on the 10th, after having logged back on yesterday all of my addons appeared to be out of date...

Deleted all, redownloaded, and began test.

Warrior Quest (was at level 12) in Tirisfal glades, (will update with actual quest name if I can be told how to find ignored quests!)

Note: The quest that was showing up had already been completed, to my knowledge.

## Questie version

v5.4.0

**Comment by BreakBB** [comment]
Some addons didn't list themselves for the recent patch 1.13.3 which is the reason they are listed as "out of date" even though "all" should still work as expected.

You can reset all the hidden quests by running: `/run Questie.db.char.hidden = nil` and then do a `/reload`. If you want just specific quests you have to search for the quest (by name or ID) and unmark is as hidden.

Just to make sure I understand you correctly: There is/was a quest shown by Questie for you which you can't take?

**Comment by Zhme-Kakarot** [comment]
Yes, the quest showed up on all maps but was unavailable for pickup.  Ran the script and reloaded but the quest that was glitched is no longer showing up, so I'll assume that a simple reload resolved the issue.  If a similar situation happens again I'll have more details to supply. Thank you.

**Comment by BreakBB** [comment]
@Zhme-Kakarot Thanks for the fast response. Yeah most likely a "desync" which shouldn't happen anymore once we finished a bigger refactoring of some code parts.
