### ISSUE TITLE
Optional 'Call of Water' quest

### ISSUE THREAD

**Issue by Junkbots** [AeroScripts/QuestieDev#1658]
There is an optional, backup quest near the end of the 'Call of Water' Shaman quest chain in Silverpine offered by Tiev Mordune, mostly as a backup in case players mess up with speaking to the Elemental to finish the quest normally.

The issue is that this quest is no longer available if you finish the Call of Water chain and it continues to be displayed on the map afterwards.

**Comment by Gogo1951** [comment]
Hey man, it's hard to test these without characters who are the right level and at the right stage of quest completion.

Can you provide Quest IDs for these quests? That'll help us easily track them down. The problem with the Call of Water chain is that every quest in the series has the same name.

Do you know what quest you have to complete to make the alternate quest chain unobtainable? Is it step 1, or the last step?

Do you know what the name of the replacement chain is? Is this it? https://classic.wowhead.com/quest=63/call-of-water

**Comment by Junkbots** [comment]
Hey, sorry for the lack of info. The specific quest I'm talking about is: https://classic.wowhead.com/quest=1103/call-of-water which requires you to have the quest: https://classic.wowhead.com/quest=100/call-of-water in progress to accept it at all.

The point of the aforementioned quest was to provide another means to summon the Minor Manifestation of Water that the latter quest is handed in to, which I assume is also the point where a player that didn't take this extra part of the Call of Water chain would be cut off from it. Apologies for not having exact quest IDs to post, I went looking but couldn't find them.

**Comment by Gogo1951** [comment]
Hey @Junkbots ,

You included the Quest IDs in the URL! (= 

Thanks!

**Comment by BreakBB** [comment]
@Junkbots Thanks for your report. I added some changes to this to mark the quest 1103 as a child quest of 100. Hopefully this fixes your issue :)

It would be great if you could extract the file below into `Database\Corrections`, overwrite the existing one and report back if the quest is removed from your map.
[QuestieQuestFixes.zip](https://github.com/AeroScripts/QuestieDev/files/4000223/QuestieQuestFixes.zip)
