### ISSUE TITLE
A Gently Shaken Gift

### ISSUE THREAD

**Issue by Orome123** [AeroScripts/QuestieDev#1659]
## Description

Questie shows "A Gently Shaken Gift" as being available under the tree in Orgrimmar, but it's nowhere to be found. I don't know if it isn't coded in the game, but the quest is just not there. Wowhead link's only comment also says it's not there. All the other "gifts" there are there with no problem.

## Wowhead link

https://classic.wowhead.com/quest=8767/a-gently-shaken-gift

## Screenshots

![WoWScrnShot_122519_215736](https://user-images.githubusercontent.com/56611266/71452277-2fc5ec80-2762-11ea-9378-5d0f194fdb03.jpg)

![WoWScrnShot_122519_215749](https://user-images.githubusercontent.com/56611266/71452280-32284680-2762-11ea-91c9-85a1f656585b.jpg)

## Questie version

5.4.1

**Comment by Cerby3BR** [comment]
This may be related to the fact that after I completed it, Questie believes I completed the Alliance version.

![WoWScrnShot_122619_184341](https://user-images.githubusercontent.com/54936174/71485102-d3b9a180-280f-11ea-8d68-0c963b90efb1.jpg)

**Comment by BreakBB** [comment]
@Orome123 @Cerby3BR This issue should be fixed with a reupload of v4.2.1 I noticed the issue just after release the latest version and added the fix to it. You might need to redownload the latest Questie version for this to be fixed.

**Comment by Orome123** [comment]
Hey, I just downloaded the most recent Questie just now, and the quest "A Gently Shaken Gift" still shows up. I think it wasn't fixed for some reason. Thanks for asnwering!

**Comment by BreakBB** [comment]
Sorry I was too fast on this. I have to check again.

**Comment by Orome123** [comment]
No problem at all! Respect the dedication and effort put into this project, always fast answers and fixing the issues. Definitely great job man :D
