### ISSUE TITLE
Compatibility with WoW 1.12

### ISSUE THREAD

**Issue by Steelzzz** [AeroScripts/QuestieDev#166]
First, congratulations for this nice work. This addon look awesome.

A simple question over there though : Is there a way to make it compatible with Vanilla 1.12 ?

I mean, 1.12 is not that far from 1.12.1, I'm pretty sure it is possible to achieve this with some little tweaks.

There are servers that run this version and the use of this addon is impossible. However, it may interest hundreds of people. So, even if you have no plan doing it, can I have some tips to do it by myself ?

Thank you.

**Comment by Logonz** [comment]
ehhhhhhhhh..... depends on what is missing really... it could be just as simple as lowering the version number in the .toc, but i haven't got 1.12 so can't test it

**Comment by Steelzzz** [comment]
Basically, nothing works on this version. map, minimap, tooltip, tracks, ... I didn't noticed any change after installing it, except that the the quest log was empty and buggy. So I think there are more things to fix than just the version number.

I'd completely understand if you don't want to spend too much time on this, though. However, I'd really appreciate if you could show me some tips, like where I should look, check things, etc ...

**Comment by Logonz** [comment]
Did you change the version number inside all toc folders? I don't Think wow will load addons that are further infront of the current version

**Comment by Steelzzz** [comment]
I forgot to mention that I got no experience on addon development so far. But I should be OK though.

I Looked for all the .toc files but only found one : "!Questie.toc"

The version is already "## Interface: 11200" so it seems ok I guess.

I made another test actually. It did work eventually, but not full : 
- I could see my quest log, but I couldn't track quests.
- I see a lot of exclamation marks on the map and the minimap, but it shows every quest givers without taking care of my current progression. It's like it's not synced with my character. So I can't rely on it.
- I got no arrow that shows me where to go neither. 
- The tooltip remains unchanged and doesn't show the quest objectives.

Any idea ?

**Comment by Steelzzz** [comment]
I think it may have something to do with the fact that my WoW client is not in english. I could make it work on 1 quest because I think the name is the same in english. However, the arrow leads me to the wrong position, like really wrong.

If I am right, how can I make it work with the translated quest names ?

**Comment by Muehe** [comment]
You'd probably have to run the extractor script over a french/german/whatever DB for a first step. Right now only english is supported.

**Comment by Logonz** [comment]
Yeah, you would need to do that first, NEVER done it so don't know how many
times it will break and if it will even work good enough (probably) but no
guarrantiees

2015-11-03 6:03 GMT+01:00 Muehe <notifications@github.com>:

**Comment by Muehe** [comment]
@Steelzzz If you play with a different language client on an english server, or vice versa, it could lead to additional trouble. So if you are seeing to making this work, keep your respective client and server language in mind, as problems might be completely different between each possible combination.

**Comment by Steelzzz** [comment]
I asked a friend to try it on an english client (cuz my internet speed is crap) and he said it worked like a charm. So yeah, language is definitely the issue here.

I know what I need to do now I guess. Thank you very much for your help, guys !
