### ISSUE TITLE
Hunter Finding The Antidote Missing

### ISSUE THREAD

**Issue by Joecunni** [AeroScripts/QuestieDev#1660]
Finding the Antidote quest is not being offered by Kor'ghan

![image](https://user-images.githubusercontent.com/59258382/71480797-3b440280-27b8-11ea-9356-565b55a580cf.png)

Version 5.4.1

**Comment by BreakBB** [comment]
@Joecunni The "Quest Missing" part in your UI is not from Questie but the Azeroth Auto Pilot quest. If you look closely at your map/minimap, you see there is no icon for that quest like:

![image](https://user-images.githubusercontent.com/33514570/71543377-109da980-2972-11ea-9ebc-77c2a241a3fb.png)

You can only take this quest if you already have [Need for a Cure](https://classic.wowhead.com/quest=812/need-for-a-cure) in your quest log.
