### ISSUE TITLE
Minimap icons show after relog while turned off in the options

### ISSUE THREAD

**Issue by IcemanHHW** [AeroScripts/QuestieDev#1663]
## Bug description
Every time I log in or relog the icons on the minimap show even though it's turned off in the options.. Turning minimap icons on and off fixes it, but the problem shows up again after every loading screen. 

Edit:
After making an alt it turns out the icons show after every change. 
Accepting a new quest also makes the minimap icons show up.

## Questie version
Questie version 5.4.1

**Comment by BreakBB** [comment]
@IcemanHHW I will try to reproduce this. Should be an easy fix if I can.

**Comment by BreakBB** [comment]
@IcemanHHW Can you extract the ZIP below into `Modules/Map` replacing the existing file and try again? I think I found the issue.

[QuestieMap.zip](https://github.com/AeroScripts/QuestieDev/files/4006999/QuestieMap.zip)

**Comment by IcemanHHW** [comment]
@BreakBB tried it with and without addons and I didnt have any problems. Seems like it's fixed.
Thanks for the quick reply and fix, you're awesome :)

**Comment by BreakBB** [comment]
@IcemanHHW Thanks for coming back to this! Glad we figured it out that fast 👍
