### ISSUE TITLE
The Swamp Talker Error 

### ISSUE THREAD

**Issue by damiong28** [AeroScripts/QuestieDev#1664]
Questie: [ERROR] [QuestieQuest]: v5.4.1 - There was an error populating objectives for The Swamp Talker 2623 1 ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:757: attempt to perform arithmetic on field 'x' (a table value) 

I get this error when logging in to a horde character with The Swamp Talker quest.

**Comment by BreakBB** [comment]
@damiong28 Please use on of our issue templates next time, so we can investigate the issue more easily.

You did restart WoW after updating to v5.4.1? I remember we had corrupted spawn data for one of the mobs, but I will check again if I might have missed something. I might confuse the quest with anotherone though.

**Comment by damiong28** [comment]
@BreakBB Yes I restarted my computer and still get the error message.

Wowhead link for the quest:
https://classic.wowhead.com/quest=2623/the-swamp-talker

Screenshot of error message, quest log, and objective tracker: 
![image](https://user-images.githubusercontent.com/14994444/71542367-dbb63600-2922-11ea-8703-bc698b252253.png)

Screenshot of the map (I don't see the objective marker here)
![image](https://user-images.githubusercontent.com/14994444/71542403-5717e780-2923-11ea-9ec6-7ab8958e49a9.png)

**Comment by BreakBB** [comment]
Please extract the ZIP below and paste the file into `Database/Corrections` replacing the existing one. It was another quest and my fault, because again it has been corrupted data instead of just adding more spawns.

[QuestieNPCFixes.zip](https://github.com/AeroScripts/QuestieDev/files/4006976/QuestieNPCFixes.zip)

**Comment by damiong28** [comment]
The error is gone now! Thanks for the fix.
