### ISSUE TITLE
Quests given from Rezlak in Durotar doesn't show up as Alliance

### ISSUE THREAD

**Issue by tsvenbla** [AeroScripts/QuestieDev#1665]
## Bug description
There are two quests offered by [Rezlak](https://classic.wowhead.com/npc=3293/rezlak)  in Durotar:

1. [Winds in the Desert](https://classic.wowhead.com/quest=834/winds-in-the-desert)
2. [Securing the Lines](https://classic.wowhead.com/quest=835/securing-the-lines)

These quests can be done both on Alliance and Horde, but they never showed up on the map for my Alliance character. 

I do not use any map addon that could screw it up. My character level is 60, but I have enabled the option to show all lower-level quests.

## Screenshots
![Annotation 2019-12-28 103351](https://user-images.githubusercontent.com/59305921/71541172-ceae3c80-294c-11ea-8d8d-552803126c10.png)
The quests should be shown at the red marker. The only one currently showing up is related to Winter Veil by the gates of Orgrimmar.

## Questie version
5.4.1

**Comment by BreakBB** [comment]
@tsvenbla Thanks for the report. Should be an easy fix!
