### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by wrexhavik** [AeroScripts/QuestieDev#1666]
logging into WoW classic on 12/19/19.  Get following error message:

Date: 2019-12-29 08:31:00
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Database\spawnDB.lua line 309:
   attempt to perform arithmetic on a nil value
Debug:
   Questie\Database\spawnDB.lua:309: in main chunk
Locals:
QuestieDB = <table> {
 FactionGroup = "Horde"
 _NPCCache = <table> {
 }
 GetQuestsByName = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:557
 _ZoneCache = <table> {
 }
 questKeys = <table> {
 }
 _GetSpecialNPC = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:471
 private = <table> {
 }
 GetCreatureLevels = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:439
 GetQuestsByZoneId = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:604
 npcKeys = <table> {
 }
 objectKeys = <table> {
 }
 objectData = <table> {
 }
 HideClassAndRaceQuests = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:684
 DeleteGatheringNodes = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:658
 questData = <table> {
 }
 GetNPC = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:507
 GetNPCsByName = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:576
 ItemLookup = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:81
 GetObject = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:90
 _ObjectCache = <table> {
 }
 Initialize = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:68
 GetQuest = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:162
 _ItemCache = <table> {
 }
 GetItem = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:115
 _QuestCache = <table> {
 }
}
(*temporary) = <table> {
 2 = <table> {
 }
 3 = <table> {
 }
 6 = <table> {
 }
 30 = <table> {
 }
 36 = <table> {
 }
 38 = <table> {
 }
 40 = <table> {
 }
 43 = <table> {
 }
 46 = <table> {
 }
 48 = <table> {
 }
 54 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 66 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 74 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 89 = <table> {
 }
 92 = <table> {
 }
 94 = <table> {
 }
 95 = <table> {
 }
 97 = <table> {
 }
 98 = <table> {
 }
 99 = <table> {
 }
 100 = <table> {
 }
 103 = <table> {
 }
 113 = <table> {
 }
 114 = <table> {
 }
 115 = <table> {
 }
 116 = <table> {
 }
 117 = <table> {
 }
 118 = <table> {
 }
 119 = <table> {
 }
 121 = <table> {
 }
 122 = <table> {
 }
 123 = <table> {
 }
 124 = <table> {
 }
 125 = <table> {
 }
 126 = <table> {
 }
 127 = <table> {
 }
 152 = <table> {
 }
 154 = <table> {
 }
 190 = <table> {
 }
 196 = <table> {
 }
 198 = <table> {
 }
 202 = <table> {
 }
 206 = <table> {
 }
 210 = <table> {
 }
 212 = <table> {
 }
 218 = <table> {
 }
 222 = <table> {
 }
 226 = <table> {
 }
 228 = <table> {
 }
 232 = <table> {
 }
 234 = <table> {
 }
 238 = <table> {
 }
 240 = <table> {
 }
 244 = <table> {
 }
 246 = <table> {
 }
 248 = <table> {
 }
 250 = <table> {
 }
 252 = <table> {
 }
 264 = <table> {
 }
 268 = <table> {
 }
 272 = <table> {
 }
 276 = <table> {
 }
 284 = <table> {
 }
 288 = <table> {
 }
 300 = <table> {
 }
 304 = <table> {
 }
 308 = <table> {
 }
 328 = <table> {
 }
 332 = <table> {
 }
 340 = <table> {
 }
 344 = <table> {
 }
 348 = <table> {
 }
 352 = <table> {
 }
 356 = <table> {
 }
 372 = <table> {
 }
 376 = <table> {
 }
 384 = <table> {
 }
 392 = <table> {
 }
 412 = <table> {
 }
 416 = <table> {
 }
 424 = <table> {
 }
 428 = <table> {
 }
 432 = <table> {
 }
 436 = <table> {
 }
 440 = <table> {
 }
 448 = <table> {
 }
 452 = <table> {
 }
 456 = <table> {
 }
 460 = <table> {
 }
 464 = <table> {
 }
 468 = <table> {
 }
 472 = <table> {
 }
 476 = <table> {
 }
 480 = <table> {
 }
 488 = <table> {
 }
 500 = <table> {
 }
 504 = <table> {
 }
 520 = <table> {
 }
 544 = <table> {
 }
 568 = <table> {
 }
 576 = <table> {
 }
 584 = <table> {
 }
 513 = <table> {
 }
 521 = <table> {
 }
 545 = <table> {
 }
 569 = <table> {
 }
 257 = <table> {
 }
 261 = <table> {
 }
 265 = <table> {
 }
 269 = <table> {
 }
 273 = <table> {
 }
 277 = <table> {
 }
 285 = <table> {
 }
 289 = <table> {
 }
 297 = <table> {
 }
 305 = <table> {
 }
 313 = <table> {
 }
 325 = <table> {
 }
 329 = <table> {
 }
 341 = <table> {
 }
 345 = <table> {
 }
 349 = <table> {
 }
 377 = <table> {
 }
 381 = <
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasLootClassic, vv1.4.3
  AtlasLootClassicData, vv1.4.3
  AtlasLootClassicDungeonsAndRaids, vv1.4.3
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.11.58
  ClassicThreatMeter, v1.10
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  ElvUI, v1.18
  FishingBuddy, v0.7 Beta 2
  HealBotData, v1.13.3.0
  HealBoten, v1.13.3.0
  HealBotOptions, v1.13.3.0
  Immersion, v1.2.2
  MissingTradeSkillsList, v1.13.27
  Questie, v5.4.0
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=26e)

**Comment by BreakBB** [comment]
@wrexhavik Please use one of our issue templates next time. Which version of Questie are you using?
And which quests did you have at the point where the error occured?

**Comment by BreakBB** [comment]
Closing because of the lack of information. This should also be fixed with the latest versions.
