### ISSUE TITLE
Gazz'uz Drop Quest

### ISSUE THREAD

**Issue by Grtwhite** [AeroScripts/QuestieDev#1667]
Missing drop quest in Skull Rock from Gazz'uz.  Eye of Burning Shadow which starts Burning Shadows quest.

**Comment by Gogo1951** [comment]
https://github.com/AeroScripts/QuestieDev/pull/1669

**Comment by Gogo1951** [comment]
Hey @Grtwhite,

Good catch, I thought I had added this in the last batch but I was just doing it mostly from memory and... bound to miss one or two. Thanks!
