### ISSUE TITLE
active quest tracker

### ISSUE THREAD

**Issue by kageAkudo** [AeroScripts/QuestieDev#1668]
## Bug description
when i get a quest with a long text it moves the active quest tracker out of place towards middle of screen. when i remove the quest it does not move back unless i restart the game or turn Questie off and on

## Screenshots
![Screenshot (16)](https://user-images.githubusercontent.com/59347064/71564317-ca218980-2aee-11ea-8d54-e2a646c2c706.png)
![Screenshot (19)](https://user-images.githubusercontent.com/59347064/71564318-cf7ed400-2aee-11ea-8d37-e0f09e6da0d3.png)

## Questie version v5.4.1
<!--

**Comment by Gogo1951** [comment]
Seems like a dupe of https://github.com/AeroScripts/QuestieDev/issues/1612

**Comment by BreakBB** [comment]
Duplicate of #1612
