### ISSUE TITLE
Tracker disappeared

### ISSUE THREAD

**Issue by norecha** [AeroScripts/QuestieDev#167]
And I could not bring it back. I'm talking about the list of quests showing in your progress in main UI. One you shift click to add quests. Is there a way to reset it's position somehow. I'm forced to reinstall at this point.
Actually reinstalling did not solve it either. idk how to fix it

**Comment by Schaka** [comment]
Try changing your UI scale (or turning it on and off). 
Typing /questie should give you an option to reset the tracker position.

**Comment by Muehe** [comment]
Did you delete your WTF folder when reinstalling? Note that this will delete all settings and saved variables, like finished quests, for all addons and WoW itself. You can try to fix the position manually by finding the right setting in the .lua file in directory WTF\Account\ACCOUNTNAME\SERVERNAME\CHARACTERNAME\SavedVariables

**Comment by norecha** [comment]
@Schaka 
scale changes the actual guide window, not the tracker. and there is no option to reset tracker position
/questie
lowlevel
professions
getpos
complete

@Muehe 
Thanks I was trying to figure out where it was stored, it was out of screen somehow, now fixed

**Comment by Lauttie** [comment]
I need a little more help.  I set the position to 10 and 10 and it is still not visible.  What should it be?

**Comment by Schaka** [comment]
("CENTER", 0, 0)

Remember to set it in the SavedVariables, not in the addon code. If that doesn't work, make sure you are actually tracking quests.

**Comment by Lauttie** [comment]
Alright, I reinstalled and deleted the file completely.  That fixed it.  Thanks!

**Comment by Lauttie** [comment]
BTW, it seems to disappear in battle grounds and then doesn't come back when I get out.

**Comment by TheGreyMouser** [comment]
Editing this file
C:\World of Warcraft Classic\WTF\Account\AccountName\SavedVariables\Questie.lua
*these 2 variables* to:
["xOfs"] = 10,
["yOfs"] = 10,
Fixed it for me.  Made the questie screen visible again so it could be moved.  

I suspect what broke it, was me having the questie box selected and moving my pointer off screen.  (DOH!)
