### ISSUE TITLE
Latin American spanish (esMX) database

### ISSUE THREAD

**Issue by woopydalan** [AeroScripts/QuestieDev#1673]
## Description
Hi, I know you guys are using the spanish database from wowhead to gather your information for both the esES and esMX clients. I know that database gets its information from the esES client. The esMX client from my experience is probably 80-85% the same as the esES, but nonetheless there are differences. I found a database that is not from wowhead that appears to use the data from the esMX client. It might be worth investigating if you can use your crawler to gather information from there for the esMX client.

## Wowhead link
https://db.wowlatinoamerica.com/

## Screenshots
N/A

## Questie version
All versions

**Comment by BreakBB** [comment]
@woopydalan Nice finding. This would actually require some in detail checking of the website you linked, but would probably been usable! Can't say though when I will able to invest the time.

**Comment by drejjmit** [comment]
Does that site have a classic section? Looks to be retail data.

**Comment by woopydalan** [comment]
@drejjmit No, I believe it is WoTLK. However, I believe since its pre-cata, the majority of quest names should be unchanged.

**Comment by woopydalan** [comment]
@BreakBB Looks awesome, I'll go through in game and change anything I find. There are a few things that might be different. For example, I know Gryan Stoutmantle was a quest giver in WoTLK grizzly hills and they renamed him, so that might have been reflected from the DB. Glad it was able to work though.

**Comment by BreakBB** [comment]
@woopydalan Yeah I also think some translations changed after Classic. It was the same with German, so that will probably require some changes by hand.
