### ISSUE TITLE
Map quest icons are bugged

### ISSUE THREAD

**Issue by Scifibookguy** [AeroScripts/QuestieDev#1676]
## Bug description
As can be seen from the screenshots below, the quest icons for some quests are bugged, as they are showing off of the map to the north of the Blasted Lands. When the Swamp of Sorrows map is viewed, there are no quest icons. My current quests for Blasted Lands can be viewed on the right side of the screenshots. The person I group with also has this issue, so I know it's not just me.

## Screenshots
![BlastedLandsMap](https://user-images.githubusercontent.com/59448593/71683036-64880400-2d5f-11ea-9a9b-2d59102e048b.jpg)
![SoSMap](https://user-images.githubusercontent.com/59448593/71683048-6c47a880-2d5f-11ea-921f-3ef30166014a.jpg)

## Questie version
5.4.1

**Comment by BreakBB** [comment]
@Scifibookguy Can you tell which quest had the icons off the map? That would increase the investigation on this.

**Comment by Scifibookguy** [comment]
The icons were for the two Dramethyst crystal quests, the level 55 orange quests that you see.

**Comment by BreakBB** [comment]
@Scifibookguy Thanks for coming back to this so quickly. I will check our data to see if there are any spawns that need correction.

**Comment by BreakBB** [comment]
I've updated some spawns. The thing with these quests is: There are NPCs like the "Nethergarde Miner", "Nethergarde Engineer" and "Nethergarde Foreman" which are in the cave/mine at `57.8 - 14.2`. And their coords are actually out of the map itself.

**Comment by Scifibookguy** [comment]
I checked it out, and those icons are definitely for the Alliance NPCs inside the mine. Sorry about reporting this as an error :(

**Comment by BreakBB** [comment]
@Scifibookguy Don't be sorry about it! We really appreciate every feedback and report we get, so we can keep improving Questie!
