### ISSUE TITLE
The Barrens Oases breadcrumb

### ISSUE THREAD

**Issue by Zardilann** [AeroScripts/QuestieDev#1679]
The Barrens Oases breadcrumb is not registering if the main quest has been picked up, and still displays as available after The Forgotten Pools has been accepted.

https://classic.wowhead.com/quest=886/the-barrens-oases

**Comment by BreakBB** [comment]
@Zardilann Could you tell which version of Questie you're using? This should have been fixed since v5.3.0

**Comment by Zardilann** [comment]
5.41

**Comment by BreakBB** [comment]
@Zardilann Can you run the following commands and report the output: `/dump IsQuestFlaggedCompleted(870)` and `/dump IsQuestFlaggedCompleted(886)`

Also a screenshot of the quest still showing up on the map would be great. I didn't find an issue with our data yet.

**Comment by Zardilann** [comment]
/dump IsQuestFlaggedCompleted(870) shows true
/dump IsQuestFlaggedCompleted(886) shows false

I'm afraid I already passed the point and finished the chain. I'll rereport if I encounter it on an alt.

**Comment by BreakBB** [comment]
@Zardilann So "The Barrens Oases" isn't showing for you in Thunder Bluff anymore?

**Comment by Zardilann** [comment]
True, it went away at some point, but was there when I had accepted The Forgotten Pools.

**Comment by BreakBB** [comment]
@Zardilann Thanks for checking again. It's most likely related to #860 .

@Muehe is about to rewrite some major parts which are most likely connected to this which should help to prevent such issues in the future. Sorry for the trouble.

**Comment by Zardilann** [comment]
That might be it. I've run into it not updating once or twice, great to see you're looking into it!
