### ISSUE TITLE
The Hunter's Path - Night Elf

### ISSUE THREAD

**Issue by Nerillida** [AeroScripts/QuestieDev#1681]
Quest 6721 starts from Olmin Burningbeard in IF, not Regnus Thundergranite - tested with two characters. Olmin Burningbeard 70.87,83.63
Quest 6722 starts from Grif Wildheart Kharanos 45.81,53.04.
Quest 6071 is as you have.
Quest 6072 - not available, as per you.
Quest 6073, Einris Brightspear (SW)

Turning in one records them as all turned in on the server.

**Comment by BreakBB** [comment]
@Nerillida Thank you very very much for taking your time to investigate these quests! ❤️
