### ISSUE TITLE
List the name of the Dungeon

### ISSUE THREAD

**Issue by njbaker7** [AeroScripts/QuestieDev#1682]
## Description

I think it would be helpful to list which quest the dungeon is located in on the tool tip when you hover over a quest.

**Comment by BreakBB** [comment]
@njbaker7 I think adding more information to the quest tooltip isn't a really good idea. If you like to get all quests before entering a dungeon you can use the Journey:

![image](https://user-images.githubusercontent.com/33514570/71769258-115caf80-2f1f-11ea-8427-05773c3f7f1a.png)

**Comment by njbaker7** [comment]
Thank you! that is very helpful.
