### ISSUE TITLE
The Hunter's Path - Dwarf

### ISSUE THREAD

**Issue by Nerillida** [AeroScripts/QuestieDev#1683]
Quest 6074 starts from Olmin Burningbeard in IF, not Regnus Thundergranite
Quest 6075 starts from Tristane Shadowstone who walks near Brewnall Village in Kharanos
Coords 30.23,47.24 30.84,48.40 30.93,50.66 31.31,44.46 30.78,45.40
Quest 6076 starts from Einris Brightspear - you have this
Turning in one records them as all turned in on the server.

These are all breadcrumbs and blocked by accepting the follow on quest.

**Comment by BreakBB** [comment]
@Nerillida Once again: Thank you very much for looking into more of those quests. Looks like a lot of these quests changed from vanilla/private servers to classic.
