### ISSUE TITLE
Deep Sea Salvage

### ISSUE THREAD

**Issue by woopydalan** [AeroScripts/QuestieDev#1686]
## Description
Questie is showing the Logs and Maps for both ships at the same location. The Maiden's Folly locations are correct, but the Spirit of Silverpine locations are just duplicate location of their Maiden Folly counterparts and are not in the correct position.

## Wowhead link
https://classic.wowhead.com/quest=662/deep-sea-salvage

## Screenshots
![Screenshot from 2020-01-05 05-34-07](https://user-images.githubusercontent.com/29320668/71778837-a8bb1480-2faa-11ea-9c46-7f8e7247f140.png)

## Questie version
v5.4.1

**Comment by BreakBB** [comment]
@woopydalan If you didn't complete this quest yet: Could you try a `/reload`?

**Comment by woopydalan** [comment]
@breakBB I already turned it in

**Comment by BreakBB** [comment]
Hmm... There might be a problem with the Blizzard API not returning the correct information in time, but I never encountered it. Looks fine for me:

![image](https://user-images.githubusercontent.com/33514570/71780352-e2e3e080-2fc1-11ea-9b51-3ca605bad100.png)
