### ISSUE TITLE
Map pin layering issue

### ISSUE THREAD

**Issue by bitingsock** [AeroScripts/QuestieDev#1687]
## Bug description
I'm not sure if this is specifically an issue with how questie handles pins or if it is an underlying HBD issue. I author [FlightQueue](https://www.curseforge.com/wow/addons/flightqueue). A fundamental function is when I create mixins of the flight points on the map using CreateFromMixins(MapCanvasDataProviderMixin), but even if I set the frame levels to the highest they can go (as happens when holding the Alt key in my addon) they still get covered by the questie pins. Oddly, this is only the case for Questie pins that were populated before mine. If I open the map fast enough after a reload before my quest log gets parsed onto the map by Questie then the pins that are generated respect the frame levels correctly. Similarly, if I toggle back and forth one of the Questie options that resets the pin drawing (i.e. "Show repeatable quests on map") then all the pins that are drawn by Questie now get correctly overlayed by mine, that is, until I open the map again and it is back to not working. Additionally, this only seems to be the case for the quest accept and turn-in pins, as the objective pins do get overlayed correctly. Finally, before one of your major versions, maybe v5, I think this was working correctly. I could try to narrow that down if it helps.

## Screenshots
![image](https://user-images.githubusercontent.com/6302101/71780210-71ca0c00-2f74-11ea-9931-260fecd1b847.png)
This is not pressing anything.
![image](https://user-images.githubusercontent.com/6302101/71780224-a76ef500-2f74-11ea-91a6-0014ae3f51e5.png)
This is when I press Alt key and raises the flight point pin to the FULLSCREEN_DIALOG strata. Notice it overlays the player pin.
![image](https://user-images.githubusercontent.com/6302101/71780268-4d226400-2f75-11ea-8662-c3fb2acb1afc.png)
An example where I loaded my mixin before the quest log was parsed to the map and my higher frame strata correctly overlays when holding Alt key.

## Questie version
5.4.1

**Comment by Logonz** [comment]
Hello!
Framelayering has always been a real issue. We are going to merge into the regular framelevel system, My thinking was that questienotes are often more important than things like FPs etc!

We set the frame level a little differently and at a more low level when we should instead set it using the framemap level.

I'll look into making a better way and follow convention better.

**Comment by bitingsock** [comment]
Ok, good to know. As long as I'm not crazy. Was getting confused why my function didn't do what I expected.

**Comment by AeroScripts** [comment]
v6.0.5
