### ISSUE TITLE
A Talking Head

### ISSUE THREAD

**Issue by Grtwhite** [AeroScripts/QuestieDev#1688]
Looks like the quest A Talking Head is missing from the list.  Drop off of Fenris Isle

BTW thanks for the addon one of the best in the game.

## Wowhead link
https://classic.wowhead.com/item=3317/a-talking-head

**Comment by Gogo1951** [comment]
Hey @Grtwhite ,

There are about 35 quests in the game that drop from items that at "zone drops" -- like the various chicken beacons in Hinterlands, Tanaris, and Feralas, for example -- that drop from a bunch of different sources. The quest you listed drops from one of 5 mob types, and if we were to add all of them to the map it'd be really cluttered. At present, only unique mob drops are shown.

This may change in the future. We need a better way to show "zone quests" - you can see a short write-up here. https://github.com/AeroScripts/QuestieDev/issues/317#issuecomment-564613358

Cool to close this ticket?
