### ISSUE TITLE
[3.0]  Questie\Questie.lua:563 attempt to index global 'center' (a nil value)

### ISSUE THREAD

**Issue by Cymerline84** [AeroScripts/QuestieDev#169]
Hello, 
I have a bug with the quest "Bitter Rivals" in Dun Morogh and Find the Lost Guards " in Elwyn forrest. When I take the quest Bitter rivals I have this error lua "Questie \ Questie.lua: 563 Attempt to global index 'center' (a nil value).
Questie deactivates and my bug interface.

Screen joint.

![sans titre](https://cloud.githubusercontent.com/assets/16113902/11525151/fbdc8ec0-98d0-11e5-8cb7-ae7ff16f454a.jpg)

**Comment by Cymerline84** [comment]
Hi, Bug identical with the quest " The lost pilot " in North gate outpost in Dun Morogh.

**Comment by Cymerline84** [comment]
The bug also occurs with the quest "Buzzbox" in Darkshore. The bug appears once complete objects for not taking quest quest. And also when you take the quest "A Watchful Eye" was the Tower Azora in Elwyn forrest.

**Comment by Dyaxler** [comment]
I just recently completed those quests on my Priest with Questie. I didn't encounter these errors. Please try the latest version. There were several code improvements that was done before my commit last night and I've been running it for over 24 hours without issue.
