### ISSUE TITLE
[52] Enticing Negolash

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#1691]
## Description
[52] Enticing Negolash (619) requires you to be on [50] Facing Negolash (8554). 
Showing up even if you're not on that quest.

## Wowhead link
https://classic.wowhead.com/quest=619/enticing-negolash
https://classic.wowhead.com/quest=8554/facing-negolash

## Screenshots
![image](https://user-images.githubusercontent.com/15526476/71786851-d0dd5e80-3010-11ea-97cf-8c6e9e558392.png)

## Questie version
v5.4.1

**Comment by BreakBB** [comment]
Nice, I've seens that quest a couple of times and never thought about it being wrong. Should be an easy fix.
