### ISSUE TITLE
The preference for hiding a quest's icons is reset

### ISSUE THREAD

**Issue by isaklilja** [AeroScripts/QuestieDev#1692]
## Bug description

1. In the quest tracker, right click a quest and select to hide the quest icons on the map.
2. Open the map. The quest icons should be hidden. Now click the enable/disable questie button in the top. Disable questie then enable it again.

Result: The quest icons are shown again. If you right click the quest in the tracker again, it now says "show icons" even though the icons are already showing.
Expected: The quest icons should remain hidden.

Version: 5.4.1

**Comment by Gogo1951** [comment]
Just tested, it's working fine for me. 5.4.1. I right click to hide a quest, I sign out. I sign back in, and the quest is still hidden.

**Comment by BreakBB** [comment]
@Gogo1951 I can reproduce this. If you click the "Hide Questie" and "Show Questie" on the world map the icons are shown again.
