### ISSUE TITLE
Arathi Highlands - mislabelled area

### ISSUE THREAD

**Issue by Coreston** [AeroScripts/QuestieDev#1693]
In Arathi Highlands, the quest Worth Its Weight in Gold is showing that Witherbark Tusks can be gathered in Boulder'Gor.  There are no trolls there.  This is mislabelled on the minimap and on the main map.

**Comment by Gogo1951** [comment]
Hey, small point on this... there are in fact trolls in the location listed. But not many.

You're better off going to the SE side of the map. But... there are some in the hills by the ogres. It's not wrong, it just isn't efficient. (=

Not sure how the guys normally handle that.

**Comment by BreakBB** [comment]
@Coreston Sorry for your trouble, but @Gogo1951 is right. There are trolls in that area.

These are [Witherbark Shadowcaster](https://classic.wowhead.com/npc=2553/witherbark-shadowcaster), [Witherbark Troll](https://classic.wowhead.com/npc=2552/witherbark-troll) and also [Witherbark Witch Doctor](https://classic.wowhead.com/npc=2555/witherbark-witch-doctor).

For some users it might be a good idea to kill those trolls, while the other area is overfarmed or to combine it with another quest. So nothing to change for us here. Thanks for your report though! We appreciate every help we can get 👍
