### ISSUE TITLE
[classic 8 jan 20] error clicking show questie on world map

### ISSUE THREAD

**Issue by emanueol** [AeroScripts/QuestieDev#1694]
Date: 2020-01-08 19:34:30
ID: 1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua line 73:
   attempt to index local 'trackerHiddenQuests' (a nil value)
Debug:
   ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:73: ToggleNotes()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
self = <table> {
 GetAllQuestIds = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:457
 AcceptQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:327
 HideQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:288
 ToggleNotes = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:61
 PopulateQuestLogInfo = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:890
 AbandonedQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:401
 SmoothReset = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:200
 ShouldQuestShowObjectives = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:501
 PopulateObjectiveNotes = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:850
 UpdateHiddenNotes = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:240
 CalculateAvailableQuests = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1425
 AddAllNotes = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:169
 DrawAllAvailableQuests = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1317
 GetRawLeaderBoardDetails = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:299
 availableQuests = <table> {
 }
 UnhideQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:293
 GetAllQuestIdsNoObjectives = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:482
 GetAllQuestObjectives = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:911
 private = <table> {
 }
 PopulateObjective = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:669
 AddFinisher = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:544
 IsComplete = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:514
 UpdateObjectiveNotes = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:532
 UpdateQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:435
 CompleteQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:371
 NotesHidden = true
 Initialize = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:49
 GetAllLeaderBoardDetails = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1140
 ForceToMap = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:639
 ClearAllNotes = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:127
 Reset = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:184
}
desiredValue = nil
questieGlobalDB = <table> {
 questieLocaleDiff = false
 trackerShowQuestLevel = true
 trackerbindSetTomTom = "ctrlleft"
 alwaysGlowMinimap = false
 enableMapIcons = true
 questObjectiveColors = false
 maxLevelFilter = 2
 trackerShowCompleteQuests = true
 eventScale = 1.350000
 dbmHUDRadius = 3
 DBMHUDRefresh = 0.030000
 trackerColorObjectives = "white"
 enableIconLimit = false
 trackerbindUntrack = "shiftleft"
 showBlizzardQuestTimer = true
 mapCoordinatesEnabled = false
 nameplateTargetFrameY = 25
 availableScale = 1.300000
 nameplateTargetFrameEnabled = true
 globalScale = 0.700000
 enableAvailable = true
 alwaysGlowMap = true
 trackerEnabled = false
 monsterScale = 1
 fadeOverPlayerLevel = 0.500000
 dbmHUDShowLoot = false
 trackerSortObjectives = "byComplete"
 globalMiniMapScale = 0.700000
 nameplateScale = 1
 nameplateTargetFrameX = -30
 minLevelFilter = 4
 dbmHUDShowAlert = true
 nameplateEnabled = true
 enableTurnins = true
 questMinimapObjectiveColors = false
 trackerFontSizeHeader = 13
 nameplateX = -17
 stickyDurabilityFrame = true
 mapShowHideEnabled = true
 enableMiniMapIcons = false
 objectScale = 1
 trackerbindOpenQuestLog = "left"
 dbmHUDShowQuest = true
 loo
AddOns:
  KalielsTracker, v0.2.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdiBags, vv1.9.17-classic
  AskMrRobotClassic, v1
  Atlas, vv1.46.04.11303.01
  AtlasBattlegrounds, vv1.45.00.11302.00
  AtlasClassicWoW, vv1.45.01.11303.05
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasTransportation, vv1.45.00.11302.00
  AtlasLootClassic, vv1.4.4
  AtlasLootClassicData, vv1.4.4
  AtlasLootClassicDungeonsAndRaids, vv1.4.4
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.11.59
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.27
  Bartender4, v4.8.9
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterNotes, v8.2.5
  CharacterStatsClassic, v2.9
  ClassicBlacklist, v1.1.5
  ClassicFriendBtn, v1
  ClassicThreatMeter, v1.10
  ClassTrainerPlus, v0.6-beta
  CoolLevelUp, v1.13.0.2
  DBMCore, v1.13.28
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1303r001
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4110
  FleecingTip, v113.1577(211219)
  GatherMate2, v1.45.5
  GatherMate2MapButton, v1.1
  GatherNotify, v1.6
  GatherTrackingReminder, v1.0
  GlobalIgnoreList, v1.13.3
  Grail, v106
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v27178
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v29297
  Grid2, vr943
  Grid2LDB, vr943
  Grid2RaidDebuffs, vr943
  GuildRosterManager, v1.831
  GuildSearch, v8.2.1
  GuildTooltip, v2.11.9
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemAutocomplete, v1.0.4
  ItemRack, v
  ItemTooltipProfessionIcons, v1.1.5
  KiwiItemInfo, vv2.3.4
  LeatrixMaps, v1.13.43
  LibClassicDurations, v1.44
  MaxCam, vv2.4.2
  NugRunning, v1.13.34
  OmniCC, v8.3.1
  OPie, vAncient Walnut 6
  Pawn, v2.3.15
  Prat30, v3.7.45
  Prat30Libraries, v
  Puggle, v2.8
  PugLoot, vv1.1.1
  Quartz, v3.5-classic-5
  Questie, v5.5.0
  RCLootCouncilClassic, v0.5.1
  RealMobHealth, v2.17
  RecipeRadarClassic, v1.0.0.23
  RollTrackerClassic, v2.10
  SexyMap, vv4-classic
  ShadowedUnitFrames, vv4.2.3-Classic
  SimpleDing, vv1.1.1
  SimpleItemLevel, v1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SmartQuest, v1.18.1
  StatPriorityTracker, v0.0.3b
  Storyline, v1.13.2.2
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TalentSequence, v2.0
  TidyPlatesThreatPlates, v1.2.8
  TipTac, v19.03.31
  TipTacItemRef, v19.03.31
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicGuild, v1.0.0.3
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRecZone, v1.0.0.5
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicRestPlus, v1.0.0.1
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  TitanProfession, vv1.2-classic
  TitanProfessionsMulti, v1.3
  TitanSkills, v1.7.0
  TitanSocial, v1.13.3
  TomTom, vv11303-1.0.9
  TownsfolkTracker, v1.0.7
  VendorPrice, v1.3.0
  WeakAuras, v2.15.5
  WhatsTraining, v1.8.7
  WhereToGatherClassic, v1.0
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=dc2)

**Comment by emanueol** [comment]
Found workaround to solve the problem:
esc > interface options > addons > questie > tracker 
and enable and disable the checkbox [ ] Enable The Questie Tracker

now in world map when i click Show Questie, no longer gives error, and i can see questie icons.

Hope this may help others.

Budha

**Comment by BreakBB** [comment]
@emanueol Thanks for your report. I think I already found the issue and fixed it. Could you grab the file below and place it in `Modules/Quest` replacing the existing file? Would be great if you could verify that this fixes your problem.

[QuestieQuest.zip](https://github.com/AeroScripts/QuestieDev/files/4039271/QuestieQuest.zip)
