### ISSUE TITLE
Disable party quest progress in tooltips

### ISSUE THREAD

**Issue by Klala** [AeroScripts/QuestieDev#1695]
I would like to have an option to disable the party progress in tooltip but keep my own progress in the tooltip if possible please.

**Comment by Gogo1951** [comment]
Hey @Klala 

Can you give me a use case for this? WoW is an MMO, right, we play because of other people. Isn't it useful to see what your party needs? Given the backlog, and limited number of volunteer dev hours the project has, hard to prioritize an issue without a strong use case. Thanks!

**Comment by Klala** [comment]
@Gogo1951 Uh, didn't think I'll need to provide such a thing.
Well, the reason for this request is because when I went to RFC with my mage for example, my group had a quest to pick up tomes from some adds inside as well as me. The tooltip was so long I couldn't tell who had what and how many.
Now, sure, wow is an mmo, but sometimes when everybody in your group (or raid, I don't want to imagine how that would look on my screen, yikes) you have too much information to look at and sometimes you might just wanna know about your own quest. 
Of course, this is your decision how much priority to give this request. I am merely suggesting that there should be an option to disable this if one so chooses.

**Comment by Gogo1951** [comment]
Hey @Klala, thanks! Normally when someone puts in a feature request they tell a bit of a user story along with it to help people prioritize. This helps, it wasn't clear why you wanted it. Lots of things could be configurable, but there's a cost in time to them. Someone could say, "Oh, I want the background to be blue," or "Why can't I make the fonts bigger..." all valid requests that help that user, developers just need context to help understand how to prioritize that request vs. all of the requests. Thanks for sharing, cheers!

**Comment by AeroScripts** [comment]
v6.0.5 includes a new tab for these sorts of options, it's lacking right now but in future updates there will be more party progress options added

**Comment by t0senWho** [comment]
> 
> 
> Hey @Klala
> 
> Can you give me a use case for this? WoW is an MMO, right, we play because of other people. Isn't it useful to see what your party needs? Given the backlog, and limited number of volunteer dev hours the project has, hard to prioritize an issue without a strong use case. Thanks!
 
100% backpadler

**Comment by bucketss** [comment]
this would be an excellent feature

**Comment by Sattva-108** [comment]
Payo is asking how to remove party progress on map / tooltip
