### ISSUE TITLE
Owatanka Quest Path

### ISSUE THREAD

**Issue by Sandstome** [AeroScripts/QuestieDev#1699]
The quest location / movement path of Owatanka [24] (Horde) seems to only reference one of his two possible locations with the other being south of Camp Taurajo around 45,60

**Comment by BreakBB** [comment]
@Sandstome Thanks for the report. I will investigate this. Please use one of our issue templates next time so we can fix things faster.

**Comment by Gogo1951** [comment]
Correct, he spawns on either the east or west side of the road. When I did this on my horde toon I must have got lucky, he was right where the marker put him.

https://classic.wowhead.com/npc=3473/owatanka
