### ISSUE TITLE
Click menu on exclamation mark to manual complete a quest

### ISSUE THREAD

**Issue by cmbijpost** [AeroScripts/QuestieDev#170]
When Questie doesnt observe you completing a quest it still shows it on the map as available. The whole Questie Complete thing is ok, but the quest names are complex sometimes. It would be enough to just copy the quest name on click or something, but a context menu to manual complete a quest would be even nicer :)

**Comment by ArtemisHerdmann** [comment]
This would be great, I don't use this addon because all the quests in the starting zone I already did are still there so it confuses me.

**Comment by Schaka** [comment]
Fixed in 13a4f6c0767a27443dba1ee13b3599d7f07990cb
