### ISSUE TITLE
BWL Attunment Quest Not Showing

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1704]
## Bug description

Now that BWL attunement is out, I would expect to see it. I thought it just wasn't added to the database, but I see it in the corrections file.

https://classic.wowhead.com/quest=7761/blackhands-command

Is there something else that's blocking this from showing up? In the corrections file, I see:

```
        [7761] = {
            [QuestieDB.questKeys.startedBy] = {{9046},nil,{18987}},
        },
```

**Comment by drejjmit** [comment]
Shows up if you have latest version

![image](https://user-images.githubusercontent.com/15526476/72460414-0af6ef00-37cd-11ea-8133-876134de9110.png)

**Comment by Gogo1951** [comment]
Yeah, I ran my Druid in after my warrior Cleared UBRS. Derp. Thanks!
