### ISSUE TITLE
Quest: Guarded thunderbrew barrel

### ISSUE THREAD

**Issue by Goodlyont** [AeroScripts/QuestieDev#1714]
I have this quest showing as needing completion, but can't acquire it from the quest giver; he doesn't have a yellow exclamation mark. I have alts so am not sure/can't remember if I completed earlier quests or not re: Bitter Rivals and Distracting Jarven. I have gone back to Marleth Barleybrew and she doesn't have any current quests showing for me. I have read the other posts here regarding this quest and they don't seem to be the same issue I have? Help! With many thanks in advance!
[Sorry can't see what version of Questie I have but I got it when WOW Classic started, if that's any help. Hovering over icon tells me nothing, sorry. Also I am inept technologically speaking ...].

**Comment by Gogo1951** [comment]
You have to buy a brew from the innkeeper upstairs, then give it to the guy. It's not, strictly speaking, a quest objective. Once he's distracted you can turn in the quest to the barrel.

**Comment by Goodlyont** [comment]
I'd love to, I have thunder ale in my bags. I can't open anything with
him. He doesn't have a yellow exclamation mark over him, there is only
one on the map? Sorry to be a pest.

----- Original Message -----

**Comment by BreakBB** [comment]
@Goodlyont If there is no version like "v5.5.1" showing when you hover over the minimap icon that means your Questie is some versions old.

It would be great if you could take the latest release and try that. Maybe we changed/fixed your issue after your current version.

You can either use the Twitch client for updating Questie or just download the ZIP file from curseforge or [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v5.5.1) and simply extract it in the AddOns folder (replace the existing files).

**Comment by Gogo1951** [comment]
Have you tried talking with him, when you have the Thunder Brew?

Same as the quest in BRD to activate Golem (where you give 10 drinks to the dwarf to start the fight), there's no great in-game ! or ? to show you how to do it... you just sort of have to do it. Apologies it's not more clear, not sure it's something Questie can fix though.

**Comment by Goodlyont** [comment]
How embarrassing. It was this, that I hadn't updated Questie since
Classic started. It would seem I have completed the quest previously,
coz now I have v5.5.1 the quest icon has gone from minimap and others
have appeared in the area. I am grateful for your obviousness, that I
overlocked, with many thanks. Questie is the only addon I run and
essential for great game play, thank you for it!

----- Original Message -----

**Comment by Goodlyont** [comment]
I had out of date Questie (now updated) from when Classic started,
feel silly. I appreciate you trying to help me! 

----- Original Message -----

**Comment by BreakBB** [comment]
@Goodlyont Glad you figured it out! Don't worry and thank you for your report! We appreciate any help and report we get to improve Questie!

**Comment by Goodlyont** [comment]
Yes but it wasn't Questie was it ... it was user error! Thanks for
your patience. 

----- Original Message -----
