### ISSUE TITLE
MBB Support for Classic

### ISSUE THREAD

**Issue by rwilliams** [AeroScripts/QuestieDev#1718]
I've got the go ahead to do an official fork of MBB for classic.
https://www.curseforge.com/wow/addons/mbb-classic

I've added
`[42] = "QuestieFrame"`
to the ignore list and it seems to work fine. There was some mention of the new `QuestieFrameGroup` parent frame in the wowace issue. Let me know if I need to make any changes.

https://github.com/AeroScripts/QuestieDev/issues/1504

Alternatively I can setup repo and you all can send over a PR with the required changes.

Cheers,
Ron

**Comment by BreakBB** [comment]
If I remember correctly we're adding our frame to the MBB ignore list to fix the issue with it.

So I am not sure if MBB really needs to change anything tbh. Did you have problems with it without your changes?

**Comment by rwilliams** [comment]
Looks good I'll close this. When i first started using questie it was a few months back before this had been implemented on questie's end. I also thought the fix was a bit more complex than what it is to inject into MBB's ignore list.
