### ISSUE TITLE
Why are cloth turn-in NPCs are blocked from auto-accept?

### ISSUE THREAD

**Issue by gouletr** [AeroScripts/QuestieDev#1720]
## Question
I see that in QuestieAuto.lua the cloth donation turn-in NPCs are blocked for auto-accept. What's the reason for this? I manually tested to remove them from the blocked list and it works just fine, so why??

**Comment by Gogo1951** [comment]
Overlaps with https://github.com/AeroScripts/QuestieDev/issues/1537

**Comment by BreakBB** [comment]
@gouletr I think that it was just for safety reasons since we don't have a key overwrite for the auto turning in yet. Once we have that we will open up those quests as well.
Sorry for your trouble.
