### ISSUE TITLE
Alliance Trauma(6625) listed as available in quests by zone 

### ISSUE THREAD

**Issue by hammerface** [AeroScripts/QuestieDev#1723]
Alliance Trauma(6625) is listed as available in quests by zone, but it seems to be a breadcrump that should become unobtainable if you complete its follow up. I cannot receive this quest from the questgiver.

v5.5.1

**Comment by BreakBB** [comment]
It would be great if you could add the wowhead links to those quests ans also use the "Quest issue" template next time.
That will ensure our limited time can be used most effectively to fix such issues.

**Comment by BreakBB** [comment]
@hammerface Could you extract the ZIP below and place the file into `Questie/Database/Corrections` replacing the existing file?
This should fix the quest for you. I can't test this myself.

[QuestieQuestFixes.zip](https://github.com/AeroScripts/QuestieDev/files/4090667/QuestieQuestFixes.zip)

**Comment by hammerface** [comment]
This patch moved the quest to Completed Quests category.

**Comment by BreakBB** [comment]
@hammerface Thanks for testing it. Marking it as complete was the idea. We agreed it would be a better feeling for the user to have quests optional pre quests marked as complete as well and not as "unobtainable".
