### ISSUE TITLE
Tormus Deepforge(1680) listed as available in quests by zone

### ISSUE THREAD

**Issue by hammerface** [AeroScripts/QuestieDev#1724]
This is a step of the Ironforge level 10 warrior quest. It seems to become unobtainable if you do its equivalent quest in another major city instead. I have already completed the follow-up Ironband's Compound(1681), and cannot acquire this quest, but it is still listed as available.

v5.5.1

**Comment by BreakBB** [comment]
@hammerface Could you run the following commands and report the output:

`/dump IsQuestFlaggedCompleted(1679)`
`/dump IsQuestFlaggedCompleted(1678)`
`/dump IsQuestFlaggedCompleted(1680)`
`/dump IsQuestFlaggedCompleted(1681)`
`/dump IsQuestFlaggedCompleted(1682)`

**Comment by hammerface** [comment]
Dump; value=IsQuestFlaggedCompleted(1679)
[1]=false
Dump; value=IsQuestFlaggedCompleted(1678)
[1]=true
Dump; value=IsQuestFlaggedCompleted(1680)
[1]=false
Dump; value=IsQuestFlaggedCompleted(1681)
[1]=true
Dump; value=IsQuestFlaggedCompleted(1682)
[1]=true


By the way, I went out to the questgiver for (1679) and it was unavailable.
