### ISSUE TITLE
Digging Through the Dirt(254) listed as a available in quests by zone.

### ISSUE THREAD

**Issue by hammerface** [AeroScripts/QuestieDev#1725]
This is a quest which only involves interacting with a grave to summon an elite for Bride of the Embalmer(253). Having completed that quest already, I cannot interact with the grave and therefore cannot begin/finish this quest, but it is still being listed as available.

v5.5.1

**Comment by Doxxer** [comment]
It still actual in v.5.6.0; I've created a PR to fix issue: #1746
