### ISSUE TITLE
Quests by Zone Errors

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1728]
List of quests I've found in the wrong category (note that I'm a druid & alchemist) I suspect the issue with most of these is that a quest being marked as unavailable doesn't automatically push its followups into the unobtainable category (which, given that breadcrumbs can become unobtainable without stopping one from doing their followups, is fair):

Alterac Mountains:
A Bubbling Cauldron is a Love is in the Air seasonal quest
https://classic.wowhead.com/quest=9029/a-bubbling-cauldron

Searing Gorge:
Both quests named The Undermarket are for tailors and should be in Unobtainable with their pre-quest Shadoweaver instead of Missing Pre-quest.
https://classic.wowhead.com/quest=3385/the-undermarket
https://classic.wowhead.com/quest=3402/the-undermarket

Feralas:
The Wild Leather Armor questchains are for LWs only
https://classic.wowhead.com/quest=2847/wild-leather-armor (Alliance)
https://classic.wowhead.com/quest=2854/wild-leather-armor (Horde)

Moonglade:
Waking Legends and its prequest Shrouded in Nightmare are drops from the Dragons of Nightmare, coming in P4.

Orgrimmar:
The questline starting with Barbaric Battlements is BS only (suspect there may be a similar problem with the Alliance equivalent, can't confirm)
https://classic.wowhead.com/quest=2751/barbaric-battlements
Horde Trauma is a breadcrumb to Triage, and should be marked as unavailable if the latter was completed but not the former. (Again, can't check if similar problem on Alliance side)
https://classic.wowhead.com/quest=6623/horde-trauma

Silithus:
Almost all quests are coming P4, save for The Spirits of Southwind, Umber, Archivist and Hive in the Tower which I have completed.

Tanaris:
All the quests following A Blue Light Bargain are BS quests
https://classic.wowhead.com/quest=7652/a-blue-light-bargain

The Barrens:
Membership Card Renewal is an Engineering quest
https://classic.wowhead.com/quest=3646/membership-card-renewal

Thunder Bluff:
Kodo Hide Bag is a LW quest
https://classic.wowhead.com/quest=769/kodo-hide-bag

Un'Goro:
The Torwa Pathfinder questline will (likely) be added in P5
https://classic.wowhead.com/quest=9063/torwa-pathfinder

Winterspring:
The Demon Forge and Fiery Plate Gauntlets are BS quests
https://classic.wowhead.com/quest=5124/fiery-plate-gauntlets
https://classic.wowhead.com/quest=5127/the-demon-forge

Dire Maul:
The Foror's Compendium questline is only available to Warriors and Paladins
https://classic.wowhead.com/quest=7507/forors-compendium
Unfinished Gordok Business (1318) seems to not be in the game, having been replaced with Unfinished Gordok Business (7703)
https://classic.wowhead.com/quest=1318/unfinished-gordok-business

Various:
The entire questlines for dungeon tier set upgrades, starting with An Earnest Proposition, will be added in AQ (P5)
https://classic.wowhead.com/quest=8913/an-earnest-proposition (this is the druid version, there's one for every class)
The entire questline for the Scepter of the Shifting Sands will also be added in P5
https://classic.wowhead.com/quest=8286/what-tomorrow-brings
The entire BS questlines starting with The Origin of Smithing (Alliance) or The Old Ways (Horde)
https://classic.wowhead.com/quest=2758/the-origins-of-smithing

Version 5.5.1

**Comment by BreakBB** [comment]
@Cerby3BR Dude this is a great list and I will look into them soon!

**Comment by BreakBB** [comment]
@Cerby3BR Thanks again for this amazing effort! I took the time to go through all of your suggestions and these will be included in the upcoming release.
