### ISSUE TITLE
Minimap/Map

### ISSUE THREAD

**Issue by TotalBarracuda** [AeroScripts/QuestieDev#173]
I started New out in the Night elf starting Zone after i Reached dolanaar i heard about Questie, Then i installed it and in Game it showed me Avaible quest from still the beginning. What i already Done . Is there a fix to that ?

**Comment by Schaka** [comment]
No way to fix it, except through /questie complete <name>.
The addon only knows about quests you've finished when it was installed. Vanilla doesn't offer another way.
