### ISSUE TITLE
Remove Quest 

### ISSUE THREAD

**Issue by Jeezas** [AeroScripts/QuestieDev#1730]
It will be awesome to have the option to disable horde or alliance quest or vise-versa. The add on is great however, I sometimes go to a quest just to find out that is Horde only or vise-versa.

**Comment by BreakBB** [comment]
@Jeezas I don't know a quest which is shown for the wrong faction. Can you give an example? They should "all" be already shown just faction specific meaning only the quests you can really accept.

**Comment by Gogo1951** [comment]
I've leveled 3 Alliance and one Horde to 60 and haven't seen this on any quests I did. Completed all quests on Alliance side, about 85% done on Horde. Not counting various professions or classes though.

We either need more details from @Jeezas, or we should close this as not reproducible.

**Comment by BreakBB** [comment]
@Jeezas I am closing this for now, but will open it up again if you provide more information.
