### ISSUE TITLE
WoW Classic - Leatrix_Maps error after login to Char

### ISSUE THREAD

**Issue by ghost** [AeroScripts/QuestieDev#1731]
**LeatrixMaps, v8.3.01
Date: 2020-01-24 08:01:59**
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Leatrix_Maps\Leatrix_Maps.lua line 235:
   hooksecurefunc(): HandleUserActionToggleSidePanel is not a function
Debug:
   [C]: hooksecurefunc()
   Leatrix_Maps\Leatrix_Maps.lua:235: MainFunc()
   Leatrix_Maps\Leatrix_Maps.lua:1743:
      Leatrix_Maps\Leatrix_Maps.lua:1693
Locals:

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.1
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  ClassicQuestLog, v1.4.6-Classic
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  Informant, v8.2.6508 (SwimmingSeadragon)
  LeatrixMaps, v8.3.01
  OmniCC, v8.3.3
  Questie, v5.5.1
  Scrap, v8.3.0
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Spy, v1.0.21
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=38b)

**Comment by BreakBB** [comment]
@SysTestEng And this is the fault of Questie because?...

**Comment by drejjmit** [comment]
https://www.curseforge.com/wow/addons/leatrix-maps-classic/issues/101
They say it's a Questie issue.

**Comment by Gogo1951** [comment]
I use both of these addons and I've never seen any issues like the one reported. 

Possible you're using Leatrix Maps instead of Leatrix Maps (Classic)? 

https://www.curseforge.com/wow/addons/leatrix-maps-classic

**Comment by BreakBB** [comment]
@Gogo1951 Great catch!

@Nevcairiel You're using the retail version of Leatrix Maps instead of the Classic version. Change that and you should be fine.

And please report such issues to the appropriate addon next time.

**Comment by Nevcairiel** [comment]
Please highlight appropriate people next time!

**Comment by BreakBB** [comment]
Oh lol, sorry about that. Took the wrong suggestion.
