### ISSUE TITLE
Manual Set Questlevel range

### ISSUE THREAD

**Issue by Ischtaratu** [AeroScripts/QuestieDev#1732]
## Description
Questie only allows the selection of "LOWLEVEL_BELOW" and "LOWLEVEL_ABOVE".
However, if you want to work through individual level areas, and your character is already level 60, you will be shown all quests, which is not very clear.

## Desired function:
New selection of the specific quest level: for example 10-20 or 35-42.
or the selection only shows the quests of a selected area as new filteroption.

**Comment by Gogo1951** [comment]
Hey @Ischtaratu , thanks for taking the time to make this request. Let me try and understand it a bit more. You're saying you're 60, but you only want to see quests that are 35-45. More or less, yeah?

Seems like an edge case to me. With a limited number of dev hours (very limited), it's hard to prioritize requests unless they have a broad appeal. We've got some other requests to hide PVP quests, and elite quests, would something like that suffice?

Can you tell me a story on why this is important to you to help me better understand this? Why do you need this? How would it help you enjoy the game?

**Comment by Ischtaratu** [comment]
Yes, you have it!

I started to make up for any missing tasks. Really everyone in all areas. And of course I can display the low quests on the world map and in the minimap, but not selectively.

This feature request is an idea, not an obligation. If there is not enough time for this, that's ok. I can't program, but thought that if you can indicate that the quest can be displayed depending on the character level, Min and Max would only have to be defined differently.

So if it makes too much effort then please close the request or push it further back.

**Comment by Ischtaratu** [comment]
consideration:
Would it be possible to replace the two sliders with input fields? Each in the value range 1 to 60.

**Comment by Ischtaratu** [comment]
I Think i have found it:

Questie\Modules\Quest\QuestieQuest.lua
Line 1495

function QuestieQuest:CalculateAvailableQuests()
    local playerLevel = QuestiePlayer:GetPlayerLevel()
    local minLevel = playerLevel - Questie.db.global.minLevelFilter
    local maxLevel = playerLevel + Questie.db.global.maxLevelFilter

Replace the Calculation with manual values!

my personal dirty solution ...

**Comment by MatKier** [comment]
Hi all,

I was bored and I decided to browse through the open issues of my favorite classic add-on.
Anyway, I believe I implemented the requested feature in a minimal disturbing way.

This is my first time contributing to another repo, so let me know if and how you want to proceed with my pull request
#1809

Here are some screenshots showing an absolute setting of 0 to 13:
![Absolute level range off](https://user-images.githubusercontent.com/10388566/76159534-f32f4d80-6121-11ea-91e8-6b643c32b7fe.jpg)

![Absolute level range on from 0 to 13(https://user-images.githubusercontent.com/10388566/76159742-c419db80-6123-11ea-86bc-3aea94f18c46.jpg)

![Showing quests from 1 to 13 on the map](https://user-images.githubusercontent.com/10388566/76159719-8c129880-6123-11ea-90c4-5e8ee78f016f.jpg)

**Comment by Ischtaratu** [comment]
vote for MatKier !

It works exactly as I imagined.
