### ISSUE TITLE
Lunar Quests completed but still on map / not in journey log

### ISSUE THREAD

**Issue by c0mm0n** [AeroScripts/QuestieDev#1733]
## Description
Doing the Lunar festivals quests, they still show on map after completion and dont appear in journey.

## Wowhead link
https://classic.wowhead.com/quest=8726/brightspear-the-elder

## Questie version
v5.5.1

**Comment by drejjmit** [comment]
Quests that are not picked up but completed directly does not get tracked since there is no quest log change. Would need to track QUEST_TURNED_IN for that:
![image](https://user-images.githubusercontent.com/15526476/73077515-986acb00-3ec0-11ea-9d93-68495c4ff5f2.png)
