### ISSUE TITLE
Lunar quests (coins from Elders) marked as level 60

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#1735]
As the title says, they are categorized as level 60 quests meaning that none of my low level alts can see them on the map (as default they can only see quests 6 levels higher).
But the quests can be done by low levels too, so not sure why they are marked as 60?

**Comment by drejjmit** [comment]
We have plans to add so quest that requires level 1 but are tagged as level 60 show up (Cloth turn in + Event quests). 
But for now you can use the ``Show above level >`` slider and set it to 60.

**Comment by BreakBB** [comment]
Fixed with f96b86bf98d0cca746dc3ba72b7e73e7fd10a8d0
