### ISSUE TITLE
Hex of Weakness not completing

### ISSUE THREAD

**Issue by BaileySri** [AeroScripts/QuestieDev#1737]
Quest not being removed after completing.

Temporary solution is using the My Journey advanced search to find all versions of Hex of Weakness and making them Hidden by user.

Current list of Hex of Weakness quest IDs:
5652
5654
5655
5656
5657

**Comment by BreakBB** [comment]
@BaileySri please use one of our issue templates next time. What version of Questie are you using and could you add some screenshots?

**Comment by BaileySri** [comment]
@BreakBB 
Apologies for that, first time making an issue.

Questie Version: v5.5.1
![Version](https://user-images.githubusercontent.com/39617257/73124157-acb0d580-3f5d-11ea-9fb1-55cca22cd8ae.png)

The quest giver was also the turn in point, Ur'kyo, located at the location shown below.
![Location](https://user-images.githubusercontent.com/39617257/73124159-b20e2000-3f5d-11ea-9d56-7145001330f0.png)

It appears that after a simple relog Questie has picked up on the completed quests and has marked them as complete now. It must have been an error with completing the quest as I received it from Ur'kyo:
![Completed](https://user-images.githubusercontent.com/39617257/73124173-e550af00-3f5d-11ea-9004-11b71f0352e8.png)

**Comment by BreakBB** [comment]
@BaileySri So you completed the quest but Questie didn't show you the NPC to turn in the quest?

**Comment by BreakBB** [comment]
Most likely related to #1762
