### ISSUE TITLE
"Fiora Longears" quest shown as not completed on the "Quests by Zone" page.

### ISSUE THREAD

**Issue by gyuuula** [AeroScripts/QuestieDev#1738]
## Description
"Fiora Longears" quest (id: 1132) is shown as not completed on the "Quests by Zone" page. I'm confident, that I completed it, and the quest marker doesn't shows up in Menethil Harbor on the map or on the minimap.

## Wowhead link
https://classic.wowhead.com/quest=1132/fiora-longears

## Screenshots
https://i.imgur.com/rsO5sxp.jpg

## Questie version
5.5.1 (latest)

**Comment by Gogo1951** [comment]
![rsO5sxp](https://user-images.githubusercontent.com/55365231/73128158-b142b180-3f90-11ea-98b3-80bd61c06710.jpg)

**Comment by drejjmit** [comment]
Could you run the following command and report the output:
``/dump IsQuestFlaggedCompleted(1133)``

**Comment by BreakBB** [comment]
@gyuuula I think that this quest is just an optional breadcrumb quest and it isn't marked as such in our data. It would be very helpful if you run the command drejjmit posted above so we can verify this.

**Comment by gyuuula** [comment]
It has returned [1]=true.

**Comment by BreakBB** [comment]
@gyuuula Thank you very much for posting back. So it really is an optional breadcrumb quest. We'll mark it and the fix should be online very soon.
