### ISSUE TITLE
QuestieQuest.lua:504 GetQuestLogTitle(index)

### ISSUE THREAD

**Issue by Pr1mu5** [AeroScripts/QuestieDev#174]
After turning the quest "[507]Lord Aliden Perenolde" this error occurred.
http://db.vanillagaming.org/?quest=507

`[2016/01/29 05:22:41-139]: Questie\QuestieQuest.lua:504: Usage: GetQuestLogTitle(index)
<in C code>: in function `QuestieCompat_GetQuestLogTitle'
Questie\QuestieQuest.lua:504: in function `AstroGetQuestObjectives'
Questie\QuestieNotes.lua:25: in function `AddQuestToMap'
Questie\QuestieQuest.lua:202: in function `UpdateQuestInZone'
Questie\QuestieQuest.lua:135: in function `UpdateQuests'
Questie\QuestieAstro.lua:100: in function `OnUpdate'
<string>:"Questie:OnUpdate":2: in main chunk`

**Comment by Dyaxler** [comment]
Has an error like this re-occurred recently?
