### ISSUE TITLE
"Lethtendris's Web" Quest doesn't show up on the map

### ISSUE THREAD

**Issue by gyuuula** [AeroScripts/QuestieDev#1740]
## Description
"Lethtendris's Web" Quest (id: 7488) doesn't show up on the map.
It is on the "Missing Pre Quest" list, but the "Feathermoon Stronghold" (id: 7494) is obviously not a requisite.

## Wowhead link
https://classic.wowhead.com/quest=7488/lethtendriss-web
https://classic.wowhead.com/quest=7494/feathermoon-stronghold

## Screenshots
https://imgur.com/a/NyTCHKD

## Questie version
5.5.1

**Comment by drejjmit** [comment]
Yeah 7494 looks like a breadcrumb that can be removed from 7488 requirements
