### ISSUE TITLE
 "An Introduction" is showing as available after having been completed 

### ISSUE THREAD

**Issue by bensoutendijk** [AeroScripts/QuestieDev#1742]
## Description
quest "An Introduction" is showing as available after having been completed 

## Wowhead link
https://classic.wowhead.com/quest=7633/an-introduction

## Questie version
5.5.0

**Comment by BreakBB** [comment]
@bensoutendijk Did you try a `/reload` or is it still showing for you? I can't find an issue in our data for this quest.

**Comment by bensoutendijk** [comment]
I did not try to reload the ui. I will check if that works, but if it does, then I still think there is a bug. I am noticing that a lot of quests have this issue. The type of quest where it continues to appear as available after having been completed all have the 'complete quest' as the only option. In other words, some questions you don't "accept" but you can only "complete quest". I see this in other instances, but can't give examples right now sorry. "An Introduction" is the most recent example I have encountered.
