### ISSUE TITLE
Bug in Un'Goro Crater

### ISSUE THREAD

**Issue by yobbin2000** [AeroScripts/QuestieDev#1743]
## Bug description
Handing in the quest Crystals of Power to J.D. Collie in Un'Goro Crater got the following error

Date: 2020-01-27 16:49:10
ID: 1
Error occured in: Global
Count: 1
Message: ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua line 577:
   attempt to index local 'iconData' (a nil value)
Debug:
   ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:577: handleMapIcon()
   ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:644:
      ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:516
Locals:
icon = QuestieFrame510 {
 glowLogicTimer = <table> {
 }
 FadeOut = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:317
 frameId = 510
 FakeUnhide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:361
 FakeHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:345
 texture = <unnamed> {
 }
 FadeLogic = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:483
 BaseOnShow = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:202
 glow = QuestieFrame510Glow {
 }
 BaseOnHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:226
 0 = <userdata>
 UpdateTexture = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:230
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:265
 GlowUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:178
 FadeIn = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:331
 BaseOnUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:196
}
iconData = nil
(*temporary) = 4287
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'iconData' (a nil value)"
self = QuestieFrame1022 {
 0 = <userdata>
 glow = QuestieFrame1022Glow {
 }
 BaseOnUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:196
 loaded = true
 FakeUnhide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:361
 data = <table> {
 }
 FakeHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:345
 AreaID = 490
 texture = <unnamed> {
 }
 FadeLogic = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:483
 BaseOnShow = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:202
 glowLogicTimer = <table> {
 }
 BaseOnHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:226
 FadeOut = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:317
 UpdateTexture = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:230
 y = 2.700000
 x = 41.920000
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:265
 miniMapIcon = true
 GlowUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:178
 FadeIn = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:331
 frameId = 1022
}
tinsert = <function> defined =[C]:-1
QuestieLib = <table> {
 PrintDifficultyColor = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:27
 ProfileFunction = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:273
 Levenshtein = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:419
 CacheItemNames = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:298
 GetQuestObjectives = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:137
 MathRandom = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:461
 GetRGBForObjective = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:79
 private = <table> {
 }
 GetDifficultyColorPercent = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:46
 SanitizePattern = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:381
 MathRandomSeed = <function> defined @Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:457
 GetColoredQuestName = <function> defined @Interface\AddOns\Questie\Modules\Lib
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.1
  AtlasLootClassicData, vv1.4.1
  AtlasLootClassicDungeonsAndRaids, vv1.4.1
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucScanData, v8.2.6498 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  Questie, v5.5.0
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TitanClassic, v1.1.4.11302
  TitanClassicAmmo, v1.1.4.11302
  TitanClassicBag, v1.1.4.11302
  TitanClassicClock, v1.1.4.11302
  TitanClassicGold, v1.1.4.11302
  TitanClassicLocation, v1.1.4.11302
  TitanClassicLootType, v1.1.4.11302
  TitanClassicPerformance, v1.1.4.11302
  TitanClassicRegen, v1.1.4.11302
  TitanClassicRepair, v1.1.4.11302
  TitanClassicVolume, v1.1.4.11302
  TitanClassicXP, v1.1.4.11302
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=48f)

**Comment by BreakBB** [comment]
Related to #1584
