### ISSUE TITLE
Missing Quest Marker for [53] The Fare of Lar'korwi in Un'Goro

### ISSUE THREAD

**Issue by yobbin2000** [AeroScripts/QuestieDev#1745]
## Description
The quest [53] The Fare of Lar'korwi is missing the marker for the quest objective.

## Wowhead link
https://classic.wowhead.com/quest=4290/the-fare-of-larkorwi

## Questie version
v5.5.0

**Comment by BreakBB** [comment]
@yobbin2000 I can't find an issue in our data for this quest. The object for this quest is in our database and it's linked to the quest.

![image](https://user-images.githubusercontent.com/33514570/73181240-23dd9980-4117-11ea-9eb1-45cec1868f46.png)


Did you try a `/reload`?

**Comment by yobbin2000** [comment]
I did not try /reload and I have now completed the quest so I can't check if the marker is still missing. Sorry

**Comment by Gogo1951** [comment]
If you reload it shows up again. But yeah, I saw this last time I did it too... there's no marker when you pick up the quest, you have to reload to see it.

**Comment by BreakBB** [comment]
This should be fixed with v5.7.2 and the changes to objective drawing.
