### ISSUE TITLE
There was an error populating objectives for Fragments of the Past

### ISSUE THREAD

**Issue by Foozor** [AeroScripts/QuestieDev#1748]
## Description
Error occurs after latest update v5.6.0 WoW Classic.
There was an error populating objectives for Fragments of the Past 5247 3
Interface\Addons\Questie\Modules\Map\QuestieMap.lua:452: No UiMapID for (nil) :2557Dire Pool

## Wowhead link
https://classic.wowhead.com/quest=5247/fragments-of-the-past

## Questie version
v5.6.0 WoW Classic

**Comment by Gogo1951** [comment]
Dupe of #1747

**Comment by BreakBB** [comment]
@Gogo1951 The error message is a totally different. It is not a dupe of #1747

**Comment by heloid** [comment]
+1 on this

**Comment by BreakBB** [comment]
Should be fixed with cc2f38bd5c9a566371bae9f95613b3ef922e78ff and will be released soon :tm:
