### ISSUE TITLE
Questie Error in Desolace

### ISSUE THREAD

**Issue by Storez101** [AeroScripts/QuestieDev#175]
Picking up the below errors when I gathered the quests at Nijel's Point in Desolace.

_interface\addons\questie\QuestieQuest.lu
a:157: attempt to call global
‘QuestCompat_GetQuestLogTitle’ (a nil value)

interface\addons\questie\QuestieQuest.lu
a:294: attempt to call global
‘QuestCompat_GetQuestLogTitle’ (a nil value)
_
The errors won't disappear, and whilst present the map does not update to show questie drops / kills.

**Comment by Dyaxler** [comment]
This error has appeared for me once or twice when I inadvertently forgot to copy over and enable the !QuestieCompatibility portion of Questie. v2.0.12 has two "mods" that need to be enabled. Questie and !QuestieCompatibility. The new version just released last night - these two mods have been merged into one. Please try the new version. :)
