### ISSUE TITLE
Missing map markers: Jonespyre's Request

### ISSUE THREAD

**Issue by AlistairJM** [AeroScripts/QuestieDev#1754]
## Description
It appears there are two missing quest markers for the quest **Jonespyre's Request**. Comes in two flavours, one picked up from Stormwind, and one from Feralas. I assume they are mutually exclusive.

## Wowhead link
https://classic.wowhead.com/quest=3787/jonespyres-request
https://classic.wowhead.com/quest=3788/jonespyres-request

## Screenshots
![Quest](https://user-images.githubusercontent.com/37016052/74030111-22796000-49a6-11ea-930d-82798b8a1bde.png)

## Questie version
v5.6.0

**Comment by BreakBB** [comment]
@AlistairJM Thanks for the report. Could you run the following command and report the output? We might have a wrong pre quest listed for those quests:

`/dump IsQuestFlaggedCompleted(3785)`

**Comment by AlistairJM** [comment]
@BreakBB Result was true.

[1]=true

**Comment by BreakBB** [comment]
@AlistairJM I can't find an issue with those quests 🤔 Did you try a `/reload` when the quest didn't show up?

**Comment by AlistairJM** [comment]
@BreakBB I am trying to recall if I had actually handed in 3785 at the time. I certainly have done since I reported this, explaining why it now returns true. Are we sure it isn't 3781, the quest prior to 3785, which is the quest which then allows these two?

**Comment by BreakBB** [comment]
@AlistairJM You mean in order to accept one of the "Jonespyre's Request" quests you need to do (just) 3781 (and/or 3785)?

**Comment by AlistairJM** [comment]
@BreakBB I am thinking just completing 3781 by itself might be enough to open up both "Jonespyre's Request" quests. I cannot say with 100% confidence, but it seems to be the case. I think I went to Feralas and noticed it while I was on 3785, but had not yet handed it in.

**Comment by BreakBB** [comment]
@AlistairJM You could check this in your "My Journey" tab if you didn't reset it lately.

**Comment by AlistairJM** [comment]
@BreakBB Sorry about the delay. Unfortunately I am unable to check this now, the recent storm killed my PSU, so I decided I was due an upgrade anyways and got a new system. So no longer have access to my previous journey information.

**Comment by drejjmit** [comment]
The one in Stormwind is not showing up for me:
https://classic.wowhead.com/quest=3787/jonespyres-request

![image](https://user-images.githubusercontent.com/15526476/74536757-0000bd00-4f39-11ea-9d1c-81a3a7c118e7.png)

[14:49:10] Dump: value=IsQuestFlaggedCompleted(3785)
[14:49:10] [1]=false

**Comment by BreakBB** [comment]
Currently there is no way to handle such quests, because they are neither a `childQuest` nor a `preQuest`. Will need to check again if the database needs to be adjusted for it.

**Comment by Gogo1951** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.
