### ISSUE TITLE
Quest "Young Crocolisk Skins" not showing on map

### ISSUE THREAD

**Issue by SpareSimian** [AeroScripts/QuestieDev#1757]
The Wetlands quest "Young Crocolisk Skins" is not showing a white or yellow quest marker on the map or minimap. I see other white and yellow markers in Menethil. Level 36 gnome mage. "Show all quests below range" is checked. 

https://classic.wowhead.com/quest=484/young-crocolisk-skins

Questie version 5.6.0 (from TOC)

(I noticed it when Missing Tradeskill Recipes showed that I lacked the cooking recipe from the followup quest for this quest. I've been doing all the recipe quests religiously on all my toons and was surprised to see this one missing and no quest marker.)

**Comment by SpareSimian** [comment]
[Questie-Issue-1757-202002081128.zip](https://github.com/AeroScripts/QuestieDev/files/4175031/Questie-Issue-1757-202002081128.zip)

Here's the WTF state file for the addon. I'm avoiding accepting the quest so I can test this later. Affected character is Cacaobelle.

**Comment by BreakBB** [comment]
@SpareSimian Thanks for the report. Could you extract the file below and place it in `Questie/Database/Corrections` and do a `/reload`?

[QuestieQuestFixes.zip](https://github.com/AeroScripts/QuestieDev/files/4176975/QuestieQuestFixes.zip)

The PR #1749 states this fixes the issue.

**Comment by SpareSimian** [comment]
Thanks! I now see the "!" on the map and minimap.

**Comment by BreakBB** [comment]
Fixes with #1749
