### ISSUE TITLE
Align tracker text to the right.

### ISSUE THREAD

**Issue by alucardu** [AeroScripts/QuestieDev#1758]
## Description
Currently the tracker text is aligned to the left. Would be nice to be able to align the text to the right so the tracker can be placed on the right side of the UI.

**Comment by BreakBB** [comment]
@alucardu Aligning the Tracker text to the right does not make much sense for most languages. It will make it really, really hard to read.

But with the latest changes to the tracker it will be easier to place the Tracker on the right side of the UI.
