### ISSUE TITLE
Questie Ragefire Chasm Issue

### ISSUE THREAD

**Issue by piemastermd** [AeroScripts/QuestieDev#176]
When i enter ragefire chasm there is a error message that i cant get rid of. Here's the image of the error message. http://puu.sh/n6V9t/2fc985eba9.jpg

**Comment by Dyaxler** [comment]
Before entering Ragefire Chasm - did you have any quests listed in your tracking frame? Which version of Questie are you using? Did you modify it in any way? We need to know which version you're using so we can identify the line number. Line 365 in QuestieTracker.lua might differ from the version I'm using.
