### ISSUE TITLE
Missing quest

### ISSUE THREAD

**Issue by S4mmis** [AeroScripts/QuestieDev#1761]
https://classic.wowhead.com/quest=1423/the-lost-supplies

Questie  5.6.0

**Comment by BreakBB** [comment]
@S4mmis Could you please explain a bit what is missing and what you experienced?

**Comment by S4mmis** [comment]
Quest not show in map

**Comment by BreakBB** [comment]
@S4mmis Showing up for us 
![image](https://user-images.githubusercontent.com/33514570/74146765-1e497e80-4c02-11ea-95a9-ce24b748b5f7.png)
![image](https://user-images.githubusercontent.com/33514570/74147726-1ee31480-4c04-11ea-9b2c-f924e552f203.png)

Maybe you didn't check the "Show Repeatable Quests Icons"?

**Comment by Gogo1951** [comment]
These work as expected, I added this and tested it while leveling two toons since.

**Comment by BreakBB** [comment]
Closing this as it seems to work perfectly fine.
