### ISSUE TITLE
Icons on map dont get updated after accepting/updating/finishing quest

### ISSUE THREAD

**Issue by IcemanHHW** [AeroScripts/QuestieDev#1762]
## Bug description
The icons on the map for objectives or quest giver dont get updated after accepting, finishing part of a a quest or finishing a quest. Clicking show/hide Questie or reloading the UI updates the icons, but only for the current quests. After getting a new quest clicking the button or reloading the UI needs to be done again. 

I have tried it with all my addons enabled, all addons disabled except Questie and with ElvUI and Questie enabled. There isnt a difference between it.

## Questie version
Latest version (v5.6.0)

**Comment by Orome123** [comment]
I can confirm this is still the case at version 5.7.0, icons don't get updated until a /reload.

**Comment by BreakBB** [comment]
@IcemanHHW Are you running Questie on WoW Classic and already tried to delete all the savedVariables of Questie?

Users reported this on Discord as well, but none of our devs can reproduce this.

**Comment by IcemanHHW** [comment]
@BreakBB I'm running it on WoW Classic yes. I haven't deleted the savedVariables yet. I guess they are in the WTF folder? Will do that later this week and report back if that fixes it.

**Comment by BreakBB** [comment]
Check [this FAQ](https://github.com/AeroScripts/QuestieDev/wiki/FAQ#2-questie-still-doesnt-show-anything) for the locations of the files you have to delete.
This will **delete your Journey** as well. Make sure to close WoW before deleting the files.

**Comment by altiods** [comment]
For me this happens anytime I uncheck "Enable Minimap Icons" from the General tab.  The only way I can fix it is by deleting my SavedVariables for questie and leaving it checked.

**Comment by Orome123** [comment]
As of 5.7.1, I still need to /reload all the time to get icons on the map updated.

After reading @altiods comment, I tested and can confirm that when I checked "Enable Minimap Icons", icons started auto-updating. and when unchecked again, they didn't auto-update. I always play with that option unchecked so I hadn't really tried it before. Hope this can be of any help.

**Comment by BreakBB** [comment]
@Orome123 So if you have the "Enable Minimap Icons" option enabled, Questie works without any problem? That would be a very good lead to find the reason for this issue!

**Comment by Orome123** [comment]
@BreakBB yes, when Enable Minimap Icons is enabled, everything works as intended. When disabled, it stops auto-updating icons on the main map and you need to do a /reload for icons to update. I also tried disabling all other addons that might conflict with questie, so it's not that either.

**Comment by IcemanHHW** [comment]
@BreakBB i deleted the savedVariables and made a fresh character to test it on, unfortunately that didn't fix it. I then tried it with minimap icons enabled and I can also confirm that with that option enabled the map icons get updated.

**Comment by BreakBB** [comment]
@IcemanHHW @Orome123

Thank you very, very much for not giving up and keep testing for this issue. I hope to find enough time next week to investigate this issue and then hopefully fix it.

It is a really, really helpful lead that the error seems to be caused by the minimap icons option :+1:

**Comment by Thorinair** [comment]
Just chiming in to say that I have exactly the same issue. I can confirm that enabling Minimap icons allows it to update.

**Comment by BreakBB** [comment]
@IcemanHHW  @Orome123 @altiods @Thorinair It would be great if you could test the version below. I think I found the issue and fixed this issue.

[Questie-v5.7.1_6-90d27bc.zip](https://github.com/AeroScripts/QuestieDev/files/4244458/Questie-v5.7.1_6-90d27bc.zip)

**Comment by Orome123** [comment]
@BreakBB just tested the version you uploaded with a lvl 1 character and it's fixed, now it's updating correctly :D thanks for all your work and dedication!

**Comment by IcemanHHW** [comment]
@BreakBB I know I'm a bit late and that the update got pushed but it's also working for me. Thanks :D

**Comment by BreakBB** [comment]
@IcemanHHW @Orome123 Thanks for testing and I am glad this could be solved :+1:
