### ISSUE TITLE
PvP Quest Icons Still Showing After Toggle Off

### ISSUE THREAD

**Issue by xDemoN** [AeroScripts/QuestieDev#1766]
**Bug Description**

- Default is TRUE for Enable PvP Quest Icon

- Check toggle to mark Enable PvP Quest Icon as FALSE

- PvP Quest Icons still appear on Map

**Questie v5.7.0**

**Comment by BreakBB** [comment]
@xDemoN Which quests are affected by this? There are a couple of Alliance quests which seems to not be marked as PvP quest on Blizzards side. We're using an API function for this.

**Comment by xDemoN** [comment]
**This is the list I have so far:**

8372 - Fight for Warsong Gulch
8386 - Fight for Warsong Gulch
8399 - Fight for Warsong Gulch
8400 - Fight for Warsong Gulch
8401 - Fight for Warsong Gulch
8402 - Fight for Warsong Gulch
8403 - Fight for Warsong Gulch
8404 - Fight for Warsong Gulch
8405 - Fight for Warsong Gulch
8406 - Fight for Warsong Gulch
8407 - Fight for Warsong Gulch
8408 - Fight for Warsong Gulch

8375 - Remember Alterac Valley
8383 - Remember Alterac Valley

5344 - The Last Barov
