### ISSUE TITLE
Sunscorched Shells shows when it's not available

### ISSUE THREAD

**Issue by wodim** [AeroScripts/QuestieDev#1767]
[Sunscorched Shells](https://classic.wowhead.com/quest=1710/sunscorched-shells) requires [Mathiel](https://classic.wowhead.com/quest=1703/mathiel) but it's shown even if Mathiel wasn't completed.

#1231 

v5.7.0

**Comment by BreakBB** [comment]
@wodim Thanks for the report. Looks like the information in #1231 were either wrong or Blizzard fixed it ^^
