### ISSUE TITLE
Error on loging in to a character

### ISSUE THREAD

**Issue by Nerillida** [AeroScripts/QuestieDev#1769]
On log in to a character

Date: 2020-02-13 09:49:24
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Questie.lua line 194:
   Usage: RegisterEvent("eventname", "methodname"): 'methodname' - method 'QUEST_DETAIL' not found on self.
Debug:
   [C]: ?
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:112: RegisterEvent()
   Questie\Questie.lua:194:
      Questie\Questie.lua:148
   [C]: ?
   ...ddOns\EMA-Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...ddOns\EMA-Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...ddOns\EMA-Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...ddOns\EMA-Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:613:
      ...ddOns\EMA-Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BadBoy, vv1-classic
  BadBoyCCleaner, vv8.2.0
  BadBoyGuilded, vv8.2.0
  BasicChatMods, vv4-classic
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.10.00
  ClassicCastbars, vv1.2.1
  ClassicCastbarsOptions, v
  ClassicSpellActivations, v
  ClassTrainerPlus, v0.5-beta
  CTBarMod, v8.3.0.3
  CTBuffMod, v8.3.0.3
  CTCore, v8.3.0.1
  CTLibrary, v8.3.0.3
  CTMailMod, v8.3.0.1
  CTMapMod, v8.3.0.3
  CTPartyBuffs, v8.2.5.6
  CTUnitFrames, v8.3.0.2
  DidIDoIt, v1.2.0
  EMAClassic, vv1.13.2-Release-v0.6(121022)
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtVendorUIClassic, v1.0.4
  FloAspectBar, v
  FloTotemBar, v
  GatherMate2, v1.45.4
  GlobalIgnoreList, v1.13.2
  Grail, v107
  GSE, v2.4.25
  GSEGUI, v2.4.25
  GSELDB, v2.4.25
  ISBoxer, v1.0
  LetMeCast, v1.3
  MageButtons, v1.0
  Mapster, v1.8.5
  Misspelled, v1.7.7
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  OmniCC, v8.2.4
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v5.5.1
  QuestLogEx, v1.2
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=67f)

**Comment by BreakBB** [comment]
@Nerillida You are running Questie on WoW Classic, aren't you? Did you try a `/reload` after the error appeared?

**Comment by Nerillida** [comment]
Yes, but the next day the error was gone. !?!?

**Comment by BreakBB** [comment]
@Nerillida Maybe you forgot to restart WoW after you updated?

**Comment by Nerillida** [comment]
I do typically restart, but who knows.

**Comment by BreakBB** [comment]
I will leave this open for a few days to see if it happens again. Thanks for the report for now 👍
