### ISSUE TITLE
Monkey Quest Theme

### ISSUE THREAD

**Issue by Qrokqt** [AeroScripts/QuestieDev#177]
I'd like to create a theme using the monkey quest colors. Would I just need to override GetDifficultyColor and getRGBForObjective?

![mquest colors](https://cloud.githubusercontent.com/assets/17385843/13203991/1ab384ba-d892-11e5-9669-9fc3d2d08c30.png)

**Comment by Schaka** [comment]
Yes, basically. No need to even overwrite them. You can just change the Questie code directly, as there will be no updates to it anyway.

**Comment by Dyaxler** [comment]
Planning on adding this type of functionality to a later version of 2.0

**Comment by Dyaxler** [comment]
I still haven't forgotten about this request. :) I looked over the QuestTracker coloring code and this would be very easy to do however, I don't know if everyone will like it. To be clear the change would only be cosmetic in nature and only the colors would change not the way that MonkeyQuest displays them. 

Currently MonkeyQuest's QuestTracker is a "static" tracker in that it doesn't intelligently sort the quests in any kind of order. It filters them and sorts by Zone and Dungeon sure but that's it. Questies QuestTracker sorts based on distance so it's handy to show the user quests they can be completed near by or remind them that a quest can be completed outside the quest they are currently focused on.

And I'll be totally honest, I hate the check boxes and the minimize / X buttons in MonkeyQuest but I do like the color scheme. I'm going to look into adding a color scheme toggle (default / MonkeyQuest like) to a future version. I had planned on adding it to v2.4 but some of the bug fixes / features took several hours and I felt that releasing that was more important then a color scheme change.

/cheers

**Comment by Dyaxler** [comment]
I've added this color scheme to v2.5

Use /questie boldcolor to enable it.
