### ISSUE TITLE
Torwa Pathfinder not showing in the journey

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1770]
The quest Torwa Pathfinder is now available, and correctly shows up on the minimap, but is not listed as available in Quests by Zone, Moonglade. (The rest of the questline does correctly show up in the Un'Goro Missing Pre Quest portion)

https://classic.wowhead.com/quest=9063/torwa-pathfinder

![WoWScrnShot_021520_100716](https://user-images.githubusercontent.com/54936174/74585273-3ee74f00-4fdb-11ea-9b22-4435e568aa0f.jpg)

Version 5.7.1

**Comment by BreakBB** [comment]
@Cerby3BR Thanks for other report from you
 This should be an really easy fix :grin:

Not sure though if the quest should show in Moonglade since you can also accept it in TB afaik :thinking:
