### ISSUE TITLE
Gorishi Sting drops only from Wasps and Stingers

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1771]
Gorishi Stings, a quest drop for Bloodpetal Poison, only seem to drop from Gorishi Wasps and Stingers, despite being marked by questie as dropping from all Gorishi mobs. Source: did a full clear of the Slithering Scar until I had all 8, only dropped from the Wasps and Stingers. The most recent comment in the Bloodpetal Poison page, "Make sure you kill more than just the wasps as the other gorishi mobs drop the stinger as well.", is likely lumping in the stingers with the other mobs, as the text quest does specifically call out the wasps but not the stingers.

https://classic.wowhead.com/item=22435/gorishi-sting
https://classic.wowhead.com/quest=9052/bloodpetal-poison

Version 5.7.1

**Comment by BreakBB** [comment]
@Cerby3BR Alright. I think we should then just mark the wasps and stingers for the quest. Even if the other mobs may drop them, we should only show the "heighest" drop chance
