### ISSUE TITLE
[12] Electropellers

### ISSUE THREAD

**Issue by xDemoN** [AeroScripts/QuestieDev#1772]
**Description:**
When the pre-quest is unobtainable - [12] Gaffer Jacks - this quest is listed as missing pre-quest instead of also being listed as unobtainable.

**Screenshot:**
![image](https://user-images.githubusercontent.com/14188974/74594871-3443ae80-5009-11ea-8f1a-294d929313d4.png)

**Questie Version:**
v5.7.1

**Comment by xDemoN** [comment]
While "missing pre quest" isn't wrong, it's my understanding that if the pre-quest is unobtainable, the remaining quests in the chain should be as well.

**Comment by BreakBB** [comment]
@xDemoN Yes, you're absolutely correct on this. I will try to fix this in the next days and get a release out.
