### ISSUE TITLE
Bloodsail Buccaneers Quests

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1777]
The quests associated with the Bloodsail Buccaneers reputation (3 normal quests with them and 4 repeatable quests to mend goblin rep) aren't showing up as available either in the map or the journey, even though I have the required rep; the objectives are showing up on the map, though, so they are in the questie database.

https://classic.wowhead.com/quest=9272/dressing-the-part
https://classic.wowhead.com/quest=1036/avast-ye-scallywag
https://classic.wowhead.com/quest=4621/avast-ye-admiral

https://classic.wowhead.com/quest=9267/mending-old-wounds (Ratchet)
https://classic.wowhead.com/quest=9259/traitor-to-the-bloodsail (Booty Bay)
https://classic.wowhead.com/quest=9268/war-at-sea (Gadgetzan)
https://classic.wowhead.com/quest=9266/making-amends (mistakenly tagged on Wowhead as Burning Steppes, actually Everlook)

![WoWScrnShot_022220_144511](https://user-images.githubusercontent.com/54936174/75093550-f0115a80-5582-11ea-9a22-650dd98b2a76.jpg)

Version 5.7.1

**Comment by Cerby3BR** [comment]
![WoWScrnShot_022220_145453](https://user-images.githubusercontent.com/54936174/75093601-88a7da80-5583-11ea-9a48-6c2f25b5bb8c.jpg)
![WoWScrnShot_022220_145502](https://user-images.githubusercontent.com/54936174/75093603-8d6c8e80-5583-11ea-8ca0-b812aa1dd2f3.jpg)
![WoWScrnShot_022220_145504](https://user-images.githubusercontent.com/54936174/75093606-9198ac00-5583-11ea-9f71-417a4e066f25.jpg)
![WoWScrnShot_022220_145511](https://user-images.githubusercontent.com/54936174/75093609-952c3300-5583-11ea-9b4e-66f79a828577.jpg)
Additional screenshots of the Buccaneer quests (Dressing the Part requires neutral rep, the other two friendly rep)

**Comment by BreakBB** [comment]
You tried a `/reload`, yes?

**Comment by Cerby3BR** [comment]
Yep, didn't do anything. Will update with screenshots of the goblin mend quests for reference.

**Comment by BreakBB** [comment]
@Cerby3BR Okay, thanks. Will look into it in the next days. Might require some research.

**Comment by Cerby3BR** [comment]
![WoWScrnShot_022220_165604](https://user-images.githubusercontent.com/54936174/75095474-6028dc00-5595-11ea-8251-8449f23d6cf9.jpg)
![WoWScrnShot_022220_150339](https://user-images.githubusercontent.com/54936174/75095480-674fea00-5595-11ea-96b8-0cdb49d2afdf.jpg)
![WoWScrnShot_022220_170402](https://user-images.githubusercontent.com/54936174/75095481-6fa82500-5595-11ea-95d1-bf6c401f9182.jpg)
![WoWScrnShot_022220_164829](https://user-images.githubusercontent.com/54936174/75095483-7767c980-5595-11ea-8f71-a86c82e4fcd0.jpg)
And here's the goblin quests, they are repeatable until you're neutral with the corresponding city (each grants full rep to their city and half rep to the other three, so it's possible to have some available and some not)

**Comment by BreakBB** [comment]
@Cerby3BR All those quests were blacklisted which is why they didn't show up. Must be from the time where reputation requirements weren't handled correctly.

Could you explain what reputation level those quests require? That way I can check them before unhiding them.

**Comment by Cerby3BR** [comment]
Dressing the Part is available starting from Neutral with Bloodsail Buccaneers.
Avast, Ye Scallywag/Admiral are available starting with Friendly. (Scallywag leads to Admiral)

Mending Old Wounds is available as long as you're Hated, Hostile or Unfriendly with Ratchet.
Similarly with Traitor to the Bloodsail/Booty Bay; War at Sea/Gadgetzan; and Making Amends/Everlook.
