### ISSUE TITLE
Missing many spots for "... and Bugs"

### ISSUE THREAD

**Issue by wodim** [AeroScripts/QuestieDev#1778]
https://classic.wowhead.com/npc=922/silt-crawler and https://classic.wowhead.com/npc=1088/monstrous-crawler drop https://classic.wowhead.com/item=5938/pristine-crawler-leg for https://classic.wowhead.com/quest=1258/and-bugs but the spots that appear on the map are lacking. Especially Silt Crawlers don't appear at all:

![image](https://user-images.githubusercontent.com/1001553/75148425-e95c2200-56ff-11ea-9470-e41b402c1366.png)

v5.7.0

**Comment by BreakBB** [comment]
@wodim Could you update to v5.7.1 and try again? For me there're a lot of spawns showing:

![image](https://user-images.githubusercontent.com/33514570/75158273-0e5b8f80-5716-11ea-8dc0-7db6d431b8bb.png)

**Comment by wodim** [comment]
There is nothing in the v5.7.1 changelog that mentions this quest. In any case I've completed it already so I can't check. Indeed looking for "Silt Crawler" shows lots of spawns, but they didn't appear when I was on the quest.
