### ISSUE TITLE
Option to move quest item button on the quest tracker to the right side instead of the current left.

### ISSUE THREAD

**Issue by deikun** [AeroScripts/QuestieDev#1779]
Currently the quest tracker will place usable quest items as a quick access button to the left of the listed quest. Since I normally keep my quest tracker docked to the upper left corner of my screen, these icons are then sent placed off the screen. Having an option to move it would be greatly appreciated in this scenario.

**Comment by Dyaxler** [comment]
This has been fixed in the new up and coming version of Questie. The tracker has been rewritten and the buttons are now inside the tracker frame so they will no longer appear off screen.
