### ISSUE TITLE
Cuergo's Gold not in the Journey

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1780]
This is a repeatable quest in Tanaris, it starts from Cuergo's Treasure Map, which is made by combining the Lower, Middle and Upper Map Fragments that can be looted from Pirate's Footloker that drop from Southsea mobs in Lost Rigger Cove in Tanaris.

https://classic.wowhead.com/quest=2882/cuergos-gold

![WoWScrnShot_022520_182358](https://user-images.githubusercontent.com/54936174/75271155-070eb180-57fc-11ea-835d-2d66bdc28ccb.jpg)

Version 5.7.2

**Comment by drejjmit** [comment]
Questie uses Blizzards data on zone and that quest is not under Tanaris but "Uncategorized".
Zone would need to be corrected.

![image](https://user-images.githubusercontent.com/15526476/75332546-dde63380-5884-11ea-8d4a-61bf8bd1257f.png)
