### ISSUE TITLE
Chen's Empty Keg Duplicates

### ISSUE THREAD

**Issue by DanJRWalsh** [AeroScripts/QuestieDev#1785]
## Bug description
A quest called "Chen's Empty Keg" is shown 7 or 8 times at random spots in The Barrens. I haven't visited all spots, but the 4 I have, no quests are available there.

## Screenshots
![gif](https://user-images.githubusercontent.com/1395674/75305199-7348df80-5813-11ea-9138-a55457075b4e.gif)

## Questie version
v.5.7.1

**Comment by BreakBB** [comment]
The quest is started by an object (the keg) which has multiple possible spawns in The Barrens. We show some (maybe all) of those possible spawns so users can keep an eye out when they roam the area.
