### ISSUE TITLE
Looking for Group type feature

### ISSUE THREAD

**Issue by orionshock** [AeroScripts/QuestieDev#1786]
Would it be possible to query everyone in the zone (via Addon Whisper) to check if others in the same zone are on a the same quest as you. (opt-in feature ofc)

Questing in Classic seems to work so much better in a party regardless of the quest difficulty.

**Comment by BreakBB** [comment]
With v6 there was a feature added which shows you players "around you" which are on the same quest as you and also their progress.

This helps a lot for finding groups while questing imo.

A LFG feature will add much overhead and is also much work.

@orionshock let us know if you still think such a feature would be good.
