### ISSUE TITLE
Map icons won't refresh unless I click on Hide Questie/Show Questie

### ISSUE THREAD

**Issue by adrianostanley** [AeroScripts/QuestieDev#1787]
## Bug description

Whenever I accept, turn in or even complete a quest objective, my map (M) is not updating with the active quests and objectives. I have to click on Hide Questie and then click on Show Questie so the icons for current quests are added and icons for completed quests/objectives are removed.

I'll be happy to send any necessary information you might need to debug that.

And of course, it's nothing that it's compromising the addon and I can easily live with that. I'm just reporting because it can be a consequence of a more important bug or something you may want to know.

## Screenshots

**1) Accepting the quest**
![WoWScrnShot_022720_161537](https://user-images.githubusercontent.com/4955242/75478304-7c08f500-597c-11ea-805d-6a1d1bb6edd8.jpg)

**2) The map won't show the location of the Power Stones**
![WoWScrnShot_022720_161436](https://user-images.githubusercontent.com/4955242/75478336-917e1f00-597c-11ea-8bce-558094fdb383.jpg)

**3) I click "Hide Questie" and then on "Show Questie"**
![WoWScrnShot_022720_161553](https://user-images.githubusercontent.com/4955242/75478365-9e9b0e00-597c-11ea-9779-ce54ef68ad53.jpg)

**4) Now the map is updated**

## Questie version

Questie v5.7.1

**Comment by BreakBB** [comment]
@adrianostanley There was a bug in the previous versions, when you had disabled the minimap icons.

Make sure to update to v5.7.2 and try again.

**Comment by adrianostanley** [comment]
Perfect. It's fixed. Thank you for that and for the wonderful work you deposit on the addon.
