### ISSUE TITLE
The Black Shield(3) [Horde] not displaying all possible mob drops

### ISSUE THREAD

**Issue by FranciscoSaraiva** [AeroScripts/QuestieDev#1788]
## Bug description
The quest [The Black Shield ](https://classic.wowhead.com/quest=1322/the-black-shield) does not list [Darkfang Lurker](https://classic.wowhead.com/npc=4411/darkfang-lurker) as a possible drop for the [Acidic Venom Sac](url), only [Darkfang Spider](https://classic.wowhead.com/npc=4413/darkfang-spider) is listed as a possible drop.

## Screenshots
![WoWScrnShot_022720_213831](https://user-images.githubusercontent.com/4421684/75489237-c5236e00-59a9-11ea-9abe-9d6f62a21d50.jpg)

## Questie version
v4.0.10 Beta

**Comment by drejjmit** [comment]
You should really update. You're 31 versions from latest.
