### ISSUE TITLE
Quests Log erased

### ISSUE THREAD

**Issue by Velinestra** [AeroScripts/QuestieDev#1789]
## Bug description

I updated to Questie v5.7.2 today. When I logged in my character, all quests were gone.

## Screenshots

![WoWScrnShot_022820_161746](https://user-images.githubusercontent.com/61603232/75588370-81cb0d00-5a46-11ea-984d-62ed31d2ed04.jpg)

**Comment by BreakBB** [comment]
@Velinestra Some other users reported something similar. You should be able to do a simple `/reload` to show them. They're not gone, but simply not shown, which is weird since Questie does nothing with the quest log.

**Comment by Velinestra** [comment]
I had reverted to v5.7.1 and still nothing. The /reload did work (on v5.7.1). Thank you. Also, just to note, logging off to the desktop and  logging back in to the game, did not work. I had to explicitly use /reload while in-game.

**Comment by Shiroma51** [comment]
mine is also blank. Disabled the addon  and have access to the quests again.

**Comment by BreakBB** [comment]
@Shiroma51 Try a `/reload` and if that is not working deleting the "cache" and "WTF" folders.

Blizzard fucked something up with their latest patch.

**Comment by Nenuvah** [comment]
FYI: reverting to quiestie v5.6.0 fixes this issue

**Comment by BreakBB** [comment]
@Nenuvah Did you try a `/reload` on v5.7.2? And could you try to update to v5.7.2 again and see if everything is working fine again?
