### ISSUE TITLE
Remove common world drops from QuestieComms

### ISSUE THREAD

**Issue by millinoid** [AeroScripts/QuestieDev#1790]
## Description

Drops like "Pristine Black Diamond" that are shared between most high level mobs always show as an objective on QuestieComms ex: https://i.imgur.com/5OrrC75.png

I feel as if these should be excluded from the feature for less clutter

**Comment by BreakBB** [comment]
Sorry for coming back to this so late. Yes, you're right. I just experienced this with the Libram of Focus which drops to cluttered it shouldn't really show up.

**Comment by BreakBB** [comment]
Fixed with e654b5f82f18059d938bc662c7fba4e19576547f
