### ISSUE TITLE
Map Icons don't update right

### ISSUE THREAD

**Issue by Elwarc** [AeroScripts/QuestieDev#1792]
## Bug description

I am trying to use questie in wow classic to only see where I can pick up low level quests. 
When I now look on my World map it shows all quests and where I can turn in the completed ones.
If I click hide and and show again, it shows everything according to my settings.
If I now complete the objective of a quest, it suddenly shows me where I can turn that in, even tho i turned this option of.
If I click hide and show on the world map again, it shows everything again according to my options
I just tried to turn off all addons, and only have questie active, but the problem persists.
Even deleting all settings in the twitch app, deleting questie and reinstalling it doesn't fix the problem.
Also hitting the reset option in questie doesn't solve this issue

## Screenshots

2 Pictures of my settings, since showing the map without a video seems counterproductive
![World Of Warcraft - Classic Screenshot 2020 03 01 - 13 42 08 25](https://user-images.githubusercontent.com/61653858/75626021-04c5a200-5bc4-11ea-891c-bb1afaaf61d0.jpg)
![World Of Warcraft - Classic Screenshot 2020 03 01 - 13 42 17 89](https://user-images.githubusercontent.com/61653858/75626024-0becb000-5bc4-11ea-8629-0ffec87b8bcc.jpg)

## Questie version

v.5.7.2

**Comment by BreakBB** [comment]
@Elwarc I made some small changes since v5.7.2. Could you try the following version and report if it is working for you?

[Questie-v5.7.2_7-48b38240.zip](https://github.com/AeroScripts/QuestieDev/files/4271885/Questie-v5.7.2_7-48b38240.zip)

**Comment by Elwarc** [comment]
@BreakBB Been trying the version for the past few hours and the issues I had are not occuring anymore

**Comment by BreakBB** [comment]
@Elwarc Perfect, thanks for testing it and coming back to this. You can keep using this version until an official update is released.

Please report back if you encounter more issues.
