### ISSUE TITLE
The Hunter's Path quests not available

### ISSUE THREAD

**Issue by shadowxclone** [AeroScripts/QuestieDev#1795]
## Description
The Hunter's Path is a breadcrumb quest available from two different quest givers. This quest becomes unavailable in-game if you begin Taming The Beast before you pick the quest up, but does not disappear from Questie on the map or minimap.

## Wowhead link
https://classic.wowhead.com/quest=6068/the-hunters-path
https://classic.wowhead.com/quest=6069/the-hunters-path

## Questie version
v5.7.2

**Comment by BreakBB** [comment]
@shadowxclone Thanks for the report. Could you run the following command ingame and report the output?

`/dump IsQuestFlaggedCompleted(6068)`
`/dump IsQuestFlaggedCompleted(6069)`
`/dump IsQuestFlaggedCompleted(6070)`
`/dump IsQuestFlaggedCompleted(6061)`
`/dump IsQuestFlaggedCompleted(6062)`
`/dump IsQuestFlaggedCompleted(6063)`
`/dump IsQuestFlaggedCompleted(6064)`

**Comment by BreakBB** [comment]
@shadowxclone Any news on this?

**Comment by shadowxclone** [comment]
Apologies, missed your original email. Will test it tonight and report back!

**Comment by shadowxclone** [comment]
Ran each line individually. All reported [1]=false, except for /dump IsQuestFlaggedCompleted(6062) which reported [1]=true.
