### ISSUE TITLE
Cursor not Pointing at Right place on Map

### ISSUE THREAD

**Issue by MisterTooh** [AeroScripts/QuestieDev#1800]
Hi AeroScripts!

My Cursor is not pointing at the right location when I mouse of it, it's quite visibly far the the top right and I have to move the visible cursor down to be able to select the Map Regions.

I've disabled all addons and turned on only Questie. I've installed Bug Grabber and Bug Sack but no bugs or errors seem to appear.

I've tried combinations of Addons to see if the issue may be from other addons but no change to the previous result; no issues with cursor, however, the problem DOES appear when the following combination of addons is used:

TomCat's Tours + SimpleMapPlus + Questie

The Problem DOES NOT appear when the following combinations are on:

TomCat's Tours + SimpleMap
TomCat's Tours + Questie
SimpleMapPlus + Questie

Hope that helps if anything. I'm not sure if this info is relevant but I'll also add it: I only install addons via the Twitch Desktop Application and have stopped doing it manually as it did cause me a lot of issues previous to Twitch App. I'm running WoW Classic on a MacBook Pro 15" Mid 2012 - 2.3 GHz Intel Core i7 - NVIDIA GeForce GT 650M 512 MB Intel HD Graphics 4000 1536 MB

I will also advise the above mentioned addon developers respectively of the issue!

Thanks again for taking the time!

**Comment by BreakBB** [comment]
@MisterTooh Hey there. Could you share some screenshots of what exactly you mean with the "cursor"? Moreover are you using the latest Questie version?

**Comment by MisterTooh** [comment]
Hi BreakBB!

Sadly My screenshots don't show cursor (Mouse Pointer) position, but if I want to select Eastern Plaguelands for example, I have to point my visible cursor (Mouse Pointer) to the area located under Silverpine Forest in order to Click Eastern Plaguelands.

I do have the latest Questie installed.

Thank you for your time!

**Comment by BreakBB** [comment]
@MisterTooh Oh wow, that sounds like a real big issue. Not sure if it really caused by Questie or if we can do anything about that on our end. You should notify the developers of the other addons as well! I will try to find some time soon to investigate this.

**Comment by MisterTooh** [comment]
No worries! I've Advised you and the other 2 developers of the Issue, as stated above the issue only persists when all 3 addons are enabled, but not when only 2 are enabled, in the combinations above.

Thanks again!

**Comment by BreakBB** [comment]
Just had a look and if you install "Leatrix Maps" as well, there is also no problem. But I can verify that there is a big issue when enabled both addons you listed above together with Questie.

**Comment by drejjmit** [comment]
How do you even get Tomcat's Tours to work with Questie? There's an issue active but no word from the developer 
<https://www.curseforge.com/wow/addons/tomcats/issues/19>

**Comment by BreakBB** [comment]
The waypoint lines are not working correctly, yes. But that is not really what this issue is about. This is the problem:

![image](https://user-images.githubusercontent.com/33514570/76855124-b9142900-6850-11ea-8481-9194d731d24c.png)

The cursor is at the red dot, but it is highlighting Winterspring.

**Comment by BreakBB** [comment]
@MisterTooh For me the issue also appears with Questie disabled. So it seems not to be related to Questie 🤔

**Comment by Sw0rdy** [comment]
Have you found any solution for this issue? I have tried so many things but nothing changed. Still it highlights another location from my cursor point same like in the picture above.

**Comment by MisterTooh** [comment]
> Have you found any solution for this issue? I have tried so many things but nothing changed. Still it highlights another location from my cursor point same like in the picture above.

I disabled Tomcat Tours, The developer SimpleMap stated he no longer does addons for wow as he stopped playing and as above mentioned TomCat is unresponsive, but I like simplemapplus and questie.
