### ISSUE TITLE
False marker for Missing Diplomat in Theramore

### ISSUE THREAD

**Issue by SpareSimian** [AeroScripts/QuestieDev#1802]
I just finished the final step of the Missing Diplomat quest chain, wherein I'm awarded a ring by Jaina. A false quest marker continues to show up on Archmage Tarvosh in Dustwallow Marsh for a level 38 quest Missing Diplomat. (I do know that he offers Shadowshard Fragments but that quest requires level 39 and he doesn't have a silver "!" over his head while I'm level 31.)

https://classic.wowhead.com/quest=1267/the-missing-diplomat

**Comment by BreakBB** [comment]
@SpareSimian What is the quest that is still showing up? Could you active the quest IDs (Advances Settings) and share a screenshot?

**Comment by SpareSimian** [comment]
Character is currently in Darnassus and phantom quest isn't showing up in Duskwallow Marsh. I've enabled the quest ID (handy!) and will check again when I move her there.

Sorry about lack of template. I'm not sure how I bypassed the issue templates page. I'd searched Github for "missing diplomat" and then probably clicked New Issue from one of the issues I found.

**Comment by SpareSimian** [comment]
I flew her to Theramore and don't see the marker. It's possible it vanished when she dinged level 32 in Duskwood last night. 

I have another two toons that still need this quest chain so I'll watch for this to happen with them.

**Comment by BreakBB** [comment]
@SpareSimian Could you run the following commands and report their output with the affected character?

`/dump IsQuestFlaggedCompleted(1250)`
`/dump IsQuestFlaggedCompleted(1264)`
`/dump IsQuestFlaggedCompleted(1265)`
`/dump IsQuestFlaggedCompleted(1250)`
`/dump IsQuestFlaggedCompleted(1324)`
`/dump IsQuestFlaggedCompleted(1267)`

**Comment by SpareSimian** [comment]
All of those are true. (You have 1250 in there twice.) It was after completing 1267 and getting the ring that I saw the phantom marker.

**Comment by BreakBB** [comment]
@SpareSimian Thanks for this fast response. I meant `1266` instead of a second time `1250` (failed the copy-paste). Could you check that ID as well?

**Comment by SpareSimian** [comment]
1266 is also true.

**Comment by BreakBB** [comment]
Okay, that means you did the complete quest line in Duskwallow Marsh and didn't skip any quests (which most likely means none of the quests can be skipped).

The only reason I can think of that the quest was shown is a possible desync. Which happens sometimes and is always fixed by a `/reload`. We're investigating this issue for a long time now and are rewriting parts of the code to stop this from happening. The past updates already decreased the chance of a desync, but apparently it is not fixed completely yet, sorry.

**Comment by SpareSimian** [comment]
The only thing I can think of is that maybe the marker for 1267 didn't properly clear after I completed the quest. Jaina and Tarvosh teleport back to her tower from the swamp so perhaps there's some glitch from that. A common complaint on Wowhead was that they teleported too fast to turn in the quest and people would have to find her in her tower to turn in the final step.  I recall logging out and back in while in Theramore to see if it was an addon glitch and it didn't remove the phantom marker. But it's gone now, so maybe some other action cleared it.

**Comment by SpareSimian** [comment]
I suggest closing this and I can reopen it if I see it again.

**Comment by BreakBB** [comment]
Yeah, that sounds good to me. Thanks for the detailed report and for taking your time to investigate the issue!

**Comment by SpareSimian** [comment]
It's 1267! I just did this on my 31 warrior. I turned in 1265, in which one kills Handel. I then spoke to Jaina to get my ring (quest 1267). So it looks like her quest "sticks" and doesn't disappear once I turn it in until I resync in some way.
