### ISSUE TITLE
Trek to Ashenvale

### ISSUE THREAD

**Issue by arnissmarins** [AeroScripts/QuestieDev#1806]
Quest shows as available when it's not, some chain is making npc disapear.

https://classic.wowhead.com/quest=990/trek-to-ashenvale

 Version: 5.7.2

**Comment by drejjmit** [comment]
This is a Blizzard problem not a Questie problem:
https://us.battle.net/support/en/article/247288

**Comment by BreakBB** [comment]
Also related to #754
