### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by AnjelVixen** [AeroScripts/QuestieDev#1808]
Hi!  First off let me say I love this addon!  My only issue is that I have to go into options everytime I sign on to check the box for showing my quests.  I'm not sure if I'm doing something wrong or if this is a bug.

Thanks!
AV

**Comment by BreakBB** [comment]
@AnjelVixen Hey could you share a screenshot which option you mean and say what version you use?

**Comment by AnjelVixen** [comment]
@BreakBB  No problem!  Here you go!  Let me know if you need anything else!  And thank you!  :)
![3-8-2020 4-51-08 PM - Questie tracker screen](https://user-images.githubusercontent.com/61918953/76171304-efbab700-615f-11ea-900b-d3f9c1b2e745.jpg)

**Comment by AnjelVixen** [comment]
Any news on this?  :)  Thanks for your help!

**Comment by BreakBB** [comment]
@AnjelVixen Could you try to check the option directly on the Blizzard side. The option in Questie is just a "shortcut" for it.

![image](https://user-images.githubusercontent.com/33514570/76357208-909fa280-6317-11ea-87e3-de3af774de80.png)

**Comment by AnjelVixen** [comment]
That is checked on all tunes...was still doing it, however it seems to have been corrected, for one reason or another.  It's possible there was a conflicting addon, but if you guys did anything to fix, it worked and thank you!!  :)

**Comment by AnjelVixen** [comment]
toons*   lol sorry...no sleep

**Comment by BreakBB** [comment]
@AnjelVixen Thanks for coming back to this and we are glad it is fixed
