### ISSUE TITLE
The pointing marker...

### ISSUE THREAD

**Issue by zeezar** [AeroScripts/QuestieDev#181]
The pointing marker over the characters which is pointing towards the quest is gone..

What have I pressed, and how do I get it back?

Zeezar

**Comment by Dyaxler** [comment]
You might have dragged it off screen by accident... look in your characters layout-cache.txt file located in: 
`%wowroot% \ WTF \ Account \ %username% \ Nostalrius Begins PvE \ %charactername% \`

You should see something like this:
```
Frame: TomTomCrazyArrow
FrameLevel: 1
X: 356
Y: -606
```
Zero out those values and your arrow should appear in the middle of your screen.

Also check your !Questie.lua file located here:
`%wowroot% \ WTF \ Account \ %username% \ SavedVariables \`

Make sure the ["ArrowEnabled"] value is set to true

**Comment by zeezar** [comment]
THANKS IT WORKS.....

**Comment by Schaka** [comment]
There should probably be a slash command for this in the future (same for the tracker position).
Could also be added to the Wiki for this repository.

**Comment by Dyaxler** [comment]
It's on my To Do list actually. :)

**Comment by Dyaxler** [comment]
Added a code fix to prevent dragging arrow off screen in v2.3
