### ISSUE TITLE
Share localized info

### ISSUE THREAD

**Issue by Warkdev** [AeroScripts/QuestieDev#1811]
## Description
Hello guys, 

I'm willing to localize my add-on (bestinslot classic), would you mind if I reuse the dataset that you already generated for quests and npc? That would be really nice. I'd provide you back credit of course for it. 

In the opposite, I'd have to extract them manually from private core database as you did which is.. Meh. 

Thanks for you feedback, 😊

Wark

**Comment by BreakBB** [comment]
@Warkdev Thanks for asking upfront and yes, feel free to reuse our data. You may also want to check [the scraper repo](https://github.com/BreakBB/wowhead_scraper) which we use to extract such data off Wowhead.

Providing the credit to us (the Questie team) is more than enough :) Good luck with your addon 💪

**Comment by Warkdev** [comment]
Many thanks! ❤️
