### ISSUE TITLE
Questie should have a Update Reminder Feature

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1815]
## Description

When you sign on, Questie should show a message letting you know if your version of Questie is out of date so that people have a bit of a reminder to update Questie more often.

A lot of other addons do this, GTFO (https://www.curseforge.com/wow/addons/gtfo) is probably the most simple example I can think of for examples of the code. But Elv, Classic Threat, Details, etc. all do it.

**Comment by Gogo1951** [comment]
I've leveled at least 2 toons to 60 on Horde and Alliance now, and I group as often as I can. At least once a week I find someone running a version of Questie that hasn't been updated since before shared quest objectives was added to the tooltip. Ha.

**Comment by BreakBB** [comment]
@Gogo1951 This is already included in Questie which sends a simple chat message once you encounter someone with a version higher than your own:

`Questie: You have an outdated version of Questie! Please consider updating!`

or

`Questie: A Major patch for Questie exists! Please update as soon as possible!`

I will try to make it more visible.
