### ISSUE TITLE
QUESTIE: BLIZZARD QUEST LOG: Some accepted quests missing from Blizzard Quest Log and also don't register with Questie as Accepted

### ISSUE THREAD

**Issue by Jnotay** [AeroScripts/QuestieDev#1816]
## Bug description
Questie missing quests previously accepted (before the 3/9 update) eg. all my Westfall quests aren't showing, but Darnassus quests do show in the log. Using /reload fixes the issue.

## Screenshots
![image](https://user-images.githubusercontent.com/1168531/76391681-3f9aa900-632d-11ea-9d90-5436f4b174c6.png)

## Questie version
5.7.2

**Comment by BreakBB** [comment]
@Jnotay You should try a `/reload`. Looks like Blizzard added another bug (as with the previous patch) which shows the quest log either empty or just partly.

If that doesn't help you should delete the `cache` and `WTF` folder. **NOTE: This will also wipe your game and addon settings, but might be the only solution**
