### ISSUE TITLE
Quest Log empty

### ISSUE THREAD

**Issue by HQOFIQ** [AeroScripts/QuestieDev#1823]
Hi - first let me say that Questie is a fabulous addon, which saved me a lot of time and tears playing WOW classic for months now ...
I experience an issue (now for the second time and that is why I report it here) that my quest log seems empty while full with 20 active quests. The quests are active and I can track progress on them or finish them and take them back to the questgiver. Just the quest log itself is "empty" ... Various inquiries from my side within the community gave me the hint that questie seems to have the problem ... I tried to find a solution within the FAQs but none so far to be found ...
I am counting on you, guys!
brgds and keep up the good work!

**Comment by drejjmit** [comment]
You'll have to ask Blizzard to fix this. Nothing we can do about it. Just ``/reload`` or relog.
<https://eu.forums.blizzard.com/en/wow/t/wow-clasic-empty-quest-logg/129678>
<https://eu.forums.blizzard.com/en/wow/t/the-matron-protectorate-quest-and-messed-up-quest-log/130235>

**Comment by 1mentat** [comment]
This started happening with 5.7, it's fine in 5.6. Nothing I've tried aside from reinstalling 5.6 (or disabling Questie) seems to help.

**Comment by HQOFIQ** [comment]
/reload worked for me, thanks to @drejjmit ... in case that doesn't work, 5.6 works as well (tried that before, @1mentat) ... thank you all!

**Comment by drejjmit** [comment]
@1mentat Only reason older versions works is because you are reloading/restarting. Try upgrading again.

**Comment by tjwrona1992** [comment]
Yeah this happened to me once or twice, /reload or logging out and back in seemed to fix it. Seems like a bug in WoW though, probably not Questie. (Although I'm not 100% sure)

**Comment by 1mentat** [comment]
Thanks, reloading did work.
