### ISSUE TITLE
Quest "Threat of the Winterfall" not showing ! marker on map.

### ISSUE THREAD

**Issue by Slothtimistic** [AeroScripts/QuestieDev#1824]
## Description

Even though the quest is available from Donova Snowden, the ! indicating there is a quest available on the map is not showing. Other quest objectives for this NPC involving the Linken storyline (It's a Secret to Everybody, The Videre Elixir) are showing on the map.

## Wowhead link

https://classic.wowhead.com/quest=5082/threat-of-the-winterfall

## Screenshots

https://i.imgur.com/5M1i3Mp.jpg

https://i.imgur.com/VHS75w3.jpg

https://i.imgur.com/n2cq2cL.jpg

## Questie version

5.7.2 and 5.8.0 both encounter this issue.

**Comment by drejjmit** [comment]
I don't think that requires prequest "[56] Trouble in Winterspring!"

[14:44:06] Dump: value=IsQuestFlaggedCompleted(6603)
[14:44:06] [1]=false
[14:44:15] Dump: value=IsQuestFlaggedCompleted(5082)
[14:44:15] [1]=true

Can you see "[56] Trouble in Winterspring!" on the map?

**Comment by Slothtimistic** [comment]
You are correct, Trouble In Winterspring is available and showing on the map https://i.imgur.com/bYKD5z9.jpg but Threat of the Winterfall was available as well, it is not required.

**Comment by Slothtimistic** [comment]
It also seems that the objective complete icon is not showing for quest The Videre Elixir
https://i.imgur.com/TXleXuW.jpg
https://i.imgur.com/1rvbN4A.jpg

**Comment by drejjmit** [comment]
I think "Trouble in Winterspring!" breadcrumb quest locks you out from picking it up. You either have to turn that in or abandon it. So it's technically available.

**Comment by gouletr** [comment]
> I think "Trouble in Winterspring!" breadcrumb quest locks you out from picking it up. You either have to turn that in or abandon it. So it's technically available.

That's quite possible. Unfortunately I turned-in the quest so I can't verify right now. 😭
