### ISSUE TITLE
Questie shows "Erion Shadewhisper" and "Erion's Behest" on the map but they are not available.

### ISSUE THREAD

**Issue by tjwrona1992** [AeroScripts/QuestieDev#1825]
## Description
The quest markers for these quests show on the minimap but I am not able to accept these quests. It looks like if you have already completed an alternate rogue quest these are no longer available. (There are similar quest chains available in Ironforge and Stormwind and these quest chains seem to be mutually exclusive.)

## Wowhead link
https://classic.wowhead.com/quest=2259/erion-shadewhisper
https://classic.wowhead.com/quest=2260/erions-behest

## Screenshots
![World Of Warcraft - Classic Screenshot 2020 03 15 - 14 39 35 68](https://user-images.githubusercontent.com/44857895/76708138-f64eae80-66ca-11ea-8434-8d4212842f8b.png)
![World Of Warcraft - Classic Screenshot 2020 03 15 - 14 39 50 05](https://user-images.githubusercontent.com/44857895/76708142-fd75bc80-66ca-11ea-96cf-1ca7393a6e18.png)

## Questie version
v5.7.2

**Comment by BreakBB** [comment]
@tjwrona1992 Could you run the following command and report the output:

`/dump IsQuestFlaggedCompleted(2281)`

**Comment by Nerillida** [comment]
I have tested these. The three chains, 
Erion Shadewhisper breadcrumb for Erion's Behest
To Hulfdan! breadcrumb for Kingly Shakedown
SI:7
are breadcrumb quests for 
Redridge Rendezvous -> Alther's Mill

They can all be done simultaneously until Redridge Rendezvous is accepted.

Despite what Wowhead says, the level 10 rogue quests are not prerequisites.

**Comment by tjwrona1992** [comment]
@BreakBB the command returns

`[1]=true`

**Comment by BreakBB** [comment]
Related to #1466 and it seems the fix wasn't completely correct.

**Comment by BreakBB** [comment]
@Nerillida Are the prequests listed on the [SI: 7 quest](https://classic.wowhead.com/quest=2300/si-7) required at all for it to show up or are those optional breadcrumb quests as well?

**Comment by Nerillida** [comment]
None of the three routes to Redridge Rendevous, or indeed going directly there require the level 10 quests. BoringlyIlevelleda rogue to level 16 without doing the level 10 quests to confirm.

**Comment by BreakBB** [comment]
@Nerillida Sorry for asking again: So you do **not** need to do any of the three level 10 quests in order to accept SI: 7?

**Comment by Nerillida** [comment]
Confirm, you do not have to do any of the level10 quests.

**Comment by BreakBB** [comment]
Perfect, thank you very, very much for testing those quests in detail!

**Comment by Nerillida** [comment]
I think we all have some degree of OCD, mine's just really bad. :)
