### ISSUE TITLE
3 Quest issue

### ISSUE THREAD

**Issue by sergib18** [AeroScripts/QuestieDev#1826]
Quest nr 1: "The Essence of Aku' Mai" (https://classic.wowhead.com/quest=6563/the-essence-of-akumai) (quest mark not showing on map) need no pre quest "Trouble in the Deeps" (https://classic.wowhead.com/quest=6562/trouble-in-the-deeps). 

Quest nr 2: "The Ashenvale Hunt" (https://classic.wowhead.com/quest=6383/the-ashenvale-hunt) following quest "Ursangous' s Paw" (https://classic.wowhead.com/quest=23/ursangouss-paw) , "Shadumbra's Head" (https://classic.wowhead.com/quest=24/shadumbras-head) , "Sharptalon's Claw" (https://classic.wowhead.com/quest=2/sharptalons-claw) quest mark not showing on map

Quest nr 3: "The Runed Scroll" (https://classic.wowhead.com/quest=3513/the-runed-scroll) quest mark not showing on map

**Comment by BreakBB** [comment]
@sergib18 Thanks for the report. Please add the required Wowhead links so it is easier for us to check the quests and verify the report.

**Comment by sergib18** [comment]
Sorry my first report. Thanks
