### ISSUE TITLE
Jonespyre's Request

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#1829]
Just stumbled across this quest in Feathermoon Stronghold as a lvl 51 mage.
https://classic.wowhead.com/quest=3788/jonespyres-request
It was not shown on the map/minimap.
Questie v5.9.0.

After handing it in, the next quest in the questline showed up fine.

**Comment by BreakBB** [comment]
Duplicate of #1754

**Comment by StraussWylde** [comment]
This quest shows up in Stormwind (level 50) on the map but NPC is not there, of course.

**Comment by drejjmit** [comment]
This is probably due to the map change introduced in Wrath of the Lich king, when Stormwind Harbour got added.
