### ISSUE TITLE
Require Shift key to move Quest Tracker

### ISSUE THREAD

**Issue by MarkusNemesis** [AeroScripts/QuestieDev#183]
Hello,

I've made this change to my personal copy of Questie, however I feel it should be a standard feature beings as I got a fair bit of interest when I said I did it.

I'd like to request that the Shift key be required when clicking and dragging the Quest Tracker window, to allow it to be moved.

I've had many issues with the Quest Tracker window flying around the screen because I accidentally clicked on it.

Any other kind of locking mechanism is fine, I just found using shift easiest and most convenient.

Cheers,

**Comment by Dyaxler** [comment]
Fixed in v2.3
