### ISSUE TITLE
Hide objectives based on tracked quests

### ISSUE THREAD

**Issue by Zeliax** [AeroScripts/QuestieDev#1834]
Hi. 

I've recently started leveling a horde alt, and in the Barrens the map is "all fucked up" and cluttered with quest objectives. I know it's possible to "unclutter" the map and I like having the quest objectives shown, but I was wondering if it was possible to hide quest objectives, and only show objectives for tracked quests?

**Comment by BreakBB** [comment]
Duplicate of #1224
