### ISSUE TITLE
Missing Quest Marker: Reclaimed Treasures

### ISSUE THREAD

**Issue by Jakobud** [AeroScripts/QuestieDev#1835]
## Description
Missing Quest Marker: Reclaimed Treasures (Horde)

## Wowhead link
https://classic.wowhead.com/quest=2342/reclaimed-treasures

The quest is available in Undercity right next to the Flight Master. It's available at level 33. It does not show up on the map or minimap when using Questie.

## Questie version
5.10.0 0 fd3ff918

**Comment by BreakBB** [comment]
@Jakobud The quest is "designed" for level 43, so it was most likely not shown for your character. Could that be possible? You need to adjust the respective setting for quests to show up for than 7 level above your own.

**Comment by Jakobud** [comment]
That is probably the problem. I would think Questie would have an option to simply show a Quest marker when the minimum level requirements for that quest have been met (ie, when you see a quest ! above an NPC it should be also appearing via Questie markers).

Thanks,

**Comment by BreakBB** [comment]
Yeah, we want to add that option or simply change the default behaviour. Simply didn't have the time yet
