### ISSUE TITLE
Show Quest Level in Quest Log Title, Quest NPC Title and Quest NPC Gossip page

### ISSUE THREAD

**Issue by Jakobud** [AeroScripts/QuestieDev#1837]
## Description
It would be nice if Questie would add the quest level in the Title/Name of the quest in several places. For example instead of showing:

`Goblin Sponsorship` it would prepend the quest level: `[37] Goblin Sponsorship`

It would need to happen in the following places:

1. In your quest log. The list of quests should show the quest level prepended to each quest name
2. In your quest log when you click on a quest to read about it, at the top the name/title of the quest the level should be prepended
3. When you talk to an NPC who has multiple quests and it shows their "gossip" page where it lists the quests available by name. It should prepend the quest level
4. When you talk to an NPC about the details of the quest and it shows the quest name/title at the top it should prepend the quest level.

The quest levels should appear like so:

[15] - A normal level 15 quest - Example: https://classic.wowhead.com/quest=1136/frostmaw
[28+] - An elite, non-dungeon, non-raid quest - Example: https://classic.wowhead.com/quest=1107/encrusted-tail-fins
[37d] - A dungeon-specific quest. Elite is implied. Example: https://classic.wowhead.com/quest=1048/into-the-scarlet-monastery
[60r] - A raid-specific quest. Elite is implied. Example: https://classic.wowhead.com/quest=6824/hands-of-the-enemy

I've seen other addons add this functionality in the past but cannot remember which ones do this. Seems like a perfect addition for Questie.

**Comment by Gogo1951** [comment]
It does this now! (=

![image](https://user-images.githubusercontent.com/55365231/90712147-fc434f80-e267-11ea-9707-f42a717c643a.png)

and when you shift click:

[[55] Deadwood Ritual Totem (8470)]
