### ISSUE TITLE
Lost Deathstalkers: Availability isn't strict enough

### ISSUE THREAD

**Issue by Treeston** [AeroScripts/QuestieDev#1838]
## Description
Even after accepting **Wild Hearts** directly, its breadcrumb **Lost Deathstalkers** is still shown as available.

If **Wild Hearts** is completed, **Lost Deathstalkers** should become unavailable.

## Wowhead link
https://classic.wowhead.com/quest=428/lost-deathstalkers
https://classic.wowhead.com/quest=429/wild-hearts

## Screenshots
![image](https://user-images.githubusercontent.com/14020072/77215215-3969b100-6b13-11ea-85e9-d854f7528fb1.png)

## Questie version
`5.10.0 0 fd3ff918`

**Comment by Treeston** [comment]
After relogging, the quest has disappeared from the map.

This might be a systemic issue in removing unavailable quests from the map at runtime?

**Comment by Anadryel** [comment]
Hi, 
I have the same issues but relogging or reload UI doesnt change the fact;
![Capture](https://user-images.githubusercontent.com/62699184/77640457-b86b4900-6f5a-11ea-90b8-6eb5e11cfb95.PNG)

What can i do? Shift+click doesnot work

**Comment by BreakBB** [comment]
@Anadryel The frame in your screenshot belongs to Azeroth Auto Pilot, not Questie. Try `/aap skip`

**Comment by BreakBB** [comment]
@Treeston We're trying to improve Questie with every update and reduce the chance for such issues to happen. There is not much we can do directly when a quest shows up but is removed after a `/reload`. Related #860
