### ISSUE TITLE
Quest Map tooltip - Show quest level

### ISSUE THREAD

**Issue by MarkusNemesis** [AeroScripts/QuestieDev#184]
Currently the map shows the quest level as the level it becomes unlocked, however it would be nice to see what level the quest is once you have it.

For example, I levelled up to 40 and went to Tanaris, as a whole heap of quests appeared there. I accept a quest, and add it to my tracker only to see that it's a red level 46 quest.

To save people's future frustration, it would be nice to see the quest level of the actual quest, not the unlock level.

Cheers.

**Comment by Dyaxler** [comment]
That unfortunately is hard coded in the database. I'd have to change all the levels in the WHOLE database. In essence it's by-design as that is how Blizzard handles quests. You are able to obtain a quest 10 levels below the generally acceptable level that most players choose to complete it.

I'll look into the possibility of adding another user-preference toggle. A filter to NOT show a quest unless it's X number of levels from current level.

**Comment by MarkusNemesis** [comment]
That would be a workable solution. Cheers.

**Comment by Dyaxler** [comment]
Filter added in v2.4
