### ISSUE TITLE
Quest Horde Trauma

### ISSUE THREAD

**Issue by isitLoVe** [AeroScripts/QuestieDev#1842]
## Description
Questie shows the Quest Horde Trauma available but it is not. Maybe because i have completed the Quest Triage already.

## Wowhead link
https://classic.wowhead.com/quest=6623/horde-trauma
https://classic.wowhead.com/quest=6622/triage

## Screenshots
-

## Questie version
5.10.0

**Comment by BreakBB** [comment]
This should be fixed with a15ff7ebb5bce8217801927ceeb5d86f08befd88

Could you share a screenshot for the quest showing up in OG? And also run the following commands and report the output:

`/dump IsQuestFlaggedCompleted(6623)`
`/dump IsQuestFlaggedCompleted(6622)`
