### ISSUE TITLE
Quest Runecloth not showing up even though I'm friendly with Timbermaw

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1846]
As the title says, the quest offered at Friendly Timbermaw rep by Meilosh isn't showing up on the map or the journey.

https://classic.wowhead.com/quest=6031/runecloth

![WoWScrnShot_032920_014201](https://user-images.githubusercontent.com/54936174/77837242-d73a2d00-715e-11ea-86cc-ee10e56606eb.jpg)

Version 5.10.0

**Comment by BreakBB** [comment]
@Cerby3BR Sorry for the late response. There was a bug with reputation changes not updating the available quests. This has been fixed with 10e250fa9131e411a1eec40f75b69b01e8b3b8c3 and will be released with the upcoming Phase 4.
