### ISSUE TITLE
Abandoning a quest marks it as complete

### ISSUE THREAD

**Issue by MarkusNemesis** [AeroScripts/QuestieDev#185]
Hello,

To stem on from my previous issue, after abandoning a quest, it no longer shows up on the map as an available quest again, even after toggling Questie.

**Comment by Dyaxler** [comment]
Yeah, I noticed that too and completely forgot to look into that. Questie has the following behavior flags for quests...
```
1 = complete
0 = seen
-1 = abandoned
```
...I'll track down the function that displays quests on the map and see if I can't add the -1 flag to the "show quest on map" loop.

**Comment by Dyaxler** [comment]
Bug is fixed in v2.4
