### ISSUE TITLE
The Ichor of Undeath

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1850]
## Description
The quest errors
error forwarding quest goal for the ichor of undeath

## Wowhead link
https://classic.wowhead.com/quest=8256/the-ichor-of-undeath

## Screenshots
![WoWScrnShot_040120_191619](https://user-images.githubusercontent.com/5685512/78166833-b79c5080-744d-11ea-9b68-ca19201d5807.jpg)

## Questie version

5.10.0_fd3ff918

**Comment by Djfe** [comment]
since it's easy to get the item from the ah/my bank, I'll restart the quest once this is fixed, so I can test the fix.

**Comment by Djfe** [comment]
I just tested this fix (I downloaded the development stage of this mod right after the patch)
It works, no error, but it doesn't place a marker on the Ruins of Eldarath:

> Powerful undead, such as the lingering highborne who wander the Ruins of Eldarath, are sometimes so infused with evil that it coalesces into a sickly greenish goo. To the living, this substance is known as ichor of undeath.

mobs that drop it (according to the comments):
https://classic.wowhead.com/npc=6116/highborne-apparition
https://classic.wowhead.com/npc=6117/highborne-lichling

further mobs according to wowhead drop tables:
https://classic.wowhead.com/npc=7864/lingering-highborne
https://classic.wowhead.com/npc=6118/varothens-ghost

**Comment by Djfe** [comment]
correction: it still errors, if you don't have the item in your inventory.
![WoWScrnShot_041320_204238](https://user-images.githubusercontent.com/5685512/79149472-8154be80-7dc7-11ea-8a7a-07c79905fc80.jpg)

**Comment by Djfe** [comment]
second correction:
the last screenshot was after I dropped the item and used /reload

restarting the quest with no item, it actually shows markers on the map (in azshara and in eastern plaguelands etc.)
but only after restarting the quest?

it still errors even after restarting ^^

![WoWScrnShot_041320_204508](https://user-images.githubusercontent.com/5685512/79149762-ec9e9080-7dc7-11ea-8fdb-765583805c15.jpg)

**Comment by Djfe** [comment]
@BreakBB please reopen this issue

**Comment by BreakBB** [comment]
This doesn't really make any sense to me, but I will investigate. Thanks for testing this :+1:

**Comment by Djfe** [comment]
This error is still happening in 5.10.3 only the lua line is 774 instead of 772/768 like in earlier screenshots

Are you able to understand the german error message?

**Comment by Djfe** [comment]
is it possible to produce a lua error with a stack trace? I have an add-on called swatter (part of auctioneer), that let's me output lua errors and copy them to my clipboard

Or is there another way how I can help with debugging?

**Comment by BreakBB** [comment]
@Djfe Sorry for not keeping you updated on this. It is really hard to find the reason for this because I can't test this quest and don't know another way to reproduce it.

I am using BugGrabber + BugSack to catch errors and investigate them. But I am not sure if this issue is caused by a logical or database problem.

The error states that some spawn data is/got corrupted and is a number instead of a table (with coords). I assume it's a logic error, but diving into that part of the code is really not easy.

**Comment by Djfe** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/5685512/82947143-da576b00-9f9f-11ea-9be5-080a02ac7a6b.jpg)
It sadly doesn't produce a lua error that I could share with you here

**Comment by BreakBB** [comment]
We think we found the issue and the fix will be easy.
Keep an eye out for an update :+1:

**Comment by Djfe** [comment]
Amazing thank you for investing the time :)
I'll test again once it's out

**Comment by Djfe** [comment]
I can confirm that this fix works :) (I tested it with the masterbranch)

**Comment by BreakBB** [comment]
@Djfe Perfect, thanks! I am glad this got finally fixed.
