### ISSUE TITLE
Questie Map Icon Issue

### ISSUE THREAD

**Issue by Vequis-uk** [AeroScripts/QuestieDev#1851]
## Bug description
Icons on the map related to questie have stopped being hidden between sessions or /reloads 

## Screenshots

![image](https://user-images.githubusercontent.com/60845140/81471082-9403bd00-91e6-11ea-8056-832fcd3eadf8.png)

## Questie version
v5.10.2

**Comment by Vequis-uk** [comment]
Unfortunately, I am still having this issue. Even after complete reinstall and settings deleted.

**Comment by drejjmit** [comment]
Please use the issue template.

**Comment by Vequis-uk** [comment]
Sorry I have had a look and cannot find it, could you link it please and I will amend.

Not used github too much, thank you 👍

**Comment by drejjmit** [comment]
https://raw.githubusercontent.com/AeroScripts/QuestieDev/master/.github/ISSUE_TEMPLATE/bug_report.md

Questie version and if it is all icons or just PvP icons for example.

**Comment by Vequis-uk** [comment]
Sorry about that, I understad its frustrating.

Updated original post and yes it appears to be all questie related icons, I have tested it with just questie turned on and it still persists.

Also tried a complete settings wipe and it persisted, very odd.

**Comment by BreakBB** [comment]
@Vequis-uk This is a known issue and I an very sure there is an existing issue for this already. Can't find it though. We're looking into this, sorry for your trouble.

**Comment by Vequis-uk** [comment]
Ah, very sorry if I have created a duplicate.

Really appreciate the work that goes into this!

**Comment by BreakBB** [comment]
No worries. Thanks for reporting issues, it helps us and all the users to make Questie even better.

I will leave this open since I haven't found the other issue (yet).
