### ISSUE TITLE
Warrior quests showing when not available

### ISSUE THREAD

**Issue by Zardilann** [AeroScripts/QuestieDev#1852]
The quest https://classic.wowhead.com/quest=1679/muren-stormpike still shows as available on the map, despite having completed https://classic.wowhead.com/quest=1638/a-warriors-training
which disables it.

**Comment by Zardilann** [comment]
Once I completed https://classic.wowhead.com/quest=1666/marshal-haggard the quest markers disappeared.

**Comment by Zardilann** [comment]
Abandoning https://classic.wowhead.com/quest=1639/bartleby-the-drunk enabled https://classic.wowhead.com/quest=1678/vejrek to be picked up, where it was not available before.

**Comment by BreakBB** [comment]
@Zardilann Did you check that "A Warriors Training" is really disabled by "Muren Stormpike"? The data on Wowhead is not trustworthy for all quests and other users reported you can do more than just one of the quests.

**Comment by Zardilann** [comment]
While I haven't tested it, I'm fairly certain that the exclusivity of "Bartleby the Drunk" and "Vejrek" also includes https://classic.wowhead.com/quest=1683/vorlus-vilehoof

I'll test "A Warrior's Training" and "Muren Stormpike" to be sure.

**Comment by Zardilann** [comment]
While you can complete https://classic.wowhead.com/quest=1638/a-warriors-training and https://classic.wowhead.com/quest=1679/muren-stormpike and https://classic.wowhead.com/quest=1684/elanaria all on the same character, only one of the follow-up quest is available to be held in your log at the same time, and will close the others down for good, once you complete one of https://classic.wowhead.com/quest=1683/vorlus-vilehoof or https://classic.wowhead.com/quest=1639/bartleby-the-drunk or https://classic.wowhead.com/quest=1678/vejrek

After completing one of the above, https://classic.wowhead.com/quest=1686/the-shade-of-elura and https://classic.wowhead.com/quest=1666/marshal-haggard and https://classic.wowhead.com/quest=1680/tormus-deepforge could all be picked up and completed on the same character.

**Comment by BreakBB** [comment]
Thanks for testing this and explaining it in detail :pray:

This should now be easy to correct for us.
