### ISSUE TITLE
[38] The Missing Diplomat Questie bug

### ISSUE THREAD

**Issue by nicklaskittelmann** [AeroScripts/QuestieDev#1853]
When having defeated Private Hendel in https://classic.wowhead.com/quest=1324/the-missing-diplomat, hand in the quest on site to Archmage Tervosh, and then directly go to Theramore and talk to Lady Proudmoor and complete her quest to get the ring, then Questie still shows that [38] The MIssing Diplomat is available in 3 locations in Dustwallow March. It is not available. Neither the Archmage nor Lady Proudmoor has any quests available.

![WoWScrnShot_040520_090525](https://user-images.githubusercontent.com/42350344/78468966-d2581900-771c-11ea-8deb-3093baa0f9b0.jpg)

## Questie version
5.10.0

**Comment by BreakBB** [comment]
@nicklaskittelmann Is it still showing as available to you or did a relog helped?

**Comment by nicklaskittelmann** [comment]
No, it's gone now. I'm still running the same version of Questie, so I guess it was the relog that helped! Thanks!

**Comment by BreakBB** [comment]
Closing this as it is related to #860
