### ISSUE TITLE
Quest missing: Compendium of the Fallen

### ISSUE THREAD

**Issue by Treeston** [AeroScripts/QuestieDev#1855]
## Description
The quest **Compendium of the Fallen** isn't being displayed as available on a Level 30 Troll.

## Wowhead link
https://classic.wowhead.com/quest=1049/compendium-of-the-fallen

## Screenshots
![image](https://user-images.githubusercontent.com/14020072/78712529-01d37500-7919-11ea-8087-5ccf5091bcdd.png)

## Questie version
`5.10.0 0 fd3ff918`

**Comment by BreakBB** [comment]
Since it is a level 38 quest by default this quest is not (yet) displayed by Questie even though you can accept it. Just as with low level quests only +-7 level around your own are shown.
