### ISSUE TITLE
Iron Coral missing prerequsitive

### ISSUE THREAD

**Issue by Zardilann** [AeroScripts/QuestieDev#1857]
https://classic.wowhead.com/quest=1708/iron-coral needs https://classic.wowhead.com/quest=1704/klockmort-spannerspan, as I wasn't able to pick up the quest at level 20.

**Comment by Zardilann** [comment]
Now hit 31, and it's still not available. I still need to complete https://classic.wowhead.com/quest=1701/fire-hardened-mail which should open up https://classic.wowhead.com/quest=1704/klockmort-spannerspan which then opens https://classic.wowhead.com/quest=1708/iron-coral

**Comment by BreakBB** [comment]
@Zardilann Looks like your previous report on this quest is not valid anymore then #1230 

Maybe you just need to complete "Fire Hardened Mail (1701)" to unlock "Iron Coral"?

**Comment by Zardilann** [comment]
I expect that to be true. Will finish 1701 this weekend.

**Comment by Zardilann** [comment]
After completing https://classic.wowhead.com/quest=1701/fire-hardened-mail it opens up for https://classic.wowhead.com/quest=1782/furens-armor for all races, and then:
Dwarf/Gnome: https://classic.wowhead.com/quest=1704/klockmort-spannerspan
Human: https://classic.wowhead.com/quest=1700/grimand-elmore
Night Elf: https://classic.wowhead.com/quest=1703/mathiel
After completing one of these, it opens up for all races:
https://classic.wowhead.com/quest=1708/iron-coral and https://classic.wowhead.com/quest=1705/burning-blood and https://classic.wowhead.com/quest=1710/sunscorched-shells

**Comment by Zardilann** [comment]
https://classic.wowhead.com/quest=1710/sunscorched-shells did not appear on the map (playing human).

**Comment by SpareSimian** [comment]
I just completed the whole thing at level 34, and got a lot of XP in spite of being high-level. The gauntlets were slightly better than what I was wearing. The pants are not as good as the quest reward from the Deadmines quest chain. The helm is not as good as  Green Iron Helm made by blacksmiths for leveling. So do the quests for the XP but don't expect great gear.

**Comment by BreakBB** [comment]
@Zardilann Sorry for the late response on this. We're pretty busy atm and still limited in time and manpower. This quest chain seems pretty complex and it would be very helpful if you could make a detailed report on all the quests related to the chain and which can/can't be accepted when 🙏 I don't really trust the data on Wowhead for such quests.

**Comment by SpareSimian** [comment]
There are four quest chains.

The first chain is common to all races and starts with 1698  and ends with 1701 that unlocks the breadcrumb to one of the race-specific chains,, but has an epilog quest (1782) that rewards the actual common armor.

The other three chains are available to all races but a breadcrumb is only offered based on the home city of your race (ie. dwarves and gnomes both get the Ironforge breadcrumb to see a gnome blacksmith in IF). So you can go do all three but you'll only be told about the one for your race.

The three racial quest chains have a race/city-specific breadcrumb, a fetch quest, and a reward quest that grants a piece of armor. The fetch and reward quests are available to all races.

**Comment by Zardilann** [comment]
> There are four quest chains.
> 
> The first chain is common to all races and starts with 1698 and ends with 1701 that unlocks the breadcrumb to one of the race-specific chains,, but has an epilog quest (1782) that rewards the actual common armor.
> 
> The other three chains are available to all races but a breadcrumb is only offered based on the home city of your race (ie. dwarves and gnomes both get the Ironforge breadcrumb to see a gnome blacksmith in IF). So you can go do all three but you'll only be told about the one for your race.
> 
> The three racial quest chains have a race/city-specific breadcrumb, a fetch quest, and a reward quest that grants a piece of armor. The fetch and reward quests are available to all races.

---

> After completing https://classic.wowhead.com/quest=1701/fire-hardened-mail it opens up for https://classic.wowhead.com/quest=1782/furens-armor for all races, and then:
> Dwarf/Gnome: https://classic.wowhead.com/quest=1704/klockmort-spannerspan
> Human: https://classic.wowhead.com/quest=1700/grimand-elmore
> Night Elf: https://classic.wowhead.com/quest=1703/mathiel
> After completing one of these, it opens up for all races:
> https://classic.wowhead.com/quest=1708/iron-coral and https://classic.wowhead.com/quest=1705/burning-blood and https://classic.wowhead.com/quest=1710/sunscorched-shells

The two above should paint the complete picture.

**Comment by BreakBB** [comment]
@Zardilann @SpareSimian Thank you for this detailed explanation. For such complex quest lines it is really helpful for us Questie devs to have people like you, who really did such quests and tested them 👍 

One question stays: If I as a *human* skip the race specific breadcrumb quest (1700) and then do either 1708 (draws/gnomes) or 1710 (nightelfs), will that disable the race specific breadcrumb quest? Or just if I do 1705?

**Comment by SpareSimian** [comment]
Alas, I don't recall that detail and I don't have any new warriors in the queue to test with. My suspicion is that the breadcrumb would remain until one starts the race-specific quest that follows it. At least, that's how _I'd_ code it.

**Comment by BreakBB** [comment]
Haha but you can trust me that Blizzard has some different ideas about quest logic in general 😄 But I will make it that way for now, since it is what I suspect as well. If it's wrong users can report it 👍
