### ISSUE TITLE
Toggle Questie Button - Removed too soon?

### ISSUE THREAD

**Issue by MarkusNemesis** [AeroScripts/QuestieDev#186]
Hello,

I've been running the latest Questie version 2.6.1, and I've had to manually toggle map aids enough time to warrant posting here to request the button be reinstated for fear that it will make people downgrade to an older version.

I personally can live with a macro that toggles it via the mapaids command, but other users may not be so imaginative.

Cheers.

**Comment by Dyaxler** [comment]
Really? What sort of situations would require you to toggle the map aids? When a quest is updated, obtained or even abandoned they are toggled automatically.

**Comment by MarkusNemesis** [comment]
Simply accepting quests in Feralas, the quest markers would update, however
the fetch locations would not appear.

**Comment by MarkusNemesis** [comment]
To add, changing zones does not update the minimap until the map is opened/closed, or my macro to reset map aids is run.

Additionally, there's a separate issue I'll raise regarding quest ! marks not disappearing after accepting a quest, in certain circumstances.

**Comment by Dyaxler** [comment]
Please upgrade to v2.62 and test again. :) I've added some additional check code for quest statuses and for map/zone refreshes. Quest objectives will not show on the Minimap unless you're in that zone or viewing that zone in the Worldmap.

The Toggle Questie button is now back.

**Comment by Schaka** [comment]
What about seeing Quest objectives on the word map (not zoomed onto a zone) then?
That was put in purposely. We specifically backported Astrolabe to Vanilla for that feature and cross-map distance calculation.

**Comment by Dyaxler** [comment]
I was referring to the Minimap only. If you aren't in the zone there is no reason to have an objective icon on the Minimap. Worldmap shows all icons, all the time, regardless of which zone you're in. :)

**Comment by Dyaxler** [comment]
All the comments in this thread have been addressed in the 2.63 version. Anyone else having issues?

**Comment by Dyaxler** [comment]
If nobody is having issues here I'll close this ticket.
