### ISSUE TITLE
Shadoweaver tailoring quest Searing Gorge

### ISSUE THREAD

**Issue by woopydalan** [AeroScripts/QuestieDev#1861]
## Description
The tailoring quest "Shadoweaver" did not show on the map even though I was able to pick up the quest. In fact, it was in my quest journal as an "unobtainable quest". This includes all its followup quests.

## Wowhead link
https://classic.wowhead.com/quest=3379/shadoweaver

**Comment by BreakBB** [comment]
@woopydalan Did you have the required 230 skinning skill to obtain Shadoweaver or some other value? Also did you try a `/reload`?

**Comment by woopydalan** [comment]
@BreakBB Yes I had 230 tailoring skill which is why the quest was available to me, but still was not showing on the map. I did not try a /reload, I have already completed the quest.

**Comment by BreakBB** [comment]
@woopydalan Had another look and didn't find an issue. Could it be that your level was too high for this quest to show? It is listed as a level 50 quest.

**Comment by woopydalan** [comment]
@BreakBB No, I was level appropriate for the quest. Maybe its possible that I had hit 230 skill in the same session, but it did not recognize my new skill? I am not sure.

**Comment by BreakBB** [comment]
I added a check for profession updates a while back which should trigger to draw available quests once you fulfill new quest requirements... 🤔 Maybe it was just a hickup...
