### ISSUE TITLE
Missing EndQuestmark

### ISSUE THREAD

**Issue by Ischtaratu** [AeroScripts/QuestieDev#1863]
Quest ID: 1451
QuestName: Rhapsody Shindigger, Part of Questchain
Link: https://classic.wowhead.com/quest=1451/rhapsody-shindigger

Objektiv: Seek out Rhapsody Shindigger in The Hinterlands.
Coordinates: 26.9 to 48.5, at west of Quel'Danil Lodge

Bug: Questmark for Rhapsody is missing!

**Comment by BreakBB** [comment]
@Ischtaratu I can't find an issue on this quest. The NPC is listed for the quest, the NPC is in our DB and has the correct spawn as well. Did you try a `/reload` when the problem appeared?

**Comment by Ischtaratu** [comment]
Ok ... maybe. At the Time, i have made the Quest, i could not see any Mark for Rhapsody on the Map.

But Yes, if you say, the Data are ok, than schould it be a problem on my side!

I will look at this.

Thanks.

/Closed
