### ISSUE TITLE
Missing Questmark

### ISSUE THREAD

**Issue by Ischtaratu** [AeroScripts/QuestieDev#1864]
Quest ID: 2990
QuestName: Thadius Grimshade, part of questchain
Link: https://classic.wowhead.com/quest=2990/thadius-grimshade

Objektiv: Bring Sharpbeak's Feather to Thadius Grimshade in the Blasted Lands.
Coordinates: 66.9 to 19.5, at Top of the Magetower in Nethergarde Keep at Blasted Lands

Bug: Questmark for Thadius is missing!

**Comment by BreakBB** [comment]
You mean the point where you hand/complete in the quest did not appear on the map.

**Comment by Ischtaratu** [comment]
Yes !

**Comment by BreakBB** [comment]
I can't find any issue for this quest. Most likely it was related to #860 Please try `/reload` next time something similar happens and also add the Questie version with which you experienced the bug. Thanks for another report @Ischtaratu 👍
