### ISSUE TITLE
Trisfal Glades Gordo's Task on map doesn't exist, coordinate included.

### ISSUE THREAD

**Issue by elo62292** [AeroScripts/QuestieDev#1867]
Hello, I am in Trisfal Glades, on (48.1, 57.5) it say's there is a quest called Gordo's Task, I don't see Gordo, I am level 5, can you guys take a look at this in case this is a bug or not. Also I am using the Twitch Client, that is where I got Questie, it is up to date.

**Comment by BreakBB** [comment]
@elo62292 I had this problem as well. Gordo sometimes gets killed or simply despawns. You need a little bit of patience for this quest to grab if you have bad luck.

**Comment by elo62292** [comment]
Hey, thanks for the response, it turns out it was moving on a certain path, he eventually shows up, but it would be nice if the Questie addon could track where Gordo is moving, because I was really confused when he wasn't at the spot it indicated on my map.

**Comment by elo62292** [comment]
> 
> 
> @elo62292 I had this problem as well. Gordo sometimes gets killed or simply despawns. You need a little bit of patience for this quest to grab if you have bad luck.

Hey, thanks for the response, it turns out it was moving on a certain path, he eventually shows up, but it would be nice if the Questie addon could track where Gordo is moving, because I was really confused when he wasn't at the spot it indicated on my map.

**Comment by elo62292** [comment]
@ BreakBB Hey, thanks for the response, it turns out it was moving on a certain path, he eventually shows up, but it would be nice if the Questie add-on could track where Gordo is moving, because I was really confused when he wasn't at the spot it indicated on my map.
