### ISSUE TITLE
Missing Quest STV Coast

### ISSUE THREAD

**Issue by DaK1Ga** [AeroScripts/QuestieDev#1869]
Hi,

I would like to add an addotional quest which didn't make it into the Questie Library so far. It's the [Carefully Folded Note](https://classic.wowhead.com/item=4098/carefully-folded-note#comments) which drops from an [Half-Buried Bottle](https://classic.wowhead.com/object=2560/half-buried-bottle) at the south-eastern coast of STV. This will start the [Message in a Bottle](https://classic.wowhead.com/quest=594/message-in-a-bottle) Quest.

Maybe it's possible to add this into the incredible good Questie Addon.

Thanks for everything and stay healthy :)

Cheers, Daniel

**Comment by Gogo1951** [comment]
Hey @DaK1Ga ,

Can you confirm you're on the latest Questie? I think this quest was added, along with the Sash from the giant in the harbor, maybe 4-5 months ago. I'm almost certain anyway. (=

Can you double check for me once you update? Thanks!
