### ISSUE TITLE
Missing Drop Markers for WANTED: Baron Longshore

### ISSUE THREAD

**Issue by PEWPEWJBR** [AeroScripts/QuestieDev#1871]
Quest: WANTED: Baron Longshore
Quest ID: 895
Wowhead link: https://classic.wowhead.com/quest=895/wanted-baron-longshore
Questie Version: 5.10.1

The Quest Mob can spawn at different locations (basically at each of the campsites) but only one of them is marked. Spawn locations are roughly 62.7,49.7 (thats where I killed him); 63.6,49.2; 64.3,47.2;

**Comment by BreakBB** [comment]
Good catch, thanks. Don't know how this was wrong for such a long time.
