### ISSUE TITLE
Move the localization over to Curseforge

### ISSUE THREAD

**Issue by woopydalan** [AeroScripts/QuestieDev#1872]
Hi,

It would be easier to maintain the config.lua localization if you guys moved that over to curseforge. Right now it's not easy to see what translations are missing, whereas curseforge has easy filtering functionality so translators can see what is missing. Have you guys considered doing that?

Thanks

**Comment by BreakBB** [comment]
@woopydalan To be honest I have no clue what curseforge is capable of. Could you explain what you mean and how to achieve this? Because some languages are indeed lacking translations and we would be happy to make it easier for translators to contribute.

**Comment by woopydalan** [comment]
@BreakBB See this issue that I put in for DBM. This is just as applicable for Questie and explains the capabilities of using curseforge for translation.

https://github.com/DeadlyBossMods/DeadlyBossMods/issues/176

**Comment by BreakBB** [comment]
We decided not to do so since Curseforge is bugged as hell and we don't want to split up the code too much.

Eventually we should create a system/page for translators to see what strings need translation.
