### ISSUE TITLE
Stepping Up Security

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1873]
## Description
Stepping Up Security is a follow up of Securing the Supply Lines.
Currently it shows the quest as available even though I haven't finished the latter quest, yet.

## Wowhead link
https://classic.wowhead.com/quest=8281/stepping-up-security

## Questie version
5.10.1

**Comment by BreakBB** [comment]
I can't reproduce this. For me only "Securing the Supply Lines" shows up on the map and not the follow up quest:
<img width="1421" alt="grafik" src="https://user-images.githubusercontent.com/33514570/80306517-1b533880-87c4-11ea-9781-3dc13be5f40d.png">

**Comment by Djfe** [comment]
mmh maybe if you start the quest stepping up security and don't finish it?
(I actually finished Stepping up security by now, so I can't test it :/ )

thank you for fixing those other quests and taking a look! :) 👍

**Comment by laurencei** [comment]
I currently have this issue. I am undertaking "Securing the Supply Lines".

Questies says "Stepping Up Security" is available - but it is not.

v5.10.1

**Comment by BreakBB** [comment]
@Djfe @laurencei I was able to reproduce this with my main and also found the reason for it. The quest "Securing the Supply Lines" as marked as exclusive to the optional breadcrumb quest "Securing Silithus". 

Fix will be included in the next release, thanks for reporting it 👍
