### ISSUE TITLE
saving setting by charakter and not by Account

### ISSUE THREAD

**Issue by Ischtaratu** [AeroScripts/QuestieDev#1874]
## Description
I have some twink-charakters and every charakter are on other levelrange and areas.

Every time, i switch to an other char, i must new setup Questi.

Is there a possible way to direct the saved settings to single Charakter like other Addons?
So the addon load the setings for each (different) charakter and not the hole account?

**Comment by BreakBB** [comment]
@Ischtaratu Some settings are stored by account and some are stored by character. Which settings are you refering to which you have want to have by character?

**Comment by Ischtaratu** [comment]
primary the level-range for showing quests.
Since we can set the level range manualy and not dependet by charakter-level, it should be saved per charakter.
