### ISSUE TITLE
Taking Back Silithus

### ISSUE THREAD

**Issue by woopydalan** [AeroScripts/QuestieDev#1875]
## Description
The quest marker for Taking Back Silithus in Ironforge is not there. I did a /reload and still not showing

## Wowhead link
https://classic.wowhead.com/quest=8275/taking-back-silithus

## Questie version
5.8.0

**Comment by BreakBB** [comment]
@woopydalan All the Silithus P4 quests are shown since v5.10.1. Did you forgot to update Questie?
