### ISSUE TITLE
Quest objective tracker is not attacked to the frame anymore.

### ISSUE THREAD

**Issue by Mhedea** [AeroScripts/QuestieDev#1876]
I updated questie fof **Wow Classic** this week and suddenly the quest objective list is not where I placed it anymore. I use Elvui so I can move the quest objective frame, and i always have it on the left side of my screen. Questie now keeps the list on the right, and I have no way to drag it to where I want it. I uninstalled and reinstalled it, and when I logged in again it was fine... but the problem came back again today. I even used the reset position option in questie and that just put the list in the middle of my screen.

**Comment by gouletr** [comment]
Yes this is a new bug, super annoying. The quest tracker no longer adjust according to the right hand side action bar buttons.

**Comment by BreakBB** [comment]
Did you guys tried `Crtl + leftclick` to move the tracker?

**Comment by gouletr** [comment]
How manually moving the tracker fixes this? I mean yeah, we can move it manually as a work-around. The bug is that the quest tracker no longer correctly attach itself to the blizzard quest tracker; it overlaps with right side action bar buttons.

**Comment by BreakBB** [comment]
When the Quest Tracker freaks out and looses it's settings it attaches to the QuestWatcher frame.

Addons that move the default quest tracker around will move the contents of the QuestWatcher frame but not the frame. So the Questie Tracker can attach itself to a "ghosted" frame or what appears to be a "ghosted" frame.

Same with minimap addons that move the minimap around. Not all grab the entire MapCluster stack.

But @Dyaxler rewrote a lot of the Tracker code and improved it by a lot, which can be seen in screenshots in #1917

It is most likely this issue will be solved with v6.0.0

**Comment by gouletr** [comment]
Thank god!
