### ISSUE TITLE
Trouble in Winterspring!

### ISSUE THREAD

**Issue by wallrik** [AeroScripts/QuestieDev#1877]
## Description
The breadcrumb quest [Trouble in Winterspring!](https://classic.wowhead.com/quest=6603/trouble-in-winterspring) is still shown as available on the map even if you're currently on the quest [Threat of the Winterfall](https://classic.wowhead.com/quest=5082/threat-of-the-winterfall).

After I had abandoned  [Threat of the Winterfall](https://classic.wowhead.com/quest=5082/threat-of-the-winterfall) I could successfully pick up [Trouble in Winterspring!](https://classic.wowhead.com/quest=6603/trouble-in-winterspring).

## Questie version
5.10.1

**Comment by BreakBB** [comment]
I can't really find an issue causing this. It should be fixed with 8766d16de7bf0e4e70a09b0a9cc1ce94be25b4e6 and 43905f08e92a54621016f07c07aa0ee23eeb01af and therefore fixed since v5.3.0 / v5.9.0 🤔

**Comment by wallrik** [comment]
That's weird. I wish I could help troubleshooting, but I have completed the quest already on my level appropriate character.

This is a snippet form my journey:
```lua
{
  ["Event"] = "Quest",
  ["SubType"] = "Accept",
  ["Level"] = 56,
  ["Quest"] = 5082,
  ["Timestamp"] = 1587268060,
},
--
{
  ["Event"] = "Quest",
  ["SubType"] = "Abandon",
  ["Level"] = 56,
  ["Quest"] = 5082,
  ["Timestamp"] = 1587270239,
},
{
  ["Event"] = "Quest",
  ["SubType"] = "Accept",
  ["Level"] = 56,
  ["Quest"] = 6603,
  ["Timestamp"] = 1587270276,
},
```
As I looked at them commits I thought I was being crazy, but the quest id's line up. 🤔

**Comment by AeroScripts** [comment]
Assuming this is fixed now, if it comes up again reply to this issue
