### ISSUE TITLE
dry times

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1878]
## Description
Probably another issue because of localization (I'm playing the german version)
Bottle of Moonshine (Flasche mit Fusel) is available in Duskwood not Stormwind (see attached screenshot)

## Wowhead link
https://classic.wowhead.com/quest=116/dry-times

## Screenshots
![https://i.imgur.com/ngwvDVH.jpg](https://i.imgur.com/ngwvDVH.jpg)

## Questie version

5.10.1

**Comment by Gogo1951** [comment]
Quest data looks good. Maybe a localization thing. 

https://classic.wowhead.com/item=1942/bottle-of-moonshine for quest https://classic.wowhead.com/quest=116/dry-times is sold by https://classic.wowhead.com/npc=274/barkeep-hann in Duskwood.

```
        [1942] = {
            [QuestieDB.itemKeys.name] = "Bottle of Moonshine",
            [QuestieDB.itemKeys.relatedQuests] = {116},
            [QuestieDB.itemKeys.npcDrops] = {274},
            [QuestieDB.itemKeys.objectDrops] = {},
        },
```

@Muehe - how would it if it's a localization issue?

**Comment by Djfe** [comment]
maybe #680 helps

how do other items with quest id 116 look? they aren't bugged ^^
