### ISSUE TITLE
No Q icons/marks, annoying Q tracker 

### ISSUE THREAD

**Issue by revar** [AeroScripts/QuestieDev#188]
I have no Toggle Questie button. I don't see quest marks/icons to see them I have to track all quests what makes that half of my screen is with tracking quest frames and I can't see shit. I want to disable tracker I don't want to see any quest on my screen, only in quest log. But if I do that, I can't see any quest on my map.

**Comment by Dyaxler** [comment]
That's a good point. Not everyone is a fan of the QuestTracker. OK... I'll create something that will allow you to always see the Quest Objectives on the Minimap and Worldmap while not tracking quests in the QuestTracker. That'll be easy enough.

**Comment by revar** [comment]
Nice to hear that. But for now, can you tell me there is any way to hide that tracker, or make it smaller or anything? When I was using older beta version I could just drag it beyond the edge of the screen and I had Q objectives on the map. I don't mind quest tracking but only for a few quest I'd like to select, but on the map I want to see all of them, so it's not working that way. And to be honest, default wow quest tracker looks better than that from questie, it's just more transparent and slimmer imo. And how about Toggle Questie button, did you discard it? It was helpful especially when yellow quest markers (after getting a new quest) still were displayed on the map.

**Comment by Dyaxler** [comment]
You can now hide the tracker but if you have EQL3 loaded it will use it's tracker instead. Or which ever mod you're using. If you don't have a QuestTracker MOD of some sort installed you'll use the default WoW clients tracker. Use /questie tracker to toggle it.

The Toggle Questie Button has returned in v2.62

**Comment by revar** [comment]
Great, good job :) So am I able now to see all quest objectives on world map without holding my quest tracker visible on the screen? I don't use EQL3 cuz it conflict with some other addon i think.

**Comment by Dyaxler** [comment]
Yes... by default it now shows everything.
