### ISSUE TITLE
ElvUi LUA Errors

### ISSUE THREAD

**Issue by Nem86** [AeroScripts/QuestieDev#1880]
I verify that you're running the latest version of Questie. 

## Bug description
LUA error upon entering game or occationally after leaving combat. 

## Screenshots 1
Message: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:942: hooksecurefunc(): AutoQuestWatch_Insert is not a function
Time: Mon Apr 20 11:34:46 2020
Count: 1
Stack: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:942: hooksecurefunc(): AutoQuestWatch_Insert is not a function
[string "@Interface\AddOns\Questie\Questie.lua"]:170: in function <Interface\AddOns\Questie\Questie.lua:153>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\AstralKeys\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:529: in function `InitializeAddon'
[string "@Interface\AddOns\AstralKeys\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:644: in function <...AddOns\AstralKeys\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

## Screenshots 2 
Message: ...erface\AddOns\Questie\Modules\QuestieProfessions.lua:10: attempt to call global 'ExpandSkillHeader' (a nil value)
Time: Mon Apr 20 11:34:54 2020
Count: 1
Stack: ...erface\AddOns\Questie\Modules\QuestieProfessions.lua:10: attempt to call global 'ExpandSkillHeader' (a nil value)

Locals: 
## Questie version
5.10.1

**Comment by BreakBB** [comment]
@Nem86 Are you using Questie on WoW Classic? The error states some API function provied by Blizzard are not available for you.

**Comment by BreakBB** [comment]
Assuming this is fixed.
