### ISSUE TITLE
SI:7

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1883]
## Description
My guess is that this quest is a bread crumb quest for:
https://classic.wowhead.com/quest=2281/redridge-rendezvous
I couldn't accept the quest si-7 anymore, but it's still being shown.

## Wowhead link
https://classic.wowhead.com/quest=2300/si-7

## Screenshots
![https://i.imgur.com/V88cmMN.jpg](https://i.imgur.com/V88cmMN.jpg)

## Questie version

5.10.1

**Comment by BreakBB** [comment]
@Djfe According to [this comment](https://github.com/AeroScripts/QuestieDev/issues/1466#issuecomment-549170705) you can do all the quest chains as long as you don't have the Blade of Cunning. If you still have it you should try to sell it, then check the quest NPC again. If you can't pick it up simply buy the blade back from the NPC.

**Comment by Djfe** [comment]
This was about the one quest chain I had already started (human)
You can only do one chain once right?
Maybe I had the blade in my inventory then (I don't remember) I don't have it anymore, I finished the chain by now and the quest icon is gone. Maybe this is no issue after all? maybe it only shows up until you finished the chain? (I'm playing on a different computer than the one back then, in-case that matters)

**Comment by BreakBB** [comment]
That Rogue quest line is somewhat cursed and really complicated to show correctly. Especially since you can't accept some other quests if you have the blade in your inventory. Tbh I think most of quests are correct now, if you know you need to remove the blade...

**Comment by Djfe** [comment]
ok works for me, the first time I reported this, I thought the quest might keep on showing up until you are 60 (when low level quests are visible)
but it's gone by now, so it works fine for me
