### ISSUE TITLE
Missing quests

### ISSUE THREAD

**Issue by Krystus** [AeroScripts/QuestieDev#1884]
I've discovered two missing quests from Questie.

- Resting in Pieces
https://classic.wowhead.com/quest=460/resting-in-pieces

- Parts of the swarm
https://classic.wowhead.com/quest=1148/parts-of-the-swarm

**Comment by Gogo1951** [comment]
Hey @Krystus ,

These quests can drop from multiple sources, and so they've intentionally been left out to avoid clutter.

There are some ideas for how to fix this. Feel free to follow along in the other issue.

https://github.com/AeroScripts/QuestieDev/issues/317#issuecomment-564613358

Can you close this?  Thanks!

**Comment by BreakBB** [comment]
@Krystus Both quests should be shown with the latest Questie version v5.10.1
