### ISSUE TITLE
Missing Quests in Silithus

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1885]
The following quests aren't in the journal.

https://classic.wowhead.com/quest=8349/bor-wildmane
https://classic.wowhead.com/quest=8348/signet-of-the-dukes
https://classic.wowhead.com/quest=8363/abyssal-signets

Version 5.10.1

**Comment by Cerby3BR** [comment]
Also,
https://classic.wowhead.com/quest=8351/bor-wishes-to-speak
https://classic.wowhead.com/quest=8352/scepter-of-the-council

**Comment by drejjmit** [comment]
and 
https://classic.wowhead.com/quest=8320/twilight-geolords
