### ISSUE TITLE
Arrow display: attempt to index field `?' (a nil value)

### ISSUE THREAD

**Issue by ChamNouki** [AeroScripts/QuestieDev#1888]
## Bug description
When I click on a tracker on the minimap, the arrow does not show up and this pop up error occure.

## Screenshots
![image](https://user-images.githubusercontent.com/25320655/80036133-77326e80-84f1-11ea-9f94-96fa0122e399.png)

## Questie version
3.7.1 (WoW 1.12)

**Comment by BreakBB** [comment]
We don't support the vanilla version of Questie anymore since WoW Classic has been released and we're very limited in time.

Most likely the quest you try to click on is not in the database.

**Comment by BreakBB** [comment]
We added a check for vanilla and retail clients to retail so it will be much more clear if users are trying to run Questie somewhere else than on Classic.
