### ISSUE TITLE
[SOLVED] Can't move questtracker or questarrow

### ISSUE THREAD

**Issue by bngs** [AeroScripts/QuestieDev#189]
Like the titles says, cant be moved even when holding SHIFT.

**Comment by MarkusNemesis** [comment]
If you're running the latest version, you need to press control and shift, then drag.

**Comment by bngs** [comment]
@MarkusNemesis Thanks! Was a bit confused, didnt find any info on that it was changed from SHIFT to CTRL+SHIFT.

**Comment by Dyaxler** [comment]
Thank you Markus for jumping in here and lending a hand!
