### ISSUE TITLE
Fire Hardened Mail followup quests

### ISSUE THREAD

**Issue by SpareSimian** [AeroScripts/QuestieDev#1891]
Questie version 5.10.1.

Furen Longbeard in Stormwind offers a series of warrior class quests to acquire various bits of mail armor. After completing the first common quests, he offers three race-specific breadcrumb quests to take his notes to fellow blacksmiths in the three capitol cities. A character can only get one of these breadcrumb quests. But the player can go to all three cities and complete all three quests for the other blacksmiths. (Ie. the breadcrumb quests are not necessary to pick up the followup armor quests.)

On my gnome I just finished the quests for Klockmore Spannerspan in Ironforge's Tinkertown. (Dwarves get the same breadcrumb.) I now see the human breadcrumb quest "Grimand Elmore" on Furen in Stormwind but he has no such quest for me.  But I can walk over to Grimand's shop and get his quest, Burning Blood. I expect the same will be true for Mathiel in Darnassus. 

You can find Furen's quests here:

https://classic.wowhead.com/npc=5413/furen-longbeard#starts

"Fire Hardened Mail" and "Furen's Armor" are the common quests that unlock the other three. The other three are named for the three blacksmiths in the three cities. 

So there's two issues: 1) The two breadcrumb quests for the smiths for the other races should not appear on Furen. 2) The followup quests should appear on the other two smiths.

**Comment by Zardilann** [comment]
Related to: https://github.com/AeroScripts/QuestieDev/issues/1857
