### ISSUE TITLE
Quest Issue around [38] Portals of the Legion

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1897]
## Description

Weird issue on this quest, in the tooltip when you are doing it with a friend, the objectives show up differently.

## Wowhead link

https://classic.wowhead.com/quest=5581/portals-of-the-legion\

## Screenshots

![WoWScrnShot_042420_180250](https://user-images.githubusercontent.com/55365231/80283345-698d0c80-86dc-11ea-970d-e374f4e19661.jpg)

![WoWScrnShot_042420_180250](https://user-images.githubusercontent.com/55365231/80283273-faafb380-86db-11ea-8674-ab5cff36b88e.jpg)

## Questie version

Latest on 25 Apr 2020.

**Comment by BreakBB** [comment]
This is an issue with either the Comms or the tooltips. Will need some time to investigate.

**Comment by Gogo1951** [comment]
Only happens on that one quest. Too small an issue to worry about. (=
