### ISSUE TITLE
Journey to Stonetalon Peak

### ISSUE THREAD

**Issue by gyuuula** [AeroScripts/QuestieDev#1901]
## Bug description
A "bread crumb" quest called "Journey to Stonetalon Peak" wasn't SET as completed. I'm fairy sure, I completed it, yet is in the Kalimdor->Ashenvale->Available Quests list.

https://classic.wowhead.com/quest=1056/journey-to-stonetalon-peak

## Screenshots
![WoWScrnShot_042620_124858](https://user-images.githubusercontent.com/60040836/80309293-7f7df880-87d4-11ea-8304-0d8515aa174d.jpg)

## Questie version
v5.10.1 (latest)

**Comment by BreakBB** [comment]
@gyuuula You can check whether you really completed the quest by running:

`/dump IsQuestFlaggedCompleted(1056)`

I guess you only completed the follow up quest [Reclaiming the Charred Value](https://classic.wowhead.com/quest=1057/reclaiming-the-charred-vale#comments). Questie doesn't hide the breadcrumb quest for this one yet, but I already fixed it and the fix will be online in the next release.
