### ISSUE TITLE
Update broke Questie on my PC

### ISSUE THREAD

**Issue by hgbhanz** [AeroScripts/QuestieDev#1903]

**Comment by hgbhanz** [comment]
Tried deleting Questie and ALL saved variable lua files for all characters. Still get this message and Questie will not load. 

Date: 2020-04-26 08:13:01
ID: 1
Error occured in: Global
Count: 1 
Message: ...erface\AddOns\Questie\Modules\QuestieProfessions.lua line 39:
   attempt to index local 'requiredSkill' (a nil value)
Debug:
   ...erface\AddOns\Questie\Modules\QuestieProfessions.lua:39: HasProfessionAndSkillLevel()
   ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1460: IsDoable()
   ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1514: CalculateAvailableQuests()
   ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:120:
      ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:113
Locals:
self = <table> {
 private = <table> {
 }
 HasProfessionAndSkillLevel = <function> defined @Interface\AddOns\Questie\Modules\QuestieProfessions.lua:38
 Update = <function> defined @Interface\AddOns\Questie\Modules\QuestieProfessions.lua:7
 GetPlayerProfessions = <function> defined @Interface\AddOns\Questie\Modules\QuestieProfessions.lua:26
}
requiredSkill = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'requiredSkill' (a nil value)"
HasProfession = <function> defined @Interface\AddOns\Questie\Modules\QuestieProfessions.lua:30
HasSkillLevel = <function> defined @Interface\AddOns\Questie\Modules\QuestieProfessions.lua:34

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.5
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterVendorPrice, vv1.13.04
  ClassicThreatMeter, v1.10
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  EZJunk, v1.0.1
  Informant, v8.2.6374 (SwimmingSeadragon)
  Questie, v5.10.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpeedyAutoLoot, v2.0.25
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v1.3.1
  TitanClassic, v1.2.2.11304
  TitanClassicAmmo, v1.2.2.11304
  TitanClassicBag, v1.2.2.11304
  TitanClassicClock, v1.2.2.11304
  TitanClassicGold, v1.2.2.11304
  TitanClassicLocation, v1.2.2.11304
  TitanClassicLootType, v1.2.2.11304
  TitanClassicPerformance, v1.2.2.11304
  TitanClassicRegen, v1.2.2.11304
  TitanClassicRepair, v1.2.2.11304
  TitanClassicVolume, v1.2.2.11304
  TitanClassicXP, v1.2.2.11304
  TomTom, vv11304-1.1.2
  ZygorGuidesViewerClassic, v1.0
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=566)

**Comment by BreakBB** [comment]
Sorry for that, I failed the update.

The version on CurseForge has already been replaced with a fixed version and should be available in a few minutes.

So try again to reinstall Questie in a few minutes :+1:

**Comment by alexriedl** [comment]
re-updated from curseforge and everything is working again!
