### ISSUE TITLE
Waypoints for objectives are missing

### ISSUE THREAD

**Issue by Muehe** [AeroScripts/QuestieDev#1907]
## Bug description

Waypoints are shown for quest givers and finishers, but not for objective NPCs (e.g. Defias Messenger in Westfall).

## Questie version

All versions since introduction of the waypoint feature are affected.

**Comment by Gogo1951** [comment]
Suggest also adding different colors for different paths.

This would help reduce confusion around paths that cross over each other.

**Comment by AeroScripts** [comment]
Implemented in 6.1
