### ISSUE TITLE
Questie Tracker strata (layer overlap)

### ISSUE THREAD

**Issue by Thordin88** [AeroScripts/QuestieDev#191]
Hello! I would like to know if you could add a setting in which to set up the Quest Tracker list strata as in make it's text/windows appear behind items such as KTM or Skada DPS Meters or even raid frames. Basically make it the base layer.
Regards!

**Comment by Dyaxler** [comment]
The QuestTracker is set to the most Optimal FrameStrata already. If I move it up it'll begin appearing over critical WoW frames such as the Character Panel, Quest Panel, Bank Frame, Auction House Frame etc.

If I move it lower then it might get stuck behind your chat window or some other frame where you can't get to it.

**Comment by Thordin88** [comment]
Thank you for your informative response. I salute the fact you added the Quest tracker toggle. It might help my cause (I am playing wow from a laptop with a small dislay so sometimes in dungeons it covers up KTM or dmg meters and there's actually no place to move it to on the workspace).

**Comment by Dyaxler** [comment]
You can disable the tracker separately. :) Use /questie tracker to toggle it. If another tracker pops up like EQL3 you'll have to disable that one too. And if you have the default Blizzard tracker enabled you'll have to disable that one too. :D But... at least it'll be out of your way.
