### ISSUE TITLE
Quest The Ashenvale Hunt is still shown as available even when all subsequent quests are completed

### ISSUE THREAD

**Issue by yangxk15** [AeroScripts/QuestieDev#1912]
## Description

Quest [The Ashenvale Hunt](https://classic.wowhead.com/quest=6382/the-ashenvale-hunt) from [Jorn Skyseer](https://classic.wowhead.com/npc=3387/jorn-skyseer) is still shown as available when the follow up quest [The Ashenvale Hunt](https://classic.wowhead.com/quest=6383/the-ashenvale-hunt) from [Senani Thunderheart](https://classic.wowhead.com/npc=12696/senani-thunderheart) and all the subsequent quests ([Shadumbra's Head](https://classic.wowhead.com/quest=24/shadumbras-head), [Sharptalon's Claw](https://classic.wowhead.com/quest=2/sharptalons-claw), [Ursangous's Paw](https://classic.wowhead.com/quest=23/ursangouss-paw)) are completed.

## Questie version

Version: 5.10.2

**Comment by BreakBB** [comment]
@yangxk15 And you check that you can't pick up the quest anymore? I am fairly sure you can at least pickup the quest from Jorn Skyseet even if you already completed the one from Senani Thunderheart.

**Comment by BreakBB** [comment]
Not able to reproduce this issue due to lack of information. Feel free to create another issue if this comes up again.
