### ISSUE TITLE
Quest Flags

### ISSUE THREAD

**Issue by Ischtaratu** [AeroScripts/QuestieDev#1913]
1st:
QuestID: 7161 and 7162 (same quest for alliance and horde)
QuestName: Proving Grounds

Question:
Sould be Marked as PVP quest, because you must go to Arati Battle Ground.
WoWHead say no PvP Flag for this quest!
How would you handle this?

2nd:
QuestID: 4734 
QuestName: egg-freezing

Quest is for Raid UBRS
But if you set Questie to hide dungeon quests, this quest will be showen.

Question: 
Raid-Quests and Dungeon-Quests are not the same flags?

**Comment by BreakBB** [comment]
@Ischtaratu Sorry for the late response.

For your first question:

We use the [GetQuestTagInfo](https://wow.gamepedia.com/API_GetQuestTagInfo) function to determine whether a quest is somewhat special (PvP, Dungeon, ...). But some quests are simply not marked correctly on Blizzard's side so we add a flag to them manually.
This is done in the `QuestieDB:IsPvPQuest` function. So for your quests Blizzard has wrong data and we fix it. Thanks for reporting them ;)

For the second question:

We didn't check for Raid quests yet, but I am about to add another checkbox as option for them.
