### ISSUE TITLE
Nothing too serious 

### ISSUE THREAD

**Issue by YakuZaazz** [AeroScripts/QuestieDev#192]
for some reasons with the new release  my quest progression overlay that comes with questies showing the quest is like almost in the middle of the screen so everytime i get  a quest i have to open my quest log and shift click to hide its progression on the side  cause normally in previous versions you could move the overlay by just clicking and dragging now its just LOCK into places would be cool if you could unlock it thank you great addon definitely lots of work put into it looking forward to its fully completed states :D
Ps: i say overlay but its just to talk about the encasement of the quest progressions on the side of the screen

**Comment by Muehe** [comment]
#189

**Comment by Dyaxler** [comment]
Correct. You must hold down Ctrl+Shift then click and hold the left mouse button while you're dragging the QuestTracker or the QuestTrackerArrow.
