### ISSUE TITLE
Children's week

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1921]
## Description

It's children's week from 1st to 7th of May 2020

## Wowhead link

https://classic.wowhead.com/quest=1468/childrens-week#english-comments

## Questie version

5.4.2

**Comment by Djfe** [comment]
![WoWScrnShot_050620_025635](https://user-images.githubusercontent.com/5685512/81129630-3bfa5b80-8f45-11ea-9fc6-a3036d822e54.jpg)

**Comment by Djfe** [comment]
Ok I don't know when it actually ended. The week days lasted longer than the 7. of May.

It might still be running?

**Comment by BreakBB** [comment]
Oh, I didn't check that tbh. Will reopen and check

**Comment by BreakBB** [comment]
From the information I can find online (e.g. [wowhead](https://classic.wowhead.com/guides/wow-classic-childrens-week-holiday)) it should have ended on the 7th May.

**Comment by Djfe** [comment]
Blizzard also confirms May 1st to 7th
https://news.blizzard.com/en-us/world-of-warcraft/22965339/children-s-week-has-arrived-may-1-may-7 (info about wow classic is at the bottom of the page)

**Comment by BreakBB** [comment]
Perfect, thanks for charing that source @Djfe :+1:
