### ISSUE TITLE
Quest listed as Abandoned in My Journey, but Completed in Quests by Zone

### ISSUE THREAD

**Issue by bretwood68** [AeroScripts/QuestieDev#1922]
## Description
In my Journey, it lists a quest as being abandoned, but in Quests by Zone, it lists it as being completed.

Originally it was listed as Available in the Quests by Zone list as well, even though my chat window clearly showed it as completed, and I received my reward.  When I logged my character out, then back in, hte Quests by Zone section now lists it as completed, but the My Journey section still lists it as abandoned.

## Screenshots

![WoWScrnShot_050420_170828](https://user-images.githubusercontent.com/64815771/81025104-61467700-8e2a-11ea-8acf-a26c30e2ec2f.jpg)
![WoWScrnShot_050420_170846](https://user-images.githubusercontent.com/64815771/81025205-bda99680-8e2a-11ea-86c3-283937046f4e.jpg)
![WoWScrnShot_050420_170938](https://user-images.githubusercontent.com/64815771/81025129-7d4a1880-8e2a-11ea-8ac7-8dad9286de6b.jpg)

## Questie version
Questie v5.10.2

**Comment by BreakBB** [comment]
@bretwood68 Looks like we falsely marked the quest as abandoned even though you completed it (both fire the same event). Are you using the Questie auto turn in/complete functionality?

**Comment by BreakBB** [comment]
Not able to reproduce this issue due to lack of information. Feel free to create another issue if this comes up again.
