### ISSUE TITLE
The Darkmoon Faire

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1924]
## Description

I'm able to get this quest in ironforge at level 27.
According to wowhead level 6 is required.

## Wowhead link

https://classic.wowhead.com/quest=7905/the-darkmoon-faire
Horde variant:
https://classic.wowhead.com/quest=7926/the-darkmoon-faire

## Screenshots

![WoWScrnShot_050520_181821](https://user-images.githubusercontent.com/5685512/81089859-2c572480-8efd-11ea-958b-d345db4f7026.jpg)

## Questie version

5.4.2

**Comment by drejjmit** [comment]
I can confirm it's not obtainable at level 5. It shows up as a silver exclamation mark above his his head so level 6 could be correct.

**Comment by Djfe** [comment]
@drejjmit I think I wrote 4 accidentally 😅
probably 5.10.2
I'm also checking whether I'm on the latest version before reporting something.
