### ISSUE TITLE
'The Twighlight Mystery' marked incorrectly

### ISSUE THREAD

**Issue by millinoid** [AeroScripts/QuestieDev#1925]
https://classic.wowhead.com/quest=8284/the-twilight-mystery

This quest is completed by collecting Twilight Tablet Fragments found on the ground. Questie currently marks the elementals near the quest pickups as dropping the fragments.

https://i.imgur.com/LBAdcq5.jpg
https://i.imgur.com/a0KREmk.jpg
https://i.imgur.com/OUyJqWK.jpg
https://i.imgur.com/DUAgapC.jpg

**Comment by BreakBB** [comment]
Fixed with 2b7ccbe2d14239ddd0e085dd7b771b21658467e9
