### ISSUE TITLE
A donation of wool/silk

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1928]
## Description

You can do these quests at level 12 respectively 26, but it doesn't show up on the map for me, yet at lvl 31.

## Wowhead link

https://classic.wowhead.com/quest=7802/a-donation-of-wool
https://classic.wowhead.com/quest=7803/a-donation-of-silk

## Questie version

5.4.2

**Comment by BreakBB** [comment]
@Djfe Those quests are marked as level 60 and we only show quests 7 level above your own by default. We will change that behavior though with #1568
