### ISSUE TITLE
Questie does not work, even when loaded as the only add on

### ISSUE THREAD

**Issue by Pemmican6** [AeroScripts/QuestieDev#1930]
when logging in, even with questie as the only add on, I cannot get it to work.
I downloaded the newest version, but i still cant seem to get it to work.

When I load it as the only add on, I get three LUA errors:

1--------------

Message: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:942: hooksecurefunc(): AutoQuestWatch_Insert is not a function
Time: Thu May 7 09:23:00 2020
Count: 1
Stack: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:942: hooksecurefunc(): AutoQuestWatch_Insert is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua"]:942: in function `HookBaseTracker'
[string "@Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua"]:152: in function `Initialize'
[string "@Interface\AddOns\Questie\Questie.lua"]:170: in function <Interface\AddOns\Questie\Questie.lua:153>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:529: in function `InitializeAddon'
[string "@Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:644: in function <...ce\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

 

2--------------------------------------

Message: Questie_Toggle: Couldn't find relative frame: WorldMapContinentDropDown
Time: Thu May 7 09:23:05 2020
Count: 4

 

3----------------------------------------

Message: ...erface\AddOns\Questie\Modules\QuestieProfessions.lua:9: attempt to call global 'ExpandSkillHeader' (a nil value)
Time: Thu May 7 09:23:07 2020
Count: 1
Stack: ...erface\AddOns\Questie\Modules\QuestieProfessions.lua:9: attempt to call global 'ExpandSkillHeader' (a nil value)
[string "@Interface\AddOns\Questie\Modules\QuestieProfessions.lua"]:9: in function `Update'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:55: in function `Initialize'
[string "@Interface\AddOns\Questie\Modules\QuestieEventHandler.lua"]:118: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:113>

Locals: self = <table> {
private = <table> {
}
HasProfessionAndSkillLevel = <function> defined @Interface\AddOns\Questie\Modules\QuestieProfessions.lua:38
Update = <function> defined @Interface\AddOns\Questie\Modules\QuestieProfessions.lua:7
GetPlayerProfessions = <function> defined @Interface\AddOns\Questie\Modules\QuestieProfessions.lua:26
}
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call global 'ExpandSkillHeader' (a nil value)"
professionTable = <table> {
응급치료 = 129
무두질 = 393
채광 = 186
草藥學 = 182
Culinária = 185
製皮 = 165
Couraria = 165
剝皮 = 393
Secourisme = 129
Mineração = 186
急救 = 129
Minage = 186
采矿 = 186
Портняжное дело = 197
Engineering = 202
剥皮 = 393
锻造 = 164
대장기술 = 164
Erste Hilfe = 129
Cocina = 185
Кулинария = 185
Encantamento = 333
Снятие шкур = 393
Ingeniería = 202
Primeiros Socorros = 129
Инженерное дело = 202
Botánica = 182
Esfolamento = 393
마법부여 = 333
First Aid = 129
Dépeçage = 393
Desollar = 393
Травничество = 182
Skinning = 393
烹飪 = 185
Горное дело = 186
Alfaiataria = 197
낚시 = 356
釣魚 = 356
附魔 = 333
钓鱼 = 356
Наложение чар = 333
Рыбная ловля = 356
採礦 = 186
재봉술 = 197
Ferraria = 164
Angeln = 356
Fishing = 356
연금술 = 171
Herboristerie = 182
Alquimia = 171
Schmiedekunst = 164
Leatherworking = 165
Encantamiento = 333
Enchanting = 333
工程学 = 202
炼金术 = 171
Bergbau = 186
기계공학 = 202
工程學 = 202
草药学 = 182
Kürschnerei = 393
Cuisine = 185
鍊金術 = 171
Ingénierie = 202
Pêche = 356
Primeros auxilios = 129
Kräuterkunde = 182
Pesca = 356
Алхимия = 171
裁縫 = 197
烹饪 = 185
Lederverarbeitung = 165
Marroquinería = 165
Couture = 197
Кожевничество = 165
Verzauberkunst = 333
Herborismo = 182
Schneiderei = 197
Cooking = 185
Tailoring = 197
Ingenieurskunst = 202
Кузнечное дело = 164
鍛造 = 164
Minería = 186
Mining = 186
가죽세공 = 165
요리 = 185
Kochkunst = 185
Alchimie = 171
약초채집 = 182
Alchemy = 171
Первая помощь = 129
Engenharia = 202
Enchantement = 333
Travail du cuir = 165
Herbalism = 182
Costura = 197
制皮 = 165
Herrería = 164
裁缝 = 197
Blacksmithing = 164
Forge = 164
}
playerProfessions = <table> {
}

**Comment by drejjmit** [comment]
What version are you on? Errors on InitializeAddon. Sure you're not running two Questies?

**Comment by Pemmican6** [comment]
I downloaded the newest version, 5.10.2, I only have one questie folder in
the addons directory,
I also tried removing everything from the addon folder except the questie
folder, and still got the same error messages.

**Comment by drejjmit** [comment]
Try deleting all Questie folders and follow the installation guide here: https://github.com/AeroScripts/QuestieDev/wiki/Installation-Guide

**Comment by Pemmican6** [comment]
does it only work in classic? I dont have a classic folder, I have a _retail_ folder.
I am running the Battle for azeroth version of WOW, maybe thats why?
Otherwise I did exactly what the guide says.

**Comment by drejjmit** [comment]
It's for classic only since retail already have a built in quest helper.

**Comment by Pemmican6** [comment]
ahh, sorry, my mistake, thanks for the help anyway.
