### ISSUE TITLE
Lua Error: Questie taints "IsQuestWatched"

### ISSUE THREAD

**Issue by Aviana** [AeroScripts/QuestieDev#1931]
## Bug description
A lua error that blames a random addon pops up thats says something like:
"An action was blocked in combat because of taint from <randomAddon> - CompactRaidGroup5Member4:Show()"

## Questie version
5.10.2

The taintlog reports "Interface\FrameXML\QuestLogFrame.lua:226 QuestLog_Update()" as the source of the taint. And line 973 of \Modules\Tracker\QuestieTracker.lua confirms that "IsQuestWatched" gets overwritten and thus tainting the default interface,

**Comment by BreakBB** [comment]
@Aviana Thanks for the report. Yes, you're right about it and also the first to experience/report this. And it has been in Questie nearly since the beginning 😄

We will look into the code and try to find a solution for it.

**Comment by BreakBB** [comment]
@Aviana There is no easy solution for this to change and actually we're not sure it really is Questie causing this error. We had some similar issue where the error message blamed some addon which wasn't the cause of it.

Moreover we need to pre-hook the `IsQuestWatched` function to be able to track more than 5 quests in our tracker. There might be another way we can't think of.

**Comment by BreakBB** [comment]
Not able to reproduce this issue due to lack of information. Feel free to create another issue if this comes up again.
