### ISSUE TITLE
Blood of Heroes locations

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#1933]
A few issues with the way the Bloods of Heroes are show in the map/minimap for the quests Libram of Rapidity, Breastplate of the Chromatic Flight, and Legplates of the Chromatic Flight.
1) The quests each seem to be using separate data sets, maybe those should be merged?
2) There are quite a few missing locations, this is certainly the most difficult one to solve.
2) Some pips are showing up on the wrong zone map.

![WoWScrnShot_051120_125206](https://user-images.githubusercontent.com/54936174/81555101-2f806380-9388-11ea-9991-95bce1e61556.jpg)
![WoWScrnShot_051120_125209](https://user-images.githubusercontent.com/54936174/81555113-360edb00-9388-11ea-9f5a-bdc93c0c1a57.jpg)
![WoWScrnShot_051120_125211](https://user-images.githubusercontent.com/54936174/81555122-3ad38f00-9388-11ea-9520-6a6e871a4a67.jpg)

https://classic.wowhead.com/object=176213/blood-of-heroes

Version 5.10.2

**Comment by BreakBB** [comment]
This has been reported in #1915 and is already solved. Will be included in the next release. Thanks for another report @Cerby3BR :pray:
