### ISSUE TITLE
Quest Issue around [12] Hilary's Necklace

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1934]
## Description

This is showing up for my Horde Orc Warrior. It's an Alliance-only quest.

## Wowhead link

Hilary's Necklace - Quest - World of Warcraft || https://classic.wowhead.com/quest=3741/hilarys-necklace

## Screenshots

![WoWScrnShot_051120_021233](https://user-images.githubusercontent.com/55365231/81578814-f2f53d80-9370-11ea-971b-fe0e1ee2db54.jpg)

## Questie version

v5.10.2

**Comment by drejjmit** [comment]
Horde can complete that quest. It's deep in alliance territory so i wouldn't recommend it tho 😃  Questie shows available quests and it's up to the player if they want to do it or not.
#1254 #1057 #840
