### ISSUE TITLE
Quest issue around [34] Valik 

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1935]
## Description

Quest is not showing up for Horde on the map, but is obtainable. Tested on a level 33 Undead Priest.

## Wowhead link

Valik - Quest - World of Warcraft || https://classic.wowhead.com/quest=535/valik

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/81579415-c261d380-9371-11ea-8f4c-4b98a9c28b7a.png)

## Questie version

v5.10.2

**Comment by BreakBB** [comment]
Ah yeah, there is some exclusivity for this quest. Maybe it is a child quest for the missive.
