### ISSUE TITLE
Quest Tracker and Map show Inconsistent Completion Status when when Quest Item Despawns

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1936]
## Description

So there's an issue when you loot an item that only lasts a set amount of time, and the item de-spawns. Your quest map and objectives will still show as completed.

## Wowhead link

One example

* Undamaged Venom Sac - Quest - World of Warcraft || https://classic.wowhead.com/quest=2934/undamaged-venom-sac

## Screenshots

![WoWScrnShot_050820_183254](https://user-images.githubusercontent.com/55365231/81580194-be828100-9372-11ea-9252-9114d73add01.jpg)

## Questie version

v5.10.2

**Comment by BreakBB** [comment]
I think this is caused by the Blizzard API for not firing another `USER_QUEST_LOG_CHANGED` event. The same happens when picking up a quest item from the bank.

You could check this by using the `/etrace` command and filter all the unimportant events before actually letting the item run out.

**Comment by Gogo1951** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.

**Comment by Gogo1951** [comment]
Tagging #2515
