### ISSUE TITLE
I pick up quests and they show that I have completed them.  In quest log they do not show.  I try turning in but won't do because I have not DONE the quest.  This is getting frustrating

### ISSUE THREAD

**Issue by GTrippodo** [AeroScripts/QuestieDev#1938]

**Comment by BreakBB** [comment]
@GTrippodo Please fill the template so we can actually help you with your issue.

**Comment by BreakBB** [comment]
Not able to reproduce this issue due to lack of information. Feel free to create another issue if this comes up again.
