### ISSUE TITLE
The Festival of Fire quest is displayed to early

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1940]
## Description

The midsummer fire festival happens somewhere in June not in May, but the quest shows up for me in the cities.

## Wowhead link

https://classic.wowhead.com/quest=9368/the-festival-of-fire

## Questie version

5.10.2

**Comment by BreakBB** [comment]
Already fixed with v5.10.3

**Comment by Plasticable** [comment]
Same now. I have Midsummer quests markers at TBC Classic, but there is no event yet.
