### ISSUE TITLE
Quest issue around [53] The Scent of Lar'korwi 

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1942]
## Description

This quest is a bit weird in that you don't have to interact with the nests, but you do have to walk over them in order to trigger the mobs that you need to kill. Not sure how to represent that on the map; maybe a magnifying glass? Once you walk over the nests, the mobs spawn and you can kill them for the scent glands. Nests aren't listed on the map, and drop locations for the glands are not accurate as the icons seem to be clumped up.

Tested on 54 Orc Warrior.

Nest locations in Un'Goro Crater:

* 60, 72
* 62, 65
* 63, 77
* 67, 67 
* 67, 73

## Wowhead link

* The Scent of Lar'korwi - Quest - World of Warcraft || https://classic.wowhead.com/quest=4291/the-scent-of-larkorwi

## Questie version

5.10.2

**Comment by BreakBB** [comment]
@Gogo1951 I checked our data and the "Lar'korwi Mate" are the mobs dropping the required items. The spawns for those have been added a while back and are still there:

![image](https://user-images.githubusercontent.com/33514570/84946683-5cdbd200-b0e9-11ea-8672-e6a4a0b46a10.png)

```lua
        [9683] = {
            [QuestieDB.npcKeys.spawns] = {[490]={{58,78},{60,72},{62,65},{62,80},{63,77},{66,62},{66,66},{67,60},{67,73},{67,67},{70,60},{71,59},},},
            [QuestieDB.npcKeys.zoneID] = 490,
        },
```

Not sure what is up with this quest then...

**Comment by Gogo1951** [comment]
v6.0.4
