### ISSUE TITLE
Action Bar Obscuring Quests

### ISSUE THREAD

**Issue by Flolyn** [AeroScripts/QuestieDev#1943]
About 3 versions back the quests were left of the right action bars. Since then, the quests are all the way to the right and obscured by the 2 right action bars. I have reloaded the UI to no avail. Is there a way where it can be pinned to another location on the screen?

Thank you

**Comment by BreakBB** [comment]
You can move the Tracker with `Ctrl + Leftclick`. Also the next big Questie update will add major changes to the Tracker to improve it's functionaly

**Comment by BreakBB** [comment]
Assuming this is fixed. Feel free to create another issue if this comes up again.
