### ISSUE TITLE
Quest issue around [55] Melding of Influences 

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1945]
## Description

The quest calls for you to use the Encased Corrupt Ooze (https://classic.wowhead.com/item=12288/encased-corrupt-ooze) on a Primal Ooze (https://www.wowhead.com/npc=6557/primal-ooze), then kill the creature that spawns and collect the Merged Ooze Sample (https://classic.wowhead.com/item=12291/merged-ooze-sample). However, there currently aren't any markers on the map for where the Primal Oozes are. Suggest putting in gears as the Primal Oozes are fairly low density. Tested on 55 Orc Warrior.

## Wowhead link

* Melding of Influences - Quest - World of Warcraft || https://classic.wowhead.com/quest=4642/melding-of-influences

## Questie version

5.10.3

**Comment by BreakBB** [comment]
There have been other issues about this quest before and I thought I found a solution. Will check again, thanks
