### ISSUE TITLE
Quest issue around [52] A Sample of Slime... & [56] ... and a Batch of Ooze

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1946]
## Description

These quests calls for you to kill oozes, then bring the samples back and use them at the testing lab in Undercity. The location to use the samples isn't shown; needs a "use" gear icon at 47,73 in Undercity.

## Wowhead link

* A Sample of Slime... - Quest - World of Warcraft || https://classic.wowhead.com/quest=4293/a-sample-of-slime
* ... and a Batch of Ooze - Quest - World of Warcraft || https://classic.wowhead.com/quest=4294/and-a-batch-of-ooze

## Questie version

5.10.3

**Comment by BreakBB** [comment]
Might be related to #1315 and #1570

**Comment by Gogo1951** [comment]
Seems fixed now. I see a gear in Undercity.

**Comment by drejjmit** [comment]
Fixed with #2224
