### ISSUE TITLE
[10] Heeding the Call 

### ISSUE THREAD

**Issue by cunninspg** [AeroScripts/QuestieDev#1947]
Quickie tells me to "Pick up: Heeding the Call"
I already had the quest in my log
I dropped the quest and re-picked up the quest and it still says: "Pick up: Heeding the Call"

**Comment by drejjmit** [comment]
Questie doesn't tell you to do anything. That's probably Azeroth Auto Pilot.

**Comment by cunninspg** [comment]
yep figured that out and was closing ticket when you posted..
Thanks
