### ISSUE TITLE
Quest issue around [1] Your Place In The World & [1] Cutting Teeth

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1956]
## Description

Ok, so this is literally the first quest on Horde side for Orcs and Trolls. Ha.

It's a chain, and it tells you to go to the cave to get Cutting Teeth.

For whatever reason, I missed the quest that was 2 feet in front of my face, and went and picked up Cutting Teeth instead. Once I did, Your Place In The World was not available to me any more, but it still showed as a ! on Questie.

## Wowhead link

* Your Place In The World - Quest - World of Warcraft || https://classic.wowhead.com/quest=4641/your-place-in-the-world

* Cutting Teeth - Quest - World of Warcraft || https://classic.wowhead.com/quest=788/cutting-teeth

## Screenshots

![WoWScrnShot_051820_185054](https://user-images.githubusercontent.com/55365231/82329225-9912fa00-99a6-11ea-9060-98074a148f3f.jpg)

**Comment by BreakBB** [comment]
Haha, nice finding :joy:
