### ISSUE TITLE
Quest issue around [10] The Hunter's Path

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1957]
## Description

This quest is available but not not showing up in Questie / showing up in the wrong spots for certain races. Tested on a Troll Hunter, also had comments in Discord about it from a Tauren Hunter. The problem is that there are as many of these as there are races, and each one has a followup that's named "The Hunter's Path" oof.

* https://discordapp.com/channels/263036731165638656/263036731165638656/708311750251905105

## Wowhead link

* the hunter's path - Wowhead Search || https://classic.wowhead.com/search?q=the+hunter%27s+path#quests:0-1+2

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/82329599-2d7d5c80-99a7-11ea-8ec8-6c1f48a36696.png)

![WoWScrnShot_051920_003404](https://user-images.githubusercontent.com/55365231/82329626-3837f180-99a7-11ea-85f1-22abc9fd9f32.jpg)

**Comment by BreakBB** [comment]
@Gogo1951 I guess your character progressed past this quest? It could be some quests are just not in the game and therefore showing falsely, but it is hard to test without a character

**Comment by BreakBB** [comment]
@Gogo1951 Did you have the time to investigate this in detail?

**Comment by BreakBB** [comment]
Without more information we can not correctly fix this quest. Someone needs at least 1 level 10 hunter to check each of the locations to investigate all the quests. Postponing to v6.1

**Comment by Gogo1951** [comment]
Yeah, unfortunately with all the quests named the same... untangling all that to align the proper quest IDs to the right races is a huge mess.

I'll see about recruiting a few more QA people who have hunters coming up.

**Comment by drejjmit** [comment]
Rest is fixed with #2167
