### ISSUE TITLE
Error, if you playing with RuWow addon

### ISSUE THREAD

**Issue by Contra111** [AeroScripts/QuestieDev#196]
This addon translate some text in the game on the Russian language, and if you tell them you use, that are not shown on the map, "Swords," only mark quests to collect. Sorry for the bad english.

**Comment by Dyaxler** [comment]
Привет. Я говорю немного русский. Пожалуйста напишите ваш вопрос на русском языке.

**Comment by Contra111** [comment]
Вот скриншот карты:
http://puu.sh/nUHNN/606d00c7b3.jpg
Если играть с аддоном RuWow, то на карте не отображаются "мечики", т.е
квесты где надо кого-то убить.
Вот тот же скриншот с включенным аддоном RuWow:
https://puu.sh/nUHUV/8404c6d6ef.jpg

2016-03-26 19:04 GMT+03:00 Dyaxler <notifications@github.com>:

**Comment by Dyaxler** [comment]
Вы можете типа "/questie settings" в то время как в игре и список выходных данных?

**Comment by Contra111** [comment]
Вот скриншоты настроек:
http://puu.sh/nUJKl/b44ff2a947.jpg
http://puu.sh/nUJLt/71f47f1133.jpg


2016-03-26 19:44 GMT+03:00 Dyaxler <notifications@github.com>:

**Comment by Dyaxler** [comment]
Некоторые из настроек "nil" введите "/questie clearconfig". Это установит эти "nil" параметры по умолчанию.

**Comment by Contra111** [comment]
Всё равно не отображается, но это не большая проблема, можно играть и без
аддона RuWow.

2016-03-26 20:05 GMT+03:00 Dyaxler <notifications@github.com>:

**Comment by Dyaxler** [comment]
Подождите. RuWoW перевести с английского на русский?

**Comment by Contra111** [comment]
RuWoW переводит большую часть текста в игре на русский: описания квестов,
предметов и т.д

2016-03-26 20:24 GMT+03:00 Dyaxler <notifications@github.com>:

**Comment by Dyaxler** [comment]
Теперь я понимаю. Редактировать "Questie.toc" и добавить RuWoW к "OptionalDeps:" линия. Это сделает Questie ждать до тех пор, пока загружается RuWoW.

Если это не работает затем попробуйте добавить "!Questie" к "OptionalDeps:" в "RuWoW.toc".

Один из этих двух вариантов может работать. Извините за мой плохой русский. :)

![capture](https://cloud.githubusercontent.com/assets/17400948/14061464/f43b158e-f33d-11e5-890d-7d68eff4253b.JPG)

**Comment by Contra111** [comment]
К сожалению это не помогло, ну ладно, могу просто не использовать аддон
RuWoW, у Вас отличный русский! :)

26 марта 2016 г., 20:32 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
Спасибо! Моя подруга всегда говорил мне, что я не совсем получить это право.

> Если это не работает затем попробуйте добавить "!Questie" к "OptionalDeps:" в "RuWoW.toc".

Первый вариант выше должна иметь работал, если RuWoW возникли проблемы, некоторые из английских слов в русском переводе. Я знаю по опыту, что это не всегда перевод напрямую. Некоторые из квестов работают?

**Comment by Contra111** [comment]
Аддон работает исправно во всём кроме одного: квесты на убийство мобов не
отображаются на карте, и из-за этого иногда приходится смотреть где эти
монстры на ходятся на wowhead или его аналогах. А в остальном проблем нет.
Имена и названия локация не переведены в этом аддоне.

26 марта 2016 г., 20:50 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
Там может быть несколько вещей происходит. В одном из ваших предыдущих снимков экрана вы показали ваши настройки. Некоторые параметры были установлены с "nil". Те должно быть "false". Если эти параметры не являются правильными, это может вызвать проблемы. Есть только два параметра, которые должен содержать ряд. Остальные параметры должны быть "true" или "false". "/questie clearconfig" следует исправить неправильные настройки вместе с добавлением RuWoW как необязательные зависимости сделает Questie ждать, пока RuWoW не полностью загружен, прежде чем он начинает делать свою работу.

Убедитесь, что закрытие WoW клиент после внесения изменений перед тестированием.

**Comment by Contra111** [comment]
После добавления RuWoW в необязательные зависимости сделал /questie
clearconfig, в /questie settings больше нету параметров с "nil", вы это
имеете ввиду? Если да, то это не помогло.

26 марта 2016 г., 21:12 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
Это может быть возможно, что ваш конфигурационный файл поврежден. Если вы копируете все ваши номера «QuestieSeenQuests» в отдельный файл...
![capture](https://cloud.githubusercontent.com/assets/17400948/14061781/c8806c56-f346-11e5-9486-c0fd50e0ad1a.JPG)
...то удалить все Questie файлы в папке "WTF". Если у вас есть более одного символа, будьте осторожны, вам придется копировать "QuestieSeenQuests" для каждого символа.

**Comment by Contra111** [comment]
Как он может быть поврежден, если без RuWowа работает, а с RuWowом не
работает, думаете проблема в этом?

26 марта 2016 г., 21:38 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
Попробуйте это. Отключите все моды и запускать только Questie. Войти в символ. Тип "/questie clearconfig". Затем введите "/questie settings". Если вы все еще видите "nil" ваш конфигурационный файл поврежден. Если не видеть любой "nil" затем выйдите из системы и включить RuWoW. Войдите в игру и типа "/questie settings". Если вы видите "nil", RuWoW разорвать Questie. Если не проверить Questie, чтобы увидеть, если он до сих пор сломался.

**Comment by Contra111** [comment]
Сделал так, в настройках нету "nil"

26 марта 2016 г., 22:11 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
Просто, чтобы подтвердить, когда вы в игре, и вы типа "/questie settings" Существует нет "nil" в списке?

Простите меня, если я спросил это раньше. Questie работает с без других модов включен?

**Comment by Contra111** [comment]
В списке нет "nil"

26 марта 2016 г., 23:28 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
С другие моды не работает?

**Comment by Contra111** [comment]
Не работает только с модом RuWoW, об этом я и писал с самого начала

2016-03-26 23:31 GMT+03:00 Dyaxler <notifications@github.com>:

**Comment by Dyaxler** [comment]
Хорошо. Вы используете русской версии World of Warcraft клиента или английская версия?

Извините, если некоторые из моих вопросов предлагается дважды. Я просто пытаюсь определить, если RuWoW не переводить основные базы данных таблицы. Например существует огромная разница между местоположением и мест на английском языке...

**Comment by Contra111** [comment]
На классическую версию игру нет официального русского клиента, официальный
русский клиент появился только во время дополнения Burning Crusade или
WoTLK, когда WoW официально вышел в России. А аддон RuWoW это любительский
перевод игры на русский язык. Сам клиент английский.

26 марта 2016 г., 23:36 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
Да. Я не мог вспомнить, если официальный Русский клиент вышел в конце классического или Burning Crusade. Глядя на ваши снимки экрана он выглядел как английский клиента, но я хотел бы подтвердить.

Можно ли вы напишите мне копию RuWoW или предоставить URL, чтобы загрузить его? Я не могу показаться, чтобы найти его. Хотелось бы взглянуть на код и посмотреть, как она выполняет его функции. Я мог бы быть в состоянии найти ошибки программного обеспечения. Некоторые из Questie работает как вы указали, так что он должен делать что-то правильно.

**Comment by Contra111** [comment]
Вы получили архив с аддоном в предыдущем письме?

26 марта 2016 г., 23:45 пользователь Вадим Савенков <mr.v.vadim@gmail.com>
написал:

**Comment by Dyaxler** [comment]
Может быть GitHub фильтровать его. Я не вижу его.

Однако я сделал быстрый поиск, и я нашел этот пост на форуме.

http://Forum.nostalrius.org/viewtopic.php?t=23404&p=162520#p163064

Он говорит, что этот мод имеет перевод лучше и лучше работает с английским модов.

Я нашел место загрузки для RuWoW после поиска через несколько больше страниц. Я скачать его и посмотреть, если я получаю такую же проблему, которую вы испытываете.

**Comment by Contra111** [comment]
ruRU и RuWoW это два разных аддона, похоже вы нашли ruRU.
Залил файл на файлообменник, попробуйте скачать:
http://rghost.ru/7jpyvJPXr

26 марта 2016 г., 23:56 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
Что ProffBot делать?

Я смотрел на код и он выглядит как своего рода профессии мод и она, как представляется, циклы много функций обратно на себя. Это выглядит как скрипт программного обеспечения, что не разрешено на Nostalrius.

**Comment by Contra111** [comment]
Не знаю, но без ProffBota RuWoW не работает.

27 марта 2016 г., 0:10 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
Да. Я посмотрел на код несколько больше и это перехват функций обратного вызова базы данных клиент wow и заменяя английский русский. Ты прав. Он не будет работать без него. Я просто увидел слово скрипт и испугался. :)

Робот программное обеспечение не допускается, и вы можете получить запретили за это.

**Comment by Contra111** [comment]
Кто не рискует, тот не пьет шампанское!
Так вы можете устранить ошибку или стоит просто не использовать RuWoW?

27 марта 2016 г., 0:15 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
LOL..., ваша цитата это смешно.

Я загрузился аддон. Я работаю на почему он будет показывать один тип значка, а не другие.

Находятся все ваши пути папки на английском языке, как моя?

![capture](https://cloud.githubusercontent.com/assets/17400948/14062564/1990d5b2-f361-11e5-9cc6-bc9944f35682.JPG)

**Comment by Contra111** [comment]
Не совсем понимаю чего вы хотите, вот мой путь аддону:
http://puu.sh/nV1hB/fd4b401817.jpg

27 марта 2016 г., 0:43 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Contra111** [comment]
Если вы про значки на карте, то у вас тоже не показываются "мечи"?

27 марта 2016 г., 0:48 пользователь Вадим Савенков <mr.v.vadim@gmail.com>
написал:

**Comment by Dyaxler** [comment]
Да. Идеальный. Вот, что мне нужно увидеть. Слова, используемые в пути к файлу всем быть на английском языке в противном случае клиент не найдете значок файлов изображений. Это было первое место, когда я посмотрел в коде. Изменить имена значков на то «меньше Английский» заставит переводчик mod игнорировать перевод на русский и вместо этого использовать английское слово. Но это не работает...

Я все еще работаю на нем. :)

----------------------------------------

Да. У меня есть RuWoW на моем компьютере и я не вижу мечи.

**Comment by Contra111** [comment]
Отлично! Если я смогу как-нибудь помочь, сообщите, пожалуйста.

27 марта 2016 г., 0:52 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
Вы делали что-нибыдь специальное с вашим клиентом WoW получить русский шрифт для работы в игре?

Кнопки в моей игре не на русском языке, поэтому я подозреваю, что я пропавш шрифт, который необходим для правильного отображения текста.

**Comment by Contra111** [comment]
С клиентом ничего не делал, правда скачивал клиент не с сайта носталриуса.
Вот мои шрифты:
http://puu.sh/nV3OO/52161fcaef.jpg

27 марта 2016 г., 1:25 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
Это не работа для меня. У вас есть локализованной русской версии Windows, поэтому я подозреваю, что системные шрифты, у вас есть отличаются от того, что у меня есть. Я установил пакет русского языка для windows, но мой wow клиент до сих пор не показаны России в пользовательском интерфейсе.

Это не является большим делом. Я уже определил, что вопрос заключается не в моде кода. Это проблема с как RuWoW обнаружения и замена шрифта строки. У меня есть один из примеров работы в Questie код, который я могу использовать в качестве тестового случая отслеживать какие строки заменяются. Затем я могу назвать их таким образом, что RuWoW не менять их без проблем английских игроков. :)

Это должно быть поздно там в России. Не бодрствовать для меня. Я собрал достаточно информации от вас, чтобы попытаться исправить эту проблему. Я буду продолжать размещать обновления в этой теме.

**Comment by Contra111** [comment]
Хорошо, в любом случае спасибо за помощь, удачи!

27 марта 2016 г., 1:39 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
Версия 2.64 выходит. Я добавил некоторый код в Questie, что предотвращает внесение изменений в строки языка, которые Questie необходимо правильно отображать объекты на миракарта addons как RuWoW и ruRU.

Пожалуйста, проверьте и дайте мне знать, если она исправлена.

**Comment by Contra111** [comment]
Теперь всё работает как надо! Спасибо!

27 марта 2016 г., 5:09 пользователь Dyaxler <notifications@github.com>
написал:

**Comment by Dyaxler** [comment]
Спасибо за проверку. Не вы когда-нибудь спать?!?!? :)

**Comment by Contra111** [comment]
Каково живется, таково и спится :)

2016-03-27 5:27 GMT+03:00 Dyaxler <notifications@github.com>:
