### ISSUE TITLE
Manual minimum level offset not working

### ISSUE THREAD

**Issue by Iowerth** [AeroScripts/QuestieDev#1961]
## Bug description
Manual minimum level offset not working. I set any value, but nothing happens. Even if I set value = 60.
If I set "Show all quests below range", it works fine.

## Screenshots
Value = 0:
![01](https://user-images.githubusercontent.com/10152411/82359281-5dad1580-9a10-11ea-8d4c-f8c3499e8ffc.jpg)

Value = 60 (no difference with value = 0):
![02](https://user-images.githubusercontent.com/10152411/82359352-74536c80-9a10-11ea-9309-233cb482798c.jpg)

Show all quests below range:
![03](https://user-images.githubusercontent.com/10152411/82359398-7f0e0180-9a10-11ea-82c8-f4523ed1036d.jpg)

## Questie version
5.10.3

**Comment by BreakBB** [comment]
This is fixed with 53769fecc2bfd0893adbdc095a05b14846a7aaff and a0bac3ef2975cf4b489802dcf6a215317e26b942
