### ISSUE TITLE
Reputation Calculation error 

### ISSUE THREAD

**Issue by Chzconey** [AeroScripts/QuestieDev#1965]
Date: 2020-05-21 01:01:52
ID: -1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\Questie\Modules\QuestieReputation.lua line 26:
   attempt to perform arithmetic on a string value
Debug:
   (tail call): ?
   ...terface\AddOns\Questie\Modules\QuestieReputation.lua:26: Update()
   ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:310:
      ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:308
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119

**Comment by drejjmit** [comment]
Fixed with b45c0236792c46d703e7eab9ca4f673312511333
Will be included in next release.
Thanks for the report.
