### ISSUE TITLE
Quest issue around [12] Proving Allegiance

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1967]
## Description

The quest calls for you to loot a candle from a box near the quest giver, however Questie doesn't have a loot icon for the candle. Tested on 11 Undead Priest.

## Wowhead link

* Proving Allegiance - Quest - World of Warcraft || https://classic.wowhead.com/quest=409/proving-allegiance

* Candle of Beckoning - Item - World of Warcraft || https://classic.wowhead.com/item=3080/candle-of-beckoning#comments

Candle can be found in Tirisfal Glades:

* 68.2,42

**Comment by BreakBB** [comment]
Same as with #1962 a blue quest icon should show up for the child quest.

**Comment by BreakBB** [comment]
@Gogo1951 Do you have more information on this?

**Comment by BreakBB** [comment]
Not able to reproduce this issue due to lack of information. Feel free to create another issue if this comes up again.
