### ISSUE TITLE
Quest issue around [60] The Matron Protectorate

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1972]
## Description

This quest shows up in UBRS in the little room after you kill Rend. There's one pack, then you have to pull the 2 orcs on the ledge, and once they are dead you can talk to the whelp on the ground. I'm not seeing this as an available quest when I mouse over the dungeon. Tested on 60 Orc Warrior.

## Wowhead link

* The Matron Protectorate - Quest - World of Warcraft || https://classic.wowhead.com/quest=5160/the-matron-protectorate

## Questie version

5.10.3

**Comment by BreakBB** [comment]
It is showing up for me just fine:

![image](https://user-images.githubusercontent.com/33514570/83294281-57c3eb00-a1ed-11ea-8f1c-33d9ccf48bbf.png)
