### ISSUE TITLE
Quest issue around [55] Hurley Blackbreath

### ISSUE THREAD

**Issue by evi1dave** [AeroScripts/QuestieDev#1973]
## Description

This quest is not showing as available in Kharanos from Ragnar Thunderbrew as an Alliance character.

## Wowhead link

https://classic.wowhead.com/quest=4126/hurley-blackbreath

## Questie version

5.10.3

**Comment by Gogo1951** [comment]
Hey @evi1dave,

Can you double check this by reloading your UI, dropping the quest, and taking a screenshot?

I've done this quest on Alliance at least 5 times, and I didn't have any problem with it. Looking at the DB, looks like we have it set up correctly. But... not to say there isn't something else going on. Let me know if you're able to re-test, thanks mate!

> [4126] = {"Hurley Blackbreath",{{1267,},nil,nil,},{{1267,},nil,},50,55,77,nil,{"Bring the Lost Thunderbrew Recipe to Ragnar Thunderbrew in Kharanos.",},nil,{nil,nil,{{11312,nil},},nil,},nil,nil,{4128,},nil,nil,nil,1584,nil,nil,nil,nil,nil,8,nil,nil,},

**Comment by Gogo1951** [comment]
Hey, possible your filter is set to ignore quests that are too high for you? There’s a known issue where the default range Questie uses sometimes doesn’t show quests that are available due to the available level and quest level being too different.

**Comment by evi1dave** [comment]
No luck on the reload, abandon attempt. My quest level options are 11 below and 7 above, though I do not have that enabled.
![2020-05-24](https://user-images.githubusercontent.com/30937862/82763866-a7af4600-9dd8-11ea-8e65-ecfaceea1207.png)

**Comment by Gogo1951** [comment]
Can you screenshot your Questie Preferences? Here's what I had for mine, they aren't default... but this works to see all the quests. Likely still a bug, but this is how you can short-term fix.

![image](https://user-images.githubusercontent.com/55365231/82769861-ff12dd80-9dfb-11ea-95ac-49e82b239b47.png)

**Comment by evi1dave** [comment]
Here's what I have currently.

![2020-05-25](https://user-images.githubusercontent.com/30937862/82798627-c6e4bc80-9e46-11ea-9d7b-9006b77cb9b1.png)

**Comment by BreakBB** [comment]
Hey @evi1dave you have to enable the "Show All Quests below range (Low level quests)" option in order to see low level quests.
By default Questie will only show quests which are at least green for your level.

**Comment by evi1dave** [comment]
A level 55 quest was yellow to me at 56.

**Comment by BreakBB** [comment]
Yeah that is as expected. The quests are colored as they are colored in the quest log.

Can you check if that quest above shows for you?
