### ISSUE TITLE
QuestieSerializer.lua (LUA) errors

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#1974]
Questie v5.10.3
Starting to get a lot of the error below.
Happens on different chars in different situations.

Date: 2020-05-24 19:04:45
ID: 2
Error occured in: Global
Count: 1
Message: ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua line 110:
   attempt to call field '?' (a nil value)
Debug:
   (tail call): ?
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:110:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:105
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:116:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:113
   (tail call): ?
   (tail call): ?
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:132:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:129
   (tail call): ?
   (tail call): ?
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:120:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:113
   (tail call): ?
   (tail call): ?
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:120:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:113
   (tail call): ?
   (tail call): ?
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:120:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:113
   (tail call): ?
   (tail call): ?
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:120:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:113
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:327: Deserialize()
   ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:396:
      ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:393
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...ce\AddOns\DataStore\libs\AceComm-3.0\AceComm-3.0.lua:222: OnReceiveMultipartLast()
   ...ce\AddOns\DataStore\libs\AceComm-3.0\AceComm-3.0.lua:256:
      ...ce\AddOns\DataStore\libs\AceComm-3.0\AceComm-3.0.lua:246
Locals:
None

**Comment by AeroScripts** [comment]
Were you in a regular party or a raid when this happened?

**Comment by Painstormx** [comment]
No, soloing

**Comment by AeroScripts** [comment]
You're totally sure you weren't in a group when that happened? Are you in a guild

The reason I ask is the error is related to quest progress sharing, which should only happen if you are in a party

**Comment by Painstormx** [comment]
99% sure I've not been grouped when I see this.
I am in a guild though.
I'll take note of it next time it happens.

**Comment by Painstormx** [comment]
Only seen it at times when I'm in a guild raid. Not often, but once in a while

**Comment by BreakBB** [comment]
@AeroScripts Any news on this?

**Comment by Painstormx** [comment]
I usually see it once when I'm in a raid group, and only in raid groups.
Don't think it's in 100% of the raids though and I can't really find any pattern in when it happens.

**Comment by Painstormx** [comment]
Saw it again today in a raid. Was just standing still at the start of MC and we were buffing and the error popped again.
It could also be due to offline people logging on while we were standing there.

**Comment by BreakBB** [comment]
This has been fixed and will be released very shortly with v6.0.0
