### ISSUE TITLE
Questie tracker and Enhanced Quest Log tracker Incompatibility

### ISSUE THREAD

**Issue by Thordin88** [AeroScripts/QuestieDev#198]
Hello again!
As mentioned in the title, aparently every time I disable questie tracker with the in-game command and try to use EHQL tracker - it reappears! To detail it, every time I make quest progress like killing an extra mob or looting an extra quest item Questie's tracker magically reappears overlapping EHQL's tracker.
Looking to see if others have this same issue, perhaps.
P.S: I am using EQL3.

**Comment by Dyaxler** [comment]
New release fixes this. v2.64 is ready to download.

I remember this coming up before and someone mentioned it while zoning. I just forgot to note it in my ToDo list. Thank you for bringing it up!

**Comment by Dyaxler** [comment]
Is this working now?

**Comment by Dyaxler** [comment]
I fixed a bunch of issues with Questie when using EQL3. Please try 2.65.

**Comment by Thordin88** [comment]
Found a bug while doing shaman water quest. By that I mean I wasn't able to turn in a part of it (think it was the Brinne part in southwestern Barrens). That was caused by a questie LUA error (nil value).

**Comment by Dyaxler** [comment]
Please don't double post. :)
