### ISSUE TITLE
Quest issue around [19] The Warsong Reports

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1985]
## Description

When you pick up [19] The Warsong Reports it's not showing where to run them in. Tested on a 26 Undead Priest. 99% sure this worked on an Orc, just not showing correctly for Undead. Orc in my party seemed to see them fine.

Part 2: And even when I get the final item, it doesn't track in my log. Warsong Scout Update 0/1.

Part 3: It did finally register that the quest was "done" - once I reloaded my UI, but then it didn't show the "done" ? on the map or mini-map.

## Wowhead link

* The Warsong Reports - Quest - World of Warcraft || https://classic.wowhead.com/quest=6543/the-warsong-reports

* Warsong Outrider Update - Quest - World of Warcraft || https://classic.wowhead.com/quest=6546/warsong-outrider-update

* Warsong Runner Update - Quest - World of Warcraft || https://classic.wowhead.com/quest=6545/warsong-runner-update

* Warsong Scout Update - Quest - World of Warcraft || https://classic.wowhead.com/quest=6547/warsong-scout-update

## Screenshots

![WoWScrnShot_052920_185021](https://user-images.githubusercontent.com/55365231/83314234-204e4200-a1df-11ea-8da8-e5bc2ff9155d.jpg)

![WoWScrnShot_052920_190535](https://user-images.githubusercontent.com/55365231/83314335-876bf680-a1df-11ea-9059-ae22576ad1c0.jpg)

![WoWScrnShot_052920_191016](https://user-images.githubusercontent.com/55365231/83314473-30b2ec80-a1e0-11ea-8f03-ce319579b2dd.jpg)

![WoWScrnShot_052920_191026](https://user-images.githubusercontent.com/55365231/83314477-33154680-a1e0-11ea-94ab-752f63aee72f.jpg)

## Questie version

5.10.3

**Comment by BreakBB** [comment]
@Gogo1951 Can you run `/dump GetQuestGreenRange()` on your level 26 Priest? Most likely it is because of the quest level.

**Comment by BreakBB** [comment]
Also about that progress problem: That is a server side problem because Blizzard doesn't care about firing a QLU event for them. There are a few other quests with similar behavior :/

**Comment by BreakBB** [comment]
@Gogo1951 Any news/ideas on this?

**Comment by BreakBB** [comment]
Not able to reproduce this issue due to lack of information. Feel free to create another issue if this comes up again.
