### ISSUE TITLE
"/questie mapaids" returns "Unknown operation"

### ISSUE THREAD

**Issue by crni536** [AeroScripts/QuestieDev#199]
Ever since version 2.63, the command "/questie mapaids" returns the message that the operation is unknown.
This command worked on previous versions, I reverted back to 2.62 and confirmed that it does work on that version.
Same thing happens on the 2.64 as well. I used this command primarily to reset the mapaids since they would not refresh and show objectives of newly picked up quests.
If it helps, other quest-related addons I have activated are Cartographer, shaguQuest, Extended QuestLog 3.6.1
![wow_2016-03-27_13-02-59](https://cloud.githubusercontent.com/assets/8262850/14065129/5075c580-f41d-11e5-84ac-f16f16dc45eb.jpg)

**Comment by Dyaxler** [comment]
Release a hot fix for this and updated release v2.64 zip file.

**Comment by Dyaxler** [comment]
Issue resolved?

**Comment by Dyaxler** [comment]
No response - assumed issue resolve via Hotfix.
