### ISSUE TITLE
Availability Listing of 'Valik' Quest in Alterac Mountains

### ISSUE THREAD

**Issue by Pawgfarts** [AeroScripts/QuestieDev#1991]
## Bug description
The quest 'Valik' (ID 535) remains in the available category of listed Alterac Mountains quests even after the associated quest 'Infiltration' (ID 533) is completed which makes it unobtainable.

## Screenshots

![265923](https://user-images.githubusercontent.com/66169124/83329011-c465d680-a23b-11ea-9ce2-bf11b1c59ca7.jpg)

## Questie version

v5.10.3

**Comment by BreakBB** [comment]
Thanks for reporting it 🙏 

I fixed this with a4c25e7d9f11c66c2d0c0865098fadf808e80074 and it will be included in the next release.
