### ISSUE TITLE
Incorrect reputation requirements on listed quests.

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#1992]
## Description
With new changes some previously hidden quests showed up. 
Reptuation data on these are incorrect:

[[60] Traitor to the Bloodsail (9259)] from hated. unavailable at neutral with booty bay
[[60] Avast Ye, Admiral! (4621)] Requires at least Bloodsail Buccaneers (Friendly)
[[60] Mending Old Wounds (9267)] from hated. unavailable at neutral with ratchet
[[60] Making Amends (9266)] from hated. unavailable at neutral with everlook
[[60] War at Sea (9268)] from hated. unavailable at neutral with gadgetzan

## Wowhead link
https://classic.wowhead.com/quest=9259
https://classic.wowhead.com/quest=4621
https://classic.wowhead.com/quest=9267
https://classic.wowhead.com/quest=9266
https://classic.wowhead.com/quest=9268

## Questie version
v6.0 alpha

**Comment by BreakBB** [comment]
Fixed with c011ffe17c2bdaef168f566ae0493bacf8a44d7d and 9a3e2fecfd2ff2c2da6162e754959abc94101c6f.
