### ISSUE TITLE
inaccurate objective marker for [55] Beware of Pterrordax

### ISSUE THREAD

**Issue by silverhawke249** [AeroScripts/QuestieDev#1996]
## Description
Questie shows objective markers for Pterrordax mobs at locations where they cannot actually be found.

## Wowhead link
Quest link: https://classic.wowhead.com/quest=4501/beware-of-pterrordax
Location of Pterrordax mobs: https://classic.wowhead.com/npc=9166/pterrordax

## Screenshots
![image](https://user-images.githubusercontent.com/50395934/83409996-1d09bf00-a448-11ea-91ee-bca4f93f8f69.png)
(Pterrordax cannot be found on the eastern/southern side of the zone, except for the southernmost area.)

## Questie version
v5.10.3

**Comment by Gogo1951** [comment]
Hey @silverhawke249 ,

Agreed they don't spawn in the middle, but WoWHead is off on this one too. They spawn by all the Pylons, and there's none listed in WoWHead on the Eastern Pylon.

I'll update to use WoWHead values, but they're still going to be off. Better, not great.

@AeroScripts new CMANGOS DB would probably help. (=

**Comment by drejjmit** [comment]
@BreakBB 

> 
        [9166] = {
            [QuestieDB.npcKeys.spawns] = {[490] = {{57.2,10.2},{50.4,10.4},{50.4,10.8},{58.4,10.8},{50.6,10},{56.2,10},{56.4,11.2},{56.6,11.4},{50.4,11.8},{50.6,11},{56.4,12.2},{56.8,12.4},{50.4,12.6},{56.4,12.6},{57,12.6},{47.4,12.8},{50.6,12},{55.4,12},{48.4,13.2},{48.4,13.8},{51.6,13.8},{51,13},{57.6,13},{49.4,14.2},{58,14.2},{50,14},{54.6,14},{58.2,15.8},{54,16.4},{52.2,16},{56.2,8.2},{57.4,8.2},{57.8,8.8},{42.8,85.4},{57.6,85.4},{54.6,85.8},{57.4,86.4},{58,86.4},{49,86.6},{54.4,86.6},{47.2,86.8},{42.8,86},{49.8,87.2},{57.4,87.2},{57.6,87.2},{43.8,87.4},{44.8,87.4},{55.4,87.4},{56.4,87.4},{43.4,87.6},{55.4,87.6},{57.6,87.8},{43.2,87},{50.8,87},{50.4,88.2},{56.4,88.2},{44.2,88.4},{44.6,88.4},{56.6,88.4},{56.2,88.6},{42.6,88.8},{50.4,88.8},{50.6,88},{44.2,89.2},{44.8,89.4},{56.6,89.4},{58.2,89.4},{44.6,89.6},{50.4,89.6},{50.6,89.6},{42.4,89},{50.6,89},{59,9.2},{50.6,9.4},{57.6,9.6},{56.2,9},{57.4,9},{44.4,90.2},{43.4,90.4},{56.4,90.4},{57.6,90.4},{44.4,90.6},{43,90.8},{44.6,90.8},{50.2,90.8},{57.8,90.8},{57,90},{56.4,91.2},{56.6,91.2},{56.4,91.6},{43,91.8},{43.4,92.6},{43.6,92.6},{57.8,92.6},{56.8,92.8},{43.8,92},{55.4,92},{56.6,92},{57.8,92},{43.2,93.6},},},
> 
Before:
![image](https://user-images.githubusercontent.com/15526476/83413851-ce92fb00-a41c-11ea-9b5e-f91224006590.png)

After:
![image](https://user-images.githubusercontent.com/15526476/83413875-d783cc80-a41c-11ea-9a5f-bc7570cfedbd.png)

**Comment by Gogo1951** [comment]
Eastern Pylon ones are:

* Fledgling Pterrordax - NPC - World of Warcraft || https://classic.wowhead.com/npc=9165/fledgling-pterrordax

Thanks @drejjmit !
