### ISSUE TITLE
Quest "The Book of Ur" fails to show up on map or minimap

### ISSUE THREAD

**Issue by SpareSimian** [AeroScripts/QuestieDev#1998]
v5.10.3.

The Book of Ur (quest 1013) does not show up on the map or minimap but I can see the "!" over the quest giver in Undercity. 

https://classic.wowhead.com/quest=1013/the-book-of-ur#comments

I'm a level away from accepting other quests for Shadowfang Keep so I'll avoid accepting this one until then in case I can do any further testing.

**Comment by drejjmit** [comment]
What level are you? This quest can be picked up at 16 but has a recommended level of 26 (10 levels). Default filtering shows quest 7 levels above your level.

**Comment by SpareSimian** [comment]
I was level 17. (I was collecting SFK quests and saw that I needed to be 18 for the other two. So I went to the Barrens after that and worked on prereqs for WC quests, where I dinged 18.)

**Comment by drejjmit** [comment]
You need to be 19 to see it with default settings. You can set it higher.

**Comment by SpareSimian** [comment]
Why would I need to be 19 to see a level 16 quest? Are there other quests with this broad a difference from allowed to recommended? Should the default range be increased?

**Comment by BreakBB** [comment]
We already changed the way how to determine which quests to show. With the next version all quests for which the requirement is fulfilled will be shown. "Low level quests" will be hidden by default once a certain level distance has been reached (like before).

The reason why it wasn't changed earlier is that some more parts of the addon relied in this behaviour. We also weren't sure if "stupidly" showing all quests that can be accepted is really a good design decision since there is a reason why a quest's level is a lot higher than the required level. Also red quests don't reward much XP.

**Comment by SpareSimian** [comment]
That's interesting and something I was unaware of. I thought the harder the quest, the more XP one got. Is there some way to know the optimum level to get maximum XP? That would be a useful piece of information to present, allowing me to defer low-return quests until I hit the optimum level.

**Comment by BreakBB** [comment]
Hmmm after a quick research to give you a link it seems I was wrong. Quests seem to always give the same amount of XP, except they are grey:

https://www.engadget.com/2007-03-26-the-facts-behind-quests-and-their-xp.html

https://www.reddit.com/r/classicwow/comments/acqxup/til_that_quests_always_give_the_same_xp_except_if/


So if Questie shows you a quest will reward you with 1k XP that will be the case as long as the quest is not grey.

**Comment by Gogo1951** [comment]
> That's interesting and something I was unaware of. I thought the harder the quest, the more XP one got. Is there some way to know the optimum level to get maximum XP? That would be a useful piece of information to present, allowing me to defer low-return quests until I hit the optimum level.

A lot of people think this, but it's only gray quests that give less XP. (=

When I'm on a "gotta level fast" kick, I usually stick to green quests. Reds slow me down.
