### ISSUE TITLE
Adjust position of quest tracker when quests get untracked as well

### ISSUE THREAD

**Issue by silverhawke249** [AeroScripts/QuestieDev#1999]
## Description
currently my Quest Tracker is basically anchored right -- when a quest is tracked that has a long name and/or long objectives, the region of the tracker goes left to ensure the rightmost bit of text stays in the same horizontal position.

except, when said quest with long text is removed from the tracker, everything stays at the same place instead of receding back to the right. so far, i could only reset this back to the right by reloading. pictured is before and after reload:
![image](https://user-images.githubusercontent.com/50395934/83665581-2fc5f480-a5fe-11ea-8d38-0f445293e2a6.png)

is it possible to have this as an option?

**Comment by Dyaxler** [comment]
I've been working this past month to bring a lot of the old Tracker features from the Vanilla 1.12 version of Questie into Classic.

In the up and coming 6.0 version the Questie Tracker will have 4 setPoints and the tracker will grow and resize itself based on that setPoint which can either be manually set or set to "auto" and will be determined by where the tracker is dragged on screen.

Example, if you drag it to the lower left quadrant then the tracker will fill up and to the right... never going off screen.

**Comment by BreakBB** [comment]
@silverhawke249 As Dyaxler already said there has been a lot of work on the Tracker and all those changes will be released very shortly with v6.0.0
