### ISSUE TITLE
Quest Issue: Gold Dust Exchange

### ISSUE THREAD

**Issue by abennette32** [AeroScripts/QuestieDev#2]
The quest Gold Dust Exchange (http://www.wowhead.com/quest=47/gold-dust-exchange) puts three points, two in the Fargodeep mine and one in the Jangolode mine. Possibly intentional.

**Comment by AeroScripts** [comment]
Kobolds at both locations drop the dust, so it's probably they're both left in.

As for there being two for one location I'm planning on implementing something that checks for a minimum distance before adding another point to avoid unnecessary duplicates (they're everywhere)

**Comment by abennette32** [comment]
Alright. Would you like me to continue reporting bugs or is this project not very serious.

**Comment by AeroScripts** [comment]
I'd love it :) Any bugs people submit are definitely appreciated. I want to get things really polished, and I don't intend on stopping any time soon. 
_Still getting used to the whole "managing a github project" thing though, bear with me._
