### ISSUE TITLE
Cartographer map always resets to current map

### ISSUE THREAD

**Issue by Schaka** [AeroScripts/QuestieDev#20]
Also another bug I noticed, once you switch the map in cartographer, every 250ms it will switch it back automatically to the map you are currently on

**Comment by Logonz** [comment]
This is done in the function function Questie:getPlayerPos()

A "bugfix" is commented but what does it fix?

**Comment by Schaka** [comment]
Thank you for this. If you submit a pull request, I will merge it into master. Unfortunately I can't test anything myself currently, as I'm at work.

**Comment by Logonz** [comment]
A Pull request has been submitted!
