### ISSUE TITLE
Is there a way to disable blizzard tracker?

### ISSUE THREAD

**Issue by fagitomania** [AeroScripts/QuestieDev#2001]
Every quest i do i have to open quest log and shift click the quest so it doesn't show a second time from the blizzard default tracker. Can i disable that?

**Comment by Dyaxler** [comment]
Go into Questie Options --> Tracker and make sure you have "Enable Tracker Hooks" checked. That should hide the default blizzard tracker and the default Questie tracker should appear. We're working on a new and improved tracker for version 6 here soon with loads of new features and QOL improvements. Stay tuned!
