### ISSUE TITLE
Wrong operator (+ instead of ..) in debug print

### ISSUE THREAD

**Issue by SpareSimian** [AeroScripts/QuestieDev#2002]
v5.10.3

I just dinged friendly with Orgrimmar and got this error:

Message: ...terface\AddOns\Questie\Modules\QuestieReputation.lua line 26:
   attempt to perform arithmetic on a string value

Questie:Debug(DEBUG_DEVELOP, "QuestieReputation: Update -", "faction \"" + name + "\" (" + factionID + ") changed")

I think you want .. instead of + for string concatenation.

**Comment by drejjmit** [comment]
It's fixed on master. Will be included in next release.
https://github.com/AeroScripts/QuestieDev/blob/master/Modules/QuestieReputation.lua#L26
Thanks for the report.

**Comment by BreakBB** [comment]
Duplicate of #1965 and already fixed
