### ISSUE TITLE
Hidden Quest List

### ISSUE THREAD

**Issue by FLHTCU** [AeroScripts/QuestieDev#2008]
My Questie quest list is always hiding behind my right action bars.  It seems locked against the right side of the WoW window.  It was movable at one point, but a little while back it no longer gave me an option to move it.  Where ever it was on the specific toon, it is now locked in place.
![Questie](https://user-images.githubusercontent.com/42047099/84559795-7e147b00-ad03-11ea-88c9-ea98457bac08.png)

**Comment by BreakBB** [comment]
@FLHTCU Did you try to reset the Tracker position in the settings? When the tracker is not locked you can move it with `CRTL + left click` by default.

**Comment by FLHTCU** [comment]
I've tried to reset it several times.  

When I first installed it, I could unlock and move it.  As of a few weeks ago, I can no longer unlock it, so I can't move it.   The menu to unlock it does not come up for me regardless of the combination of CTRL, SHIFT, or left/right clicks I use.



    On Saturday, June 13, 2020, 2:01:42 AM CDT, Björn Böing <notifications@github.com> wrote:  
 
 


@FLHTCU Did you try to reset the Tracker position in the settings? When the tracker is not locked you can move it with CRTL + left click by default.

**Comment by BreakBB** [comment]
@FLHTCU That sounds like some other window/addon is above our tracker if the right click menu doesn't come up.

Can you do a `/fstack` and share a screenshot of your UI?`After you took the screenshot type the command again to hide the green windows.

**Comment by FLHTCU** [comment]
Here's the screenshot.  I moused over the entire screen and the only green boxes I saw near the questie list were the right action bars

    On Saturday, June 13, 2020, 1:07:27 PM CDT, Björn Böing <notifications@github.com> wrote:  
 
 


@FLHTCU That sounds like some other window/addon is above our tracker if the right click menu doesn't come up.

Can you do a /fstack and share a screenshot of your UI?`After you took the screenshot type the command again to hide the green windows.

**Comment by BreakBB** [comment]
@FLHTCU Uhm your post doesn't contain a file/link/screenshot 🤔 You can simply paste the screenshot into the field. Not sure how it is handled when answering by mail though...

**Comment by FLHTCU** [comment]
![WoWScrnShot_061320_131430](https://user-images.githubusercontent.com/42047099/84576392-0d5c7580-ad7a-11ea-8be2-a6b9a107a87f.jpg)
I tend to forget to come here, I hate forums and such, as a rule.

**Comment by BreakBB** [comment]
@FLHTCU Sorry to hear you hate GitHub ^^ For us devs it helps a lot to keep the code and issues in one place ;)

Towards your screenshot: It looks like some addon added a frame which fills the complete screen. You should try to disable all addons except Questie and then try to move the tracker.

The "MoLibPixelPerfectFrame" is non of the default frames and will likely give Questie a hard time.

**Comment by FLHTCU** [comment]
Thanks that worked... I think it was an add-on called "Faster Looting" as I added 1 add-on at a time until the error occurred again, and that is the add-on I activated that caused the error.  I then deleted it and any others I was not using regularly.  So far it looks good.



 

    On Saturday, June 13, 2020, 1:39:22 PM CDT, Björn Böing <notifications@github.com> wrote:  
 
 


@FLHTCU Sorry to hear you hate GitHub ^^ For us devs it helps a lot to keep the code and issues in one place ;)

Towards your screenshot: It looks like some addon added a frame which fills the complete screen. You should try to disable all addons except Questie and then try to move the tracker.

The "MoLibPixelPerfectFrame" is non of the default frames and will likely give Questie a hard time.

**Comment by BreakBB** [comment]
@FLHTCU Can you check that again by enabling only FasterLooting and Questie and run `/fstack`? I am using that addon as well and never had a problem like this 🤔 

Knowing which addon it is we might be able to either contact the developers of that addon and/or add a fix on our side.

**Comment by FLHTCU** [comment]
I reinstalled faster looting, and now it's working right, with it, again.   I can't figure it out, now, but it's working..I don't know what caused it, then.   But it is working now, thank you.  







    On Saturday, June 13, 2020, 2:13:46 PM CDT, Björn Böing <notifications@github.com> wrote:  
 
 


@FLHTCU Can you check that again by enabling only FasterLooting and Questie and run /fstack? I am using that addon as well and never had a problem like this 🤔
 
Knowing which addon it is we might be able to either contact the developers of that addon and/or add a fix on our side.

**Comment by BreakBB** [comment]
@FLHTCU Too bad, but I am glad it is fixed for you.
