### ISSUE TITLE
'Quests below level' slider not changing anything

### ISSUE THREAD

**Issue by TedTheFarmer** [AeroScripts/QuestieDev#2009]
## Bug description
When I enable manual minimum level offset and slide the bar to show quests a certain number of levels beneath me it's not updating anything, it looks to be stuck on 5-6 level beneath me no matter what options I modify.

The bar for levels above me looks to be working perfectly fine though!

Please note for the screenshot below, my current level is 42.

## Screenshots
![WoWScrnShot_061320_101118](https://user-images.githubusercontent.com/66866693/84565059-8948c480-ad5e-11ea-9f20-0d1b26c1ec6a.jpg)

## Questie version
5.10.3

**Comment by BreakBB** [comment]
Duplicate of #1961 and already fixed. Fix will be included in v6 which is currently available as beta version on our Discord.
