### ISSUE TITLE
Quest tracker doesen't work v2.64

### ISSUE THREAD

**Issue by Mormor123** [AeroScripts/QuestieDev#201]
Hi Man. My Quest tracker doesent work for some reason. I tried to shift click and it doesent work either

**Comment by Mormor123** [comment]
And Also this pop up when I accept a quest: Interface/AddOns/!Questie/Modules/QuestieTracker.lua:731: attempt to index global 'QuestieTrackerHeader' (a nil value)

**Comment by Schaka** [comment]
Please add which version of Questie you are using.

**Comment by Mormor123** [comment]
you know whats the problem Schaka?

**Comment by Dyaxler** [comment]
I do... you need to run /questie clearconfig. Your config file doesn't contain the QuestieTrackerHeader table value and it's nil'ing out. Doesn't matter if the feature is on or off. If that isn't in there then there are other values that aren't present either... I've added some code to help with the QuestTracker menu to make sure it behaves. If that's not in there either, you aren't going to move that sucker anytime soon. :P

**Comment by Mormor123** [comment]
Ty alot:)

**Comment by Dyaxler** [comment]
Did that work?

**Comment by Mormor123** [comment]
Yep
Den 29 mar 2016 17:42 skrev "Dyaxler" <notifications@github.com>:

**Comment by Dyaxler** [comment]
Awesome! :)
