### ISSUE TITLE
Quest issue around [60] Aurius' Reckoning

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2011]
## Description

This quest does not show as an available quest ! on Stratholme.

## Wowhead link

* Aurius' Reckoning - Quest - World of Warcraft || https://classic.wowhead.com/quest=5125/aurius-reckoning

**Comment by drejjmit** [comment]
Did you complete the prequest https://classic.wowhead.com/quest=5122/the-medallion-of-faith ?

**Comment by Gogo1951** [comment]
Yes, and even when you do the quest doesn't show up as available in the instance. It's a bit of a weird quest, granted... having to turn the medallion in to make it available. Certainly not a high priority fix. (=

**Comment by BreakBB** [comment]
@Gogo1951 When removing the preQuest from 5125 both show up just right for me.


![image](https://user-images.githubusercontent.com/33514570/84597010-3a378800-ae61-11ea-9731-5a96e34d45cc.png)

But the problem is 5122 is repeatable (according to #1140) which means it can never be "completed".

Can you run `/dump IsQuestFlaggedCompleted(5122)` please.

**Comment by Gogo1951** [comment]
Got it, thanks! I have repeatable quests hidden. It is a repeatable quest I guess... sort of. Good catch.

**Comment by BreakBB** [comment]
@Gogo1951 Wait the follow up quest shouldn't be repeatable from what I know, is it?

Also could you report what the command above is printing?

**Comment by drejjmit** [comment]
It's not repeatable per say. You can only do it once per instance but you can do it multiple times (like the trap in Dire maul) so it should be tagged repeatable

**Comment by BreakBB** [comment]
"The Medallion of Faith" quest is (from the game perspective) indeed repeatable, but the follow up quest "Aurius' Reckoning" is not:

![image](https://user-images.githubusercontent.com/33514570/86279421-4601a900-bbda-11ea-905e-11273a35f1c6.png)


So our data is correct on this.
