### ISSUE TITLE
Quest issue around [60] The Truth Comes Crashing Down

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2012]
## Description

This quest does not show as an available quest ! on Stratholme.

## Wowhead link

* The Truth Comes Crashing Down - Quest - World of Warcraft || https://classic.wowhead.com/quest=5262/the-truth-comes-crashing-down
* Head of Balnazzar - Item - World of Warcraft || https://classic.wowhead.com/item=13250/head-of-balnazzar
* Balnazzar - NPC - World of Warcraft || https://classic.wowhead.com/npc=10813/balnazzar

**Comment by BreakBB** [comment]
@Gogo1951 And again it looks like the NPC spawn is missing as you can see when running `/dump QuestieLoader:ImportModule("QuestieDB"):GetNPC(10813)`.

It should be `[2017] = {{-1,-1},},`
