### ISSUE TITLE
Quest issue around [26] The Glowing Shard

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2013]
## Description

This quest does not show as an available quest ! on Wailing Caverns.

## Wowhead link

* The Glowing Shard - Quest - World of Warcraft || https://classic.wowhead.com/quest=6981/the-glowing-shard
* Glowing Shard - Item - World of Warcraft || https://classic.wowhead.com/item=10441/glowing-shard
* Mutanus the Devourer - NPC - World of Warcraft || https://classic.wowhead.com/npc=3654/mutanus-the-devourer

**Comment by Gogo1951** [comment]
>         [6981] = {
            [QuestieDB.questKeys.startedBy] = {{3654},nil,{10441}},
        },

From the corrections file... but the quest still doesn't show up.

**Comment by BreakBB** [comment]
@Gogo1951 Same as with the other issue, the spawn is missing from the NPC as you can see when running `/dump QuestieLoader:ImportModule("QuestieDB"):GetNPC(3654)`.

It should be `[718] = {{-1,-1},},`
