### ISSUE TITLE
Quest issue around [12] Journey to the Crossroads

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2014]
## Description

This quest is showing up in Camp Turajo, but it's not actually available. Tested on Tauren Druid.

## Wowhead link

* Journey to the Crossroads - Quest - World of Warcraft || https://classic.wowhead.com/quest=854/journey-to-the-crossroads

## Screenshots

![WoWScrnShot_061220_175004](https://user-images.githubusercontent.com/55365231/84582085-ebc8b180-adac-11ea-9e83-a1d8e07e8f0c.jpg)

**Comment by BreakBB** [comment]
@Gogo1951 Have you done any of the quests this NPC starts: https://classic.wowhead.com/npc=3429/thork

?

**Comment by Gogo1951** [comment]
Yes, I had on that toon. Struggled to find the official "exclusive" quest to this. Once I did Tauren start, I moved over to do Orc / Troll start zones. This quest is weird since it's a low quest in Camp Turajo (like a level 20ish area) you'd naturally hit coming out of the Tauren start zone, but I had ported over to do Org instead of running over. I did all the Orc start zone quests so one of those probably is the Exclusive data point.

**Comment by BreakBB** [comment]
Hmmm... Won't be easy to test or better said: Will require some time to investigate.

**Comment by Gogo1951** [comment]
I'll message some folks on the server I'm on, see if I can get some level 9 Taurens to test this for us. Cheers!

**Comment by Gogo1951** [comment]
OLD comment I found:

> By Grimhyde on 08/16/2008 (Patch 2.4.3)
> As a Tauren Warrior, I could not pick up this quest. I do think it is a Tauren exclusive, but I think it is also mutually exclusive with the quest http://vanillawowdb.com/?quest=860 Sergra Darkthorn because I have completed this quest with my Tauren warrior and http://vanillawowdb.com/?quest=854 Journey to the Crossroads is unavailable.

> Note: This is not confirmed.

> P.S. Some believe it is only available after completing http://vanillawowdb.com/?quest=844 Plainstrider Menace. I have completed this quest as well and http://vanillawowdb.com/?quest=854 Journey to the Crossroads is still unavailable.

* Journey to the Crossroads - Quest - Classic wow database || https://classicdb.ch/?quest=854

**Comment by BreakBB** [comment]
@Gogo1951 Let me know if you find a player. If not I will level my Tauren 2 levels more.

**Comment by drejjmit** [comment]
According to https://discordapp.com/channels/263036731165638656/579966856085897216/753980900676468736 it's disabled by "Disrupt the Attacks"
