### ISSUE TITLE
Quest issue around [60] Seal of Ascension

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2015]
## Description

The turn in for the quest is not shown; you have to go back to LBRS and turn the quest in to Vaelan to complete it.

## Wowhead link

* Seal of Ascension - Quest - World of Warcraft || https://classic.wowhead.com/quest=4743/seal-of-ascension
* Vaelan - NPC - World of Warcraft || https://classic.wowhead.com/npc=10296/vaelan

**Comment by Gogo1951** [comment]
Hey @BreakBB ,

I think this is deeper than just a data issue.

Here's how I would have fixed it:

>        [4743] = {
>            [QuestieDB.questKeys.finishedBy] = {{10296,},nil,},
 >       },

And here's what the DB has in it already, seems to already point to Vaelan as the turn in.

> [4743] = {"Seal of Ascension",{{10296,},nil,nil,},{{10296,},nil,},57,60,255,nil,{"Travel to the Wyrmbog in Dustwallow Marsh. Find the ancient drake, Emberstrife and beat him without mercy until his will is broken.","It is at that moment which you must place the Unforged Seal of Ascension before the great beast. You must then be quick to use the Orb of Draconic Energy on his weakened form and claim dominion over his mental faculties. Control the beast and force the Flames of the Black Dragonflight upon the Unforged Seal of Ascension!",},nil,{nil,nil,{{12324,nil},},nil,},12339,nil,{4742,},nil,nil,nil,1583,nil,nil,nil,nil,nil,nil,nil,nil,},

**Comment by BreakBB** [comment]
@Gogo1951 Well the spawn for Vaelan is missing. Should point to `[1583]={{-1, -1},},`
