### ISSUE TITLE
Quest issue around [20] The Ashenvale Hunt

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2017]
## Description

You should only be able to get one of these quests, but the exclusivity of the quest in the data is off. Even when I have one, Questie still shows the others as being available. I think the issue is with all 4, I only tested 2... 

## Wowhead link

* The Ashenvale Hunt - Quest - World of Warcraft || https://classic.wowhead.com/quest=235/the-ashenvale-hunt
* The Ashenvale Hunt - Quest - World of Warcraft || https://classic.wowhead.com/quest=742/the-ashenvale-hunt
* The Ashenvale Hunt - Quest - World of Warcraft || https://classic.wowhead.com/quest=6382/the-ashenvale-hunt

**Comment by BreakBB** [comment]
@Gogo1951 I am pretty sure the quest in Ashenvalue at "Senani Thunderheart" can still be done when you did any of the others.

**Comment by Gogo1951** [comment]
Yes, just confirmed. I'll update the PR.

**Comment by Gogo1951** [comment]
So the data looks right, but the quest still shows up in Questie when you pick up one of the "exclusive to" quests.

  >      [235] = {
  >         [QuestieDB.questKeys.exclusiveTo] = {742,6382,6383,},
  >      },

 >       [742] = {
 >           [QuestieDB.questKeys.exclusiveTo] = {235,6382,6383,},
 >       },

>        [6382] = {
>            [QuestieDB.questKeys.preQuestSingle] = {882},
>           [QuestieDB.questKeys.exclusiveTo] = {235,742,},
>        },

Not sure how to fix this.

**Comment by bantern** [comment]
After completion of all 4 related quests, the "Available" text and quest "!" marker remain on NPC "Senani Thunderheart".

**Comment by drejjmit** [comment]
> After completion of all 4 related quests, the "Available" text and quest "!" marker remain on NPC "Senani Thunderheart".

This was fixed on 6.0.4. 
Are you really on latest version?

**Comment by bantern** [comment]
> 
> 
> > After completion of all 4 related quests, the "Available" text and quest "!" marker remain on NPC "Senani Thunderheart".
> 
> This was fixed on 6.0.4.
> Are you really on latest version?

You're totally right. The update solved it. I'm sorry for the waste of time.

**Comment by BreakBB** [comment]
@drejjmit This can be closed then, yes?

**Comment by drejjmit** [comment]
Yes. This quest has been tested and works.

**Comment by BreakBB** [comment]
@drejjmit Thanks for the response and sorry for the late reply 😅
