### ISSUE TITLE
Quest Tracker gone

### ISSUE THREAD

**Issue by erikabp123** [AeroScripts/QuestieDev#202]
Updated to the new version of Questie today (from a 2.x ver to the newest 2.64) and the quest tracker has disappeared. Managed to get the quests on the map through a toggle, but cant get the tracker despite resetting position (thought I might have moved it off screen by accident) and by using the toggle command for it. I didn't have this problem before updating so I figure it is probably something with the newest version. I installed EQL3 AFTER the tracker was gone and it ofc. doesnt work with EQL3 on either. I DID get this error while trying to track a quest by shift-clicking it, but that was with EQL3 on.
http://i.imgur.com/YOBP8wV.png

**Comment by Dyaxler** [comment]
Did you try /questie clearconfig? The error from your screenshot is because there is a table that it's looking for that isn't in there. This is a common issue when folks upgrade.

**Comment by erikabp123** [comment]
This seems to have fixed the issue, thank you.

**Comment by Dyaxler** [comment]
CTRL+SHIFT+Mouse click-hold to drag. Same with the QuestArrow.

**Comment by erikabp123** [comment]
thank you

**Comment by Dyaxler** [comment]
Fixed a bunch of bugs/conflicts in Questie when you have EQL3 loaded. Please try 2.65.
