### ISSUE TITLE
Durability Frame Resets

### ISSUE THREAD

**Issue by Nexrus333** [AeroScripts/QuestieDev#2031]
The durability frame resets to the left side of the tracker every time you unequip a piece of armor - even if you have the option unchecked. Running the latest version.

**Comment by Dyaxler** [comment]
Is this the current release or the 6.0 Beta?

**Comment by BreakBB** [comment]
@Nexrus333 Please use the prefilled issue template so we get the required information, thanks :)

**Comment by Nexrus333** [comment]
## Bug description
The durability frame resets to the left side of the tracker every time you unequip a piece of armor - even if you have the option unchecked.

Which version of Questie are you using? 
5.10.3

**Comment by Dyaxler** [comment]
That will be fixed in the up and coming v6.0

**Comment by BreakBB** [comment]
This has been fixed on master and will be released very shortly with v6.0.0
