### ISSUE TITLE
LUA error when reputation changes

### ISSUE THREAD

**Issue by teelolws** [AeroScripts/QuestieDev#2033]
...terface\AddOns\Questie\Modules\QuestieReputation.lua:26: attempt to perform arithmetic on a string value

**Comment by teelolws** [comment]
Might be something to do with me changing game text language occasionally (to test localization changes on other addons).

**Comment by BreakBB** [comment]
Duplicate of #1965 and already fixed :) Will be included in the v6.0.0 update
