### ISSUE TITLE
Questie issue

### ISSUE THREAD

**Issue by Vidoqueen** [AeroScripts/QuestieDev#2038]
Date: 2020-06-17 20:44:08
ID: 1
Error occured in: Global
Count: 1
Message: ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua line 110:
   attempt to call field '?' (a nil value)
Debug:
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:110:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:105
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:120:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:113
   (tail call): ?
   (tail call): ?
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:132:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:129
   (tail call): ?
   (tail call): ?
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:120:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:113
   (tail call): ?
   (tail call): ?
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:116:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:113
   (tail call): ?
   (tail call): ?
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:120:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:113
   (tail call): ?
   (tail call): ?
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:120:
      ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:113
   ...ce\AddOns\Questie\Modules\Libs\QuestieSerializer.lua:327: Deserialize()
   ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:396:
      ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:393
   [C]: ?
   ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...s\LibThreatClassic2\Libs\AceComm-3.0\AceComm-3.0.lua:218: OnReceiveMultipartLast()
   ...s\LibThreatClassic2\Libs\AceComm-3.0\AceComm-3.0.lua:256:
      ...s\LibThreatClassic2\Libs\AceComm-3.0\AceComm-3.0.lua:246
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.5
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  DBMCore, v1.13.49
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.4.4
  GatherMate2, v1.45.5
  GroupCalendar, v
  Informant, v8.2.6374 (SwimmingSeadragon)
  MissingTradeSkillsList, v1.13.45
  Questie, v5.10.3
  Scrap, v8.3.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v1.4.1
  VuhDo, v3.113-classic
  VuhDoOptions, v3.113-classic
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=4f0)

**Comment by BreakBB** [comment]
Merging with #1974
