### ISSUE TITLE
Shaman Water Totem can't be turned in (Questie bug)

### ISSUE THREAD

**Issue by Thordin88** [AeroScripts/QuestieDev#204]
Found a bug while doing shaman water quest. By that I mean I wasn't able to turn in a part of it (think it was the Brinne part in southwestern Barrens). That was caused by a questie LUA error (nil value).

Edit:

error states: **Questie.lua:336**

**Comment by Dyaxler** [comment]
Which version are you running? This is critical because in the latest version line 336 is:

`local req = QuestieHashMap[questhash]['rq'];`

There are tons of quests that I've personally done where that field doesn't exist. This line has also been present in Questie since before I started improving it.

**Comment by Thordin88** [comment]
2.65 (latest one I guess)

**Comment by Thordin88** [comment]
Might have something to do with that NPC Brinne or Cartographer idk tbh

**Comment by Dyaxler** [comment]
Can you do me a favor? Will you edit your copy of Questie.lua and add these lines?

Old:
`function Questie:finishAndRecurse(questhash)
        local req = QuestieHashMap[questhash]['rq'];
	if req then
		Questie:finishAndRecurse(req);
		QuestieTrackedQuests[req] = nil;
		--DEFAULT_CHAT_FRAME:AddMessage("Requirement: "..req);
	end`

New:
`function Questie:finishAndRecurse(questhash)
	if QuestieHashMap[questhash]['rq'] == nil then
		return
	else
		local req = QuestieHashMap[questhash]['rq'];
		if req then
			Questie:finishAndRecurse(req);
			QuestieTrackedQuests[req] = nil;
			--DEFAULT_CHAT_FRAME:AddMessage("Requirement: "..req);
		end
	end`

**Comment by Thordin88** [comment]
ok, done it but as I said I had completed the quest allready :) I will report any issues if they appear.

**Comment by Dyaxler** [comment]
Wait... I forgot about something. :D You don't want to do that. Remove the word "return" like so and save it:

```
    if QuestieHashMap[questhash]['rq'] == nil then
    else
```

**Comment by Thordin88** [comment]
Allright..

**Comment by Dyaxler** [comment]
v2.66 - new version. Should be fixed.

**Comment by Dyaxler** [comment]
When you open your quest log, select a quest, is the quest level present? Should be in the main list but I'm talking about the large quest title at the top of the quest summary frame, not the quest log list.

[30] Some quest title

**Comment by Dyaxler** [comment]
Please test again with the new 2.67 release.
