### ISSUE TITLE
The Midsummer Fire Festival - Flickering Flames in the Eastern Kingdoms - German Translation

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#2048]
## Description

The hillsbrad flame shows up in westfall.

## Wowhead link

https://classic.wowhead.com/quest=9389/flickering-flames-in-the-eastern-kingdoms

## Screenshots

![https://i.imgur.com/PTlfkfa.png](https://i.imgur.com/PTlfkfa.png)

## Questie version

5.10.3

**Comment by Djfe** [comment]
![https://i.imgur.com/wENXkuR.jpg](https://i.imgur.com/wENXkuR.jpg)
Somehow the check mark for the tracker is displayed outside of the window (the quest name is wider and wow shortens the name with an ellipsis, questie still calculates the width with the full quest name)

**Comment by drejjmit** [comment]
It's not like that on English. Maybe @BreakBB can see it there's something wrong here. Can you hold shift and see what name the object has (like my screenshot)
![image](https://user-images.githubusercontent.com/15526476/85220274-6ba4dc00-b3aa-11ea-9003-2425a3ecb0f0.png)

**Comment by Djfe** [comment]
It's a common issue with quest objectives in other languages, breakbb will likely know what to do :)
![https://i.imgur.com/8rRYghX.jpg](https://i.imgur.com/8rRYghX.jpg)

**Comment by Djfe** [comment]
I gotta say, I love the redesign of the tracker :)
I just verified the fix with the current version of the alpha 6.0 branch.

![WoWScrnShot_062720_025945](https://user-images.githubusercontent.com/5685512/85911171-c4013100-b823-11ea-9842-a68f5e3bc7ac.jpg)
![WoWScrnShot_062720_030041](https://user-images.githubusercontent.com/5685512/85911174-c82d4e80-b823-11ea-90a2-9e98a8ff6a72.jpg)
