### ISSUE TITLE
Don't complete quest

### ISSUE THREAD

**Issue by BoneLord** [AeroScripts/QuestieDev#205]
Can't complete quest, 'nil' occurred.
Interface\addOns\!Questie\Questie.lua:336: attemps to index field '?' (a nil value)
I try complete two quests and error occured twice.
Smart Drinks and Harpy Lieutenants.

**Comment by Dyaxler** [comment]
There is a quick fix that will be in the next release... edit Questie.lua and make the following change.

Old:
```
function Questie:finishAndRecurse(questhash)
  local req = QuestieHashMap[questhash]['rq'];
    if req then
        Questie:finishAndRecurse(req);
        QuestieTrackedQuests[req] = nil;
        --DEFAULT_CHAT_FRAME:AddMessage("Requirement: "..req);
    end
```
New:
```
function Questie:finishAndRecurse(questhash)
    if QuestieHashMap[questhash]['rq'] == nil then
    else
        local req = QuestieHashMap[questhash]['rq'];
        if req then
            Questie:finishAndRecurse(req);
            QuestieTrackedQuests[req] = nil;
            --DEFAULT_CHAT_FRAME:AddMessage("Requirement: "..req);
        end
    end
```

**Comment by BoneLord** [comment]
Thanks for fast reply.
I change than fragment, but issue not disappeared.
Can I help you (some logs, debug info) ?

**Comment by psychedelique** [comment]
that didn't fix it for me either? any more fixes? i really don't want to keep relogging every time i have to hand in a quest.

**Comment by Dyaxler** [comment]
I've fixed this issue in the next release. I'm really really really sorry. I was going to release it today but I ran into a couple of issues that is holding me up. However, the fix isn't an easy one and it goes hand in hand with the new Quest Caching system. I'm currently running through my 3rd character from level 1-10 today... newest being a Horde Shaman to make sure it's not a "faction" specific issue... I should be done with testing tomorrow. Keep an eye out!

**Comment by BoneLord** [comment]
Dyaxler, thanks, you're doing a great job.

**Comment by Dyaxler** [comment]
New version - 2.66. Should be fixed.

**Comment by BoneLord** [comment]
Thanks, previous issue fixed. I can complete quest, but box with text error appears.It does not prevent complete quest, if I press "Okay" button. Should I open new issue or we continue here?

![wowscrnshot_040616_225126](https://cloud.githubusercontent.com/assets/1656752/14330679/5f6586a4-fc4a-11e5-923c-24130a44f81e.jpg)

**Comment by Dyaxler** [comment]
Something is going on with your database. You shouldn't be hitting the function at the referenced line number.

Please "untrack" all your quests in your QuestLog then type "/questie clearconfig"

**Comment by Dyaxler** [comment]
When you open your quest log, select a quest, is the quest level present? Should be in the main list but I'm talking about the large quest title at the top of the quest summary frame, not the quest log list.

[30] Some quest title

**Comment by BoneLord** [comment]
Error occurs even after delete ..\SavedVariables\!Questie.lua and /questie clearconfig.
I noticed that after an error has occurred, a new record of quest create in ..\SavedVariables\!Questie.lua. Moreover, quest with this id does not exists in addendum.lua.
After than quest completed. I may sent my file (!Questie.lua), if needed.

![wowscrnshot_040716_234903](https://cloud.githubusercontent.com/assets/1656752/14366417/5743ed7c-fd1b-11e5-823a-7014c29495f4.jpg)
The quest level present in list, but not quest detail.

**Comment by Dyaxler** [comment]
Yeah. So that's part of the problem right there. It's looking for the quest level in [%%] on the journal page side, not the quest list side. In my local copy of Questie I have it fixed.

If you look in Questie.lua, which is one of the main AddOn files look for: local questTitle = GetTitleText();

Add the last 4 lines like below under the first 2 lines.

```
	local questTitle = GetTitleText();
	local _, _, level, qName = string.find(questTitle, "%[(.+)%] (.+)")
	if qName == nil then
		qName = GetTitleText();
	else
		qName = qName
	end
```
This will catch either instances in case you don't play on either Nos or Kronos.

**Comment by BoneLord** [comment]
I found 2 string of code with same fragment:
`local _, _, level, qName = string.find(questTitle, "%[(.+)%] (.+)")`
This is 146 and 267 line number. I need add "if then else" in both?
I play in Nos, but 10 april is coming :(
It turns out this solution will not help me?

**Comment by Dyaxler** [comment]
Correct. One section is to handle quest completion when you click the complete button and the other section handles the "auto complete quest" feature that some addons use.

**Comment by BoneLord** [comment]
I add fragment of code in 2 place, but error still there.
It does not disturb me. Maybe it is due to my enviroment.

**Comment by x003** [comment]
![capture](https://cloud.githubusercontent.com/assets/12950645/14416154/e3ea9784-ff74-11e5-94b5-82cffdcc3d70.PNG)
Can't complete any quests as a tauren

**Comment by Dyaxler** [comment]
Which server are you guys playing on?

I played a Tauren Shaman up to level 20 without issues.

**Comment by psychedelique** [comment]
playtbc later this week.

**Comment by Schaka** [comment]
Deleted a comment because it was irrelevant to the thread. He asked which servers this Questie bug occurs on. It certainly doesn't happen on unreleased patch 2.4.3 servers.

**Comment by Dyaxler** [comment]
Please test again with the new 2.67 release.
