### ISSUE TITLE
Set Them Ablaze! - German Translation

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#2054]
## Description

3 of the 4 towers are shown at one spot, likely due to the german translation.

## Wowhead link

https://classic.wowhead.com/quest=3463/set-them-ablaze#comments

## Screenshots

![https://i.imgur.com/wP8jaY6.png](https://i.imgur.com/wP8jaY6.png)

## Questie version

5.10.3

**Comment by BreakBB** [comment]
@Djfe Are the other locations not shown at all or is this location simply showing 3 objectives in the tooltip?

**Comment by Djfe** [comment]
1 tower is shown at another location
2 towers are not shown at all on the map -> 3 towers are displayed at the position of one tower.

**Comment by anon1231823** [comment]
I seem to recall this quest having an issue with spanish as well -- this might not be limited to just German.
