### ISSUE TITLE
Hide Questie not remembered

### ISSUE THREAD

**Issue by Libero11** [AeroScripts/QuestieDev#2056]
### Steps to Reproduce:
Open map by pressing "M". Click the Hide Questie button to hide the nodes on the map. 
Then logout and log back in.

### Expercted Behaviour:
Nodes should be hidden and the button should say "Show Questie"

### Actual Behaviour:
The nodes are visible on the map and the button says "Show Questie" To hide them again you have to click Show Questie once so it becomes Hide and then click the button again.

### Version:
This was working fine in v5.8 and stopped working in v5.9. Its been broken ever since.
This is for WoW Classic

**Comment by Dyaxler** [comment]
This has been fixed in v6.0 Beta2 which is currently available on our Discord.

**Comment by BreakBB** [comment]
Fixed with d06ac73e7ffa89fc67fd87f85c0b72761e7fa9d7 and will be included in v6.0.

Thanks for reporting this @Libero11, look out for the next release 😃
