### ISSUE TITLE
Reduce Number of Coorinates in Corrections File

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2059]
## Description

From tests, when a mob has over 5 coordinates listed it's generally just as helpful if the coordinates are rounded vs. actual. So like instead of 77.1,13.5, just 77,14. Some mobs have literally hundreds of coordinates listed, and the number of coordinates may be hindering performance.

In one test, I was able to shave character count of the corrections file from 2200 to 700 characters, and coordinate pairs from 180 to 80 with no visible impact on mob locations in-game. When testing some of the longer coordinate sets, significant reductions can be made. 

![image](https://user-images.githubusercontent.com/55365231/85354336-f501fe80-b4cf-11ea-8e97-788b7ae5c3a2.png)

Good if we take a look at optimizing our corrections file, possibly even our database. Suggest only rounding and then de-duplicating coordinate sets that have more than 5 entries.

May be worth while to look into more aggressive rounding as the sets increase, so like maybe we round to the nearest whole coordinate for 6-20, and maybe we just look for edges and draw a polygon for sets larger than that. Will require additional exploration as many mob spawn points are clustered and not in contiguous areas.

**Comment by drejjmit** [comment]
You wouldn't get nice lines like this if you did that.
With the new compression (that compresses numbers very well) i don't think it matters that much. 

![image](https://user-images.githubusercontent.com/15526476/85534721-dc99fd00-b611-11ea-80ba-dc6f163cfa1c.png)

**Comment by BreakBB** [comment]
@Gogo1951 @drejjmit I think it really depends on the NPC/object. For a basic spawn I think it doesn't matter if it has two decimal points more or not. For the waypoints it can be quite nice to have such data, as Drejj already said.
