### ISSUE TITLE
tracker too close to arrow

### ISSUE THREAD

**Issue by robotninek** [AeroScripts/QuestieDev#206]
i don't know how to move this stuff, but i feel like they are too close to each other. I've been messing around with options and nothing has been solving the issue

http://prntscr.com/ao3jx8

**Comment by robotninek** [comment]
i reloaded my whole ui and it went to my face
http://prntscr.com/ao3sup

**Comment by Dyaxler** [comment]
Move the Arrow first by holding Shift+CTRL while clicking with your mouse and dragging. All have to be held down while moving.

Then you can do /questie cleartracker and that will relocate it to the center of your screen. Then drag it to the area you want.
