### ISSUE TITLE
Essence Mangoes quest should not be autoacccepted

### ISSUE THREAD

**Issue by scleal** [AeroScripts/QuestieDev#2060]
## Bug description

The quest for Essence Mangoes (https://classic.wowhead.com/quest=8196/essence-mangoes) should be in the disallowed quests for autoaccept.

## Screenshots

Don't have a screenshot

## Questie version

Version 5.10.3

**Comment by scleal** [comment]
Made a pull request for this. This burned me a little bit ago 😛

**Comment by drejjmit** [comment]
Sorry for that. disallowedQuests list were made before ZG patch and that's probably why it wasn't added before.
