### ISSUE TITLE
Bad Journey Logic on Tinkmaster Overspark (2923)

### ISSUE THREAD

**Issue by Cwis3man** [AeroScripts/QuestieDev#2067]
## Description
Bad Journey Logic on Tinkmaster Overspark (2923), quest shows available in journey but is un-obtainable, believe it was removed in a later patch.  

## Wowhead link
https://classic.wowhead.com/quest=2923/tinkmaster-overspark

## Questie version
5.10.3

**Comment by BreakBB** [comment]
@Cwis3man We need more information
