### ISSUE TITLE
Item value tool tips appear "Ghosted" when visiting a vendor

### ISSUE THREAD

**Issue by zeitgeist08** [AeroScripts/QuestieDev#207]
Using this addon causes my gold to be really dim. Happens for all items. You can still read the number, but for some reason it seems greyed out?

**Comment by Dyaxler** [comment]
I could swear that I've seen this a time or two. Are you using TinyTip?

Right now I can't seem to get this to repro. I'm wondering if I've fixed it while working on the next feature in my own local copy.

**Comment by zeitgeist08** [comment]
No, im not using TinyTip. Hmm. Not that big of a deal, just kind of annoying.

**Comment by Dyaxler** [comment]
Well if it does turn out to be something that Questie is doing, I want to find it and fix it. :) It's a big deal to me...

**Comment by zeitgeist08** [comment]
Oh i definitely want to see a solution too! I meant that as it is still usable, and a great addon!

**Comment by Dyaxler** [comment]
Huh... I repro'd it ONCE. Seemed to only appear when I sold a TON of stuff to a vendor and the Buyback queue filled up. I tried filling it up with cheap single items. Might be several pages worth of stuff before it borks out again. Might not even be Questie... I'll keep this open and in mind.

**Comment by Dyaxler** [comment]
This issue isn't happening on another server. Must be a Nostalrius specific issue.
