### ISSUE TITLE
Bad Journey Logic on Tran'rek (2864)

### ISSUE THREAD

**Issue by Cwis3man** [AeroScripts/QuestieDev#2072]
## Description
Bad Journey Logic on Tran'rek (2864), quest unavailable, still showing as available in Journey

## Wowhead link
https://classic.wowhead.com/quest=2864/tranrek

## Questie version
5.10.3

**Comment by BreakBB** [comment]
@Cwis3man Please provide the required information on your tickets to help us fixing the problems.

**Comment by drejjmit** [comment]
Check you paste these commands in chat and report the output
``/dump IsQuestFlaggedCompleted(2865)``
``/dump IsQuestFlaggedCompleted(2864)``

**Comment by Cwis3man** [comment]
2865 = True
2864 = False

**Comment by drejjmit** [comment]
So Tran'rek (2864) is a breadcrumb for Scarab Shells (2865)

**Comment by Cwis3man** [comment]
Correct, but Journey doesn't reflect that - I believe the map icons do, but the journey doesn't.

**Comment by Cwis3man** [comment]
The rest of the issues I entered should be updated now, but I believe they are all the same thing.

I went through and completed every quest in game if you'd like me to test anything.

**Comment by drejjmit** [comment]
2864 is exclusive to 2865

        [2864] = {
            [QuestieDB.questKeys.exclusiveTo] = {2865},
