### ISSUE TITLE
A lot of errors with the latest release.

### ISSUE THREAD

**Issue by psychedelique** [AeroScripts/QuestieDev#208]
![wowscrnshot_040616_090827](https://cloud.githubusercontent.com/assets/16769325/14307384/40d986b8-fbd7-11e5-8d9d-4c919131dd07.jpg)

The errors are displayed in the chat (they are probably displayed there because of the UI). The errors keep going, and I cannot write anything in chat. This also cuts my fps in half (you can see on the right side that I have 100 fps, but it will go as down as 60. I get 150-200 usually).

**Comment by Schaka** [comment]
Did you run /questie clearconfig as advised in the release notes?

**Comment by psychedelique** [comment]
Yes, tried that right now. It doesn't fix it.

**Comment by Dyaxler** [comment]
The error in QuestieNotes is because of the error in QuestieTracker. It's trying to validate against a new config table key ["tracked"]. Open your quest log and make sure everything is "untracked". Then run "/questie clearconfig"... run it a couple of times. Then re-add quests to your tracker.

**Comment by Dyaxler** [comment]
By the way... when trying to determine an issue this addon is awesome!
http://addons.us.to/addon/improvederrorframe

It will stack all the errors in a neat little box with a stack trace. Usually the very first error is the culprit. It helps in trying to track down an issue.

**Comment by psychedelique** [comment]
That fixed it! Thanks!

**Comment by Dyaxler** [comment]
I'll add that tip to the post. Thank you for confirming.
