### ISSUE TITLE
world map displaying quests level outside range I specified.

### ISSUE THREAD

**Issue by emanueol** [AeroScripts/QuestieDev#2089]
## Bug description
world map displaying quests level outside range I specified.
see screenshot. 

## Screenshots
![wow_questie bug](https://user-images.githubusercontent.com/8422412/85912807-3fb0ad00-b827-11ea-8022-05f4173cbf2e.jpg)

## Questie version
Questie-v5.10.3.zip

**Comment by BreakBB** [comment]
Hey @emanueol, thanks for another report 🙂 This issue has already been fixed in a0bac3ef2975cf4b489802dcf6a215317e26b942 and will be released with the upcoming (big) update v6.0.0. Merging this with #1963
