### ISSUE TITLE
Quest markers staying on map.

### ISSUE THREAD

**Issue by timo103** [AeroScripts/QuestieDev#209]
Even if you complete the quests the markers stay on the map, is this supposed to happen?

Quests completed before installing Questie also are stuck on the map.

**Comment by Dyaxler** [comment]
If you're upgrading to the new version you need to perform /questie clearconfig

This will create the new keys in your config that the new quest cache system uses.

**Comment by Dyaxler** [comment]
Please test again with the new 2.67 release. There was some zone map data fixes and a fix for EQL3 that seems to be causing some headaches.
