### ISSUE TITLE
triggerEnd only draws first zone.

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#2097]
## Bug description
In this example trigger it only draws the triggerEnd in zone 28 (Western Plaguelands) and ignores zone 139 (Eastern Plaguelands).

``{"The Blightcaller Uncovered",{[28]={{84.65,52.25},},[139]={{26.82,74.81},},}}``

[6185] = {"The Eastern Plagues"
https://classic.wowhead.com/quest=6185/the-eastern-plagues

## Screenshots
![image](https://user-images.githubusercontent.com/15526476/85945632-66fa9d80-b93f-11ea-8c80-17b4aedd736d.png)

## Questie version
v6.0 Beta v2

**Comment by BreakBB** [comment]
The problem with this was a change in the correction file removing the correct location in the Eastern Plaguelands.
