### ISSUE TITLE
Q is over play portrait

### ISSUE THREAD

**Issue by Dragoma** [AeroScripts/QuestieDev#210]
Is there a way to move it by hand or is it set in one place

**Comment by Dyaxler** [comment]
If you're referring to the QuestTracker or the QuestArrow you can hold down CTRL+Shift while click dragging the frames around. Otherwise /questie clearconfig will move the tracker to the center of the screen and clean up your database. Or you could do /questie cleartracker

**Comment by Dyaxler** [comment]
Did you figure out how to move them?

**Comment by Dragoma** [comment]
Yes I did thx
Den 15 apr 2016 18:18 skrev "Dyaxler" <notifications@github.com>:

**Comment by Dyaxler** [comment]
Thank you for the confirmation. :)
