### ISSUE TITLE
The Brokering of Peace

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#2114]
The Timbermaw Hold exalted quest The Brokering of Peace shows up as available on the map & minimap even though it follows The Root of All Evil.

https://classic.wowhead.com/quest=8481/the-root-of-all-evil
https://classic.wowhead.com/quest=8484/the-brokering-of-peace (Alliance version)
https://classic.wowhead.com/quest=8485/the-brokering-of-peace (Horde version)

![WoWScrnShot_070120_162359](https://user-images.githubusercontent.com/54936174/86255353-4ccaf480-bbb7-11ea-8988-9b5d5fce3c74.jpg)

Version 5.10.3

**Comment by drejjmit** [comment]
We should be able to squeeze this in for v6.0 release. Hard to test every quest in the game with help from the community. Thanks for all your reports.
