### ISSUE TITLE
shelf life indicator/durability

### ISSUE THREAD

**Issue by Waythor** [AeroScripts/QuestieDev#2117]
With the new File (6.0.0) the shelf life indicator/durability indicator is always show <100%.How can i hide this?

**Comment by BreakBB** [comment]
@Waythor Can you share a screenshot? I am not sure I understand you correctly

**Comment by Waythor** [comment]
Gesendet: Donnerstag, 02. Juli 2020 um 11:16 Uhr
Von: "Björn Böing" <notifications@github.com>
An: "AeroScripts/QuestieDev" <QuestieDev@noreply.github.com>
Cc: "Waythor" <waythor@gmx.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [AeroScripts/QuestieDev] shelf life indicator/durability (#2117)


 

@Waythor Can you share a screenshot? I am not sure I understand you correctly

**Comment by BreakBB** [comment]
@Waythor Even though you closed this could you share a screenshot what you mean or what you did to solve the problem?

Other users might help the information
