### ISSUE TITLE
A Thief's reward

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#2124]
## Description

Finishing a thief's reward isn't registered by questie, it still shows up on the map unless you /reload. The quest history (journal) doesn't list the quest (even after a /reload)

## Wowhead link

https://classic.wowhead.com/quest=9339/a-thiefs-reward (Alliance)

## Screenshots

![https://i.imgur.com/uDr01Ey.png](https://i.imgur.com/uDr01Ey.png)

## Questie version

6.0.0

**Comment by drejjmit** [comment]
Unfortunately it doesn't trigger on those type of quests that you just complete without picking up first.

**Comment by Djfe** [comment]
I found another one of these:
https://de.classic.wowhead.com/quest=5237/mission-erf%C3%BCllt#see-also

**Comment by Djfe** [comment]
Another one:
https://classic.wowhead.com/quest=1185/under-the-chitin-was

**Comment by drejjmit** [comment]
One stays. The other doesn't
![image](https://user-images.githubusercontent.com/15526476/88487026-26179800-cf82-11ea-99c2-d36059ef8d3d.png)
