### ISSUE TITLE
Questie-v6.0.0.zip - General > Quest Level Options > Level To is disabled!! Cant set max Level To

### ISSUE THREAD

**Issue by emanueol** [AeroScripts/QuestieDev#2125]
## Bug description
Questie-v6.0.0.zip - General > Quest Level Options > when enabled [x] Enable manual minimum level offset, we used to be able to set both:
< Sow bellow level
and
Level to

now in addon 6.0 "Level to" is disabled, so we no longer can set max level

## Questie version
Questie-v6.0.0.zip

**Comment by drejjmit** [comment]
Just set 'absolute level range' and you can set between what levels you want to show.

**Comment by emanueol** [comment]
> Just set 'absolute level range' and you can set between what levels you want to show.

Behaviour changed, that what im trying to report.
before i could use addon in 2 ways:
1. general > quest level options > [x] enable absolute level range  ----> and then set both "Level from" and "Level To".
or - the way i used was to specify both offsets:
2. general > quest level options > [x] Enable manual minimum level offset  --> and then would set both min and max ("<Show bellow level and upper offset.

So for example, i was lv 9, and would set:
general > quest level options > [x] Enable manual minimum level offset 
Show bellow level=1 and "upper level"=3

Questie then would only show quests of levels 8, 9, 10, 11 and 12.


PROBLEM NOW: is when we turn on [x] Enable manual minimum level offset, the 2nd slider to choose upper offdset now is disabled.. we no longer can set upper offset. Only downwards offset.

Hope this helps..

**Comment by uzify** [comment]
Guess we'll have to stick with v5.10.3 until this is sorted. You can downgrade on the Twitch app using the Versions tab.

Being able to limit both lower and higher offset on quest levels is really desirable, and should not have been removed.
Please reimplement this feature.

**Comment by Gogo1951** [comment]
Hey @uzify, Struggling to see an honest use case here. Do people really quest that way? "I only want to do level 40-50 quests, but I don't want to do 51 quests." Are you adjusting that every time you level?

I think general use case is "Show me all the quests I can get, and if I'm really pedantic, show me the gray quests too..."

Just trying to better understand the goal here. You really only want to see quests up to a certain specific level range? Keep in mind, the "available to you" flag is also applied.

Cheers!

**Comment by emanueol** [comment]
The goal here is to keep it simple, using lowerbound offset and an
upperbound offset, we will never need to tweak addon.
I never used the globals min/max tho (i prefer to offset version).

So would be nice to have offset lower/upper working again thanks.

Best Regards,
*Emanuel Oliveira*

**Comment by Gogo1951** [comment]
Bear with me, still not understanding the ask.

So you want to see all the quests that you can, at the high end? Yeah? Anything that's available to you?

But you only want to see quests that are above a certain min level?

So like, "I'm 55, so I want to see all quests a 55 can pick up, down to like level 40. I don't want to see "all the quests, only those above 40." Do I have the gist of what you're saying down right?

**Comment by Gogo1951** [comment]
PS: I think what you're asking for is already there... that's why I'm trying to understand it.

**Comment by uzify** [comment]
In v5.10.3, you had a show above level which you could alter to your choice. An example, you are level 33 and want only to see quests up to 35. You do a couple of quests and get to level 34. Then you'd naturally want to see quests up to level 36 instead of 35. 

In v5.10.3 you had this option. In v6.0.0 this slider is no longer usable unless you tick the absolute level range option. 
It is the dynamic "Show above level" feature we want back. I hope this clarifies the issue here.

**Comment by BreakBB** [comment]
@emanueol @uzify I will look into it to see if it is easy to reintroduce the behaviour you ask for. With v6.0.0 we changed quite a bit of the general logic for the level sliders and also the way quests are shown.

**Comment by Gogo1951** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.
