### ISSUE TITLE
Legplates of the Chromatic Defiler

### ISSUE THREAD

**Issue by Nadoran** [AeroScripts/QuestieDev#2126]
The spawn locations for Blood of Heroes as shown on the map are offset since this last update. 
![WoWScrnShot_070420_110742](https://user-images.githubusercontent.com/67833604/86515494-30ad9a00-bde7-11ea-91db-b8cc90c7f87a.jpg)

**Comment by drejjmit** [comment]
If you want to see all/more spawns you can set a lower cluster value (1 shows all). You can also go to ``/questie journey`` and search for 'Blood of Heroes' in 'Advanced Search' then 'Show on Map'
