### ISSUE TITLE
: ..\AddOns\Questie\Questie.lua line 145:    attempt to call method 'Migrate' (a nil value)

### ISSUE THREAD

**Issue by conan4281** [AeroScripts/QuestieDev#2127]
Since latest update, on every login- Reinstall comleted but still the problem persists 

Date: 2020-07-04 19:45:02
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Questie.lua line 145:
   attempt to call method 'Migrate' (a nil value)
Debug:
   Questie\Questie.lua:145:
      Questie\Questie.lua:141
   [C]: ?
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:613:
      ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:605
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnSkins, v4.40
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.5
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BestInSlotClassic, v2.5.2
  CEPGP, v
  DBMCore, v1.13.51
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  ElvUI, v1.24
  ElvUIRedtuzkClassic, v1.2.0
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  GroupCalendar, v
  HealBotData, v1.13.4.11
  HealBoten, v1.13.4.11
  HealBotOptions, v1.13.4.11
  NugRunning, v1.13.41
  Questie, v5.10.3
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=481)

**Comment by drejjmit** [comment]
Did you restart the client after the update?

**Comment by conan4281** [comment]
Yup... I've rolled back to a previous version and it now works fine...

Get BlueMail for Android<http://www.bluemail.me/r?b=15894>
On 4 Jul 2020, at 20:10, drejjmit <notifications@github.com<mailto:notifications@github.com>> wrote:

Did you restart the client after the update?

**Comment by conan4281** [comment]
Which of course the newest update still doesn't work for me....

**Comment by BreakBB** [comment]
@conan4281 Sorry to hear this and even more sorry to not come back to this earlier. Do you still have problems with the latest Questie version?
