### ISSUE TITLE
Aquementas

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#2132]
## Description

There should be a bag icon (object marker) at 70.8, 50.0 in Tanaris for the stone circle, where you can do part of the quest to get the totem. After that you can finish it in Un'Goro.

## Wowhead link

https://classic.wowhead.com/quest=4005/aquementas#comments

## Screenshots

![https://i.imgur.com/AcF7Ljk.jpg](https://i.imgur.com/AcF7Ljk.jpg)
m

## Questie version

6.0.0

**Comment by Djfe** [comment]
Alternative Coords: 70.4 49.9 (middle of the circle)
![https://i.imgur.com/QccxKWU.jpg](https://i.imgur.com/QccxKWU.jpg)

**Comment by BreakBB** [comment]
I thought I fixed that some month ago... Will do soon :grin:
