### ISSUE TITLE
"Donation of Wool" lvl 60 quest is shown?

### ISSUE THREAD

**Issue by runboy93** [AeroScripts/QuestieDev#2141]
Questie v6.0.0 show quest "Donation of Wool" as lvl 60 quest, on my characters that are around lvl 10-20.

I mean bug might be, that it's should not be lvl 60 quest, but much lower (no idea, on what level it start show up)

Or setting to hide these "Donation of x" quests?

**Comment by drejjmit** [comment]
It shows quests that you can complete. You can hide it by shift clicking it from the world map.

**Comment by runboy93** [comment]
But how I can complete lvl 60 quest on lvl 10-20, sounds weird to me :/

Not really lvl 60 quest, it's "adaptive quest" with different level requirement for all stages of quest.

**Comment by runboy93** [comment]
Nevermind, just checked on wiki, quest is indeed lvl 60, and starts on lvl 12 (for wool)
