### ISSUE TITLE
Tracker + Timed Quests

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2143]
## Bug description

Hey @Dyaxler, just adding a ticket so it doesn't get lost in Discord.

There's something funky going on with the tracker when you have a timed quest and then pick up another quest. Layout gets screwy, and headers disappear. It rights itself when you toggle a zone on or off, but every time you pick up a new quest it inserts the timer count down in a weird place and potentially removes random zone headers.

## Screenshots

Pick up a quest while on a timed quest...

![image](https://user-images.githubusercontent.com/55365231/86538517-11cd0780-bebc-11ea-8d25-8e4256cdc2e5.png)

Pick up another quest / turn a quest in... note how the Undercity Quest now shows up under Uldaman, and the UC section title is gone.

![image](https://user-images.githubusercontent.com/55365231/86538526-1db8c980-bebc-11ea-8fa0-033565c42084.png)

Rights itself when you toggle zone headers or reload the UI.

![image](https://user-images.githubusercontent.com/55365231/86538538-2ad5b880-bebc-11ea-8d1d-ed083053773a.png)

## Questie version

6.0

**Comment by Dyaxler** [comment]
Uhhh... that is an edge case I hadn't thought of. :D What in the world?!?! Code can do some really weird things sometimes... I uh, will look into that and see if I can't figure out what is going on.

Can you reset while NOT using sortByZone?

**Comment by Gogo1951** [comment]
When sorting by Proximity it will still insert the timer oddly.

![image](https://user-images.githubusercontent.com/55365231/86676200-fea36000-bfbf-11ea-91b1-4c3fa62411a8.png)

Happens when you toggle over to "Track by Proximity."

Original issue still happens in both Proximityand Zone-based sorts. If you pick up a quest while timer is running the display breaks.

**Comment by Gogo1951** [comment]
Not sure if related... "Timed" quests are still showing up as available when you pick them up.

![image](https://user-images.githubusercontent.com/55365231/86859109-8acc8a80-c087-11ea-9e4d-fae9ced3aeac.png)

**Comment by Dyaxler** [comment]
zone and proximity are both new sort types. I wanted to know if the timers still worked using one of the original sort methods.

**Comment by Dyaxler** [comment]
@Gogo1951 Fixed in https://github.com/AeroScripts/QuestieDev/commit/66a97c1244c38196d8830b25b51dcae123e27327
