### ISSUE TITLE
Can't disable seeing (nearby) quests from other players

### ISSUE THREAD

**Issue by aressler38** [AeroScripts/QuestieDev#2146]
The problem I'm having is that I keep seeing quests from other (nearby) players. It's confusing because it looks like I'm on the quest, but really, someone else is. I don't care about tracking every other player's quest progress. I would like to disable seeing this, but I don't see the option. I do see the option to prevent my progress from being shared, but that doesn't fix it. In the screenshot, you can see that someone is near me, and I am seeing their quest status, but I don't have that quest tracked at all. 

I would like to only see others' progress if they are in my immediate party (or maybe guild). At a minimum, I'd like to be able to disable seeing other people's progress. Is this possible? 

![image](https://user-images.githubusercontent.com/2053500/86554276-28567b80-bf1b-11ea-8061-28a3529d60d8.png)

**Comment by ixidion** [comment]
Agree, annoys me as well that I can't turn it off.

**Comment by ksulli10** [comment]
PLEASE add an option to turn this off.  Having the option is a good idea, but I really do not want to see it personally.

**Comment by aressler38** [comment]
Ok here's an idea. If you won't prevent me from seeing (nearby) players, then at least give me a quick option to invite them to my party so that I don't have to type out /invite (nearby player ...)

**Comment by ixidion** [comment]
> Ok here's an idea. If you won't prevent me from seeing (nearby) players, then at least give me a quick option to invite them to my party so that I don't have to type out /invite (nearby player ...)

This is related to the problem area, but a new feature. It does not contribute to solve the posters problem. I suggest to open a new feature request.

**Comment by BreakBB** [comment]
This should be fixed with v6.0.1 released yesterday.

**Comment by BreakBB** [comment]
And yes @aressler38 a feature request for such a shortcut sounds like a great idea :+1:

**Comment by ksulli10** [comment]
> This should be fixed with v6.0.1 released yesterday.

Thanks so much!  Love the addon, it is invaluable.

**Comment by Digital-Tectonics** [comment]
@BreakBB if this is in 6.0.1 can this be closed?

**Comment by BreakBB** [comment]
Yes, thanks. This is fixed an released :+1:

**Comment by aressler38** [comment]
This did get fixed, but I'm not sure if it got fixed in the way I expected. I unchecked the 'share with others' checkbox and I stopped seeing quests, but did it have any unexpected consequences like not showing quests to party members? Overall, this helped a lot. Thanks!
