### ISSUE TITLE
Use different color for "Quest complete!" text

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#2147]
Questie v6.0.0

I love the new tracker with the "sort by zone".
But please use a different color for the "Quest complete!" text (like blue) or let me chose one.
The color is exactly the same as the green quests, so when you got a full tracker, the completed quests are quite hard to spot with the "sort by zone" option.

**Comment by drejjmit** [comment]
Try "Min Complete Quests" in options. Then it says complete in the title instead. Maybe that is better for you.

**Comment by Gogo1951** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.
