### ISSUE TITLE
Error spamming chat when using Questie 3.0

### ISSUE THREAD

**Issue by chazragg** [AeroScripts/QuestieDev#215]
so i thought i would give questie 3.0 a go (i understand it is alpha nad will be buggy) but i though i would let you know it is constantly printing out in chat Interface\AddOns\!uesties\Questie.lua:471: attempt to index local 'QuestData' (a nil value) 
and causes extra boxes to appear on screen

**Comment by Dyaxler** [comment]
The 3.0 branch is a mess... you have to combine most of the directories together in order to get it to all work right. I wouldn't recommend it unless you know how to combine TOC's and dependencies.

**Comment by chazragg** [comment]
fair enough BTW love the work you are doing

**Comment by Dyaxler** [comment]
Thanks but it's a team effort. :) The original authors are still around...
