### ISSUE TITLE
All Along the Watchtowers - german localization issue

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#2151]
## Description

The tower locations are all in one spot in the german version.
The screenshot shows this. I already got tower one that's why it's not in the list.

## Wowhead link

https://classic.wowhead.com/quest=5097/all-along-the-watchtowers

## Screenshots

![https://i.imgur.com/XqE0dPu.png](https://i.imgur.com/XqE0dPu.png)

## Questie version

6.0.0

**Comment by drejjmit** [comment]
Could be related to #2054
