### ISSUE TITLE
Error Clear all points

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#2152]
## Bug description

```
1x [ADDON_ACTION_BLOCKED] AddOn 'Questie' hat versucht die geschützte Funktion 'Questie_TrackedQuests:ClearAllPoints()' aufzurufen.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `ClearAllPoints'
...ceQuestie\Modules\Tracker\QuestieTracker.lua:599: in function `Update'
...ceQuestie\Modules\Tracker\QuestieTracker.lua:1222: in function `Update'
...rfaceQuestie\Modules\QuestieEventHandler.lua:354: in function <...rfaceQuestie\Modules\QuestieEventHandler.lua:350>
[C]: ?
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
```
I actually don't know, when this happened and bugsack only shows a time, when an error happened yesterday but not for "today".

## Questie version

6.0.0

**Comment by Dyaxler** [comment]
@Djfe Have you run into this issue again in the latest release?

**Comment by Djfe** [comment]
I haven't. this might be fixed already. I don't know what caused it and I haven't noticed any issues. only bugsack reported that it happened.

**Comment by Dyaxler** [comment]
Just reopen this if it happens again. :)

**Comment by Djfe** [comment]
I just happened again, when I turned friendly with Hydraxian in MC.
```
2x [ADDON_ACTION_BLOCKED] AddOn 'Questie' hat versucht die geschützte Funktion 'Questie_TrackedQuests:ClearAllPoints()' aufzurufen.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `ClearAllPoints'
...ceQuestie\Modules\Tracker\QuestieTracker.lua:600: in function `Update'
...ceQuestie\Modules\Tracker\QuestieTracker.lua:1235: in function `Update'
...rfaceQuestie\Modules\QuestieEventHandler.lua:354: in function <...rfaceQuestie\Modules\QuestieEventHandler.lua:350>
[C]: ?
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
```

**Comment by Djfe** [comment]
I can't reopen (missing permissions)

**Comment by Dyaxler** [comment]
@Djfe Were you tracking this quest at the time you turned Friendly?

**Comment by Djfe** [comment]
I was doing/tracking https://classic.wowhead.com/quest=6822/the-molten-core at the time (reputation not relevant for quest completion) not https://classic.wowhead.com/quest=6823/agent-of-hydraxis where reputation is the quest goal.

**Comment by Djfe** [comment]
I'm fairly sure this is not quest related and happens on every reputation level increase for every faction?
the original one I reported wasn't Hydraxian, probably Zandalari but I'm not even sure at this point.

I could be wrong on this though.
I'll keep you updated ^^

**Comment by BreakBB** [comment]
@Djfe any news on this? Did it happen again and/or were you able to test it?

**Comment by Djfe** [comment]
I just turned Revered with Zandalar and no error. I'm on 6.0.4

**Comment by BreakBB** [comment]
@Djfe Great, thanks (once again) for your response and your reports! 👍
