### ISSUE TITLE
Update process error on Korean client

### ISSUE THREAD

**Issue by northmage** [AeroScripts/QuestieDev#2153]
## Questie version

3x Questie\Database\compiler.lua:278: bad argument #1 to 'pairs' (table expected, got string)
[C]: in function `pairs'
Questie\Database\compiler.lua:278: in function `?'
Questie\Database\compiler.lua:558: in function <Questie\Database\compiler.lua:543>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = "페랄라스의 모자케 야영지에 있는 장도르 스위프트스트라이더에게 완전한 설인 가죽을 가져가야 합니다."
(*temporary) = "table expected, got string"
 = <function> defined =[C]:-1

Questie Version : 6.0.0

After 6.0.0 update, When I start WoW, it updates its DB.

NPC, objects update have no error, but when it updates quests, Above error occures.

The korean of errors means "Bring the Perfect Yeti Hide to Jangdor Swiftstrider at Camp Mojache, Feralas."

**Comment by drejjmit** [comment]
Fixed in 6.0.2
