### ISSUE TITLE
attempt to call field 'QueryQuest'

### ISSUE THREAD

**Issue by jkw** [AeroScripts/QuestieDev#2154]
## Bug description

Lua error on login.

```lua
7x Questie\Modules\Quest\QuestieQuest.lua:1418: attempt to call field 'QueryQuest' (a nil value)
Questie\Modules\Quest\QuestieQuest.lua:1418: in function `filterFunc'
ElvUI\Modules\chat\Chat-Chat.lua:1192: in function `ChatFrame_MessageEventHandler'
ElvUI\Modules\chat\Chat-Chat.lua:1902: in function `DisplayChatHistory'
ElvUI\Modules\chat\Chat-Chat.lua:2367: in function <ElvUI\Modules\chat\Chat.lua:2320>
[C]: ?
ElvUI\Core\Core.lua:1222: in function `CallLoadFunc'
ElvUI\Core\Core.lua:1237: in function `CallLoadedModule'
ElvUI\Core\Core.lua:1263: in function `InitializeModules'
ElvUI\Core\Core.lua:1549: in function `Initialize'
ElvUI\init.lua:144: in function <ElvUI\init.lua:143>
[C]: ?
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function <FrameXML\UIParent.lua:352>
[C]: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:424: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:693: in function <FrameXML\UIParent.lua:658>
```

## Screenshots
n/a

## Questie version
v6.0.0

**Comment by AmosPolanski** [comment]
I have been been seeing the same or similar error message popping up the last couple of days.

Date: 2020-07-08 07:16:38
ID: 1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua line 1418:
   attempt to call field 'QueryQuest' (a nil value)
Debug:
   ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1418: filterFunc()
   ElvUI\Modules\chat\Chat.lua:1192: ChatFrame_MessageEventHandler()
   ElvUI\Modules\chat\Chat.lua:1902: DisplayChatHistory()
   ElvUI\Modules\chat\Chat.lua:2367:
      ElvUI\Modules\chat\Chat.lua:2320
   [C]: ?
   ElvUI\Core\Core.lua:1222: CallLoadFunc()
   ElvUI\Core\Core.lua:1237: CallLoadedModule()
   ElvUI\Core\Core.lua:1263: InitializeModules()
   ElvUI\Core\Core.lua:1549: Initialize()
   ElvUI\init.lua:144:
      ElvUI\init.lua:143
   [C]: ?
   ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:70:
      ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65
   ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:527: EnableAddon()
   ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:620:
      ...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353:
      ..\FrameXML\UIParent.lua:352
   [C]: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:424: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:693:
      ..\FrameXML\UIParent.lua:658
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ArkInventory, v30929
  ArkInventoryRules, v20000
  ArkInventorySearch, v20000
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CallbackHandler10, v
  CharacterStatsClassic, v3.5.4
  ClassicLootAssistant, v
  DBMCore, v1.13.52
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  ElvUI, v1.24
  ElvUIExtraDataTextsClassic, v1.0.2
  ElvUINutsAndBoltsClassic, v1.02
  ExtendedCharacterStats, v2.4.4
  FarmHud, v8.3-6-classic-release
  FishingBuddy, v0.7.3 Beta 5
  GatherMate2, v1.45.5
  HandyNotes, vv1.5.10
  ItemRack, v
  LeatrixMaps, v1.13.71
  LibHealComm40, v
  LibSharedMedia30, v3.0-113
  LibStub, v
  NovaWorldBuffs, v1.70
  Pawn, v2.3.29
  Prat30Libraries, v
  Questie, v6.0.0
  SigmaLoot, v1.05
  SigmaProfessionFilter, v
  SigmaProfessionFilterAlchemy, v
  SigmaProfessionFilterBeastTraining, v
  SigmaProfessionFilterCooking, v
  SigmaProfessionFilterEnchanting, v
  SigmaProfessionFilterFirstAid, v
  SigmaProfessionFilterMining, v
  SigmaProfessionFilterPoisons, v
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TheoryCraftClassic, v1.17.2020
  TomTom, vv11304-1.1.2
  VuhDo, v3.113-classic
  VuhDoOptions, v3.113-classic
  WeakAuras, v2.17.9
  WIM, v3.8.12
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=724)

**Comment by AeroScripts** [comment]
Should be fixed in 6.0.1, its good as of b15eb4f27ec290c025557b6af5ef5c9239aedf76

**Comment by rlavoie012** [comment]
I overlaid the fix, it works. Thank you!

**Comment by AmosPolanski** [comment]
Thanks!
