### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RxMonster** [AeroScripts/QuestieDev#2156]
## Questie version

Questie is updated. even tried uninstalling and reinstalling. When i open my mini map and hover over any arrow i get this messgae. and then it won't show anything while my mouse is over a !

Date: 2020-07-08 20:50:06
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\Libs\QuestieLib.lua line 179:
   attempt to index field 'collapsedQuests' (a nil value)
Debug:
   ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144:
      ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:142
   [C]: ?
   Questie\Modules\Libs\QuestieLib.lua:179:
      Questie\Modules\Libs\QuestieLib.lua:171
   (tail call): ?
   ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:392: GetAvailableOrCompleteTooltip()
   ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:596: handleMapIcon()
   ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:648:
      ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:509
Locals:
private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:44
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:85
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:105
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:81
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:114
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:75
 NewError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:48
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:92
}
orig_errorhandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:597

**Comment by jlonardi** [comment]
Same error happening when targeting an enemy. The tooltip does not display the quest progress and getting a similar error.

```
Date: 2020-07-09 16:47:05
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\Libs\QuestieLib.lua line 179:
   attempt to index field 'collapsedQuests' (a nil value)
Debug:
   [C]: ?
   Questie\Modules\Libs\QuestieLib.lua:179:
      Questie\Modules\Libs\QuestieLib.lua:171
   (tail call): ?
   Questie\Modules\QuestieTooltips.lua:87: GetTooltip()
   Questie\Modules\QuestieTooltips.lua:274:
      Questie\Modules\QuestieTooltips.lua:259
   [C]: ?
Locals:

```

**Comment by Dyaxler** [comment]
@RxMonster Fixed. Please update to 6.0.2 and then close your issue once you confirm.
