### ISSUE TITLE
Questie crashes when hovering over "!" on map

### ISSUE THREAD

**Issue by Surlygit** [AeroScripts/QuestieDev#2160]
## Swatter dump:
Date: 2020-07-09 10:37:57
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\Libs\QuestieLib.lua line 179:
   attempt to index field 'collapsedQuests' (a nil value)
Debug:
   [C]: ?
   Questie\Modules\Libs\QuestieLib.lua:179:
      Questie\Modules\Libs\QuestieLib.lua:171
   (tail call): ?
   ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:392: GetAvailableOrCompleteTooltip()
   ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:596: handleMapIcon()
   ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:648:
      ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:509
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AskMrRobotClassic, v2
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.6
  Bartender4, v4.9.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  Clique, vv1.0.3-classic
  DBMCore, v1.13.52
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FasterLooting, v1.1.2
  GatherMate2, v1.45.5
  GTFO, v4.55
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixMaps, v1.13.71
  Mapster, v1.8.5
  NeatPlates, v1.13.4.28
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v2.0
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  NovaWorldBuffs, v1.70
  NugComboBar, v1.13.7
  Quartz, v3.5-classic-5
  Questie, v6.0.1
  Recount, vv1.13.5a
  SexyMap, vv5-classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.1.0
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TellMeWhen, v8.7.5
  ThreatClassic2, v2.22
  TomTom, vv11304-1.1.2
  WhatsTraining, v1.8.7
  WIM, v3.8.12
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=6df)

**Comment by Dyaxler** [comment]
https://github.com/AeroScripts/QuestieDev/commit/5ac9a86c1841a05570742bb34694a99bf9675e23

Please update to 6.0.2
