### ISSUE TITLE
Dawn's Gambit

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#2161]
From Discord:

I have a new bug that started with version 6.0.0, it's a chain quest called Dawn's Gambit, level 60, from EPL. Every time I log in I get the error: "Questie: [ERROR] Missing event data for Objective: Place Dawn's Gambit id: nil
https://classic.wowhead.com/quest=4771/dawns-gambit

**Comment by fireboy92k** [comment]
This issue also exists in 6.0.2.  Looks like it's been fixed above, but wanted to note just in case.  :)

**Comment by Djfe** [comment]
I can confirm this

**Comment by Djfe** [comment]
![WoWScrnShot_072420_032700](https://user-images.githubusercontent.com/5685512/88353670-b70e2980-cd5e-11ea-91c8-9c73529a150e.jpg)
