### ISSUE TITLE
Replacement for UpdateHiddenNotes functionality

### ISSUE THREAD

**Issue by ceci-woodward** [AeroScripts/QuestieDev#2163]
### Question

Hey there! 👋 

In the process of updating `ButterQuestTracker` to support Questie v6 I noticed that `UpdateHiddenNotes` was renamed to `_UnhideManualIcons` and `_HideManualIcons` along with being made private / internal.

I'm wondering if this functionality was replaced with anything that's publically available, or if there's something similar I can utilize.

### My Scenario

Effectively I was calling it when `ButterQuestTracker` was initialized (with a bit of delay to account for Questie loading) and when a user untracked / tracked a quest.

This would result in the icons on the map either appearing or disappearing depending on the intent since I was updating the `HideIcons` variable as well.

Any help would be appreciated!

**Comment by Gogo1951** [comment]
Hey @ceci-woodward,

Sorry for delay on this. Can you confirm this is still an issue and let me know what the impact is for you? Trying to get a sense for how to prioritize this one. It's only impacting people who use ButterQuestTracker?

**Comment by ceci-woodward** [comment]
Hey @Gogo1951!

I don't actively work on ButterQuestTracker anymore, I mostly just resolve critical bugs when they come up.
However, I'll try to give my best run down of the issue based on what I remember!

### "Workaround"

I effectively disabled the functionality in ButterQuestTracker w/ Questie v6+ so people could still utilize both addons together.

[See code](https://github.com/butter-cookie-kitkat/ButterQuestTracker/blob/85424ff70f38e7fec98bff84b0bae80a9be5c93d/LibQuestHelpers/LibQuestHelpers.lua#L63-L68)

### Who does this effect?

The removal of the API would have impacted anyone trying to externally hide / refresh the Questie Map Icons.
However, last I knew ButterQuestTracker was the only addon with this sort of integration.

### Impact on ButterQuestTracker

The impact of this functionality being removed is that unwatching a quest from ButterQuestTrackers "watch" list no longer causes Questie to hide the relevant icons from the map.

**Comment by Gogo1951** [comment]
Hey @ceci-woodward ,

Thanks for the info! We've got a lot of changes in store for BC, let's chat then if this comes up again.

Feel free to re-open once we both have versions for BC and we can see if we still need to make a fix.

Cheers!
