### ISSUE TITLE
Battle Ground Pop Up Requests Questie be disabled

### ISSUE THREAD

**Issue by Digital-Tectonics** [AeroScripts/QuestieDev#2165]
![BG Capture](https://user-images.githubusercontent.com/48304461/87216228-b6f83d80-c30b-11ea-93ae-80ca54322e67.JPG)
## Bug description
WoW Client states that when a Battle Ground (BG) pops Questie is doing something illegal with the UI and is required to be turned off before accepting the BG popup.

## Questie version
6.0.2

**Comment by Dyaxler** [comment]
This is NOT a Questie bug... Questie just happens to be the last addon to touch that API. We suspect that Blizzard has once again broken something or has reintroduced an old bug and is tainting their own execution path.

I currently have the same issue. If I disable Questie it'll say "Prat has been blocked...". If I disable Prat it'll say some other addon is blocked.

Just use the Battleground icon on the Minimap --> Right Click and enter Battleground.

**Comment by Digital-Tectonics** [comment]
So after a fair amount of further testing @Dyaxler is correct.
