### ISSUE TITLE
Feature Request: Add xp award to tracker quest title

### ISSUE THREAD

**Issue by tgilman** [AeroScripts/QuestieDev#2168]
Would love to be able to see the xp award for each quest next to the quest title in the tracker window.  Currently the only way to see this information is to hold shift while hovering over the start/complete quest or quest objective icons on the map.

**Comment by Dyaxler** [comment]
This is on my "ToDo" list for the v6.1 milestone :)

**Comment by Digital-Tectonics** [comment]
@Dyaxler I would make it a toggle

**Comment by Dyaxler** [comment]
I'm hesitant to embed this info into the actual Quest Title along with toggleable options like QuestID's and QuestLevel's. This would make the tracker even wider. I think I would like to see the info but only when I want to see it. I might make it call it's own tooltip with the Shift modifier - the same one that gets called when hovering over the Minimap or Worldmap icons. This would allow one to quickly check the quest without opening the Quest Log and wouldn't require any additional code or testing.

**Comment by Gogo1951** [comment]
May be addressed as part of #2498 ; closing as a stand-alone issue.
