### ISSUE TITLE
Questie throwing up error

### ISSUE THREAD

**Issue by zensik** [AeroScripts/QuestieDev#217]
Error is as follows:
Interface\addOns\!Questie\Modules\QuestieTracker.lua:845: attempt to call global 'EQL3_IsQuestWatched' (a nil value)

Continues to pop up after clicking Okay. Error pops up as soon as I load in.

EDIT: also another error. If you click Okay out of the previous error and quickly try to track a quest this will pop up:
Interface\FrameXML\UIPanelTemplates.lua:236: attempt to index local 'Frame' (a nil value)

**Comment by Dyaxler** [comment]
Are you running EQL3 aka Enhanced Quest Log...

**Comment by zensik** [comment]
No, I don't have any other addons. Should I be using it? Never had this issue before.

**Comment by Dyaxler** [comment]
Nope. I'll need to reload my vanilla dev env and unload EQL3 and take a look. I might have missed a couple of NIL checks during the re-write as I was primarily using EQL3... sigh. Sorry about that.

**Comment by zensik** [comment]
No worrys! Best of luck :)

**Comment by jdhusker7** [comment]
I too am having the same issue zensik is having. I also don't have any other adddons. Additionally, my minimap is full of "!" from quests I have already completed. It looks like it's not detecting what I have or haven't already done. Not sure if that and the errors I am getting are related

**Comment by Dyaxler** [comment]
Questie 3.0 has been patched. Hotfix applied. Please test again. It's all working in my testdev env without EQL3. Sorry about that guys!

**Comment by Dyaxler** [comment]
@jdhusker7 - In regards to your minimap being full of "!"... please try the hotfix. If you still see a bunch of "!" all over the place then chances are you upgraded from an earlier version that wasn't handling quest turn-ins correctly.

Shortly after I began managing this project I discovered a bug where completed quests weren't being recorded correctly. This is why I improved the whole quest management system and built in redundant checks all over the place. I also created helper switches to force a clean up. If there was an entry in your database marked with a "%hash% = 0;" and the corresponding quest wasn't in your log, then the entry was deleted. A zero indicates that you are on that quest. Additionally, tracker data would have also been removed. This is so your database doesn't get inflated with unnecessary entries which could potentially cause issues the higher you level. I also made it easier to manually complete a quest. Just simply open your Worldmap and hold down your Shift key while clicking on a quest icon. Should only take you a few minutes to go through the zones you remember doing and re add those entries as complete. :)

**Comment by jonteyy** [comment]
Getting the same error, where do i download the fixed version so i can try it?   Also am i suppose to only dowload the questie 3.0 or do i need the master thing that it says in the install guide, the files arent even the same as on the pics

**Comment by jonteyy** [comment]
Works for me now, thanks

**Comment by Dyaxler** [comment]
Yeah, under the Releases tab just download the ZIP file. It contains the HOTFIX. I just updated the zip with the new files rather than spinning up a version 3.1... you should never download a zip from the master branch since it contains files that aren't necessary for the addon to run properly.

**Comment by Dyaxler** [comment]
A new hot fix has been applied. Please give it a try and report back. :)

https://github.com/AeroScripts/QuestieDev/releases/latest
