### ISSUE TITLE
QuestieDB misc quest issues

### ISSUE THREAD

**Issue by TexFromHell** [AeroScripts/QuestieDev#2173]

**Comment by drejjmit** [comment]
We need more information.

**Comment by TexFromHell** [comment]
Right so after completing almost every quest in classic, I have found the following issues:

- "Report to Capitain Stoutfist" cannot be picked up if you finish "The Algaz Gauntlet" beforehand, hence it should be marked as completed or unobtainable.
- "Digging Through the Dirt" is still showing up on questie even if you complete it (as I remember doing it).

Hope this helps :)
