### ISSUE TITLE
Necklace Recovery, Take 2

### ISSUE THREAD

**Issue by Digital-Tectonics** [AeroScripts/QuestieDev#2180]
## Description
The Quest; "Necklace Recovery, Take 2" has two (2) locations shown, but only the one on the location of the Uldaman instance.
The second marker

## Wowhead link
https://classic.wowhead.com/quest=2284/necklace-recovery-take-2#comments

## Screenshot
![map](https://user-images.githubusercontent.com/48304461/87596464-3005e500-c6be-11ea-9acf-b3af784a95e6.JPG)

## Questie version
6.0.2

**Comment by drejjmit** [comment]
Entrance and backdoor shows for you? That's how it should be?

**Comment by Digital-Tectonics** [comment]
@drejjmit Tried on a different character and yes your screenshot is right. Not use why my warrior had it different.
