### ISSUE TITLE
Autotracking

### ISSUE THREAD

**Issue by joaosantana** [AeroScripts/QuestieDev#219]
Hi. There's a way to Questie automatically track picked quests?

**Comment by Dyaxler** [comment]
No because EQL3 already does this as well as many other quest log mods.

**Comment by joaosantana** [comment]
Sorry for ask. I'm new to vanilla add-ons, and Questie is the only questlog I know. I have some issues using Questie, but I'll search better before make any other question. Thanks.

Enviado pelo meu Windows Phone
________________________________
De: Dyaxler<mailto:notifications@github.com>
Enviada em: ‎24/‎04/‎2016 12:46
Para: AeroScripts/QuestieDev<mailto:QuestieDev@noreply.github.com>
Cc: João Santana<mailto:joaosantana@outlook.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [AeroScripts/QuestieDev] Autotracking (#219)

No because EQL3 already does this as well as many other quest log mods.

---

**Comment by Dyaxler** [comment]
Totally OK. Please ask. :)
