### ISSUE TITLE
Incorrect min level The Captain's Chest

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#2192]
The Captain's Chest has a minimum level requirement of 35, not 40.

https://classic.wowhead.com/quest=614/the-captains-chest

![WoWScrnShot_072020_160519](https://user-images.githubusercontent.com/54936174/87947333-76cf5280-caa3-11ea-9fdc-4718759859d9.jpg)

Version 6.0.2

**Comment by drejjmit** [comment]
Fixed in #2178
