### ISSUE TITLE
Minimap Mixup Un'Goro/Searing Gorge

### ISSUE THREAD

**Issue by polaarbear** [AeroScripts/QuestieDev#2193]
## Bug description
The minimaps for Un'Goro Crater and Searing Gorge have been frequently mixing themselves up recently in my playthroughs.  You can see in the screenshot that I am seeing quests for Searing Gorge when I am clearly in Un'Goro.  This problem doesn't exist in the popup map, only in the corner minimap. The reverse problem is also true, while I was in Searing Gorge I was seeing quest markers and objectives for Un'Goro.

## Screenshots
![Mixup](https://user-images.githubusercontent.com/9713177/87979398-9ceef580-ca97-11ea-9545-287f171f26e8.png)

## Questie version
6.0.2

**Comment by drejjmit** [comment]
Are you sure you're on 6.0.2? This was a problem in 6.0.1 and has since been thought to be fixed. I'm at the exact same spot as you in Un'Goro and can't see any Searing Gorge quests with 6.0.2.

**Comment by polaarbear** [comment]
I believe I must have gotten a half-install somehow when I updated.  The version was showing 6.0.2 but was also saying outdated.  I just completely deleted the folder and re-installed and the issue has disappeared, this can be marked as resolved.

**Comment by drejjmit** [comment]
Great to hear 👍
You are able to check loaded version by hovering over the minimap icon.
Report back if you encounter any problems.
