### ISSUE TITLE
QuestGuru support

### ISSUE THREAD

**Issue by Pegoth** [AeroScripts/QuestieDev#2194]
I'm using quest guru and was wondering if I could open QuestGuru window instead of blizzard frame.
So I looked into the code and found that Modules/Tracker/QuestieTrackerUtils.lua:17 (classic) has checks for addons and I added QuestGuru to check if it would work and so far it does, so decided to create an issue.

Code:
```lua
-- Priority order first check if addon exist otherwise default to original
local questFrame = QuestGuru or QuestLogExFrame or ClassicQuestLog or QuestLogFrame;
```

**Comment by drejjmit** [comment]
Hello!

Problem with QuestGuru is that it makes a new Quest log frame and is incompatible with all addons that make changes to the quest log. By doing this, quest linking introduced in Questie 6.0 doesn't work.
I would recommend you changing to:

[Leatrix Plus with "Enhance quest log"](https://www.curseforge.com/wow/addons/leatrix-plus-classic)

![image](https://user-images.githubusercontent.com/15526476/87985364-c2055780-cadb-11ea-9817-abfd4db44a78.png)
or

[Wide Quest Log](https://www.curseforge.com/wow/addons/widequestlog) with [Wide Quest Log Levels](https://www.curseforge.com/wow/addons/widequestloglevels)

![image](https://user-images.githubusercontent.com/15526476/87985505-042e9900-cadc-11ea-8085-47ede9487efb.png)

If you still want it added you can always do a 'Pull request' with the changes you've made.

**Comment by Pegoth** [comment]
Thanks, didn't even know that leatrix had that feature, I'll switch to that as I already have that installed!
