### ISSUE TITLE
Available quests need to take into account the player's class

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#22]
Currently, all class-specific quests are shown as available if the player is in the right level range.

**Comment by ayrb13** [comment]
Is there any way to get data of quests which are finished or not finished?

**Comment by Schaka** [comment]
QuestieSeenQuests (SavedVariable) contains that information. But there is no other way to get that information other than if you've actually seen the quest ingame. No server query or anything.

**Comment by ayrb13** [comment]
If i didn't install this addon at first and i finished half of quests in a zone, then I install this addon, Is there any way for Questie to get data of finished quests before it is installed.

**Comment by Schaka** [comment]
Like I said, no. The only way to get finished quest data is by having the addon run so it can record what you finish.

**Comment by Schaka** [comment]
Fixed as of https://github.com/AeroScripts/QuestieDev/commit/b5f4c33079489a124e9e79f8467b435308d4c975
