### ISSUE TITLE
Cant move the quest tracker/arrow

### ISSUE THREAD

**Issue by zensik** [AeroScripts/QuestieDev#220]
Hey its me again, I've been trying to fix the issue on my on but haven't had any luck. For some reason I am unable to move the quest tracker or the quest arrow. /questie cleartracker or /quest NUKE do not fix it. The Tracker and arrow just stay right in the middle of my screen. :/

**Comment by Dyaxler** [comment]
Hold down CTRL + Shift while you drag the frames with your mouse.

**Comment by zensik** [comment]
Wow haha I feel stupid. thank you! XD

**Comment by Dyaxler** [comment]
LOL... no problem. Blame me for not updating the main readme on the site. It's all in the release notes though but they are all pretty detailed and most don't read through it all.

https://github.com/AeroScripts/QuestieDev/releases/tag/v2.5
