### ISSUE TITLE
Dungeon Tool Tips 

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2205]
## Bug description

Quest List on the dungeon tool tip layout is off. Extra spacing between some quests.

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/88472395-e98f6200-ced7-11ea-9b79-8ddfa2ea48b8.png)

## Questie version

6.0.2

**Comment by drejjmit** [comment]
We already played around with this. Looks awful in other cases if you add spacing.
