### ISSUE TITLE
Quest issue with Lost Deathstalkers

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2206]
## Bug description

Says I can pick up quest but quest isn't there. Tested on 26 Troll Hunter.

* Lost Deathstalkers - Quest - World of Warcraft || https://classic.wowhead.com/quest=428/lost-deathstalkers

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/88472409-0b88e480-ced8-11ea-829b-72bffac3ac08.png)

## Questie version

6.0.2

**Comment by Nerillida** [comment]
That quest is a breadcrumb for [Wild Hearts](https://classic.wowhead.com/quest=429/wild-hearts. Probably you have done this.

**Comment by drejjmit** [comment]
We have this already: ```        [428] = {
            [questKeys.exclusiveTo] = {429}, 
        },```
Try ``/reload`` on that character and see if it's still there.

**Comment by drejjmit** [comment]
I spoke to TheCrux about this bug. Exclusive to quests aren't being removed.

**Comment by drejjmit** [comment]
Should be fixed with https://github.com/AeroScripts/QuestieDev/commit/ee93b7dca09de68c8549056caf607aaebb2f1953
