### ISSUE TITLE
A Sample of Slime...

### ISSUE THREAD

**Issue by Digital-Tectonics** [AeroScripts/QuestieDev#2212]
## Description
There is a set of testing equipment that needs to be used. Can you added a gear to 47.77, 73.2 (Undercity)

## Questie version
6.0.2

**Comment by drejjmit** [comment]
WHen you pick up "A Sample of Slime..." it opens up the repeatable quest "Testing for Corruption - Felwood" that's picked up at object "Testing Equipment" in Undecrity 47.85,73.48. Can't find any problems in the database. It shows up as a repeatable quest at 47.85,73.48 and not as an object to pick up/be looted.

**Comment by drejjmit** [comment]
I added "Testing Equipment" as source for "Corrupted Felwood Sample"
