### ISSUE TITLE
Hot Fiery Death missing in the Journey

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#2219]
Likely has something to do with its zoneOrSort tag in the database being -121.

https://classic.wowhead.com/quest=5103/hot-fiery-death

Version 6.0.2

**Comment by drejjmit** [comment]
We don't have a Blacksmithing or Profession category yet. There's a feature request for it here: #2073

**Comment by Cerby3BR** [comment]
That's not the issue, the issue is that it's not even showing up in the "Unobtainable Quests" lists with the other profession quests.

**Comment by drejjmit** [comment]
"Zone" is "Blacksmithing". That quest is done in "Winterspring" but it's not in the "Winterspring" category by Blizzard. 
All these are missing at the moment: https://classic.wowhead.com/profession-quests#0+12
All "zones" under 0 (-121 in this case) are categories (events, war effort, blacksmithing etc) so the data is correct.

**Comment by Cerby3BR** [comment]
In that case all the other profession quests are in the wrong "zone", as they do show up in their respective geographic zones' Unobtainable Quests lists.

**Comment by BreakBB** [comment]
@Cerby3BR Yeah some has been "corrected" as I remember correctly to show up there, but a lot are still missing. I hope to really have some time soon ™️  to add a hidden, class and profession list to the Journey.

**Comment by Gogo1951** [comment]
Will be fixed with #2043 - closing as dupe.
