### ISSUE TITLE
v3.0 No tracking

### ISSUE THREAD

**Issue by Pandikey** [AeroScripts/QuestieDev#222]
Hello, 

Thanks for your work !

How can I get the tracking of one quest ? I do not see the arrow to show me the direction. 
Also when i press shift + click to follow a quest, nothing happen.

I have try without any addon, only questie 3.0 but it's same.
Any idea ?

Thanks for all.

**Comment by Dyaxler** [comment]
try /questie clearconfig while in game...

**Comment by Pandikey** [comment]
Hello Dyaxler,

Thanks for your answer.
It reload my UI but nothing change. Still do not see the arrow, and impossible to track a quest with shift + click.

I use the french client 1.12.1 on the server nostalgeek.

**Comment by Dyaxler** [comment]
In your quest log... are the quests all in French? Questie only understands English. :( If the server is broadcasting all the quests in French... there is your problem.

**Comment by Pandikey** [comment]
Yes my quests is in french.

Fuck that's bad :( No way to fix that's later ? If need any help ask me.

**Comment by Pandikey** [comment]
Also, do you know an addon who will help me for the quest and who work on a french client ?

Thanks you !

**Comment by Dyaxler** [comment]
ShaguQuest is the only Vanilla quest helper aside from Questie that works outside an English only server. Unfortunately, it only works on English and German servers... I'm not aware of any quest helper apps for French servers.
