### ISSUE TITLE
Goblin Town Repeatable Quests

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#2220]
The four goblin town repeatable turn-in quests are in the Repeatable section of their respective zones' journeys, despite being unavailable starting at Neutral 0/3000. Could the cause be that having a 0 in the requiredMaxRep value is somehow not handled correctly?

https://classic.wowhead.com/quest=9259/traitor-to-the-bloodsail
https://classic.wowhead.com/quest=9266/making-amends
https://classic.wowhead.com/quest=9267/mending-old-wounds
https://classic.wowhead.com/quest=9268/war-at-sea

Version 6.0.2

**Comment by BreakBB** [comment]
@Cerby3BR Are those still showing up for you in v6.0.4?

**Comment by drejjmit** [comment]
I don't think 'Quest by zone'/'Journey' respects reputation requirements. Doesn't show up on the map, only in 'Quest by zone' as a repeatable.

**Comment by Cerby3BR** [comment]
@BreakBB yes they still do.

@drejjmit no they shouldn't. The Thorium Brotherhood turn in quests, for instance, were correctly put into Unobtainable Quests after I passed their respective rep threshholds.

**Comment by BreakBB** [comment]
Found the issue. Another one linked to `unpack` when the first value returned is `nil`. Stupid Lua >_> Fix will be included in the next release.
