### ISSUE TITLE
Auto complete for AQ handins not working?

### ISSUE THREAD

**Issue by laurencei** [AeroScripts/QuestieDev#2229]
## Bug description
- The AQ hand in quests do not auto accept/auto complete.
- I have "Enable AQ War Effort Quest Icons" on

## Questie version
6.0.3 (updated just now on Twitch)

**Comment by drejjmit** [comment]
These are on the disallowedNPCs list. You can remove them from \Questie\Modules\Auto\DisallowedIDs.lua and it should auto turn in for you.

**Comment by laurencei** [comment]
Ok, yes, that fixed it.

That seems strange - why would they be "hard coded" disabled?

**Comment by BreakBB** [comment]
@laurencei Well we have to have a list of NPCs with which auto turn in might not be save... So they are "hardcoded" in a list 🤔

This is fixed with https://github.com/AeroScripts/QuestieDev/commit/da651040407c8375ed1a39e463ee8124121acf3e
