### ISSUE TITLE
AQ icons

### ISSUE THREAD

**Issue by Nerillida** [AeroScripts/QuestieDev#2238]
There are Commendation Officers that will persist after the AQ events. One/two in each city

15761 Officer Vu'Shalay
15762 Officer Lunalight
15763 Officer Porterhouse
15764 Officer Ironbeard
15765 Officer Redblade
15766 Officer Maloof
15767 Officer Thunderstrider
15768 Officer Gothena

These are still here in retail.

**Comment by BreakBB** [comment]
@Nerillida Yeah, you are right. Thanks 👍
