### ISSUE TITLE
Port to WotLK 3.3.5?

### ISSUE THREAD

**Issue by crumdidlyumshis** [AeroScripts/QuestieDev#224]
I apologize if this has been posted before as I could not find it. But is there any plans for a port to WotLK? I saw there TBC 2.4.3 version is in progress. Just curious. Currently I am having to rely on EveryQuest and HandyNotes which sucks IMO.

**Comment by Dyaxler** [comment]
WotLK is my favorite expansion and I was planning on making a version of Questie that will work but it all depends on the tool I need to update the current database to include all the quest data from BC and Wrath for those versions to properly work or be of use. The tool is being worked on but I have no ETA nor can I make any promises that it will even work...

**Comment by crumdidlyumshis** [comment]
Awesome! Thank you for the reply and the hard work you guys do! I look forward to the future of Questie! :dancer:

**Comment by leopku** [comment]
What's the progress of this issue?
Does this awesome plugin support WotLK now?

Appreciate for the author and all contributors.

**Comment by BreakBB** [comment]
@leopku We're very limited in manpower and time, so we have been focusing on WoW Classic and (at least currently) don't plan to start porting Questie to some other expansion. Sorry mate and thanks for your kind words.

**Comment by leopku** [comment]
@BreakBB  It's OK.
Thanks for your reply.

Is where any guid or attentions for porting plugins from Classic to WotLK? Maybe I can do something for this plugin.

**Comment by BreakBB** [comment]
@leopku This really depends on the addon. For Questie you would have to port the hole database to WotLK, meaning adding all the new quests (including TBC) and changing what changed since vanilla. There will most likely also be problems with some API functions we're using now which were not included in vanilla, but are now in Classic.

All in all a really, really hard and time intensive task.

**Comment by leopku** [comment]
@BreakBB Got it.
I will try it today. Thanks again.

**Comment by loskiq** [comment]
I found someone who ported this addon for version 3.3.5
https://github.com/widxwer/Questie
It really works!
