### ISSUE TITLE
Gammerita, Mon! does not require a prequest

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#2247]
Despite what Wowhead says.

https://classic.wowhead.com/quest=7816/gammerita-mon

![WoWScrnShot_080520_103019](https://user-images.githubusercontent.com/54936174/89390390-ed588b00-d706-11ea-98a2-10cc5d10e355.jpg)

Version 6.0.4

**Comment by BreakBB** [comment]
Thanks @Cerby3BR for another report :pray: This is easy to fix :+1:
