### ISSUE TITLE
Wrong Quest marker location A call to Arms: Plaguelands! (horde) 

### ISSUE THREAD

**Issue by Dtenwolde** [AeroScripts/QuestieDev#2251]
The quest marker for A call to arms: Plaguelands (hords) can be found in the Valley of Spirits coords 37.5 75.6, but should be at 46.6 64.6

**Comment by drejjmit** [comment]
He paths. It even shows the path he's taking. 
![image](https://user-images.githubusercontent.com/15526476/89719781-51f83c00-d9cc-11ea-9063-e25805867ad4.png)

**Comment by BreakBB** [comment]
@Dtenwolde Thanks for reporting this, but as @drejjmit already answered this is working correctly. Feel free to open up a new ticket if this (or anything else) is still an issue for you 👍
