### ISSUE TITLE
Search for Incendicite missing pre-quest

### ISSUE THREAD

**Issue by Zardilann** [AeroScripts/QuestieDev#2252]
https://classic.wowhead.com/quest=466/search-for-incendicite is missing the pre-quest https://classic.wowhead.com/quest=467/stonegears-search . It is not available before that, despite showing on the map.

![image](https://user-images.githubusercontent.com/167260/89723955-6acd1580-d9fd-11ea-8257-b87ff6b9c008.png)

![image](https://user-images.githubusercontent.com/167260/89723969-8506f380-d9fd-11ea-831c-bbdaa553db89.png)

**Comment by drejjmit** [comment]
It is available if you abandon the breadcrumb quest. Tested this myself. Stonegear's Search is not required for Search for Incendicite.

**Comment by BreakBB** [comment]
Closing this as it is working as expected.
