### ISSUE TITLE
Several Dungeon Quest icons still appear even though the option to show them is disabled

### ISSUE THREAD

**Issue by zgit2020** [AeroScripts/QuestieDev#2254]
## Description
I have the option "Enable Dungeon Quest Icons" unchecked. However, several dungeon quests still appear on the map/minimap in Tanaris and Searing Gorge.

## Wowhead Link(s)
Tanaris:
Scarab Shells - https://classic.wowhead.com/quest=2865
Troll Temper - https://classic.wowhead.com/quest=3042
Divino-matic Rod - https://classic.wowhead.com/quest=2768
Into the Depths - https://classic.wowhead.com/quest=3446
Secret of the Circle - https://classic.wowhead.com/quest=3447

Searing Gorge:
The Heart of the Mountain - https://classic.wowhead.com/quest=4123
The Good Stuff - https://classic.wowhead.com/quest=4286
Overmaster Pyron - https://classic.wowhead.com/quest=4262

## Screenshots
![Questie Screen 01](https://user-images.githubusercontent.com/69525736/89922987-b7a71c80-dbb4-11ea-8dfc-d70148c196ec.jpg)
![Questie Screen 02](https://user-images.githubusercontent.com/69525736/89922997-ba097680-dbb4-11ea-9dfd-f530719d86ae.jpg)

**Comment by BreakBB** [comment]
@zgit2020 Did you try a /reload ? There is a general problem with the icons settings atm, sorry.

**Comment by zgit2020** [comment]
Yes, and that seemed to work. Thank you!
