### ISSUE TITLE
Major performance issue with mob tooltip, make the game freeze for a split second

### ISSUE THREAD

**Issue by gouletr** [AeroScripts/QuestieDev#2259]
## Bug description
When doing mouse hover mobs to show tooltip, while in a raid with people also having the same quest (for example, [The Perfect Poison](https://classic.wowhead.com/quest=9023/the-perfect-poison)), there's a major performance issue that will freeze the game for a split second. This is pretty annoying since it happens every time we mouse hover a mob, so it makes the game choppy.

The work-around is to disable Questie tooltips when hovering mobs, problem goes away. I would expect Questie to make some kind of cache so that hovering mobs wouldn't cause lag/stuttering.

## Questie version
Version: 6.0.4

**Comment by drejjmit** [comment]
Should be fixed with 67fa6b37d11b9f82b9a2c36796a4550a57293719
