### ISSUE TITLE
Issue with [56+] Ursius of the Shardtooth

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2266]
## Bug description

[[56+] Ursius of the Shardtooth (5054)]

Needs more than one dot for the location of Ursius 

* Ursius of the Shardtooth - Quest - World of Warcraft || https://classic.wowhead.com/quest=5054/ursius-of-the-shardtooth

* Ursius - NPC - World of Warcraft || https://classic.wowhead.com/npc=10806/ursius

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/90303853-80b45d80-de77-11ea-9fa8-fe6d3f6adb93.png)

## Questie version

6.0.4

**Comment by Gogo1951** [comment]
Followup quests need work too.

[[58] Brumeran of the Chillwind (5055)]

* Needs pat of Brumeran 

* Brumeran - NPC - World of Warcraft || https://classic.wowhead.com/npc=10807/brumeran

[[60] Shy-Rotam (5056)]

* needs the "fresh carcus" effect (like from https://classic.wowhead.com/search?q=Frostmaw) for the Sacred Frostsaber Meat that drops off of a few kinds of frostsabers.

* Sacred Frostsaber Meat - Item - World of Warcraft || https://classic.wowhead.com/item=12733/sacred-frostsaber-meat

**Comment by drejjmit** [comment]
Moving last one out of this issue. See #2286
