### ISSUE TITLE
Custom Target Frame Quest Objectives marker

### ISSUE THREAD

**Issue by theoriginalmre** [AeroScripts/QuestieDev#2269]
Since I use the addon Shadowed Unit Frames instead of the default Blizzard Unit Frames, I am unable to see any Mob Objectives marks on my Target Frame. 

So to combat this, can you implement the feature to make a custom moveable Target Frame Quest Objectives marker that I can manually position next to the Target Frame? This will solve any issues regarding other addons that replace the default Blizzard Unit Frames.

**Comment by drejjmit** [comment]
This isn't a feature even on default Blizzard Unit Frames, but maybe it should be. Objective icons are only shown on nameplates and tooltips, not target frames.

**Comment by theoriginalmre** [comment]
There is currently an option in Questie to enable Target Frame Quest Objectives. It doesn't seem to do anything, but like I said im using Shadowed Unit Frames so i assume it doesnt work with this addon.

**Comment by drejjmit** [comment]
https://github.com/AeroScripts/QuestieDev/blob/67cadac9379d74094d94947ecc74568cbbedbf67/Modules/QuestieNameplate.lua#L207 You can change this from ``TargetFrame`` to ``SUFUnittarget``
I use **PitBull4** and that frame is ``PitBull4_Frames_Target``

@BreakBB Do you think we can do something similar to what we do on questFrame? And draw it on ``TargetFrame``,``SUFUnittarget``or ``PitBull4_Frames_Target`` https://github.com/AeroScripts/QuestieDev/blob/67cadac9379d74094d94947ecc74568cbbedbf67/Modules/Tracker/QuestieTrackerUtils.lua#L17

**Comment by theoriginalmre** [comment]
I've made the code changes and the icons have finally appeared! - However, the Frame Strata that Questie is using is apparently lower than Shadowed UF, so the icon appears behind the frame. I have to manually position it next to the frame to make it visible.

**Comment by drejjmit** [comment]
https://github.com/Nevcairiel/ShadowedUnitFrames/blob/a64713d5788e402a917a13b126268d11e6c45513/modules/units.lua#L1267
You can change this to
```	bar:SetFrameLevel(1)```
Since default unit frame uses LOW strata this will not be changed on our side.

**Comment by theoriginalmre** [comment]
Damn you're good Drej.

**Comment by BreakBB** [comment]
@drejjmit Yeah that should be no problem. Simply check for all "known" frames and add them. Great catch and I think it will be a great improvement! 👍

**Comment by theoriginalmre** [comment]
> 
> 
> https://github.com/Nevcairiel/ShadowedUnitFrames/blob/a64713d5788e402a917a13b126268d11e6c45513/modules/units.lua#L1267
> You can change this to
> ` bar:SetFrameLevel(1)`
> Since default unit frame uses LOW strata this will not be changed on our side.

Unfortunate side effect of this is that the Party Frames lose their foreground colours. Same goes for Party Target Frames, and Pet Target Frames. I had to set bar:SetFrameLevel(3) to get the colours back, but this results in the same initial Frame Strata problem for Questie's Target Frame marker not being at the correct strata.

I've positioned the marker next to the target frame again which is fine for now.

**Comment by drejjmit** [comment]
Try setting the foreground colors as a higher FrameLevel.
Did he stop updating? No changes on that project for 7 months

**Comment by theoriginalmre** [comment]
I don't think the author keeps it updated. For the most part the addon is fine though so I don't have much to complain about. 

I don't know enough about what to look for in the code to set the framelevel. It's above my understanding of the API.

**Comment by BreakBB** [comment]
Pullrequest #2357
