### ISSUE TITLE
Cant move questie tracker

### ISSUE THREAD

**Issue by Salix01** [AeroScripts/QuestieDev#227]
Hi, with the 3.0 I just cant move the questie tracker where I want, and when I log in log out it just goes top left of the screen. 
Am I the only one having this issue?

Ty for this addon

**Comment by Fujiroko** [comment]
i have the same issue and i cannot move the arrow ether

**Comment by Dyaxler** [comment]
/questie clearconfig
English only server otherwise the tracker/Questie doesn't work
Hold CTRL+Shift+Click while dragging

**Comment by Salix01** [comment]
yeh that was the server! thank you

**Comment by Dyaxler** [comment]
no problem
