### ISSUE TITLE
Icons on Map not showing

### ISSUE THREAD

**Issue by Madduke1** [AeroScripts/QuestieDev#2270]
The quest markers don't update on certain quests to note their pick up or drop off location.
The main problem is the kill objectives and locations don't show up.
I have reinstalled questie, disabled all other addons, can't seem to fix the problem.

**Comment by Madduke1** [comment]
Update it is only not showing the new Silithus quests you get to kill bugs, etc.

**Comment by drejjmit** [comment]
Try checking "Enable AQ War Effort Quest Icons" then ``/reload``. 
Some quests are tagged incorrectly as war effort instead of Phase 5.

**Comment by BreakBB** [comment]
@Madduke1 It would be great if you could try what drejjmit suggested. There is a single option for most of the new Silithus quests which (currently) needs to be enabled.

**Comment by Jessebel** [comment]
I dont see quest givers on my map, it's only on one toon. I tried resetting Questie, reinstalling Questie, unchecking all addons xcept questie, nothing showing

**Comment by Gogo1951** [comment]
Please update to latest questie, then enable this button. You should see quests.

![image](https://user-images.githubusercontent.com/55365231/90699956-2e45b900-e24a-11ea-8fc2-23e68b29fa2f.png)

**Comment by Jessebel** [comment]
ty very much, it wasnt that but a check of absolute minimum quests 😉
________________________________
Van: Gogo1951 <notifications@github.com>
Verzonden: donderdag 20 augustus 2020 01:32
Aan: AeroScripts/QuestieDev <QuestieDev@noreply.github.com>
CC: Jessebel <c.broekmeijer@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [AeroScripts/QuestieDev] Icons on Map not showing (#2270)


Please update to latest questie, then enable this button. You should see quests.

[image]<https://user-images.githubusercontent.com/55365231/90699956-2e45b900-e24a-11ea-8fc2-23e68b29fa2f.png>

**Comment by drejjmit** [comment]
Glad you figured it out. Just make a new 'issue' if you encounter any problems

**Comment by drejjmit** [comment]
> @drejjmit your suggestion worked. Was busy at work during the week, but got a chance to try it out last night, works well. Just sucks having the ironforge quests all up, but rather be able to see the kill targets. Thanks!

Fixed in v6.0.5 so now you don't have to have it enabled for the quests to show 🙂
