### ISSUE TITLE
[Brann Bronzebeard's Lost Letter (8308)]

### ISSUE THREAD

**Issue by Ulidan** [AeroScripts/QuestieDev#2279]
[Brann Bronzebeard's Lost Letter (8308)] is linked to the war effort quests by mistake and gets disabled when disabling the war effort quests in settings as some other new quests I can't recall now.

**Comment by drejjmit** [comment]
Fixed with https://github.com/AeroScripts/QuestieDev/commit/a570b2cc9d1aa6d50357f4f172259ed6f3be3c2b
