### ISSUE TITLE
Show Townsfolk on the Map and Minimap

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2282]
## Description

As a user who quests, I would love to know where various townsfolk are while I'm out in the world.

* We've got a nice map interface, it seems like it'd be a good fit to add some other things to it.

* As the game matures, looking for ways to keep people engaged with Questie once they hit 60.

I spoke with the guy who created Townsfolk Tracker, and he's OK with us absorbing that functionality if we're keen. Just need to list him in the patch notes. He quit and doesn't maintain the addon any more.

Here's the code:

* Townsfolk Tracker - Addons - World of Warcraft - CurseForge || https://www.curseforge.com/wow/addons/townsfolk-tracker

* mokulu / townsfolk-tracker — Bitbucket | https://bitbucket.org/mokulu/townsfolk-tracker/src/master/

**Comment by Gogo1951** [comment]
Sounds like this is in progress. (=

**Comment by Kazenokamii** [comment]
Can't find a way to disable this new feature...

**Comment by drejjmit** [comment]
Just click the minimap icon.

**Comment by Kazenokamii** [comment]
Ahh - ty - I didn't have the minimap button showing and there's no way to disable from the /questie portion

**Comment by Gogo1951** [comment]
This was completed with 6.0 (=
