### ISSUE TITLE
script error at first run.

### ISSUE THREAD

**Issue by rasberryrabbit** [AeroScripts/QuestieDev#229]
I got script error message on running addon first.
I changed 'QuestieTracker.lua' line 710 and it fixed.

`if QuestieTrackedQuests[hash] and QuestieTrackedQuests[hash]["objective1"] then`

**Comment by Dyaxler** [comment]
That might not be a good idea. Coding around "first run" nil errors is always tricky. Reloading your UI should have gotten rid of that error. Once the initial QuestieConfig is done loading and caching it shouldn't nil out.

**Comment by rasberryrabbit** [comment]
Aha, I understand. It is not a big problem :)
