### ISSUE TITLE
Here is the ticket I just opened with Blizzard re WoW Classic.

### ISSUE THREAD

**Issue by jim55price** [AeroScripts/QuestieDev#2293]
The Questie addon blocks questing information between party members. I can be standing right beside a party member who is on the same quest that I am, but we cannot see this in our quest logs. QUESTIE IS WRECKING NORMAL WOW QUESTING MECHANICS. Please fix this. I've never used this abominable addon and probably never will. However, now it is strong-arming its way into wrecking gameplay for non-users. Make them fix it, or make them disappear.

**Comment by drejjmit** [comment]
``The Questie addon blocks questing information between party members.``
Blizzard UI doesn't share any questing information between party members.

`` I can be standing right beside a party member who is on the same quest that I am, but we cannot see this in our quest logs. ``
Questie doesn't do anything to the quest log. Must be some other addon.

``QUESTIE IS WRECKING NORMAL WOW QUESTING MECHANICS.``
It only offers information. You can disable the information you don't want on minimap/map or tooltips.

``wrecking gameplay for non-users.``
Questie doesn't do anything outside of your own UI.
A player without Questie can't tell that you're using it.

**Comment by jim55price** [comment]
When I look at my quest log, the interface routinely shows how many nearby
party members are on the same quests.  It looks like this :

   - [1] Beren's Peril
   -      Some-other-quest
   - [2] Yet-another-quest

In the above example, one nearby member is on the first quest with me, none
are on the second one, and two are on the third.  This has been standard in
Classic for me from the start.

As for Questie not doing anything with the quest log, that's obviously a
dodge, and an unprofessional one, at that.  No one said anything about
anything being done "to the quest log".  The complaint is over what is
shown to me and to other players.

As I've stated quite clearly, I don't have Questie installed -- never have,
probably never will -- so please rethink your advising me to "disable the
information you don't want on minimap/map or tooltips".  That is simply
impossible.  I have no Questie to adjust.

As for doing things outside my UI and who can tell what, again, this is a
dodge, and an irrelevant one, at that.  When another player and I stop to
discuss the FACT that neither of our quest logs show that the other is on a
given quest we both have, and that we are OBVIOUSLY accustomed to having
this information show up in our quest logs, otherwise we wouldn't be
stopping to discuss it NOT being shown, then your dismissals and denials
here look very poor indeed.

Please refer this issue to your supervisor.  I'd like to speak to someone
more familiar with logical fallacies and less guilty of engaging in them in
professional communications.

**Comment by AeroScripts** [comment]
I'll do some testing to try to reproduce the issue soon, but this really shouldn't be possible as the party member count is handled by internal blizzard code, I don't think we could break that even if we wanted to

Are you absolutely sure it's questie and not some other combination of addons? What steps should we take to reproduce the issue

You gotta chill out a bit though, we're all volunteers here trying to improve things best we can, no need to get heated

**Comment by Gogo1951** [comment]
I just tested with 2 accounts side by side. Invited a third person who had the quest, 2 had Questie, the other had Questie disabled. No issue.

Hey @jim55price we're an all volunteer team, limited hours and all that. Sorry you're having an issue, but it's not a Questie issue. Good luck sorting it out. Cheers!

**Comment by jim55price** [comment]
Okay, sure, I can chill.  I'm just a 20-year veteran of serious corporate
mainframe software design & programming who finds it a bit insulting to be
dismissed so casually -- & wrongly, to boot.

But chill I shall.

I'm going to employ a strategy known as "minimal pairing" -- that is, each
step below is designed to illustrate exactly ONE thing, & that one thing
only.  A simple series of such minimal pairs will make my case abundantly
clear, I do believe.

(1) Start two new toons anywhere, side by side on separate accounts so both
can be logged on at the same time.  With no alterations to anything at all,
& no addons, period, have both toons group together & then get the initial
newbie quest.  Then, have both toons stand close together & look at their
quest logs.  Do this and each quest log should list that first newbie quest
with a [1] to its left, indicating that one nearby party member is on that
same quest.

(2) Start a third new toon on a third account side by side with the first
two.  Have this toon install Questie & then join the above group, get the
newbie quest, & look at the quest log.  If there is no interference in
quest log display, all three toons should now have [2] to the left of that
quest in the quest log because, from each toon's perspective, two nearby
party members are on the same quest.  What I expect, however -- because of
the error I'm reporting -- is that the first two toons will still have [1]
& the third toon will have just a blank space where the others have [1],
meaning that Questie is interfering with the normal sharing of quest log
information, as I've reported.

(3) Assuming step two goes as expected, one of the first two toons should
then ungroup, at which point the two remaining grouped toons' quest logs
should both have reverted to a blank space beside the newbie quest.  (NOTE
that a wrinkle in step two may or may not invalidate this step.  If there
is such a wrinkle, you'll have to stop & think about whether this step is
affected or not.)

If the above strategy fails, then more analysis is required.  For instance,
maybe starter zone quests are processed differently somehow in some way I'm
unaware of.  That's entirely possible.  However, I know what I've observed
for months & actually stood in a cave & discussed with another player
yesterday, & it is that interplayer questlog communication we're used to is
absent when only one of us has Questie installed.

Understand, I've run into at least one other ongoing Questie issue ever
since I've seen Questie around (I started Classic on day one or two at
initial launch, I forget which), but only this one impacts me directly,
hence my complaint.

And yes, I'm sorry I'm sometimes such an ass, but that's life.  I will try
to be more civil in the future.

Good luck, and feel free to ask for more diagnostic ideas.  I may have to
ask for a little basic info along the way, but I'll be glad to help if I
can.  I *do* have substantial experience at debugging complex systems.

Anyway, cheers.  Holler back any time.

**Comment by jim55price** [comment]
Interestingly, this problem occurs ONLY between me (no Questie) and other
players (all with Questie).

But sure, it's not  a Questie problem.

Ha ha ha.

I'm glad your preliminary investigation essentially mirrored the one I
devised & sent you about the same time you sent your last response.  Sadly,
though, I see you falling prey to something known as Confirmation Bias when
that initial look appears to have gone along with what you already
believe.  You are seeing what you want to and refusing to dig deeper.  This
is both unprofessional and amateur.  (And no, that's not "heated".  I'm
smiling.  It's just fact.)

So, Questie is now in my mind an even bigger waste of time than it already
was.

Y'all have fun.  I can see now why you're "only volunteers".

**Comment by Gogo1951** [comment]
Hey @jim55price,

You've eaten up enough time as it is, but with over 20M downloads we do take this addon pretty seriously.

Most of us have extensive backgrounds in tech... AWS, Microsoft, Accenture... If you're into mainframes, likely Cobol, you've got a lot of job security so you can probably afford to be a bit more gruff than the rest of us. Kudos to you. Ride it out.

But to put this to bed once and for all, I did exactly what you had said. Created some new toons, without Questie. I had a toon with Quesite join the group and we picked up a quest.

Here are the screenshots. The logs were identical.

## Questie

![image](https://user-images.githubusercontent.com/55365231/90842064-f01cc800-e323-11ea-9fdc-4e33add9b2ad.png)

## No Questie

![image](https://user-images.githubusercontent.com/55365231/90842069-f4e17c00-e323-11ea-9be3-ad92aeef0748.png)

**Comment by jim55price** [comment]
As I said before, I'm glad your initial test was essentially identical to
the one I devised.  It shows at least a modicum of reason and a nose for
starting an investigation.  Your logic in that test is good, as far as it
goes.  The problem is that it doesn't go far enough.

Confirmation bias is the thing that allows you to find what you want to
find, interpret it as final proof of what you personally desire to believe,
and then declare the matter done.

Sadly, that doesn't suffice in more demanding environments, which, again,
is why I'm so "gruff", as you put it.

Simply put, I'm the guy who codes in assembler and single-handedly builds
systems that produce $35,000 an hour profit in 1980s money -- yeah, I'm
that old -- and when I tell you you're declaring victory and quitting the
game after only one inning, you would be well advised to take heed --
EXCEPT, of course, for the fact that you're talking about coding for a game
alongside a pack of volunteers, and no one's life or livelihood is at
stake, in contradistinction to the bulk of my work.  My code had to be
perfect or people's whole lives were wrecked, and the same held true for my
diagnostics and investigations (of which there were many).  That's what my
20 years was.  I'm afraid your attempted COBOL insult widely missed its
mark.

You see, if you'll review my initial plan, it included at least a mention
of what to do if it failed, because, very much unlike your effort to prove
a negative -- that is, what you insist can't be true because a single round
of testing didn't expose it -- I am 100% certain of what I've experienced
repeatedly over the past several months in WoW Classic, and that is that,
when I and a party member's quest logs don't reveal our mutual quests, that
party member has Questie installed (and I, as a reliable constant, do not).

But you know, beating dead horses and all like that.

I don't mean to be professionally disrespectful, but in a serious work
environment, I'd fire you and your whole team in a heartbeat if you came
back after one round of testing and told me I hadn't seen what I told you I
saw.

Don't worry about my opinion, though, cowboy.  I'm not a Questie user, and
I'm fine if what I say matters to you not at all.  I enjoy WoW enough to
have put up with a little Questie crippling for a while, and if it STAYS
that way, I'll probably put up with that, too.

If you do find and fix the problem, I'd appreciate being notified.  Don't
worry, though :  I won't be holding my breath.

Y'all take care now.  Bye.

**Comment by jim55price** [comment]
Well, here you go, a screenshot of (to borrow your phrasing) "shite being
broke".

Do me a favor and don't reply.  I'm not a Questie user, I don't care if you
fix this or not, and I generally despise your illogical assertion that
nothing can be wrong because you can't make it show up when you happen to
see fit.  I just thought you might like to see a screenshot of what it
looks like when your product fails in the manner I've described to you in
some detail already.

In the attached screenshot, I'm the cat facing into the cave.  My partymate
is the troll running out of the cave.  My quest log is open, the offending
quest is highlighted, and there is no (1) by it to indicate we were both on
it, despite the fact that we were.  The troll is a Questie user; the cat is
not.  This is a picture of the Questie error I've tried to bring to your
attention.

Again, I don't care if you fix it.  I brought it to your attention as a
matter of professional courtesy.  Your unprofessional blow-off reply isn't
my concern.  Cheers.

**Comment by drejjmit** [comment]
Can't see any attachment.

**Comment by Dyaxler** [comment]
I multibox. Not seeing an issue here.
