### ISSUE TITLE
Combat Taint Encountered

### ISSUE THREAD

**Issue by Alumian** [AeroScripts/QuestieDev#2294]
## Bug description
While in combat, a taint was detected. See attached: [taint.log](https://github.com/AeroScripts/QuestieDev/files/5106452/taint.log)
The taint occurred shortly after log in, I was soloing (not in a party/raid/battleground group)

## Screenshots
Unfortunately I didn't grab a screenshot at the time.

## Questie version
V6.0.4

**Comment by AeroScripts** [comment]
There were some changes to the tracker logic that should hopefully solve this issue, so im closing it for now, but if this happens again post back and ill re-open this
