### ISSUE TITLE
AQ War effort config should be per realm, not per char

### ISSUE THREAD

**Issue by dieck** [AeroScripts/QuestieDev#2295]
Hello,

On logging in, you are presenting the message "The AQ War Effort quests are shown for you. If your server is done you can hide those quests in the General settings of Questie!".

The config is currently done per character.
I think it would make much more sense to have this on realm level, or at least realm/faction level

**Comment by Gogo1951** [comment]
Good catch. (=

**Comment by Gogo1951** [comment]
Good fix. Marking this as closed so we can focus on other issues. Cheers!
