### ISSUE TITLE
Questie.lua:253 attempt to index field 'ABANDON_QUESTS_WITH_ITEMS'(a nil value)

### ISSUE THREAD

**Issue by chrispwns** [AeroScripts/QuestieDev#230]
Title. 

Just thought  I'd bring it to your attention; I'm also unable to use /questie without getting the WoW error "Type '/help' for a listing of a few commands.'

**Comment by Dyaxler** [comment]
"StaticPopupDialogs["ABANDON_QUEST_WITH_ITEMS"].OnAccept"

This is an actual Blizzard popup that I hooked into. Might be an addon issue that's conflicting or the server you're on. Is this the first time you've run Questie or did you upgrade from an earlier version?

**Comment by chrispwns** [comment]
This is my first time using it, is there a list of known conflicting addons? A few others in my guild are using it without issue. So I assume It's an addon issue then, I can always go through them one-by-one if I have to.

**Comment by Dyaxler** [comment]
I would personally disable everything except Questie and EQL3. Login. ReloadUI. Logout. Re-enable all addons and log back in. Try that first.

**Comment by chrispwns** [comment]
Yeah, same issue with only Questie and EQL3 enabled.

**Comment by Dyaxler** [comment]
Where did you get EQL3 and which version of Questie did you download?

**Comment by chrispwns** [comment]
I downloaded EQL3 from vanilla-addons.com and I'm using 3.0, the most current one on the downloads page.

**Comment by Dyaxler** [comment]
So when does this error occur? Upon login? It's not supposed to fire unless you're abandoning a quest.

**Comment by chrispwns** [comment]
As soon as I login the error pops up, quests I've previously done show up as available and I cannot use any slash commands.

**Comment by Dyaxler** [comment]
I think what we're dealing with here is a simple case of corruption... since this is the first time using Questie I'd suggest deleting it and reinstall it. Don't forget to clean out your WTF directory and delete the !Questie.lua file in the WTF directory. There will be one for each character you have. I'd also suggest clearing your client cache by deleting all the files in the WDB directory. Perhaps your cache is presenting scrambled quest data.

**Comment by chrispwns** [comment]
Okay, did all of that. Same issue.

**Comment by Dyaxler** [comment]
Are you playing on an English server?

**Comment by chrispwns** [comment]
yes

**Comment by chrispwns** [comment]
well US, if you mean English as in Country.

**Comment by Dyaxler** [comment]
Can you send me your !Questie.lua and addons.txt from your WTF directory?

Some of the servers that are available to us aren't always using an English database... I just needed to make sure because Questie depends on all data coming from the server to be in English.

**Comment by chrispwns** [comment]
[AddOns.txt](https://github.com/AeroScripts/QuestieDev/files/245459/AddOns.txt)


http://pastebin.com/YuwsFiUe

kua is on pastebin since I cannot upload it here for some reason.

**Comment by Dyaxler** [comment]
Don't indicate here but please send me a private PM or Email with the server you play on please. It must be server related. It's possible that the server is blocking this Blizzard function. This is the actual Blizzard code that I'm hooking from the 1.12.1 client...

`StaticPopupDialogs["ABANDON_QUEST_WITH_ITEMS"] = {
	text = TEXT(ABANDON_QUEST_CONFIRM_WITH_ITEMS),
	button1 = TEXT(YES),
	button2 = TEXT(NO),
	OnAccept = function()
		AbandonQuest();
		PlaySound("igQuestLogAbandonQuest");
	end,
	timeout = 0,
	whileDead = 1,
	exclusive = 1,
	hideOnEscape = 1
};`

My code simply waits for the "OnAccept" click from the player then executes the code after from within the Questie namespace. All it does is set a few QuestieConfig flags in the quest hash tables. Nothing EULA breaking from a servers operational perspective. I can't imagine why the server would block this function but I've seen it happen.

**Comment by chrispwns** [comment]
iirc github removed the PM feature. I really don't mind anyone knowing what server I've been on lately, unless it's for security reasons.

**Comment by Dyaxler** [comment]
Ah yes... good point. My email is my handle at hotmail dot com. For everyone's protection it's just best to not talk about or mention where we choose to use the art we create. ;)

**Comment by chrispwns** [comment]
Sent! :)

**Comment by Dyaxler** [comment]
Yeah, I got it... I'm going to see if I can repro this issue.

**Comment by Dyaxler** [comment]
This is incredibly odd... I can't get it to re-pro. Question for you. Where did you install the client? D:\ drive? C:\ drive? Mac? PC? C:\Program Files?

**Comment by chrispwns** [comment]
J:\Game\World of Warcraft 1.12 PC

**Comment by chrispwns** [comment]
I can try putting it on my SSD if that would be helpful?

**Comment by Dyaxler** [comment]
Yeah this is strange... if I unload EQL3 then the function that you say is error'ing fires just fine.

I assume you have a "short-cut" on your desktop? Try running the wow client "Run as Administrator". Do you have full administrative permissions to your computer? Just asking because I once talked to a kid that only had "Power User" level permissions and he was getting all kinds of bizarre errors. Took us a LONG time to figure that one out because it's so uncommon.

I have my client running on an SSD. Trust me, it's not that.

**Comment by Dyaxler** [comment]
Oh... is this J drive an external hard drive?

**Comment by chrispwns** [comment]
I'm the only user on this PC, I have complete permissions. I can run it as admin right quick, I actually don't have anything on my desktop, I pin things on my task bar.

**Comment by chrispwns** [comment]
No, I just have like 5 hard drives lmao.

**Comment by chrispwns** [comment]
Okay, still getting this when I run as admin.

**Comment by Dyaxler** [comment]
Well I created a new character on that server you mentioned... was playing a mage for the past couple of hours. The queue was bloody brutal. I had to wait quite awhile to get in.

I did a stack trace against the two abandonment functions that I'm hooking into and they both fire in debug mode so I know they aren't being blocked on the server. My only guess is that something in your client isn't allowing you to read your questie config file.

Questie.lua line 253 is this... `QuestAbandonWithItemsOnAccept = StaticPopupDialogs["ABANDON_QUEST_WITH_ITEMS"].OnAccept;` which pipes out just fine in game.

![capture](https://cloud.githubusercontent.com/assets/17400948/14968033/87e49712-106f-11e6-8ab6-610d3c793e78.JPG)

Can you try copying your install to the root of your C:\ drive? Something like C:\wowclassic just to see if that solves the issue. Maybe the client is having issues with the drive letter being that high. *shrug* that is really the only thing that is jumping out at me right now. It's really the only difference between your install and mine... and most everyone else I suppose. :D

**Comment by Dyaxler** [comment]
You said you only had Questie and EQL3 loaded while testing? Because it looks like you're running VanillaGuide and AtlasQuest... Questie isn't an ACE mod so if something else is trying to hook into the same thing Questie is hooking... you're going to have issues.

Bongos_MapBar: enabled
Bartender2: disabled
Atlas: disabled
AtlasLoot: enabled
AtlasQuest: enabled
MetaMap: enabled
MapCoords: enabled
Bongos: enabled
BigWigs: enabled
Bongos_ActionBar: enabled
Bongos_Options: enabled
Bongos_RollBar: enabled
LunaUnitFrames: enabled
VanillaGuide: enabled
MoveAnything: enabled
CT_MailMod: enabled

**Comment by chrispwns** [comment]
I have ran it alone, it had the same issue. I will swap to C drive soon

**Comment by Dyaxler** [comment]
Did you move your folder and clean out your WDB cache? Another person resolved his issue with Questie by cleaning out his WDB folder. He recently switched servers.

![capture](https://cloud.githubusercontent.com/assets/17400948/14988648/b957cd2e-1109-11e6-82f5-6e57e6eeaaca.JPG)

**Comment by chrispwns** [comment]
Yeah, sorry was busy. Same deal. Might end up having to redownload the client, do you have a preferred download?

**Comment by Dyaxler** [comment]
I suggest getting to it before the links go dead...
http://forum.nostalrius.org/viewtopic.php?f=32&t=2803

**Comment by chrispwns** [comment]
Same issue, weird. I'm very confused by this and entirely certain it's on my end just not sure where to look at this point.

**Comment by Dyaxler** [comment]
I'm at a loss unless your video card or a memory stick might be going bad... :(

**Comment by chrispwns** [comment]
I'm buying another 16GB to throw in my machine anyways today, I will test without the other ram (current ram passed memtest recently). As far as GPU I've got a 980TI that's (basically) brand new and hasn't given me any fuss so far, but I'll run so real heavy benchmarks and see if I can't get it to show some defects and get an RMA if I need to.

**Comment by Dyaxler** [comment]
Sounds like you practically have a brand new computer. It's gotta be something stupid or small that we're overlooking. I refuse to believe it won't run on your computer. If this was a coding issue, WAY more people would be getting this error you're experiencing.

For kicks, have you tried running on a different server? Different faction. New character? Have you tried deleting your WTF folder and WDB folder and run this on a "clean" install of wow running all default settings?

**Comment by chrispwns** [comment]
I'm constantly building to it, so kinda new. Could resolution be an issue? It is extremely unlikely; however, I have an oddball resolution so maybe? Yes, I've deleted my  WTF and WDB, other servers do the same. idk.

**Comment by Dyaxler** [comment]
oddball resolution? How oddball? At this point I wouldn't rule anything out...

**Comment by chrispwns** [comment]
3440x1440 ultrawide, so pretty odball. I know the login screen and character select cut off and show weird colors floating.

**Comment by Dyaxler** [comment]
Well I run in 2560 x 1080 so it does run in ultrawide 21:9

**Comment by chrispwns** [comment]
Okay, so that's not an issue. I'm not really sure, if you want to do your own troubleshooting let me know and I can let you teamviewer. I've already unhooked a few hard drives just to see if the count matters and same deal.

**Comment by Dyaxler** [comment]
Lets try and get the full error message... maybe there is something else that is triggering the error. Start with a FRESH install of the WoW client installed in the root of your C: drive. Then install a fresh install of Questie and Improvederrorframe: http://addons.us.to/addon/improvederrorframe

Make sure your WTF and WDB directories are also cleaned out. Login, make sure both Questie and Improvederrorframe are installed. Capture the error call stack and screen shot it if you can. I'll need the top most error message.

**Comment by chrispwns** [comment]
![wowscrnshot_050216_160255](https://cloud.githubusercontent.com/assets/10478216/15031800/c5debd22-1218-11e6-8e37-e4fe985421aa.png)
HEee's what it gives me

**Comment by Dyaxler** [comment]
Try this file please... replace Questie.lua in this directory:
> Addons\Interface\!Questie

[Questie.zip](https://github.com/AeroScripts/QuestieDev/files/249731/Questie.zip)

**Comment by chrispwns** [comment]
![wowscrnshot_050416_181623](https://cloud.githubusercontent.com/assets/10478216/15032242/0b139bbc-121c-11e6-883d-9896e25c161c.png)

**Comment by Dyaxler** [comment]
WHAT THE F***! I almost expected the first two errors but the third was totally unexpected. This isn't right. The OnUpdate function is right. I know it is. You definitely have something else going on here. Can you logout and back to the screen with the Addon's button on it. Click that and show me your addons. It will also show how much memory you're allocating to addons there too...

**Comment by Dyaxler** [comment]
... do you know how to take a screen capture? If not just use the Windows Snipping Tool.

**Comment by chrispwns** [comment]
![2](https://cloud.githubusercontent.com/assets/10478216/15032371/5f64e080-121d-11e6-8c65-67281ffcab72.png)
If by screen capture, do you mean screen shot? Yes, if you want a video of it in action I can do that too, but it won't be full res because that would take forever to load.

**Comment by Dyaxler** [comment]
Wait... it allows you to allocate 999mb of memory? That can't be right. Please change that to 128mb. You don't need anymore than that. I use over 86 mods and I've never gone over 76mb of usage while in game.

**Comment by chrispwns** [comment]
Same deal at 128mb, it shows the 3 errors. If it's something that just can't be fixed on my end that's no big deal, it's not entirely game breaking or anything.

**Comment by Dyaxler** [comment]
My concern is that you'll run into other issues with other mods. Not just Questie.

**Comment by chrispwns** [comment]
So far *most* of the mods have been okay, except for a few just wouldn't show up like a backport of elvui.

**Comment by Dyaxler** [comment]
Which other mods aren't "showing" up?

**Comment by Dyaxler** [comment]
You are running the wow client on a windows pc? Not in a VM or some other virtual environment?

**Comment by chrispwns** [comment]
elvui, a recount backport, and an omen threat meter backport. I assume it has something to do with them being backported, I put them in my addons as I usually would. Just wouldn't appear in my in game addons menu.

**Comment by Dyaxler** [comment]
As far as I know there isn't a viable back port for ElvUI. The closest one I could find is ShaguUI: http://shaguaddons.ericmauser.de/shaguui/

Same story with Recount and Omen. KTM has a decent threat meter: http://addons.us.to/addon/klhthreatmeter-0 and SWStats is what I use for damage meters: http://addons.us.to/addon/swstats

**Comment by chrispwns** [comment]
That explains it, but overall most other addons have been fine. I've mainly been using VanillaGuide, bongos, and Luna Unit Frames.

**Comment by Dyaxler** [comment]
Luna Unit Frames is a good addon. I hate Bongos...  :P never used VanillaGuide. Aside from Questie I think ShaguQuest is better then VanillaGuide.

This is a really bizarre issue you have. It's almost like something is corrupted. The fact that the OnUpdate function is throwing a nil error is what has got my troubleshooting ears perking up. This function shouldn't error at all. Matter of fact there are tons of mods that have an OnUpdate. I wonder if some of your client files have a "read-only" flag or some other weird file attribute attached to it. And you're sure you're running it as an "administrator"? You aren't running WINE in Linux or a VM?

**Comment by chrispwns** [comment]
I'm running on Windows 10, I don't use Linux for gaming because support.  As far as read only I know when I downloaded the file I went into properties and gave it full permissions since sometimes windows will "restrict" downloaded files.

**Comment by Dyaxler** [comment]
Good man; for checking the file permissions. I too am running Windows 10 so I know that's not an issue. Are you sure a virus scanner didn't flag any of the files? Sheesh, wouldn't that be hysterical but it's not beyond the realm of possibility.

Having an improperly patched client is not really a possibility since the server wouldn't even let you login. At least I wouldn't think so but you downloaded the same client I'm using so... huh. It's almost like Questie isn't loading into memory all the way... like something is getting blocked.

You could try this file. See if the OnUpdate error's again. I commented out the QuestAbandonWithItemsOnAccept code.
[Questie.zip](https://github.com/AeroScripts/QuestieDev/files/249778/Questie.zip)

**Comment by chrispwns** [comment]
The only Virus scanner I use is windows defender, everything else just send annoying updates and if you don't download trash outside of a virtual env you should be fine.

I'll try that file and report back. Thanks for sticking with me lol

**Comment by chrispwns** [comment]
That fixed it, weird.

**Comment by chrispwns** [comment]
I can even use slash commands and all now.

**Comment by Dyaxler** [comment]
Of course because the OnLoad is working now. :) When it encounters an error it stops processing the rest of the function...

Keep that file I gave you handy. I'm curious if you were to shut down your wow client and reinstall Questie without touching your WDB and WTF folders... I wonder if it'll work without issue. Maybe something needed to be cached before it could find the Blizzard QuestAbandonWithItems code.

**Comment by Dyaxler** [comment]
Now I have a hunch. I'm going to try and repro this...

**Comment by chrispwns** [comment]
Fresh install of questie without clearing gave me the indexing error with a nil value again.

**Comment by Dyaxler** [comment]
HUH... yeah I just tried with a fresh install of the WoW Client with just Questie and Improved Error frame. I completely deleted my WDB and WTF folders and logged in. No errors.

**Comment by chrispwns** [comment]
puzling. What exactly does abandon quests do? Just auto abandon old quests?

**Comment by Dyaxler** [comment]
There has GOT to be a logical explanation for this. However, you have a patched file now that works with your client. In the future if I update Questie you'll have to edit Questie.lua and search for this code and comment it out or delete it:

`QuestAbandonWithItemsOnAccept = nil;`

...and...

`QuestAbandonWithItemsOnAccept = StaticPopupDialogs["ABANDON_QUEST_WITH_ITEMS"].OnAccept;
	StaticPopupDialogs["ABANDON_QUEST_WITH_ITEMS"].OnAccept = function()
		local hash = Questie:GetHashFromName(QGet_AbandonQuestName());
		QuestieTrackedQuests[hash] = nil;
		QuestieSeenQuests[hash] = -1;
		if (TomTomCrazyArrow:IsVisible() ~= nil) and (arrow_objective == hash) then
			TomTomCrazyArrow:Hide()
		end
		Questie:AddEvent("CHECKLOG", 0.135);
		QuestAbandonWithItemsOnAccept();
	end`

All this code does is that it waits for the user to click the Accept button after the WoW Client fires the Blizzard function "ABANDON_QUEST_WITH_ITEMS" which fires off a popup dialog. There are two types of quests... one that requires a "Quest Item" (not a drop) to complete a quest and ones that don't. I think its fairly obvious which is which. :) If a player hits the accept button then it runs some code that is specific to Questie. Flags a quest as -1 which means it's been abondond and it clears the QuestArrow if the quest is currently being tracked via the Arrow and clears the tracking cache. Not running this code isn't SUPER critical. There are other "clean up" functions that will clean it up if the quest isn't flagged correctly. You might still see it on your map as either a ? or a ! ... the event handler has similar code for catching these types of quest events so it might catch it if this code doesn't fire. I wouldn't worry about it too much. :)

**Comment by chrispwns** [comment]
sweet, yeah I should have 0 issue commenting code out and I agree, anything programming/computer related has to have a logical explanation, the whole idea of algorithms are built from logic... this one is just hiding :p

Anyways, if I can use that and the addon will otherwise function that's no issue for me, a hell of a lot better than no addon for sure lol.

**Comment by Dyaxler** [comment]
Well an unsolved puzzle drives me nuts! I still want to figure it out but without a repro... I'm stuck. If you figure it out... please let me know. :)

**Comment by chrispwns** [comment]
For sure, if you ever decide you wanna teamviewer it let me know. I'll let you use my account and all :)

**Comment by Dyaxler** [comment]
I'm floating this issue by the original authors of Questie first. They might have an idea or two to try.

**Comment by chrispwns** [comment]
Sure, thanks for helping me out.
