### ISSUE TITLE
Quest issue with Marg Speaks 

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2302]
## Description

We only show 3 dots for where this pendant can drop. It's roughly the right area, but it's not the "good spots" where there are a high concentration of the mobs needed. Let's adjust the locations of these crab people. (=

## Wowhead link

* Marg Speaks - Quest - World of Warcraft || https://classic.wowhead.com/quest=1261/marg-speaks
* Jeweled Pendant - Item - World of Warcraft || https://classic.wowhead.com/item=5942/jeweled-pendant

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/90922301-64ea1380-e3b1-11ea-9ebe-fb87ca3c4945.png)

![image](https://user-images.githubusercontent.com/55365231/90922319-6adff480-e3b1-11ea-9058-fdcec994e7ee.png)

## Questie version

6.0.4

**Comment by AeroScripts** [comment]
Should be fixed as of 284802344100ca67b528fce5da881f52ae8d5960
