### ISSUE TITLE
Nelf Priest quest 5622 incorrectly flagged available at level 4, actually requires level 5.

### ISSUE THREAD

**Issue by teelolws** [AeroScripts/QuestieDev#2306]
## Description

Questie showing the quest available at level 4. Actually requires level 5.

## Wowhead link

https://classic.wowhead.com/quest=5622/in-favor-of-elune

## Screenshots

![image](https://user-images.githubusercontent.com/49792789/90968755-1caf2a80-e544-11ea-8501-a1e2b5cb0893.png)
![image](https://user-images.githubusercontent.com/49792789/90968758-2c2e7380-e544-11ea-9d20-2775ca51c6cf.png)

## Questie version

6.0.5

**Comment by drejjmit** [comment]
This actually is set to level 5 req in db. I have to test it ingame.

![image](https://user-images.githubusercontent.com/15526476/90988885-8d7f3280-e596-11ea-985a-02c239b7e886.png)

**Comment by teelolws** [comment]
Is the "Quest Level" overriding the "Required Level"?

**Comment by drejjmit** [comment]
Thanks for the report
Fixed with fbc8696f9e73cc11e2690332a2999fb8bd93d35e
