### ISSUE TITLE
Quest The Nightmare's Corruption

### ISSUE THREAD

**Issue by Stabbu** [AeroScripts/QuestieDev#2308]
Description
I'm on the quest The Nightmare's corruption. (farm 4 fragments at the Emerald Dream portals)
We farmed for the fragment in Feralas and Ashenvale and obtained both. We started farming in Hinterlands and the dragons don't show that they drop the fragment. When i go to my map i still see that in Ashenvale the fragment drops while i have that fragment in bags. I just want to be sure we are not farming Hinterlands in vein.
When i hoover over the Twilight Corruptor in Duskwood he doesnt say aswell that he drops the fragment i need.

So is this a bug? See screenshots

## Screenshots
![WoWScrnShot_082320_131641](https://user-images.githubusercontent.com/66034982/90977112-4e73c180-e543-11ea-9c5c-75201b549a82.jpg)
![WoWScrnShot_082320_131714](https://user-images.githubusercontent.com/66034982/90977115-53387580-e543-11ea-87b5-545174bf1272.jpg)

## Questie version

Which version of Questie are you using? v6.0.5

**Comment by drejjmit** [comment]
Same problem with this quest. Same objective name:
https://classic.wowhead.com/quest=4282/a-shred-of-hope

**Comment by BreakBB** [comment]
This is the output of `/dump C_QuestLog.GetQuestObjectives(8735)`:

![grafik](https://user-images.githubusercontent.com/33514570/94000243-35a33980-fd97-11ea-8235-1b286395486b.png)

This is the reason why Questie has problems with such quests, as the objectives are all "the same".

**Comment by BreakBB** [comment]
When adding all the possible NPCs to the 4 items results in this (with objective cluster = 1):

![grafik](https://user-images.githubusercontent.com/33514570/94014191-802eb100-fdab-11ea-8737-57566c95e4bb.png)

![grafik](https://user-images.githubusercontent.com/33514570/94014229-8b81dc80-fdab-11ea-9b9b-e50c1e1a4abe.png)

This shows at least the possible locations, but as soon as you fulfill one of the objective the location won't be removed. Not an ideal solution though.

**Comment by Djfe** [comment]
can't you add the index to the item (name) for identification?

**Comment by drejjmit** [comment]
Quest log only returns text "Fragment of the Nightmare's Cirruption: 0/1", no item id. Therefore we can only match by name, and since they all have the same name we can't know which is which.
This is only a problem with 2 quests in the game: [The Nightmare's Corruption](https://classic.wowhead.com/quest=8735/the-nightmares-corruption) and [A Shred of Hope](https://classic.wowhead.com/quest=4282/a-shred-of-hope)

**Comment by Djfe** [comment]
can't you id the order in which they are read in (for these quests)?
Or is the order not static?

also: I see an array with Indizes (1-4) above, isn't the code reading the array?

**Comment by BreakBB** [comment]
Yeah I was thinking about a way to add some extra code for "special" quests like these. Will most likely be easier (or maybe the only way) to fix stuff like this.
