### ISSUE TITLE
Cannot Track/ See Arrow

### ISSUE THREAD

**Issue by Zygga7** [AeroScripts/QuestieDev#231]
First time questie user here, am playing on a vanilla server and the only thing I can get questie to do is show available quests and nothing more. I've tried commands such as the questie clear config cmd and also the questie arrow and tracker cmd. I have had no luck getting it to work at all, and my quests are in English.

**Comment by Dyaxler** [comment]
This usually means that Quests aren't being found and recorded in the QuestieConfig table... or, after obtaining a quest you aren't actively tracking them. Try opening your quest log and "shift+clicking" a quest in the list. See if that pops your quest tracker.

**Comment by Zygga7** [comment]
Thank you for your prompt response. I have tried multiple times to Shift+click to try and toggle the tracker but its not working at all. It wont even show up under the mini-map in the top right like it usually does without Questie.

**Comment by Dyaxler** [comment]
Can you send me your !Questie.lua and addons.txt so I can look at the tables and addons? You might have a conflict of some kind. If you could also indicate in a PM or Email which server you're playing on... might be server related.

**Comment by Zygga7** [comment]
Hmm weird it wont let me upload the questie.lua even if in a zip folder. I did upload the addons.txt however. I have cartographer enabled for the time being to help me find things, but cut it off before trying to use questie each time. Also cant figure out how to pm to tell you what server xD went to your profile but did not see anything about sending a message or an email.
[AddOns.txt](https://github.com/AeroScripts/QuestieDev/files/246157/AddOns.txt)

**Comment by Dyaxler** [comment]
dyaxler at hotmail dot com

Questie is compatible with Cartographer by the way.

**Comment by Zygga7** [comment]
Ok sent bro.

**Comment by Zygga7** [comment]
My problem ended up being that I didnt know I was supposed to clear the cache in my WoW WDB folder. Hope this helps someone.
