### ISSUE TITLE
Quests not showing up on screen

### ISSUE THREAD

**Issue by Mogrann** [AeroScripts/QuestieDev#2314]
![WoWScrnShot_081120_172421](https://user-images.githubusercontent.com/70208150/91173855-d9c09480-e6b4-11ea-86a5-d2e1e3002ddd.jpg)
![WoWScrnShot_082520_092231](https://user-images.githubusercontent.com/70208150/91173888-e513c000-e6b4-11ea-96b2-b35ca67400fd.jpg)

## Questie version

I have attached a screenshot that shows the issue.  As you can see on this character I don't have a listing of my active quests.  On other characters Questie is working correctly.  I have deleted and reinstalled Questie, repaired Questie, read your FAQ, toggled options and clicked and unclicked the boxes.   My version is 6.0.5

**Comment by drejjmit** [comment]
Try untracking some quests you're not planning to do (Maybe some Silithus gear quests?). 
Tracker currently can't show more than 80 lines. Will be fixed for next release.

**Comment by Gogo1951** [comment]
Hey @Mogrann ,

Did tracking the quests fix the issue you were having? We safe to close this out?

**Comment by Mogrann** [comment]
Yes it did thank you so much
    On Friday, August 28, 2020, 07:05:26 a.m. ADT, Gogo1951 <notifications@github.com> wrote:  
 
 


Hey @Mogrann ,

Did tracking the quests fix the issue you were having? We safe to close this out?
