### ISSUE TITLE
Map features still using cpu cycles when disabled

### ISSUE THREAD

**Issue by cltnschlosser** [AeroScripts/QuestieDev#2317]
## Bug description
I'm trying to track down any sources of lag my addons may be causing, I found questie to be quiet high. I have coordinates and fade disabled for the minimap, and the big map is closed. QuestieMap and QuestieCoords are still using cpu cycles (nothing drastic in this case, but since these features are disabled, I wouldn't expect them to use anything).

## Screenshots
Profiler (This was taken standing still in SW bank):
![image](https://user-images.githubusercontent.com/1498529/91315954-e6f58600-e77d-11ea-9c1d-e6f49a99469e.png)
Minimap settings:
![image](https://user-images.githubusercontent.com/1498529/91316301-45baff80-e77e-11ea-9584-9a8b82868b9b.png)

## Questie version
v6.0.5

**Comment by Gogo1951** [comment]
This will likely be addressed as part of #2500  - closing this as it's not a stand-alone priority.
