### ISSUE TITLE
Add Quests Available to Tooltip for Quest Givers

### ISSUE THREAD

**Issue by eTzmNcbkrng** [AeroScripts/QuestieDev#2319]
I am a recent convert from Classic Codex and loving the extra features Questie offers, there is however one feature I miss from Classic Codex.

With Classic Codex, Mousing over a Quest Giver gives details about any Quests that NPC starts in the tooltip.  
I found this to be a very useful feature and am really missing it.  
I tried running a hybrid environment with both addons enabled (which gave no errors) but it also meant I had two entries for every objective tooltip so I had to abandon this.

Please consider adding Guest Giver information to NPC tooltips.

Thanks.

PS. Here is a screenshot showing Classic Codex' Quest Giver tooltips for a Quest I have not yet picked up.
![image](https://user-images.githubusercontent.com/26512802/91522554-a6009b80-e94e-11ea-9acb-5dca0fa346fa.png)

**Comment by Gogo1951** [comment]
Hey @eTzmNcbkrng ,

Welcome to the party! Shame Classic Codex is no longer being supported, it had some good ideas.

We'll see what we can do about adding this in a future patch.

Cheers!

**Comment by BreakBB** [comment]
Listing to the `UPDATE_MOUSEOVER_UNIT` event will do the trick for this. Maybe this isn't even needed when looking at the `TooltipShowing_unit` method of the [Tooltip.lua](https://github.com/AeroScripts/QuestieDev/blob/0c175ca08aa70cc7746585b17dd6867f623cd0c6/Modules/Tooltips/Tooltip.lua#L267).
