### ISSUE TITLE
Quest Issue with "Another Message to the Wildhammer"

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2320]
## Description

Hey @drejjmit , good news! Horde don't have to kill only the Alliance Griffons to get these feathers! I mean, we still should, but we don't have to. (= They drop all over. Good to update since we have a bunch of quests that send us back and forth between Feralas and Hinterlands, and we can farm these as we go between the two zones. They've got a pretty shit drop rate, so listing more sources will be helpful. 

## Wowhead link

* Another Message to the Wildhammer - Quest - World of Warcraft || https://classic.wowhead.com/quest=7842/another-message-to-the-wildhammer
* Long Elegant Feather - Item - World of Warcraft || https://classic.wowhead.com/item=4589/long-elegant-feather

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/91547850-204b0480-e8ea-11ea-83bc-a2e4e23379c5.png)

**Comment by drejjmit** [comment]
We already have all those NPCs as drop? Same as Wowhead.
```[4589]={"Long Elegant Feather",{7842},{2347,2473,2474,2651,2657,2658,2659,5300,6375},{}},```
Since it's far away it's probably on a high cluster level tho.

**Comment by Gogo1951** [comment]
Doesn't show up in tooltips though for those other mobs. Any ideas?

**Comment by Gogo1951** [comment]
Looks like it's in the new DB, with drop chances! Cool!

> [4589] = {0,1,0,{{2651,9.42},{2347,42.86},{2473,46.03},{2474,34.73},{2657,40.19},{2658,38.78},{2659,38.83},{5300,27.68},{6375,35.61},},nil,nil,nil,nil,"Long Elegant Feather"},
