### ISSUE TITLE
Quest issue with "Improved Quality"

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2321]
## Description

There's an incorrect dot off to the south, the Yeti Hides in question for this quest only drop in the cave up north.

## Wowhead link

* Improved Quality - Quest - World of Warcraft || https://classic.wowhead.com/quest=7734/improved-quality
* Improved Quality - Quest - World of Warcraft || https://classic.wowhead.com/quest=7733/improved-quality

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/91551096-4030f700-e8ef-11ea-9f2e-6f7c17b715b7.png)

**Comment by drejjmit** [comment]
Use Quest ids and hold shift!

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/91551402-b3d30400-e8ef-11ea-9092-ffa17e6a6ab6.png)

These guys are the spawns for the previous quest in the chain.

**Comment by drejjmit** [comment]
Thanks. That helps 👍. Now i know it's the Lurking Feral Scar

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/91552146-edf0d580-e8f0-11ea-8bed-3c0d9094d97f.png)

They don't drop it (=

**Comment by drejjmit** [comment]
Fixed with 6471748bfb300b3f39ff719b96184a40f0a81c2c
