### ISSUE TITLE
Quest issue with "Perfect Yeti Hide"

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2322]
## Description

This quest isn't showing on the map; we could give it the same treatment as Talking Head or Parts of the Swarm I think. It's just the yetis in the gave that drop this, so the ! should all be in one spot.

## Wowhead link

* Perfect Yeti Hide - Quest - World of Warcraft || https://classic.wowhead.com/quest=7738/perfect-yeti-hide
* Perfect Yeti Hide - Item - World of Warcraft || https://classic.wowhead.com/item=18972/perfect-yeti-hide

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/91553397-f1855c00-e8f2-11ea-8096-35c4e15f9922.png)

## Questie version

6.0.5

**Comment by drejjmit** [comment]
Both Horde and Alliance version shows up for me:

![image](https://user-images.githubusercontent.com/15526476/91648167-72b03080-ea64-11ea-8886-301b97887134.png)

**Comment by Gogo1951** [comment]
I don't think it should be tagged as a repeatable quest. It's not repeatable.

**Comment by Gogo1951** [comment]
Oof, it is repeatable. Thanks!
