### ISSUE TITLE
Alliance Class Quest Mage - Pristine Spider Silk

### ISSUE THREAD

**Issue by ixidion** [AeroScripts/QuestieDev#2323]
## Description
The Quest [Pristine Spider Silk](https://classic.wowhead.com/quest=1940/pristine-spider-silk) says the Silk drops from Carrion Recluse, but nothing else.

It does NOT drop from: https://classic.wowhead.com/npc=930/black-widow-hatchling - as Questie/Wowhead states.

Please can a mage player verify this, because it was a notice from a player in /1.

## Wowhead link
https://classic.wowhead.com/quest=1940/pristine-spider-silk

## Questie version
6.0.5

**Comment by drejjmit** [comment]
They do drop from Black Widow Hatchlings
![image](https://user-images.githubusercontent.com/15526476/91648115-e7cf3600-ea63-11ea-97a2-69b75e6b8092.png)
