### ISSUE TITLE
Quest issue with "WANTED: Caliph Scorpidsting"

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2324]
## Description

Caliph Scorpidsting needs a pat. 

## Wowhead link

* WANTED: Caliph Scorpidsting - Quest - World of Warcraft || https://classic.wowhead.com/quest=2781/wanted-caliph-scorpidsting

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/91618920-638c8e00-e951-11ea-9b23-dc8d0391a817.png)

**Comment by drejjmit** [comment]
Already has waypoints
```{[440]={{61.59,38.24},{61.29,38.9},{60.99,39.44},{60.99,39.44},{60.8,39.74},{60.44,40.36},{60.44,40.36},{60.1,40.92},{59.86,41.28},{59.62,41.51},{59.44,41.28},{59.36,41.07},{59.24,40.76},{59.13,40.42},{59.03,40.16},{58.99,39.85},{58.96,39.54},{58.9,39.26},{58.86,38.98},{59.24,38.57},{59.36,38.38},{59.77,37.71},{59.77,37.71},{59.95,37.1},{59.98,37.01},{60.35,36.9},{60.62,36.7},{60.74,36.36},{60.88,35.95},{60.96,35.9},{61.52,35.56},{61.66,35.41},{61.74,35.03},{61.88,34.63},{61.88,34.63},{62.09,34.3},{62.27,33.94},{62.45,33.57},{62.62,33.19},{62.79,32.81},{62.82,32.82},{63.11,32.95},{63.36,32.8},{63.48,32.37},{63.61,32.03},{63.61,32.03},{63.51,32.64},{63.51,33.12},{63.5,33.4},{63.29,34.1},{63.16,34.52},{63.12,34.83},{63.12,34.83},{63.17,35.26},{63.19,35.71},{63.19,35.71},{63.22,36.28},{63.22,36.28},{63.25,36.64},{63.27,36.91},{63.3,37.16},{63.34,37.38},{63.42,37.6},{63.23,37.48},{63.07,37.52},{62.91,37.51},{62.7,37.39},{62.51,37.59},{62.4,37.82},{62.26,38.03},{62.12,38.15},{61.96,38.18},{61.83,38.2},},}```
Try again with latest master

**Comment by Gogo1951** [comment]
Looks good.
