### ISSUE TITLE
Quest links should request additional info from the sender when opened

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#2327]
This was planned for a while but there was no issue made for it yet

Basically, when opening a quest link in chat, questie should send an addon whisper message to the sender to request stuff like the amount of players in their group, and their progress

**Comment by Gogo1951** [comment]
What's the value for a user on this one? Just trying to understand the use case for it.

**Comment by Gogo1951** [comment]
Seems like low ROI. Let's close it and re-open in the future if still needed.
