### ISSUE TITLE
Option to display townsfolk on the map/minimap

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#2329]
Similar to what we have in retail wow, a dropdown to select different kinds of townsfolk (repair, reagents, mailboxes etc)

We could also have a few extra ones like "my professions" to show profession trainers that you can train at, and "pet food" to show vendors that sell food your pet can eat

We could also put toggles for different types of questie icons in the dropdown

**Comment by AeroScripts** [comment]
I just realized this is a duplicate of #2282 oops

**Comment by Kazenokamii** [comment]
I can't find the option to disable this new feature...

**Comment by egorpugin** [comment]
@AeroScripts 
Is it possible to hidfe mailboxes/flight masters on map and minimap?

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/105432859-1b327d00-5c1e-11eb-8381-17560a05276b.png)

Turn it off in the mini-map menu.

**Comment by egorpugin** [comment]
Oops, thank you.
I played without minimap button and there are no alternative switches in menu.

**Comment by drejjmit** [comment]
> Oops, thank you.
> I played without minimap button and there are no alternative switches in menu.

There is. 
Just press ``Config Tracking Icons`` in General options.

**Comment by egorpugin** [comment]
Oops again, sorry!
