### ISSUE TITLE
Button to swap between Options and Journey

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#2331]
Add a button in Questie Options to swap window to Journey and vice versa.
If it gets even 1 person to discover Journey it's a win 😃

**Comment by BreakBB** [comment]
I think this was already proposed a few month ago, but got lost. It is a really good idea though and easy to add :grin:

**Comment by AeroScripts** [comment]
The default functionality of left click will be changed with #2329 too so it will be even more important to have options for that

Both should be more intuitive to access when that happens too because we can add "open options" and "open journey" to the top of the menu
