### ISSUE TITLE
Questie Tracker

### ISSUE THREAD

**Issue by Aneko1** [AeroScripts/QuestieDev#2338]

**Comment by drejjmit** [comment]
We need more information. Please make a new issue if you have any problems.

**Comment by Aneko1** [comment]
Hello, I'm having an issue with the quest tracker portion of questie v6.0.5. Currently it is not showing any of the quests in my log(my log is full). when I hover my mouse over the header, I get the following error message:

Message: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:1906: attempt to index field '?' (a nil value)
Time: Thu Sep  3 11:48:11 2020
Count: 1
Stack: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:1906: attempt to index field '?' (a nil value)

Locals: 

**I have also tried disabling all my addons and only having questie enabled. I still get the same issue but with a longer error message:**
![WoWScrnShot_041220_005731](https://user-images.githubusercontent.com/5566162/92156279-987b6380-eddd-11ea-8042-2088a5ed218d.jpg)
![WoWScrnShot_090320_115930](https://user-images.githubusercontent.com/5566162/92156389-bea10380-eddd-11ea-837d-75fd3561d33f.jpg)



Message: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:1906: attempt to index field '?' (a nil value)
Time: Thu Sep  3 11:48:11 2020
Count: 1
Stack: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:1906: attempt to index field '?' (a nil value)

Locals:

**Comment by drejjmit** [comment]
Try untracking some quests. Fixed for next release.

**Comment by Gogo1951** [comment]
There's a fix for this coming in the next release.
