### ISSUE TITLE
Quest issue with "Cuergo's Gold"

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2339]
## Description

The objective is missing for Cuergo's Gold. Maybe because you trigger the mob spawn who drops the item? Let's just put it on the object that triggers the mob spawn.

## Wowhead link

* Cuergo's Gold - Quest - World of Warcraft || https://classic.wowhead.com/quest=2882/cuergos-gold

## Screenshots

Github needs to get with the times. =P

![image](https://user-images.githubusercontent.com/55365231/92184444-dba5f880-ee16-11ea-98ad-37dc28e53ec5.png)

**Comment by drejjmit** [comment]
Quest item:
[9275] = {"Cuergo's Key",2112,nil,{7902,7901,7899,},nil,nil,nil,nil,},

All these have spawn points:
        [7899] = {
            [npcKeys.name] = "Treasure Hunting Pirate",
            [npcKeys.zoneID] = zoneIDs.TANARIS,
            [npcKeys.spawns] = {[zoneIDs.TANARIS] = {{54.45,93.47},},},
        },
        [7901] = {
            [npcKeys.name] = "Treasure Hunting Swashbuckler",
            [npcKeys.zoneID] = zoneIDs.TANARIS,
            [npcKeys.spawns] = {[zoneIDs.TANARIS] = {{54.4,93.5},},},
        },
        [7902] = {
            [npcKeys.name] = "Treasure Hunting Buccaneer",
            [npcKeys.zoneID] = zoneIDs.TANARIS,
            [npcKeys.spawns] = {[zoneIDs.TANARIS] = {{54.34,93.58},},},
        },

**Comment by drejjmit** [comment]
Works for me
![image](https://user-images.githubusercontent.com/15526476/92217932-a8a44900-ee98-11ea-9d4b-178143788c44.png)

**Comment by Gogo1951** [comment]
It's flagged as repeatable. Ok, I guess it is. Thanks!
