### ISSUE TITLE
Getting FPS lag when mousing over mobs.

### ISSUE THREAD

**Issue by futscdav** [AeroScripts/QuestieDev#234]
Title says it.

Started seemingly randomly, as it was fine before. I had been using questie for about 4 days (levels 18-25), and now when I mouseover an npc, the game skips a frame or two (with i7-4790k, no lua error, probably just some extremelly unnecessary computation).

Tried resetting config, NUKEing, deleting WTF, recopying addon files Nothing fixed it.

**Comment by Dyaxler** [comment]
It's not Questie... it's the WoW client. This tooltip issue has existed for a long time. Check out some of the old Blizzard Forum posts about it.

**Comment by futscdav** [comment]
Aha ok, is there any fix then? Does reinstall help?

**Comment by Dyaxler** [comment]
The only thing I came across to mitigate the issue is to keep the number of mods that modifies the tooltip to a min and empty your WDB cache when it starts to become noticeable.

**Comment by futscdav** [comment]
After turning in the quest Items of some consequence, the lag went away. So I suppose it's the part that required Silk Cloth as so many mobs can drop it?
