### ISSUE TITLE
Soul Ashes of the Banished

### ISSUE THREAD

**Issue by isitLoVe** [AeroScripts/QuestieDev#2344]
## Description
Not all mobs are showing up dropping the quest item https://classic.wowhead.com/item=22229/soul-ashes-of-the-banished  
For instance https://classic.wowhead.com/npc=7068/condemned-acolyte is missing

## Wowhead link
https://classic.wowhead.com/quest=8988/more-components-of-importance

## Screenshots
![WoWScrnShot_090620_000846](https://user-images.githubusercontent.com/20051956/92314209-4d2ba580-efd5-11ea-963a-182282c62b74.jpg)

## Questie version
Version: 6.0.5

**Comment by drejjmit** [comment]
Thanks for the report. Will be added for next release.
