### ISSUE TITLE
The Left Piece of Lord Valthalak's Amulet (Stratholme)

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#2345]
## Description

This part of the T0.5 Quest happens in Stratholme, but there is no marker for it on Stratholme.
There are 3 other variants of this quest happening in other instances.
So 4 quests and you get assigned one of them.

Later down the quest line the same thing again for the right side of the amulett: one of 4 quests.

## Wowhead link

https://classic.wowhead.com/quest=8968/the-left-piece-of-lord-valthalaks-amulet

## Questie version

6.0.5

**Comment by drejjmit** [comment]
Thanks for the report. 
Fixed with 192b391302dcd8544e738183848834ce48aa461f.
Will be included in next release.
