### ISSUE TITLE
Missing event data for Objective: Destroy the Demon Seed

### ISSUE THREAD

**Issue by Big-Gaz** [AeroScripts/QuestieDev#2347]
## Bug description
Gave Example Collar to Neeru Fireblade in Cleft of Shadow to complete "Neeru Fireblade" quest. Neeru offered "Ak'Zeloth" quest, I accepted it and following message appeared:
[ERROR] Missing event data for Objective: Destroy the Demon Seed id: nil

## Screenshots
See chat log:
![World Of Warcraft - Classic Screenshot 2020 09 08 - 10 54 43 28](https://user-images.githubusercontent.com/24977745/92462641-a60c6100-f1c2-11ea-8ce2-16353c5e55a4.png)

## Questie version
v6.0.5

**Comment by drejjmit** [comment]
Thanks for the report.
Will be included in next release.
