### ISSUE TITLE
Quest issue with "A Reliquary of Purity"

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2349]
## Description

This quest shows up as available, but it's not. Need to figure out what the actual prerequisites are. Spoke with the guy, no dialogue or quest is available. Tested on a 55 Troll Hunter.

Looks like you have to go into DM before the quest is available. Oof. Testing that out now.

> Confirmed. My Undead Rogue was unable to get the chat option to start the quest until after I had entered the Dire Maul instance once (tested with another character to be sure).
> https://classic.wowhead.com/quest=5527/a-reliquary-of-purity#comments:id=2968386

## Wowhead link

* A Reliquary of Purity - Quest - World of Warcraft || https://classic.wowhead.com/quest=5527/a-reliquary-of-purity

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/92608984-a3217700-f27b-11ea-9774-efdba530ef36.png)

**Comment by drejjmit** [comment]
It will have to be like this unless someone finds the trigger to check for.

**Comment by Gogo1951** [comment]
I zoned into DM, and presto this quest is available. Oof. Going to close this as we don't have a trigger for uncovering a map / zoning into a dungeon to make a quest available. Just something to be aware of if anyone ever opens a ticket for this again.

**Comment by drejjmit** [comment]
We could check for ``fileDataIDs = 271687`` in ``/Dump C_MapExplorationInfo.GetExploredMapTextures(1444)``

**Comment by BreakBB** [comment]
@drejjmit Should we reopen this? It will be another special handling for one quest, but your idea looks like it could work. But maybe it is not worth it
