### ISSUE TITLE
Qustie raise error with unknown quest completion.

### ISSUE THREAD

**Issue by rasberryrabbit** [AeroScripts/QuestieDev#235]
I got error with "Captain Sander's Hidden treasure" quests.

![wowscrnshot_050816_115145](https://cloud.githubusercontent.com/assets/11563461/15095809/0cb870da-1516-11e6-9e1d-d1f95935495d.png)

Each quest completion raise error in QuestQuest.lua line 37,

`        local req = nil;
        if QuestieHashMap[questhash] then 
            req = QuestieHashMap[questhash]['rq'];
        end
`

I changed with this, no more errors.

**Comment by Dyaxler** [comment]
Hmmm.... interesting. I recently done this quest and didn't get that error. But there is no harm in nil'ing out the req variable before setting it. 

I have noticed that depending on which "server core" is used... Questie can behave in strange ways. They all have their little quirks. I'll have to investigate further before permanently incorporating this into the next release.

**Comment by Dyaxler** [comment]
This fix will be in version 3.1

**Comment by rasberryrabbit** [comment]
Thank you :)
