### ISSUE TITLE
Issue with Quest with Missing Objective that Causes WoW to Crash

### ISSUE THREAD

**Issue by Xzecuter** [AeroScripts/QuestieDev#2350]
Hey, I keep getting this error when I launch the game. Also when I try to do anything in the Questie addon interface, the game crashes. All of this started happening after the latest update.

Date: 2020-09-09 17:23:38
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\Libs\QuestieLib.lua line 309:
   Usage: NonEmptyItem:ContinueOnLoad(callbackFunction)
Debug:
   [C]: ?
   [C]: error()
   ..\FrameXML\ObjectAPI\Item.lua:235: ContinueOnItemLoad()
   Questie\Modules\Libs\QuestieLib.lua:309: CacheItemNames()
   Questie\Modules\Libs\QuestieLib.lua:295: CacheAllItemNames()
   ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:117:
      ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:115
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Ace3, v
  AceGUI30SFXWidgets, v1.0.1
  AdiBags, vv1.9.20-classic
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.9.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicAuraDurations, v1.13.61
  ClassicCastbars, v1.3.12
  ClassicCastbarsOptions, v
  DBMCore, v1.13.59
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4160
  EZJunk, v1.0.1
  FishingBuddy, v0.7.3 Beta 7
  GatherMate2, v1.45.5
  GroupBulletinBoard, v2.42
  GroupCalendar, v
  GTFO, v4.55
  HealCommClassic, v
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixPlus, v1.13.78
  Masque, v8.3.0
  NovaWorldBuffs, v1.79
  OmniCC, v8.3.6
  Prat30, v3.8.26
  Prat30Libraries, v
  Questie, v6.0.5
  Recount, vv1.13.5b
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.1.1
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TankWarningsClassic, v1.1.9(BETA)
  ThreatClassic2, v2.24
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLocation, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRegen, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  VendorPrice, v1.3.6
  VuhDo, v3.113-classic
  VuhDoOptions, v3.113-classic
  WeaponSwingTimer, v4.1.0
  ZPerl, v5.9.8
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_ruRU v1.13.5.11305 <none>
  (ck=920)

Date: 2020-09-09 17:23:41
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\QuestieStream.lua line 296:
   bad argument #1 to 'stringchar' (number expected, got nil)
Debug:
   [C]: ?
   [C]: ?
   Questie\Modules\QuestieStream.lua:296: ReadShortString()
   Questie\Database\compiler.lua:101: ?()
   Questie\Database\compiler.lua:929: QueryQuest()
   Questie\Database\Zones\zoneDB.lua:101: GetZonesWithQuests()
   ...ce\AddOns\Questie\Modules\Journey\QuestieJourney.lua:31: Initialize()
   ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:129:
      ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:124
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Ace3, v
  AceGUI30SFXWidgets, v1.0.1
  AdiBags, vv1.9.20-classic
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.9.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicAuraDurations, v1.13.61
  ClassicCastbars, v1.3.12
  ClassicCastbarsOptions, v
  DBMCore, v1.13.59
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4160
  EZJunk, v1.0.1
  FishingBuddy, v0.7.3 Beta 7
  GatherMate2, v1.45.5
  GroupBulletinBoard, v2.42
  GroupCalendar, v
  GTFO, v4.55
  HealCommClassic, v
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixPlus, v1.13.78
  Masque, v8.3.0
  NovaWorldBuffs, v1.79
  OmniCC, v8.3.6
  Prat30, v3.8.26
  Prat30Libraries, v
  Questie, v6.0.5
  Recount, vv1.13.5b
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.1.1
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TankWarningsClassic, v1.1.9(BETA)
  ThreatClassic2, v2.24
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLocation, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRegen, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  VendorPrice, v1.3.6
  VuhDo, v3.113-classic
  VuhDoOptions, v3.113-classic
  WeaponSwingTimer, v4.1.0
  ZPerl, v5.9.8
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_ruRU v1.13.5.11305 <none>
  (ck=920)

**Comment by Gogo1951** [comment]
Hey @Xzecuter ,

I'm not able to reproduce this issue issue, but there are a lot of other addons in your list. Possible one or more of them has a conflict. The trouble is, a lot of addons aren't being well maintained, and so making sure Questie always works when some other add-ons interfere with it can burn a lot of dev hours. Really hard to prioritize that work over new feature dev, I'm sure you understand. (=

If you disable all the other add-ons other than Questie, do you have the same issue? You can try enabling in batches to see which is causing the conflict. Make sure they are all up-to-date, and try and migrate away from addons that are no longer supported as quickly as you can. Best advice I can give.

Will keep this open for a few days, please let us know if you find the conflicted add-on. Thanks!

**Comment by Xzecuter** [comment]
Hey @Gogo1951 

I have disabled all addons except Questie, but the game still keeps crashing when I use the addon. Also, I forgot to mention that there are no markers most of the time (some of them appear at random intervals) and the quest log is missing.

**Comment by Gogo1951** [comment]
Hey @Xzecuter ,

Message me on the Questie discord? Happy to chat through this with you and see if we can find a solution.

**Comment by Xzecuter** [comment]
Here is the screenshot requested, along with the quest ID`s 
![Untitled](https://user-images.githubusercontent.com/71023854/92636855-badf1680-f2e0-11ea-96fd-822f527e6c8f.png)

https://classic.wowhead.com/quest=8790/imperial-qiraji-regalia
https://classic.wowhead.com/quest=8789/imperial-qiraji-armaments
https://classic.wowhead.com/quest=8697/ring-of-infinite-wisdom
https://classic.wowhead.com/quest=8689/shroud-of-infinite-wisdom
https://classic.wowhead.com/item=21410/gavel-of-infinite-wisdom
https://classic.wowhead.com/quest=4742/seal-of-ascension
https://classic.wowhead.com/quest=8288/only-one-may-rise
https://classic.wowhead.com/quest=8916/an-earnest-proposition
https://classic.wowhead.com/quest=8572/veterans-battlegear
https://classic.wowhead.com/quest=8548/volunteers-battlegear
https://classic.wowhead.com/quest=8573/champions-battlegear
https://classic.wowhead.com/quest=9023/the-perfect-poison
https://classic.wowhead.com/quest=8348/signet-of-the-dukes
https://classic.wowhead.com/quest=8731/field-duty
https://classic.wowhead.com/quest=8574/stalwarts-battlegear

Hope this helps.

**Comment by Gogo1951** [comment]
After chatting with @Xzecuter I see the issue. I think there's a problem with one of the quests that he's on. He's going to send over a list of quests so we can investigate.

**Comment by Gogo1951** [comment]
Hey @AeroScripts or @drejjmit ,

Either of you have time to look into this one?

**Comment by AeroScripts** [comment]
Will look into this now, looks like there's some locale conflict with the compiler, might be a character encoding issue

**Comment by AeroScripts** [comment]
```
Questie\Modules\QuestieStream.lua:296: ReadShortString()
Questie\Database\compiler.lua:101: ?()
Questie\Database\compiler.lua:929: QueryQuest()
Questie\Database\Zones\zoneDB.lua:101: GetZonesWithQuests()
```
According to this part of the error, its trying to read objective text even though that's not being requested, which could only happen if you have a partially broken install.

Are you sure you don't have some partly broken copy of questie somewhere in your addons folder?


Can you try running this macro ingame
```
/script QuestieConfig.dbIsCompiled = false;ReloadUI()
```
And see if you get errors from that during DB compile?

**Comment by Xzecuter** [comment]
The macro worked, There are no more error messages, and Questie is working :)

Thanks for the help.

**Comment by AeroScripts** [comment]
oh sweet <3

**Comment by AeroScripts** [comment]
I'm going to add a message box in the next update if this happens again, with a button to recompile which should hopefully prevent issues like this in the future
