### ISSUE TITLE
Auto accept/auto turn in not working properly

### ISSUE THREAD

**Issue by Laoina** [AeroScripts/QuestieDev#2352]
First I double checked that my addons are up to date. Next I have gone onto all of my characters and turned OFF the auto accept auto turn in for quests.  I have restarted the game. I have turned off questie completely. I have tried everything. Quests continue to auto accept/auto turn in.

**Comment by drejjmit** [comment]
Check Leatrix Plus ``/ltp`` and uncheck "Automate quests".
