### ISSUE TITLE
Questie bug on only on toon

### ISSUE THREAD

**Issue by Warlodude** [AeroScripts/QuestieDev#2355]
i love the addon.. but lately my hunter hasnt been able to use it... it doesnt show quests or anything... iv restarted it.. updated it... and its working with all my other characters EXCEPT my hunter... is there some i can do ( without having to delete my character or the addon)

**Comment by drejjmit** [comment]
Map/Minimap or Tracker not showing quests?

**Comment by Warlodude** [comment]
map/mini map are not show anything.

**Comment by drejjmit** [comment]
Did you try "Reset Questie" in Advanced Options? This will only clear settings, not Journey or completed quests.

**Comment by Warlodude** [comment]
Is that done in game?

**Comment by drejjmit** [comment]
Yes. ``/questie`` then go to Advanced.

**Comment by Warlodude** [comment]
Just did it. And it is now working! Thank you so much for your help.

**Comment by wyspir1566** [comment]
I'm having the same problem, questie doesn't show on my warrior even after reinstalling fresh but shows for all my other characters.  I tried resetting questie and it still doesn't work.
