### ISSUE TITLE
Azuregos's Magical Ledger - no question mark in Azshara

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#2359]
## Description

There is no question mark on the map in azshara where Azuregos's Spirit is.
This quest is available after you finished a quest in tanaris by talking to Anachronos. (The Charge of the Dragonflights)
The other two quests (Eranikus in Moonglade and Vaelastrasz in Blackrock) are marked on the map.

## Wowhead link

https://classic.wowhead.com/quest=8575/azuregoss-magical-ledger

## Questie version

6.0.5

**Comment by drejjmit** [comment]
Thanks for the report.
Fixed with 39570b80556632ebd93e3a139a8f2675fbf9c37d. Will be included in next release.

**Comment by Djfe** [comment]
Hi that was quick ^^
was the following fixed as well? @drejjmit 
https://classic.wowhead.com/quest=8733/eranikus-tyrant-of-the-dream
this quest starts in the tempel instance (of atal'hakkar) not in moonglade

**Comment by drejjmit** [comment]
Malfurion with that NPC id is there during the Eranikus fight. But since you're not picking up/turning in any quests to that version of Malfurion i guess he can be removed from Moonglade. I also added spawn location for "Number Two".

**Comment by Djfe** [comment]
I just realized that there already is an exclamation mark in the swap of sorrows, just not on top of the tempel on the map ^^ (it's on top of the entry of the instance which is offset north-east to the lake) other instance quests like morphaz blood are displayed on top of the lake.

**Comment by drejjmit** [comment]
I changed ``[zoneIDs.SWAMP_OF_SORROWS] = {{77.32,35.98}`` to ``[zoneIDs.THE_TEMPLE_OF_ATAL_HAKKAR] = {{-1,-1}`` already so it should show at 69.4, 56.8 (Entrance of the Temple) now.

**Comment by Djfe** [comment]
yep, I just wanted to mention that there might be a marker there already for malfurion. (around 75,37 or so) in 6.0.5

another part of the bang a gong quest chain:
finishing the quest https://classic.wowhead.com/quest=8599/love-song-for-narain
allows you to get the buff siren's song from meridith

it's not exactly a quest, but you need the buff to reach the island south of there (off the map) for the next quest, so maybe she ought to get an exclamation mark after all

**Comment by Djfe** [comment]
the actual quest then starts at 59.2, 99.7 but the zone is south seas ("Die südlichen Meere")

```/dump C_Map.GetBestMapForUnit("player")``` returns ```[1]=1446```

![WowClassic_2020-09-20_05-21-29](https://user-images.githubusercontent.com/5685512/93693522-2acf7700-fb01-11ea-8ecd-39e805a34076.jpg)
