### ISSUE TITLE
Quest tracker not adding quests automatically

### ISSUE THREAD

**Issue by akanimh** [AeroScripts/QuestieDev#236]
Automatic Quest Tracking is checked under Interface Options. I've disabled all other mods, and ran Questie 3.0 solo. I've also ran the /questie NUKE command a few different times. Picking up quests still doesn't add them to the tracker automatically. Am I missing something?

**Comment by Dyaxler** [comment]
Look in !Questie.lua in your characters WTF directory... if you see an entry like this...

> QuestieTrackedQuests = {
> 	[671885097] = {
> 		["leaderboards"] = 0,
> 		["arrowPoint"] = {
> 			["hash"] = 671885097,
> 			["c"] = 2,
> 			["dist"] = 1.537153051749279,
> 			["yDelta"] = 0.3241300615772821,
> 			["xDelta"] = -1.502590831758276,
> 			["y"] = 0.2982,
> 			["x"] = 0.3996,
> 			["title"] = "|cFFFFFF00[12] |rThe Tome of Divinity",
> 			["z"] = 17,
> 		},
> 		["level"] = 12,
> 		["tracked"] = true,
> 		["questName"] = "The Tome of Divinity",
> 	},

...then something else is preventing the tracker from appearing. Are you on an English server? Which server are you playing on?

**Comment by akanimh** [comment]
Kronos 2,

Here's my lua:
`
QuestieSeenQuests = {
	[934255773] = 1,
	[1905147592] = 1,
	[492876965] = 0,
	[3184761309] = 0,
	[1843465797] = 1,
	[1453840085] = 0,
	[688250421] = 1,
	[2028259693] = 0,
	[1865263941] = 1,
	[3815619821] = 1,
}
QuestieTrackedQuests = {
	[2028259693] = {
		["objective1"] = {
			["notes"] = {
			},
			["type"] = "monster",
			["desc"] = "Ice Claw Bear slain: 0/6",
		},
		["tracked"] = true,
		["arrowPoint"] = {
			["hash"] = 2028259693,
			["c"] = 2,
			["dist"] = 114.9852403437755,
			["yDelta"] = -86.0458965710132,
			["xDelta"] = -76.27390890865834,
			["y"] = 0.4335,
			["x"] = 0.2878,
			["title"] = "|cFFFFFF00[8] A Favor for Evershine|r",
			["z"] = 7,
		},
		["objective2"] = {
			["notes"] = {
			},
			["type"] = "monster",
			["desc"] = "Elder Crag Boar slain: 0/8",
		},
		["questName"] = "A Favor for Evershine",
		["level"] = 8,
		["objective3"] = {
			["notes"] = {
			},
			["type"] = "monster",
			["desc"] = "Snow Leopard slain: 0/8",
		},
		["leaderboards"] = 3,
	},
	[3184761309] = {
		["leaderboards"] = 0,
		["isComplete"] = 1,
		["questName"] = "Bitter Rivals",
		["level"] = 6,
		["arrowPoint"] = {
			["hash"] = 3184761309,
			["c"] = 2,
			["dist"] = 882.4059300953579,
			["yDelta"] = 219.9607625110174,
			["xDelta"] = 854.5510449487646,
			["y"] = 0.5267,
			["x"] = 0.4768,
			["title"] = "|cFFFFFF00[6] Bitter Rivals|r",
			["z"] = 7,
		},
		["tracked"] = true,
	},
	[492876965] = {
		["objective1"] = {
			["notes"] = {
			},
			["type"] = "event",
			["desc"] = "Fully explore Frostmane Hold",
		},
		["tracked"] = true,
		["objective2"] = {
			["notes"] = {
			},
			["type"] = "monster",
			["desc"] = "Frostmane Headhunter slain: 0/5",
		},
		["questName"] = "Frostmane Hold",
		["level"] = 9,
		["arrowPoint"] = {
			["hash"] = 492876965,
			["c"] = 2,
			["dist"] = 326.29917524895,
			["yDelta"] = 168.0840971301584,
			["xDelta"] = -279.6763988256508,
			["y"] = 0.5109,
			["x"] = 0.2465,
			["title"] = "|cFFFFFF00[9] Frostmane Hold|r",
			["z"] = 7,
		},
		["leaderboards"] = 2,
	},
	[1453840085] = {
		["objective1"] = {
			["notes"] = {
			},
			["type"] = "item",
			["desc"] = "Shimmerweed: 0/6",
		},
		["leaderboards"] = 1,
		["questName"] = "The Perfect Stout",
		["level"] = 9,
		["tracked"] = false,
	},
}
QuestieConfig = {
	["minLevelFilter"] = false,
	["maxShowLevel"] = 3,
	["getVersion"] = 3,
	["alwaysShowDistance"] = false,
	["boldColors"] = false,
	["arrowEnabled"] = true,
	["showMapAids"] = true,
	["trackerEnabled"] = true,
	["showProfessionQuests"] = false,
	["minShowLevel"] = 5,
	["alwaysShowQuests"] = true,
	["resizeWorldmap"] = false,
	["alwaysShowLevel"] = true,
	["showTrackerHeader"] = false,
	["trackerList"] = false,
	["maxLevelFilter"] = false,
}
QuestieTrackerVariables = {
	["position"] = {
		["relativeTo"] = "UIParent",
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["yOfs"] = -275.5236749442353,
		["xOfs"] = 1536.37405741013,
	},
}
`

**Comment by Dyaxler** [comment]
Another thing I just remembered... automatic quest tracking via the WoW client interface options doesn't pop quests into Questie's tracker. Only EQL3 does that. Try Shift+Clicking on a quest in the quest log to get the tracker to appear.

**Comment by akanimh** [comment]
Got the tracker to appear manually by doing that, but new quests don't add themselves automatically. Is this intended? I thought for sure older versions did that.

**Comment by Dyaxler** [comment]
Unless you're running EQL3, quests won't automatically appear in the Questie quest tracker. As far as I know Questie was never tied to the Blizzard quest tracker. Older versions of Questie had Cartographer and EQL3 included in it. If I remember correctly, shortly after Questie v2 was released by the original contributors they made Questie independent of Cartographer and EQL3. Cart and EQL3 became optional dependencies.

If you want the auto quest tracking feature to work via the WoW clients interface options you'll have to disable the Questie quest tracker by running:

> /questie tracker

Or use EQL3: http://addons.us.to/addon/eql3

**Comment by akanimh** [comment]
Okay that makes sense if it was included before. Adding EQL3 did the trick with Questie 3.0 after some option changes. But I do sorta wish Questie did it independently so I'm running one less mod. Not a big deal though, thanks for the help!

**Comment by Dyaxler** [comment]
Yeah, I probably should link that client option to Questies functions but personally, I hate the default quest log. I just figured that most everyone else did too and use a mod that makes it better. :D 

Shouldn't be too much trouble to add that functionality to Questie for those that don't want to run something other than the default quest log.

**Comment by Dyaxler** [comment]
I've added additional support for EQL3, Shag and the default wow client. Everything should be working now. :)

I'm about to release v3.1.

**Comment by jeff1736** [comment]
If anyone else was having issues with auto adding new quests to questie, disabling Fuquests seemed to solve it.
