### ISSUE TITLE
Clamlette Surprise

### ISSUE THREAD

**Issue by thombs** [AeroScripts/QuestieDev#2361]
No objectives shown.

**Comment by drejjmit** [comment]
We need more information to be able to help.

**Comment by drejjmit** [comment]
We deliberately blacklisted the items on this quest.
[Alterac Swiss] drops from 303 NPCs.
[Giant Egg] drops from 25 NPCs 
[Zesty Clam Meat] doesn't drop from any mob (Found inside clams that drops from mobs)

Say every NPC got around 20 spawns, that would add 300+ icons over both continents.

You can remove
-         [12207] = true, -- giant egg
-         [8932] = true, -- Alterac Swiss
From ``Questie\Database\Corrections\QuestieItemBlacklist.lua`` if you want them shown.
