### ISSUE TITLE
Decoy!

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#2362]
## Description

There is no object marker at:
67.2, 72.4
you need to place https://classic.wowhead.com/item=21041/bag-of-gold there and fight a mob that spawns

## Wowhead link

https://classic.wowhead.com/quest=8606/decoy

## Questie version

6.0.5

**Comment by drejjmit** [comment]
I told you i fixed it already :smile: 
https://github.com/AeroScripts/QuestieDev/issues/2359#issuecomment-695415400

**Comment by Djfe** [comment]
that was a different part of that long quest chain 😅
I guess, I should test the master then ^^

**Comment by drejjmit** [comment]
Don't forget to "Recomplie Database" in Advanced options if you download master. ^^
