### ISSUE TITLE
Draconic for Dummies

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#2363]
## Description

The marks on the map are missing (for example ony, raggi, bwl, undercity, stormwind)

## Wowhead link

https://classic.wowhead.com/quest=8597/draconic-for-dummies

## Questie version

master

**Comment by drejjmit** [comment]
Do you mean https://classic.wowhead.com/quest=8620/the-only-prescription ? 
https://classic.wowhead.com/quest=8597/draconic-for-dummies is only to go to the souther islands.

**Comment by Djfe** [comment]
oh, you're right 😅
the only prescription
