### ISSUE TITLE
"Elmore's Task" breadcrumb quest listed as available even when followup completed

### ISSUE THREAD

**Issue by MisterTibbs** [AeroScripts/QuestieDev#2364]
## Description
The "Elmore's Task" breadcrumb quest is listed as available under Journey -> Quests by Zone -> Eastern Kingdoms -> Stormwind City even when you have completed the followup quest, "Stormpike's Delivery". I have checked both "Verner Osgood" and "Smith Argus" NPCs and neither offer the quest.

## Wowhead link
[Elmore's Task - Breadcrumb quest](https://classic.wowhead.com/quest=1097/elmores-task)
[Stormpike's Delivery - Main quest](https://classic.wowhead.com/quest=353/stormpikes-delivery)

## Screenshots
![WoWScrnShot_092720_121153](https://user-images.githubusercontent.com/24671315/94362413-65b24b80-00bb-11eb-9b16-7b5097788cd9.jpg)

## Questie version
6.0.5

**Comment by drejjmit** [comment]
Thanks for the report. Will be fixed for next release.
