### ISSUE TITLE
Eranikus, Tyrant of the Dream

### ISSUE THREAD

**Issue by yobbin2000** [AeroScripts/QuestieDev#2365]
Description
The ! for the quest [Eranikus, Tyrant of the Dream] shows up on the maps event though I have not completed the prerequisite quest [The Charge of the Dragonflights].

## Wowhead link
https://classic.wowhead.com/quest=8733/eranikus-tyrant-of-the-dream#comments

## Screenshots 

![Eranikus, Tyrant of the Dream](https://user-images.githubusercontent.com/60338910/94403810-4eee2080-01b1-11eb-8726-b34ceab7df66.png)

**Comment by drejjmit** [comment]
Thanks for the report. 
Will be fixed for next release.
