### ISSUE TITLE
Questie v3 issue with EQL3

### ISSUE THREAD

**Issue by SilverSaw** [AeroScripts/QuestieDev#237]
Hello,

Questie v3 with EQL3 cause permanent automatic quest tracking and when you click on EQL3 options to remove this after relog they are clicked again and options are not saved.

There is no such a problem with Questie v2.67

Best Regards

**Comment by Dyaxler** [comment]
Edit Questie.lua and remove lines 137 and 138

> QuestlogOptions[EQL3_Player].AddUntracked = 1;
> QuestlogOptions[EQL3_Player].AddNew = 1;

**Comment by Dyaxler** [comment]
These lines have been removed in version 3.1...
