### ISSUE TITLE
Questie for French ?

### ISSUE THREAD

**Issue by Pandikey** [AeroScripts/QuestieDev#238]
Hello Dyaxler,

Thanks again for your great work !
Just to know if you get the french quests, any way to work Questie on french client ? We are lot of french who need this great addons, we can help you if you need anything for french !

Hope we can find a solution for all french people.
Merci beaucoup monsieur !

**Comment by Dyaxler** [comment]
I can't promise anything, but we're hoping to make Questie compatible for other languages. This requires an update to our database tool. I'm waiting for someone to update it but he's very busy. Please have patience.
