### ISSUE TITLE
[11] Crown of the Earth Quest ID 934 Quest Not Completing 

### ISSUE THREAD

**Issue by SonicMcCall** [AeroScripts/QuestieDev#2385]
## Description
In the "My Journey" tab when using Questie, and going onto "Quests by Zone" and setting the region to Teldrassil, there is an incompletable quest. It uses Quest ID 934 and is [11] Crown of the Earth; Fill the amethyst phial and bring it back to Corithras Moonrage in Dolanaar.  Please fix it so that it completes when the task objectives are met as it hinders the ability to show that you have completed all quests in Teldrassil. This would just be a quality of life update as it does not change the core functions of the mod  

## Wowhead link
https://classic.wowhead.com/quest=934/crown-of-the-earth

## Screenshots
![WoWScrnShot_100820_152232](https://user-images.githubusercontent.com/72543176/95427628-6e880480-097a-11eb-9900-4f391ae6d117.jpg)

## Questie version
Questie  v6.0.5

**Comment by BreakBB** [comment]
Hey @SonicMcCall could you explain if this was not a problem at all or if you found a solution?

**Comment by BreakBB** [comment]
Ah, nevermind. Ticket is #2386
