### ISSUE TITLE
No Quest Marker For: [22] Search For Incendicite On Map

### ISSUE THREAD

**Issue by SonicMcCall** [AeroScripts/QuestieDev#2388]
## Description
[22] Seach for Incendicite collected from Pilot Stonegear has no quest marker on map but there is a ! above the quest giver

## Wowhead link
https://classic.wowhead.com/quest=466/search-for-incendicite

## Screenshots
![WoWScrnShot_101120_084635](https://user-images.githubusercontent.com/72543176/95667852-58f32480-0b9e-11eb-8836-06f864ea044a.jpg)

## Questie version
Questie v6.0.5

**Comment by drejjmit** [comment]
I can't find any problem with this quest in the DB. It shows up on all my characters. Any ideas @BreakBB?

**Comment by BreakBB** [comment]
@SonicMcCall This is a pretty easy quest which does not has much magic in our database. Could you make sure your Questie settings are correct and you see other quests?

Just like drejjmit I can't find any issues in our data for this quest.

**Comment by Gogo1951** [comment]
I think this may not have anything to do with the specific quest that @SonicMcCall wrote in about.

I've been noticing when I quest for an hour or so, Questie can occasionally bug out and stop showing icons.

Thought it was just part of the Alpha but maybe it's a bug from 6.0.5 that the Alpha inherited.

I haven't had a ton of time to quest lately, but something to keen an eye out for.

**Comment by drejjmit** [comment]
Please make a new issue if you still have issues. Tested working with 6.2.0
