### ISSUE TITLE
[27] Gnogaine In Dun Morogh Doesn't Show On Map Or On Quests By Zone 

### ISSUE THREAD

**Issue by SonicMcCall** [AeroScripts/QuestieDev#2389]
## Description
The quest [27] Gnogaine doesn't show up on the map or in quests by zone. It is situated at 45.87, 49.38 in Dun Morogh and the quest giver is Ozzie Togglevolt. It's Quest ID is 2926.

## Wowhead link
https://classic.wowhead.com/quest=2926/gnogaine

## Screenshots
![WoWScrnShot_101120_085413](https://user-images.githubusercontent.com/72543176/95667997-33ffb100-0ba0-11eb-83cb-b54b3e5d6af5.jpg)

## Questie version
Questie v6.0.5

**Comment by SonicMcCall** [comment]
That available quest is Search For Incendicite

**Comment by drejjmit** [comment]
Thanks for the report. Will be fixed for next release.

Gnogaine is a Gnomeregan quest. Shows up in ``Dungeons > Gnomeregan``
