### ISSUE TITLE
Mouseover on escort mob raise error.

### ISSUE THREAD

**Issue by rasberryrabbit** [AeroScripts/QuestieDev#239]
mouseover on Escorting quest mob raise error.

![wowscrnshot_050916_132416](https://cloud.githubusercontent.com/assets/11563461/15105865/273d785c-1600-11e6-8f57-c36e60bfc8f3.png)

I make some modification on questienotes.lua line 265.

                                                if indx~=nil then
												    local countstr = string.sub(desc, indx+2);
												    local namestr = string.sub(desc, 1, indx-1);
												if(string.find(name, monster) and QuestieItems[namestr] and QuestieItems[namestr]['drop']) then -- Added Find to fix zapped giants (THIS IS NOT TESTED IF YOU FIND ERRORS REPORT!)
													for dropperr, id in pairs(QuestieItems[namestr]['drop']) do
														if(name == dropperr or (string.find(name, dropperr) and name == dropperr) and not p) then-- Added Find to fix zapped giants (THIS IS NOT TESTED IF YOU FIND ERRORS REPORT!)
															GameTooltip:AddLine(v['objectives']['QuestName'], 0.2, 1, 0.3)
															GameTooltip:AddLine("   " .. namestr .. ": " .. countstr, 1, 1, 0.2)
															p = true;
															return;
														end
													end
												end
                                                else
													GameTooltip:AddLine(v['objectives']['QuestName'], 0.2, 1, 0.3)
                                                    p = true;
                                                    return;
                                                end

**Comment by Dyaxler** [comment]
Can you attach your version of QuestieNotes.lua here in a zip file so I can take a look at an actual copy that fixes the issue?

**Comment by rasberryrabbit** [comment]
[QuestieNotes_escortmob.zip](https://github.com/AeroScripts/QuestieDev/files/256188/QuestieNotes_escortmob.zip)

I change code for working on non-countable quest mob. There is may no ":" in quest description.

**Comment by rasberryrabbit** [comment]
I make another patch for finding mob & counter text.

[questienote_mobcount.patch.txt](https://github.com/AeroScripts/QuestieDev/files/264845/questienote_mobcount.patch.txt)

**Comment by Dyaxler** [comment]
I've already inserted the changes you made. It'll be in version 3.1 here shortly.

**Comment by rasberryrabbit** [comment]
Thank you :)
