### ISSUE TITLE
ZG Quests May Be Incorrectly Tagged As Repeatable

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2398]
## Bug description

I had some quests to turn in for ZG, for the various armaments. But they didn't have a completion ? on the map. I think it was because they were incorrectly tagged as repeatable quests.

### Nothing on Map

![image](https://user-images.githubusercontent.com/55365231/96359874-33ee3c80-10dd-11eb-89d7-d430ef25285a.png)

### Settings

![image](https://user-images.githubusercontent.com/55365231/96359881-394b8700-10dd-11eb-9805-e87678ae3d43.png)

### Once you turn them quests in, dialogue to get replacements.

![image](https://user-images.githubusercontent.com/55365231/96359886-48323980-10dd-11eb-98f7-1244f2371b1d.png)

**Comment by BreakBB** [comment]
This could be a general problem as #2405 suggests

**Comment by BreakBB** [comment]
@Gogo1951 can you remember if you picked up the token items from the bank and then checked the map?

**Comment by drejjmit** [comment]
Complete icons should show even if you have that icon type turned off (If they were tagged repeatable with repeatable turned off). As BreakBB said, picking up from bank doesn't trigger any updates.

**Comment by Gogo1951** [comment]
I pulled the items from my bank. This would be fixed with #2515
