### ISSUE TITLE
Warlock quest "Tainted Parchment" Icon

### ISSUE THREAD

**Issue by Znbd** [AeroScripts/QuestieDev#2399]
## Bug description
As undead warlock i can't complete "Tainted Parchment" quest in Durotar, but its icon still shown on the map. In zone quest list that quest is not available to me.

## Screenshots
![image](https://user-images.githubusercontent.com/55866790/96362442-0386bc80-1136-11eb-9b37-9b1c2649881d.png)
![image](https://user-images.githubusercontent.com/55866790/96362462-21542180-1136-11eb-8153-676a5cb2ab56.png)

## Questie version
"v6.1.0"
-->

**Comment by drejjmit** [comment]
Thanks for the report. These are really hard for us to find without help from the community. 
So please report if you find more 😃.

Will be fixed for next release.

(Class quests are shown in "Warlock" and not "Durotar" for example)
