### ISSUE TITLE
Some Logistic Task quest are not marked as Repeatable

### ISSUE THREAD

**Issue by Znbd** [AeroScripts/QuestieDev#2401]
## Bug description
Four Logistic Tasks (see screenshot) should (probably) be in repeatable group as the rest of them.

## Screenshots
![image](https://user-images.githubusercontent.com/55866790/96365078-c7a82300-1146-11eb-8c4c-6a90f0c728ff.png)

## Questie version
v6.1.0

**Comment by drejjmit** [comment]
Thought horde and alliance used the same quests. Horde quests will be tagged as repeatable for next release.
