### ISSUE TITLE
Townfolks settings are missing in the options

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#2404]
## Bug description

When you disabled the minimap icon there is no way to edit the townfolk icons. This should be added to the options. Noticed on [Curseforge](https://www.curseforge.com/wow/addons/questie?comment=1328)

## Questie version

v6.1.0

**Comment by omggga** [comment]
+++
Strange you added that icons (near the end of classic), but no options to disable it (only disabled all icons). Now full map in posts and hyppo riders...

**Comment by drejjmit** [comment]
You can still press the minimap button to pick what you want/don't want tracked.
This is just a suggestion to add it in options as well.

**Comment by omggga** [comment]
Oh, thanks. Never know about that functionality.
