### ISSUE TITLE
Reagents for Reclaimers Inc. (part 3)   "Doomwarder Blood"

### ISSUE THREAD

**Issue by matthewhively** [AeroScripts/QuestieDev#2407]
Map icons for `Doomwarder Blood` are clustered more broadly than the monsters that drop it. As per quest text:
>doomwarder captain, or lord

drop the blood, ot the far more plentiful Doomwarders. The map icons incorrectly show for all the desolace regions that contain doomwarders of any rank, not confined to the small area where doomwarder captions are found.

https://classic.wowhead.com/quest=1466/reagents-for-reclaimers-inc

I did not take a screenshot before completing the quest. I only thought of doing a bug report over night.

Questie Version 6.0.5. Not exactly the latest I know, but I didn't see anything like this listed in the changelog, and I wouldn't be able to update the version and re-test anyways since I've completed it.
I hope this helps.

**Comment by drejjmit** [comment]
Thanks for the report. 

In 6.1 we added waypoints for objectives. Before this the elite npc "Lord Azrethoc" got 89 spawn points to the east of where "Doomwarder Captains" are.
It should be easier with 6.1 to see that that's a separate elite mob.

**Comment by matthewhively** [comment]
Ah, that makes sense. Thanks!
