### ISSUE TITLE
Errors showing due to potentially bad data for the quest 'The Challenge' - part of the Tier 0.5 dungeon set questline. 

### ISSUE THREAD

**Issue by TomVanLierop** [AeroScripts/QuestieDev#2408]
## Bug description
The bug/issue is that upon login and/or switching to different zones while having the quest 'The Challange' active the chat is filled with error messages.

## Screenshots
![WowClassic_1UyYEVl61w](https://user-images.githubusercontent.com/8556252/96550759-8e3ff680-12b1-11eb-8da9-4c25cbff06d2.png)
![WowClassic_8ZDuhOC9pK](https://user-images.githubusercontent.com/8556252/96550782-96983180-12b1-11eb-884a-d4de17a9a92a.png)

## Questie version
Running version 6.1.0

**Comment by drejjmit** [comment]
Thanks for the report. Will be fixed for next release.
