### ISSUE TITLE
Minimap Icons in Darnassus always show at the player instead of location

### ISSUE THREAD

**Issue by x003** [AeroScripts/QuestieDev#241]
Inside of Darnassus If you look at the main map you'll see the ! and ? icons where they should be but if you look at the minimap it will always be in the center on the player icon instead.

**Comment by Dyaxler** [comment]
Sounds like you got some issues with your SavedVariables file... I've only seen this behavior in the WoW TBC client I was working on a couple of weeks back but it had to do with a nasty little mod that anchored MiniMap mod icons to itself which I fixed.

Are you on an English server? If not then there's your issue. Currently Questie only supports English.

**Comment by Dyaxler** [comment]
Apologies... this has been resolved in v3.1. Turned out to be bad Astrolabe data.

**Comment by Muehe** [comment]
My bad. Note to self: Use regular expression next time instead of eyes.

**Comment by Dyaxler** [comment]
Hey we all make spelling mistakes. Trust me... I suck at spelling and constantly catch myself but they still slip through.

Questie v3.1 has been patched and the zip file has been updated.
