### ISSUE TITLE
Wrong coordinates for Quest Witherbark Cages

### ISSUE THREAD

**Issue by dende** [AeroScripts/QuestieDev#2411]
## Description

For the Aerie Peak Quest Witherbark Cages, the third cage is at  X: 31  Y: 57 and not at X: 23  Y: 58 as Questie reports

## Wowhead link

https://classic.wowhead.com/quest=2988/witherbark-cages

## Screenshots

No screenshot, as I just finished the quest, but all three cages were displayed on the same spot at X: 31  Y: 57

## Questie version

v.6.1.0

**Comment by dende** [comment]
I just looked up the info [in the Database](https://github.com/AeroScripts/QuestieDev/blob/cd479d77c0f62679bf1cceaa24e0e9c0323de731/Database/objectDB.lua#L2930) and it seems to be correct there, so this issue can be closed too.

**Comment by BreakBB** [comment]
I think this could be linked to #2151 as you are playing on a German client @dende aren't you?

**Comment by BreakBB** [comment]
Specially this quest has been an issue in the past as well. Looks like something changes: #1424
