### ISSUE TITLE
Silithus Logistics quests should be marked as repeatable

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#2412]
This concerns the horde versions of the quests Scrying Materials, Grinding Stones for the Guard, Boots for the Guard and Desert Survival Kits.

https://classic.wowhead.com/quest=8807/scrying-materials
https://classic.wowhead.com/quest=8806/grinding-stones-for-the-guard
https://classic.wowhead.com/quest=8805/boots-for-the-guard
https://classic.wowhead.com/quest=8804/desert-survival-kits

![WoWScrnShot_102020_133654](https://user-images.githubusercontent.com/54936174/96581902-d58ead00-12da-11eb-8228-891cce04c759.jpg)

Version 6.1.0

**Comment by drejjmit** [comment]
Fixed with ae94980d3db64f5a0c1f7b6d735e92a4099a9cae.
Thanks for the report.
