### ISSUE TITLE
Only one Your Fortune Awaits You... marked as repeatable

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#2413]
The quest Your Fortune Awaits You..., from Sayge's fortunes in the Darkmoon Faire, actually has 4 versions leading to different objectives; only one is correctly marked as repeatable in the Questie database.

https://classic.wowhead.com/quest=7937/your-fortune-awaits-you
https://classic.wowhead.com/quest=7938/your-fortune-awaits-you
https://classic.wowhead.com/quest=7944/your-fortune-awaits-you (correctly marked as repeatable)
https://classic.wowhead.com/quest=7945/your-fortune-awaits-you

![WoWScrnShot_102020_135201](https://user-images.githubusercontent.com/54936174/96582430-8dbc5580-12db-11eb-8b75-57e7b15b8b2b.jpg)

Version 6.1.0

**Comment by drejjmit** [comment]
Are you sure these are repeatable?

**Comment by Cerby3BR** [comment]
I completed one (the one that leads to the logging camp in Elwynn), and using the IsQuestFlaggedCompleted script still returns a "false".

**Comment by Cerby3BR** [comment]
Also, an old DMF rep guide notes that these quests are a cheap, if very slow and random, way to grind to exalted.

**Comment by drejjmit** [comment]
Thanks for the report. Will be fixed for next release.
