### ISSUE TITLE
Hallow's End Candy quests are repeatable

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#2414]
The quests Chicken Clucking for a Mint, Incoming Gumdrop, Flexing for Nougat and Dancing for Marzipan, for both factions, are repeatable quests (to be specific, they award the quest objectives of Hallow's End Treats for Jesper/Spoops! and are therefore repeatable as long as one is on that quest)

Alliance:
https://classic.wowhead.com/quest=8353/chicken-clucking-for-a-mint
https://classic.wowhead.com/quest=8355/incoming-gumdrop
https://classic.wowhead.com/quest=8356/flexing-for-nougat
https://classic.wowhead.com/quest=8357/dancing-for-marzipan

Horde:
https://classic.wowhead.com/quest=8354/chicken-clucking-for-a-mint
https://classic.wowhead.com/quest=8358/incoming-gumdrop
https://classic.wowhead.com/quest=8359/flexing-for-nougat
https://classic.wowhead.com/quest=8360/dancing-for-marzipan

![WoWScrnShot_102020_140104](https://user-images.githubusercontent.com/54936174/96583250-b55fed80-12dc-11eb-865e-5332944e76a7.jpg)

Version 6.1.0

**Comment by drejjmit** [comment]
Thanks for the report. Will be fixed for next release.
