### ISSUE TITLE
Wrong class colors 

### ISSUE THREAD

**Issue by TomKing1** [AeroScripts/QuestieDev#2419]
![1](https://user-images.githubusercontent.com/38212845/96739515-c6316180-13b7-11eb-936e-223c39b37071.PNG)

How do I change it so the class colours are the same? It has orange for both of us but my other party member is a hunter. happens with no other addons on and using the latest version.

**Comment by BreakBB** [comment]
Hey @TomKing1 this bug has also been reported on Discord and a fix for this is already in the pipeline. Keep an eye out for the next release 👍

**Comment by BreakBB** [comment]
Looking good again 
![grafik](https://user-images.githubusercontent.com/33514570/97103243-7f8b8200-16ab-11eb-95b0-053068e53601.png)

**Comment by TomKing1** [comment]
Ty so much I messed around with ElvUI for a hour to figure it out <3
