### ISSUE TITLE
Automatic quest tracker

### ISSUE THREAD

**Issue by pyryny** [AeroScripts/QuestieDev#242]
Hey, I'm using the latest Questie version alongside EQL3 and cannot seem to find a way for the tracker to automatically track new quests. I turned on/off the default wow automatic tracker, to no avail. I always need to shift click quests in my quest log in order for them to show up. Is there any way around this?

Thanks

**Comment by Dyaxler** [comment]
EQL3 has it's own setting... open the quest log and click Options. Here are some of the options I use while using EQL3.

![capture](https://cloud.githubusercontent.com/assets/17400948/15332141/3f7ad792-1c19-11e6-8c82-aad706fde458.JPG)

**Comment by pyryny** [comment]
Strange.
I have exactly the same EQL settings as you, and I also tried using /questie NUKE to reset settings just in case I had done something weird and it is still no automatically tracking quests :S

**Comment by Dyaxler** [comment]
Are you on an English based server? Questie only supports English currently.

**Comment by pyryny** [comment]
Yup, I'm playing on Kronos right now with english client.

**Comment by Dyaxler** [comment]
Kronos and Kronos II works fine for me. Both auto tracking new quests and adding a quest to the tracker when an objective updates that isn't already on the tracker works with and without the QuestieTracker enabled. Works with the EQL3 tracker too.

**Comment by pyryny** [comment]
and do you have the default wow tracker enabled in interface options?

**Comment by Dyaxler** [comment]
That option only works when you aren't running EQL3. Questie obeys the default wow api's when EQL3 isn't loaded and the QuestieTracker is disabled.

**Comment by pyryny** [comment]
Ok, just wanted to make sure but I already had this option unchecked. Pretty weird honestly. Maybe another addon is interfering with questie or EQL. I'm going to try disabling other addons and see if this fixes the problem.

**Comment by Dyaxler** [comment]
The auto tracking option in Interface Options... I made a note about it in the release notes. It doesn't work the way the EQL3 option works...

> For those not running EQL3 or some other QuestLog mod. If you prefer the
default wow QuestLog and Tracker that's fine but it's very limited. For
example, if a quest doesn't have any objectives to "track" then it won't
appear in the quest tracker and no Quest Arrow will be available for it.
Additionally, quests will not automatically be tracked by the default WoW
quest tracker. The way that it works is that if you have the option enabled
in the games Interface Options --> "Automatic Quest Tracking" then yes,
it will auto track a quest with an objective once you OBTAIN the first
item. Then it will appear automatically in the list unless you manually
Shift+Click the quest in the QuestLog but again, only if there is a
"trackable" objective. Unlike EQL3 or other QuestLog/QuestTracker mods
where pretty much anything is trackable, these quests will appear in the
Questie QuestTracker. If the quest appears then map coordinates are
cached and this allows the QuestieArrow to hook into the position and
give you an arrow.

**Comment by pyryny** [comment]
No I know I ready everything you wrote in the release note, I just wanted to make sure. I do not want to have to wait to get the first item/objective for the quest to start tracking, hence my interrogation.

**Comment by Dyaxler** [comment]
Just making sure because most people assume that is what that default wow option does. :)

If you immediately want a quest to be tracked when you pick up a quest you'll have to run EQL3 or MonkeyQuest or some other type of quest management mod. The original authors have always liked EQL3, as do I, and we've kept Questie compatible with EQL3.

**Comment by pyryny** [comment]
It is strange though that I am running EQL3 with the latest questie 3.1 and it is not tracking. It is probably something on my end since you don't have any problems. I'll disable other addons and see how it goes.

**Comment by Dyaxler** [comment]
Yeah, unload everything except EQL3 and make sure it's not the mod itself... if it's EQL3 here is the version tons of people use without issue.

http://addons.us.to/addon/eql3

**Comment by pyryny** [comment]
Will do once Kronos gets back online!
Thanks for your help.

**Comment by Dyaxler** [comment]
Kronos is down for me too now. Make a character on Kronos II and test it there. :)

**Comment by pyryny** [comment]
I finally found the culprit responsible!
I also had the whole CT addons, including CT_QuestLevels enabled.
Disabled it and now everything works like a charm!

Cheers
