### ISSUE TITLE
Error for repeatable Silithus Quest "Desert survival pack"

### ISSUE THREAD

**Issue by Karmuk** [AeroScripts/QuestieDev#2420]
[20:45] Quest angenommen: Wüstenüberlebenspaket 
 [20:45] ...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:52: bad argument #1 to 'unpack' (table expected, got nil) 
 [20:45] ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:975: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:973>
[C]: in function `unpack'
...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:52: in function `?'
...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:104: in function `?'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:714: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:702>
[C]: in function `xpcall'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:973: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:970>
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1028: in function `PopulateObjectiveNotes'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:395: in function `val'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:370: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:368>
 
 [20:45] Questie: [ERROR] [QuestieQuest]: v6.1.0 - Es gab einen Fehler beim Weitergeben der Ziele für Wüstenüberlebenspaket 8804 1 No error 
 [20:45] ...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:52: bad argument #1 to 'unpack' (table expected, got nil) 
 [20:45] ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:975: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:973>
[C]: in function `unpack'
...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:52: in function `?'
...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:104: in function `?'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:714: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:702>
[C]: in function `xpcall'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:973: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:970>
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1028: in function `PopulateObjectiveNotes'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:395: in function `val'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:370: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:368>
 
 [20:45] Questie: [ERROR] [QuestieQuest]: v6.1.0 - Es gab einen Fehler beim Weitergeben der Ziele für Wüstenüberlebenspaket 8804 2 No error 
 [20:45] ...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:52: bad argument #1 to 'unpack' (table expected, got nil) 
 [20:45] ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:975: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:973>
[C]: in function `unpack'
...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:52: in function `?'
...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:104: in function `?'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:714: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:702>
[C]: in function `xpcall'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:973: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:970>
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1028: in function `PopulateObjectiveNotes'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:395: in function `val'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:370: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:368>
 
 [20:45] Questie: [ERROR] [QuestieQuest]: v6.1.0 - Es gab einen Fehler beim Weitergeben der Ziele für Wüstenüberlebenspaket 8804 3 No error 
 [20:45] ...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:52: bad argument #1 to 'unpack' (table expected, got nil) 
 [20:45] ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:576: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:574>
[C]: in function `unpack'
...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:52: in function `?'
...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:104: in function `?'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:714: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:702>
[C]: in function `xpcall'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:574: in function `UpdateObjectiveNotes'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:488: in function `UpdateQuest'
...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:90: in function <...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:85>
...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:73: in function `CompareQuestHashes'
...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:353: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:335>
[C]: ?
...\AddOns\Details\Libs\AceBucket-3.0\AceBucket-3.0.lua:73: in function <...\AddOns\Details\Libs\AceBucket-3.0\AceBucket-3.0.lua:71>
...\AddOns\Details\Libs\AceBucket-3.0\AceBucket-3.0.lua:89: in function `func'
...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:57: in function <...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>
 
 [20:45] ...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:52: bad argument #1 to 'unpack' (table expected, got nil) 
 [20:45] ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:576: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:574>
[C]: in function `unpack'
...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:52: in function `?'
...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:104: in function `?'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:714: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:702>
[C]: in function `xpcall'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:574: in function `UpdateObjectiveNotes'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:488: in function `UpdateQuest'
...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:90: in function <...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:85>
...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:73: in function `CompareQuestHashes'
...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:353: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:335>
[C]: ?
...\AddOns\Details\Libs\AceBucket-3.0\AceBucket-3.0.lua:73: in function <...\AddOns\Details\Libs\AceBucket-3.0\AceBucket-3.0.lua:71>
...\AddOns\Details\Libs\AceBucket-3.0\AceBucket-3.0.lua:89: in function `func'
...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:57: in function <...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>
 
 [20:45] ...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:52: bad argument #1 to 'unpack' (table expected, got nil) 
 [20:45] ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:576: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:574>
[C]: in function `unpack'
...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:52: in function `?'
...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:104: in function `?'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:714: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:702>
[C]: in function `xpcall'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:574: in function `UpdateObjectiveNotes'
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:488: in function `UpdateQuest'
...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:90: in function <...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:85>
...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:73: in function `CompareQuestHashes'
...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:353: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:335>
[C]: ?
...\AddOns\Details\Libs\AceBucket-3.0\AceBucket-3.0.lua:73: in function <...\AddOns\Details\Libs\AceBucket-3.0\AceBucket-3.0.lua:71>
...\AddOns\Details\Libs\AceBucket-3.0\AceBucket-3.0.lua:89: in function `func'
...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:57: in function <...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

**Comment by drejjmit** [comment]
Thanks for the report. Will be fixed for next release.
