### ISSUE TITLE
Commendation Officers

### ISSUE THREAD

**Issue by Nerillida** [AeroScripts/QuestieDev#2421]
See closed issue #2238

The latest version of Questie switches the persistent commendation officers on and off with the "AQ" quests. They're separate.

15761 Officer Vu'Shalay
15762 Officer Lunalight
15763 Officer Porterhouse
15764 Officer Ironbeard
15765 Officer Redblade
15766 Officer Maloof
15767 Officer Thunderstrider
15768 Officer Gothena

**Comment by drejjmit** [comment]
Why show those quests? 
Tokens for an event that's not active on any server? 
It's just unnecessary cluttering of the map.

They still show if you enable AQ icons.

**Comment by Nerillida** [comment]
Q: Why show those quests?
A: For completeness, they will persist past AQ. 
It is up to you if you want to show them. They were present until recently in "retail".
Why Blizzard left them in for so long is unknown to me.

**Comment by drejjmit** [comment]
I've spoken with the team and we decided to keep these under ``AQ War Effort`` toggle to not confuse new players and not clutter the map.
We may eventually add an inventory check and show these quests if you have "Commendation Signet" in your bags.
