### ISSUE TITLE
Doesn't load

### ISSUE THREAD

**Issue by Ignatheos** [AeroScripts/QuestieDev#2422]
Gives me the error:

Date: 2020-10-23 00:02:16
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua line 116:
   Usage: RegisterEvent("eventname", "methodname"): 'methodname' - method 'CHAT_MSG_LOOT' not found on self.
Debug:
   [C]: ?
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:112: RegisterEvent()
   ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:116: RegisterAllEvents()
   Questie\Questie.lua:157:
      Questie\Questie.lua:141
   [C]: ?
   ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:623:
      ...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:615
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.3
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DungeonMaps, v0.1c
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FlightMastersClassic, vv1.2
  GatherLite, v3.2.5
  GoldPoints, v0.3.0
  GroupCalendar, v
  Immersion, v1.2.3
  LFG113, v
  PallyPower, vv1.2.27-classic
  Pawn, v2.4.1
  Questie, v6.0.5
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11305-1.1.5
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=499)

**Comment by BreakBB** [comment]
@Ignatheos Are you sure you restarted WoW after you updated Questie?

**Comment by Ignatheos** [comment]
Yes, I restarted wow, even the laptop, still it doesnt load.

**Comment by BreakBB** [comment]
@Ignatheos Hmmm... Strange error, since it is loading just fine for "everybody else". You installed Questie on Classic, right?

You should also verify you've got the correct version of Questie. We had an alpha version out for a few hours which might be the problem here.

But we will investiagate to see if there is something up with our code :ok_hand:

**Comment by Ignatheos** [comment]
No need, I have reinstall it from scratch and it is now working properly, ty very much.

**Comment by BreakBB** [comment]
@Ignatheos Thanks for coming back to this! I am glad you figured it out and that it is working for you now :+1: Feel free to open another issue if you encounter further problems.
