### ISSUE TITLE
Autocomplete not working as intended.

### ISSUE THREAD

**Issue by OrceMaceski** [AeroScripts/QuestieDev#2423]
After almost 3 days of farming Cenarion Tactical and whatnot badges autocomplete function screwed me over and spent all the tokens on the wrong quest.
Keep up the good work!
Questie deleted from my addons.

**Comment by drejjmit** [comment]
Thanks for the report.
It's not on by default. Disallowed list is manually maintained.
Fixed with 3b8eb493ee921bebfff48d48554a125add14165f
