### ISSUE TITLE
Wrong NPC tagged for Darnassus version of the dwarf priest quest "A Lack of Fear"

### ISSUE THREAD

**Issue by Nuffalo** [AeroScripts/QuestieDev#2424]
On my dwarf priest in Darnassus I noticed a marker for an available quest named "A Lack of Fear" offered by the priest trainer Lariia.  The quest is actually offered by Priestess Alathea, another priest trainer nearby.

**Comment by BreakBB** [comment]
@Nuffalo Thanks for the report. [This](https://classic.wowhead.com/quest=5647/a-lack-of-fear) is the quest correct? Will be an easy fix 👍

**Comment by Nuffalo** [comment]
Yup! That is indeed the quest I was referencing.

**Comment by drejjmit** [comment]
Thanks for the report. Will be fixed for next release.
