### ISSUE TITLE
Questie: [ERROR] Missing event data for Objective: Die drei geheimen Notizen suchen. id: nil

### ISSUE THREAD

**Issue by huhubi** [AeroScripts/QuestieDev#2425]
Hello,

i am using questie v.6.1.0 and got the error mentioned in the title for the "Grimtotem Spying" quest. I assume that the issue is that only 2/3 objectives are showed on the map. 
![image](https://user-images.githubusercontent.com/73472722/97165810-90f48d00-1784-11eb-9775-fc6b344f0575.png)
![image](https://user-images.githubusercontent.com/73472722/97165573-378c5e00-1784-11eb-89a4-9c7ef06a41fd.png)

I hope that I could help you out and thanks for making just such an amazing addon!

**Comment by drejjmit** [comment]
Only German and French got a triggerEnd on this quest

![image](https://user-images.githubusercontent.com/15526476/97298197-6291b300-1853-11eb-9b30-2ae3061505fa.png)

**Comment by andreihq** [comment]
Want to add, that Secret Note #1 is not displayed on the map and when coming to the item location, which is at 31,32 and mousing over chest, Questie adds tooltip: "Secret Note #2" thinking that the chest is for Note #2, while its Note #1

**Comment by BreakBB** [comment]
This behaviour was also noticed on an English client.
