### ISSUE TITLE
questie error

### ISSUE THREAD

**Issue by RTBacon** [AeroScripts/QuestieDev#2426]
Date: 2020-10-26 16:27:16
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua line 116:
   Usage: RegisterEvent("eventname", "methodname"): 'methodname' - method 'CHAT_MSG_LOOT' not found on self.
Debug:
   [C]: ?
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:112: RegisterEvent()
   ...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:116: RegisterAllEvents()
   Questie\Questie.lua:157:
      Questie\Questie.lua:141
   [C]: ?
   ...\ClassicGuildBank\libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...\ClassicGuildBank\libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...\ClassicGuildBank\libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...\ClassicGuildBank\libs\AceAddon-3.0\AceAddon-3.0.lua:613:
      ...\ClassicGuildBank\libs\AceAddon-3.0\AceAddon-3.0.lua:605
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  BagFreeSpaceCounter, v1.0.3
  Bagnon, v8.3.5
  BagnonScrap, v8.3.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicGuildBank, v1.3
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GroupCalendar, v
  Questie, v6.0.5
  Scrap, v8.3.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=350)

**Comment by BreakBB** [comment]
@RTBacon Make sure you restarted WoW after updating Questie.
