### ISSUE TITLE
Questie Challenge!

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2427]
## Description

I want the ability to challenge my friends so I can compare achievements and promote questing.

When I type "/qc" I would like Questie to compare the number of quests I've done, and those of my target, and return in chat the results.

## typing "/qc" with no target

/s ""{rt1} Questie : Take the Questie Challenge with your friends by typing "/qc" with them targeted.

/s "I have completed {# Quests}!"

## typing "/qc" with a target

/s "{rt1} Questie : {Your Name} & {Target's Name} are taking the Questie Challenge! (Take the Questie Challenge with your friends by typing "/qc" with them targeted.)"

/s "I have completed {# Quests}!

Target should automatically respond.

/s "I have completed {# Quests}!

Followed by the loser saying:

/s "Congratulations, {Winner's Name}! You have proven your skills at Questing to be superior to my own."

## If it's a tie... the originator would say:

/s "We seem to be evenly matched... for now!"

Thought about XP points to settle a tie... but meh, that's too complicated.

## If target doesn't have an up-to-date version of Questie:

/s "{rt1} Questie : {Your Name} & {Target's Name} are taking the Questie Challenge! (Take the Questie Challenge with your friends by typing "/qc" with them targeted.)"

/s "I have completed {# Quests}!

/s "... and {Target's name} forfeits. Please download the latest version of Questie so we can compete!

## Questions

* There's a range limit, yeah? We'll probably need an out of range response.
* Could we add on a "/qc zone" modifier so it would only report back on the current zone you were in? Maybe we make that the default? No worries if there are no quests in a zone, both people would just report back 0. May be cool to also list the total possible quests in the zone... like "I've done 75/80 quests!" but thinking it through some races / classes have different totals. If we did it, we'd have to do like "I've done 94% (75/80) of the quests available to me in this zone..." and while I think that's cool, probably gets complicated.

And just to be very clear this is a sub-trivial task just adding it after a conversation in Discord. (=

**Comment by AeroScripts** [comment]
With guild members, party members and players with known usernames there's no range limit because we can use the party/guild/whisper addon channels for that

yell comms are about the same distance as a /s message, but if its announcing that text in /s, questie could parse the player name from that and request the additional info from them via an addon whisper

**Comment by Arccai** [comment]
**Love** the idea!

**Comment by Gogo1951** [comment]
Cute idea, but hard to get time to do it right.

We'd end up building out a whole achievement system I suspect. Ha. And there's not time for that.

Partially covered by #2517
