### ISSUE TITLE
Error when accepting Hallow's End quest "The Power of Pine"

### ISSUE THREAD

**Issue by MisterTibbs** [AeroScripts/QuestieDev#2428]
## Bug description
You get an error when you accept the alliance Hallow's End quest "The Power of Pine"
[The Power of Pine](https://classic.wowhead.com/quest=8373/the-power-of-pine)
You can complete the quest just fine though.

## Screenshots
![questie](https://user-images.githubusercontent.com/24671315/97301720-6aa02180-1858-11eb-8a72-726297bb3660.jpg)

## Questie version
6.1.0

**Comment by drejjmit** [comment]
Thanks for the report. Will be fixed for next release.
cd479d77c0f62679bf1cceaa24e0e9c0323de731
