### ISSUE TITLE
Is the alliance quest "Concerted Efforts" incorrectly grouped as an Arathi Basin quest?

### ISSUE THREAD

**Issue by MisterTibbs** [AeroScripts/QuestieDev#2430]
## Description
Questie groups the quest as an "Arathi Basin" quest whereas the normal quest log categorizes it as an "Ironforge" quest, intended behavior?

## Wowhead link
One of these two, not sure which one the game uses:
[Wowhead link 1](https://classic.wowhead.com/quest=8371/concerted-efforts)
[Wowhead link 2](https://classic.wowhead.com/quest=8385/concerted-efforts)

## Screenshots
![concerted](https://user-images.githubusercontent.com/24671315/97308278-fd44be80-1860-11eb-95f5-ff9d81070d8d.jpg)

## Questie version
6.1.0

**Comment by BreakBB** [comment]
Hey @MisterTibbs this is indeed a problematic sitatuion. Those quests have been changed to be categorized as Arathi Basin quests. But since the quest log does list them as Ironforge quest I think we should mirror this. Thanks for your report, the fix will be in the next release 👍
