### ISSUE TITLE
Manual complete feature - Greyed out?

### ISSUE THREAD

**Issue by Mazz312** [AeroScripts/QuestieDev#2431]
Is it currently possible to manually complete a quest in Questie Classic? The option only seems available in the search prompt and it is always greyed out. There are a handful of quests, such as Valik in Alterac, that are not able to be completed if done out of order and the like that I would like to be able to manually flag complete. Hiding does not remove these quests from the active list in any given zone.

This existed in Questie of old as "/questie complete" but I can find no functionality here to do the same, at least not thus far. 

If this doesn't exist, could this be added back?

**Comment by BreakBB** [comment]
@Mazz312 Questie will only show quests on the map which you can accept and complete. So if there are quests which you can not accept then we have some corrupted data in our database. For Valik there exists an open issue #2402 which most likely does not on the map, but in the Journey.

You can `Shift + Left click` on a possible quest to manually hide it from the map. But for quests you can not accept it would be great if you could report them here, so we are able to fix it. Manually hiding should never be required if you don't want to simply ignore possbile quests.

**Comment by Mazz312** [comment]
Thank you for the response. 

I guess a better way to put it is that there are likely some quests available in the game that I will never reasonably choose to complete because of extenuating circumstances and it would be nice if there was a way to flag them as hidden/unavailable/complete in the Quests Per Zone tab. Some option hide or flag a quest like we can on the map in this area would alleviate this issue for myself and others who don't like leaving things unfinished in that way. 

Two quick examples from leveling would be the The Harvester in the Barrens, which is a quest drop from a rare spawn Silithid, and Magram Alliance, a quest chain that will forever be available but would require a significant commitment to accomplish after choosing Gelkis in Desolace. Both of those are technically available _and_ should be, but I either have to ignore them (and that nagging feeling!) in the Quests per Zone tracker or I have to set aside an inordinate amount of time to clear them from my Questie lists. Being able to mark them as complete, or something similar like ignored by user would let me "finish" those zones and not require anything on the Questie's team's end for future issues.

It's very minor and I wouldn't consider at all a high priority, but it would be appreciated.

**Comment by BreakBB** [comment]
Thanks for the clarification @Mazz312 . Now I totally understand what the situation is and what would help you.

For now I think about adding an `Ignored` category so you can still see what you have ignored. That would also play together with the point that it is really painful atm to find the quests you hid at any time. Currently you have to know the quest name, search for it and then unhide them.

Adding such a menu point not at zone level but at "continent" level aside to the Class and Dungeon category.

**Comment by Mazz312** [comment]
That would be perfect, thank you.

**Comment by Gogo1951** [comment]
You can shift + click to hide quests. 

No intention of building a way to manually cross off objectives; opens a can of worms.
