### ISSUE TITLE
Jungle Remedy error

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#2433]
The item Jungle Remedy, an objective of the quest Bad Medecine, doesn't drop from Kurzen Jungle Fighters, yet Questie believes it does.

https://classic.wowhead.com/item=2633/jungle-remedy#dropped-by

![WoWScrnShot_102920_223349](https://user-images.githubusercontent.com/54936174/97635110-1c954480-1a37-11eb-8dce-0c057b9c76e9.jpg)

Version 6.1.0

**Comment by drejjmit** [comment]
Thanks for the report. Will be fixed for next release.
