### ISSUE TITLE
Minimap icon and arrow are stuck to my character

### ISSUE THREAD

**Issue by GKCzar** [AeroScripts/QuestieDev#244]
Questie does not seem to work in cities. The map works, but in the minimap any quest that I am currently tracking with the arrow it follows my character around. So the arrow always says that I have arrived.

**Comment by Dyaxler** [comment]
Which city? Darnassus was at one point an issue but it was fixed with a patch.

**Comment by GKCzar** [comment]
It was happening in Ogrimmar for me. Have not checked other cities yet.

**Comment by Dyaxler** [comment]
Are you on an English server?

**Comment by GKCzar** [comment]
Yes, I am playing on Kronos 2.

**Comment by Dyaxler** [comment]
Crap... I see the issue. Looks like there is more than one spelling error in a patched Astrolabe.lua someone submitted a month ago.

I'll scrub through the file and make sure all the cities are spelled correctly.

**Comment by GKCzar** [comment]
Sweet, keep up the good work!

**Comment by Muehe** [comment]
This should be all:

```diff
--- a/!Questie/astrolabe/Astrolabe.lua
+++ b/!Questie/astrolabe/Astrolabe.lua
@@ -630,7 +630,7 @@ WorldMapSize = {
                                xOffset = 15366.59973144531,
                                yOffset = 8126.98388671875,
                        },
-                       Azshara = {
+                       Aszhara = {
                                height = 3381.2498779296902,
                                width = 5070.8327636718695,
                                xOffset = 20343.68286132813,
@@ -649,10 +649,10 @@ WorldMapSize = {
                                yOffset = 4466.5673828125,
                        },
                        Darnassis = {
-                               height = 705.7102838625474,
-                               width = 1058.300884213672,
-                               xOffset = 14127.75729935019,
-                               yOffset = 2561.497770365213,
+                               height = 705.7294921875,
+                               width = 1058.33325195312,
+                               xOffset = 14128.23681640625,
+                               yOffset = 2561.583984375,
                        },
                        Desolace = {
                                height = 2997.916564941411,
@@ -696,7 +696,7 @@ WorldMapSize = {
                                xOffset = 15018.68298339844,
                                yOffset = 13072.81704711914,
                        },
-                       Orgrimmar = {
+                       Ogrimmar = {
                                height = 935.41662597657,
                                width = 1402.6044921875,
                                xOffset = 20747.20068359375,
```

**Comment by Dyaxler** [comment]
Yep. I'm already working on it. I found that one too.

**Comment by Dyaxler** [comment]
Quesite v3.1 has been patched and the Zipfile in the release has been updated.

**Comment by Muehe** [comment]
Hmm after testing this briefly it is kind of working, but when in Orgrimmar the minimap icons are moving when the player moves... This is not (or just barely) happening in Durotar, Teldrassil and Darnassus.

**Comment by Dyaxler** [comment]
Its always done that on the Minimap in Vanilla. In the TBC version it doesn't do that. I believe I remember someone on the Nost forums complaining about it and one of the original authors explained why but I don't recall.
