### ISSUE TITLE
toggle icon quests mobs 

### ISSUE THREAD

**Issue by richardotl** [AeroScripts/QuestieDev#2443]
## Bug description

hi guys I have a question, I just created a new account and I cant toggle the icon near the plates that shows mob quests. It works on my main account so I'm kinda lost, tried pretty much everything and it doesnt work FeelsBadMan any idea what's going on? cheers

## Screenshots

![image](https://user-images.githubusercontent.com/15526476/97902624-26bc8900-1d3e-11eb-9ea2-f4cf5c51b370.png)

**Comment by Gogo1951** [comment]
Hey @BreakBB 

![image](https://user-images.githubusercontent.com/55365231/104856292-7dfede00-58d7-11eb-8d18-f05b9ad4d717.png)

Reopen if you still have problems. Cheers!
