### ISSUE TITLE
"Encrusted Tail Fins" appears available when it shouldn't

### ISSUE THREAD

**Issue by mgalliou** [AeroScripts/QuestieDev#2444]
## Description
"Encrusted Tail Fins" appears as available after only completing "Hardened Shells" while it is also needed to have "Salt Flat Venom" completed

## Wowhead link
https://classic.wowhead.com/quest=1107/encrusted-tail-fins

## Questie version
v6.2.0

**Comment by drejjmit** [comment]
Thanks for the report. Will be fixed for next release.
