### ISSUE TITLE
Incorrect Minimum Level Find th Gems

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#2447]
The minimum level for th Alliance quest Find the Gems is 37, not 40.

https://classic.wowhead.com/quest=2201/find-the-gems

![WoWScrnShot_110520_092452](https://user-images.githubusercontent.com/54936174/98255454-b8660980-1f7d-11eb-96a2-140f55134f09.jpg)

Version 6.2.0

**Comment by drejjmit** [comment]
Thank for the report. Will be fixed for next release.
