### ISSUE TITLE
Quest "James Hyal" (ID 1301) not taking into account alternative breadcrumb

### ISSUE THREAD

**Issue by RaphMad** [AeroScripts/QuestieDev#2448]
## Description
The quest "James Hyal" (ID 1301) is showing up for me as non-completed, even though its not possible to take or complete it.
According to WoWhead comments they are mutually exclusive breadcrumb quests (the other one being "They Call Him Smiling Jim" 1282), so if one is completed, the other should not show up.

(Also note the "James Hyal" breadcrumb consists of 2 steps (ID 1301 and then 1302), while "They Call Him Smiling Jim" (1282) only has one)

## Wowhead link
https://classic.wowhead.com/quest=1301/james-hyal#comments

## Screenshots
![image](https://user-images.githubusercontent.com/5588470/98440141-41548080-20f7-11eb-9ba2-25a30fb876b8.png)
![image](https://user-images.githubusercontent.com/5588470/98440151-4fa29c80-20f7-11eb-8395-9ae0d75b0002.png)

## Questie version
6.2.1

**Comment by drejjmit** [comment]
Thanks for the report. Will be fixed for next release.
