### ISSUE TITLE
Issue around Corrupted Sabers and Well of Corruption (Winna Hazzard).

### ISSUE THREAD

**Issue by EugeneLeclerc** [AeroScripts/QuestieDev#2449]
## Description

The PNJ [Winna Hazzard](https://classic.wowhead.com/npc=9996/winna-hazzard) is shown on my map offering the quest [Corrupted Sabers](https://classic.wowhead.com/quest=4506/corrupted-sabers). In reality, she is only offering [Well of Corruption](https://classic.wowhead.com/quest=4505/well-of-corruption) which unlocks Corrupted Sabers. The issue is persisting after multiple reloads and logouts, with and without accepting Well of Corruption.

## Wowhead link

https://classic.wowhead.com/npc=9996/winna-hazzard
https://classic.wowhead.com/quest=4505/well-of-corruption
https://classic.wowhead.com/quest=4506/corrupted-sabers

## Screenshots

![image](https://user-images.githubusercontent.com/44815069/98541891-68928580-2290-11eb-8739-1e9950997f7f.png)
![image](https://user-images.githubusercontent.com/44815069/98541917-6fb99380-2290-11eb-9a59-1deff288258a.png)

## Questie version

I'm running Questie v6.2.1, which is the latest at the time I'm writing this.

Couldn't find any issue about this, I'm sorry if I'm just bad at searching. 

Thanks a lot for you work on Questie !

**Comment by drejjmit** [comment]
Fixed with b84134a9e28b6f44b4eac04f3b7abff3018f9b57
Thansks for the report. Will be included in next release.
