### ISSUE TITLE
Can't track more than 5 quests at a time

### ISSUE THREAD

**Issue by Ghamarro** [AeroScripts/QuestieDev#245]
I remember the previous versions of Questie being able to track more than 5 quests simultaneously, and since I didn't find any mentions about it in the changelog supplied with the actual addon, I decided to post it here in case it is a bug.

**Comment by Dyaxler** [comment]
Are you using just Questie with no other mods? Not sure if the default wow client limits this or not but if you use EQL3 along with Questie, I know for a fact that I can track more then 5 quests at a time.

Also, if you're using only Questie then "tracking" quests is limited to quests with "trackable" objectives. You can't track an quest finisher NPC like you can if you're running EQL3 or MonkeyQuest or some other QuestLog mod. This is the version that most everyone, including myself, use...

http://addons.us.to/addon/eql3

**Comment by Schaka** [comment]
Default client limit is 5 (and the tracker itself is limited and works like shit too). Which is why we originally hooked the default quest log and made it ignore its own tracking + just added everything to QuestieTracker.

**Comment by Ghamarro** [comment]
I was using a plethora of other mods but nothing that would affect the quest log or quest tracking in anyway, save for Questie. I downloaded EQL3 from the link you gave and it works great. Now I can track more than 5 quests at a time. Thanks!
