### ISSUE TITLE
Map/Minimap Icons Aren't Being Shown

### ISSUE THREAD

**Issue by SonicMcCall** [AeroScripts/QuestieDev#2450]
Map/Minimap icons aren't being shown. When I went into the Questie settings, I unticked and re-ticked the checkbox for "Enable Available Quest Icons" and "Enable Objective Icons" and then they would flicker on for a split second and then disappear again on my minimap. there is no sign of them on my map either. The mod also occasionally disregard config choices such as "Hide Unexplored Area Icons" and shows all available quests and objectives icons.

I'm using ver 6.2.1

**Comment by tominosik** [comment]
Same for me. I found out a workaround by clicking + and - minimap icon. But is it annoying.

**Comment by BreakBB** [comment]
Hey @SonicMcCall and @tominosik could you verify that this issue also happens when you have just Questie enabled?

And it would also be nice if you could share your "General" settings.

**Comment by tominosik** [comment]
@BreakBB Here they are. I have just one addon active now, Questie-v6.2.3

https://ibb.co/BgQ2T19
https://ibb.co/nwSfqNX
https://ibb.co/m6nj0XK

Hope it helps. I have already a gray hair because of this problem. :)

**Comment by BreakBB** [comment]
@tominosik and @SonicMcCall go ahead and try to disable the rotating minimap. I remember some issue about this.

**Comment by tominosik** [comment]
@BreakBB Hi Bjorn, sorry for late answer. I think it is working better with no-rotate minimap. But still, would be nice to find a solution for the minimap with rotate function on. I feel like drunk without it. :)

**Comment by BreakBB** [comment]
@tominosik Yes, we should really fix this. Problem this our underlying library (HereBeDragons) which we use to draw to the map/minimap, is causing this issue. But we are heavily considering to move away from the library as preparation of Classic TBC.

**Comment by Gogo1951** [comment]
May be fixed in #2500 ; but not something we have a lot of control over given underlying dependencies.
