### ISSUE TITLE
Questie receiving errors when BoTD Guild Addon is also installed

### ISSUE THREAD

**Issue by stealthyloon** [AeroScripts/QuestieDev#2452]
Questie V6.2.1

Install the botd-guild-addon-beta addon and then hover over an icon on the map and you will receive this error.

Message: ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:555: attempt to concatenate local 'argbHex' (a nil value)
Time: Fri Nov 13 08:41:10 2020
Count: 1
Stack: ...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:555: attempt to concatenate local 'argbHex' (a nil value)
...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:555: in function `GetObjectiveTooltip'
...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:713: in function `handleMapIcon'
...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:738: in function <...ddOns\Questie\Modules\FramePool\QuestieFramePool.lua:592>

Locals: self = <table> {
 unusedFrames = <table> {
 }
 lastTooltipShowHack = 16657.996000
 _lastMiniInside = false
 GetAvailableOrCompleteTooltip = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:455
 IsMinimapInside = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:228
 GetObjectiveTooltip = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:493
 wayPointColorHover = <table> {
 }
 AddTooltipsForQuest = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:571
 QuestieCreateFrame = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:217
 QuestieTooltip = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:592
 GetEventObjectiveTooltip = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFramePool.lua:482
 numberOfFrames = 282
 wayPointColor = <table> {
 }
 usedFrames = <table> {
 }
 allFrames = <table> {
 }
 _lastMiniInsideCheck = 16405.917000
}
icon = QuestieFrame273 {
 0 = <userdata>
 FadeOut = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:339
 frameId = 273
 loaded = true
 FakeUnhide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:383
 data = <table> {
 }
 FakeHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:367
 _loaded = true
 AreaID = 1
 texture = <unnamed> {
 }
 UiMapID = 1426
 BaseOnShow = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:209
 BaseOnHide = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:233
 glow = QuestieFrame273Glow {
 }
 UpdateTexture = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:237
 y = 44.437653
 x = 25.179299
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:272
 miniMapIcon = false
 GlowUpdate = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:185
 FadeIn = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:353
 ShouldBeHidden = <function> defined @Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:398
}
tooltips = <table> {
 1 = <table> {
 }
}
iconData = <table> {
 ObjectiveTargetId = 1211
 Type = "item"
 IconScale = 1
 ObjectiveData = <table> {
 }
 Id = 412
 QuestData = <table> {
 }
 GetIconScale = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:815
 touchedPins = <table> {
 }
 Name = "Leper Gnome"
 IconColor = <table> {
 }
 Icon = "Interface\AddOns\Questie\Icons\loot.blp"
 ObjectiveIndex = 2
}
text = "0/8 Gyromechanic Gear"
color = ""
anotherPlayer = true
quest = <table> {
 Mywarlock = <table> {
 }
}
name = "Holyloon"
className = "Paladin"
classFilename = "PALADIN"
rPerc = ""
gPerc = nil
bPerc = nil
argbHex = nil
(*temporary) = " (|c"
(*temporary) = nil
(*temporary) = "Holyloon)"
(*temporary) = ""
(*temporary) = ""
(*temporary) = ")"
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 1 = <table> {
 }
}
(*temporary) = <table> {
 0/8 Gyromechanic Gear (Mywarlock) (Nearby) = <table> {
 }
}
(*temporary) = "/"
(*temporary) = "8"
(*temporary) = " "
(*temporary) = "Gyromechanic Gear"
(*temporary) = " (Mywarlock)

**Comment by stealthyloon** [comment]
Another Error:

Message: ...nterface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:254: attempt to concatenate local 'argbHex' (a nil value)
Time: Fri Nov 13 09:03:04 2020
Count: 4
Stack: ...nterface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:254: attempt to concatenate local 'argbHex' (a nil value)
...nterface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:254: in function `GetTooltip'
...e\AddOns\Questie\Modules\Tooltips\TooltipHandler.lua:27: in function <...e\AddOns\Questie\Modules\Tooltips\TooltipHandler.lua:6>
[C]: ?

Locals: self = <table> {
 lastGametooltipCount = 0
 lastGametooltipUnit = "Leper Gnome"
 lastGametooltipType = "monster"
 lookupByKey = <table> {
 }
 lastGametooltip = "Leper Gnome"
 GetTooltip = <function> defined @Interface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:86
 RemoveQuest = <function> defined @Interface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:72
 lastFrameName = ""
 RegisterObjectiveTooltip = <function> defined @Interface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:40
 RegisterQuestStartTooltip = <function> defined @Interface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:56
 Initialize = <function> defined @Interface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:291
 private = <table> {
 }
 lastItemRefTooltip = ""
 lookupKeysByQuestId = <table> {
 }
}
key = "m_1211"
tooltipData = <table> {
 412 = <table> {
 }
}
npcTooltip = <table> {
}
anotherPlayer = true
tip = <table> {
}
playerName = "Holyloon"
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 412 = <table> {
 }
}
(for control) = 412
questId = 412
questData = <table> {
 title = "[10] Operation Recombobulation"
 objectivesText = <table> {
 }
}
hasObjective = false
tempObjectives = <table> {
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
(for control) = 1
_ = 1
playerList = <table> {
 Holyloon = <table> {
 }
 Boldbraids = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Holyloon = <table> {
 }
 Boldbraids = <table> {
 }
}
(for control) = "Holyloon"
objectivePlayerName = "Holyloon"
objectiveInfo = <table> {
 color = ""
 text = "   0/8 Restabilization Cog"
}
playerInfo = nil
playerColor = nil
playerType = ""
_ = "Paladin"
classFilename = "PALADIN"
_ = ""
_ = nil
_ = nil
argbHex = nil
(*temporary) = "   0/8 Restabilization Cog"
(*temporary) = " (|c"
(*temporary) = nil
(*temporary) = "Holyloon)"
(*temporary) = ""
(*temporary) = ""
(*temporary) = ")"
(*temporary) = "attempt to concatenate local 'argbHex' (a nil value)"
QuestieTooltips = <table> {
 lastGametooltipCount = 0
 lastGametooltipUnit = "Leper Gnome"
 lastGametooltipType = "monster"
 lookupByKey = <table> {
 }
 lastGametooltip = "Leper Gnome"
 GetTooltip = <function> defined @Interface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:86
 RemoveQuest = <function> defined @Interface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:72
 lastFrameName = ""
 RegisterObjectiveTooltip = <function> defined @Interface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:40
 RegisterQuestStartTooltip = <function> defined @Interface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:56
 Initialize = <function> defined @Interface\AddOns\Questie\Modules\Tooltips\Tooltip.lua:291
 private = <table> {
 }
 lastItemRefTooltip = ""
 lookupKeysByQuestId = <table> {
 }
}
QuestieDB = <table> {
 objectCompilerOrder = <table> {
 }
 questDataOverrides = <table> {
 }
 _QueryItemSingle = <function> defined @Interface\AddOns\Questie\Database\compiler.lua:939
 itemCompilerOrder = <table> {
 }
 questKeys = <table> {
 }
 questFlags = <table> {
 }
 objectDataOverrides = <table> {
 }
 _npcAdapterQueryOrder = <table> {
 }
 NPCPointers = <table> {
 }
 IsActiveEventQuest = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:325
 ObjectPointers = <table> {
 }
 IsComplete = <function> defined @Interface\AddOns\Questie\Database\QuestieDB.lua:300
 factionTemplate = <table> {
 }
 IsParentQuestActive = <function> defined @Interface\AddOns\Questie

**Comment by Gogo1951** [comment]
Hey @stealthyloon ,

Really hard for us to put time into this, sorry.

https://www.curseforge.com/wow/addons/botd-guild-addon-beta

Great big red letters "still in beta" -- doesn't seem like a stable addon and likely they haven't tested their code. Hasn't been updated since November 2020, only has 188 total downloads... 

Try reporting the error to them, and if they take this out of beta and it's still causing issues we'll look into it.

Cheers!

![image](https://user-images.githubusercontent.com/55365231/105751456-a2783d00-5f0b-11eb-91ec-84255d2c4b57.png)


![image](https://user-images.githubusercontent.com/55365231/105751487-aa37e180-5f0b-11eb-8a4c-80c9d074457d.png)

**Comment by stealthyloon** [comment]
I am the developer for BoTD Addon and I did check through all of my code and changed everything I could. Yes the code hasn’t been updated since November 20th and I submitted my GitHub ticket on November 13th. Thanks for the excuse though.
