### ISSUE TITLE
world map tracker for party members

### ISSUE THREAD

**Issue by Thaiselaise** [AeroScripts/QuestieDev#2453]
it would be nice if you could see world map quest trackers for party members, if they have a different quest or you are boosting a low level (also location for quest)
![99189343-0ab6df80-2761-11eb-8088-0890a9cafe57](https://user-images.githubusercontent.com/74501002/99189464-8d3f9f00-2761-11eb-8a63-858f1e2ea0ad.png)
![Capture1edit](https://user-images.githubusercontent.com/74501002/99189466-8dd83580-2761-11eb-951f-c2a6bf83a24d.PNG)

**Comment by Gogo1951** [comment]
Will be addressed in #2499
