### ISSUE TITLE
Error when accepting "Investigate the Scourge of <City>" quests.

### ISSUE THREAD

**Issue by MisterTibbs** [AeroScripts/QuestieDev#2460]
## Bug description
When accepting the six quests listed on [this Wowhead](https://classic.wowhead.com/guides/wow-classic-scourge-invasions#scourge-invasion-quests) guide under "2. Investigate the Scourge" you get an error message. The quests also do not show up as availabe on the map or the minimap, I guess they simple are not in the database.

## Screenshots
![city](https://user-images.githubusercontent.com/24671315/101299060-f2eaec80-3830-11eb-94b5-ca4ea2ae8b87.jpg)

## Questie version
6.2.3

**Comment by siementaja** [comment]
![image](https://user-images.githubusercontent.com/76152030/102460829-3b37b500-4050-11eb-9d04-e93d61778f50.png)

Same issue here with the Undercity quest
