### ISSUE TITLE
mini freezes when mouseover npc's

### ISSUE THREAD

**Issue by Ascencio** [AeroScripts/QuestieDev#248]
Whenever I mouseover any NPC's I get a one-second screen freeze. When I turn off questie the issue resolves itself. I've tried turning up the script memory as well as installing other versions of questie without success. As for other (possibly interfering addons) I run Atlas/Atlasloot/Cartographer/Onebag. I've played up to lvl 49 with these same addons however before this issue came apparent. 

Has anyone come across this or could help me out nevertheless?

**Comment by crumdidlyumshis** [comment]
https://github.com/AeroScripts/QuestieDev/issues/226

**Comment by Dyaxler** [comment]
It's also stated in the FAQ: https://github.com/AeroScripts/QuestieDev/blob/master/Readme%20%26%20FAQ.txt

**Comment by catterpiler74** [comment]
same problem, and i can not find answer for that problem :(

**Comment by Schaka** [comment]
The only solution is to turn off vsycn and take measures to keep your FPS as high as you can get them. There is only "so much" WoW con process per frame (that's how Lua is executed, alongside WoW's visual rendering). If you have more frames, you will get less stutter.

**Comment by catterpiler74** [comment]
Vsync already off.   I have only 25-30 fps on my old notebook. The problem is not solved

**Comment by Schaka** [comment]
It can't be solved then. If your laptop is only able to generate the minimum amount of FPS, it's a performance issue.

Disable all addons that modify the game tooltip except for Questie. 
These are the solutions to make the issue less annoying, there's no way to truly solve it.

**Comment by catterpiler74** [comment]
the problems were only then with the quest where you need to bring 15 pieces of silk cloth.
quest is done and the lags are gone. maybe this will help, all the problems is loot from citizens and guards with which it is possible drops silk cloth for Horde I think...

**Comment by Muehe** [comment]
Depending on the source, silk cloth is dropped by 400-1000 NPCs. Basically this is the same issue as #247 
Nothing much there can be done but untracking the quest(s) placing too many notes.
