### ISSUE TITLE
Minimap/map not showing quest objectives for grey quests

### ISSUE THREAD

**Issue by Fjaeset89** [AeroScripts/QuestieDev#249]
Hello,

I am currently trying to grind reputation with Darnassus. Doing so, I started doing the grey low level quests in Teldrassil. As a level 60, all these quests are grey for me. But none of the quest objectives are visible on the map/minimap, as they always have been for me before. I have tried numerous settings to try and fix this, and googled the issue, but can't find anything. I find it hard to believe that it's not possible, so I must just have missed an obvious option for this. 

Anyway, hope you can help, thanks in advance.

**Comment by Dyaxler** [comment]
Look in the FAQ: https://github.com/AeroScripts/QuestieDev/blob/master/Readme%20%26%20FAQ.txt

Specifically these two settings...

> /questie minlevel
> /questie setminlevel

The min level setting's default is 5 which means that any quest that is 5 levels below your current level will be hidden. Just toggle the minlevel off.

**Comment by Fjaeset89** [comment]
> I have tried numerous settings to try and fix this, and googled the issue, but can't find anything.

I have tried these settings, and it doesn't fix the issue.

**Comment by Fjaeset89** [comment]
![questie](https://cloud.githubusercontent.com/assets/19599820/15594129/fb742b56-23b2-11e6-8946-233beb935860.PNG)

This picture is with minlevel filter off. As shown, none of the objectives are visible on the map

**Comment by Dyaxler** [comment]
You should see the ! on the mini map and world map but when you visit the NPC it won't show an icon above their heads. The game hides them. The "Show Low Level" quests option wasn't available in Vanilla wow but if you talk to the NPC you'll see the quest. The icons above their heads are invisible.

**Comment by Fjaeset89** [comment]
That's not what I am searching after. I know the ! doesn't show ingame. I want Questie to show the OBJECTIVES of the quest on the minimap, as it does with green+ quests.

**Comment by Dyaxler** [comment]
You have to obtain the quest first before the quest objectives show up on the Worldmap / Minimap...

**Comment by Dyaxler** [comment]
Ahhh... wait a second. I see from the screen shot that you have a couple of the quests and the objectives aren't on the Worldmap.

Can you do a /questie settings and show me the output?

**Comment by Fjaeset89** [comment]
I am afraid you don't understand what I am writing/showing in the picture. Ofcourse I have obtained the quest first. 

My experience step-by-step:

1. I pickup a grey quest in Teldrassil.
2. The quest is shown in the QuestTracker
3. I look at the minimap and map for objectives
4. Objectives are NOT shown on the minimap/map
5. I have to read every quest 
6. Questie becomes obsolete
7. Im here now asking for help :)

**Comment by Fjaeset89** [comment]
![2](https://cloud.githubusercontent.com/assets/19599820/15594200/d4ba9aa8-23b3-11e6-8682-186867fadaaf.PNG)

**Comment by Dyaxler** [comment]
Excellent... now can you attach your !Questie.lua file from your WTF directory in your characters SavedVariables folder so I can take a look at the quest tracker data?

**Comment by Fjaeset89** [comment]
When Kronos went down I went to play on Rebirth. I experienced some issues, and read that I should delete my WTF folder if I came from another private server.

The WTF folder didn't rebuild, so I don't have one now :) 

There is a Questie.lua file in the !Questie folder under addons if that helps

**Comment by Dyaxler** [comment]
No it doesn't... that file contains the program code. If the WTF folder didn't rebuild then that is your issue. WTF is required to exist in order to run WoW as the client saves all of it's user settings there. Are you sure you aren't talking about the WDB folder? Deleteing your cache when switching between servers is the only files you need to delete inside the WDB folder NOT the WTF. You can keep those files since the client will build a separate directory for each server you play on.

**Comment by Fjaeset89** [comment]
I see. Well, thanks for the help so far. I'll try to fix the WTF situation and then come back to you. :)

**Comment by Dyaxler** [comment]
Just create a WTF folder in the root of your install directory and your game client should do the rest.

![capture](https://cloud.githubusercontent.com/assets/17400948/15594688/cd45a796-236c-11e6-97e3-e6bdc8528d09.JPG)

**Comment by Muehe** [comment]
Sounds like WoW doesn't have write access in its directory. Normally a new WTF folder would be created upon starting the game client if none is present.
