### ISSUE TITLE
Map target issues

### ISSUE THREAD

**Issue by bigbeardkrakauer** [AeroScripts/QuestieDev#2491]
## Bug description
 quest targets on map and available new quests don’t show up on main map or minimap. They stopped showing up mid game. Did EVERYTHING to get addon to work. Only thing shows on map is where finished quests can be turn in at. 

## Questie version
 6.4.2

**Comment by Gogo1951** [comment]
Should get addressed in map rework for BC. #2500 and new settings. Closing as it's not a high-priority as a stand alone issue.
