### ISSUE TITLE
Screen crashing while using Questie on MacBook Air M1

### ISSUE THREAD

**Issue by Avrexa** [AeroScripts/QuestieDev#2497]
## Questie version

Hello, 
I wanted to use questie on wow classic. sitting it up all works fine. I can login prefectly and the add-on also loads in and I can see al the quests. but after a few min my screen starts flashing and I can't play. I made a video of wat happens when I want to play. I have to fully delete questie form my folder for wow to work again. I am using the new MacBook Air M1 (idk if that might have to do something with it) 

https://user-images.githubusercontent.com/77928030/105634194-28897a80-5e5d-11eb-9c40-836d95025146.mov

**Comment by Gogo1951** [comment]
Not a ton of into here to help diagnose the problem. Sorry mate. We'll keep an eye out.
