### ISSUE TITLE
Infinite loading screen with Questie

### ISSUE THREAD

**Issue by Logonz** [AeroScripts/QuestieDev#25]
Questie creates an Infinite loading screen when switching Maps (HS or Boat etc)

Tried with completely new WTF, WDB and no other addons, same issue WoW.exe process is running 12% on an i7 4770k and is just frozen.

**Comment by Schaka** [comment]
Haven't tested that in a while. I'll take care of it right away once I get home. For now, you can comment out line 304 and see if that solves the issue for you.

**Comment by Logonz** [comment]
it "Worked" as soon as you open the questlog the game freezes again. probably some kind of infinite loop. Will look into it myself as well.

**Comment by Schaka** [comment]
Fixed as of https://github.com/AeroScripts/QuestieDev/commit/0594e0a97c731eccfddfc7cb85538ebd29c0f816
