### ISSUE TITLE
Darkened item sell price - Minimap

### ISSUE THREAD

**Issue by erkankhan** [AeroScripts/QuestieDev#250]
I have spent a bunch of time to try and narrow down what causes the darkened sell price, although this observation might already be known. 

The glitch occurs when **hovering** over an icon on the **minimap**.
Using the regular map works fine.

I tested this with several different addons, including a fresh install while only using questie. 
I have tried it with several versions of questie ranging from 2.0 to 3.1 .

Additionally it seems like Questie interacts with how normal item tooltips are displayed, here is a comparison with and without Questie with the addon PriceDB to display sell price:
http://imgur.com/S9bp5Te

**Comment by mubbleman425** [comment]
I'm having the same issue with the darkened sell prices. It almost looks like the text for the sell price is behind the gray tooltip box.

**Comment by n0rc** [comment]
Same here with v3.68. Seems to be related with  #128, #146 and #225. This is definitely caused by Questie, I don't use any other addon right now.

Unfortunately, the issues were all closed without a solution. :(
