### ISSUE TITLE
Missing hoggar quest

### ISSUE THREAD

**Issue by beren12** [AeroScripts/QuestieDev#251]
at westbrook garrison @24.5,74.7

**Comment by Muehe** [comment]
Wild guess here: Questie has no data for either objects or items starting quests.

**Comment by beren12** [comment]
No, the quest starts from a wanted poster. It didn't show up on the map, and it didn't track the objective. Doing it again, one I put a checkmark to track the quest the location of hogger himself showed up. I have to do this to random quests here and there for questie to realize I'm on it. It won't show any objectives on the map until I kill or gather one of the quest items.

**Comment by Muehe** [comment]
Ohh. I was only talking about the quest start icons. You have to have "/questie showquests" activated if you want quest objectives to appear instantly. The quests get added to the tracker automatically when you advance, so that's why they show up at that point.

**Comment by beren12** [comment]
Well questie knows about the hogger quest and where he is, but so far on none of my 4 toons that did it, did it show a ! on the map for the wanted poster quest. Seemed odd to me

**Comment by Muehe** [comment]
Yeah, the poster not showing is definitely a bug. But could you close #253 ? That should be the "/questie showquests" thing as well.
