### ISSUE TITLE
Missing warlock quest objectives

### ISSUE THREAD

**Issue by beren12** [AeroScripts/QuestieDev#253]
http://db.vanillagaming.org/?quest=4783 is the link to it.

**Comment by Muehe** [comment]
That's weird, shows fine for me. Maybe a problem with your SavedVariables?

**Comment by beren12** [comment]
No you are right, for some reason the quest objective locations doesn't always show up until you kill the first quest mob. Renaming bug.

**Comment by Muehe** [comment]
I didn't kill any, it showed nonetheless.
