### ISSUE TITLE
Quest Tracking Interface

### ISSUE THREAD

**Issue by impire123** [AeroScripts/QuestieDev#254]
The Quest Tracking seems to be showing up above the player profile on the upper-left corner of the screen. I'm in Windows Mode.

**Comment by Muehe** [comment]
[FAQ:](https://github.com/AeroScripts/QuestieDev/blob/master/Readme%20%26%20FAQ.txt#L11)
>  - How do I move the QuestieTracker and QuestArrow?
>	* Hold down CTRL + Shift + Hold Left Mouse Button + Drag
