### ISSUE TITLE
Quest: Enraged Wildkin Item: Jaron's Supplies - Wrong Location

### ISSUE THREAD

**Issue by x003** [AeroScripts/QuestieDev#255]
For the quest Enraged Wildkin the quest item Jaron's Supplies should be at 61,4 60,7 in Winterspring but questie is showing the objective for it just outside of Menthil Harbor instead for some reason

**Comment by Muehe** [comment]
The reason is the name of the object ending the quest:

https://vanilla-twinhead.twinstar.cz/?search=Damaged+Crate

Not sure how Questie handles objects, but I'd guess by name...
