### ISSUE TITLE
Questie causes stuttering

### ISSUE THREAD

**Issue by b0b0bg** [AeroScripts/QuestieDev#258]
I've been using Questie for weeks and haven't had any problems so far but today as i clicked on a quest to track it the game started stuttering. This doesn't happen when Im not tracking a quest but when i click on the quest to track it the game immediately starts to stutter. Deleting Questie fixes the problem but that's not a real fix for me :)

**Comment by Schaka** [comment]
It's drawing too many frames. You will just have to leave the quest untracked until it's done.
Maybe @Dyaxler can build throttling for the amount of frames on the Minimap for a specific zone (I've only encountered this in STV).

**Comment by Muehe** [comment]
@b0b0bg Mind sharing which quest this was happening with? Would like to research.

**Comment by marius366** [comment]
Sorry for bad english. got this stutter whenever i click or mouse over an NPC, very unpleasant thing to have.Disabling tracker didn't help me and other different questie settings. I found that Quest called "Items of Some Consequence" was the trigger and after finishing the quest everything went normal.

**Comment by Muehe** [comment]
@marius366 That would be the Silk Cloth causing this again. Try playing with the `/questie`options. Especially `/questie showquests`. When disabled, it will remove all quests from map that are not currently tracked.
