### ISSUE TITLE
Tracker will not show up

### ISSUE THREAD

**Issue by TRSolo** [AeroScripts/QuestieDev#260]
I have Questie 3.1 installed on Kronos (WoW 1.12.1) and on all my characters but one (6) the tracker doesn't show up.  I've tried resetting, /questie tracker to make sure it was displaying, everything.  Any ideas what would be causing this?

**Comment by Muehe** [comment]
First guess would be another addon. Check #231 #242 and if that doesn't help [other tracker realted issues](https://github.com/AeroScripts/QuestieDev/issues?utf8=%E2%9C%93&q=is%3Aissue+tracker).

**Comment by TRSolo** [comment]
I dropped Questie 3.1 alone in a fresh 1.12.1 Kronos client today.  No other addons at all;  same issue the tracker was no where in sight.

**Comment by TRSolo** [comment]
Bump still having this problem.

**Comment by TRSolo** [comment]
You can close this.  The tracker popped up after I cleared the cache.
