### ISSUE TITLE
'ABANDON_QUEST_WITH_ITEMS' (a nil value)

### ISSUE THREAD

**Issue by kasper0999** [AeroScripts/QuestieDev#265]
Hi,
I'm using the Questie 3.1 and him gives this error:
http://imgur.com/oKW3jwR
What do I need to do?

**Comment by Muehe** [comment]
Well this was mentioned already in #230, I'm not sure how that was solved as it is not noted in the issue... Have you made sure you have write access to the place WoW is located? E.g. it is not in a "program files" folder?

**Comment by kasper0999** [comment]
No, my game folder is: I:\Games\World of Warcraft 1.12

**Comment by kasper0999** [comment]
Okey, I'm reinstall game and all is already good.

**Comment by Muehe** [comment]
Next time, try deleting Cache and WDB folders. Some private servers might write bad (i.e. wrong) data into them.
