### ISSUE TITLE
Compatibility issue with tooltip addons

### ISSUE THREAD

**Issue by OskarOskar** [AeroScripts/QuestieDev#268]
When using addons that change the behavior of tooltips along with Questie, the feature that shows if a mob is part of a quest, doesn't work.
I've tested this with EQCompare and FlightTime, and both of them break it.

![wowscrnshot_072416_014225](https://cloud.githubusercontent.com/assets/6757518/17081113/a5a211a4-514b-11e6-984a-d1d4fe6cf083.jpg)

**Comment by Schaka** [comment]
Can you try downloading the current master branch (as opposed to the latest release) and give it another try? I haven't gotten around to testing the latest 2 pull requests in detail and haven't published a new release for that reason.

**Comment by OskarOskar** [comment]
Unfortunately that seems to produce the same result as before.

**Comment by Dyaxler** [comment]
Please try v3.5 and report back. :)
https://github.com/AeroScripts/QuestieDev/releases/latest
