### ISSUE TITLE
Autotrack without other addons?

### ISSUE THREAD

**Issue by ShaunDreclin** [AeroScripts/QuestieDev#269]
Is there any way to auto track and track quests without objectives without needing a quest log overhaul addon like eql3? If they can track them Questie should be able to too :o

**Comment by Muehe** [comment]
Have you tried this again when you upgraded to 3.1? Questie shouldn't need **any** other addon. Have a look at the [FAQ](https://github.com/AeroScripts/QuestieDev/blob/master/Readme%20%26%20FAQ.txt) and the ingame chat commands for controlling the tracking behavior.

**Comment by ShaunDreclin** [comment]
I want quests to be added to the tracker as soon as I accept them and removed when they're completed. Does questie have that? The only tracker options I see are to completely disable the tracker (and level filtering)

**Comment by Muehe** [comment]
FAQ:
>Questie Slash Commands - use "/questie" to show the help menu in game.
>[...]
>  - showquests: Toggles on and off the ability to always show quests on the Worldmap / Minimap - tracked or not tracked.

**Comment by ShaunDreclin** [comment]
That shows them on the maps but not in the quest tracker

**Comment by Muehe** [comment]
Oh, that's what you meant. You can Shift+Click in quest log. I'm not sure right now, but there might also be an option in the Interface settings related to tracking all quests. If those two options don't work for you, you are stuck with using EQL3 or similar.

**Comment by ShaunDreclin** [comment]
Yeah I was wanting it automatic, the option in the interface settings only track when you make progress on an objective, not when you pick up the quest.

**Comment by thehaplo** [comment]
I have the same issue here. 

When I was using early versions of Questie for vanilla, it was autotracking all my quests and adding them to my play-screen so I could easily track them. But after upgrading my Questie to latest version, it stopped auto-adding my quests to questtracker. Now, I must add quests manually by Shift+Click on Blizz's Quest Log. But there is a limit; only 5 quests can be tracked, and everytime I have to change it manually when I change my zone, or when I decided to go for other quests. 

"Automatic Quest Tracking" is already enabled on interface settings.

**Comment by Plaetomat** [comment]
I struggled with the same issue while using an old version of questie and adding EQL3 to it.

One thing you can do with the newest version of Questie is that you disable the Questie quest tracker and instead use the quest tracker from EQL. In my opinion you get an better overview over things, you can display as many quests as you want and the two addons don't keep on bugging each other.

Greetz
