### ISSUE TITLE
Error "Cannot destroy note "213921" at "Loch Modan" if it does not exist

### ISSUE THREAD

**Issue by AndersBrohus** [AeroScripts/QuestieDev#27]
I get this error if Questie got a quest "marked" and then abandon it.

It says it's on the line 809.

**Comment by AeroScripts** [comment]
Oh no! I thought this bug was fixed, I'll take a look at it now. In the meantime it should be fixable by deleting the WTF folder (or JUST WTF/account/questie.lua/.lua.back)

**Comment by AndersBrohus** [comment]
Okay nice, thanks for a great addon! :D :+1:

**Comment by AeroScripts** [comment]
Should be fixed as of 18c90d8fcf4d0fbb9abce1495ab4a1b5b1e68e68, updating release with v1.0i shortly. And thank you for helping with it by submitting a bug :o

**Comment by AndersBrohus** [comment]
No problem, thanks :smile:

**Comment by AeroScripts** [comment]
Closing this because it's fixed
