### ISSUE TITLE
Questie 3.1 abandoning the wrong quest

### ISSUE THREAD

**Issue by fildew** [AeroScripts/QuestieDev#271]
I and several others of my friends have a problem with Questie not abandoning the selected quest. It seems to abandon the quest furthest down in the questlog, however I'm not completely sure that is always the case.

For example, if I select quest A and click abandon, the confirmation window says 'Abandon "Quest Z"' and by clicking yes, quest Z will be abandoned, obviously.

I have tried disabling other possibly conflicting addons to no avail; the only thing that helps is temporarily disabling Questie 3.1 and abandoning the right quest.

Edit: I cannot reliably reproduce the issue, it seems to occur at random.

**Comment by laytya** [comment]
what addons you have? can you list it? I had same problem w/ NotesUNeed. NotesUNeed not properly use quest scan.

**Comment by fildew** [comment]
I think it doesn't matter, only disabling Questie works. Even when disabling all other addons it still occurs. I'm not sure if it has occured since I downloaded Questie 3.2 though, I will try to get back to you when Nost is back up again and I've had the opportunity to test it thoroughly!

**Comment by fildew** [comment]
Was gonna abandon a quest today and got this:

![image](https://cloud.githubusercontent.com/assets/20835970/23765573/ecd51a98-0501-11e7-97e1-c75a5d96eddf.png)

Restarting the WoW client fixed the issue, so there seems to be some event triggering this ingame.
