### ISSUE TITLE
Quest tracker

### ISSUE THREAD

**Issue by grinsteindavid** [AeroScripts/QuestieDev#273]
Sometimes the quest tracker is not updated like when I just recently got a quest item and the quest tracker doesn't know it.

**Comment by crumdidlyumshis** [comment]
This is actually a server issue. I have found this issue on Warmane as well. Either of their realms.

**Comment by Schaka** [comment]
Server is sometimes not sending the correct events. Unfortunately, nothing we can do about it (happens to the default tracker too).

Also, this project is currently not in development.
