### ISSUE TITLE
Map Toggle Questie icon, cosmetic

### ISSUE THREAD

**Issue by slacker3007** [AeroScripts/QuestieDev#286]
Toggle Questie Icon is above Continent and Zone buttons. Issue is present with /questie resizemap and without.
Screenshots:
http://imgur.com/a/oCG7E

**Comment by AeroScripts** [comment]
Yes, I just noticed this in someone's video. I'll add an option to remove the button as well as change it's default position to fix this issue.

**Comment by AeroScripts** [comment]
Everyone ok with it's position being opposite the zoom out button on the other side of the zone drop-downs by default?

**Comment by slacker3007** [comment]
suggested position seems to be like good option

**Comment by AeroScripts** [comment]
Fixed, closing this
