### ISSUE TITLE
Option to limit minimap icons to a square area instead of a round one

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#287]
Some minimap addons change it's appearance to be square instead of round. Some have requested an option to make the minimap icons fit properly into these square-mode minimaps.

**Comment by laytya** [comment]
i did some changes to automatic work of this option. But it works w/ some addons. Can you say what addon not working?

**Comment by SalviaSage** [comment]
I can confirm that this already works with some square map addons. Namely, "Squeenix" addon works well. 
I don't think anything else needs to be done by the Questie addon. 
This task can be handled by the square minimap addons.

**Comment by laytya** [comment]
I Just need name of another square minimap addons to make compatibility to it.

**Comment by SalviaSage** [comment]
Laytya; Thanks for your reply. I wanted to talk with you. I also sent you a steam friend list request.

I was using an addon called "YASMM" before. Here is a link to it.
http://www.wowinterface.com/downloads/info5583-YASMM-YetAnotherSquareMiniMap.html

Questie's minimap icons were appearing as if the minimap was a round map so I switched to squeenix which was working the way it should be. Were you the one who tweaked squeenix to work the way it should with questie's minimap icons? That addon works perfectly.

If you want, you can make a similar fix for YASMM and other maps out there, but we already have squeenix working.

IMPORTANT:
Please look at this issue that I submitted on your repository.
https://github.com/laytya/MinimapButtonBag-vanilla/issues/2

**Comment by laytya** [comment]
YASMM is horrible =))) even dont want look at it =))

use simpleMinimap - its best for vanilla

**Comment by Dyaxler** [comment]
Use SpartanUI - https://github.com/Dyaxler/SpartanUI_Vanilla/releases/latest - problem solved.

https://github.com/Dyaxler/SpartanUI_Vanilla/blob/master/ScreenShots/FullUI.jpg

**Comment by laytya** [comment]
dont like any UI*...

**Comment by Krabator** [comment]
Hi laytya,

I am using simpleMinimap and it does not seems to work. (ie: it does not fit to the square)
Is it normal ?

**Comment by laytya** [comment]
can u post screen?

**Comment by Krabator** [comment]
not now but i ll do it

**Comment by laytya** [comment]
no u dont

**Comment by Krabator** [comment]
![minimap](https://cloud.githubusercontent.com/assets/14138462/21999116/c6adf44e-dc38-11e6-810c-d23e10193238.jpg)
Not sure if it helps a lot :)

**Comment by laytya** [comment]
can u send me your simpleMinimap addon files?

**Comment by Krabator** [comment]
I ll do it tonight

**Comment by laytya** [comment]
better both

**Comment by Krabator** [comment]
For /interface
[simpleMinimap.zip](https://github.com/AeroScripts/QuestieDev/files/712640/simpleMinimap.zip)
For /WTF
[SavedVariables.zip](https://github.com/AeroScripts/QuestieDev/files/712651/SavedVariables.zip)

I hope it will help

**Comment by laytya** [comment]
you have old version of simpleMinimap

try this https://github.com/laytya/Vanilla-Addons/blob/master/simpleMinimap.zip

**Comment by Krabator** [comment]
thx for your support it works peerfectly
