### ISSUE TITLE
Questie makes KTM Frame move a bit at every restart.

### ISSUE THREAD

**Issue by bigdilll** [AeroScripts/QuestieDev#288]
Questie makes KTM Frame move a bit at every restart/log in/reload etc.. So I have to manually replace it everytime it moves or eventually it will dissapear from the screen and then I will have to type /ktm gui reset and then replace it.

I tried to lock it in place with Discord Frame Modifier but didn't work at all.

[This is the version of KTM I'm using](https://www.dropbox.com/s/y891rvtlb7ukbco/KLHThreatMeter.rar?dl=0)

Thank you !

**Comment by AeroScripts** [comment]
I'll take a look and see if I can replicate this. Are you sure it's Questie related, that's really strange.

**Comment by bigdilll** [comment]
Yeah, KTM moves when I activate Questiev3.3. But my version of KTM is a modified one so may be this is the problem. 

I'll try with a normal version and tell you what happen.

**Comment by bigdilll** [comment]
KTM 17.22 doesn't move every time I log in with Questie activated. I guess I'll stick with the ugly KTM then :/

**Comment by AeroScripts** [comment]
If possible can you link me to 17.22? Will help when I fix this bug (it will get fixed)

**Comment by Schaka** [comment]
He is saying that another KTM (not 17.22) is causing the bug. That's the one you need linked :p

**Comment by bigdilll** [comment]
the version of KTM i'm using : https://www.dropbox.com/s/y891rvtlb7ukbco/KLHThreatMeter.rar?dl=0

KTM 17.22 which doesn't move with Questie : http://www.vanilla-addons.com/dls/klhthreatmeter/

**Comment by AeroScripts** [comment]
He already linked the one that is bugged schaka, I just wanted the one that is working so I can compare the two

I'll look into this shortly.

**Comment by Dyaxler** [comment]
I use KTM all the time... not able to repro this with the latest release.
