### ISSUE TITLE
Multiple objectives (from interaction with other addons?)

### ISSUE THREAD

**Issue by mihneaadr** [AeroScripts/QuestieDev#289]
I have redownloaded questie 3.3 just yesterday in preparation for the Nostalrius/Elysium relaunch, and have run into a problem I have not noticed before (since I used to run fewer addons).
I'll try to post all of my findings. When multiple tooltip addons are enabled alongside questie, they multiply the number of objectives in the tooltip, as seen here 
(questie+tinytip+mobinfo2+EQL3 with NO tooltip tracking+Theorycraft):
![1](https://cloud.githubusercontent.com/assets/22300740/20354875/2acc60b4-ac28-11e6-9abf-438538f5849e.png)
Disabling any one of those addons decreases the number of multiplied questie objectives by 1, as seen here 
(questie+tinytip+EQL3 with NO tooltip tracking+theorycraft):
![3](https://cloud.githubusercontent.com/assets/22300740/20355124/f6140c68-ac28-11e6-8a3b-caca616b6d7f.png)
OR
(questie+tinytip+EQL3 with NO tooltip tracking+mobinfo2):
![4](https://cloud.githubusercontent.com/assets/22300740/20355731/ff5c579c-ac2a-11e6-8b88-d7a695e1685b.png)
Finally disabling questie solves the multiple objectives problem, as seen here 
(tinytip+mobinfo2+EQL3 WITH tooltip tracking+Theorycraft):
![2init](https://cloud.githubusercontent.com/assets/22300740/20355493/28ec7f2a-ac2a-11e6-844a-06007328c841.png)
However this does not solve the big problem of not having questie.

I am aware this issue has been addressed before, and I apologise for any redundancy, but I do think the problem is slightly different this time.

**Comment by AeroScripts** [comment]
It's possible this was introduced with the changes in 3.3. Do you mind testing to see if it also happens in v3.1? Here is the link for that: https://github.com/AeroScripts/QuestieDev/releases/download/v3.1/Questie-3.1.zip

**Comment by mihneaadr** [comment]
The same exact behavior happens with the 3.1 version.

**Comment by AeroScripts** [comment]
Ok, I'll see if I can get this fixed for v3.4

**Comment by AeroScripts** [comment]
Fixed, closing this now.
