### ISSUE TITLE
Add a window to see which quests have been completed and are still available.

### ISSUE THREAD

**Issue by LastAnarch** [AeroScripts/QuestieDev#290]
This is more of a feature suggestion that I would really like to see,

basically, it would be window that lists all the quests in your zone, and you can filter through completed, available, or unavailable, etc.

It would just be nice to see how many you have left to do in your zone and in the world.

Just my 2 cents.

**Comment by AeroScripts** [comment]
This is a great idea! I'll see if I (or someone else) can add it but I'm not sure when since all my time is going into 4.0 right now

**Comment by Dyaxler** [comment]
DugiGuides does this on Retail... it is kind of nice to see how far you have to go.

**Comment by istepanko** [comment]
Great request! Please implement it.

**Comment by Ghamarro** [comment]
I mighty second this feature request. Also, I would like to add to this request in the form of a UI that allows you to return quest markers onto the map if you accidentally manually completed them by shift clicking; sometimes when questie doesn't properly remove quest markers after completion of a quest, or after moving to a new server with no prior questie data for my past characters, I sometimes accidentally delete some available quests from the map by shift clicking through those that I actually have already done. If I can see neither a list of quests nor a marker on the map of any kind, I'm predisposed to easily forget about the quest altogether, sometimes for a really long time, and me being an OCD (read obsessive completionist disorder) freak, it really bugs me out. And to no help at all, vanilla being vanilla, it doesn't show the yellow exclamation points over quest giver npcs if the quests are too low level.

**Comment by Dyaxler** [comment]
Picking up the quest and abandoning the quest will wipe it from your Database. That is the only easy way to get it back. Or you can do /questie NUKE and start over. :( Sorry but without an actual mechanism to compare a quest on screen (or one you know is there) doesn't help Questie find it in it's database. It needs a reference from your quest log, an NPC or one of the markers on your map; which doesn't help you in this case. Next time, slow down. :D 

I have no idea what Aero has planned for a core feature set for Questie 4.0... it won't be added pre-4.0. I have no time to write that feature. :(

**Comment by BreakBB** [comment]
This is implemented with the journey system isn't it?
