### ISSUE TITLE
Minimap zoom level resets itself to default zoom level after restart.

### ISSUE THREAD

**Issue by SalviaSage** [AeroScripts/QuestieDev#292]
Without the questie addon, if you change your minimap zoom level, it sticks and if you log out or exit the game or even alt+f4 the game, the minimap zoom level will be the same as the one you set before.

But, questie resets it back to the default zoom level everytime you login to the game world.
Please change this, and make it just like the default.

**Comment by Dyaxler** [comment]
@SalviaSage - do me a favor and search for this function in Questie.lua:

`Astrolabe:isMinimapInCity()`

There should be two calls - just comment them out and give it another shot. I don't get why we're triggering this when VARIABLES_LOADED event fires and MINIMAP_UPDATE_ZOOM. Astrolabe already has that event registered and is calling that function itself so we're doubling up. Could be it's trying to trigger it twice and they aren't running congruently and fighting over the zoom level instead of just running a check... LOL this version of LUA is so old compared to the current version there is no telling what it's doing. I'm surprised nobody has pointed this out before. Astrolabe has been part of Questie for quite some time.

**Comment by SalviaSage** [comment]
I commented out the lines 401 and 448 where it says "Astrolabe:isMinimapInCity()"

Nothing changed.

**Comment by Dyaxler** [comment]
Then something else is causing it and it's not Questie. Works on my computer. Mine no longer changes the zoom setting and it persists through logout / login.

You don't need to comment out the entire function. You might end up breaking something else in Astrolabe which is a mod that wasn't designed by the creator of Questie. It's quite a common mod. The only thing that needed to be commented out was lines 401 and 448 in Questie.lua.

**Comment by SalviaSage** [comment]
"Works on my computer. Mine no longer changes the zoom setting and it persists through logout / login."
That's right. But you didn't exit your client and log back in. Then, it resets to default. It does not do that without the questie add-on.

"The only thing that needed to be commented out was lines 401 and 448 in Questie.lua"

That's exactly what I did. I only commented out those lines by putting -- in front of them. I did not comment out any other line. 

The same problem persisted.

I can confirm that this reset to default is caused by questie. I tried everything, including fix addons like Minimap:SetZoom(0) but something from questie is overriding it.

Dyaxler. Please look into this further.

**Comment by Dyaxler** [comment]
Logout / Login and Client off and relaunch. My zoom level stays the same. I've tried 3 different characters and 2 different zoom level settings. Try deleting your WDB folder and try again. Other than Astrolabe there aren't any functions in Questie that messes with the Minimap zoom level. This Astrolabe function is currently commented out in the latest check-ins.

```
    if(event =="ADDON_LOADED" and arg1 == "Questie") then
    elseif( event == "MINIMAP_UPDATE_ZOOM" ) then
        --Astrolabe:isMinimapInCity()
```
...everything else is all Astrolabe.

![image](https://cloud.githubusercontent.com/assets/17400948/21670449/13133eb2-d2c9-11e6-8f2e-436dd740201e.png)

**Comment by Dyaxler** [comment]
BTW... make sure your Config.wtf file doesn't have a "Read-Only" flag on it. This would prevent you from saving any changes you make in game.

Also, the old Nost client wouldn't run correctly if it was installed in C:\Program Files*** - move your WoW client to D: or the root of C: - try running your WoW client as Admin.

**Comment by SalviaSage** [comment]
I tested this bug and I can confirm that this bug is now fixed.

**Comment by Dyaxler** [comment]
SWEET!

**Comment by grommpy** [comment]
This did not fix the issue, as the original reporter and responding developer probably both set their inside and outside zoom to different levels. A permanent solution is found in #440 .
