### ISSUE TITLE
Request: Toggle quest objectives markers on/off

### ISSUE THREAD

**Issue by Lexenadar** [AeroScripts/QuestieDev#294]
Hi, I was wondering if there is a way to configure Questie (and if not, whether it would be possible to add such an option) so that the map shows where available quests are, BUT without showing where the objectives are (NPCs, Objects, mobs to kill, etc) .

To clarify, removing everything from the map that isn't a yellow exclamation mark (!) .

The reason is that while I find it annoying to miss a quest because you didn't check an area properly, I find it more fun to have to actually search for the objectives, rather than seeing on the map where they are. 

Thanks in advance, sorry if I've put this in the wrong place. 

EDIT: I'm not certain that's exactly what the author meant as he was scarce on details, but I believe I'm suggesting the same thing as this person: https://github.com/AeroScripts/QuestieDev/issues/291 .

**Comment by AeroScripts** [comment]
Fixed, making v3.4 release now hold on!

**Comment by Lexenadar** [comment]
Thanks for adding it to the 3.5 release, it's very appreciated.

Would it be possible to make the hideobjectives option really only keep the quest givers though? As in, not leave any yellow interrogation mark on the map? (or make it another option)

It's a minor thing and there's no rush, but it still kinda breaks it for me to see on the map a big "?" when I receive a quest with an obj to find someone.

In any case, fantastic work you guys are doing.
