### ISSUE TITLE
Minimap Clutter

### ISSUE THREAD

**Issue by lovestrange** [AeroScripts/QuestieDev#295]
Is there a way to limit the objectives icons showing on the mini-map at a certain distance as opposed to tracking the whole zone? The icons clutter up the mini-map because its tracking objectives from the whole zone. Objectives only closer to the player showing up on the mini-map would help clear the mini-map a bit. The world map shows the objectives of the whole zone anyways.

Also, adding quest markers on the Wanted posters quests would be really helpful since they are easy to miss.

**Comment by AeroScripts** [comment]
This used to be something that happened automatically in older versions of questie, I'll see what I can do to bring it back soon


As for wanted posters, they're coming in 4.0 along with daily quests and a few other new available quests things

**Comment by Dyaxler** [comment]
Questie already limits the number of objectives. This was changed in v2.5 a long time ago. If you untrack a quest it will remove the objectives from the minimap and worldmap. It used to show everything. Quest objectives beyond a certain distance should also be hidden on the minimap. Quest givers and finishers will always appear on the minimap but only in the zone that you're in.

I could swear that Wanted Posters show up as regular quest givers on the minimap/worldmap. There are a few in red ridge. I could be wrong...

**Comment by jackajack** [comment]
Well this is still an issue. My minimap's borders are cluttered by quest icons far away from where I am.
The thing is I only need to see them in my minimap when I'm really close to them. If they're far away, I'm looking at my world map anyway...

**Comment by BreakBB** [comment]
Is this still an issue?
