### ISSUE TITLE
[Quest][60] "Honored Amongst the Clan" and "Earned Reverence"

### ISSUE THREAD

**Issue by Hallonkaka** [AeroScripts/QuestieDev#296]
http://db.vanillagaming.org/?quest=7164
and
http://db.vanillagaming.org/?quest=7165

both horde quests show up in Questie for Alliance

https://gyazo.com/6b2aad5c64dec7d8cae5e3289ef864d0

EDIT:

was some more after i manually completed them:

https://gyazo.com/674b67ba41d279003956f4a02959e2e2

**Comment by AeroScripts** [comment]
This is related to #274 

Will be fixed when the new database arrives in v4.0. This will also bring in new data for daily quests and for quests that are started by objects instead of NPCs
