### ISSUE TITLE
doubles

### ISSUE THREAD

**Issue by x003** [AeroScripts/QuestieDev#297]
![one](https://cloud.githubusercontent.com/assets/12950645/21083497/e1b222d2-bfbf-11e6-810d-caf22dd252fe.jpg)
![two](https://cloud.githubusercontent.com/assets/12950645/21083498/e40d680c-bfbf-11e6-9640-b7c15c606eb5.jpg)

**Comment by AeroScripts** [comment]
What version of Questie are you using?

**Comment by x003** [comment]
the newest one

**Comment by Muehe** [comment]
What other addons are you using? Could be the same root issue as #289.

**Comment by x003** [comment]
!ImprovedErrorFrame
!OmniCC
_LazyPig
Align
Cartographer
ClassicSnowFall
CS_AddOnOrganizer
ShaguDB
Buffalo
TinyTip
Bongos
CEnemyCastBar
simpleMinimap
OneBag/OneBank
EQL3
BigWigs
KTM
VGuide
TrinketMenu
SuperMacro
QuestHistory
DPSMate
EnhancedFlightMap
Aux
AutoProfit
CT
Postal
questie
enemybufftimers
luna
shaguplates
atlas
mobhealth
outfitter
adapt
classviewer
Informant
Stubby
EnhTooltip
SCT

**Comment by AeroScripts** [comment]
I'll look in to this

**Comment by AeroScripts** [comment]
Fixed, closing this now

**Comment by x003** [comment]
Whatever you changed to fix this fucked up TinyTip and it causing it to bug out a lot by displaying wrong colors and putting tooltips in wrong positions

**Comment by AeroScripts** [comment]
Really? wtf.. Send me your version of tinytip that wasn't happening for me.

**Comment by x003** [comment]
I got TinyTip from here http://addons.us.to/addon/tinytip

This is tested with only TT and Questie enabled 

At first hovering over someone to see their name tooltip works fine but then after 2 or 3 people even though I have the games default backdrop color selected for tinytip it will show me this blue color instead and when I hover over items like my armor it will show the same backdrop for that even though tinytip isn't suppose to change those backdrops or tooltips. It behaves normal once I disable questie.
![t3](https://cloud.githubusercontent.com/assets/12950645/21225887/0c0534aa-c2a1-11e6-9e05-aec7471dfee8.png)
 Eventually it gets so wacky the more I use it things will get stuck in the wrong spots.

![t1](https://cloud.githubusercontent.com/assets/12950645/21225815/97517934-c2a0-11e6-9288-c0acb1c8c1f3.png)
![t2](https://cloud.githubusercontent.com/assets/12950645/21225819/995965b6-c2a0-11e6-9f48-aa642dfc1eae.png)
