### ISSUE TITLE
Integrated guide making addon that uses Questie as a DB

### ISSUE THREAD

**Issue by DKXAM** [AeroScripts/QuestieDev#298]
We have talked about this on Reddit, i just wanted to add it as an issue for a future enhancement

I would like to be able to make and publish guides with the Questie database. Basically a guide maker/player addon that uses the data Questie provides. Within the addon you can create a guide by selecting create guide, then selecting pickup. This pickup gives you a search engine where you can search for and select a quest, and put that one into the guide steps. Then selecting do quest, this gives you a selection of the quests you have in the guide and adds it to the guide steps. It would create a crazy arrow based on the location of the quest pickup/do areas from the Questie database.

This same plugin/addon for Questie would let you play a guide and run through the steps automatically if possible and if not manually. Questie will then map highlight the active quest in the guide step only.

I think this would be a good way for the community to make quest guides quickly and easily. This will be very useful for new players to vanilla to make leveling guides for, and for guilds to create quest guides for quest lines people often have to run through for attunements and pre raid bis gear etc.

This would also mean that the hard tedious work to create a good leveling guide in code would not have to be done only by people with the knowledge of Lua but by anyone with time and effort.

Thank you for you work guys!

**Comment by AeroScripts** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.
