### ISSUE TITLE
improve load times/optimization (if possible?)

### ISSUE THREAD

**Issue by x003** [AeroScripts/QuestieDev#299]
checked with the warmup addon while u sing the newest version of questie and while it doesn't use the most memory of all my addons it gives the longest impact on loading time. Wondering if it's possible to optimize Questie to reduce impact on login load time.
![questie load](https://cloud.githubusercontent.com/assets/12950645/21196321/36048130-c205-11e6-8a72-c5cc757f9b58.png)

**Comment by AeroScripts** [comment]
I may be able to significantly improve this by changing how DB loading works

**Comment by AeroScripts** [comment]
I added this to 3.5 because I can partially improve it in that version. However, 4.0 is going to make the most improvement to this since it overhauls the whole DB.

**Comment by ZoeyZolotova** [comment]
Uh oh, I think the new clustering stuff further increases the load time.

**Comment by Muehe** [comment]
@ZoeyZolotova Just tested, seems to be ok. Bottom is with current commit (52cf893d3f56d54156f912ca3dd52a54aa83f171):

![warmup](https://cloud.githubusercontent.com/assets/8838573/22471732/8996c026-e7d3-11e6-960d-25d9561f71f8.jpg)

(No idea why my v3.3 is using thrice the memory it did for OP though... SavedVariables maybe?)

**Comment by BreakBB** [comment]
The performance has been increased by a lot in the last updates thanks to @Logonz
