### ISSUE TITLE
Possible Auto-Track Quests?

### ISSUE THREAD

**Issue by abennette32** [AeroScripts/QuestieDev#3]
Would there be any way for the addon to automatically track all supported quests? At this time it's a bit annoying to have to track quests manually in the quest log for Questie to show them.

**Comment by AeroScripts** [comment]
I just had a big conversation with someone who may help with development here, about this topic [here](https://www.reddit.com/r/wowservers/comments/2ybw20/vanilla_addon_questie/cpb926a). the plan is to have things auto-plot the most efficient route through all objectives from the current location. It's going to take a bit of work but I'm fairly certain it's doable.

**Comment by abennette32** [comment]
Ah, fantastic. Would you be interested in a site or forum by chance? That's what I do for a living and I'd love to set it up for free if you pay for the hosting/domain. I can recommend some nice cheap ones.

**Comment by AeroScripts** [comment]
It's funny you should mention it because that's essentially the same way I make bank lol. Though help is always appreciated, I'll have to get back to you on it. There are still a few things up in the air. (And that's a topic better discussed in other places)

**Comment by Schaka** [comment]
A bit offtopic, but what do you two do exactly? Because frontend isn't exactly my forte, but I can provide a solid JEE backend. Only problem is I don't have that much experience routing Tomcat URLs behind an Apache (for static resources).
If you just want a cheap website advertising your addon, pages.github.com should be enough.

**Comment by abennette32** [comment]
I almost strictly do front end, and usually use some sort of CMS for the back end. Html/CSS/JS
