### ISSUE TITLE
Interface/AddOns/!QUestie/Questie.lua:251:attempt to index field ' ABANDON_QUEST_WITH_ITEMS' (a nil value)

### ISSUE THREAD

**Issue by HennersUK** [AeroScripts/QuestieDev#301]
Hiya!

So I got Questie today and for my first couple of WoW sessions, it worked just fine, but now I am getting this error on logging in to a character and quests that I've completed are displaying as active. It's making the mod pretty unusable.

I've tried reinstalling and disabling other addons - it's still happening. All I can think to do is try a clean WoW install?

**Comment by Schaka** [comment]
That does sound like a missing variable that's supplied by the default UI/client itself.
If deleting WDB/WTF doesn't work, your client might be corrupted.

**Comment by AeroScripts** [comment]
Assuming this is not the latest version of questie, so closing this for now
