### ISSUE TITLE
Questies version 3.3

### ISSUE THREAD

**Issue by MASTERMAGITH** [AeroScripts/QuestieDev#302]
Apon trying to use questie 3.3 last night on the Elysium server after about 30 mins of it working fine the add on cause a critical error between me and the server and forced me out of sync and cause massive invisible lag Exapmles:ppl where running in place and doing combat with the wall they ran into, mobs where fighting invisible players that i could not see,i would get target not in light of sight errors,can't log out errors, your are in combat with nothing attacking me errors. Once i disabled the addon i was sent to my last know location on the server and the lag issue stopped i dunno if any 1 else had an error this bad but i hope it can be resolved soon love the addon. i dunno if this is a issue cause this version is not designed for the Elysium server and if so what version is more compatible?

**Comment by AeroScripts** [comment]
This is unrelated to questie, I've been having this problem too with no addons enabled. Relogging can sometimes fix it, that's probably why you got that impression.
