### ISSUE TITLE
Not tracking...

### ISSUE THREAD

**Issue by statiqshock** [AeroScripts/QuestieDev#303]
I went from having icons on the map tracking many of my quests, to not having anything (save two quests that could be tracked but not untracked). it began when I toggled a quest off of my map since I had completed it

I completed those two quests and now I have NO tracking at all.
I've unistalled, tried different versions. Tried UI scale changes, tried disabling other mods. I can't get it to work

My questie will not track anything new

**Comment by AeroScripts** [comment]
That is very strange. Have you tried running /questie showquests command?

**Comment by AeroScripts** [comment]
assuming this is a duplicate of #307 so closing for now
