### ISSUE TITLE
Only parts of Questie work. 

### ISSUE THREAD

**Issue by ChimBrouer** [AeroScripts/QuestieDev#304]
I have installed Questie 3.3 (and also tried other versions 3.4 and older). Even tried to install on a new WoW installation without any other add ons, but I still have the same problem:

- The main Quest Log (with the details and where you can abandon a quest) is unchanged.
- The quest tracker is not the standard quest tracker frame, so I can not move it with a tool like MoveAnything

What works:
- In the new quest tracker I see the level of the quest
- Quest Icons on the minimap and World map appear.

See images:

Still same old Quest Log window:
https://www.flickr.com/photos/8680115@N07/31685249851/in/dateposted-public/

Quest Tracker Frame is not movable by MoveAnything, because it is not the standard quest tracker frame:
https://www.flickr.com/photos/8680115@N07/31764432136/in/dateposted-public/

World Map feature seem to work
https://www.flickr.com/photos/8680115@N07/31801438585/in/dateposted-public/

This is so strange, because it seems to works for a lot of people, because it is so popular, so I wonder if I miss something very simple and stupid.

IS THERE ANY OTHER PRE-REQUISITE ADD ON THAT I NEED?

I just installed !Questie from the GitHub project directory. But also tried Questie installations from other sources. 

![wowscrnshot_122216_122158](https://cloud.githubusercontent.com/assets/3807126/21424563/f4bbc4c8-c843-11e6-9d4d-a0e36dfb78eb.jpg)
![wowscrnshot_122216_122237](https://cloud.githubusercontent.com/assets/3807126/21424562/f4bba628-c843-11e6-916e-fc0b03b97675.jpg)
![wowscrnshot_122216_122306](https://cloud.githubusercontent.com/assets/3807126/21424565/f4bf6ef2-c843-11e6-9cf4-1818441d8d5f.jpg)
![wowscrnshot_122216_122317](https://cloud.githubusercontent.com/assets/3807126/21424564/f4bce556-c843-11e6-9506-06a66af3307a.jpg)

**Comment by Muehe** [comment]
> FAQ:
>   - How do I move the QuestieTracker and QuestArrow?
>     * Hold down CTRL + Shift + Hold Left Mouse Button + Drag
