### ISSUE TITLE
Logalization for RUru locale...

### ISSUE THREAD

**Issue by gamer4eg** [AeroScripts/QuestieDev#305]
Sorry my english is wary bad...and this post generate google translate=*(
I'd love to get you caught up with the developers and localization RUru jointly questie translated into Russian.
Link to a group of developers RUru localization: https://vk.com/wowruru
Yes, they do not have a group on facebook-vk.com rosiyskogo his counterpart.

**Comment by gamer4eg** [comment]
I hope this helps
RUru WoW client https://vk.com/doc-113603759_437863254
and RUru server locale https://vk.com/topic-113603759_34231730

**Comment by Muehe** [comment]
Support for additional languages is already tracked in issue #282. Please keep the discussion there.

If all goes according to plan the following languages should be supported:

 - Russian
 - Chinese
 - French
 - German
 - Italian
 - Korean
 - Spanish
 - Taiwanese

However, there is no release date yet.

**Comment by gamer4eg** [comment]
Dear developers, a workaround (a database of translation with the replacement of English names) have made one good man
(He asked to specify a link to it) https://vk.com/mockba
But there was a bug - do not work coordinates spawn monsters and items (quest objectives)
Please fix this workaround, some WoW players speak English on Google translator ^ _ ^
Thanks in advance!

PS Link to a translated's database system
https://docviewer.yandex.ru/?url=ya-disk-public%3A%2F%2Fv%2Fi6Ok0PXXx5dF0hq67644I5hKY90n8bsRlYeAw3F28%3D%3A%2FQuestie_Database%20Rus.rar&name=Questie_Database%20Rus.rar&c=585e3be935c8
