### ISSUE TITLE
Some quests not tracking

### ISSUE THREAD

**Issue by Xero-Tec** [AeroScripts/QuestieDev#307]
In questie 3.4 and then questie 3.3, only some of the quests I chose were actually getting tracked. It worked fine in Tirisfal Glades, but once I went to Silverpine and the Barrens it only tracked 1 or 2 quests. 
http://i.imgur.com/h6yciXl.jpg
That's a picture of it happening.
Thanks.

**Comment by AeroScripts** [comment]
It's possible this is related to the autotracking mode. You can configure that using the /questie slash command. Try running /questie showquests to see if it helps?

**Comment by Xero-Tec** [comment]
That didn't seem to help. 
I don't seem to be getting any errors or anything when I try to track them.
If this helps, here's a list of my current addons;

- LazyPig
- Align
- Atlas
- AtlasLoot
- Aux
- Bagnon
- Banknon
- Big Wigs
- Bongos
- BonusScanner
- Buffalo
- BuffWatch
- CallToArms
- Cartographer
- Caster Stats
- ChatSuey
- Classic Snowfall
- FlightMap
- DoTimer
- DPSMate
- Elkano's BuffBar
- Enchantrix
- EnemyBuffTimers
- EnhTooltip
- EquipCompare
- Gatherer
- Improved Error Frame
- Improved Ignore
- Informant
- KLHThreatMeter
- Luna Unit Frames
- maff
- MetaMap
- MetaMapBWP
- Mik's Scrolling Battle Text
- MobHealth
- MobInfo
- MovaAnything
- MPOWA
- Natur ECB
- oCB3
- OmniCC
- Postal
- Sell Value
- simpleMinimap
- Sprocket
- Stop The Spam
- Stubby
- SuperInspect
- SuperMacro
- Telo's LootLink
- TheoryCraft
- TinyTip
- TrinketMenu
- VanillaGuide
- vQueue
- WIM
- XLoot
- ShaguCombat
- ShaguDB
- ShaguInventory
- ShaguKill
- ShaguPlates
- ShaguQuest
- Necrosis
- Questie 3.3

**Comment by Muehe** [comment]
I see your "Improved Error Frame" showing two errors in that screenshot, maybe this problem is related? Try giving the error message next time it happens (first one is most important).

**Comment by Xero-Tec** [comment]
Nothing to do with questie, just super macro and bongos.
http://i.imgur.com/xwYv0lT.jpg
I think I might just delete my WTF folder soon and re-setup everything.

**Comment by Muehe** [comment]
Worth a try. If you have a "Cache" folder there, delete it as well.

Another approach would be to deactivate everything except Questie (or at least Super Macro and Bongos) and see if the problem persists. If it does not, this is a compatibility issue.

**Comment by AeroScripts** [comment]
Since this issue has been reported 4 times now, twice in issues here and twice to me directly in discord, (and happens with old versions of questie also) I'm going to assume this is a new bug related to how elysium is handling things. I'll look into it as soon as I get time.

**Comment by Muehe** [comment]
I'd still like the feedback though. Especially on the Cache folder, which tends to fuck everything up when not deleted upon switching servers.

**Comment by Xero-Tec** [comment]
Okay, so I deleted my WDB and WTF folder and went into the game and tried once again to use questie, and once again, it only tracked one or two quests, no errors. Next thing I could try would be disabling all my other addons.

**Comment by AeroScripts** [comment]
I don't think its addon related. This issue popped up just the other day and many people have reported it. If it was unrelated to recent changes on elysium it would have been noticed much earlier than now (since it happens on old versions)

**Comment by Xero-Tec** [comment]
Alright, cool, so I'm assuming no current fix is available. Thanks for all the work you do on this, have a merry Christmas/Hannukah/whatever.

**Comment by Xero-Tec** [comment]
Alright, cool, so I'm assuming no current fix is available. Thanks for all the work you do on this, have a merry Christmas/Hannukah/other.

**Comment by kunicmarko20** [comment]
Same problem, it was all working great but now questie is not tracking quests I already have in my quest log, but if I abandon them and take quests again it starts tracking. Biggest problem is when you relog, I have to abandon all quests and take them again. Hope you find fix

**Comment by Dyaxler** [comment]
Question... to everyone reporting issues with Quest Tracking. Is everyone using VanillaGuide?

**Comment by Dyaxler** [comment]
OK... so a little research. VanillaGuide doesn't hook into the QuestLog.

@Xero-Tec in your opening post you shared a screenshot. Your EQL3 shows a button I've never seen before and I can can't figure out where it's coming from. My only guess is that you're using a modified version of EQL3 that isn't compatible with Questie. I vaguely recall that there is a version floating around somewhere that isn't the real EQL3. I found it once and it hooks into some of the same things that Questie hooks into but I don't recall where I found it. All I know is that it caused all sorts of weird issues.

This is the version I'm using: https://github.com/ericraio/vanilla-wow-addons/tree/master/e/EQL3

**Comment by Xero-Tec** [comment]
Alright, so I am using Vanillaguide, and I am using a different EQL3 which is provided through ShaguQuests, but I had the tracker issue before I installed that plugin. Next time I can get on WoW though I'll try using that version of EQL and disable and some other addons.

**Comment by Flaktrack** [comment]
Just upgraded to 3.5 and the quests don't get added to the tracker.

**Comment by Dyaxler** [comment]
I loaded Vanillaguilde and I didn't see any issues but I didn't try ShaguQuests version of EQL3. I'll give it a shot tonight after work to see if that might be the culprit. At the very least I'll look at his code and see if I can discover what is different between my version and his version. We might be able to come up with a work around... no promises since we can't possibly support every version, branch, spawn of the same Mod. :(

**Comment by Flaktrack** [comment]
Ok i found the problem. I've copied my settings which i adjusted on an other server. \WTF\Account\AccName\Nostalrius PvE\CharName\SavedVariables (the SavedVariables for each character)

After deleting the "!Questie.lua" File the tracker is here again. Unfortunately the whole quest history is gone - but better than no tracker.

In order to prevent this behavior (as it seems it is no unique case, as people know the "copy-trick" to save time) maybe there is a possibility to reset this variables right at the start.

**Comment by Dyaxler** [comment]
I suggest reading the Readme & FAQ in the future. Could have saved yourself a lot of time and trouble.
> 
> Questie Slash Commands - use "/questie" to show the help menu in game.
>   - arrow: Toggles the QuestArrow on and off.
>   - clearconfig: Resets all Questie settings and removes stale quest database entries (will not delete
>     completed quests).
> - cleartracker: Resets the position of the QuestTracker and places it in the center of your screen.

**Comment by kunicmarko20** [comment]
@Dyaxler Tried all from readme, deleted addon, nothing helps, on every login addon resets and I have to abandon all quests and take them again to be able to track them.

**Comment by Dyaxler** [comment]
Sounds like you've got a "read-only" flag set somewhere. Tracking info is stored in the characters SavedVariables file. Where did you install your game client? I could swear I remember reading somewhere that you can't run the game with it installed in either of the C:/Program Files* directories. Or is this on a Mac?
