### ISSUE TITLE
QuestTracker. Add a way to link quest's level/name/title.

### ISSUE THREAD

**Issue by rsheep** [AeroScripts/QuestieDev#31]
Would be nice to have a way to add quest's basic info to chat.

Example:
Ctrl-RightClick: send quest's info to general/party/say with a message like: "LFG *quest_info*".
If the chat's editbox is open, just paste quest_info into it.

This could be further improved using other mods/mouseclicks combination, to paste to specific target channels.

Would be worth exploring the possibility to add a feature to paste other information in party chat as well, like clicking on a sub-objective and print the progress for it to inform party-members.

**Comment by AeroScripts** [comment]
This has been implemented.
