### ISSUE TITLE
Equipment comparison window not cleaned up properly

### ISSUE THREAD

**Issue by torusnc** [AeroScripts/QuestieDev#310]
The equipment comparison window becomes stuck on screen, moving with the tooltip (currently, tooltip is set to be at my cursor). Each item that regenerates a tooltip moves the item window to that location, as if the comparison is continuing. I thought this was an issue with pfUI, but it was pointed out on their site that this was a known issue with Questie and didn't exist in prior versions (see - https://github.com/shagu/pfUI/issues/226).  

EDIT: Issue does go away with Questie disabled, normal behavior resumes.

Please see screenshots below at the following link:

https://imgur.com/a/6jW33

Thank you!

**Comment by AeroScripts** [comment]
This happens with v3.4, which is why I removed the download link. Are you using 3.4?

**Comment by torusnc** [comment]
I'm syncing directly with github. Do you have a commit suggested to pull until fix is in?

**Comment by Muehe** [comment]
```
git rev-list -n 1 v3.3
4abac2138af64534916bd26983bbb83ef968cf11
```

You can also see which commit a tag belongs to on the [release list](https://github.com/AeroScripts/QuestieDev/releases). Be aware though that the content in the zip files provided there does not necessarily match the commit id, what an uploader puts inside them is completely arbitrary.

**Comment by AeroScripts** [comment]
A fix will be up very soon for this btw. I've been really busy with xmas but Dyaxler is working on it.

**Comment by Dyaxler** [comment]
v3.5 has been released to fix this issue:
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by torusnc** [comment]
Seems fixed on my end. Thanks!
