### ISSUE TITLE
/hideobjectives still showing where to hand in quests

### ISSUE THREAD

**Issue by Lexenadar** [AeroScripts/QuestieDev#312]
Pretty straightforward, the initial idea was to remove everything from the map but exclamation marks (!), yet right now all interrogation marks (?) still appear (even when it is not the same NPC or Object as the initial quest giver). The only things that were removed are stuff like items to collect or mobs to kill.

If doable, solution would be to either include the removal of all interrogation marks (the quest "receivers") in /hideobjectives, or to add a second option for it.

Thanks for the hard work guys.

**Comment by AeroScripts** [comment]
In v4.0 there will be much more control over what specifically is shown and hidden via a UI, but for now I won't be adding more features to v3.x

**Comment by AeroScripts** [comment]
See #314
