### ISSUE TITLE
Suggestion: Make !Questie root level directory on GitHub

### ISSUE THREAD

**Issue by istepanko** [AeroScripts/QuestieDev#313]
Hello,

 It is very convenient to clone a lot of add-ons from different repositories and then update them all with GitClient but Questie is on lvl 2 of Repo and WoW won't see it unless you copy it 1 level upper. Is it possible to make !Questie root level folder?

Thanks!

**Comment by istepanko** [comment]
There is a workaround - symlink.

**Comment by AeroScripts** [comment]
The problem is, if we do this it will likely clone into a folder with the wrong folder name, and wow doesn't load addons if the folder name doesn't match the TOC name.
