### ISSUE TITLE
Proper control over what kind of notes are displayed

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#314]
There needs to be an option in the configuration UI to choose what types of notes are displayed.

**Comment by Gogo1951** [comment]
Hey @AeroScripts,

Is this still relevant? If not, let's close it. If it is, can you give some examples of what needs to be changed?

**Comment by BreakBB** [comment]
This is handled enough in the current version of Questie. If anything specific comes up again users will create a new issue.
