### ISSUE TITLE
Questie needs a configuration UI (not just slash command)

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#315]
The configuration could be much more intuitive. A UI can be generated from the same logic that handles the slash command.

**Comment by Dyaxler** [comment]
We should have an On/Off switch for every major feature in Questie... just some examples.

* Quest Item Toolips
* Quest Mob Tooltips
*Tracker
*Mini-Map Icons
*World-Map Icons
*Questie Arrow

**Comment by TheBozzer** [comment]
+1 for mee on this. It's such a good add-on, it deserves that front end polish, maybe even a minimap rotatable icon a'la X-pearl?

**Comment by ThiconZ** [comment]
I suppose it's time I make a note on here that I'll be making a pull request soon to resolve this:
![image](https://cloud.githubusercontent.com/assets/6924950/22853355/7e7ea652-f022-11e6-9a2f-5b3873ffbeff.png)
Just working on adding in the last few options. @Dyaxler if you plan on adding in more settings for 3.70 let me know and I'll throw them into the UI. UI is currently set to be displayed by typing ```/questie options``` and all settings are applied when ```Done``` is clicked to keep things nice and simple.

**Comment by ZoeyZolotova** [comment]
Close this issue?
