### ISSUE TITLE
Show reputation rewards for quests

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#316]
And also show rep rewards on available quest tooltips. (optionally)

**Comment by ZoeyZolotova** [comment]
Implemented in 3.7 (see #419 ). Showing rep rewards on available quest tooltips has **not** been implemented.

**Comment by Gogo1951** [comment]
Hey @AeroScripts,

Is this still relevant? If not, let's close it.

**Comment by BreakBB** [comment]
@Gogo1951 We should rename it, because the requirements are already handled for some updates. Rewards are still missing.

**Comment by AeroScripts** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.
