### ISSUE TITLE
Questie should have some way of finding available quests that start from item drops

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#317]
Not sure the best way of doing this though.

**Comment by Dyaxler** [comment]
The only way that I can figured to do that would be to either have a "Zone Note" placed on the World Map in a given zone or have a ! icon over the quest turn in NPC indicating a quest that can be obtained via a drop.

**Comment by Muehe** [comment]
Quest starts from items are stored in the `Item_template.startquest` field. From there you have to look up the groups for this item in the various `*_loot_template` tables (find everyone/everything using the loot-group the item is contained in, including other loot-groups). And after that you need to look up spawns for the creature/gameobject using the loot-group (I don't think there are items dropped by items which start quests, but haven't looked).

With this information you can place the icon on the NPC dropping the item.

**Comment by ZoeyZolotova** [comment]
I've been experimenting in this area in my fork. Here's what I have going so far:
Captain Sander's Hidden Treasure (which is actually simply listed as a monster with specific locations) looks like this: 
![image](https://cloud.githubusercontent.com/assets/22694317/22552023/48e9127a-e9ab-11e6-975a-8ccf5c3fce74.png)

The Unsent Letter starts from an item called An Unsent Letter dropped by Edwin VanCleef, whose location is listed as Westfall at the entrance to Deadmines. Looks like this: 
![image](https://cloud.githubusercontent.com/assets/22694317/22552068/78f14a5a-e9ab-11e6-883e-6c97afbaac75.png)

The Key to Freedom is listed as startedType "item" startedBy "Grimeslit Outhouse Key" which drops of various mobs in Searing Gorge. Looks like this, with several duplicate exclamation marks: 
![image](https://cloud.githubusercontent.com/assets/22694317/22552101/9b2201d2-e9ab-11e6-81d0-6e547b499725.png)

I'll keep this thread updated with any progress I make.

**Comment by ZoeyZolotova** [comment]
Just managed to add "Dropped by:" to the tooltip :)

![image](https://cloud.githubusercontent.com/assets/22694317/22552756/53867062-e9ae-11e6-94c3-9e1b60f5e3b3.png)

**Comment by ZoeyZolotova** [comment]
@Muehe I just found a quest-starting item which is dropped by an item. "Target: Hive'Ashi Workers" is started by "Combat Task Briefing III" which is randomly contained in "Hive'Ashi Dossier".

**Comment by reaper666735** [comment]
another one for the list if a system will ever be made :) 

Container: https://classic.wowhead.com/object=2560/half-buried-bottle#contains  -->  
Quest starter: https://classic.wowhead.com/item=4098/carefully-folded-note#starts

**Comment by Gogo1951** [comment]
Hey @AeroScripts,

Questie seems to have this functionality, mostly. Adding containers and drops to the corrections file seems to work OK. Is this still relevant or can it be closed?

**Comment by BreakBB** [comment]
@Gogo1951 This is still relevant, because we don't show quests that are started by item drops. Meaning there is no way to see which mobs drop an item that starts a quest. Also related to #1616

**Comment by Gogo1951** [comment]
Hey @BreakBB ,

Got it, and I can see it's not easy to make a ton of changes to the data to support all this.

What if we added a "Zone" quest spot we could manually define, and a Zone Notes spot for text notes, and then stuck that on the zone map?

![WoWScrnShot_120919_132943](https://user-images.githubusercontent.com/55365231/70637921-a65cd900-1bfd-11ea-99e1-d41fd1f6bb31.jpg)

If you like this approach, I can work to create the list of quests for each zone, as well as the notes for what to bring. Cheers!

**Comment by BreakBB** [comment]
I personally see that it as a great idea! I will let the others know and report back :)
