### ISSUE TITLE
Proper quest item tooltips

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#318]
Currently, item tooltips for quest items only work sometimes.

**Comment by Dyaxler** [comment]
Actually...  rasberryrabbit may have found the reason why tooltips for quest items have been broken. I just haven't had a chance to try it out yet. I've been sick these past several days...

See: https://github.com/AeroScripts/QuestieDev/issues/311

**Comment by Dyaxler** [comment]
My latest check-in addresses the tool tips on Quest Items but only for quests that are currently in the players quest log. The code scrapes the quest log for the info since the current database can't tell us which quest an item is for.

So for Questie v4.0 I would LOVE to see a database that we can query for Quest Tool Tip info:

- Hovering over mobs
- Quest items in the environment 
- Identify quests for items in a players bank or bag 
- Where to obtain said quest if it's not already in the players quest log

**Comment by Muehe** [comment]
What do you mean by "Quest items in the environment"? Like items in chests or other gameobjects?

**Comment by Dyaxler** [comment]
Like the wood on the ground for one of the quests near Eastvale Logging Camp... in hindsight you can't really interact with an Quest Object unless you're on the quest so it might not be useful.

**Comment by Muehe** [comment]
You can't interact with them, but you should be able to get a tooltip by mousing over them I think. Anyway, those are all gameobjects and accordingly the needed information is in the [gameobject_loot_template](https://github.com/cmangos/issues/wiki/loot_template) table. The problem I see is identifying which GO you are seeing exactly, as their names are not unique.

**Comment by Dyaxler** [comment]
I dunno what I was thinking exactly... it would be nice if I picked up an item, no matter where, and it won't matter if I'm on the quest or not we should see a tool tip saying that this item can be used in a quest. For example, Murloc Fins can drop from any Murloc. I usually end up with a bunch of them by the time I'm done with Elwynn Forest and Westfall. In Red Ridge there is a quest you can get where you need to collect Murloc Fins and once complete you get a cooking recipe to cook them. It's great buff food and you can level up your cooking. Informant kind of does it but all the tool tip says is "Quest item in 1 quests" but it doesn't say where to get the quest.

There should be a filter on it so in case it's an item that can be used in more then one quest or if it's 20 levels above your current level, don't show it. It should only briefly show where to get quests close to your current level. Make sense? This of course should be an option a player can turn on or off. Some folks don't like the extra info all over the place.

**Comment by Muehe** [comment]
Once the item is in your inventory this should be quite easy, even if the item is used in more than one quest. Same for NPC tooltips (all non-unique NPC names are not used in quests).
