### ISSUE TITLE
More mod compatibility stuff

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#319]
v4.0 is going to have a number of new things to optionally integrate with other addons. This issue will be to consolidate information on those enhancemements. Feel free to post a reply here if you have an idea for a cross-mod enhancement.

**List of enhancements:**
OneBag/Bagnon - Custom color for quest items, red if it's for a quest you don't have.

**Comment by Gogo1951** [comment]
Hey @AeroScripts,

Is this still relevant? If not, let's close it.

**Comment by BreakBB** [comment]
Closing this, since we're handling compatible problems directly and/or in separated issues.
