### ISSUE TITLE
No description for quests in the Quest Log

### ISSUE THREAD

**Issue by hakase-C** [AeroScripts/QuestieDev#32]
The description field for quests in the Quest Log is blank for all quests

**Comment by AeroScripts** [comment]
It's possible the most recent commit (aca9220379bdc98692b80c2dae7e2bcfdf6f1557) caused this, I'll take a look. Are you using EQL3?

**Comment by AeroScripts** [comment]
This should be fixed as of 1.0k, it's working now for me anyway. 1.0k is now in the release page or [get it here](https://github.com/AeroScripts/QuestieDev/releases/download/v1.0b/Questie-1.0k.zip)

Sorry about that D:
