### ISSUE TITLE
available quests not shown on map/minimap

### ISSUE THREAD

**Issue by Shadehand** [AeroScripts/QuestieDev#321]
I can not see available quests on map.
Max and min level is set to 5-5 but nothing.

**Comment by Dyaxler** [comment]
run this command in game then screen shot it and post it for us.

`/questie settings`

**Comment by Shadehand** [comment]
I dont know why they disappeared. I reinstalled the whole addon and now it works. The inly problen that it forgo my done quests, but it is ok. 
Is there any forum fir thus addon? I have some questions but u dont wan ti bither you with it.

**Comment by Dyaxler** [comment]
You won't bother anyone. Ask away!

By the way, `/questie NUKE` does the same thing as a reinstall basically.

**Comment by Shadehand** [comment]
Is there any way to auto show quests in quest tracker window? I have to add
always manually (shift click questlog). In an older version it showed
always all quests when I logged in but niw empty.

**Comment by Dyaxler** [comment]
![image](https://cloud.githubusercontent.com/assets/17400948/21670095/4416bed8-d2c6-11e6-8cfb-649d21f042f1.png)

**Comment by Dyaxler** [comment]
Yeah, I just turned off my EQL3 and checked. The default WoW quest log is not auto tracking quests. Bummer. Use EQL3 AKA EnhancedQuestLog... most players use it.
