### ISSUE TITLE
Questie issues when using SimpleMiniMap (SMM) addon

### ISSUE THREAD

**Issue by Cole34567** [AeroScripts/QuestieDev#323]
-Icons on regular map and minimap move around, and blink on and off
-Icons in minimap bunch up into a big circle instead of conforming to whatever map skin is being used
-Icons get stuck on player arrow on minimap

I also made a post (with pictures) on Kronos before I moved to Elysium. https://forum.twinstar.cz/showthread.php/112654-Problem-with-SMM-amp-Questie

If no fix can be made, maybe just add an option to turn off all map icons for people with minimap skins.

**Comment by Cole34567** [comment]
I tried both suggestions still having problems.

The Icons show up, but they blink and move around on the minimap, the icons also dont properly conform to different sized minimaps (such as a square) which creates circles of distant icons around the character icon on the map.

**Comment by Dyaxler** [comment]
I don't know then... someone else checked in the code that supposedly made Questie compatible with Square MiniMaps. We can't possibly write code to account for every little change that other mods do to the "default code base" including running custom map skins...

I know that Aero is working hard on 4.0 and he says that the new code base plays a lot nicer with other addons. I get your frustration but all I'm saying is that I've been running Questie for over a year and supporting it one and off for more than 6 months and I've never had anyone report this kind of issue.

**Comment by Dyaxler** [comment]
...actually there is one more thing you can try. If you're flipping back and forth between servers you really should be deleting your WDB folder. Also, the old Nost client had issues running from WoW clients that were installed in "C:\Program Files***"... move your client to the root of your drive. Try running the client with admin rights.

**Comment by Cole34567** [comment]
Didn't work :(  Anyway its an issue that's not to hard for me to work around. Thanks for the help!
