### ISSUE TITLE
Question/Suggestion: Toggle questinfo in item tooltip.

### ISSUE THREAD

**Issue by kev41** [AeroScripts/QuestieDev#325]
Is there a way to toggle off questinfo in item tooltip?

I have problems with it, flickering when mouseovering an item that is in a quest.
But it might be my PC because it's only sometimes so therefore I ask this, not reporting a bug.
If it's no option to toggle this, then it's a suggestion =)

This is how it can look for me: https://clips.twitch.tv/slacker091/SmilingCarabeefRalpherZ

And I have tried disabling ALL addons except questie and I still have it :(

**Comment by Dyaxler** [comment]
Thanks for the video! This is more helpful than most people who complain - "...it's broken fix it." LOL...

I notice it flicker once on my computer but, once the tooltip is cached it stops. I've never seen it persist like that. I'll try adjusting the timings a bit. I've got code to keep it from looping over and over like that but maybe I missed a stop check somewhere. I was pretty tired when I first threw this code together and it was entirely re-written from scratch compared to the original logic loop I was using...

**Comment by kev41** [comment]
@Dyaxler 

Ok thanks for looking into this, if you do find a solution please let me know in this thread.
It's amazing to get the phone notification!

Keep up the good work.
Regards.

**Comment by Dyaxler** [comment]
Do me a favor... change this line in QuestieNotes.lua - should be line 381

From this:
`elseif objective and GetTime() - Questie_LastTooltip > 0.01 then`

To this:
`elseif objective and GetTime() - Questie_LastTooltip < 0.05 then`

...and test again. This seems to have fixed it on my computer.

**Comment by kev41** [comment]
@Dyaxler 

My hero, it works smooth like never before now. :+1: 

Time to start use questie again! 

Ty and just let me know if you want me to test something more!

**Comment by kev41** [comment]
@Dyaxler 

Edit: actually the only thing now is that it doesn't show the info at all in the item tooltip. 
But now it is like I toggled off that fuction and that I was I requested at first post, just wanted to let you know.

**Comment by Dyaxler** [comment]
Doesn't show at all?!?!

Try .01 instead of .05 then... tooltips show up just fine on my machine. You must have a SUPER fast computer if the tips aren't showing up. You're blowing by the function too fast.

**Comment by kev41** [comment]
@Dyaxler 

Hehe, funny you mention that. I tried 0.01 and it was flickering, then I tested all from 0.0125 and it was flickering all the way until 0.0165 and there it started not show at all. I will try a bit more.

**Comment by Dyaxler** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17400948/21667820/e7ece660-d2b0-11e6-9db4-5130e435e9a6.png)

**Comment by Dyaxler** [comment]
Let me go back over my code... maybe there was another line I changed.

**Comment by Dyaxler** [comment]
Opps... I did change some other lines. haha

```
@@ -208,7 +208,6 @@ end
---------------------------------------------------------------------------------------------------
-- Tooltip code for quest objects
---------------------------------------------------------------------------------------------------
__TT_LineCache = {};
function Questie:hookTooltip()
    local _GameTooltipOnShow = GameTooltip:GetScript("OnShow") -- APPARENTLY this is always null, and doesnt need to be called for things to function correctly...?
    GameTooltip:SetScript("OnShow", function(self, arg)
@@ -223,13 +222,13 @@ function Questie:hookTooltipLineCheck()
        if oh then
            oh(self, arg);
    end
        --DEFAULT_CHAT_FRAME:AddMessage("ClearLinesHook " .. GetTime());
        DEFAULT_CHAT_FRAME:AddMessage("ClearLinesHook " .. GetTime());
        __TT_LineCache = {};
    end);
    GameTooltip.AddLine_orig = GameTooltip.AddLine;
    GameTooltip.AddLine = function(self, line, r, g, b, wrap)
        GameTooltip:AddLine_orig(line, r, g, b, wrap);
        --DEFAULT_CHAT_FRAME:AddMessage("AddLineHook " .. line);
        DEFAULT_CHAT_FRAME:AddMessage("AddLineHook " .. line);
        if (line) then
            __TT_LineCache[line] = true;
        end
@@ -239,6 +238,7 @@ end
Questie_LastTooltip = GetTime();
QUESTIE_DEBUG_TOOLTIP = nil;
Questie_TooltipCache = {};
__TT_LineCache = {};
function Questie:Tooltip(this, forceShow, bag, slot)
    local monster = UnitName("mouseover")
    local objective = GameTooltipTextLeft1:GetText();
@@ -289,7 +289,7 @@ function Questie:Tooltip(this, forceShow, bag, slot)
                                    break;
                                end
                            end
                        elseif m[1] and (m[1]['type'] == "item" or m[1]['type'] == "loot") then
                        elseif m[1] and (m[1]['type'] == "monster" or m[1]['type'] == "loot") then
                            local monroot = QuestieMonsters[monster];
                            if monroot then
                                local mondat = monroot['drops'];
@@ -378,7 +378,7 @@ function Questie:Tooltip(this, forceShow, bag, slot)
                GameTooltip.lastmonster = monster;
                GameTooltip.lastobjective = nil;
            end
        elseif objective and GetTime() - Questie_LastTooltip > 0.01 then
        elseif objective and GetTime() - Questie_LastTooltip < 0.05 then
            for k,v in pairs(QuestieHandledQuests) do
                local obj = v['objectives']['objectives'];
                if ( obj ) then
```

**Comment by kev41** [comment]
@Dyaxler 

Ok so, do I change something from that screenshot?

**Comment by kev41** [comment]
No rush btw =)

**Comment by Dyaxler** [comment]
Well I only told you to change the bottom one.... let me just attach my file. I don't know why I didn't just do that to begin with. Just make sure you rename the file back from TXT to LUA.

[QuestieNotes.txt](https://github.com/AeroScripts/QuestieDev/files/686336/QuestieNotes.txt)

**Comment by kev41** [comment]
![sickdude](https://cloud.githubusercontent.com/assets/21115526/21668070/86126bce-d2fe-11e6-8a9a-8929416065b9.jpg)

Nice job man, thanks alot!

**Comment by kev41** [comment]
![dffgfgdf](https://cloud.githubusercontent.com/assets/21115526/21668429/149844d8-d302-11e6-942a-dbdb175509d5.jpg)

Last thing, since I used your file it spams this is chat whenever I mouseover anything in the game.

Any ideas?

**Comment by Dyaxler** [comment]
Oppps.... I left one of the debug checks turned on LOL.
