### ISSUE TITLE
compatibility issues

### ISSUE THREAD

**Issue by brolernus** [AeroScripts/QuestieDev#328]
![tooltip](https://cloud.githubusercontent.com/assets/24928956/21707653/75745308-d3d1-11e6-94a9-9f0036ea7ed6.PNG)

double tooltip on items, which is caused by Aux as well as ShaguInventory (addons that change parts of the tooltip).
Disabling either one "fixes" this, would be nice however to have only show one regardless.

**Comment by Dyaxler** [comment]
Forcing Questie to check tooltips for redundant information or adding additional code to 'check for this addon then turn off tooltips' isn't ideal either. All it does is add code bloat. It's the nature of addons in WoW. Even in the most current Retail versions of the game, the mod echo system is filled with mods that do very similar things and can even double up on the info you get on screen. The best a player can do is choose which mod feature to show and which to disable.

Aero is working hard on Questie v4.0 - it'll contain a GUI config with options to turn on or off individual features of Questie with ease. This is the best option to offer going forward.
