### ISSUE TITLE
[Help] Bugged Tracking, Etc.

### ISSUE THREAD

**Issue by SneakySphynx** [AeroScripts/QuestieDev#330]
Heya, 

Thanks for an awesome addon, but i have some serious issues with it.
It worked flawlessly more or less until south of barrens.

1. Now 75% of my tracked quests wont show on the tracker list.

2. Map doesn't show any notes for 75% of my quests * Unless * i go there, and do a part of the objective then it shows up, but is quite buggy.

3. If i manage to track a quest, then try to remove it when it's complete it wont dissapear from track log.

4. If i manage to track a quest, and close and reopen game they are still stuck on screen even tho they are not tracked aswell.

Reinstalled, cleaned it, reset it, turn on and off on map + reload ui,  etc etc no help.

Any fixes for this? =)

-----------------------
Addons i'm using:

Atlas
AtlasLoot Enhanced
AtlasQuest
Auctioneer
Cartographer
Classic Snowfall
CT_MailMod
EnhTooltip
EzDismount
Gatherer
Improved Error Frame
Informant
Luna Unit Frames
maff
Mik's Scrolling Battle Text
Move Anything
OmniCC
OneBag
OneBank
OneRing
OneView
Prat
Stubby
XLoot
UUI - QuestLevels
Questie

**Comment by Dyaxler** [comment]
Looks like you're using the WoW Default QuestLog. It only allows tracking up to 5 quests at a time and will only track certain things not everything like EnhancedQuestLog will. The issues you're experiencing are only reported by users who didn't install the mod correctly or they have data in their cache from other servers they play on.

**Comment by SneakySphynx** [comment]
Heya, thanks for quick reply!

Didn't know about the enhanced one, will sure look into that!
Only played on one server, and started 3.5 day ago on Nostralius PvP.

For installation, i opened up the zip file and put it straight into addons folder.
Weird :/

**Comment by Dyaxler** [comment]
Try running this command...

`/questie settings`

Then screen shot the whole list and post here.

**Comment by SneakySphynx** [comment]
[Questie Settings](http://image.prntscr.com/image/33f7219d4cf54ac8bd268fe386027716.png)

**Comment by Dyaxler** [comment]
Nothing out of the ordinary there. Questie works best with EnhancedQuestLog AKA EQL3.

Link to EQL3 from old Nost forums:

> by schaka » Fri Mar 27, 2015 8:53 pm
> This is the EQL3 version I used to develop compatibility. So if you're having issues, please download http://www.mediafire.com/download/aslmbmmq25ka29y/EQL3.zip

**Comment by SneakySphynx** [comment]
Yeah i just downloaded it, and " installed " it. 
I'm going to try to reinstall questie again, will report back. 

And thanks for helping :)

**Comment by Dyaxler** [comment]
I played a Horde Druid up to level 54 on the old Nost servers.... Questie works fine. One of your Saved Variables files might have become corrupt. I'd purge the WDB folder too while you're at it. Might just be bad cache.

**Comment by SneakySphynx** [comment]
Remove the lua files, and delete WDB folder?

**Comment by SneakySphynx** [comment]
yeah it worked great for 3 days, then this :p

**Comment by Dyaxler** [comment]
I just delete all the files IN the WDB folder... without the game running though. Either way, you can safely nuke the folder. It'll just get recreated upon login.

**Comment by SneakySphynx** [comment]
[Check this one](http://image.prntscr.com/image/8c45a2d7fb9c494295300d76400fd031.png)

Seems like it thinks i didn't pick up the quests.

I deleted all files, but problem still exists.

**Comment by Dyaxler** [comment]
What's this? UUI - QuestLevels

**Comment by SneakySphynx** [comment]
Yeah the QuestLevels addon, shows appropriate level for certain quests.
Tried disabling it, but didn't help.

**Comment by Dyaxler** [comment]
If you're running a MOD that's messing with the QuestLog it can screw up Questie's ability to obtain and track quests.

**Comment by Dyaxler** [comment]
Disabling it won't fix what didn't make into your Characters QuestTracker cache.

**Comment by SneakySphynx** [comment]
Kind of weird that it worked flawlessly for 3 days, and just all of a sudden buggs out.

I'll try removing QuestLevels, the luas that goes with it. 
Clean out WDB folder again.
And reinstall Questie again.

**Comment by Dyaxler** [comment]
If possible I would disable UUI-QuestLevels and try abandoning Deepmoss Spider Egs and the Blueleaf Tubers to see if that clears it up.

**Comment by Dyaxler** [comment]
You shouldn't have to "re-install" questie... just run...

`/questie NUKE`

Pretty much does the samething

**Comment by SneakySphynx** [comment]
Still won't work, fawk. 

Oh well, we tried.

**Comment by SneakySphynx** [comment]
If you come up with some ideas, just write here and i'll try em out asap. :)

**Comment by Dyaxler** [comment]
Yeah, but you might not like it.

Clean out WTF and WDB. Disable all addons except for Questie and EQL3. Try it again. If it's still screwed up I'd say you have a corrupt client.

**Comment by SneakySphynx** [comment]
Worst case scenario, but might aswell rule everything else out. 

I will do this right when i wake up, and report back. Gonna grab some sleep, thanks again and talk tommorow :)
