### ISSUE TITLE
Background alpha slider for Quest Tracker.

### ISSUE THREAD

**Issue by SalviaSage** [AeroScripts/QuestieDev#331]
Hi. I would like to request that a background alpha slider be added to the quest tracker of Questie, similar to the alpha settings of the main chat window. (see here http://wowprogramming.com/docs/api/SetChatWindowAlpha)

Please consider adding this feature.

**Comment by AeroScripts** [comment]
This actually was a feature in earlier versions, expect to see it back in 4.0

**Comment by Dyaxler** [comment]
Please update Questie and review the readme's. Background is back but not enabled by default. There is also a slash command for adjusting the alpha level from 1-9.

https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by SalviaSage** [comment]
Dyaxler. Thanks for reintroducing this feature. 

The background does not auto adjust to the quest description.
So the quest description goes outside of the background towards the right.
(which doesn't look right)

Please re-enable the auto adjustment on the next update.

**Comment by Dyaxler** [comment]
Not going to happen I'm afraid. It causes too many lag spikes. 

Search for this line in QuestieTracker.lua:

`QuestieTracker.frame:SetWidth(200);`

And change the 200 to 250.

**Comment by SalviaSage** [comment]
It's okay if it can be manually adjusted. Maybe add a slash command to change this setting?

Also, what is the maximum width for the quest descriptions so the background can be set accordingly?
