### ISSUE TITLE
Quest 'complete' mark doesn't disappers on map.

### ISSUE THREAD

**Issue by rasberryrabbit** [AeroScripts/QuestieDev#333]
Somtimes completed quest's 'complete' mark doesn't disappears on map.
I make force updating after quest dialog is closed and it solves problem.

[patch_3.6_diff_completemark.txt](https://github.com/AeroScripts/QuestieDev/files/692531/patch_3.6_diff_completemark.txt)

**Comment by Dyaxler** [comment]
Hmmm... that's interesting. I'm fairly certain that I had this event in there at one point but it caused some issues and fired too often or wasn't firing at all. I don't remember. I'll add this back in.

**Comment by rasberryrabbit** [comment]
I remember it happens with "Mountaineer Stormpike" quest in Loch Modan and "The Defias Brotherhood" quest in westfall.

**Comment by Dyaxler** [comment]
Please update Questie - these changes were made.
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by rasberryrabbit** [comment]
Thank you :)

**Comment by Muehe** [comment]
@rasberryrabbit I'd suggest posting your diffs to gist.github.com. If you give them a `*.patch` filename there [it adds syntax highlighting](https://gist.github.com/Muehe/d2b5a28344e647f438e29fd588ac1169). Another possibility would be using [Markdown code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) with highlighting option `diff`:

```diff
--- Questie.lua	Fri Jan 06 18:21:48 2017
+++ Questie.lua	Sun Jan 08 19:20:16 2017
@@ -252,6 +252,7 @@
     this:RegisterEvent("ADDON_LOADED");
     this:RegisterEvent("VARIABLES_LOADED");
     this:RegisterEvent("CHAT_MSG_LOOT");
+    this:RegisterEvent("QUEST_FINISHED")
     QuestAbandonOnAccept = StaticPopupDialogs["ABANDON_QUEST"].OnAccept;
     StaticPopupDialogs["ABANDON_QUEST"].OnAccept = function()
         local hash = Questie:GetHashFromName(QGet_AbandonQuestName());
@@ -422,6 +423,12 @@
             QUESTIE_LAST_UPDATE = GetTime();
         end
         Questie:BlockTranslations();
+    elseif(event == "QUEST_FINISHED") then
+        QUESTIE_UPDATE_EVENT = 1;
+        Questie:AddEvent("CHECKLOG", 0.135);
+        QUESTIE_LAST_CHECKLOG = GetTime();
+        Questie:AddEvent("UPDATE", 0.15);
+        QUESTIE_LAST_UPDATE = GetTime();
     elseif(event == "QUEST_PROGRESS") then
         if IsAddOnLoaded("EQL3") or IsAddOnLoaded("ShaguQuest") then
             if IsQuestCompletable() then

```

**Comment by rasberryrabbit** [comment]
@Muehe ok, it is interesting function. Thank you.

**Comment by Dyaxler** [comment]
@rasberryrabbit 

Muehe is quoting your changes to show you syntax highlighting. These changes are in the current build of Questie.
