### ISSUE TITLE
[Shift+Click] manual quest complete list outside viewable window

### ISSUE THREAD

**Issue by bitingsock** [AeroScripts/QuestieDev#335]
if multiple quests are at the same spot a list appears to select which one complete. However, if the point is too high on the screen the list becomes unusable.
![asd](https://cloud.githubusercontent.com/assets/6302101/21792304/a0fb125e-d69d-11e6-8c49-eb61a5b1bd88.jpg)

**Comment by Dyaxler** [comment]
I'm about to upload a new release that fixes this issue

**Comment by Dyaxler** [comment]
Please update Questie - this issue should be fixed:
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by bitingsock** [comment]
Looks good to me
