### ISSUE TITLE
Toggleable categories for the quest tracker.

### ISSUE THREAD

**Issue by SalviaSage** [AeroScripts/QuestieDev#336]
Hello. I would like to request an optional feature for the quest tracker.
In the quest log, you can see that the quests are divided into categories based on zones and professions.
In the quest tracker, they are not.

Please add toggle-able categories to the quest tracker.
Make it an optional feature, in case the players want the old style.

Thanks.

**Comment by Dyaxler** [comment]
Sorry. We aren't going to add this feature. One of the core features of Questie is that it organizes the objectives by distance and this code is an integrated part of the QuestTrack functions. To separate this would require a complete re-write. Maybe you could convince Aero to add it to 4.0.

**Comment by SalviaSage** [comment]
This is an optional feature. If it isn't compatible with the Questie functions. Then, don't add it. 
Still, I think the two features can work together.

Just consider it for the future.
