### ISSUE TITLE
A way to keep the completed quest data updated

### ISSUE THREAD

**Issue by DoctorBak** [AeroScripts/QuestieDev#338]
I find strange that this question didn't come up a lot of times already. If that's the case, I read the FAQ and i couldn't find an answer, I'm sorry.
I play through different terminals and I always have the quest database messed up since is saved locally in each terminal.
Is there a way to keep in sync the files? for example a way to keep the settings in a dropbox folder?
Of course the best thing would be a 'sync' button ingame that scans the completed quests on the server and updates the local files.
Thanks for the hard work, still the best addon ever made.

**Comment by Dyaxler** [comment]
You could try installing your WoW Client in a directory that can be monitored by DropBox or OneDrive and synch ONLY the WTF folder.

As far as asking the server for a list of quests you've completed: 
`questsCompleted = GetQuestsCompleted([table])`
that functionality wasn't added to World of Warcraft until patch 3.3.0.

**Comment by DoctorBak** [comment]
I solved by creating a junction to the original path using few strings of command
`mkdir "%USERPROFILE%\Dropbox\WoWSync"
move "%WOWPATH%\Interface\AddOns" "%USERPROFILE%\Dropbox\WoWSync\"
mklink /J "%WOWPATH%\Interface\AddOns" "%USERPROFILE%\Dropbox\WoWSync\AddOns"
move "%WOWPATH%\WTF\Account" "%USERPROFILE%\Dropbox\WoWSync\"
mklink /J "%WOWPATH%\WTF\Account" "%USERPROFILE%\Dropbox\WoWSync\Account"`

**Comment by DoctorBak** [comment]
> As far as asking the server for a list of quests you've completed:
> `questsCompleted = GetQuestsCompleted([table])`
> that functionality wasn't added to World of Warcraft until patch 3.3.0.

Sorry to bring back this old ticket, but I wonder if the incoming Classic WoW will have new APIs such as the above and if there are any plans to integrate a backup feature in questie using the server data.
Thanks for your time.
