### ISSUE TITLE
Some addons cause strange note flickering on map/minimap

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#339]
Some addons seem to cause Questie notes to flicker randomly, multiple users have reported it. It seems one of the culprits is "Detached Mini Buttons" but from the sounds of it, it could be caused by more than 1 thing.

**Comment by SalviaSage** [comment]
Yes. I experienced this bug myself. So I stopped using detached minimap buttons in favor of questie. There is a conflict with some minimap functions.

I don't consider it a bug though since it's just a conflict with another addon. But, see if it can be fixed from Questie's side.

**Comment by Dyaxler** [comment]
Please update Questie and retest:
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by SalviaSage** [comment]
I downloaded the addon detached minimap buttons and ran it alongside questie. I know this bug was happening with these 2 addons running together earlier.

Now, it is not flickering anymore.

**Comment by Dyaxler** [comment]
Nice... some good news! Thanks for the confirmation!
