### ISSUE TITLE
abandon quest with items error and can't use /questie commands

### ISSUE THREAD

**Issue by lewtorz** [AeroScripts/QuestieDev#343]
First im getting this error on login
Error: attempt to index field 'ABANDON_QUEST_WITH_ITEMS' (a nil value)
File: Interface\addons\!Questie\Questie.lua
Line:280
count: 1

I also am not able to use questie / commands. I have the newest version as of right now and they don't seem to work, I have went through and deleted my old questie files in interface and WTF folder under my character both.

**Comment by Dyaxler** [comment]
Well foooy... that's interesting. Nobody has touched that block of code in months. Is this happening when you're abandoning a quest or picking up a quest? Running around? Changing zones? Please be more specific on when it's happening and what you're doing. This can help narrow down the issue.

Based on what you're telling me I'd have to say your cache is corrupted and needs to be flushed. So you deleted all the Saved Variables files in WTF and tried to reload Questie? What about the WDB folder? Try cleaning out Questie again but before reinstalling, wipe out all the files in your WDB folder. This will not break your client. It simple clears the game cache.
