### ISSUE TITLE
[Minor] Version name in 'Changelog.txt' and 'Questie.lua' not properly updated

### ISSUE THREAD

**Issue by Phantomb** [AeroScripts/QuestieDev#345]
Still says version 3.61 instead of the current version 3.64. Really minor issue, but I'd thought to let you know.

**Comment by Dyaxler** [comment]
3.61 was a release. 3.62-3.64 were technically hot fixes.

3.65 is a release and the version has been updated in this one.
https://github.com/AeroScripts/QuestieDev/releases/latest

Don't forget to read the readme or run the '/questie' command in game for options to customize Questie.
