### ISSUE TITLE
QuestLog dissapearing in dungeons

### ISSUE THREAD

**Issue by Larsy93** [AeroScripts/QuestieDev#347]
QuestLog dissapearing in dungeons

Atleast in wailing caverns, dont know about others.

**Comment by Dyaxler** [comment]
I'll look into this today...

**Comment by Larsy93** [comment]
It happened to me but not to my friend, questlog only showed Up when map was open.

**Comment by Dyaxler** [comment]
This has been fixed in v3.66
https://github.com/AeroScripts/QuestieDev/releases/latest
