### ISSUE TITLE
Different icon for ground pickups and mob drops

### ISSUE THREAD

**Issue by ShaunDreclin** [AeroScripts/QuestieDev#348]
Small issue but it would be helpful if the "loot bag" icon was changed for mob drops, maybe a sword and loot bag? or maybe change the icon for ground pickups to the interaction cog.

Also for mob drops, could the tooltip list what mob drops the item?

**Comment by Dyaxler** [comment]
The Icon assigned to a "drop" is based on the items/mobs flag in the database. Without an accurate database we'd spend days chasing minor issues with icon assignment.

We're just going to have to wait until Aero releases Questie v4.0 which will have a brand new... more accurate database based on the latest version of Mangos. :) It's an entirely new layout and requires a complete rewrite. This is why he has quite a few threads marked as enhancement already.

**Comment by ShaunDreclin** [comment]
Ahh yeah if you don't already have the info in the database that'd be a massive pain to do. Hype for 4.0! :o
