### ISSUE TITLE
Tooltip is missing.

### ISSUE THREAD

**Issue by rasberryrabbit** [AeroScripts/QuestieDev#349]
I download questie 3.65, but it cannot show tooltip with items and mobs.
I delete WDB but it cannot help.

And I made patch.

[patch_3.65_diff.txt](https://github.com/AeroScripts/QuestieDev/files/707853/patch_3.65_diff.txt)

**Comment by Dyaxler** [comment]
The patch diff is kind of hard to read... I want to make sure I understand what you're trying to change. Can you attach your whole Questie.lua file here?

**Comment by rasberryrabbit** [comment]
Yep. There are small changes on "Questie:OnEvent".

[Questie.lua.txt](https://github.com/AeroScripts/QuestieDev/files/708971/Questie.lua.txt)

**Comment by Dyaxler** [comment]
This has been addded v3.66 - thanks!
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by rasberryrabbit** [comment]
Thank you! :)
