### ISSUE TITLE
Some quests can not be tracked by shift+click

### ISSUE THREAD

**Issue by ayrb13** [AeroScripts/QuestieDev#35]
While i was doing some quest in dungeon named BFD, i tried to track a quest by shift+click, but it didn't work as expected. There were still some quests can be tracked, but i didn't see the checkmark followed quest name in questlog

**Comment by Schaka** [comment]
If it has no available notes for the quest, it will not track it. Therefore it's not "really" a bug, more of a feature. In one of the recent releases, I fixed a bug with quests where you only have to tun to a person not showing up.

**Comment by ayrb13** [comment]
That quest told me to pick up 10 items, but i can not track it.
Besides I can not use the Native tracker to track some quests which are not tracked by Questie.
I think there should be a option or menu to let user decide which tracker should be used.
I'm just talking about the UI of tracker on the right side of my screen.
Questie in minimap and world map works well and thank you for providing this great addon

**Comment by Schaka** [comment]
Can you tell us, which quest caused that issue (if you remember)? 
It might be an issue with missing information on the quest itself (in our database).

**Comment by ayrb13** [comment]
The quest is Twilight Falls

**Comment by Schaka** [comment]
It's inside a dungeon. There might not be any notes for it. Currently, you can only track quests that have notes, because the tracker is meant to be a GPS system (which is currently unfinished). We should add notes to our database for all dungeon quests that just point to the dungeon's entrance, I guess.
