### ISSUE TITLE
Disable/enable seasonal, holiday quests

### ISSUE THREAD

**Issue by slacker3007** [AeroScripts/QuestieDev#350]
Sometimes those quests are bothering me and I'm not interested doing them, but they keep pop-ing up even after I manual complete them.
I like requests option/command to disable/enable seasonal holiday quests.

Thanks.

**Comment by Dyaxler** [comment]
Some of the holiday quests have very similar tooltips. Just keep SHIFT+CLICKING them until they are gone. If they reappear after a reload or relog then something is going on with that characters Saved Variables. Once a quest is completed it should never reappear.
