### ISSUE TITLE
Missing Quest: 'Jonespyre's Request'

### ISSUE THREAD

**Issue by kev41** [AeroScripts/QuestieDev#351]
Missing Quest: 'Jonespyre's Request'

http://db.vanillagaming.org/?quest=3788

**Comment by Dyaxler** [comment]
Horde Side or Alliance?

This is one of those dual faction quest lines. Jonespyre's Request requires Morrowgrain Research to be completed before it shows on the map as a quest. However, Jonespyre's Request is showing the same "required" hash:   ['rq']=461774661 for both the Horde and the Alliance side. So I need to know which one are you so I can fix it.

**Comment by kev41** [comment]
Alliance, Stormwind.
I had not completef any morrowgrain quest before taking this.
Though it is one as a followup to this:

http://db.vanillagaming.org/?quest=3787
ons 18 jan. 2017 kl. 05:07 skrev Dyaxler <notifications@github.com>:

**Comment by Dyaxler** [comment]
I've done the quest a LONG time ago back in the real vanilla wow days but not since then. I have no idea if Jonespyre's Request requires you to do Morrowgrain Research first or not. According to the database you do. But if you're in game and you are able to pick up the quest without doing Morrowgrain Research then let me know and I'll remove the ['rq'] flag.

**Comment by kev41** [comment]
If you visit http://db.vanillagaming.org/?quest=3787 there you can see the
Morrowgrain quest being enabled after this quest. I was able to pick up
Jonespyre's Request without it showing up on questie, that is the only
problem :)
ons 18 jan. 2017 kl. 07:22 skrev Dyaxler <notifications@github.com>:

**Comment by Dyaxler** [comment]
Just to be sure the info in the DB is accurate... what level are you currently? Or what level were you when you picked it up? Did you get the quest from Tannysa or from Innkeeper Shyria?

**Comment by kev41** [comment]
I was level 45 and I got it from npc Tannysa, in Stormwind.
ons 18 jan. 2017 kl. 07:32 skrev Dyaxler <notifications@github.com>:

**Comment by Dyaxler** [comment]
Ahhh... it wouldn't have shown up on the map until you were level 47. Look at the quoted code above. Both quests are flagged 47 and they are level 50 quests. So I can lower it to 45.

**Comment by kev41** [comment]
I have both minlevel and maxlevel disabled. Ok, I am just reporting it
missing:)
ons 18 jan. 2017 kl. 07:36 skrev Dyaxler <notifications@github.com>:

**Comment by Dyaxler** [comment]
Doesn't matter... "min level" quests do not show up in Questie until you reach the min level. It works like that by default. No use showing a flag on the map until you're actually able to pick up the quest. :)

The min/max filters were created before someone took the trouble to check in a DB with the Required Level flags. This changed the Flag types and now we have "questLevel" = The level of the quest and "level" = Required level. This initially broke the min/max filters I added a long time ago and recently fixed. :) So "technically" the maxlevel filter is redundant.

**Comment by Dyaxler** [comment]
Commit checked in:
https://github.com/AeroScripts/QuestieDev/commit/3b4573fbdfbb191b08b9421795ba6b0f4988b4b9

You'll have to install it manually until I have enough changes to build a release.

**Comment by Dyaxler** [comment]
Fixed in: https://github.com/AeroScripts/QuestieDev/commit/3b4573fbdfbb191b08b9421795ba6b0f4988b4b9

**Comment by Dyaxler** [comment]
New release with fix:
https://github.com/AeroScripts/QuestieDev/releases/latest
