### ISSUE TITLE
Missing Questline: 'Caught!'

### ISSUE THREAD

**Issue by kev41** [AeroScripts/QuestieDev#352]
Missing Questline: 'Caught!'

http://db.vanillagaming.org/?quest=4449

**Comment by Dyaxler** [comment]
Commit checked in:
https://github.com/AeroScripts/QuestieDev/commit/3b4573fbdfbb191b08b9421795ba6b0f4988b4b9

You'll have to install it manually until I have enough changes to build a release.

**Comment by kev41** [comment]
No problem. I found the Q anyhow. Just helping out for an even more perfect
addon.
ons 18 jan. 2017 kl. 08:38 skrev Dyaxler <notifications@github.com>:

**Comment by Dyaxler** [comment]
Fixed in: https://github.com/AeroScripts/QuestieDev/commit/3b4573fbdfbb191b08b9421795ba6b0f4988b4b9

**Comment by Dyaxler** [comment]
New release with fix:
https://github.com/AeroScripts/QuestieDev/releases/latest
