### ISSUE TITLE
Missing Quest: 'WANTED: Andre Firebeard'

### ISSUE THREAD

**Issue by kev41** [AeroScripts/QuestieDev#354]
Missing Quest: 'WANTED: Andre Firebeard'

http://db.vanillagaming.org/?quest=2875

**Comment by RBDaniel** [comment]
Level of character?

**Comment by kev41** [comment]
45

**Comment by Dyaxler** [comment]
Fixed in: https://github.com/AeroScripts/QuestieDev/commit/3b4573fbdfbb191b08b9421795ba6b0f4988b4b9

**Comment by Dyaxler** [comment]
New release with fix:
https://github.com/AeroScripts/QuestieDev/releases/latest
