### ISSUE TITLE
Missing Questline: 'Lieutenant Paval Reethe'

### ISSUE THREAD

**Issue by kev41** [AeroScripts/QuestieDev#355]
Missing Quest: 'Lieutenant Paval Reethe'

Alliance: http://db.vanillagaming.org/?quest=1252
Horde: http://db.vanillagaming.org/?quest=1269

**Comment by RBDaniel** [comment]
Which step? Again, what level is your character when you were looking for these quests?

Step one and two are both called by the same title but are started from different starters.

Step one starts with the badge in the Barrens
Step two starts with Captain Garran Vimes

**Comment by kev41** [comment]
Step one - Level 38

Yes for Alliance step one and two are both called the same, nothing wrong with that. When you deliver the step one to 'Captain Garran Vimes', then he wants you to speak to 'Adjutant Tesoran' in step two.

Step one is not showing up to take the quest and that is what I am reporting here.

**Comment by Dyaxler** [comment]
Fixed in: https://github.com/AeroScripts/QuestieDev/commit/3b4573fbdfbb191b08b9421795ba6b0f4988b4b9

**Comment by Dyaxler** [comment]
New release with fix:
https://github.com/AeroScripts/QuestieDev/releases/latest
