### ISSUE TITLE
Missing Quest: 'Suspicious Hoofprints'

### ISSUE THREAD

**Issue by kev41** [AeroScripts/QuestieDev#357]
Missing Quest: 'Suspicious Hoofprints'

Alliance: http://db.vanillagaming.org/?quest=1284
Horde: http://db.vanillagaming.org/?quest=1268

**Comment by RBDaniel** [comment]
Level of character?

**Comment by kev41** [comment]
38

**Comment by Dyaxler** [comment]
Fixed in: https://github.com/AeroScripts/QuestieDev/commit/3b4573fbdfbb191b08b9421795ba6b0f4988b4b9

**Comment by Dyaxler** [comment]
New release with fix:
https://github.com/AeroScripts/QuestieDev/releases/latest
