### ISSUE TITLE
Quest wrongly positioned: 'Tooga's Quest'

### ISSUE THREAD

**Issue by kev41** [AeroScripts/QuestieDev#358]
Quest wrongly positioned: 'Tooga's Quest'

My screenshot: http://i.imgur.com/JNnKT5m.jpg

Database location: http://db.vanillagaming.org/?npc=5955

**Comment by RBDaniel** [comment]
Level of character?

**Comment by kev41** [comment]
50

**Comment by Dyaxler** [comment]
There are are actually 5 locations for this guy... but there was one entry that conflicted and overwrote all the others. According to the quest comments he does move around a little so I'll keep these cords in for now.

Fixed. I'll check these in shortly. 

```
  ["Tooga"] = {
    ["locations"] = {
      [1] = {8.0, 0.2942, 0.6413, 100.0},
      [5] = {8.0, 0.3354, 0.5756, 2.0},
      [3] = {8.0, 0.2873, 0.6717, 66.0},
      [4] = {8.0, 0.296, 0.6084, 58.0},
      [2] = {8.0, 0.3062, 0.7291, 88.0}
    },
    ["locationCount"] = 5
  },
```

**Comment by Dyaxler** [comment]
Fixed in: https://github.com/AeroScripts/QuestieDev/commit/3b4573fbdfbb191b08b9421795ba6b0f4988b4b9

**Comment by Dyaxler** [comment]
New release with fix:
https://github.com/AeroScripts/QuestieDev/releases/latest
