### ISSUE TITLE
Option to disable Corpse Arrow

### ISSUE THREAD

**Issue by ThiconZ** [AeroScripts/QuestieDev#359]
There should be a toggle option to enable or disable the showing of the Corpse Arrow.

**Comment by Dyaxler** [comment]
Done. Until a new release is drafted you'll have to manually install it.
https://github.com/AeroScripts/QuestieDev/commit/f4c2e5e6da587b1d1cb1f48f9c7dbc830c0fb2f7

**Comment by crumdidlyumshis** [comment]
👍 Also, I think the whole "My Dead Corpse" is kinda redundant. Maybe just "My Corpse"? Kinda like saying "my dead dead body"

**Comment by crumdidlyumshis** [comment]
@Dyaxler Dang you responded as I was typing xD Did you see my comment?

**Comment by Dyaxler** [comment]
The "My Dead Corpse" is kind of an inside joke from the original Closed Beta for Vanilla WoW days. Back then I was playing Alliance exclusively and the famous Horde guild [Goon Squad] was notorious for trolling Stranglethorn Vale. They would lock up the zone for hours corpse camping any Alliance player. Someone created a toon called MyDeadCorpse and left it dead and never resurrected. It was always there in the zone. A naked Gnome. For some reason, the Horde HATED Gnomes. :)

**Comment by crumdidlyumshis** [comment]
LOL I had no idea. Never got to play Closed Beta :D Good joke nonetheless

**Comment by Dyaxler** [comment]
New release with fix:
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by AvicusDelacroix** [comment]
My Dead Corpse was funnier tho.

**Comment by KingLich1** [comment]
no fun allowed
