### ISSUE TITLE
QuestieToolip messing with Theorycraft

### ISSUE THREAD

**Issue by Schaka** [AeroScripts/QuestieDev#36]
It seems like Questie conflicts with TheoryCraft addon. When Questie is active there is no theorycraft data in spell tooltips.

**Comment by egea-a** [comment]
It is also messing with MobInfo

**Comment by Schaka** [comment]
Guess we need to look into how to book the tooltip so other addons doing the same thing don't break. Bit sure that's even possible. 
Maybe disabling the tooltip hook is an option we can give the user.

**Comment by AeroScripts** [comment]
I might have found a way to fix this, looking into it now.
