### ISSUE TITLE
Missing Questline: 'It's a Secret to Everybody'

### ISSUE THREAD

**Issue by kev41** [AeroScripts/QuestieDev#361]
Missing Questline: 'It's a Secret to Everybody'

http://db.vanillagaming.org/?quest=3844

**Comment by Dyaxler** [comment]
I see it... one of the Quest entries was marked as a min level of 52. According to db.vanillagaming.org it's supposed to be 48. I'll check in the fix for that tonight.

**Comment by kev41** [comment]
I was level 54 - did not see it.

**Comment by Dyaxler** [comment]
Ah yes... wrong started and finisher types and there was some missing location info. Fix checked in:
https://github.com/AeroScripts/QuestieDev/commit/b408bacb2a78e5f0f3a6479588f0d8d5ddc2ea1e

**Comment by Dyaxler** [comment]
New release with fix:
https://github.com/AeroScripts/QuestieDev/releases/latest
