### ISSUE TITLE
Questie breaks if you delete a character and make a new one with the same name

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#363]
If you had quest history/tracking stuff on the original character

**Comment by Dyaxler** [comment]
I can add a function check to see if a character is level 1. If it is I can force Questie to perform a NUKE upon login. This would prevent this issue.

But if someone where to create a new toon by a name of a former toon then logout and log back in later and a nuke has been done already, it'll check the Questie Saved Variables and if there isn't any quests done then the NUKE would be skipped.

MOST players when they create a new toon they either level up to 2+ or run the toon to a capitol city (bank toon) before they logout. This logic should cover all situations.

**Comment by Dyaxler** [comment]
New release with fix:
https://github.com/AeroScripts/QuestieDev/releases/latest
