### ISSUE TITLE
The Missing Shipment start by Gazlowe in Ratchet

### ISSUE THREAD

**Issue by BoneLord** [AeroScripts/QuestieDev#364]
I have a level 11. In quest tooltip on map min level for quest is 10, but I can't take it from NPC.
![tooltip](https://cloud.githubusercontent.com/assets/1656752/22162776/0be69f2c-df61-11e6-901d-e4f0f5d88480.jpg)
[The Missing Shipment](http://db.vanillagaming.org/?quest=890)

**Comment by Dyaxler** [comment]
Yep... the Min Level should have been set to level 12. Fixed. I'll check it in soon.

**Comment by Dyaxler** [comment]
New release with fix:
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by Muehe** [comment]
I'm not so sure 12 is the correct value here, the DB I use has 9. Also note that there is a prequest, and two follow up quests, all of them having 9 in my DB, but only the first one (887) has level 9 on vanillagaming. Twinhead has 9-10-10-10. Everything 9 would make the most sense though, as the first three quests have the NextQuestInChain field set, which means the next quest will be immediately offered when turning the current quest in. If you finish the first quest still being level 9 this would not work.

**Comment by Dyaxler** [comment]
He said his character was level 11 and couldn't take the quest so I assume he was seeing a "silver !" above the NPC or none at all which means Questie is showing a quest that can't be obtained. He's not hovering over the "yellow ?" in the screen shot... he's hovering over something else. If the quest tooltip in the screenshot is indeed of the yellow ? then it doesn't make sense that he couldn't "get the quest." ;) Besides the Quest Tooltip shows (available) in green which further suggests he's hovering over a "yellow !" on the map.

Am I being too Vulcan here?
