### ISSUE TITLE
Addon memory usage

### ISSUE THREAD

**Issue by silverwind** [AeroScripts/QuestieDev#367]
I'm seeing around 70KiB/s memory growth from Questie in PerformanceFu shortly after login which causes the LUA garbage collection to run approximately every 3 minutes as opposed to every 50 minutes with the AddOn disabled (GC causes a short freeze of the game).

My script memory setting is currently at 512MB, but it appears to have no influence on the GC threshold. Could it be that there are memory leaks in the addon which cause the unusual high growth?

##### Without Questie:
![](https://cloud.githubusercontent.com/assets/115237/22183237/676140c4-e0b9-11e6-9e56-ae9cd50a367e.png)

##### With Questie
![](https://cloud.githubusercontent.com/assets/115237/22183238/6763f814-e0b9-11e6-9137-0f6de9dfab95.png)

**Comment by Dyaxler** [comment]
Not sure which AddOn's you're running but here is mine after spending a couple hours going through some of the OnUpdate functions and moving a few things around.

Before Tweaks:
Average: **72.1 KiB/s**

After Tweaks:
Average: **22.2 KiB/s**


Without Questie:
![image](https://cloud.githubusercontent.com/assets/17400948/22191440/9667a356-e0df-11e6-9ff2-d457dc2e0602.png)


With Questie:
![image](https://cloud.githubusercontent.com/assets/17400948/22191406/521060e4-e0df-11e6-9707-99d9ad513502.png)


Questie is a memory pig there is no doubt there. But this is the first time in months someone has complained about lag or poor performance. Hopefully my tweaks will work for you. I'll get my changes committed but you'd have to manually install the build until it makes it into an official release.

**Comment by Dyaxler** [comment]
I installed the latest release so this is WITHOUT my new tweaks just for an unbiased 1:1 comparative baseline. I think the numbers speak for themselves.

I double checked after disabling Questie and the numbers were virtually the same as my original screenshot in the above post.

With Questie:
![image](https://cloud.githubusercontent.com/assets/17400948/22191583/1550af7c-e0e1-11e6-963c-90271aeb4bb9.png)

**Comment by silverwind** [comment]
Looking good. The issue came to my attention because I've had garbage collections happening every 30s which was rather annoying. I've found that CustomNameplates (up to 400kb/s), FastQuest (up to 200 kb/s) were even worse offenders than Questie. 30kb/s is totally acceptable. I will test your changes later today. Thanks!

**Comment by Schaka** [comment]
Those addons do a lot of OnUpdate, meaning code is being called on every single frame (and they probably don't cache anything). For Nameplates, there is no other possibility, because they are drawn on WorldFrame withe very rendered frame. Questie is, considering its size, pretty performant. 

Well done on the changes, Dyaxler.

**Comment by silverwind** [comment]
Some more tests with a full quest log this time. Without Questie, I see around 5 KiB/s shortly after login.

https://github.com/AeroScripts/QuestieDev/commit/04578d2d6c52649ed5f92a09cb0b3482c6af8817 - 240 KiB/s
https://github.com/AeroScripts/QuestieDev/commit/805fc60f0a67ec8ae6762d2cee6b3a6246413774 - 155 KiB/s
https://github.com/AeroScripts/QuestieDev/commit/9d1dfc415c239f852ffe57fd8761e0b6ae1b75fb - 170 KiB/s

List of my current [Addons](https://gist.github.com/silverwind/4348694204fd29b3aba1bc2a795cf35b), but I doubt they really matter.

**Comment by Dyaxler** [comment]
That's still a pretty damn good improvement over the release build. Even the one I checked in last night didn't increase much. I did however find out what is taking up so much memory. The QuestieTracker:fillTrackingFrame() - its constantly calculating distance for all quests in the list and shuffling them in order from closest to furthest. Slowing it down to once every 5 seconds gave the largest performance boost. When I have a huge chunk of time I'm going to see if I can't streamline that whole function; break it apart so I have better control over what it's doing. For example, it only needs to fill the tracker with objectives when a quest is added or removed from the quest log tracker or when a quest updates. That can be triggered by events. But the distance calcs should be done faster - not in real time. Once every 10 seconds should be more than enough for the tracker sorting. However, the QuestieArrow depends on this function as well to get the closest objective's distance it's pointing at - there can be more than one point for a quest or steps that the arrow switches to. That data is being cached (formally at 60 times a second) now slowed down to once every 5 seconds. The arrow and tracker list will update but when a character is running they will hardly notice the lag. I don't hardly notice it. Other things also trigger the QuestieTracker:fillTrackingFrame() but at least the OnUpdate function has been slowed down.

So yeah... it'll take me some time.

**Comment by silverwind** [comment]
Yeah, I see that my framerate is part of the reason why it's so high. I run uncapped at 200+ fps because VSync just doesn't seem as smooth. By the way: after 2 hours of gaming memory went down to 60k-100k, which is totally fine. Oh, and I'm not using the arrow.

**Comment by Dyaxler** [comment]
My monitor sucks and is only capable of 60 Hz so I have my FPS capped at 60 FPS... it's an older 27" Ultrawide screen so I'm running in a Maximized Window @ 2056 x 1080 so I can use my other three monitors to update code, chat on Discord etc. The game runs smoothly with no lagging at anytime so I was a bit surprised when you said you were experiencing some lag. But after looking at and narrowing down which functions were causing the excessive usage... I'm surprised it's not a bigger issue for some folks.

My inner obsessive compulsiveness is screaming to make that function more efficient now that I know it's gobbling up a ton of memory. I know I can make it better. :)

**Comment by Dyaxler** [comment]
@silverwind I put in some more work tonight. I'm getting closer.

With Questie:
![image](https://cloud.githubusercontent.com/assets/17400948/22241775/b8bfb6d6-e1d5-11e6-9f3a-49ecfb34665f.png)

Without Questie:
![image](https://cloud.githubusercontent.com/assets/17400948/22241783/c9531c9a-e1d5-11e6-9799-a87bdf7c5046.png)

So according to this Questie is only consuming 43.8 KiB/s

**Comment by Dyaxler** [comment]
Interesting! Here is with Just EQL3 - FuBar and PerformanceFu loaded:

With Questie:
![image](https://cloud.githubusercontent.com/assets/17400948/22242076/df1c644a-e1d6-11e6-9f96-ea5e7582f513.png)

Without Questie:
![image](https://cloud.githubusercontent.com/assets/17400948/22242088/e861e610-e1d6-11e6-909c-c5bcbe1ee09f.png)

I wonder what mod I'm running is gobbling up all my memory cycles... hmmm....

**Comment by silverwind** [comment]
Kind of a shame we don't have memory/cpu profiling available in the 1.12 client (they came in 2.1) which would make this stuff a lot easier.

**Comment by Dyaxler** [comment]
Indeed. LUA Profiler helped a little though.

**Comment by silverwind** [comment]
Few results on the latest commits:

https://github.com/AeroScripts/QuestieDev/commit/ae2418c1c3ccffd709f94654e82a226806c587e7 - 52 KiB/s
https://github.com/AeroScripts/QuestieDev/commit/71eb4c6aa095ddfc55735a6fdc2e45a920ab8bef - 55 KiB/s
https://github.com/AeroScripts/QuestieDev/commit/805fc60f0a67ec8ae6762d2cee6b3a6246413774 - 49 KiB/s
https://github.com/AeroScripts/QuestieDev/commit/04578d2d6c52649ed5f92a09cb0b3482c6af8817 -110 KiB/s

The latest tweaks seem to only have a minor effect on my side. I had the CorpseArrow turned off in all tests. Could it be that some CorpseArrow OnUpdate code is still active even when it's disabled?

**Comment by Dyaxler** [comment]
Which latest commits? I didn't commit anything yet. :) The screen shots from last night is still beta code on my test box. :P

**Comment by silverwind** [comment]
Ah, sorry. I guess I confused https://github.com/AeroScripts/QuestieDev/commit/9d1dfc415c239f852ffe57fd8761e0b6ae1b75fb with being your latest tweaks 😉 Awaiting your commit.

**Comment by Dyaxler** [comment]
Yeah, these two were just misc fixes... no performance related work in those...
ae2418c - 52 KiB/s
71eb4c6 - 55 KiB/s

**Comment by Dyaxler** [comment]
Please try the new release and let me know what you think. I have a feeling you might be surprised.
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by silverwind** [comment]
![](https://cloud.githubusercontent.com/assets/115237/22304201/c7915bf8-e336-11e6-9fcd-8644c78e79f8.jpg)

Woah, just 11 KiB/s with https://github.com/AeroScripts/QuestieDev/commit/2ea766028df71c607ae9e2d12ba3b4b2d3f55a75 (6 KiB/s with Questie disabled, 90 KiB/s with 2 commits earlier). Awesome work. This is definitely fixed. 👍

**Comment by Dyaxler** [comment]
Yeah, I didn't even bother with posting screenshots. I wanted the surprise to be... well... a surprise. :)

I even re-added some old code that caused an even larger memory issue several months ago. If you enable the background (/questie background) it'll auto size the background up - down - left - right and frame your tracked quests perfectly. Looks bloody awesome.

I even fixed a super old issue with Quest drops not registering on the tracker upon first drop. In the past it would update after picking up the second drop. Sometimes it would happen with "kill x number of mobs". The first kill wouldn't register until the second etc...

**Comment by Dyaxler** [comment]
![image](https://cloud.githubusercontent.com/assets/17400948/22304401/2235cbf2-e2ec-11e6-9932-46de18fce93e.png)

**Comment by silverwind** [comment]
> /questie background

Looks quite sexy, I'll keep it that way.

>  Quest drops not registering

Nice, I noticed this too. My first thought was that the update frequency was throttled. Great to see that fixed too.

**Comment by Dyaxler** [comment]
It's a patch... I know what's going on. I was being lazy and wasn't checking to see how many buttons were being added before the resize tracker function call. Each tracked quest is actually being created separately as a button. This allows us to dynamically change their order from closest to furthest. Same behavior gets applied to the quest objectives when you have an arrow attached to it. I just need to move the margin modifiers from buttons to the tracker frame so it doesn't get added into the buttons size. There will be less calculations once I get it working right.

**Comment by silverwind** [comment]
> This allows us to dynamically change their order from closest to furthes

Neat, didn't know it does that. Would it be possible for the arrow to then always track the topmost (nearest) objective? It's a feature I remember from TomTomLite 😉.

**Comment by Dyaxler** [comment]
I was just thinking about that last night too... that's going to be a totally new feature. I'll have to think on it's logic flow before I start injecting smarter behavior like that. :P

**Comment by silverwind** [comment]
The corpse arrow should take priority when dead. Otherwise, track the nearest objective of all tracked quests. :)

**Comment by Dyaxler** [comment]
...I have the update function for that throttled to once every 5 seconds. So, this should work and only update once every 5 seconds. Even if a player is hanging out at the mid point of two objectives and keeps bouncing back and forth. It shouldn't drive players nuts to see their arrow jump back and forth as much as it would be if this function were running at 30x-120x per second. This was the old rate. It was based on the users detected FPS...

**Comment by Dyaxler** [comment]
I should build in a toggle though... some users are going to want full control over what their arrow is pointing at.

**Comment by silverwind** [comment]
Looking at [TomTomLite](http://www.wowinterface.com/downloads/info18855-TomTomLite.html), the updates happen in 2 seconds granularity, which I guess is acceptable, but a config option wouldn't hurt, yes.

````
corpseArrow = true,
forceUpdateThrottle = 2.0,
goodcolor = {0, 1, 0},
badcolor = {1, 0, 0},
middlecolor = {1, 1, 0},
````

**Comment by n0rc** [comment]
@Dyaxler, seems like you removed the travel time shown with the arrow in 805fc60f0a67ec8ae6762d2cee6b3a6246413774...
Any chance to see the time again?

**Comment by Dyaxler** [comment]
Nope. It was triggering too many calculations and because of the way the functions were rebuilt and throttled, it would only update once every 5 seconds making it useless.

If I find stable TomTom like arrow code that I can back port to Vanilla without it causing HUGE amounts of memory issues, I'm sure it'll have a Time To Arrival feature.
