### ISSUE TITLE
Tower of Althalaxx

### ISSUE THREAD

**Issue by Krabator** [AeroScripts/QuestieDev#369]
The quest marker are not working properly from the part 7 (included) to the end.

**Comment by Dyaxler** [comment]
Hmmm... there is location info on every starter and finisher. There is location info for Athrikus Narassin and Athrikus Narassin's Head (step 8). Step 7 is just simply run here and turn in quest to get next step... unless.

What level are you?

**Comment by Krabator** [comment]
I was 31 at this moment
This quest is really long and I will understand if this fix is not a priority.
Anyway I solved this quest very easily without the markers.

**Comment by Dyaxler** [comment]
I think I may see the issue. In Step 7 the quest title changes to "The Tower of Althalaxx part 7" then The Tower of Althalaxx part 8". Step 9 has the original title but without properly recording the previous two steps as complete, it won't show you markers for step 9.

Yep. Quest titles were wrong. Fixed and checked in.
