### ISSUE TITLE
Attempt to concatenate field 'formatUnis' (a nil value) QuestieTracker.lua line 273

### ISSUE THREAD

**Issue by egea-a** [AeroScripts/QuestieDev#37]
It happened when I disabled an reenabled all of my addons at the same time.
After exiting the game and starting it again, the error pops for the first time when opening the quest log and stays after every UI reload

**Comment by Schaka** [comment]
Can't reproduce this. I, however, made sure the variables are always set before this line is called, as of https://github.com/AeroScripts/QuestieDev/commit/b4460c45325b89f47b9e37f755ae71f1c66f338f
