### ISSUE TITLE
Option to clear previously-completed quests

### ISSUE THREAD

**Issue by twocows** [AeroScripts/QuestieDev#371]
This might not be possible in vanilla, but I'd like an option to have Questie look for and clear previously-completed quests (for instance, on a new install of Questie or on a Questie instance on another computer). Ideally I'd be able to run something like /questie updatedb or something to do this, since I imagine it might take a while. My use case is that I have two computers in two different physical locations that I use and completing quests on one doesn't change their completion status in Questie on my other computer.

Alternatively, any built-in method for dealing with this specific issue would work, too; this just seemed like the most obvious way to deal with it. If there was a built-in way to export/import the completed quests database or something, that might work, too.

**Comment by Dyaxler** [comment]
Write a batch file and put in on your desktop. When you're done playing click it and it will copy your Questie.lua file to Dropbox, or Onedrive or some other on line cloud storage. Click the batch again and it'll pull down a copy.

We can't "look in a server database" and see which quests a character has done. It would defeat Questies need for having a Quest Database locally. This ability wasn't available until WotLK in 2009.

Welcome to vanilla :(

**Comment by agemennon675** [comment]
Same here when I started using this addon with my lvl7 character it just shows all quests even previously completed ones, its frustrating and makes me check every ncp that have exclamation mark on it

**Comment by Muehe** [comment]
@agemennon675 As stated by Dyaxler above there is no way we can possibly fix this, which is why this issue has the `wontfix` label. You will have to manually mark these quests as finished by `Shift+Click`ing them on the map.

**Comment by Dyaxler** [comment]
The GUI has an above and below players level filter. If you don't want to see the lower level quests then reduce the number of levels below your characters current level. I think the default is 5 levels? Make it one or two.
