### ISSUE TITLE
grammar

### ISSUE THREAD

**Issue by jimmyleith** [AeroScripts/QuestieDev#372]
"My Dead Corpse" potentially redundant

**Comment by Schaka** [comment]
Great find!

**Comment by Muehe** [comment]
> The "My Dead Corpse" is kind of an inside joke from the original Closed Beta for Vanilla WoW days. Back then I was playing Alliance exclusively and the famous Horde guild [Goon Squad] was notorious for trolling Stranglethorn Vale. They would lock up the zone for hours corpse camping any Alliance player. Someone created a toon called MyDeadCorpse and left it dead and never resurrected. It was always there in the zone. A naked Gnome. For some reason, the Horde HATED Gnomes. :)

https://github.com/AeroScripts/QuestieDev/issues/359#issuecomment-273827044

**Comment by Dyaxler** [comment]
LMAO! True story.

**Comment by crumdidlyumshis** [comment]
Lol thats funny, I just mentioned that in another issue. xD

**Comment by crumdidlyumshis** [comment]
Just a thought, what about adding a slash  command to this name since this seems to be a popular issue recently. Not that I really care, but for those who wish the name to be "My Corpse" rather than "My Dead Corpse" could just do a "/questie corpsename" or something along those lines to toggle the name.

```
/questie corpsename
Returns Message: "Corpse arrow name changed to "My Corpse"
/questie corpsename
Returns Message: "Corpse arrow name changed to "My Dead Corpse"
```

Disregard if you feel it is unnecessary. Just a thought.

**Comment by Dyaxler** [comment]
Another slash? Uh no. We've got too many as it is.

If I have time this weekend and am super indulgent, I'll see if I can't create a Settings GUI and a Mini map button to go with it. I need to brush up on my UI skills.

**Comment by crumdidlyumshis** [comment]
Haha no problem. I knew the GUI was eventually in the works, but I figured for now, just a slash could work.  Look forward to the GUI! Your doing a great job!
