### ISSUE TITLE
MinTracker being activated when you click title of first quest if you have Header Disabled

### ISSUE THREAD

**Issue by zaphon** [AeroScripts/QuestieDev#375]
Starting with 3.68 (and maybe earlier, I updated from 3.50 to 3.68), if you have the Quest Tracker header disabled, and you click the title of the first quest in the list, it will enable the mintracker function.  This leaves you with no way to unminimize short of using the /questie mintracker command line option.  If you enable the header, it works as expected (opening the arrow for the first quest).

**Comment by Dyaxler** [comment]
Thank you! I knew I was forgetting something. See... work distracts me. :P

**Comment by Dyaxler** [comment]
This has been fixed in the latest release - Hotfix:
https://github.com/AeroScripts/QuestieDev/releases/latest
