### ISSUE TITLE
Find a decent build of TomTom or some other "arrow" mod and back port it to Vanilla

### ISSUE THREAD

**Issue by Dyaxler** [AeroScripts/QuestieDev#379]
I'm going to do some research and find a code base with a good calculation stack that doesn't gobble up tons of memory. I removed the Time To Arrive feature from the QuestieArrow and a few folks have reached out to me to ask for it back. This feature was the only thing that I could cut from QuestieArrow to improve performance.

I'm also hoping to find the following features:
- Ability to set their own Way-points with a right click on the World-map.
- Turn on a feature that will always point to the closest Objective or Quest Finisher NPC.
- Import a list of Way-points in a specific sequence then carry out that queue for the purpose of farming materials.

**Comment by drtakhs** [comment]
WOW! this sounds super awesome! i wish i could help but I'm in the middle of an exam period so my free time is non existent :<

**Comment by crumdidlyumshis** [comment]
https://forum.elysium-project.org/topic/29180-addon-tomtom/

**Comment by Dyaxler** [comment]
Have it... need to review the code first. Not sure where the source came from.

**Comment by Schaka** [comment]
When I ported the Arrow, I took it from TomTom for TBC, but used an older (almost fully vanilla) version of Astrolabe, which is TomTom's #1 dependency.

**Comment by laytya** [comment]
use Astrolabe from Questie -its updated and improved.

**Comment by Schaka** [comment]
Yes. The arrow is already the TomTom arrow - and Astrolabe has been improved a lot. If you do decide to do this, I'd write it from scratch (an API around the arrow), not try to backport anything.
