### ISSUE TITLE
Make Questie work with Quest Chat Hyperlinks

### ISSUE THREAD

**Issue by Dyaxler** [AeroScripts/QuestieDev#380]
...it will also be compatible with ShaguQuest's method so users of both Questie and ShaguQuest can see each others Quest Chat Hyperlinks.

Questie will do the quest look ups via it's own database rather than having a dependency on the users Queset Log and being **ON** the quest in order to see the quests description.

**Comment by Dyaxler** [comment]
Haha... success. :)

![image](https://cloud.githubusercontent.com/assets/17400948/22368632/7a86fe74-e43c-11e6-86f5-2163f304bd28.png)

**Comment by Muehe** [comment]
@SalviaSage

**Comment by SalviaSage** [comment]
Thanks dyaxler.

**Comment by Dyaxler** [comment]
...and since I'm using the same hooking method as Shagu; if a Questie user links a quest in General Chat or a Whisper and the recipient has either Questie or ShaguQuest, they will see the link and it'll be displayed based on that AddOns functionality. ShaguQuest will only show you the Quest Description if you're on the quest. Questie pulls the info out of it's own database so there is no dependency. 

@Muehe : Maybe you can copy what I'm doing and add it to ShaguQuest? ;)

Anyway. I'll have this checked in soon.

**Comment by Muehe** [comment]
Going to do that one of these days. Will require some rework though, as currently I am deleting objective text on unique quest names. Btw. I released the 8.0 Beta, totally forgot to mention it.

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).
