### ISSUE TITLE
Incorrect Quest Markers are shown during Instances

### ISSUE THREAD

**Issue by ThiconZ** [AeroScripts/QuestieDev#382]
While in an Instance, quest markers for unrelated quests are still displayed on the minimap and Worldmap. While in an instance if quest markers cannot be shown properly they should be hidden from view automatically.

Screenshot showing unrelated quests in Scarlet Monastery:
![image](https://cloud.githubusercontent.com/assets/6924950/22361732/9192b7fa-e42a-11e6-869c-da83c6817587.png)

**Comment by Dyaxler** [comment]
I'm going to mark this as invalid and close it. There is a TON of work that is currently being done for Quest Starters, Finishers and Objectives that will be in the new 3.70 release. I can't say that this new work will "resolve" this particular issue but there is no sense in troubleshooting this until after that has been released. I will try and repro this bug with those changes to see if it occurs but I can't guarantee it. It's best to wait and see if it repro's after 3.70.

Please re-open this bug if it happens.
