### ISSUE TITLE
Missing Quest Marker - Arachnophobia (Stonetalon Mountains)

### ISSUE THREAD

**Issue by Svettkraft** [AeroScripts/QuestieDev#383]
There is a wanted poster at 59,76 that gives you the quest Arachnophobia, which is not displayed on the map at level 20.

**Comment by Dyaxler** [comment]
Yep... no coordinates for `['startedBy']="Wanted Poster: Besseleth",`

Added. Fix will be in next release.

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).
