### ISSUE TITLE
Distance calculation does not work across zones/maps

### ISSUE THREAD

**Issue by Schaka** [AeroScripts/QuestieDev#39]
Self explanatory. We need to implement Gatherer's cross-zone distance table to properly calculate how far away a certain objective REALLY is.

**Comment by Schaka** [comment]
This will be done when moving to Astrolabe with all calculations

**Comment by AeroScripts** [comment]
Yeah, astrolabe's Astrolabe:ComputeDistance works across multiple zones (and continents)
