### ISSUE TITLE
Quest Arrow doesn't show up?

### ISSUE THREAD

**Issue by Ayrill** [AeroScripts/QuestieDev#390]
Hello, i got questie(v3.69) a few days ago (lvl 20 now) and it works pretty fine for me.

I just can't get the arrow to work.

i tried it with the /questie arrow command and i get the message "Arrow should be shown now" but it doesn't appear after all.

is there something i'm missing? or do i need a additional addon to get the arrow?

Regards

**Comment by Muehe** [comment]
[FAQ](https://github.com/AeroScripts/QuestieDev/wiki/FAQ&Readme)

>    Q: Why isn't the QuestieArrow appearing?

>    A: You have to click on an objective on the Minimap, Worldmap or the quest in the QuestieTracker. If a quest has never been tracked it won't appear until after it has appeared at least once in the QuestieTracker. If you disable the QuestieTracker, the QuestieArrow will not work.

If this doesn't help, please re-open the issue. Closing it in the meantime.
