### ISSUE TITLE
QuestieTracker not showing quests

### ISSUE THREAD

**Issue by NicotineLL** [AeroScripts/QuestieDev#393]
Some (if not most) quests I track are not shown in the QuestieTracker. Map/mini map objectives are also not shown for the quests.

I'm attaching an image of the issue.

![questie-bug](https://cloud.githubusercontent.com/assets/6986993/22518830/c9097bca-e8b6-11e6-9ca1-ed2c188a37b5.jpg)

I reinstalled the addon, even NUKEd it (cry), but the problem persists. Even tried disabling all other addons but Questie - the result is the same.

Now, I did check the Database folder and quests/objectives are in there so the problem must be somewhere else.

Any ideas?

**Comment by Muehe** [comment]
Seeing you have EQL3, please make sure its settings are correct. Also make sure you have the latest release installed and `/questie showquests` activated. [FAQ](https://github.com/AeroScripts/QuestieDev/wiki/FAQ&Readme):

> Q: I can't seem to get my quests to appear in the tracker automatically.

> A: For those not running EQL3 or some other QuestLog mod. If you prefer the default wow QuestLog and Tracker that's fine but it's very limited. For example, if a quest doesn't have any objectives to "track" then it won't appear in the quest tracker and no Quest Arrow will be available for it. Additionally, quests will not automatically be tracked by the default WoW quest tracker. The way that it works is that if you have the option enabled in the games Interface Options --> "Automatic Quest Tracking" then yes, it will auto track a quest with an objective once you OBTAIN the first quest item. Then it will appear automatically in the list unless you manually Shift+Click the quest in the QuestLog but again, only if there is a "trackable" objective. Unlike EQL3 or other QuestLog/QuestTracker mods where pretty much anything is trackable, these quests will appear in the Questie QuestTracker. If the quest appears then map coordinates are cached and this allows the QuestieArrow to hook into the position and give you an arrow.

Closing this issue for now, assuming it is a configuration problem. If your problem persists, please reopen this issue and post the output of the `/questie settings` command. Thank you!

**Comment by NicotineLL** [comment]
Hello @Muehe,

Here's a screenshot with all addons diabled (only Questie enabled) and toggling /questie showquests (it was _true_  to begin with). Also my current settings, I hope that helps.

![questie-bug-2](https://cloud.githubusercontent.com/assets/6986993/22533917/822dd992-e8f9-11e6-8c79-baa0210d1e71.jpg)

**Comment by Muehe** [comment]
Yeah, as stated in the FAQ excerpt I posted above, limitations apply when not using EQL3. In the EQL3 options you have to check two fields for everything to get added automatically to the tracker (you will still have to Shift+Click the quests you currently have in your log or progress on them so they get added, but new quests should work fine):

![eql3](https://cloud.githubusercontent.com/assets/8838573/22534224/e0fb24ae-e8f2-11e6-8a4b-6e0af13f3833.jpg)

**Comment by NicotineLL** [comment]
I went back to Gadgetzan and tried to abandon and retake a quest just to see what happens. As I click Abandon most (note: _most_, not all) quest suddenly became visible in the tracker. However as I was taking/abandoning quests some were becoming visible, others - invisible. Sometimes I shift-click a quest to add it to the tracker but it adds the quest above it too, then when I try to remove it from the tracker it doesn't go away.

I abandoned all PvP quests I had and it seems like things are back to normal.

Do you think that a bug in the quest database could cause such a behavior?

I searched the Database folder for a little bit and noticed that in addendum.lua there is no quest named "Arathi Basin Mark of Honor" (other 2 PvP quests that are in my screenshot were present), there is however "Conquering Arathi Basin" which is the correct name of the quest. Do you think this could've messed up the tracker? This whole thing seems like a bug to me rather than misconfiguration.

Anyways, thank you for your support!

**Comment by Muehe** [comment]
Hmm yeah you are right, this sounds weird. I know there is some code that changes Questie internal strings for dungeon quests and PVP quests, maybe that is causing this. I'll try to investigate it, but I'm not sure I'm experienced enough with the source yet @Dyaxler.

**Comment by Dyaxler** [comment]
The two PVP quests you mentioned could potentially cause some issues. I'll have to look at the Quest Title scraping code and see if there is some kind of weird conflict.

I did attempt to shore up the DB scraping code to make Objects, Items and various other types of quests show up on the map to help reduce the number of "Hey, this quest giver doesn't show up..." only to find out that it's flagged as an Object rather than a Monster/NPC. I've fixed other Object/Item orientated quest start-able quests by simply changing the flag in the DB from Object or Item to Monster then making sure a location was in the DB for the Quest Starter. 80% of the time the location info was there. Which lead me to think that maybe we were missing a couple of parsing functions for Objects and Items. Duplicating the "Monster" scraping code seemed like a logical place to start but now I'm thinking I should reverse those changes....

**Comment by ZoeyZolotova** [comment]
@Dyaxler I've been having a look into the object/item/monster issue. You can look in my fork to see how i'm progressing, but more specifically [here](https://github.com/ZoeyZolotova/QuestieDev/commit/57339a9da49b19f782738bf796d2474333868448#diff-a9c27313150ba3163797df4a57abacfeR55546) and some of my comments on #317

**Comment by Dyaxler** [comment]
AWESOME! I just finished resolving another bug that might be causing some of these issues. It had to do with how the Quests and Objective clusters were shown and hidden. The logic order was all changed. Just finished redoing it and it's working FLAWLESSLY. :)

Sorry that I haven't been around for the past couple of days. I got sidetracked and wrote a new mod. I named it BlizzMo. I can now move any Blizzard frame and Bags with a toggle'able save state and you can adjust the frames scale with a simple mouse wheel flick. I grew tired of MoveAnything. The method for moving frames around... Oy!

I'll be uploading it tomorrow morning after I get some sleep. It's 3 am here in Seattle. :( Need to take one more test pass so I can dive into finishing up Questie v3.70 and get this bad boy out. The fixed bugs are piling up!

I'll put my dev build on a private GitHub folder so you can take a look at what I've done so far and make sure it doesn't conflict with your DB changes. :)

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta). If you continue having problems, please re-open this issue or create a new one.

**Comment by mailbox112** [comment]
how do I make it to not show quests that I have taken as still being available I found the guide once and cant seem to find it again

**Comment by AeroScripts** [comment]
Your history DB may be corrupted, try this command ingame:

/run Questie.db.char.complete = {}

And then /reload
