### ISSUE TITLE
Compendium of the Fallen dont displayed

### ISSUE THREAD

**Issue by BoneLord** [AeroScripts/QuestieDev#394]
Quest "Compendium of the Fallen" dont displayed in map and minimap.

![wowscrnshot_013017_231729](https://cloud.githubusercontent.com/assets/1656752/22522653/7b55d7d6-e8cd-11e6-87f1-8eb6efa39f0d.jpg)

[Compendium of the Fallen](http://db.vanillagaming.org/?quest=1049)

**Comment by Muehe** [comment]
Seems to work for me, do you have the newest version of Questie installed?

![compendium](https://cloud.githubusercontent.com/assets/8838573/22533914/1a40806c-e8f1-11e6-9fd0-d64ab132b4aa.jpg)

**Comment by BoneLord** [comment]
I have v3.66

**Comment by Muehe** [comment]
Please update to the current [version 3.69](https://github.com/AeroScripts/QuestieDev/releases) and see if that fixes your problem.
