### ISSUE TITLE
Questie Tracker not showing

### ISSUE THREAD

**Issue by Tepetkhet** [AeroScripts/QuestieDev#399]
Hey people,

Posted this on the E forums as well.

Questie version:  3.69

Recently started playing Vanilla and Questie was the first AddOn I installed.  It worked ok, but seemed a little flaky (quest log / tracker position would randomly move, ! shows up on the minimap for quests that don't exist).  I decided to install Titan Panel and Elkano's Buff Bars, and now Questie will NOT show the quest log at all on any characters.  The minimap tracker still shows, but I can't get the quest tracker, even if I try /questie clearconfig and /questie cleartracker.

What's interesting is that now even on a NEW character with ONLY the Questie mod enabled, I am seeing the following error after trying the clear commands:

![questieerror](https://cloud.githubusercontent.com/assets/25622814/22713325/95b0ec0e-ed4d-11e6-9286-d8d4e5063cdb.jpg)

"ERROR!  Database Detected!"

Any ideas what's going on here?
Thanks!

Edited to add that I don't think this is the same issue as #393 which is why I posted a new issue.  The tracker isn't showing at all now.

-T.

**Comment by Muehe** [comment]
> It worked ok, but seemed a little flaky (quest log / tracker position would randomly move, ! shows up on the minimap for quests that don't exist).

There are some commands with which you can control tracker behaviour, see our [FAQ](https://github.com/AeroScripts/QuestieDev/wiki/FAQ&Readme). Tracker behaviour can be a bit confusing at first, especially when using other addons. It's recommended to use EQL3 if you want to see every quest all of the time in your tracker.

> I decided to install Titan Panel and Elkano's Buff Bars, and now Questie will NOT show the quest log at all on any characters.

Totally possible one of the addons is messing with the tracker, however Titan Panel works fine for me. Maybe a TP plugin is doing this? If you want help, it would be a lot easier if we knew exactly which of these two addons (or which specific TP plugin) is causing the issue.

> What's interesting is that now even on a NEW character with ONLY the Questie mod enabled, I am seeing the following error after trying the clear commands:

This message appears if you have a level 1 character with more than 2 quests in its SavedVariables. These SavedVariables for addons do not get deleted when you delete a character, so this should (in theory) only show for characters that use a name you have previously used for another, now deleted, character. If you accepted 3 quests on a level 1 character though, you can ignore this message and just click no. Not sure how this message would get triggered by using the clear commands, but you should still be save just ignoring it.

**Comment by Tepetkhet** [comment]
Here's a screenshot with only Questie enabled:

http://i.imgur.com/jDG17sR.jpg

The toggles should also be displayed at the bottom left.  Am I missing something?

-T.

**Comment by Muehe** [comment]
Yes, your quests are not tracked. You have to Shift+Click them, so they have a little tick behind them, or use EQL3 and configure it as described in #393

**Comment by Tepetkhet** [comment]
Ah ha.  When I enabled EQL3 and ticked items off, the quest tracker appeared.  Thanks.  I didn't realize EQL3 was a requirement.  Seems to have done the trick, though.
Tracker is now appearing, even on characters with other plugins enabled.
Appreciate the help.

-T.

**Comment by Muehe** [comment]
You are welcome. Note however that EQL3 is not strictly a requirement. You can show a tracker without it, but you'd have to add most quests manually or by progressing on an objective (if you have that Interface option enabled in the WoW client) and you won't be able to show quests without objectives (I think) or finished quests in the tracker.
