### ISSUE TITLE
Pick Up Quest icons are showing even if you are not eligible (like too low level) to get the quest.

### ISSUE THREAD

**Issue by valmarkuristik** [AeroScripts/QuestieDev#40]
This is super confusing and clutters the maps.

There should also be an option to resize the quest tracker though, it's pretty big for laptop screens for example.

P.S. Thanks a lot for working on this, loving the addon a lot thus far, nothing else comes even close.

**Comment by Schaka** [comment]
You can resize the tracker by doing 
/run QuestieTrackerFrame:SetScale(0.5) 
for example. However, please download the latest version first, the size has changed.. 
The quest level thing is something else we will look into. We might have the wrong data available.

**Comment by AeroScripts** [comment]
The reason for this is that the value for the quest level is somewhat ambiguous, as it refers to the quest's recommended level not what it requires. This is also something that would be fixed by getting a better source of data (mangos-zero)

**Comment by valmarkuristik** [comment]
Yeah, it's also offering a druid shaman totem quests(for example The Call of Water), etc.

**Comment by Schaka** [comment]
Fixed as of https://github.com/AeroScripts/QuestieDev/commit/b5f4c33079489a124e9e79f8467b435308d4c975

Still doesn't differentiate between factions
