### ISSUE TITLE
2.4.3 version...

### ISSUE THREAD

**Issue by Ryofu** [AeroScripts/QuestieDev#403]
It kinda works,I don't really need it for outland content but for vanilla.It correctly shows quests on map,tested all function it's just it point at wrong position.Example in screenshot,I just accepted first 2 quests and it points somewhere in Silithus. http://imgur.com/a/bk9jJ Also,blood elf and draenei quests shows an error that it cannot find the quest,but I assume it's because it's outland.

**Comment by Muehe** [comment]
The map icons being off like that is the result of the Astrolabe library using map boundaries from classic, not TBC. Would be a matter of extracting them from the dbc file contained in the TBC client and apply the data to the lua file. However QuestieTBC is not under active development currently and the version in our branch is an archived alpha. For this reason, and because both issues would be fixed in case development picks up again, I am closing this issue for now.

**Comment by Dyaxler** [comment]
Uh that branch is ALPHA - ALPHA stage and the code is now horribly out of date compared to the current version we're working on right now. I "ported" to a BC compliant code base to have something to work with. Yes, Astrolabe data is off. And the database needs BC quests. I was planning on updating it once I got a new DB from one of the other devs but that never happened. We might still make one some day. But BC has QuestHelper and a few others I think?

**Comment by Ryofu** [comment]
For me Questie rules,it's so flexible,convenient and in the end visually more attractive.I pretty much know all the outland content quests since it introduced quest hubs.Problem is of course vanilla ones,I like seeing quests on map,to "feel the progress" as I level.Questie is just too superior to questhelper and any other quest add on I tried.

**Comment by Dyaxler** [comment]
I'm sure this comment will severely bloat Aero's already bloated ego. :) I think some of the other Dev's mentioned trying to extract a new DB directly from mangos that matches the 3.x schema. One has already been built for v4 but it's not compatible with v3... I'll see what I can do about porting over the next release. No promises. If it only take me an hour or two to convert the necessary code to make it BC friendly then I'll do it when I have some down time.
