### ISSUE TITLE
SimpleMiniMap integreation

### ISSUE THREAD

**Issue by lordninjamelon** [AeroScripts/QuestieDev#404]
I'm using [SimpleMinimap](https://github.com/ericraio/vanilla-wow-addons/tree/master/s/simpleMinimap) with square skin ("/smm skin")

This results in a square minimap, and it doesn't seem that Questie is compatabile with that.
[example .gifv](http://i.imgur.com/YrqP1VZ.gifv)

Issues:
Questie starts flickering when walking
Very often, the minimap icons are drawn in fixed position on the minimap, and don't actually reflect their in game coordinates, i.e. if I was far away from quest giver and yellow "!" was in the corner, even when I stand right next to the quest giver, the "!" is still in the corner.

If these issues are unlikely to be fixed, could you point me in a right direction how to fix it myself?

**Comment by Muehe** [comment]
See https://github.com/AeroScripts/QuestieDev/issues/287#issuecomment-273370141 and try the SMM version provided there please. Closing for now. Please reopen if problem persists.
