### ISSUE TITLE
Questie causing WoWError 132 and crash.

### ISSUE THREAD

**Issue by SneakySphynx** [AeroScripts/QuestieDev#409]
Read several others suffering from the same thing.

If i don't track/untrack deliver/pickup quests it won't crash.
Last version worked perfectly. 

Any news about this, or an upcoming fix maybe ? :)

Thanks for all your hard work.

**Comment by Muehe** [comment]
Please delete the directories **WDB** and **Cache** (if present) inside the World of Warcraft directory, and retest.

**Comment by SneakySphynx** [comment]
Alright, did that when i installed addon etc. 
But i'll give it another try.

Deleted WDB folder, didn't have a Cache folder.

Will report back!

**Comment by SneakySphynx** [comment]
Worked pretty decently mostpart of the day, but it gives me a slight laggspike everytime i pickup a quest.
Which might just be to load the markers on world/minimap.

But it ended up in another crash 5 min ago.

Will be online a bunch tommorow aswell, and will report back if i crash more or less etc.

**Comment by SneakySphynx** [comment]
Another crash, while abandoning a quest.

**Comment by SneakySphynx** [comment]
My addons, all up to date.

Atlas
AtlasLoot Enhanced
AtlasQuest
Aux
Cartographer
ccwatch
Classic Snowfall
Debuff Timers
Extended QuestLog
EzDismount
Improved Error Frame
Mobhealth 3
Mobhealth 3: Blizzard Frame
Postal
SuperIgnore
VanillaGuide
WIM
pfUI
OmniCC
Questie v3.69

**Comment by Muehe** [comment]
Please try to reproduce the crash with only Questie active, to rule out compatibility issues.

**Comment by SneakySphynx** [comment]
Turned everything off except Questie, abandoned / accepted quests nothing happend at first.
Then i tracked a few quests and BAM crash again.

**Comment by Muehe** [comment]
Please list some of the quests this is happening with. Or does it happen for any quest?

Another thing to test is renaming your WTF directory (it contains all addon and game settings). If this fails to solve your problem delete the new, automatically created WTF directory and rename the backup to WTF again to restore your settings.

Furthermore, we are currently in the process of testing a new release, which will introduce some changes to the tracker code. You also could give that a try:

[Questie.zip](https://github.com/AeroScripts/QuestieDev/files/800492/Questie.zip)

**Comment by SneakySphynx** [comment]
Will try that out right away, i just noticed i hadn't tried reproducing the crash without Questie enabled, and felt abit embarassed. 

But i've been Accepting/Abandon/Tracking for 5+ minutes now and no crash with 0 addons enabled.

Reporting back within 10 minutes.

**Comment by SneakySphynx** [comment]
So far it seems to work pretty well, but it's spamming my chat after every mob with:
SYNCLOG / CHECKLOG / UPDATE / TRACKER / TRACKERSIZE etc

Anyway to turn that off? :)

**Comment by Muehe** [comment]
Those are debug messages, they will be removed in the final release.

**Comment by SneakySphynx** [comment]
Yeah figured, as long as it works i'm more than happy. 
Will report back if a crash will happen, and thanks for the help so far! 
Really appreciated.

**Comment by SneakySphynx** [comment]
Alright, played for most part of yesterday. 
And havn't had any crashes yet, so far so good.

Will update again if something happens!

**Comment by SneakySphynx** [comment]
Been playing for 9 days now, and not a single crash!

**Comment by MaxiM-PL** [comment]
I've been playing for weeks without an issue, but once I've got to Stranglehold Vale and started questing there, Error #132 started popping every few minutes.

**Comment by Muehe** [comment]
@MaxiM-PL Do you have the Chapter quests for Green Hills of Stranglethorn pages?

Anyway, try setting addon memory to zero in the character selection screen. That removes the memory limit. You could also try to configure Questie to not follow untracked quests using the ingame slash commands and make sure the Chapter quests are not tracked.

Furthermore, you can try to use the version of Questie I uploaded above, it might fix your problem.

**Comment by MaxiM-PL** [comment]
Yeah, I've got the chapters quests. Tried the attached version above but the chat spam was too much and I don't know which file to edit to get rid of it. There was also another problem: when questie's tooltip pops up the framerate of the game drops dramatically (from super stable and unmovable 60FPS to 25-30).I'll try setting memory to zero and I'll report back. 

Btw, love the grey !'s in this new version. It makes more sense now. Can't wait for the finished version.

**Comment by Muehe** [comment]
That is related to the Chapter quests as well. Lag should be gone once you finish them. Apart from completely deactivating Questie the only solution would be to abandon the quests until you have them finished (the pages drop regardless of you being on the quest).

**Comment by MaxiM-PL** [comment]
I'm done with the quests and it happened again with more quests from Booty Bay, but only after ~2h of gameplay after finishing chapters/green hills, so the main culprit is gone. Setting memory to 0 didn't help while I was in the middle of these quests. Seems the more "bag" icons there are on the map, the worse it gets.

**Comment by iotheo** [comment]
I am experiencing the same issue with the current stable version (3.6.9). I'll try the v3.70 and report back.

**Comment by iotheo** [comment]
So far so good. Everything runs great with the v.370. No crashes whatsoever.

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).
