### ISSUE TITLE
Strange map zones confuse Questie

### ISSUE THREAD

**Issue by anojoyman** [AeroScripts/QuestieDev#41]
Hello, this is some superb addon and it is doing great job for me and my friends, but there is little bug that is too annoying and I think it is easily fixed. When I am in Deeprun Tram waiting for the train or traveling in it Questie fills my chat log with message like : "Questie: Strange Zone Map ID: -1" and something else for trying to reset. And this is done like 5-10 times a second. I cannot read if someone was selling something, needing people for group or anything. Also when I am in town minimap is showing quests tracking from previous zone - which is confisung. Thanks and keep up the good work!

**Comment by Schaka** [comment]
Please update to the latest version, this issue has already been resolved.
See here: https://github.com/AeroScripts/QuestieDev/commit/5a6c56cb817b5fa4a683a4f22c8430d17ad38f44
