### ISSUE TITLE
"Watcher Callahan"

### ISSUE THREAD

**Issue by drtakhs** [AeroScripts/QuestieDev#411]
I think the quest "Watcher Callahan" in duskwood does not exist. Yet, there is an exclamation point on the map saying that "Watcher Dodds" offers this quest. I searched online for this quest and i think this might not exist.

**Comment by Muehe** [comment]
We are aware of this issue and it will be fixed in one of the upcoming releases. Thanks anyway for the report!

**Comment by drtakhs** [comment]
Btw in case you aren't already aware, questie does not add a marker for the quest [The Weathered Grave](http://db.vanillagaming.org/?quest=225) on the map. Not sure if i should have opened a new issue so i put it here. 

Keep up the good work guys and thanks for this great addon!

**Comment by Muehe** [comment]
I also researched The Weathered Grave quest, it shows up fine in v3.7.0
