### ISSUE TITLE
Questie side tracker Disaperes after entering world

### ISSUE THREAD

**Issue by Zikasuo** [AeroScripts/QuestieDev#412]
If you shift click a quest it puts it in you're tracker on the right side, i tried to click on it and the whole side menu pane is gone, if i relog it shows up for a split second but then disappears

**Comment by SneakySphynx** [comment]
Try to reset position, do /questie ingame and you'll see a ton of commands in chat.

**Comment by Dyaxler** [comment]
> /questie cleartracker

is what you need I think. Maybe you encountered some weird edge case and your tracker is minimized.
