### ISSUE TITLE
Chill of Death not marked as finished

### ISSUE THREAD

**Issue by niclaslindstedt** [AeroScripts/QuestieDev#414]
When I finished the Chill of Death quest, it did not disappear on the mini map. Instead, it shows as a question mark.

Everytime I hover over an item from the quest (coarse thread) or the question mark, I get this error:

![image](https://cloud.githubusercontent.com/assets/615926/23752122/5b501be0-04d4-11e7-8c54-18edf664cc81.png)

I'm thinking the quest wasn't marked as finished since I still have quest stuff in my bags? They weren't quest specific.

**Comment by niclaslindstedt** [comment]
The problem disappeared after I relogged, but then other quests shown up on minimap as exclamation points, eventhough I had already taken those quests (but not finished).

**Comment by Dyaxler** [comment]
We're working on a new release at the moment and we've noticed some timing differences between servers. Latency seems to be effecting how quickly certain functions are firing. Currently these timings are fairly aggressive to keep things quick. The above referenced error message isn't much help I'm afraid. The line number refers to a function that intercepts the Blizzard GetQuestLogTitle(index) and pipes it to the Questie version. Could be that it's looking for Quest, Tooltip or Mapnote cache data that is no longer there - hence the incorrect icon. Having quest items left over in your bags won't affect Questie.

When you reloaded your UI and icons showed up for quests that you've accepted is a bit concerning. Sounds like your Saved Variables file might have gotten messed up. During a reload, it gets moved from memory and saved into that file. If it's not making it into the file, then this would cause the icons to reappear as ! icons. I would try running:

> /questie clearconfig

This will reset your Questie settings and your caches but not touch your finished quests DB table.

**Comment by Dyaxler** [comment]
Closed due to lack of response.
