### ISSUE TITLE
Questie Dev map problem.

### ISSUE THREAD

**Issue by haverdaden** [AeroScripts/QuestieDev#416]
I've been using the stable version but it lags my game pretty badly so I wanted to try these dev versions but all of the dev versions I tried are acting really wierd with the same problem and error.

I've tried deleting my WTF files and running only Questie. That didn't help though.
Edit: Also deleted WDB.

Attempt to index local "questinfo" (a nil value). Line 84.
![questiegif](https://cloud.githubusercontent.com/assets/15102449/24014800/898d921e-0a86-11e7-9f9e-2519d1033955.gif)

**Comment by Dyaxler** [comment]
When the error was thrown the notes stop updating. That's why your notes aren't updating after the map changes zoom levels... which Dev commit were you running that triggered the error after Toggling questie back on?

**Comment by ZoeyZolotova** [comment]
He has the minimap icon so it must be one of the more recent ones.

**Comment by ZoeyZolotova** [comment]
Can you list what quests you have?

**Comment by haverdaden** [comment]
![skarmklipp](https://cloud.githubusercontent.com/assets/15102449/24038706/d8bcb4f6-0b02-11e7-8b67-f57615f71580.PNG)

That was the latest dev commit. 
Tried two versions from one week before and got the same error.

Btw running the latest stable version again.

**Comment by ZoeyZolotova** [comment]
I've confirmed that the problem is that on the server you are playing, it incorrectly gives the quest title "A Plague Upon Thee (part 2)" when it should be "A Plague Upon Thee". Thinking about how to handle these situations.

**Comment by ZoeyZolotova** [comment]
For now i'll start with preventing the error if no quest information is found so that the ones without a match will simply not appear on the map, rather than breaking everything.
May look into making corrections for incorrect quest names later.

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).
