### ISSUE TITLE
Quests with a name that doesn't match the one in the Questie database don't show their finisher location.

### ISSUE THREAD

**Issue by ZoeyZolotova** [AeroScripts/QuestieDev#418]
Discovered this problem when investigating #416 

We could try to find the closest match if an exact match doesn't exist, but that may impact performance. Not sure of the best solution.

**Comment by GavrilenkoS** [comment]
jfyi

Shaman quest "Call of water (part 6)" partially broke quest tracking for me until I abandoned it. I mean some quests never appeared in track list when were shift-clicked in quest log. Checked on 3.69. 

Looked like this:
![wowscrnshot_031917_134059](https://cloud.githubusercontent.com/assets/26520598/24080396/729b6682-0caf-11e7-8f39-26e4ffc5b502.png)
