### ISSUE TITLE
Problem with 3.70 dev version

### ISSUE THREAD

**Issue by Larsy93** [AeroScripts/QuestieDev#419]
https://i.gyazo.com/302743c5e7cd5275713037ee27149157.png

keeps spamming all the time and cant pickup any quest or anything, any ideas?

**Comment by ZoeyZolotova** [comment]
Can you screenshot your quest log?

**Comment by Larsy93** [comment]
https://i.gyazo.com/0cb7fb461b4e1f9751be32665e743af5.png

**Comment by Dyaxler** [comment]
@Larsy93 Line 367 in QuestieQuest.lua is an end... which version of Questie are you running and where did you get it?

**Comment by Larsy93** [comment]
524bd00

tried removing my saved variables and redownloading but still doesnt work, tried on 2 computer aswell both at home and at work, will check if problem still exists in the newest version.

**Comment by Larsy93** [comment]
This is line 367 in the version im using

https://i.gyazo.com/cf51397772c3ab37986e001019792613.png

**Comment by Larsy93** [comment]
Just wanted to post and say i have the same problem with the newest version, now on line 368 tho.

**Comment by Larsy93** [comment]
https://i.gyazo.com/4c58cbca319dea86bd8febe2dd0652c6.png

**Comment by ZoeyZolotova** [comment]
Have you tried disabling your other addons?

**Comment by ZoeyZolotova** [comment]
Think I've found the cause. It's related to reputation quest objectives.

**Comment by Larsy93** [comment]
Yup, the errors stopped spraying once i abandoned "Ongeku" the quest with reputation as an objective, thanks.

**Comment by ZoeyZolotova** [comment]
Added handling of reputation-type objectives.

![image](https://cloud.githubusercontent.com/assets/22694317/24097559/7b49f03a-0dba-11e7-8d27-a23932735829.png)

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).
