### ISSUE TITLE
Reputation handling may need to take into account the player's current reputation for the faction.

### ISSUE THREAD

**Issue by ZoeyZolotova** [AeroScripts/QuestieDev#420]
Creatures reward reputation for a faction only up to a varying standing level (Friendly, Honored, etc.) and there may be quests that required Exalted. With the current implementation, it would show locations of creatures you can slay to gain reputation even if they don't actually award it at your current standing with the faction.

Need to investigate if such quests exist, and if so add the [MaxStanding](http://mangoszero-docs.readthedocs.io/en/latest/database/world/creature-onkill-reputation.html) column value into the Questie reputations.lua and use it to handle such situations.

Related to #419

**Comment by BreakBB** [comment]
Related to #316

**Comment by AeroScripts** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.
