### ISSUE TITLE
A suggestion!

### ISSUE THREAD

**Issue by drtakhs** [AeroScripts/QuestieDev#421]
We all know about the Shift-click to complete the quest manually, and it works great! But, how about a shortcut to "Hide" the quest? Let me explain.

Shift clicking is marking the quest as completed and removes it from the world map, but then after some time you can't tell if you have indeed completed it or just Shift-Clicked by looking at saved variables. 

After shift-clicking, the addon sees the quest as completed and opens the quests that are enabled by that completion (followup quests on a chain for example) . While, this works well, sometimes it has a lot drawbacks. 

Let's say i wanna temporarily (or permanently) hide a quest from the map maybe because it's a Blacksmithing quest and i don't have that profession atm. My only choice is to shift click it. This hides the quest (yay!) but also opens 3 new quests (whyyyy) on map (same npc or random location) that needed that quest completed to become available. So i have to shift click those as well, and this becomes chaotic and confusing especially for chains! Moreover, if down the line, i decide to pick up Blacksmithing for whatever reason, i have no way of going back on the map to look for some blacksmith quests! 

So here is my suggestion, 

add a way to hide quests without marking them as completed, and at the same time add one more button on the world map to toggle display of hidden quests! 
This way we will be able to hide a quest while still being able to find and pick it up later down the line! This is also especially useful on progressive realms, where seasonal events and/or war effort event are not active at the moment (or cloth turn in quests). Those quests make the map cluttered with unavailable quests that we shouldn't shift-click because we will need later down the line! So why not hide them, without marking them as complete!

Any thoughts?

**Comment by Dyaxler** [comment]
When you "shift-click" a quest to finish that specific one it only recursively finishes all the quests the come before it... not after. This is why you're seeing other [ ! ] icons appear after finishing a quest. It's the next quest in the chain or the one before it that you just finished was a required quest before the next one shows up.

I like your idea about "hiding vs finishing". It would be simple to just add an additional flag:

-1 for abandon
0 for active
1 for finish
2 for hidden

The "show hidden quests toggle" would simply show all the 2's. Doesn't sound tough to code in principle but I'd have to go through all the workflows to see how that would effect other things.

**Comment by drtakhs** [comment]
yeah i understand how shift-click works and how other [ ! ] icons appear, this is useful when for example client closes unexpectedly and saved variables aren't saved, but yeah hiding is something extra that could be added for other uses as mentioned above :) 

thanks for taking time to look into this

**Comment by Dyaxler** [comment]
Pushing this to post-v3.70 release.

**Comment by BreakBB** [comment]
All available quests can be seen in the journey system under "Quests by Zone"
