### ISSUE TITLE
questie 3.70 bug?

### ISSUE THREAD

**Issue by KasVital** [AeroScripts/QuestieDev#423]
can you fix this
![image](https://cloud.githubusercontent.com/assets/15636669/24654572/e676809c-1942-11e7-9c51-171151342a65.png)

**Comment by Larsy93** [comment]
Yeah Quest progress doesnt update much at all for me neither

**Comment by ZoeyZolotova** [comment]
Could you please list what addons you use?

**Comment by KasVital** [comment]
i tested questie only, same problem
![image](https://cloud.githubusercontent.com/assets/15636669/24702450/6fb802da-1a07-11e7-81c2-874c736390d3.png)

**Comment by ZoeyZolotova** [comment]
Yeah you're right it just happened to me too.

**Comment by ZoeyZolotova** [comment]
Should be fixed now. Try the latest code.

**Comment by KasVital** [comment]
Ye thanks
