### ISSUE TITLE
TBC lua:466 bad argument

### ISSUE THREAD

**Issue by slacker3007** [AeroScripts/QuestieDev#424]
Soon as you log in on 2.4.3 client u get error.
http://imgur.com/VxO2fsL

**Comment by Dyaxler** [comment]
Change this (line 466):

`local tbsize = table.getn(MBB_Exclude)`

to this:

`local tbsize = #MBB_Exclude`

And you should be good. This post might help with some other errors encountered when I converted the code from Vanilla to BC:
http://wowwiki.wikia.com/wiki/Patch_2.0.1/API_changes

**Comment by slacker3007** [comment]
I edited \Modules\QuestieNotes.lua, just like suggested and i get new error.
http://imgur.com/U5k3D8S
466: Attempt to get length of global 'MBB_Exclude' (a nil value)

**Comment by Dyaxler** [comment]
Ahhh... makes sense now. You're not using MiniMapButtonBag.

Change this:
```
	local MBB_ExcludeTemp = {}
	local count = CREATED_NOTE_FRAMES
	local tbsize = table.getn(MBB_Exclude)
	if tbsize == 0 then
		MBB_Exclude[1] = "QuestiePlaceHolderFrame";
	end
	if IsAddOnLoaded("MBB") then
		if tbsize >= count + 1 then return end
		for i = 1, count do
			MBB_ExcludeTemp[i] = "QuestieNoteFrame"..i;
		end
		for i = 1, #MBB_ExcludeTemp do
		 MBB_Exclude[#MBB_Exclude+1] = MBB_ExcludeTemp[i]
		end
		MBB_ExcludeTemp = {}
	end
end
```
To this:
```
    if IsAddOnLoaded("MBB") then        
        local MBB_ExcludeTemp = {}
        local count = CREATED_NOTE_FRAMES
        local tbsize = table.getn(MBB_Exclude)
        if tbsize == 0 then
            MBB_Exclude[1] = "QuestiePlaceHolderFrame";
        end
		if tbsize >= count + 1 then return end
		for i = 1, count do
			MBB_ExcludeTemp[i] = "QuestieNoteFrame"..i;
		end
		for i = 1, #MBB_ExcludeTemp do
		 MBB_Exclude[#MBB_Exclude+1] = MBB_ExcludeTemp[i]
		end
		MBB_ExcludeTemp = {}
	end
end
```

That should bypass that whole block of code if you're not running that addon. I use that addon all the time and ported a version to Vanilla. The BC version was causing some map note issues...

**Comment by slacker3007** [comment]
Yep, seems to be working. 
Also I'm getting error lines of: "QuestieQuest: Error! This doesn't Appear to be a valid quest or it's missing from the database. Please report on Github."
http://imgur.com/g4jDNUg

It seems to be tracking only one quest, rest get error:  "QuestieQuest: Error! This doesn't Appear to be a valid quest or it's missing from the database. Please report on Github."
Quests:
http://imgur.com/dN9pGti

If can provide any other helpful information let me know.

**Comment by Dyaxler** [comment]
As the readme states for that build. The DB is incomplete. All the BC quests aren't present.
