### ISSUE TITLE
Toggling Questie off and on causes the completed icons to stay gone.

### ISSUE THREAD

**Issue by ZoeyZolotova** [AeroScripts/QuestieDev#425]
Steps to reproduce:
- Have a completed quest
- Toggle Questie off
- Toggle Questie on

Actual Result:
- Completed icons don't reappear.

Expected Result:
- Icons reappear.

Specific situation that the issue occurred:
- I was doing [The Missing Diplomat](http://db.vanillagaming.org/?quest=1245) and after accidentally toggling Questie off, I noticed turning it back on didn't show me where to turn in the quest.

**Comment by Dyaxler** [comment]
Fixed in latest commit:
https://github.com/Dyaxler/QuestieDev/commit/7374e1564c7546363ffcb888f6df8215c21b2312

**Comment by ZoeyZolotova** [comment]
Do you think you could fix this in a way that doesn't make it take 2 seconds for the icons to appear after toggling Questie on?

**Comment by Dyaxler** [comment]
Here you go Zoey. :)
https://github.com/Dyaxler/QuestieDev/commit/dc5a537d41def3768d3fe2bd96ba1cfa2310477f
