### ISSUE TITLE
Script Error frame wont clear.  Pics included. 3.70

### ISSUE THREAD

**Issue by hvownij** [AeroScripts/QuestieDev#427]
installed lastest dev build.  It gave me the update screen before this happened.  
![wowscrnshot_041917_092518](https://cloud.githubusercontent.com/assets/27772441/25182523/e70a72c4-24e2-11e7-8af8-775cb548d2ae.jpg)
![wowscrnshot_041917_092524](https://cloud.githubusercontent.com/assets/27772441/25182527/eb1e71d0-24e2-11e7-82ca-c1c785f9378a.jpg)
I cannot use this addon currently unless i downgrade.  Then I cannot use the /questie command.

Bunch of trouble. Hopefully some I can get some help?

**Comment by Muehe** [comment]
Does this error also appear when you disable all other addons?

Also, see issue #265

**Comment by hvownij** [comment]
Yes.  Just tried to be sure again, Disabled everything but questie same errors

**Comment by Dyaxler** [comment]
Can you load ImprovedErrorFrame (http://addons.us.to/sites/default/files/addons/ImprovedErrorFrame.zip) and reproduce the error? I really need to see the full call stack.

The first error is trying to index a Blizzard Hook - the second error is just a common update. These are two functions that are part of Questies core functions. If it was an issue with Questie, we'd have every user beating on our door with errors. Must be a cache issue or another addon. Did you try clearing your WDB folder like Muehe suggested by linking issue #265?

Yeah, I need the call stack. :( I'd really like to know where this error is coming from so we can help you resolve it.

**Comment by hvownij** [comment]
Well first off, my malwarebytes pulls me away from that link, might wanna double check that on your end... I however did find a safe link to that addon and it actually makes it so I can use questie and play with the latest version because the error frame is changed...  here is the 3 errors it gives me questie related of course.
![wowscrnshot_041917_232051](https://cloud.githubusercontent.com/assets/27772441/25212236/3541191a-2557-11e7-99dd-383c5ebb2c8e.jpg)
![wowscrnshot_041917_232100](https://cloud.githubusercontent.com/assets/27772441/25212252/41e1f2de-2557-11e7-86f7-487a2b668220.jpg)

**Comment by Muehe** [comment]
Please try this:

1. Rename the `Interface` and `WTF` folders.
2. Start the game and log on to a character (this will create new folders automatically).
3. Close the game, re-install only Questie and test again.

If the problem persists, you can delete the newly created `Interface` and `WTF` folders and rename your back-ups to restore your settings and SavedVariables.

My guess is somehow the Blizzard UI files got changed and that is why Questie can not find the entry in StaticPopupDialogs table.

**Comment by hvownij** [comment]
I did everything you asked.  Tested again with only the questie addon in the folder and let it repopulate the blizz ui files.  Same issues, same errors.  No other addon is giving an error.

**Comment by Dyaxler** [comment]
Are you running this addon that is modifying all the client strings? Everything is in all CAPS. When we ask to not run anything we mean to run the WoW Client as it is when it's freshly installed. Any modification to the clients strings or the client can cause issues.

Please try just running Questie and ImprovedErrorFrame. All the errors in your screenshots are basically impossible and would only occur when the client files themselves are corrupt or modified in some way. I've dealt with this before. There are some Vanilla WoW projects where teams have made changes to the WoW client. :( I got my hands on one once and it does indeed screw with addons that rely heavily on certain Blizzard API's.

**Comment by hvownij** [comment]
There is nothing not stock about this installation except fonts.

**Comment by ZoeyZolotova** [comment]
What's the mod you're using called?

**Comment by hvownij** [comment]
Well I got my hands on my old cd install of wow reinstalled everything
issue is solved.  Something corrupted something somewhere.

**Comment by ZoeyZolotova** [comment]
Does it still work if you apply the font mod to the newly installed copy?

**Comment by hvownij** [comment]
Yes font mod is just a rename on the font files and replacement.  Just
gives wow a whole new feel after all these years.

Sorry for any trouble but glad we found my client to be abnormal and not
this great addon!
