### ISSUE TITLE
Cannot set waypoint from world map

### ISSUE THREAD

**Issue by mawarm** [AeroScripts/QuestieDev#433]
It was working at first but not anyomore. Now whenever I try to do it I get the following error message: "Interface\AddOns\!Questie\Modules\QuestieArrow.lua:111: attempt to index field `?' (a nil value)".

I am using some other addons and I did not test this in between installing each of them, I don't know if this could be caused by a conflicting mod?

**Comment by Muehe** [comment]
Closing as duplicate of #429

This issue will be fixed in the next release, see the other report for download instructions.
