### ISSUE TITLE
Bad argument errors

### ISSUE THREAD

**Issue by Caylara** [AeroScripts/QuestieDev#436]
The addon works fine otherwise, been using it in pair with cartographer to help me find quests

This is at the TBC version

![error_message](http://i.imgur.com/wWoQpxP.png)
> Edit by Muehe: embed image

**Comment by Muehe** [comment]
QuestieTBC is not in active development currently. That being said, if you want to fix it yourself, you can try to remove [this part](https://github.com/AeroScripts/QuestieDev/blob/QuestieTBC/!Questie/Modules/QuestieNotes.lua#L464-L479) from the file mentioned in the error message (that code is not in the [master branch](https://github.com/AeroScripts/QuestieDev/blob/master/!Questie/Modules/QuestieNotes.lua#L763-L782) anymore).

**Comment by Muehe** [comment]
Closed due to `wontfix` status. Feel free to ask additional questions in this issue if you require help on fixing it yourself.
