### ISSUE TITLE
Can't Move RESOLVED 

### ISSUE THREAD

**Issue by Ragranok2147** [AeroScripts/QuestieDev#438]
Help I can't Move the Marker or the Log of Quest it just stays in one corner and I can't move it

Edit
MY Dumbass didn't read it I found how yo move it

**Comment by joelgriffiths** [comment]
For later people who find this, The most recent Release uses <ctrl><shift>+<Left Click> to move stuff.

The thing the OP didn't read was the FAQ - the source code. 

I hate it when people mark things 'Resolved', then say "I figured it out<eom>."

**Comment by Muehe** [comment]
[FAQ Link](https://github.com/AeroScripts/QuestieDev/wiki/FAQ%26Readme#faq)
