### ISSUE TITLE
the quest list and arrow was by a mistake moved out of the screen (got dual screen)

### ISSUE THREAD

**Issue by aksina** [AeroScripts/QuestieDev#439]
the quest list and arrow was by a mistake moved out of the screen (got dual screen)
Got NO clue on how to get it back and tried and searched for MULTIPLE hours :( can ANY one help me

**Comment by Muehe** [comment]
Try `/questie cleartracker` and if that doesn't help try `/questie clearconfig`. See the [Wiki](https://github.com/AeroScripts/QuestieDev/wiki/FAQ&Readme#questie-slash-commands) for more commands.

**Comment by aksina** [comment]
didnt help :(

**Comment by aksina** [comment]
none of the commands seems to work

**Comment by Muehe** [comment]
You can use`/questie setting` to see if everything is set correctly. If not, use the other commands to adjust the settings. After that Shift+Click every quest in the quest log once. After that they should be added automatically.

**Comment by Muehe** [comment]
Assumed solved.  If you continue having problems, please re-open this issue or create a new one.
