### ISSUE TITLE
Astrolabe changes outdoor minimap zoom level to 3 on load of Questie if it is equal to the indoor minimap zoom level

### ISSUE THREAD

**Issue by grommpy** [AeroScripts/QuestieDev#440]
Similar to issue #292 , Questie sets a minimap zoom on load instead of using default preferred zoom levels in my config.wtf , which are:
```
SET minimapInsideZoom "0"
SET minimapZoom "0"
```
I don't like having to zoom out each time. What is going on here? I thought I had found the source on line 1287 in the tracker, but that just sets the general map. The issue persists on logout/login, whether i clear WDB or not, and only goes away when i disable Questie.

As mentioned in #292 , the issue is probably with Astrolabe itself, when the function Astrolabe:isMinimapInCity() is called.

Observations:
if minimapZoom != minimapInsideZoom , then the zoom settings are stored and retrieved correctly on load.
if minimapZoom = minimapInsideZoom , the minimapZoom = 3 always.

Questie is the only add-on that uses Astrolabe in my addon folder, and Astrolabe is deprecated.

I've tried updating the local function isMinimapInCity() with a newer bit of code from a later version of Astrolabe, but to no avail.

I can only suspect that... - more non-developer hunches that come from a lack of .lua understanding - ... I have to cut this bit of flawed logic out in Astrolabe.lua, line 300 to 308:

```
--    if (GetCVar("minimapZoom") == GetCVar("minimapInsideZoom")) then
--        if (GetCVar("minimapInsideZoom")+0 >= 3) then
--            Minimap:SetZoom(Minimap:GetZoom() - 1);
--            tempzoom = 1;
--        else
--            Minimap:SetZoom(Minimap:GetZoom() + 1);
--            tempzoom = -1;
--        end
--    end
```
This bit of code assumed + or - is pressed and seems to work with a limitation that the same zoom level cannot be set, but it is loaded as soon as Astrolabe.lua is loaded. I don't know what the original intention was of this function, but I've changed it so that it sets what it gets. My problem is fixed, and my minimap still works correctly, including quest icons!

I would recommend somebody include this fix in the master... if approved.

**Comment by Muehe** [comment]
Looks like a good fix to me. We are not currently merging into master though, as we have a development branch (see Readme) and there is a blocking issue nobody has the time to fix currently. Once that is taken care of pending fixes will be handled. Thanks for your effort!
