### ISSUE TITLE
Abandoning quest removes it from the map

### ISSUE THREAD

**Issue by astarielko** [AeroScripts/QuestieDev#442]
When i abandoned the quest in desolace that wants you to gather the ghost ectoplasm it vanished from the map as if i have completed it. Happens on other quests too.

**Comment by Muehe** [comment]
Which version are you using? The stable release (v3.69)?

**Comment by Muehe** [comment]
Closed due to missing feedback. Please re-open this issue or create a new one if you continue having problems.
