### ISSUE TITLE
Repeatedly "detects database" when no quests have been completed

### ISSUE THREAD

**Issue by Priddles** [AeroScripts/QuestieDev#443]
When no quests have been completed on a new character, Questie repeatedly warns "database detected" and asks to clear config. Clearing config in any way (whether by clicking yes, `clearconfig`, or `NUKE`) makes no difference. Reloading the UI makes the warning appear again.

**Comment by Muehe** [comment]
I think there might be a small mistake in that part of the code. It is intended for characters that were created with the name of a deleted character (so there might still be left over data in the SavedVariables). Once you get to level 2 the message should not appear anymore.
