### ISSUE TITLE
New quests don't appear on map

### ISSUE THREAD

**Issue by imbarr** [AeroScripts/QuestieDev#444]
New quests don't show up on map, which can only be resolved by nukeing and manually completing previous ones. Before that, "unable to concatenate a 'nil' value" error appeared a few times. Also, "?" icons on map sometimes don't disappear after quest is completed and remain until game reset.

**Comment by Muehe** [comment]
If you are using the v3.7 branch, see my answer on issue #446. Otherwise I would need to know the exact error message.

**Comment by Muehe** [comment]
Assumed solved.  If you continue having problems, please re-open this issue or create a new one.
