### ISSUE TITLE
Hemet Nesingwary in wrong place

### ISSUE THREAD

**Issue by oleedv** [AeroScripts/QuestieDev#447]
In the questline Raptor Mastery (http://db.vanillagaming.org/?quest=194) you get told to turn in the quest at Hemet Nesingwary. Questie shows him being somewhere on the edge of Eastern Plaguelands, when infact he is acutally in Stranglethorn Vale at his Camp right below the Rebel Camp. 

Thanks for making such a awesome addon!

**Comment by Muehe** [comment]
This issue has already been reported in #405 and is fixed on our development branch. You can download it from [here](https://github.com/Dyaxler/QuestieDev/archive/Version3.70.zip). Note: You only need the `!Questie` folder from inside the `QuestieDev` folder. If you just copy all the extracted files the addon won't work.
