### ISSUE TITLE
Option to disable quest log

### ISSUE THREAD

**Issue by valmarkuristik** [AeroScripts/QuestieDev#45]
Quest log and minimap buttons are showing quest completion wrong or as 0/0.

For now it would be great to disable it and use something else for quest log frame.

**Comment by AeroScripts** [comment]
Do you mean the tracker or the actual quest log? It shouldn't be showing incorrect values, what other addons are you using?

As far as being able to disable the tracker, that option is going to be added very shortly.

**Comment by valmarkuristik** [comment]
Both. It usually showed either 1 less item missing, or correctly complete on the tracker, and 0/x on both maps.
Yestoday I downloaded the newest version and deleted caches and whatnot, and now it seems to be working correctly.

**Comment by AeroScripts** [comment]
Oh ok, either way that's very strange, I'd never seen that happen even in an old version.

Closing this for now.
