### ISSUE TITLE
Switching from main branch to 3.70 dev branch

### ISSUE THREAD

**Issue by tsheeley** [AeroScripts/QuestieDev#450]
I'd like to try out the 3.70 dev branch, but I'm worried about losing the tracking of things I've already done.

What's the best way to migrate? Would there be an issue if I just cloned the dev branch in my GitDesktop and copied over version 3.69?

**Comment by Muehe** [comment]
If by "tracking" you mean finished quests, they are all saved inside the `WTF` directory. So if you make a backup of that before switching you can always restore them.

You can either download through GitDesktop or from https://github.com/Dyaxler/QuestieDev/archive/Version3.70.zip

Then just copy the `!Questie` directory over to WoWs addon directory, replacing all existing files.

**Comment by tsheeley** [comment]
Thanks! That worked perfect.

For some reason, GitDesktop didn't like cloning the dev branch... it kept cloning the main one, even though I was giving the dev folder a different name then the main... but the zip worked. So I'm not gonna argue with it.

One thing I was hoping this would do is hide the [Road to Salvation](http://www.wowhead.com/quest=2218/road-to-salvation) quest in Dun Morogh, since as a human I already did [Seek out SI: 7](http://www.wowhead.com/quest=2205/seek-out-si-7) in Goldshire. I know for a fact that I didn't do Salvation, so I'm thinking it's only for Dwarves? Are there any race checks in place for these kind of things... or at least something planned for a future version?

**Comment by Muehe** [comment]
Yeah quest 2205 and 2218 are mutually exclusive. 2241 (The Apple Falls) in Teldrassil too btw. Questie does not handle quest relations 100% correctly, which is something we are aware of and which would have to be fixed with a DB update.

Sadly my RL is a sh**show right now, so I can not promise anything in that regard. Unless someone from the other devs does jump in, it won't be fixed for 3.7.

**Comment by tsheeley** [comment]
Ah. I see. That's what I was figuring with those quests, so I just manually completed them.

No worries. RL comes first. If I had the time or coding knowledge, I'd assist with it... but alas, I have neither. I might randomly poke around the files tho, just for giggles.

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).
