### ISSUE TITLE
Questie Show Horde quest on alliance

### ISSUE THREAD

**Issue by ZeGaaL** [AeroScripts/QuestieDev#451]
When you play on the alliance side in STV ( Stranglethorn Vale ) you see 1 horde quest its the Quest Called: Grim Message ( http://db.vanillagaming.org/?quest=2932 ) - React: ( RED - A ) -  ( Green - H ).

Maby fix this so players dont go into horde camp and try to get this Quest. Minor fix but to make questie a good addon we need to perfect it  :)

**Comment by Muehe** [comment]
Fixed in https://github.com/Dyaxler/QuestieDev/commit/807c0367e38e58b45c2051993b2c851e4dd6bf42

**Comment by ZeGaaL** [comment]
Muehe

When will the next release come?

**Comment by Muehe** [comment]
It is basically ready, there was just one blocking issue (#446) which I think I fixed. I am waiting for feedback on the tracker behaviour before doing an official beta release though.

You can download it from https://github.com/Dyaxler/QuestieDev/archive/Version3.70.zip (Copy only the `!Questie` directory, not all the files in the zip archive).

**Comment by ZeGaaL** [comment]
STV Fix, good. I also love the new UI on the Questie lots easier to fix stuff and have it perfect. Still is some few things that are a bit bugged, but atm its not a problem.

**Comment by bigdilll** [comment]
I'm trying 3.70 atm and I think it's awesome ! Thanks !

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).
