### ISSUE TITLE
Invisible map & minimap icons

### ISSUE THREAD

**Issue by Haky00** [AeroScripts/QuestieDev#455]
Hey, I recently upgraded from a very old verson (2.0.4), and everything works except for one thing - icons on my minimap and map are completely invisible, but when I hover over the place where the icon should be, the tooltip appears (images).
I don't know if its some setting, addon incompatibility or something else.

Addons I am using that could cause problems (but even without them, the icons are invisible, so probably not):
Cartographer
Simple Minimap
![2](https://user-images.githubusercontent.com/32370956/30987410-364d9f4e-a497-11e7-8182-8bccaeac522f.png)
![1](https://user-images.githubusercontent.com/32370956/30987409-364da73c-a497-11e7-9ac8-6507aacff5f0.png)
![3](https://user-images.githubusercontent.com/32370956/30987506-853d2bec-a497-11e7-9ef2-39ea350faf44.png)

**Comment by Muehe** [comment]
Well this is weird. Only thing coming to mind is that you maybe forgot to delete the old folder? It was renamed from `Questie` to `!Questie`, so it would be loaded sooner. If you did not delete the old folder of version 2.0.4 there might be a conflict with the icon names... Are there any error messages in the chat when you first log in?

**Comment by AriinPHD** [comment]
Muehe obviously knows what they're talking about, but I agree. A lot of the !Questie updates have required me to delete all the old info to avoid background errors... Probably worth a shot, just remember to back-up the WTF and !Questie folder first in case you wanna revert back :)

**Comment by Muehe** [comment]
Assumed solved due to missing feedback. If you continue having problems, please re-open the issue or create a new one.
