### ISSUE TITLE
Completed quests merging

### ISSUE THREAD

**Issue by EvgenStudent** [AeroScripts/QuestieDev#459]
I play on 2 computers. But when I complete some quests on the 1st computer, these quests aren't marked as completed if I use the 2nd computer.

Do I have any ways to merge completed quests on all computers where I play? (except of local replacing of addon files)
Can 'QuestieDev' request a server for checking completed and uncompleted quests and update local DB cache by itself? 
Any other ideas?

**Comment by Muehe** [comment]
The database of finished quests is saved per character in a table found in `<WOW_FOLDER>/WTF/Account/<ACCOUNT_NAME>/<SERVER_NAME>/<CHARACTER_NAME>/SavedVariables/!Questie.lua`.

You can copy the whole `WTF` folder (or sync it with a cloud service) if your systems use the same settings for WoW itself (resolution, etc.) and have the same addons.

If they differ, you will have to copy/sync the files manually for each character or make a Bash/Batch script to do that for you.
