### ISSUE TITLE
No way to cancel crazy-taxi-esque arrow

### ISSUE THREAD

**Issue by ayrb13** [AeroScripts/QuestieDev#46]
Once i shift+click the quest name in tracker, an arrow displays on the head of my character, but I can't find a way to remove that arrow. I think it is better to add a button or command to remove it.

**Comment by Schaka** [comment]
That should not happen. It should only appear when clicking on a frame in the trackerframe. I need to doublecheck that, I guess.

**Comment by ayrb13** [comment]
I mean that i can't remove the arrow. Is there any way to remove it?

**Comment by AeroScripts** [comment]
Yeah it shouldn't be happening on shift+click, as far as being able to remove it, ill make quick a change so when you double-click in the tracker it hides it if it's already shown.

**Comment by AeroScripts** [comment]
I added a way to hide the arrow (double-click in the tracker again,) it's in v1.0o on the release page.

**Comment by valmarkuristik** [comment]
Once I activate the arrow, it's also spamming my general tab with numbers, like
0:0
2:9
1:2
etc.

It seems to happen when I either turn my character or move.

**Comment by Schaka** [comment]
Please update your version. The debugging log is not in the latest release.
