### ISSUE TITLE
[Suggestion] Share status to chat

### ISSUE THREAD

**Issue by Mkmk93** [AeroScripts/QuestieDev#461]
Make on optional option to share quest status changes (killed 1/6 or something) or completed quest xy in group chat automatically.

Maybe even share that information visible in questie between party members that have questie too?

**Comment by Dyaxler** [comment]
You can manually share by CTRL + Clicking the quest while your chat window is open (ready to accept text). 

To get it to automatically update your party/guild could be done but unless someone else is interested in writing the code - sorry but my job has kept me pretty busy lately. Sorry for being absent...

**Comment by Muehe** [comment]
As explained in detail in #469, quest status sharing can be achieved by using EQL3.

@Mkmk93 If you still think Questie should support this feature natively, feel free to re-open this issue!
