### ISSUE TITLE
Crash occasionally after releasing the mouse button when dragging the quest tracker

### ISSUE THREAD

**Issue by thetup** [AeroScripts/QuestieDev#468]
Fresh install with this being the only Add-on added to the game.

Last error message:

> ERROR <span>#</span>132 (0x85100084) Fatal Exception
> Program: C:\Program Files (x86)\World of Warcraft\WoW.exe
> Exception: 0xC0000005 (ACCESS_VIOLATION) at 0023:007A2452

> The instruction at "0x007A2452" referenced memory at "0x0E79FFE8".
> The memory could not be "read".

**Comment by Muehe** [comment]
Which version of Questie were you using?

**Comment by Dyaxler** [comment]
A work around for "fresh installs" is to either reload your UI or log out and back in before moving the tracker or quest arrow. This will create and save a Saved Variables file for those screen coordinates to be saved to. In rare cases the Blizzard Function we're using to move the frame can't read or write to memory.

There are other add-ons that are plagued by the same issue.
