### ISSUE TITLE
Quest links not appearing as links

### ISSUE THREAD

**Issue by Malevola** [AeroScripts/QuestieDev#469]
When shift-clicking quests in the quest log into chat, the name of the quest appears in the chat window with brackets around it (e.g., [Quest Name]), but the text is not a clickable link.

Installed:
World of Warcraft ##Version: 1.12.1 (5875)
Questie ##Version: 3.69
EQL3 ## Version: 3.6.1.11200
Ace Library r17998 

Troubleshooting
1. No other addons installed.
2. New WTF folder.
3. Deleted my "modified" version of Questie which used a reference to the Ace library I had separately installed, downloaded your version of Questie 3.69, disabled the separate Ace library so that only EQL3 and the fresh install of Questie were enabled.

At this point, I'm not certain what else I need to get this working. I couldn't find any reference to this issue from either the [Issues on GitHub](https://github.com/AeroScripts/QuestieDev/issues) nor the [Elysium Forum](https://forum.elysium-project.org/topic/23008-addon-questie-~-a-vanilla-quest-helper/)

**Comment by Dyaxler** [comment]
Where are you trying to get this "quest link" to show up? In a whisper? Battlegrounds chat? Guild / Party chat? Are you using PRAT, WIM or some other addon that changes the way Chat is displayed?

**Comment by Malevola** [comment]
It was in /w /p and /s. None of them worked. 

Unfortunately, after loading all of my addons, it magically started working, but I can't say why. If I only load EQL3 and Questie, I still can't link quests. When I discovered the issue, I had a clean WTF folder and no other addons had been installed. 

Current Addons Installed:
!Libs (consolidated Ace2 libraries)
!Questie (with included Ace2 libraries in place)
_LazyPig
AutoDecline
aux_merchant_prices
aux-addon
Bagnon
Bagnon_Core
Bagnon_Forever
Bagnon_Options
CECB_Options
CEnemyCastBar
CharactersViewer
ChatHighlight
ChatSuey
ChatSuey-ChannelLinks
ChatSuey-ItemLinkHover
ChatSuey-MarkdownLinks
ChatSuey-Mentions
ChatSuey-MiniChannels
ChatSuey-PlayerLinks
ChatSuey-WebLinks
Clean_Up_GUI
ColoredWhispers
ColoredWhoClasses
crafty
Decursive
DefendYourself
ElkBuffBar
EQL3
FishingBuddy
FlightMap
GFW_AutoCraft
GFW_ShoppingList
Informant
LunaUnitFrames
MobInfo2
myBindings2
Outfitter
pfQuest
pfUI
Postal
ReagentData
Recap
RecipeBook
RecipeRadar
ShaguCopy
ShaguInventory
SmartBuff
SpamThrottle
SuperMacro
TalentSafe
TNE_RareTrackerCore
TNE_RareTrackerMap
TradesBar
TrinketMenu
WeaponRebuff

**Comment by Malevola** [comment]
I just tested it out of curiosity with just pfQuest and EQL3 installed. Quest linking now works, so Questie doesn't have anything to do with why quest linking is now functional, but it is supposed to have that capability, am I correct?

**Comment by Muehe** [comment]
Questie only produces Quest "Links", which show your current progression of the quest (you as in the person reading the link, not the person sending the link). However Questie's method gets superseded by pfQuest, showing the Objective and Description texts and the level of a quest. So when you `Shift+Click` a quest, the addon actually doing something with your collection of addons is pfQuest.

The `Ctrl+Click` text with the quest progress is provided by EQL 3 and is there even without pfQuest or Questie activated. The only thing they do is overwrite EQL's `Shift+Click` to produce a link instead of plain text.

**Comment by Dyaxler** [comment]
Questie has no dependencies for linking quests in chat. It works for me with only Questie enabled. If this is a brand new install and you were trying it when you first logged in then chat linking might not work until you reload your UI or log out and back in but I fail to see why you'd need to do that. I'm only throwing out stuff you can try.

This is quite literally the entire function for linking quests in chat. It doesn't rely on quests in the log to parse the quest description. It looks in it's own database so if someone links a quest you aren't on... Questie can still show you the quest description. It's possible that the quest you were trying to link wasn't found in the database or it was parsed incorrectly. I'm pretty sure our 'string.find' REGEX is pretty solid. If someone comes up with a better one please let us know.

```
local HookSetItemRef = SetItemRef;
function SetItemRef(link, text, button)
    if ItemRefTooltip:IsVisible() then
        ItemRefTooltip:Hide();
    else
        isQuest, _, _ = string.find(link, "quest:(%d+):.*");
        if isQuest then
            _, _, QuestTitle = string.find(text, ".*|h%[(.*)%]|h.*");
            local questTitle = tostring(QuestTitle);
            if questTitle then
                ShowUIPanel(ItemRefTooltip);
                ItemRefTooltip:SetOwner(UIParent, "ANCHOR_PRESERVE");
                ItemRefTooltip:AddLine(questTitle);
                local questHash = Questie:getQuestHash(questTitle);
                questOb = nil;
                local QuestName = QuestieHashMap[questHash].name;
                if QuestName == questTitle then
                    local index = 0;
                    for k,v in pairs(QuestieLevLookup[QuestName]) do
                        index = index + 1;
                        if (index == 1) and (v[2] == questHash) and (k ~= "") then
                            questOb = k;
                        elseif (index > 0) and(v[2] == questHash) and (k ~= "") then
                            questOb = k;
                        elseif (index == 1) and (v[2] ~= questHash) and (k ~= "") then
                            questOb = k;
                        end
                    end
                    ItemRefTooltip:AddLine("Started by: |cFFa6a6a6"..QuestieHashMap[questHash].startedBy.."|r",1,1,1);
                    if questOb ~= nil then
                        ItemRefTooltip:AddLine("|cffffffff"..questOb.."|r",1,1,1,true);
                    else
                        ItemRefTooltip:AddLine("Quest *Objective* not found in Questie Database!", 1, .8, .8);
                        ItemRefTooltip:AddLine("Please file a bug report on our GitHub portal:)", 1, .8, .8);
                        ItemRefTooltip:AddLine("https://github.com/AeroScripts/QuestieDev/issues", 1, .8, .8);
                    end
                    local _, _, questLevel = string.find(QuestieHashMap[questHash].questLevel, "(%d+)");
                    if questLevel ~= 0 and questLevel ~= "0" then
                        local color = GetDifficultyColor(questLevel);
                        ItemRefTooltip:AddLine("Quest Level " ..QuestieHashMap[questHash].questLevel, color.r, color.g, color.b);
                    end
                    ItemRefTooltip:Show();
                else
                    ShowUIPanel(ItemRefTooltip);
                    ItemRefTooltip:SetOwner(UIParent, "ANCHOR_PRESERVE");
                    ItemRefTooltip:AddLine(questTitle, 1,1,0);
                    ItemRefTooltip:AddLine("Quest not found in Questie Database!", 1, .8, .8);
                    ItemRefTooltip:AddLine("Please file a bug report on our GitHub portal:)", 1, .8, .8);
                    ItemRefTooltip:AddLine("https://github.com/AeroScripts/QuestieDev/issues", 1, .8, .8);
                end
                ItemRefTooltip:Show();
            end
        else
            HookSetItemRef(link, text, button);
        end
    end
end
```

**Comment by Dyaxler** [comment]
Here is a screen shot...

![image](https://user-images.githubusercontent.com/17400948/33336817-00c8bf34-d426-11e7-8378-b33efba99117.png)

**Comment by Muehe** [comment]
Yeah, wasn't disputing that. My point was that pfQuest [hooks into the same method](https://github.com/shagu/pfQuest/blob/master/pfQuest.lua#L433-L513) by overwriting it, and due to its name it is loaded later, and therefore if you use both Questie and pfQuest, only the pfQuest chat links work.

Btw. good to see you back. :wave:

**Comment by Dyaxler** [comment]
I had this thread open and didn't refresh before posting my comment. I never saw your comment Muehe. LOL. Sorry man.

Yes. I'm back. Sort of. Work has been NUTS. A lot of high profile projects that's been all over the news stole most of my attention. That and this years racing season was filled with a LOT more track days. AND Blizzards announcement at Blizzcon just FIRED me right up! YES! Classic will officially be launched. It's about time is all I have to say. I'm super excited to learn what Blizzard has in store and I'm almost hesitant to do any more work with Questie. We have no idea which patch version / LUA version Blizzard will implement for Classic.

**Comment by Muehe** [comment]
@Malevola I am clsoing this issue, since it can be resolved by enabling EQL3 / disabling pfQuest.

If you want to be able to choose between the pfQuest chat links and the Questie chat links, the appropriate solution would be to add a config option to pfQuest, since its chat links are taking precedence over ours, so if you need that feature please create an issue there and I will see if I can resolve it.

Thanks for your report anyway! :+1:
