### ISSUE TITLE
Arrow and minimap icon discrepancies

### ISSUE THREAD

**Issue by valmarkuristik** [AeroScripts/QuestieDev#47]
Some quests have arrow pointing in a totally different direction with false distance showing, while icon on the minimap is right.
For example, "The Manor, Ravenholdt", the arrow is pointing well into WPL, while the map icon is in the right position. Are they using different databases for coordinates?

**Comment by Schaka** [comment]
You need to click on the quest in the tracker frame again. The arrow doesn't update to the closest coordinate properly yet. It only updates when you click it.  We are also going to rework the coordinate system and move it over to use Astrolabe entirely. That should fix all these issues and make it possible to have cross-map and cross-continent coordinates displaying properly, calculating distance properly etc.

**Comment by valmarkuristik** [comment]
Reclicking didn't help with at least this particular quest. Not even when I was standing right on top of the right coordinates just to check.
With all the latest fixes, everything's looking more and more awesome though. Sadly I'm nowhere near at home with lua myself to commit anything.

**Comment by AeroScripts** [comment]
It should defintiely be updating when you click a quest in the tracker again. Maybe there's something funky going on with the coordinates for "The Manor, Ravenholdt," you were in EPL right? I'm going to see if I can replicate the issue on the test server.

**Comment by valmarkuristik** [comment]
I was in Tarren Mill first, then checked in Alterac Mountains where it was
pointing at, passing Strahnbrad and then going into WPL.
I then went to the actual location, which also showed correctly on the
minimap, retracked it and it was still showing in the wrong direction, all
the way into WPL, while I was standing in Ravenholdt.

On Mon, Apr 13, 2015 at 1:51 AM, AeroScripts <notifications@github.com>
wrote:

> It should defintiely be updating when you click a quest in the tracker
> again. Maybe there's something funky going on with the coordinates for "The
> Manor, Ravenholdt," you were in EPL right? I'm going to see if I can
> replicate the issue on the test server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AeroScripts/QuestieDev/issues/47#issuecomment-92146609>
> .
>



-- 
Tervitades
Valmar Kuristik
ÕF SMARTKool
ISP 213
