### ISSUE TITLE
Some of AV quests crashes questie

### ISSUE THREAD

**Issue by elenmerbau** [AeroScripts/QuestieDev#473]
![error_message](https://i.imgur.com/oDok5g3.png)

**Comment by Muehe** [comment]
Seems you are using an older version of Questie, could you please test if this bug also happens when using the beta release? Also the exact names of the quests would be helpful in finding the issue (if it still exists).

**Comment by elenmerbau** [comment]
I was using 3.7.0b. Can't tell names tho.

**Comment by Dyaxler** [comment]
typeFunction isn't being set... my guess the database doesn't contain the necessary field so it's being set to nil and error'ing on line 110. We need to know the name of the quest its tripping over.

![image](https://user-images.githubusercontent.com/17400948/34217101-4d63cc86-e55f-11e7-8131-15d19aaba5b2.png)

**Comment by Muehe** [comment]
@elenmerbau Downloading the [master branch](https://github.com/AeroScripts/QuestieDev/archive/master.zip) and coyping the `!Questie` folder out of it and over the files in your WoW folder should fix this issue.

Thanks again for reporting :+1:

**Comment by elenmerbau** [comment]
Thanks, man. I will report back when AV week starts.

**Comment by elenmerbau** [comment]
Works fine, thanks again.

**Comment by Muehe** [comment]
Glad to hear it, thanks for reporting back!
