### ISSUE TITLE
Error on Light Leather for AQ War Effort - Darrowshire

### ISSUE THREAD

**Issue by tsheeley** [AeroScripts/QuestieDev#474]
When I'm tracking the Light Leather for the War Effort and mouse over the tracker, I get the error below. I tried turning off Tooltips in the options, but it still gives the error.

![image](https://user-images.githubusercontent.com/31299310/34072047-55709a12-e235-11e7-9210-00e573bd6f95.png)

I've got a GitDesktop clone directly into my Addons folder and then a symlink it to give the proper folder structure and pull 3.7 from that... so I should be using the current version.

**Comment by ZoeyZolotova** [comment]
Your commit message says you were unable to reproduce the error, but isn't it just a matter of a quest not found in the quest table? The quest "Light Leather for the War Effort" isn't in the quest table.

**Comment by Muehe** [comment]
I assumed it was quest 8511 (The Alliance Needs Light Leather!) and tested with that. The quest shows up in the tracker and there are even some notes, though I doubt the marked creatures actually drop light leather as loot...

**Comment by ZoeyZolotova** [comment]
Could be some servers have significantly different quest names, so we should make sure at least nothing completely breaks in those situations. Obviously we can't correctly handle quests with incorrect names, but we can try to handle errors a bit better.

**Comment by Muehe** [comment]
An error in theses cases shouldn't happen anymore, because the lookup function now returns `QuestieLevLookup[realName] or {}`, so if `QuestieLevLookup[realName] == nil` then an empty table is returned and used where the function is called as an argument of `pairs()` resulting in zero loops.
