### ISSUE TITLE
Quest giver "!" icon appearing as a drop...

### ISSUE THREAD

**Issue by Dyaxler** [AeroScripts/QuestieDev#477]
Example quest: JOB OPPORTUNITY: Culling the Competition

"!" appears along with the "sword" icon... it's happened a few times with other quests just not to this extreme. I'm sure bug is in the code someplace and not in the database.

Although it could be the "Key to Freedom" quest. Once I untrack everything the "!" remain and this is the quest the tooltip indicates.

![image](https://user-images.githubusercontent.com/17400948/34393287-35c399ec-eb06-11e7-94e9-a1884bc88097.png)

**Comment by Dyaxler** [comment]
Yeah... nm. That's by design. It just looks kind of messy with all "!" all over the place. :D

**Comment by ZoeyZolotova** [comment]
See #317 it happens whenever a creature related to an objective also starts a quest (whether by dropping an item or directly). ! and ? icons join together in one tooltip, and the objective icons join together into one tooltip too. But if they overlap, you can only read one of them.

Should we consider joining the two types of icon groups?

**Comment by Dyaxler** [comment]
(RE: "!" marked all over the zone) I remember that we chatted about this on Discord one night. I think it's best to keep it as it is unless we add a notes column to the World Map listing the possible quests you can obtain from drops and the mobs that drop the item that starts the quest. That is the only clean way I can think of to do it. It would get rid of the clutter off the world map and mini maps.

(RE: "!" overlapping quest objective icons) Is there a way we can filter out the "!" while those mobs exist as a Quest objective? I like your idea of tagging an extra tool tip line to remind players that this mob also drops a quest item that starts a quest.

I'm a bit nervous doing any more "new coding" to Questie without knowing Blizzards plans for Classic WoW. ;) We can make an educated guess but it would suck if they implemented/supported a newer version of LUA than what was originally available in 2004.
