### ISSUE TITLE
Other Fish To Fry Quest Error

### ISSUE THREAD

**Issue by Dioxane** [AeroScripts/QuestieDev#479]
When doing the Horde quest Other Fish to Fry in Desolace ( https://db.vanillagaming.org/?quest=6143 )
any time I moused over the quest in the quest tracker, or one of the mobs from the quest, would get this error. "Interface/AddOns/!Questie/Modules/QuestieNotes.lua:369: attempt to index local `questInfo' (a nil value)

**Comment by Muehe** [comment]
Can't test right now, but this variable isn't called in that line anymore (its called in line 397 instead) which might indicate you are using an outdated version. I published a new release yesterday, you can get it here: https://github.com/AeroScripts/QuestieDev/releases

If updating doesn't solve your problem, I'll have a look at this later. Please check your Questie version.

**Comment by Muehe** [comment]
Just tested this on version 3.7.0 and everything works fine. Closed due to being invalid. Please update your Questie version.
