### ISSUE TITLE
Dungeon Quests Filter - GUI Toggle

### ISSUE THREAD

**Issue by Dyaxler** [AeroScripts/QuestieDev#480]
*Idea for future feature*

Build a toggle in the GUI that will show the player where to obtain (or start a quest chain to obtain) quests for specific Dungeons. The toggle will include a drop down list of available dungeons.

Obviously this will require the new Database so we can look for specific fields.

**Comment by BreakBB** [comment]
In the journey system one can go at "Quests by Zone" and select "Dungeons" to see a list of dungeon quests. After a quick glance there seem to be an issue with showing all the quests started/completed in a dungeon (e.g. for Ragefire Chasm just one quest is listed).
