### ISSUE TITLE
"Toggle Questie" button over "Instances" in MetaMap

### ISSUE THREAD

**Issue by inscaped** [AeroScripts/QuestieDev#482]
![scrn](https://user-images.githubusercontent.com/30598442/34491139-53f1b998-eff3-11e7-9311-d099530d5624.jpg)
Using last versions of both addons, can't find any solution. Any help?

**Comment by Dyaxler** [comment]
Looks like MetaMap is magically screwing with the WorldMap. Elements under it are coming through. Look at the bottom edge of the map. I can see some of your UI Elements.

We'll add some code that will detect MetaMap and push the button further left...

**Comment by Dyaxler** [comment]
Hows this? :)

![image](https://user-images.githubusercontent.com/17400948/34495713-42e03834-efab-11e7-86d4-0b987c83287b.png)

**Comment by Dyaxler** [comment]
Fixed this for Cartographer too...
![image](https://user-images.githubusercontent.com/17400948/34495963-5bb36e16-efac-11e7-8e92-a1ca0a4034d7.png)

**Comment by Dyaxler** [comment]
Default UI position...

![image](https://user-images.githubusercontent.com/17400948/34496012-9f94ee48-efac-11e7-8836-3c87cd0a1ad9.png)

**Comment by inscaped** [comment]
Looks pretty neat, bruh, thanks!
