### ISSUE TITLE
Enhancement Request: Only display events like Darkmoon Faire and seasonal events when they are active

### ISSUE THREAD

**Issue by tsheeley** [AeroScripts/QuestieDev#483]
The screenshot below was just taken in Goldshire on Darrowshire Realm... the Darkmoon Faire isn't active right now. Is it possible to only have those type of quests showing when the event is active?

![image](https://user-images.githubusercontent.com/31299310/34635969-2b740038-f24c-11e7-8b8a-564116b7be58.png)

**Comment by Dyaxler** [comment]
We're aware of this issue. It's one of the many reasons we've talked about needing a new Database. :(

Currently there are no fields to distinguish some of the Holiday quests with actual quests. Some of the profession quests have a designation field so we're able to toggle those.

**Comment by FrostShock** [comment]
Or to even add an option to completely disable showing all the event-related quests. It's quite annoying to see the exclamation marks for all those Lunar Festival quests, in every zone. And wasting a lot of player time. I guess a list of such quests can fix it. Thanks

**Comment by Muehe** [comment]
Well this issue will be a year old next week, so don't hold your breath. Like Dyaxler said we would need new data. If you want to make the changes yourself by adding a list of quests, feel free to create a Pull Request.

**Comment by Muehe** [comment]
P.S.:

https://github.com/cmangos/issues/wiki/Quest_template#zoneorsort  
https://github.com/cmangos/issues/wiki/QuestSort.dbc

**Comment by BreakBB** [comment]
Seasonal events are already handled. Darkmoon Faire is not.

**Comment by BreakBB** [comment]
This has been fixed with v5.7.0
