### ISSUE TITLE
'hideobjectives' gone

### ISSUE THREAD

**Issue by kev41** [AeroScripts/QuestieDev#484]
is nowadays 'showobjectives' giving you 2 options to toggle;
show objects when tracking the quest or always show objectives for all quests
all these but the one that I used: never show objectives
talked with aero about this and he thought it would not be intentional but he suggested me to make this here so other devs can see it. 
would really appreciate the old option back or make the current command to have 3 options i:e never show objectives.

thankful for all the work, keep it up

**Comment by Dyaxler** [comment]
Just so I'm clear... you want to keep everything active but NEVER show any quest objectives under any circumstance?

There was a Slash command for that at one point in a really old version but when the GUI was finally added this option was removed.

**Comment by kev41** [comment]
@Dyaxler 
yeah the old command was 'hideobjectives' and now it's 'showobjectives' and the feature that 'hideobjectives' had is gone, would like it back - maybe as a 3rd option in 'showobjectives' or something?

**Comment by Dyaxler** [comment]
I'll look into that sure.

**Comment by Dyaxler** [comment]
OK... now I remember. I reviewed all the old code and the slash command for:

`/questie hideobjectives`

...simply duplicated what the Toggle Questie button on the World Map did. This hid everything including quest npc's and objectives. At one point the button was either covered by some other addon or it didn't show up for some reason for some folks so I created a slash command "backup" to resolve those issues. There was never a single option to only hide Quest Objectives while leaving Quest NPC's active.

There is an option to toggle Quest Objectives for ONLY quests that are actively tracked. This reduces world map and mini map clutter significantly.

**Comment by kev41** [comment]
@dyxaler

sorry if im being annoyong about thos but ’/questie hideobjectives’ only hid the objectives not the quest npcs for pickup/deliver and thats exactly what i used the command for, show quests but not objectives.

thanks in advance

**Comment by Dyaxler** [comment]
Yep you're right! Sorry. I was only looking at the slash command code and saw that the only thing it was doing was triggering the Quest Toggle button code. I forgot that I was also setting a flag in the notes stack which made it not re-paint the Objectives... only the NPC icons.

At the very least I can re-add a slash command. We can make it a GUI toggle if enough folks want to use it.

**Comment by Dyaxler** [comment]
This [change ](https://github.com/AeroScripts/QuestieDev/commit/ee4e60999549c1e466fd59d13d01e854344e00ff)will officially be in the next release. As always you can use it now by cloning the repro or downloading the whole repro as a ZIP file and install Questie manually.

**Comment by kev41** [comment]
You are best.
Thanks alot for so fast work!
