### ISSUE TITLE
Missing Quest Markers

### ISSUE THREAD

**Issue by Hiethen** [AeroScripts/QuestieDev#485]
The following two quest don't show exclamation markers on the mini map.

http://db.vanillagaming.org/?quest=684
http://db.vanillagaming.org/?quest=685

**Comment by Dyaxler** [comment]
Yes. Some of the "Wanted Posters" or "Wanted Boards" don't show up on the minimap or worldmap. Questies database isn't 100% accurate and has some stale and Burning Crusade data in it still. Making a new Database is one of the first things we'll probably do once Blizzard releases more details on Classic WoW - LUA version, available API's etc - Addon related information.

In the mean time well continue fixing small bugs. I'm sure one of us will snag this issue and fix the quests...

Thanks for the report!
