### ISSUE TITLE
Quest tracker details over portrait...can I move this?

### ISSUE THREAD

**Issue by ericmt87** [AeroScripts/QuestieDev#486]
Hey! So here's a picture of what my quest tracker looks like. It stays over my portrait in the top left corner of my screen. I am wondering how I can get this over to the right where the normal quest tracking default from wow goes? Here's a picture...playing in windowed mode. Thanks!

![screenshot](https://i.gyazo.com/86c9c29becb935d8955de4ce7aeb9599.jpg)

**Comment by Muehe** [comment]
Use `Ctrl+Shift+Click` to drag it around [(see Readme)](https://github.com/AeroScripts/QuestieDev/wiki/FAQ&Readme#faq).
