### ISSUE TITLE
Weird interaction with Pets?

### ISSUE THREAD

**Issue by Sparh4wk** [AeroScripts/QuestieDev#49]
Hi, dont know if this is intended or not, but when I hover mouse over someones pet I can see something weird.. it seems like some tooltip with his quests?
![yxgfbw8](https://cloud.githubusercontent.com/assets/7014826/7155775/9bd4222e-e361-11e4-8ea4-7ba3bb7aed1d.png)

**Comment by AeroScripts** [comment]
Haven't seen that one before... I'll take a look, it's possible it's related to the string comparison the objective starts with "scar" and the pet name is also "scar"

**Comment by ayrb13** [comment]
It is just a coincidence

**Comment by Sparh4wk** [comment]
nope its not.. another one 
![lv4oxak](https://cloud.githubusercontent.com/assets/7014826/7215176/ef01c72e-e5ca-11e4-8267-d8ad221bb30b.png)

**Comment by Schaka** [comment]
Um, that's clearly due to how string search patterns work and because the pet's name is broken. That's literally "just a coincidence".

**Comment by Sparh4wk** [comment]
ok then :)

**Comment by Schaka** [comment]
An issue with string patterns that should be fixed now, but can NEVER be fully fixed.
