### ISSUE TITLE
Questie is moving my traked quests

### ISSUE THREAD

**Issue by Mr-Phantom** [AeroScripts/QuestieDev#491]
Questie is putting my tracked quests list in the upper right corner of my ui which is right over my portrait... i dont know how to move either of these.

**Comment by Dyaxler** [comment]
ctrl+shift+leftclick = drag

**Comment by Mr-Phantom** [comment]
You are awesome! thanks for the quick reply!

**Comment by Dyaxler** [comment]
Welcome!
