### ISSUE TITLE
Tooltip information not showing on pfUI

### ISSUE THREAD

**Issue by Svahnen** [AeroScripts/QuestieDev#492]
Tooltip information is not showing when using pfUI, at first i thought this was a bug in pfUI, but when testing a older version of Questie (3.69), the bug was not present.
Related issue and more explanation of how to reproduce the bug at pfUI issue https://github.com/shagu/pfUI/issues/775

**Comment by Muehe** [comment]
Tooltips are working fine with just Questie and EQL3, so this is likely a problem on the pfUI side. If the issue on their repository gets closed stating the problem is in our code feel free to re-open this issue.
