### ISSUE TITLE
No info in tooltip

### ISSUE THREAD

**Issue by hurryupweredreaming** [AeroScripts/QuestieDev#501]
Hello. I have installed tinytip + questie + mobinfo2 and questie tooltip setting is enabled. But anyway i can't see quest info in tooltip :(
![image](https://user-images.githubusercontent.com/7894442/39195699-08078e9c-47e9-11e8-9855-f8adae3bac00.png)

**Comment by Dyaxler** [comment]
Not sure which ToolTip addon that is but try turning it off. Does the Questie info appear?

Questie adds to the tool tip, it doesn't over write it. The addon in the screen shot looks completely custom and might be replacing the game tool tip thus not allowing quest info to appear.

**Comment by Optics82** [comment]
Having the same problem.  I just updated to 3.7.  Also using Tinytip, TinyTipOptions,  and TinyTipExtras.  Prior to updating, my tooltip would show the quests progress.   After updating it's gone (with the option enabled).  In TinyTip options there is a "show other addons info" section and turning that on I am able to get the objectives in a tooltip.. but not my tooltip.   instead I get 2 tooltips, one with loads of info and then my normal tooltip.  But the normal tooltip is now in the default blizzard location and not on cursor as I have it set to.   The curser tooltip options now has the new window with the spammy details.  I've never had to enable the "show other addon info" option before either.  Just tested it after not getting any questie objectives in my tooltips to see if it helped.  It does.. but not really.


**How it should look (but missing the quest progress info)**
![](https://i.gyazo.com/a7c0a0ff8e7223547dcd192b282511cc.jpg)

**Options and the double tooltip if I enable other addon info (not my cursor tooltip is now at the bottom right as default blizzard location)**
![](https://i.gyazo.com/74c68fb3c87dfe54d4dbaa5279bdc718.jpg)


I did try disabling my TinyTip and yes Questie progress showed up in the default blizzard tooltip, but again in the lower right part of the screen.

**Comment by Dyaxler** [comment]
Weird because I use mobinfo2 and tinytip too...

**Comment by Optics82** [comment]
What version of TinyTip do you use? Perhaps I have a faulty one and can try another version.

**Comment by Optics82** [comment]
I just downgraded to 3.69 and everything is fine and back to normal.   So something changed with the newest release.

**Comment by Muehe** [comment]
Should be fixed now. Please re-open this issue or create a new one if you continue having problems.
