### ISSUE TITLE
Long quest objective names could be shown as multi-line on the tracker

### ISSUE THREAD

**Issue by alibayindir** [AeroScripts/QuestieDev#502]
ex. Alliance quest in Darkshore (id#4811)
The Red Crystal
"Locate the large, red crystal on Darkshore's eastern mountain range"

**Comment by Dyaxler** [comment]
Hmmm... interesting. Well the track does have a "hard cap" on width but for the most part it auto adjusts. Would you rather it be super wide or truncate the Quest Objective?

**Comment by alibayindir** [comment]
Tracker became super wide.
It would be good if the tracker text lines are word-wrapped to multiple
lines by an adjustable width set in the options menu.

2018-05-22 22:11 GMT+03:00 Dyaxler <notifications@github.com>:

**Comment by BreakBB** [comment]
@AeroScripts Keep this in mind when porting the tracker to Classic or close this if it already in included.

**Comment by Muehe** [comment]
Tracked elsewhere for 1.13

**Comment by minetrinitite** [comment]
Looks like having the same issue. Tracker became very wide because of the long objective. 
Version 6.0.4
Screenshot https://imgur.com/a/K2NMnuY

**Comment by drejjmit** [comment]
Unlock the tracker and you can make it the width you want in the lower right.
