### ISSUE TITLE
Lua error on log on

### ISSUE THREAD

**Issue by davedehaan** [AeroScripts/QuestieDev#503]
Only happens on my holy priest.

https://imgur.com/a/0IJLsxl

Ping me on discord if you need more info

Error went away after dropping Shadow Guard quest, fwiw

**Comment by Dyaxler** [comment]
You must be running an older version... line 1092 in QuestieNotes.lua is:

`local quests = nil;`

However, there is a reference to questA in the code but it's first appearance isn't until line 1401 and it's in our Clustering code. Either update your Questie or turn off Clustering. It might be trying to cluster a quest objective that's still in your cache but not in your quest log.
