### ISSUE TITLE
Questie interferes with "Click to Move"

### ISSUE THREAD

**Issue by eniac86** [AeroScripts/QuestieDev#504]
Questi (Commits Apr 24, 2018 ) interferes with "Click to Move" somehow.
When putting a spot to move to on the map by right clicking the character will start to move there, but the spot will disapear and the char will stop moving. Sometimes the CTM spot is gone immediately sometimes it takes a second or two, but i narrowed it down to questie causing it.

**Comment by eniac86** [comment]
Might be because of the quest "Root Samples" ( https://vanilla-twinhead.twinstar.cz/?quest=866 ).
The quest spams the map and minimap with cogwheel symbols, to the point that the client starts laging.

**Comment by BreakBB** [comment]
Recent versions shouldn't have these issues
