### ISSUE TITLE
Attempt to perform arithmetic on a nil value.

### ISSUE THREAD

**Issue by Witnessthis** [AeroScripts/QuestieDev#506]
I'm getting this error occasionally.

As seen in the chat, I just accepted "Hamuul Runetotem" and "Mura Runetotem". I'm not sure which of these triggered the error or if it's tied to a specific quest at all.

The quests can be found on NPC "Tonga Runetotem" in "The Crossroads".

![questiebugreport](https://user-images.githubusercontent.com/12346326/41500059-664bd046-718b-11e8-8b58-9e1cfb413754.JPG)

**Comment by wbb1977** [comment]
Had the same error today (current master branch). It appeared when I changed / selected some quests to track (using EQL3). I could get it to pop two times in a row by randomly changing quests to track and untrack. I was not able to reliable reproduce the error though.


![questi](https://user-images.githubusercontent.com/6225161/51002212-df468680-1532-11e9-90dc-01c70f53c8a5.jpg)

**Comment by BreakBB** [comment]
@AeroScripts Keep this in mind as well when porting the tracker to Classic
