### ISSUE TITLE
WoW Crashing rarely when dragging questie tracked quests

### ISSUE THREAD

**Issue by Sabre142** [AeroScripts/QuestieDev#509]

**Comment by crackola** [comment]
Likewise. Tried two different toons and also tried a complete re-install. See attached for error.

![Capture](https://user-images.githubusercontent.com/49603791/56088418-32cbb780-5e35-11e9-80c4-1c258ddfe8b7.PNG)

**Comment by crackola** [comment]
It's the sole addon I'm using. Used in the undead noob zone. It appears to
occur when putting it far to the right... maybe with a portion off-screen?

Sometimes it works. But the other issue is with the quest text. If it's
very long, it will push questie further into the screen towards the middle,
essentially increasing the right margin. Of course that them disables any
interaction with whatever's covered up by it.

Thanks

**Comment by crackola** [comment]
Here's a ss of the margin issue.

![WoWScrnShot_042419_011723](https://user-images.githubusercontent.com/49603791/56684516-c8ace100-6684-11e9-84c6-91dc39622f6a.png)

**Comment by BreakBB** [comment]
Margin issue is related to #502 Closing this for now and will reopen if the new tracker will have the same issue
