### ISSUE TITLE
Move everything to Astrolabe and 'streamline' the code

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#51]
This has been mentioned in several places but I figured I'd create an issue for it.

We need to move everything to Astrolabe.

**Comment by Logonz** [comment]
First hurdle done, QuestieNotes.lua has been added.

**Comment by Sparh4wk** [comment]
update is great.. already tryed it.. notes hides etc.. still first item doesnt count.. sometimes even second.
btw with latest version from git Ive got some error.. just wanted to report it.
![rzs0goj](https://cloud.githubusercontent.com/assets/7014826/7196234/2bd0beba-e4ce-11e4-85cf-5ddba982cdb7.png)

**Comment by Logonz** [comment]
Sparh4wk the reason we really want to do this change is because it will probably fix most of the problems currently as we will rewrite the logic for just the things you have problems with.

**Comment by Sparh4wk** [comment]
Logonz I know, you are doing great job.. if u dont need my feedback for non official released version, Im ok with it.. Ill uset it anyway, cause even know with some bugs with map etc, its still better then version 1o :)

**Comment by Logonz** [comment]
Go ahead man! It's impossible for us to test all this, continue to write issue posts etc, just wanted to explain the situation no to think we are ignoring you! :)

**Comment by Sparh4wk** [comment]
np, I know you dont have time to answer all of my posts, I have your git linked to my addons, so Im getting new version right after you commit any changes :) Im glad that I can use it, test it and maybe find some bugs etc...I used shagu quest but its clumsy and not that good as questie, even with bugs that questie have atm.. btw gj with fixing map zooming bug :)

**Comment by Logonz** [comment]
Yeah, that map zooming bug is super annoying...

**Comment by Sparh4wk** [comment]
another error 
![yzfmukx](https://cloud.githubusercontent.com/assets/7014826/7209997/2aadf9c8-e54e-11e4-9003-dd1b0257566f.png)

if there is some kind of debug file, I can send you it.. but dunno if there is one

**Comment by Logonz** [comment]
I've gotten that myself also but only once from what i can remember, hard bug to fix... you should really put in the quest etc when i happened etc.

**Comment by Logonz** [comment]
1.1 is very close, closing to clean up the tracker
