### ISSUE TITLE
level filter seems not work

### ISSUE THREAD

**Issue by fantasy4u** [AeroScripts/QuestieDev#510]
I try to set filter hope not showing the quest that higher than my player. However, it's not working, it's show all of the quest on mini map and map. Even it already finish.

**Comment by Muehe** [comment]
If quests you already finished reappear after restarting WoW, make sure you do not have WoW installed in `C:\Program Files` or `C:\Program Files (x86)`.

The level filter can be set over the settings GUI which can be opened with the minimap button. There you have two sliders for how much levels above/below your level you want to see quests.
