### ISSUE TITLE
jerkiness

### ISSUE THREAD

**Issue by mipstien** [AeroScripts/QuestieDev#52]
I have downloaded the newest released 1.0o and had to revert to 1.0k because i am having a lot of jerkiness almost like screen tearing. it doesn't seem to be affecting actual fps but because it is so twitchy i can not tell if it is actually affecting fps. as soon as i removed the o version it stopped.
i am using a dell venue 8 windows 8.1 pro. quad core atom with 2gb memory and 64gb hdd. intel hd graphics card. nothing crazy powerful but it runs wow just fine with plenty of addons. i have ran my install with just the o download and no other addons and it does the same thing.

**Comment by Logonz** [comment]
First make sure to turn off Vsync and Triple buffering with dualcore / quadcore.
If the problem still persist please come back and i'll look into it more!

**Comment by mipstien** [comment]
I have done this and it doesn't fix the issue.

**Comment by Schaka** [comment]
I'm afraid you will have to wait for the next, big update. Lots of changes will have been made by then (including performance improvements). While I would not encourage this, you can download the latest master branch and see if it already does the trick for you. But be careful, it's under heavy development.

**Comment by Logonz** [comment]
1.1 is very close, closing to clean up the tracker
Please open up again if the new version gives you performance problems!
