### ISSUE TITLE
QuestieNotes.lua:110

### ISSUE THREAD

**Issue by Jpxg** [AeroScripts/QuestieDev#525]
Hey there, i'm having an error making the addon do complete random tracking of quests.

The only lua error i have is : 

Interface/AddOns/!Questie/Modules/QuestieNotes.lua:110: attempt to call local 'typeFundtion' (a nil value)

Using : 
-Questie last version
-EQL3
-Cartographer

Same error occuring without carto or EQL3

Happends only on one char.

Thanks for your help.

**Comment by Muehe** [comment]
I assume by latest version you mean the 3.7.0 release? If so please try the current state of the master branch: https://github.com/AeroScripts/QuestieDev/archive/master.zip

I run the same addons and do not have this issue. If you continue having problems with the version I linked please provide a list of your quests so I can investigate.
