### ISSUE TITLE
Game freezes when Questie enabled

### ISSUE THREAD

**Issue by wourn** [AeroScripts/QuestieDev#526]
Hi.
I'm having a problem with Questie.
Every times i level a new toon, when I get in the range of lvl 20-25 (horde side, if that matters) I start to get freezes. They occur randomly, when I'm fighting, running, on a Zep, even if standing still doing nothing. 
The freezes last 1-2 seconds.
If I reach lvl 20-25 and get the freezes, if I start a new character, I will not have freezes on that character untill I reach that level range.
Scriptmemory is 1024MB
Questie v3.7.0
If I disable Questie, the freezing is gone
Any solutions?

**Comment by Muehe** [comment]
This is a common problem with quests that put too many notes on the map (cloth drops for example). Workaround is to disable automatic tracking, which means only quests that are manually tracked in the quest log will get shown on the map.

You may also want to try setting memory limit to zero (unlimited).

See #258

**Comment by wourn** [comment]
I know that, I remember especially a Herbalism quest, but that only game me fps drops.
This is straight up freezes, even if I have no quests active.

I can try to set memory limit to zero though

**Comment by Muehe** [comment]
Hmm, this sounds weird. You could try making a backup of your `WTF` directory and then using `/questie NUKE` on an affected character.

**Comment by wourn** [comment]
Even after setting memory to 0, and using /questie NUKE, I still get freezes. 
I have no idea whats causing it, but disabling Questie gets rid of it.
Any other ideas?

I have tried on 3 different computers, and having the issue on all 3. (one of the computers are brand New)

Note that I have copied over Wow Vanilla and Questie. Maybe I should download and install it again

**Comment by wourn** [comment]
I fixed the issue.
If I had actually read your guide I would have been fine.
The issue was that WoW was installed under c:\programfiles\...
After I moved it to another folder, the freezing stopped.

Thank you for looking into this issue anyway

**Comment by Muehe** [comment]
Yeah that explains a lot. I keep wanting to make an issue template that points people to re-reading the FAQ before posting a report.

 Glad your problem is solved.
