### ISSUE TITLE
Arrow is inaccurate

### ISSUE THREAD

**Issue by wodim** [AeroScripts/QuestieDev#527]
Here you can see me looking directly at my objective but the arrow is a bit to the right:

![image](https://user-images.githubusercontent.com/1001553/50543106-d6b68d80-0bcd-11e9-9ce8-ace610fad7b7.png)

But what happens if I go where the arrow points?

![arrowz](https://user-images.githubusercontent.com/1001553/50543133-b9ce8a00-0bce-11e9-9caa-c0b37f684219.gif)

I feel a bit tricked.

**Comment by Levitanious** [comment]
What, you didn't know? Tauren are _MASSIVE_.

**Comment by Levitanious** [comment]
...not to mention general spacetime curvature around NPCs~
