### ISSUE TITLE
Modules/QuestieTracker.lua:225 attempt to index local 'quest' (a nil value)

### ISSUE THREAD

**Issue by wbb1977** [AeroScripts/QuestieDev#528]
Hello

I currently use it on the WoW Vanilla "Light's Hope" server and randomly the following error message appears:

"Modules/QuestieTracker.lua:225 attempt to index local 'quest' (a nil value)"

I am using the current Questie master branch together with EQL3 13.6.2

Thanks for your great work!!

-wbb

**Comment by Muehe** [comment]
Thanks for the report.

Could you please send a list of quests you were on when this error happened? Something like this is usually triggered by a specific quest. I could just introduce another nil guard, but I'd rather know why this error happens first.

**Comment by wbb1977** [comment]
Unfortunately, I do not have a complete list of my quest log during the time the error appeared, so I am not sure if it possible to back track the error to the quest causing the error. Luckily, I recorded the gameplay when the error appeared. I usually track all quests for the zone I am in. In the video I tracked all quests I worked on in Desolace. I uploaded the relevant part to YouTube, maybe it helps: https://youtu.be/4loUMKa9jvA

Thank you for the background info and for looking into the matter. Next time if it happens, I capture my complete quest log for future investigations.

**Comment by wbb1977** [comment]
I think you right, I can follow that. Pretty sharp eyes you have. Quest was still active but not on the Questi tracker list.

**Comment by Muehe** [comment]
@ZoeyZolotova Was thinking along the same line. IIRC the quest finish event is not being used but rather the click-event of the buttons in the quest log UI. This was due to a problem with quest events differing between different server cores I think.

By the way, nice to see you alive and hopefully well. :wave:

**Comment by BreakBB** [comment]
Could this still be an issue?
