### ISSUE TITLE
With the addition of Astrolabe the minimap resets the worldmap.

### ISSUE THREAD

**Issue by Logonz** [AeroScripts/QuestieDev#53]
With the addition of Astrolabe the minimap resets the worldmap.

**Comment by AeroScripts** [comment]
This was happening before with our code that was used to check the current zone id, because it called SetMapToCurrentZone(), and that reset the map. It could be related.

**Comment by Logonz** [comment]
It's in the function function Astrolabe:GetCurrentPlayerPosition() in astrolabe.lua, didn't want to fix it before i fully understand how Astrolabe uses this function

**Comment by Logonz** [comment]
Fixed with the latest commit, uses the old value before the map was opened.
