### ISSUE TITLE
Hide Objectives option

### ISSUE THREAD

**Issue by Malevola** [AeroScripts/QuestieDev#534]
The toggle for "showobjectives" doesn't do what I'd like it to do, which is to remove the objectives for all quests (tracked or not) from the minimap the way "/questie hideobjectives" used to do. Is there some way to accomplish that with the latest version?

**Comment by Malevola** [comment]
After reviewing the issues, there was apparently a version in august that had what i'm looking for: a button to turn the minimap icons for the objectives off without turning off the quest giver icons. What happened to that button?

**Comment by Muehe** [comment]
Not exactly sure which issue/version you are talking about, but the releases tab shows different versions and furthermore git should allow you to roll the repo back to any point in development, so you could just test.

**Comment by Malevola** [comment]
sorry, but I don't see a releases tab. I was just searching the previous issues and found this: https://github.com/AeroScripts/QuestieDev/pull/499 but I don't have that feature in the latest release.

**Comment by Muehe** [comment]
The release tab is only visible from the main repo page, this is its adress: https://github.com/AeroScripts/QuestieDev/releases

You can also just download the current state of the repo as described [here](https://github.com/AeroScripts/QuestieDev/wiki/FAQ%26Readme#basic-installation-instructions). This will be the most updated version of Questie.

**Comment by Malevola** [comment]
Thanks so much. Exactly what I was looking for.
