### ISSUE TITLE
Missing Quest "Investigate the Scourge of Stormwind"

### ISSUE THREAD

**Issue by Hiethen** [AeroScripts/QuestieDev#537]
Using Questie 3.70.

https://www.wowhead.com/quest=9260/investigate-the-scourge-of-stormwind

![capture3](https://user-images.githubusercontent.com/32824778/53970006-d81d9e00-40c7-11e9-9f9b-3a04c5f3c3ad.PNG)

Received the following error when mousing over the item.
![capture](https://user-images.githubusercontent.com/32824778/53970269-511cf580-40c8-11e9-908e-63c0ad214ebf.PNG)

![capture2](https://user-images.githubusercontent.com/32824778/53970052-e7045080-40c7-11e9-8c6a-fcdaabe97054.PNG)

**Comment by Muehe** [comment]
This bug may have been fixed by the [latest release](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.1), please update and re-open the issue if the problem persists.
