### ISSUE TITLE
QuestieQuest.lua:1116: Usage: GetQuestLogTitle(index)

### ISSUE THREAD

**Issue by Hiethen** [AeroScripts/QuestieDev#538]
Accepted "Underbelly Scales" and "A Baying of Gnolls" quests. The quest question mark remained on the mini map. Upon mousing over the question mark, I received the following error. Using Question 3.70.

![capture1](https://user-images.githubusercontent.com/32824778/54045950-ed1a3000-41a0-11e9-8f71-cc99b60ccff5.PNG)

**Comment by Muehe** [comment]
This bug may have been fixed by the [latest release](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.1), please update and re-open the issue if the problem persists.
