### ISSUE TITLE
Will Questie Support the Official WoW Classic Client?

### ISSUE THREAD

**Issue by gingerBill** [AeroScripts/QuestieDev#539]
Will Questie Support the Official WoW Classic Client?

**Comment by AeroScripts** [comment]
Yep, check out the QuestieClassic branch, work is being done there currently. It will be merged into the master branch once things get stable.

**Comment by gingerBill** [comment]
AMAZING! As the only addon I want for the official client is this one. It just saves me from just searching up on Wowhead etc for the really obscure quests which have really annoying descriptions.
