### ISSUE TITLE
Using Questie in WoW Classic Beta?

### ISSUE THREAD

**Issue by Eric-Johnston** [AeroScripts/QuestieDev#540]
I see there's a branch for the classic version of Questie, but I'm unable to get it to show up once I launch my game. Is this intended?

**Comment by AeroScripts** [comment]
Most likely reason is the addon folder name being wrong, it should be called "Questie" not "QuestieClassic"

Be warned though, it really is a very early test build, most things are missing including objective notes

**Comment by Eric-Johnston** [comment]
Thanks for the response, renaming the folder to "Questie" did the trick. I appreciate the work you do!

**Comment by AeroScripts** [comment]
This was recently changed to make it easier during development, you don't need to rename the folder anymore it should stay "QuestieDev-QuestieClassic"
