### ISSUE TITLE
Quest Test of Faith not returning a description

### ISSUE THREAD

**Issue by Logonz** [AeroScripts/QuestieDev#541]
![Image](https://cdn.discordapp.com/attachments/579966856085897216/580333953077084160/unknown.png)

It errors trying to get description, also a blizzard bug. Keep an eye out

**Comment by AeroScripts** [comment]
Changes to the event api have hopefully fixed this but there's no way to know for sure until its tested again

**Comment by towneh** [comment]
Message: ...s\QuestieDev-QuestieClassic\Modules\QuestieQuest.lua:682: bad argument #1 to 'match' (string expected, got nil)
Time: Sat May 25 21:44:50 2019
Count: 1
Stack: ...s\QuestieDev-QuestieClassic\Modules\QuestieQuest.lua:682: bad argument #1 to 'match' (string expected, got nil)
[C]: in function `match'
...s\QuestieDev-QuestieClassic\Modules\QuestieQuest.lua:682: in function `GetLeaderBoardDetails'
...s\QuestieDev-QuestieClassic\Modules\QuestieQuest.lua:637: in function `GetAllQuestObjectives'
...s\QuestieDev-QuestieClassic\Modules\QuestieQuest.lua:614: in function `PopulateQuestLogInfo'
...s\QuestieDev-QuestieClassic\Modules\QuestieQuest.lua:198: in function `UpdateQuest'
...ieDev-QuestieClassic\Modules\QuestieEventHandler.lua:79: in function <...ieDev-QuestieClassic\Modules\QuestieEventHandler.lua:78>

Locals: (*temporary) = nil
(*temporary) = "(.*):%s*([%d]+)%s*/%s*([%d]+)"
(*temporary) = "string expected, got nil"

From the QuestieClassic branch updated today.

**Comment by AeroScripts** [comment]
I'll look into that now

**Comment by AeroScripts** [comment]
@towneh should be fixed now thanks for letting us know

**Comment by BreakBB** [comment]
Description is included in the new questDB
