### ISSUE TITLE
Map markers are green boxes [Classic WoW]

### ISSUE THREAD

**Issue by kalashnikovvodka** [AeroScripts/QuestieDev#542]
![image](https://user-images.githubusercontent.com/37820621/58148951-d0818600-7c2e-11e9-9f0d-b6c54511a3d6.png)

**Comment by AeroScripts** [comment]
This can happen if the folder name is wrong, Is questie folder named "QuestieDev-QuestieClassic"?

Also, make sure you have the newest version, I just pushed an update  a couple minutes ago.

**Comment by kalashnikovvodka** [comment]
The new update fixed it, thanks!
