### ISSUE TITLE
Quest Milly Osworth(3903) requires both Brotherhood of Thieves(18) and Wolves Across the Border(33)

### ISSUE THREAD

**Issue by Logonz** [AeroScripts/QuestieDev#543]
The quest:
https://classic.wowhead.com/quest=3903/milly-osworth

Requires both quest 
Brotherhood of Thieves:18 https://classic.wowhead.com/quest=18/brotherhood-of-thieves
and
Wolves Across the Border:33 https://classic.wowhead.com/quest=33/wolves-across-the-border

but only requires Wolves Across the Border:33 in the DB.

Wrong with generation?

**Comment by BreakBB** [comment]
This is fixed via the corrections.lua

**Comment by anon1231823** [comment]
For posterity reading this, quest 18 is required, but 33 is NOT required.
