### ISSUE TITLE
Quest log data takes an unpredictable amount of time to be updated

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#548]
It's hard to say if this will be something we'll have to deal with at launch, but its a source of a few quirks with objective notes. Sometimes the API returns " : / " for objective text, or old data.

We've put together some code to compensate for this, and at this point it's working pretty well but it's not ideal. This issue will be used to track progress on this (It might be fixed on Blizzard's end)

**Comment by BreakBB** [comment]
There was a message on Discord just today about this issue. Is this fixed @AeroScripts ?
