### ISSUE TITLE
Quest "The Blackwood Corrupted" has No Markers

### ISSUE THREAD

**Issue by manistal** [AeroScripts/QuestieDev#550]
This quest in Darkshore has the objective of "Gather a sample of fruit, nut and grain from the norther Blackwood furblog camps" 

The `Food Crate` objects are around 51,35 in Darkshore. 

https://classic.wowhead.com/quest=4763/the-blackwood-corrupted

**Comment by AeroScripts** [comment]
Just to make sure, they still don't show after reloadui, and on the latest version? Last night I fixed a lot of event-type quests like that. It's possible they weren't showing due to the API latency bug

I'm going to look into the quest data now though, thanks for the report 👍

**Comment by manistal** [comment]
Confirming they do not show up after a reload. Issue encountered on `9fa4ef988b3294`

**Comment by christophrus** [comment]
so should we report quests, that dont show up even after /reload ?

**Comment by AeroScripts** [comment]
Yes please do it's really helpful. We'll try to fix thigs as quickly as possible as long as we know they're broken

**Comment by AeroScripts** [comment]
Just posting back to say this should be fixed now but I can't confirm so leaving this open

**Comment by BreakBB** [comment]
This is fixed
