### ISSUE TITLE
Wrong Quest Showing: Bingle's Missing Supplies

### ISSUE THREAD

**Issue by PibbzTV** [AeroScripts/QuestieDev#553]
The quest in loch modan, Bingle's Missing Supplies does not show up on the correct location. Instead there is a low level quest called In Favor of the Light displayed in its place.

**Comment by AeroScripts** [comment]
Thanks for letting us know, ill check the data it's probably missing. I'm sure it's not the case this time but always give /console reloadui a try as it will often fix notes (There is a bug with the API currently that we're working on)


Pretty sure this one is wrong in the DB though, regardless thanks again for the report

**Comment by AeroScripts** [comment]
This should be fixed now, finished that quest myself and it seemed fine
