### ISSUE TITLE
No Questmarkers on map for "The Peoples Militia"

### ISSUE THREAD

**Issue by christophrus** [AeroScripts/QuestieDev#556]
Link: https://classic.wowhead.com/quest=12/the-peoples-militia

**Comment by AeroScripts** [comment]
This is likely due to the API bug, Logon and Muehe are working on a better solution for that, but in the meantime /console reloadui will clear it up

I'm sure in this case because I'm currently on that quest myself
https://cdn.discordapp.com/attachments/441795788801179649/583056579734142986/unknown.png

Thanks for the report though 👍

**Comment by AeroScripts** [comment]
If reloadui does not clear it up for you, make sure you're on the latest build, and post back ill still watch this issue

**Comment by christophrus** [comment]
Definitly not working for me. Always doing /reload first before posting here and also always on the latest version using git pull

Follow up quest is also affected: https://classic.wowhead.com/quest=13/the-peoples-militia

**Comment by AeroScripts** [comment]
I'll look into this maybe its because im still on the first step 😮

**Comment by christophrus** [comment]
markers weren't showing for me at the first step also

**Comment by christophrus** [comment]
@AeroScripts The 3rd part of the quest chain is also affected: https://classic.wowhead.com/quest=13/the-peoples-militia

I figured out that the problem seems to be related to the locale of the client. When switching to english locale the markers are shown correctly, but not with german locale.

**Comment by AeroScripts** [comment]
ooooh that could be it. Some of the database data is english specific, but we're working on making it universal and importing the other languages into the DB

**Comment by christophrus** [comment]
@AeroScripts so should I report other quests that dont work in non-english client further on?
