### ISSUE TITLE
QuestTracker look n feel

### ISSUE THREAD

**Issue by hjortmar** [AeroScripts/QuestieDev#56]
The quest tracker is too big, it would be preferrable if it was resizable and/or cleaner like the default quest tracker / eql3 tracker.
Not a bug but I would almost prefer to use something else only for the size of the tracker.

These quests are Horde only yet they show up for me as Alliance.
Identifying the Brood
Armry of the Black Dragon
Overlord Mok'Morokk's Concern

**Comment by Sparh4wk** [comment]
confirmed, some quests shows up even if they arent for your faction.
and some quests shows even if you already done them.
+1 for resizable tracker

**Comment by hjortmar** [comment]
Would it be a huge endeavour to replace EQL3? There is an issue where its questtracker flashes by every minute or so.
What you want from EQL is the two page setup and WHDB support.

**Comment by hjortmar** [comment]
Is it possible to change the opacity of the background aswell? For some reason I am unable to add some quests to the tracker.

**Comment by Logonz** [comment]
Thjortmar the problem with it flashing is because when questupdate event gets triggered EQL by it self shows the tracker, to fix this we would need to edit the EQL code.

**Comment by hjortmar** [comment]
Ah alright, I would like the addon alot more if it removed the need for these other addons (you cant really use the default layout for the quest log).
I really like the addon, the feature I like the most is the way objectives and quest hubs show up on the map.

Good job so far.
