### ISSUE TITLE
No Quest at marker for Guarded Thunder Ale Barrel

### ISSUE THREAD

**Issue by Lickwid** [AeroScripts/QuestieDev#562]
Searched for a good 15 minutes, there no quest at the quest marker. Maybe I just missed it, but was standing on the marker for 5 minutes. Tried getting to it from the outside and you can't climb the mountains.

Edit: I just got the quest Bitter Rivals (https://www.wowhead.com/quest=310/bitter-rivals), and it appears to be on the same marker as Guarded Thunder Ale Barrel, possibly the start marker is wrong?

**Comment by sinkda** [comment]
Just to confirm, you saw the quest to get the Guarded Thunder Ale Barrel but you didn't have the quest for Bitter Rivals yet?  I know this quest makes you buy the thunder ale for the dwarf in the inn's basement and he walks away. then you interact with the barrel behind him but in-game there is no quest marker on the barrel itself.  you have to mouse over it and it highlights then you can interact with that quest.

**Comment by Lickwid** [comment]
Yep. I walked into town and started picking up quests, couldn't get that one. Didn't realize what it was until I was completing Bitter Rivals, and then I put two and two together.
