### ISSUE TITLE
Random LUA Error while walking around Chill Breeze Valley (Classic)

### ISSUE THREAD

**Issue by Lickwid** [AeroScripts/QuestieDev#565]
Happened twice and hasn't happened again since. Was just walking towards brewnall village when it popped up

Message: ...s\QuestieDev-QuestieClassic\Modules\QuestieQuest.lua:664: bad argument #1 to 'match' (string expected, got nil)
Time: Thu May 30 02:29:00 2019
Count: 2
Stack: ...s\QuestieDev-QuestieClassic\Modules\QuestieQuest.lua:664: bad argument #1 to 'match' (string expected, got nil)
[C]: in function `match'
...s\QuestieDev-QuestieClassic\Modules\QuestieQuest.lua:664: in function `GetLeaderBoardDetails'
...s\QuestieDev-QuestieClassic\Modules\QuestieQuest.lua:612: in function `GetProgress'
...uestieDev-QuestieClassic\Modules\QuestieTooltips.lua:86: in function `GetTooltip'
...uestieDev-QuestieClassic\Modules\QuestieTooltips.lua:118: in function <...uestieDev-QuestieClassic\Modules\QuestieTooltips.lua:114>
[C]: ?
[C]: ?

Locals: (*temporary) = nil
(*temporary) = "(.*):%s*([%d]+)%s*/%s*([%d]+)"
(*temporary) = "string expected, got nil"

**Comment by AeroScripts** [comment]
Just pushed a fix to prevent errors and hopefully solve this, but I can't be sure until I can reproduce it myself (Can't seem to atm)

**Comment by Lickwid** [comment]
Just tried to duplicate it to give you more information...couldn't duplicate it either 🈂️ 

Might just be one of those weird things that popped up...

**Comment by AeroScripts** [comment]
Should be fixed, closing this for now
