### ISSUE TITLE
After Completing Stocking Jetstream tooltip still shows that quest progression at 0/0 (Classic)

### ISSUE THREAD

**Issue by Lickwid** [AeroScripts/QuestieDev#566]
Completed the quest stocking jetstream (https://www.wowhead.com/quest=317/stocking-jetsteam), and when I get Chunk of Boar Meat it still shows I need 0/0 for the quest.

This overwrites the current quest I'm on (A Favor for Evershine: https://www.wowhead.com/quest=319/a-favor-for-evershine).

You can briefly see the correct quest, then it will switch to the old one.

**Comment by AeroScripts** [comment]
This should be fixed with the recent logic changes so closing this for now
