### ISSUE TITLE
Weird quest line issue "Shimmer Stout" showing quest you can't do "Rejold's New Brew" (Classic)

### ISSUE THREAD

**Issue by Lickwid** [AeroScripts/QuestieDev#567]
Was really confused about this until I googled them. 

If you do the shimmer stout quest (which works fine), you can't complete https://www.wowhead.com/quest=415/rejolds-new-brew

You have to decline shimmer stout, run back to kharanos, take the Rejold's New Brew quest, then you can do shimmer stout.

Currently, if you complete shimmer stout without doing Rjold's New Brew, Rjold's New Brew is still showing up on the map as available.

**Comment by AeroScripts** [comment]
Ahh, it's a breadcrumb quest, we're probably missing the ExclusiveGroup data, ill add it now 👍

**Comment by mbrannon** [comment]
Just confirming that this is still happening. Rejold's is a breadcrumb to get you to Shimmer Stout which sends you across the map towards Loch Modan side. Anyways, if you find Shimmer Stout on your own while doing the other quests, two copies of Rejold's New Brew appear on your map and can't be gotten rid of.

**Comment by Muehe** [comment]
Ah yeah, this quest chain is pretty complex. Will look into it once I get to that level/zone.

Thanks for the report. :+1:

**Comment by BreakBB** [comment]
@Muehe Did you put some time into this?

**Comment by AeroScripts** [comment]
apparently still not working right

**Comment by AbelBeja** [comment]
Just providing an update as I completed the Dun Morogh zone quests last night on a lvl 60 who didn't quest in the zone when lvling up.

After doing the Shimmer Stout quest without picking up the breadcrumb Rejold's New Brew quest the ! icon would still appear on the map for the 2 quest givers who give it. After a relog the ! icons disappeared.

**Comment by drejjmit** [comment]
Tested this on latest and everything works as it should. 
"Rejold's New Brew" shows up as 'Available' from Pilot Bellowfiz & Tharek Blackstone after you complete "The Perfect Stout" and both offers the quest.
"Rejold's New Brew" gets removed from Questie and from the NPCs when you pick up "Shimmer Stout"
