### ISSUE TITLE
"Deeprun Rat Roundup" is showing up outside deeprun tram in both SW and IF (Classic)

### ISSUE THREAD

**Issue by Lickwid** [AeroScripts/QuestieDev#568]
also not showing where monty really is (IF side of deeprun tram)

https://www.wowhead.com/quest=6661/deeprun-rat-roundup

**Comment by MysticalOS** [comment]
I figured this is intentional, although adding (entrance) to tooltip might make that clearer.

**Comment by Lickwid** [comment]
That might make sense for the one in IF, but not SW. And the quest isn't showing up in IF DRT either.

**Comment by AeroScripts** [comment]
Not sure the best way to handle this to be honest, I don't think theres a way to properly render notes inside the deeprun instance, so if it doesn't show there it can't really show anywhere

**Comment by Muehe** [comment]
Yes this is intentional behaviour, the map shows both entrance points to the instance.
