### ISSUE TITLE
Druid quest "Gathering the cure" shows nearly all mobs in every zone dropping Earthroot, causing performance issues

### ISSUE THREAD

**Issue by Ickzy** [AeroScripts/QuestieDev#570]
Populates nearly every zone with tons of markers for mobs dropping the herb Earthroot for the quest. Tanks your fps and causes massive stuttering. (i9 9900k @ 5ghz all cores/RTX 2080)

**Comment by AeroScripts** [comment]
Hey thanks for the report!
I just changed the logic as of commit 030f1149fec6a02f814892b017f80781fffa4901 which should take care of this, though we should probably blacklist earthroot anyway, ill do that too

**Comment by Roughrider** [comment]
Turn off questie in cartographer.  Severe hitching for "Root Samples" in the barrens as well.
