### ISSUE TITLE
Classic: "The Corruption Abroad" still shows up, even though I have "Researching the Corruption"

### ISSUE THREAD

**Issue by CapnRat** [AeroScripts/QuestieDev#576]
The quest "The Corruption Abroad" is an optional quest that will lead you to get "Researching the Corruption". I already have "Researching the Corruption", but questie is still showing "The Corruption Abroad" even though I can't actually get it anymore.

In the attached image, see that Questie is showing in the minimap that Argos Nightwhisper should be giving me "The Corruption Abroad" question. But there's no quest to be gotten here. Also, note that my quest log has "Researching the Corruption".

![World Of Warcraft Screenshot 2019 06 01 - 18 59 53 64](https://user-images.githubusercontent.com/141458/58751524-d6356200-849f-11e9-90b7-ff8a1270b4eb.png)

**Comment by AeroScripts** [comment]
Nice catch, fixed now 👍
