### ISSUE TITLE
No exclemation mark for "The weathered grave"

### ISSUE THREAD

**Issue by christophrus** [AeroScripts/QuestieDev#578]
Initially there is no exclemation mark on the map for this quest, but when I accept the quest and then cancel it, the exclemation mark shows up. After a /reload it is gone again.

Link: https://classic.wowhead.com/quest=225/the-weathered-grave

**Comment by Shelfen** [comment]
This showed up on my Walkthrough of Duskwood, so this is in Good order, its just the Tracking bug that desyncs or stops updating after some time but starts working again at random or after a /reload.

**Comment by AeroScripts** [comment]
Closing this for now

**Comment by christophrus** [comment]
Always tried to /reload before reporting anything :)

**Comment by AeroScripts** [comment]
This was likely fixed during one of the updates after you posted, lot of changes to the logic. If it happens again ill reopen but the quest data looks correct
