### ISSUE TITLE
No marker on map for "Ogre Thieves"

### ISSUE THREAD

**Issue by christophrus** [AeroScripts/QuestieDev#579]
Link: https://classic.wowhead.com/quest=134/ogre-thieves

**Comment by Shelfen** [comment]
[[Abercrombie's Crate(1349)]](https://classic.wowhead.com/item=1349/abercrombies-crate)
Location: "Player: 33.4 X , 76.4 Y"
![WowB_2019-06-07_17-43-15](https://user-images.githubusercontent.com/51490713/59136386-338b5080-8983-11e9-8e68-13aef57d255b.jpg)

**Comment by AeroScripts** [comment]
Fixed as of 199926e569a9ee72786f3d4e326d0f77d3e8c488 thanks for the report 👍
