### ISSUE TITLE
no question mark for "the prodigal lich" to complete in Undercity

### ISSUE THREAD

**Issue by Seizzz** [AeroScripts/QuestieDev#583]

**Comment by Seizzz** [comment]
no question mark for "the prodigal lich" to complete in Undercity

**Comment by AeroScripts** [comment]
It's likely this one is related to the desync issue. /reloadui will likely clear it up until that is solved. Just checked the db, and all the data looks good in this case

**Comment by BreakBB** [comment]
Related to #860
