### ISSUE TITLE
No exclemation mark for "Mythology of the Titans"

### ISSUE THREAD

**Issue by christophrus** [AeroScripts/QuestieDev#584]
Link: https://classic.wowhead.com/quest=1050/mythology-of-the-titans

**Comment by AeroScripts** [comment]
What level were you at the time? In the DB this quest has no requirement data, just min level 30 and must be alliance

**Comment by christophrus** [comment]
Its acceptable as of level 28. Anyways, I only reported quests that I could accept from the npc but didn't showed up on the map. Always tried /reload before

**Comment by BreakBB** [comment]
Should be fixed with the latest spawn data update
