### ISSUE TITLE
Exclemation mark is showing up again on map after completing quest "Lightforge Ingots"

### ISSUE THREAD

**Issue by christophrus** [AeroScripts/QuestieDev#587]
Link: https://classic.wowhead.com/quest=526/lightforge-ingots

**Comment by Shelfen** [comment]
![image](https://user-images.githubusercontent.com/51490713/59135525-86630900-897f-11e9-93fa-001367aefd7f.png)
[[The Lost Ingots(324)]](https://classic.wowhead.com/quest=324/the-lost-ingots) is the continuing quest from the Box you loot on the [[Lightforge Iron(321)]](https://classic.wowhead.com/quest=321/lightforge-iron) quest from.

The whole quest i think is based under the [[Lightforge Iron(321)]](https://classic.wowhead.com/quest=321/lightforge-iron) and only has that ID for the quest, not the [[Lightforge Ingots(526)]](https://classic.wowhead.com/quest=526/lightforge-ingots).
[[Lightforge Ingots(526)]](https://classic.wowhead.com/quest=526/lightforge-ingots) is indicated on the questline on wowhead, but based on my logs i never picked this quest up while doing this, so this quest should be false.

**Comment by BreakBB** [comment]
Closing this for now. Fix looks good at a second glance
