### ISSUE TITLE
No exclemation mark on map for "Preserving Knowledge"

### ISSUE THREAD

**Issue by christophrus** [AeroScripts/QuestieDev#588]
Link: https://classic.wowhead.com/quest=540/preserving-knowledge

**Comment by AeroScripts** [comment]
Going to take some time tomorrow and go through all of these, thanks for posting ❤️

**Comment by BreakBB** [comment]
"Loremaster Dibbs" is listed in the spawnDB and connected to this quest. Should be fixed
