### ISSUE TITLE
Shift+Click TrackerFram to stop tracking quests

### ISSUE THREAD

**Issue by ayrb13** [AeroScripts/QuestieDev#59]
Usually there are many quests tracked in trackerfram, when i want to stop tracking some quests, I need to find it in native questlog and shift+click to remove it from trackerfram.

**Comment by AeroScripts** [comment]
I've started implementing a system that should solve this. It's not shift+click but you can right-click on a quest in the tracker and click "Untrack"

**Comment by ayrb13** [comment]
That's better than my solution. Keep it going!
