### ISSUE TITLE
QuestieDev-master (classic) LUA error on load

### ISSUE THREAD

**Issue by towneh** [AeroScripts/QuestieDev#590]
Message: Interface\AddOns\QuestieDev-master\Questie.lua:680: attempt to call method 'CloseCallback' (a nil value)
Time: Thu Jun  6 20:24:48 2019
Count: 1
Stack: Interface\AddOns\QuestieDev-master\Questie.lua:680: attempt to call method 'CloseCallback' (a nil value)
Interface\AddOns\QuestieDev-master\Questie.lua:680: in function <Interface\AddOns\QuestieDev-master\Questie.lua:619>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...QuestieDev-master\Libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...QuestieDev-master\Libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...QuestieDev-master\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

**Comment by sinkda** [comment]
Thanks for reporting this.  This seems to have come from an issue with the ace library and other addons.  A fix has been pushed (see: #591) Once this gets accepted it should resolve this lua error.

In the meantime you can do a quick fix of changing line 680 in Questie.lua to add a "--" (without the quotes) to the front of the line.  But the PR should be pulled in soon.
