### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tuska76** [AeroScripts/QuestieDev#592]
Message: ...s\QuestieDev-QuestieClassic\Database\functionsDB.lua:258: attempt to index global 'questRequirementFixes' (a nil value)
Time: Thu Jun  6 23:26:36 2019
Count: 1
Stack: ...s\QuestieDev-QuestieClassic\Database\functionsDB.lua:258: attempt to index global 'questRequirementFixes' (a nil value)
...s\QuestieDev-QuestieClassic\Database\functionsDB.lua:258: in function `GetQuest'
...s\QuestieDev-QuestieClassic\Modules\QuestieQuest.lua:252: in function `GetAllQuestIdsNoObjectives'
...ieDev-QuestieClassic\Modules\QuestieEventHandler.lua:72: in function <...ieDev-QuestieClassic\Modules\QuestieEventHandler.lua:67>
[C]: ?
...Icon-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...Icon-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Icon-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ev-QuestieClassic\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ev-QuestieClassic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by AeroScripts** [comment]
Has this been solved yet? Looks like an issue with your download, try downloading again it should fix it. Make sure you have deleted any old questie folders also. Closing this for now
