### ISSUE TITLE
Wrong exclemation mark location for "Gizelton Caravan"

### ISSUE THREAD

**Issue by christophrus** [AeroScripts/QuestieDev#595]
The place where u actually accept the quest and the caravan starts is at 40.80 (see wowhead comments)

Link: https://classic.wowhead.com/quest=5943/gizelton-caravan

**Comment by BreakBB** [comment]
@Trovalds is correct. The caravan is patrolling from the given spawn location all the way down and you can get the quest on its way.

We have yet to find a way to show this correctly without flooding the map.

**Comment by BreakBB** [comment]
According to Rainerius on Discord the quest simply has two starting points which will be an easy fix:

67,37
45,76

**Comment by BreakBB** [comment]
I followed [this commend](https://classic.wowhead.com/quest=5943/gizelton-caravan#comments:id=3153393) on Wowhead and changed the locations accordingly.
