### ISSUE TITLE
Error when accepting Study of the Elements: Rock (3rd quest)

### ISSUE THREAD

**Issue by towneh** [AeroScripts/QuestieDev#596]
![image](https://user-images.githubusercontent.com/25694892/59116670-feabd900-8943-11e9-941c-375d7979a832.png)

**Comment by AeroScripts** [comment]
Fixed as of 917add128bf63e5c95bb85013d929d410b9052a8 thanks for posting ❤️ 

Looking into the quest data related issues shortly, thanks for reporting all those too
