### ISSUE TITLE
Tooltip error

### ISSUE THREAD

**Issue by Elekayl** [AeroScripts/QuestieDev#597]
For quest Murloc Poachers in Redridge Mountains, I have aleady completed the quest and turned it in.  I have an extra Murloc Fin in my bag, and when I hover over it, it shows that it requires Bellygrub's Tusk.  This same tool tip shows on the Mob that drops the fins.

Lua Error:  QuestieQuest.lua:646; bad argument#1 to 'match' (string expected, got nil)

**Comment by AeroScripts** [comment]
According to the error you must have an outdated version, as that line doesn't have anything to do with string matching

https://github.com/AeroScripts/QuestieDev/archive/master.zip

Make sure you're on the latest version, that bug is hopefully fixed by now 🙏

**Comment by Elekayl** [comment]
Thanks, I'm too used to using Twitch and Curse before that to totally understand how Github works.  I thought WillitClassic.com would alert me of an update.

Things seem fine!

**Comment by AeroScripts** [comment]
We gotta work on making things easier to set up too. Recently started putting up releases on wowinterface 

https://www.wowinterface.com/downloads/info24994-Questie.html
Downloading from there is probably a better idea because only "stable" builds will be there

**Comment by Elekayl** [comment]
I saw that, the link to Github wasn’t even active on willitclassic, but I got there via wowinterface.  I’m liking this newest version.  Thanks!
