### ISSUE TITLE
Error when entering Razorfen Downs

### ISSUE THREAD

**Issue by towneh** [AeroScripts/QuestieDev#599]
Message: ...ddOns\QuestieDev-master\Modules\QuestieFramePool.lua:33: attempt to index global 'icon' (a nil value)
Time: Sat Jun  8 02:10:13 2019
Count: 1
Stack: ...ddOns\QuestieDev-master\Modules\QuestieFramePool.lua:33: attempt to index global 'icon' (a nil value)
...ddOns\QuestieDev-master\Modules\QuestieFramePool.lua:33: in function `GetFrame'
...face\AddOns\QuestieDev-master\Modules\QuestieMap.lua:103: in function `DrawWorldIcon'
...ce\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:349: in function `AddFinisher'
...ce\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:580: in function `PopulateObjectiveNotes'
...ce\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:236: in function `GetAllQuestIds'
...ns\QuestieDev-master\Modules\QuestieEventHandler.lua:156: in function <...ns\QuestieDev-master\Modules\QuestieEventHandler.lua:154>

Locals: self = <table> {
 1 = "QuestieDev-master"
 2 = <table> {
 }
 remap = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieFramePool.lua:177
 UnloadAll = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieFramePool.lua:58
 GetFrame = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieFramePool.lua:27
 euclid = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieFramePool.lua:171
}
f = QuestieFrame212 {
 0 = <userdata>
 glow = QuestieFrame212Glow {
 }
 _hide = <function> defined =[C]:-1
 hidden = true
 loaded = true
 Hide = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:45
 data = <table> {
 }
 Show = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:40
 y = 35.290000
 x = 15.040000
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieFramePool.lua:148
 _show = <function> defined =[C]:-1
 shouldBeShowing = true
 AreaID = 3
 texture = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = QuestieFrame212 {
 0 = <userdata>
 glow = QuestieFrame212Glow {
 }
 _hide = <function> defined =[C]:-1
 hidden = true
 loaded = true
 Hide = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:45
 data = <table> {
 }
 Show = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:40
 y = 35.290000
 x = 15.040000
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieFramePool.lua:148
 _show = <function> defined =[C]:-1
 shouldBeShowing = true
 AreaID = 3
 texture = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'icon' (a nil value)"
unusedframes = <table> {
 1 = QuestieFrame102 {
 }
 2 = QuestieFrame101 {
 }
 3 = QuestieFrame195 {
 }
 4 = QuestieFrame197 {
 }
 5 = QuestieFrame199 {
 }
 6 = QuestieFrame201 {
 }
 7 = QuestieFrame203 {
 }
 8 = QuestieFrame205 {
 }
 9 = QuestieFrame207 {
 }
 10 = QuestieFrame209 {
 }
 11 = QuestieFrame211 {
 }
 12 = QuestieFrame196 {
 }
 13 = QuestieFrame198 {
 }
 14 = QuestieFrame200 {
 }
 15 = QuestieFrame202 {
 }
 16 = QuestieFrame204 {
 }
 17 = QuestieFrame206 {
 }
 18 = QuestieFrame208 {
 }
 19 = QuestieFrame210 {
 }
 20 = QuestieFrame212 {
 }
 21 = QuestieFrame195 {
 }
 22 = QuestieFrame197 {
 }
 23 = QuestieFrame199 {
 }
 24 = QuestieFrame201 {
 }
 25 = QuestieFrame203 {
 }
 26 = QuestieFrame205 {
 }
 27 = QuestieFrame207 {
 }
 28 = QuestieFrame209 {
 }
 29 = QuestieFrame211 {
 }
 30 = QuestieFrame196 {
 }
 31 = QuestieFrame198 {
 }
 32 = QuestieFrame200 {
 }
 33 = QuestieFrame202 {
 }
 34 = QuestieFrame204 {
 }
 35 = QuestieFrame206 {
 }
 36 = QuestieFrame208 {
 }
 37 = QuestieFrame210 {
 }
 38 = QuestieFrame212 {
 }
 39 = QuestieFrame195 {
 }
 40 = QuestieFrame197 {
 }
 41 = QuestieFrame199 {
 }
 42 = QuestieFrame201 {
 }
 43 = QuestieFrame203 {
 }
 44 = QuestieFrame205 {
 }
 45 = QuestieFrame207 {
 }
 46 = QuestieFrame209 {
 }
 47 = QuestieFrame211 {
 }
 48 = QuestieFrame196 {
 }
 49 = Quest

---------------------------------

Message: ...ddOns\QuestieDev-master\Modules\QuestieFramePool.lua:33: attempt to index global 'icon' (a nil value)
Time: Sat Jun  8 02:45:52 2019
Count: 2
Stack: ...ddOns\QuestieDev-master\Modules\QuestieFramePool.lua:33: attempt to index global 'icon' (a nil value)
...ddOns\QuestieDev-master\Modules\QuestieFramePool.lua:33: in function `GetFrame'
...face\AddOns\QuestieDev-master\Modules\QuestieMap.lua:103: in function `DrawWorldIcon'
...ce\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:349: in function `AddFinisher'
...ce\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:580: in function `PopulateObjectiveNotes'
...ce\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:236: in function `GetAllQuestIds'
...ns\QuestieDev-master\Modules\QuestieEventHandler.lua:156: in function <...ns\QuestieDev-master\Modules\QuestieEventHandler.lua:154>

Locals: self = <table> {
 1 = "QuestieDev-master"
 2 = <table> {
 }
 remap = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieFramePool.lua:177
 UnloadAll = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieFramePool.lua:58
 GetFrame = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieFramePool.lua:27
 euclid = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieFramePool.lua:171
}
f = QuestieFrame210 {
 0 = <userdata>
 fadeLogic = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieMap.lua:164
 loaded = true
 data = <table> {
 }
 _show = <function> defined =[C]:-1
 shouldBeShowing = false
 AreaID = 3
 texture = <unnamed> {
 }
 _hide = <function> defined =[C]:-1
 hidden = true
 y = 35.290000
 x = 15.040000
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieFramePool.lua:148
 miniMapIcon = true
 Hide = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:45
 glow = QuestieFrame210Glow {
 }
 Show = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:40
}
(*temporary) = nil
(*temporary) = QuestieFrame210 {
 0 = <userdata>
 fadeLogic = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieMap.lua:164
 loaded = true
 data = <table> {
 }
 _show = <function> defined =[C]:-1
 shouldBeShowing = false
 AreaID = 3
 texture = <unnamed> {
 }
 _hide = <function> defined =[C]:-1
 hidden = true
 y = 35.290000
 x = 15.040000
 glowTexture = <unnamed> {
 }
 Unload = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieFramePool.lua:148
 miniMapIcon = true
 Hide = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:45
 glow = QuestieFrame210Glow {
 }
 Show = <function> defined @Interface\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:40
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'icon' (a nil value)"
unusedframes = <table> {
 1 = QuestieFrame102 {
 }
 2 = QuestieFrame101 {
 }
 3 = QuestieFrame195 {
 }
 4 = QuestieFrame197 {
 }
 5 = QuestieFrame199 {
 }
 6 = QuestieFrame201 {
 }
 7 = QuestieFrame203 {
 }
 8 = QuestieFrame205 {
 }
 9 = QuestieFrame207 {
 }
 10 = QuestieFrame209 {
 }
 11 = QuestieFrame211 {
 }
 12 = QuestieFrame196 {
 }
 13 = QuestieFrame198 {
 }
 14 = QuestieFrame200 {
 }
 15 = QuestieFrame202 {
 }
 16 = QuestieFrame204 {
 }
 17 = QuestieFrame206 {
 }
 18 = QuestieFrame208 {
 }
 19 = QuestieFrame210 {
 }
 20 = QuestieFrame212 {
 }
 21 = QuestieFrame195 {
 }
 22 = QuestieFrame197 {
 }
 23 = QuestieFrame199 {
 }
 24 = QuestieFrame201 {
 }
 25 = QuestieFrame203 {
 }
 26 = QuestieFrame205 {
 }
 27 = QuestieFrame207 {
 }
 28 = QuestieFrame209 {
 }
 29 = QuestieFrame211 {
 }
 30 = QuestieFrame196 {
 }
 31 = QuestieFrame198 {
 }
 32 = QuestieFrame200 {
 }
 33 = QuestieFrame202 {
 }
 34 = QuestieFrame204 {
 }
 35 = QuestieFrame206 {
 }
 36 = QuestieFrame208 {
 }
 37 = QuestieFrame210 {
 }
 38 = QuestieFrame212 {
 }
 39 = QuestieFrame195 {
 }
 40 = QuestieFrame197

**Comment by AeroScripts** [comment]
Hey thanks for the report, though this one was fixed last night as of https://github.com/AeroScripts/QuestieDev/commit/917add128bf63e5c95bb85013d929d410b9052a8

Should be good now
