### ISSUE TITLE
`questIndex' a nil value

### ISSUE THREAD

**Issue by rosariop** [AeroScripts/QuestieDev#600]
I get an error at Interface\AddOns\!Questie\Modules\QuestieTracker.lua:988 attempt to concatenate field `questIndex' (a nil value)

I got it at multiple quest. Right now i am at "Riverpaw Gnoll Bounty".

**Comment by BreakBB** [comment]
Something else you @AeroScripts should keep in mind

**Comment by BreakBB** [comment]
Closing this for now in favor of WoW Classic
