### ISSUE TITLE
Add zhTW localization

### ISSUE THREAD

**Issue by class2u** [AeroScripts/QuestieDev#602]
Is there any possibility to display localized quest name in tooltip? I am using zhTW client. Thank you.

**Comment by AeroScripts** [comment]
It works on zhTW client? I will push a change to make it use the localized quest name based on quest log, but you might experience other issues (please post about them though)

**Comment by class2u** [comment]
It does show localized quest name and no LUA error. Much helpful now. Thank you!
The issues now are:
1. Quest names of available quest are not localized.
2. NPC names of completed and available quest are not localized. So it may display both localized and not localized info at the same time.
3. Nameplate icon of objective mob does not work.

**Comment by EKE00372** [comment]
It probably because Database ware based by name, not IDs (npc id / quest id or other else)

and should said, locale file name should be zhTW/zhCN, not enTW/enCN

**Comment by class2u** [comment]
Version 4.0.4 (download from wowinterface) does not display localized quest name of which already in quest log.

**Comment by AeroScripts** [comment]
Working on some more localization stuff, but it's a tough process. We need to import translated NPC, object and quest names. Mainly for availble quests. It should be possible to do mob tooltips without that, but for things to work properly the real data is needed.

Hopefully we can collect the data before launch, I think wowhead has some languages already on the classic DB, it's bound to be online somewhere. cmangos also has some of it, but not all languages

**Comment by BreakBB** [comment]
[This webiste](http://db.178.com/wow/tw/index.html) includes zhTW data. Using [the scraper](https://github.com/BreakBB/wowhead_scraper) this could help to get the data for quests and NPCs. Would appreciate a PR on the scraper since I can't read anything on that side which makes it quite difficult to navigate and find interesting data 😅

**Comment by EKE00372** [comment]
> [This webiste](http://db.178.com/wow/tw/index.html) includes zhTW data. Using [the scraper](https://github.com/BreakBB/wowhead_scraper) this could help to get the data for quests and NPCs. Would appreciate a PR on the scraper since I can't read anything on that side which makes it quite difficult to navigate and find interesting data 😅
This is not correct data. it's not vanilla data.

**Comment by BreakBB** [comment]
Sorry for the late response @EKE00372 . Hmmm do you have any source of WoW Classic data on zhTW? I don't understand any Language different to German, English or Dutch so I have no clue what content those websites actually have :/

**Comment by EKE00372** [comment]
there's no database on internet, MaNGOS zhTW localized are incorrect too.

i only have some cache(WDB file)

**Comment by BreakBB** [comment]
@EKE00372 Can you tell what the current situation on this issue is?

**Comment by EKE00372** [comment]
MaNGOS zhTW lost almost quest data, only have some quest name, and unit name incorrect.

**Comment by EKE00372** [comment]
Quest cache 010 editor template:
https://github.com/EKE00372/WOWThings/blob/master/Working_on_TWDB/questcache.bt
cache(minority):
https://drive.google.com/open?id=1Wg0ili_Ct1Oe8xlyqS8EUt_pklNmB_A1

**Comment by AeroScripts** [comment]
v6.0.5
