### ISSUE TITLE
Questlog tracker now showing in dungeons and instances.

### ISSUE THREAD

**Issue by Mufaz333** [AeroScripts/QuestieDev#603]
Hello,

I love the addon and I'm using it on a 1.12.1 vanilla server while waiting for classic release. Therefore I'm using the latest release - Questie v3.7.1 - LAST 1.12 version.

Questie works perfectly apart from 1 thing:

Quest tracker disappears whenever I enter any dungeon.
It also happens when I enter the separate zone in Stormwind or Ironforge (Deeprun Tram).

In any other zone I visited so far the tracker works properly.
I tried reinstalling, tried resetting my settings, tried running it without any other addons etc.
When I disable questie tracker I can see the default tracker inside dungeons.

Please help!

**Comment by BreakBB** [comment]
Closing this for now in favor of WoW Classic

**Comment by revar** [comment]
Why closing, fix this pls.

**Comment by drejjmit** [comment]
> Why closing, fix this pls.

We're no longer working on 1.12 version of Questie.

**Comment by 12512421** [comment]
fixed by if you toggle on/off button on the world map while inside dungeon
it's a bug

**Comment by safir2600** [comment]
cuz questie v.3.7.0: tooltip doesn't work and questie v.3.7.1:tracker closes in dungeon --> questie v3.7.0.5 fixes both 
uploaded as zip
[https://github.com/safir2600/Questie_v3.7.0.5](url)
https://github.com/safir2600/Questie_v3.7.0.5.git
