### ISSUE TITLE
Young bears not marked for quest: Stocking Jetsteam

### ISSUE THREAD

**Issue by duffman4evr** [AeroScripts/QuestieDev#613]
https://classicdb.ch/?quest=317

Was able to get the fur off bears that weren't marked as dropping it on the hover-over tooltip.

**Comment by duffman4evr** [comment]
Follow up to this - this might just be a bug related to too many nodes for quest drops present on minimap. I did notice during this session that when I held on to several quests which had many many markers for gathering/etc on the minimap, seems that some markers started to go missing. May also apply to hover over tooltips as well, since some of them seemed to magically fix themselves once I completed these 'heavy' quests and reloaded the UI. Overall looks like there needs to be some sort of priority system when there are too many icons to render maybe?

**Comment by BreakBB** [comment]
Young bears (ID=1128) which are dropping "Thick bear fur" are listed in the itemDB, so it most likely is not related to this.

```lua
[6952] = {
			{
			{1128,80.0},
			{1196,80.0}
		},
		{},
		{},
		{},
		{},
		"Thick Bear Fur"
	},
```

**Comment by AeroScripts** [comment]
Yeah, this is likely due to the clustering system to prevent too many icons on the map. We probably need to tune the values though. there's "max number of same icons in the same spot in the map"

and "max number of icons per objective". It's probably hit the limit of per-objective per-zone, so it's stopping there

**Comment by BreakBB** [comment]
@AeroScripts Any news on this or any hint how to change those values?

**Comment by BreakBB** [comment]
Assuming this is fixed
