### ISSUE TITLE
Quest "Washed Ashore" not showing objective location

### ISSUE THREAD

**Issue by Berlocky** [AeroScripts/QuestieDev#616]
The quest "Washed Ashore" second part, to get the 'Sea Turtle Remains' located at Ashenvale (31,46) is not showing on map or minimap.
This is on Classic Stress Test (June 19-21).
So, I'm reporting to help improve this great addon that works very well on other pservers.
Keep up the great work.

**Comment by AeroScripts** [comment]
Even after reloadui? That quest is part of a series, it could be why but I did most them myself and it was working fine. It's possible something got messed up recently though

**Comment by BreakBB** [comment]
Location of "Skeletal Sea Turtle" is included and linked in the DB. Should be fixed
