### ISSUE TITLE
questie does not work with mac computers. tested and works fine on my desktop PC. Does not work on my wife's macbook either, other addons work fine on mac

### ISSUE THREAD

**Issue by sethik** [AeroScripts/QuestieDev#617]

**Comment by sethik** [comment]
questie does not work with mac computers. tested and works fine on my desktop PC. Does not work on my wife's macbook either, other addons work fine on mac so I'm not mistaken. https://i.imgur.com/soZ6Azj.jpg

**Comment by AeroScripts** [comment]
Very strange, ill try to test mac client myself shortly, it's probably an easy fix

**Comment by AeroScripts** [comment]
Actually, are you on classic beta client? If not you need to use 3.7.x (for 1.12) from the releases page

**Comment by Muehe** [comment]
This is 1.12 (note the pfQuest icon on the minimap).

**Comment by bjordan2010** [comment]
Works for me on Mac Mini with Mac OS 10.14.6.

**Comment by AeroScripts** [comment]
Closing this for now then, good to hear

**Comment by timendez** [comment]
Questie didn't work for me on Mac Mojave 10.14 when downloaded from https://legacy-wow.com/classic-addons/questie-classic/

However, when downloading the latest release (Questie v4.0.17 BETA) it worked great!
