### ISSUE TITLE
Deleted old build that never gave me lua error today with newest build got this.

### ISSUE THREAD

**Issue by Asglarek** [AeroScripts/QuestieDev#618]
Message: ...ce\AddOns\QuestieDev-master\Locale\QuestieLocale.lua:59: bad argument #2 to 'format' (string expected, got no value)
Time: Sun Jun 23 12:26:55 2019
Count: 1
Stack: ...ce\AddOns\QuestieDev-master\Locale\QuestieLocale.lua:59: bad argument #2 to 'format' (string expected, got no value)
[C]: in function `format'
...ce\AddOns\QuestieDev-master\Locale\QuestieLocale.lua:59: in function `GetUIString'
...ce\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:752: in function `GetAllQuestObjectives'
...ce\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:668: in function `PopulateQuestLogInfo'
...ce\AddOns\QuestieDev-master\Modules\QuestieQuest.lua:237: in function `GetAllQuestIds'
...ns\QuestieDev-master\Modules\QuestieEventHandler.lua:235: in function <...ns\QuestieDev-master\Modules\QuestieEventHandler.lua:233>

Locals: (*temporary) = "Error finding entry ID for objective %s %s"
(*temporary) = "string expected, got no value"

**Comment by AeroScripts** [comment]
Thanks for the report, this should be fixed now but there's likely a quest in your log that will have a missing note, what quests do you have?

**Comment by Asglarek** [comment]
It was Test of Faith causing the exception error. I actually accepted the quest was ported to area and left the quest without leaping off rise.
