### ISSUE TITLE
Questie Error in Azshara

### ISSUE THREAD

**Issue by Kage1831** [AeroScripts/QuestieDev#620]
the error code is as follows:

Interface\AddOns\!Questie\Modules\QuestieNotes.lua:393: attempt to index local `questInfo' (a nil value)

I have tried downloading this addon through several different sources, but none have had this error fixed. Even if this quests that I am currently on is in a zone no one likes (Azshara), it is still annoying. If someone has a fix, please respond as soon as possible.

Thank you.

**Comment by BreakBB** [comment]
Closing this for now in favor of WoW Classic
