### ISSUE TITLE
building under terminal in macOS does not work.

### ISSUE THREAD

**Issue by brannow** [AeroScripts/QuestieDev#621]
major problem is the "\\\\" dose not understand my mac (10.14).

other problem is the dependency to 7z. 
why not the build in "zip" command?

**Comment by brannow** [comment]
image from the current build.sh on my machine: 
![Bildschirmfoto 2019-08-06 um 17 33 20](https://user-images.githubusercontent.com/19426486/62553936-893f8480-b870-11e9-9ce5-1fe877431dde.png)

**Comment by AeroScripts** [comment]
Oh jeez yeah the .sh definitely shouldnt use backslashes.

The build script is only needed to generate release .zips though, you can drop QuestieDev-master into your addons folder and it will work as a normal addon

**Comment by Muehe** [comment]
Should be solved as of d5af7b0154bb2d77df825c86c0c3d6d40a462972. If you have problems running that script on Mac please open a new issue.
