### ISSUE TITLE
Goldshire quests in Shadowglen

### ISSUE THREAD

**Issue by NerdBird91** [AeroScripts/QuestieDev#623]
The Fargodeep Mine, Kobold Candles, Gold Dust Exchange are Goldshire quests and showing up in Shadowglen as a level 4 night elf.

**Comment by NerdBird91** [comment]
Specifically north of the big tree near the ponds where you collect Moonpetal Lily's for Iverron's Antidote quest

**Comment by BreakBB** [comment]
This must have been because of the desync bug. Closing this for now since the database looks alright

**Comment by BreakBB** [comment]
Related to #860
