### ISSUE TITLE
Classic Stress Test Bugs

### ISSUE THREAD

**Issue by bjordan2010** [AeroScripts/QuestieDev#624]
1. Coolridge Valley Mail Delivery quest turn-in to Talin Keeneye does not show up.
2. Small boars in Coolridge show up for boar ribs Kharanos.

And a question:

Is there a way to limit the quests that show up so that Steelgrill's Depot quests doesn't show up in Kharanos Inn.

**Comment by Muehe** [comment]
1. Will have to look into it once servers are back up.
2. Have you checked if they drop the ribs or not?
3. Not really, you could hack it by adding the quest IDs to the `qHide` table in `Database/corrections.lua`, but we plan on adding an ingame interface for that soon™, so probably not worth the hassle.

**Comment by BreakBB** [comment]
1. Should be fixed since the NPC is included with a spawn location in our database

2. [Small Crag Boars](https://classic.wowhead.com/npc=708/small-crag-boar#drops) really don't drop [Crag Boar Rip](https://classic.wowhead.com/item=2886/crag-boar-rib#dropped-by)s.
