### ISSUE TITLE
QuestieComms

### ISSUE THREAD

**Issue by Roeshambo** [AeroScripts/QuestieDev#627]
`function QuestieComms:MessageReceived(channel, message, type, source) -- pcall this
	DEFAULT_CHAT_FRAME:AddMessage("recv(|cFF22FF22" .. message .. "|r)")
	if channel == "questie" and source then`

Writing all comms to chatframe is picking up any and all addon messages received and printing them to the chat frame. Including from about 4 other addons I've got installed at the moment. It makes for a lot of spam. I've commented it out on my side as it's not necessary but just a heads up if it was a debug overlook.

**Comment by AeroScripts** [comment]
Nice catch, what version are you on? Comms was supposed to be disabled

**Comment by AeroScripts** [comment]
yeah, try the latest 4.0.9 release, it's been disabled since 4.0.4
