### ISSUE TITLE
Old Persistent Issue - Green boxes appearing instead of map markers

### ISSUE THREAD

**Issue by cmcaulay** [AeroScripts/QuestieDev#628]
I've downloaded the latest version, I've made sure that the directory name is QuestieDev and I renamed QuestieDev-master.toc to QuestieDev.toc.  Any ideas why the green boxes are still an issue?

![Filenames](https://user-images.githubusercontent.com/11338041/62815449-f00da980-bacd-11e9-97fd-6633b1dcf050.png)
![Green 1](https://user-images.githubusercontent.com/11338041/62815451-f0a64000-bacd-11e9-83eb-4d05f2d7b7bd.png)
![Green 2](https://user-images.githubusercontent.com/11338041/62815452-f0a64000-bacd-11e9-94ba-d12303a8ec9f.png)

**Comment by Muehe** [comment]
There are two ways to download, neither one needs renaming.

1. Stable releases: You have folder `Questie` and inside is a file `Questie.toc`
2. Current development: You have folder `QuestieDev-master` and inside is a file `QuestieDev-master.toc`

Please delete the folder and re-download.

**Comment by Muehe** [comment]
P.S. feel free to ask for further help here, don't mind the issue being closed.

**Comment by cmcaulay** [comment]
Thanks!!  That was the problem.  -master needed to stay in the directory name and the .toc filename for the dev version.

**Comment by Muehe** [comment]
Happy to help. FYI you can track updates here: https://github.com/AeroScripts/QuestieDev/commits/master

Just re-download from the same link you used and replace the existing folder and it will be updated.
