### ISSUE TITLE
AddToBlizOptions

### ISSUE THREAD

**Issue by Zetaprime82** [AeroScripts/QuestieDev#629]
Message: Interface\AddOns\Questie\Questie.lua:998: attempt to call method 'AddToBlizOptions' (a nil value)
Time: Sat Aug 10 16:00:53 2019
Count: 1
Stack: Interface\AddOns\Questie\Questie.lua:998: attempt to call method 'AddToBlizOptions' (a nil value)
Interface\AddOns\Questie\Questie.lua:998: in function <Interface\AddOns\Questie\Questie.lua:952>
[C]: ?
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:498: in function `InitializeAddon'
...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:613: in function <...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>

Locals: <none>

**Comment by sinkda** [comment]
This seems to be an error with the ACE Library.  What version of Questie are you using and what other addons do you have installed?  Seems someone may have edited the ace addon and modifying the object before questie loads.

**Comment by Zetaprime82** [comment]
Here is the list of addons i use for Classic WoW

MoveAnnyThing
Prat 3.0
Vendor Price
WeakAuras 2
Z-Perl Unit Frames
Dominos
DBM
Btex/CABSkins
Coordinates by Tom Cats Tours
TitanClassic (TitanPanel)
SimpleMap
OmniCC
Details

**Comment by Zetaprime82** [comment]
I have allso made a post the details addon site for the same error since it seems to be the details who sending the errors

**Comment by BreakBB** [comment]
Please try again. We didn't have any similar reports
