### ISSUE TITLE
Can you make it an extra option to show quests that are too low level (grey)?

### ISSUE THREAD

**Issue by teddygdev** [AeroScripts/QuestieDev#63]
Hey, I'm doing quests for the lore and by the time I get to some zones I am too high level to have the golden (!) appear over the questgivers, and questie also hides the ones that I am too high level for. I have to talk to absolutely every person in a town to make sure I didn't miss any quest pickups.

Can you make it so that there is an extra option to turn off and on low level quests?
Thanks for this addon, it is absolutely amazing!

**Comment by Logonz** [comment]
This is acually a feature i myself want so i will try make it happen after 1.1 is released

**Comment by AeroScripts** [comment]
It would be really easy to implement, the data/code is all already there

**Comment by AeroScripts** [comment]
Will implement this very soon

**Comment by AeroScripts** [comment]
Sorry this has taken so long, lots of stuff was on the table. This feature will be included in 2.1.x for sure. (Should be out very soon)

**Comment by AeroScripts** [comment]
After a ridiculously long time this is now top priority, sorry it took so long guys...
