### ISSUE TITLE
Questie DEVELOP chat messages

### ISSUE THREAD

**Issue by RoyBoy432** [AeroScripts/QuestieDev#630]
Is there any way to turn off the chat messages that Questie posts? For example, upon looting a quest item, Questie posts 3 DEVELOP lines to chat--- see screenshot
![20190810_142427](https://user-images.githubusercontent.com/21083418/62825493-9f07bf00-bb7a-11e9-8e9a-2a2ee8c297c2.JPG)

Could an option be added to turn off these messages, perhaps while keeping bigger-picture DEVELOP messages (for example, ones upon quest completions)? The constant DEVELOP messages become "spam"y quickly in certain areas.

**Comment by sinkda** [comment]
You have the debug option checked in the advanced menu.  go to the menu via the minimap icon or /questie. go to the last tab and uncheck debug mode.

**Comment by RoyBoy432** [comment]
Oh dang! Apologies for the seriously noob question in this case... I did look for any "let Questie post to chat or not" options but I didn't consider the debug option. Thanks for the quick fix, mate.
