### ISSUE TITLE
Persistent ! icons

### ISSUE THREAD

**Issue by Roeshambo** [AeroScripts/QuestieDev#631]
Not a terribly pressing issue. When running into Org with my map open, one of the exclamation points for a quest in Razor Hill remained on the screen when the map was closed. Required a reload to get rid of. This is with "SimpleMap" addon installed, though not sure if related. No Lua errors. This is easily recreated. Zone out of org (says Left Trade), open map and run back into org, close map.

![image](https://user-images.githubusercontent.com/6285297/62828656-5c150e00-bbb1-11e9-83d4-039b015daf87.png)
![image](https://user-images.githubusercontent.com/6285297/62828661-70f1a180-bbb1-11e9-94f4-3868cd4c9009.png)

**Comment by AeroScripts** [comment]
This is on 4.0.9? It's likely that /reload will temporarily clean this up, but we'll need to test with smplemap to fix it properly

**Comment by Roeshambo** [comment]
Yes it's 4.0.9. And it seems the map doesn't need to be opened while zoning into Org. It seems simply zoning will make the point appear and disappear:

In Durotar:
![image](https://user-images.githubusercontent.com/6285297/62840191-fc277180-bc5b-11e9-9a60-2ea87252aa9b.png)

Take one step to the left into Org:
![image](https://user-images.githubusercontent.com/6285297/62840194-0d707e00-bc5c-11e9-9a9d-e56c12ad875d.png)

Take one step to the right back into Durotar:
![image](https://user-images.githubusercontent.com/6285297/62840198-17927c80-bc5c-11e9-9c75-3f16aeca01cd.png)

I only have the 1 ! on my Durotar map atm so not sure if it effects all icons or maybe just the !s. 
With SimpleMap turned off, it does not occur (may actually be a bug with SimpleMap not hiding all children).
Also it does not occur if the map has never been opened in Durotar.

**Comment by AeroScripts** [comment]
Hmm that's very strange, well thanks for posting ill definitely have to check this out. It may be something we can prevent on our end, even if it is a bug with simplemap

**Comment by BreakBB** [comment]
@Roeshambo Is this still an issue?
