### ISSUE TITLE
Quests Missing: Finding the Antidote(813)

### ISSUE THREAD

**Issue by n0xh** [AeroScripts/QuestieDev#632]
Hi,

Last night I completed this quest, but questie isn't syncing with my client. I will say that last night during this quest my timer ran out. I dropped the quest and had to claim it again to complete it.

I do not have exact replication steps, but do need to know how to get Questie and my client to sync. This is for Vanilla Wow.

Thanks,

**Comment by PMizer** [comment]
Same issue

**Comment by gdestree** [comment]
same

**Comment by AeroScripts** [comment]
This is an AAP issue I think

**Comment by BreakBB** [comment]
Have a look at [the FAQ](https://github.com/AeroScripts/QuestieDev/wiki/FAQ-for-Classic-(1.13)#9-i-see-a-message-saying-quest-missing-and-cant-get-rid-of-it). This is an issue with AAP
