### ISSUE TITLE
Other languages support 

### ISSUE THREAD

**Issue by bmagic** [AeroScripts/QuestieDev#633]
I wanted to try questie with the French client of the game. But it seems that some quests are missing.

Client: 4.0.9

Here is the French version:
![WoWScrnShot_081119_100707](https://user-images.githubusercontent.com/1854422/62831542-6969e100-bc21-11e9-8ff4-63a009405e25.jpg)

Here is the English version:
![WoWScrnShot_081119_100609](https://user-images.githubusercontent.com/1854422/62831540-6242d300-bc21-11e9-8662-9896c4076946.jpg)

In the screenshots the supported quests are:
- The Haunted Mills : Les Moulins Hantés
- A New Plague : Une Peste nouvelle
- The Lich's Identity : Le Nom de la Liche

The quests that does not work
- The Mills Overrun  : La chute des moulins
- Deaths in the Family : Morts dans la Famille
- At War With The Scarlet Crusade : En Guerre avec la Croisade écarlate

An idea of what might prevent some quests from working ?

**Comment by bmagic** [comment]
I try to debug it I found an error on the missing quest : 
- Error finding entry ID for objective item [French Name] 

![WoWScrnShot_081119_102853](https://user-images.githubusercontent.com/1854422/62831629-
dd58b900-bc22-11e9-804e-8addac5ff417.jpg)

**Comment by bmagic** [comment]
Ok I found it, you get the string description from API_GetQuestLogLeaderBoard and you compare with  the itemDB.lua. 
In my case the description is in French & the DB in English. 

It's works on some quest because they have only one objective.

Have you plan to export others languages ?

**Comment by bmagic** [comment]
I have found a temp solution : https://github.com/AeroScripts/QuestieDev/pull/637

**Comment by borisBelloc** [comment]
thanks for creating the issue, I came here for the same thing, "addon not working with the french client"; if I can help by doing something for log or test, let me know.
