### ISSUE TITLE
Mac Mojave AceLibrary.lua:301: 'setn' is obsolete

### ISSUE THREAD

**Issue by BrendanJackson** [AeroScripts/QuestieDev#635]
I haven't played WoW in a decade so this may be improper setup on my end. I am on MacOS 10.14.5 and I'm getting 33 pages of lua errors

`Message: ...rface\AddOns\!Questie\Libs\AceLibrary\AceLibrary.lua:301: 'setn' is obsolete
Time: Sun Aug 11 06:55:59 2019
Count: 1
Stack: ...rface\AddOns\!Questie\Libs\AceLibrary\AceLibrary.lua:301: 'setn' is obsolete
[C]: ?
...rface\AddOns\!Questie\Libs\AceLibrary\AceLibrary.lua:301: in function <...rface\AddOns\!Questie\Libs\AceLibrary\AceLibrary.lua:298>
...rface\AddOns\!Questie\Libs\AceLibrary\AceLibrary.lua:550: in function `Register'
...rface\AddOns\!Questie\Libs\AceLibrary\AceLibrary.lua:751: in main chunk

Locals: (*temporary) = <table> {
 GetInstance = <function> defined @Interface\AddOns\!Questie\Libs\AceLibrary\AceLibrary.lua:475
 IterateLibraries = <function> defined @Interface\AddOns\!Questie\Libs\AceLibrary\AceLibrary.lua:690
 Register = <function> defined @Interface\AddOns\!Questie\Libs\AceLibrary\AceLibrary.lua:523
 HasInstance = <function> defined @Interface\AddOns\!Questie\Libs\AceLibrary\AceLibrary.lua:448
 IsNewVersion = <function> defined @Interface\AddOns\!Questie\Libs\AceLibrary\AceLibrary.lua:423
 positions = <table> {
 }
 libs = <table> {
 }
}
(*temporary) = 0
`

`Message: ...terface\AddOns\!Questie\Libs\AceOO-2.0\AceOO-2.0.lua:17: AceOO-2.0 requires AceLibrary.
Time: Sun Aug 11 06:55:59 2019
Count: 1
Stack: ...terface\AddOns\!Questie\Libs\AceOO-2.0\AceOO-2.0.lua:17: AceOO-2.0 requires AceLibrary.
[C]: in function `error'
...terface\AddOns\!Questie\Libs\AceOO-2.0\AceOO-2.0.lua:17: in main chunk

Locals: (*temporary) = "AceOO-2.0 requires AceLibrary."
`

`Message: ...e\AddOns\!Questie\Libs\AceEvent-2.0\AceEvent-2.0.lua:17: AceEvent-2.0 requires AceLibrary
Time: Sun Aug 11 06:55:59 2019
Count: 1
Stack: ...e\AddOns\!Questie\Libs\AceEvent-2.0\AceEvent-2.0.lua:17: AceEvent-2.0 requires AceLibrary
[C]: in function `error'
...e\AddOns\!Questie\Libs\AceEvent-2.0\AceEvent-2.0.lua:17: in main chunk

Locals: (*temporary) = "AceEvent-2.0 requires AceLibrary"
`

`Message: ...e\AddOns\!Questie\Libs\AceAddon-2.0\AceAddon-2.0.lua:17: AceAddon-2.0 requires AceLibrary.
Time: Sun Aug 11 06:55:59 2019
Count: 1
Stack: ...e\AddOns\!Questie\Libs\AceAddon-2.0\AceAddon-2.0.lua:17: AceAddon-2.0 requires AceLibrary.
[C]: in function `error'
...e\AddOns\!Questie\Libs\AceAddon-2.0\AceAddon-2.0.lua:17: in main chunk

Locals: (*temporary) = "AceAddon-2.0 requires AceLibrary."
`

`Message: ...terface\AddOns\!Questie\Libs\AceDB-2.0\AceDB-2.0.lua:17: AceDB-2.0 requires AceLibrary
Time: Sun Aug 11 06:55:59 2019
Count: 1
Stack: ...terface\AddOns\!Questie\Libs\AceDB-2.0\AceDB-2.0.lua:17: AceDB-2.0 requires AceLibrary
[C]: in function `error'
...terface\AddOns\!Questie\Libs\AceDB-2.0\AceDB-2.0.lua:17: in main chunk

Locals: (*temporary) = "AceDB-2.0 requires AceLibrary"
`

`Message: ...ace\AddOns\!Questie\Libs\AceHook-2.1\AceHook-2.1.lua:17: AceHook-2.1 requires AceLibrary.
Time: Sun Aug 11 07:11:42 2019
Count: 1
Stack: ...ace\AddOns\!Questie\Libs\AceHook-2.1\AceHook-2.1.lua:17: AceHook-2.1 requires AceLibrary.
[C]: in function `error'
...ace\AddOns\!Questie\Libs\AceHook-2.1\AceHook-2.1.lua:17: in main chunk

Locals: (*temporary) = "AceHook-2.1 requires AceLibrary."
`

`Message: ...AddOns\!Questie\Libs\AceLocale-2.2\AceLocale-2.2.lua:17: AceLocale-2.2 requires AceLibrary.
Time: Sun Aug 11 07:11:42 2019
Count: 1
Stack: ...AddOns\!Questie\Libs\AceLocale-2.2\AceLocale-2.2.lua:17: AceLocale-2.2 requires AceLibrary.
[C]: in function `error'
...AddOns\!Questie\Libs\AceLocale-2.2\AceLocale-2.2.lua:17: in main chunk

Locals: (*temporary) = "AceLocale-2.2 requires AceLibrary."
`

`Message: ...ace\AddOns\!Questie\Libs\AceComm-2.0\AceComm-2.0.lua:17: AceComm-2.0 requires AceLibrary
Time: Sun Aug 11 07:11:42 2019
Count: 1
Stack: ...ace\AddOns\!Questie\Libs\AceComm-2.0\AceComm-2.0.lua:17: AceComm-2.0 requires AceLibrary
[C]: in function `error'
...ace\AddOns\!Questie\Libs\AceComm-2.0\AceComm-2.0.lua:17: in main chunk

Locals: (*temporary) = "AceComm-2.0 requires AceLibrary"
`

`Message: ...dOns\!Questie\Libs\AceConsole-2.0\AceConsole-2.0.lua:18: AceConsole-2.0 requires AceLibrary.
Time: Sun Aug 11 07:11:42 2019
Count: 1
Stack: ...dOns\!Questie\Libs\AceConsole-2.0\AceConsole-2.0.lua:18: AceConsole-2.0 requires AceLibrary.
[C]: in function `error'
...dOns\!Questie\Libs\AceConsole-2.0\AceConsole-2.0.lua:18: in main chunk

Locals: (*temporary) = "AceConsole-2.0 requires AceLibrary."
`

`Message: ...Questie\Libs\AceModuleCore-2.0\AceModuleCore-2.0.lua:17: AceModuleCore-2.0 requires AceLibrary
Time: Sun Aug 11 07:11:42 2019
Count: 1
Stack: ...Questie\Libs\AceModuleCore-2.0\AceModuleCore-2.0.lua:17: AceModuleCore-2.0 requires AceLibrary
[C]: in function `error'
...Questie\Libs\AceModuleCore-2.0\AceModuleCore-2.0.lua:17: in main chunk

Locals: (*temporary) = "AceModuleCore-2.0 requires AceLibrary"
`

`Message: ...ace\AddOns\!Questie\Libs\Dewdrop-2.0\Dewdrop-2.0.lua:15: Dewdrop-2.0 requires AceLibrary
Time: Sun Aug 11 07:11:42 2019
Count: 1
Stack: ...ace\AddOns\!Questie\Libs\Dewdrop-2.0\Dewdrop-2.0.lua:15: Dewdrop-2.0 requires AceLibrary
[C]: in function `error'
...ace\AddOns\!Questie\Libs\Dewdrop-2.0\Dewdrop-2.0.lua:15: in main chunk

Locals: (*temporary) = "Dewdrop-2.0 requires AceLibrary"
`

`Message: ...ns\!Questie\Libs\Babble-Zone-2.2\Babble-Zone-2.2.lua:15: Babble-Zone-2.2 requires AceLibrary
Time: Sun Aug 11 07:11:42 2019
Count: 1
Stack: ...ns\!Questie\Libs\Babble-Zone-2.2\Babble-Zone-2.2.lua:15: Babble-Zone-2.2 requires AceLibrary
[C]: in function `error'
...ns\!Questie\Libs\Babble-Zone-2.2\Babble-Zone-2.2.lua:15: in main chunk

Locals: (*temporary) = "Babble-Zone-2.2 requires AceLibrary"
`

`Message: ...ns\!Questie\Libs\Babble-Boss-2.2\Babble-Boss-2.2.lua:15: Babble-Boss-2.2 requires AceLibrary
Time: Sun Aug 11 07:11:42 2019
Count: 1
Stack: ...ns\!Questie\Libs\Babble-Boss-2.2\Babble-Boss-2.2.lua:15: Babble-Boss-2.2 requires AceLibrary
[C]: in function `error'
...ns\!Questie\Libs\Babble-Boss-2.2\Babble-Boss-2.2.lua:15: in main chunk

Locals: (*temporary) = "Babble-Boss-2.2 requires AceLibrary"
`

`Message: [string "Questie:OnUpdate"]:1: attempt to call method 'OnUpdate' (a nil value)
Time: Sun Aug 11 07:16:18 2019
Count: 7504
Stack: [string "Questie:OnUpdate"]:1: attempt to call method 'OnUpdate' (a nil value)
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: self = Questie {
 FlyoutBorderShadow = QuestieFlyoutBorderShadow {
 }
 HotKey = QuestieHotKey {
 }
 SpellHighlightAnim = <unnamed> {
 }
 NewActionTexture = <unnamed> {
 }
 cooldown = QuestieCooldown {
 }
 AutoCastShine = QuestieShine {
 }
 Border = QuestieBorder {
 }
 Flash = QuestieFlash {
 }
 AutoCastable = <unnamed> {
 }
 SpellHighlightTexture = <unnamed> {
 }
 Count = QuestieCount {
 }
 Name = QuestieName {
 }
 0 = <userdata>
 FlyoutArrow = QuestieFlyoutArrow {
 }
 icon = QuestieIcon {
 }
 FlyoutBorder = QuestieFlyoutBorder {
 }
}
elapsed = 0.038000
(*temporary) = nil
(*temporary) = QuestieLua {
 FlyoutBorderShadow = QuestieLuaFlyoutBorderShadow {
 }
 CheckPlayerInventory = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:208
 AstroGetFinishedQuests = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:723
 NewActionTexture = <unnamed> {
 }
 SanitisedQuestLookup = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:1035
 lastCollapsedCount = 0
 Border = QuestieLuaBorder {
 }
 Flash = QuestieLuaFlash {
 }
 OnLoad_QuestEvents = <function> defined @Interface\AddOns\!Questie\Questie.lua:225
 getQuestHash = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:1052
 icon = QuestieLuaIcon {
 }
 IsQuestFinished = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:1113
 AutoCastable = <unnamed> {
 }
 MarkQuestAsFinished = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:94
 CreateMinimapButton = <function> defined @Interface\AddOns\!Questie\Modules\QuestieGUI.lua:5
 collapsedThisRun = false
 ParseQuestLoot = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:186
 UpdateGameClientCache = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:292
 UpdateQuests = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:492
 HotKey = QuestieLuaHotKey {
 }
 LoadEQL3Fix = <function> defined @Interface\AddOns\!Questie\Modules\QuestieTracker.lua:693
 AstroGetQuestObjectives = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:795
 finishAndRecurse = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:234
 GetAvailableQuestHashes = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:1194
 AstroGetAllCurrentQuestHashesAsMeta = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:673
 RemoveUniqueSuffix = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:1042
 UpdateQuestIds = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:1006
 GetQuestIdFromHash = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:975
 AutoCastShine = QuestieLuaShine {
 }
 AstroGetAllCurrentQuestHashes = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:632
 FlyoutBorder = QuestieLuaFlyoutBorder {
 }
 SetupDefaults = <function> defined @Interface\AddOns\!Questie\Questie.lua:18
 CheckDefaults = <function> defined @Interface\AddOns\!Questie\Questie.lua:66
 SpellHighlightAnim = <unnamed> {
 }
 UpdateQuestInZone = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:533
 OnLoad = <function> defined @Interface\AddOns\!Questie\Questie.lua:204
 BlockTranslations = <function> defined @Interface\AddOns\!Questie\Questie.lua:195
 0 = <userdata>
 SpellHighlightTexture = <unnamed> {
 }
 CheckQuestLog = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:340
 OnQuestProgress = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:74
 DetectQuestItem = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:164
`

`Message: Interface\AddOns\!Questie\Modules\QuestieTracker.lua:59: attempt to index global 'QuestieConfig' (a nil value)
Time: Sun Aug 11 07:16:34 2019
Count: 7954
Stack: Interface\AddOns\!Questie\Modules\QuestieTracker.lua:59: attempt to index global 'QuestieConfig' (a nil value)
Interface\AddOns\!Questie\Modules\QuestieTracker.lua:59: in function <Interface\AddOns\!Questie\Modules\QuestieTracker.lua:49>

Locals: (*temporary) = nil
(*temporary) = "ShaguQuest"
(*temporary) = "attempt to index global 'QuestieConfig' (a nil value)"
`

`Message: Interface\AddOns\!Questie\Modules\QuestieArrow.lua:18: attempt to index local 'm' (a nil value)
Time: Sun Aug 11 07:16:43 2019
Count: 297
Stack: Interface\AddOns\!Questie\Modules\QuestieArrow.lua:18: attempt to index local 'm' (a nil value)
Interface\AddOns\!Questie\Modules\QuestieArrow.lua:18: in function `GetPlayerFacing'
Interface\AddOns\!Questie\Modules\QuestieArrow.lua:376: in function <Interface\AddOns\!Questie\Modules\QuestieArrow.lua:368>

Locals: p = Minimap {
 0 = <userdata>
 timer = 0
}
m = nil
(*temporary) = MiniMapTrackingFrame {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "attempt to index local 'm' (a nil value)"
`

I included the errors at the ends of the report, WoW seems to Truncate these so if you need more information I'll do what I can, having said that, the stress test does end tomorrow. I saw an issue referring to astrolabe having conflicts with another addon but at this moment the only addon I have installed is questie. I haven't managed to get an addon on my mac to work in WoW yet so there may just be something I am unaware of.

Path is ⁩ ▸ ⁨Applications⁩ ▸ ⁨World of Warcraft⁩ ▸ ⁨_classic_⁩ ▸ ⁨Interface⁩ ▸ ⁨AddOns⁩ ▸ ⁨ !Questie

**Comment by drejjmit** [comment]
You are installing the vanilla version in classic client. Download the classic version here: https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by Muehe** [comment]
Assumed solved, please re-open or create a new issue if you still have problems.
