### ISSUE TITLE
Questie for 1.13 client quest issue: Guarded Thunder Ale Barrel

### ISSUE THREAD

**Issue by hammerface** [AeroScripts/QuestieDev#641]
Guarded Thunder Ale Barrel is a quest in Dwarf starting zone that is not being treated properly by Questie. 

It is a optional quest which allows you to complete another quest: Unguarded Thunder Ale Barrel.

If someone has already complete the Guarded Thunder Ale Barrel quest recently, you are able to complete the Unguarded quest without doing the Guarded quest. After doing so, you are not able to do the Guarded quest, but it remains on the map and can't be removed.

I think Guarded Thunder Ale Barrel should be auto completed if Unguarded Thunder Ale Barrel is completed in order to avoid this issue.

**Comment by AeroScripts** [comment]
Thanks for posting, this should be relatively straightforward to fix ill try to get a commit out later today
