### ISSUE TITLE
/reload unloads icons

### ISSUE THREAD

**Issue by repsejnworb** [AeroScripts/QuestieDev#642]
Seems like `/reload` unloads icons (rendering only green squares).

Got to be frank, saw this very late during stresstests-life and didn't have time to investigate further.
I was playing around with different CVars (the one I remember testing when this happened was `violenceLevel`).

So unsure if just a `/reload` is enough or a `/console SOMECVAR VALUE` into `/reload` is needed.

(Also did not have `scriptErrors` enabled. Sorry)

**Comment by AeroScripts** [comment]
Is this happening on v4.0.9? That was a problem with earlier builds on the stress test, but 4.0.9 should take care of it

**Comment by repsejnworb** [comment]
I was not running 4.0.9, so closing this (saw your changes).

Cheers mate.
