### ISSUE TITLE
Quest level range description

### ISSUE THREAD

**Issue by Nock-git** [AeroScripts/QuestieDev#645]
Hi,
I'm currently working on the translation into German, whereby I noticed a trifle. The description of the Level range in which the Quest should be shown seems screwed.  Please check minLevelFilter and maxLevelFilter and their description.

**Comment by sinkda** [comment]
Are you saying the in-game or the translation?  And are you using the latest translation version from enUS or the version in deDE? I checked both and the wording seemed off in the deDE but was fixed (changed) in the enUS version of the translation.

**Comment by Nock-git** [comment]
I'm working with the most current source code so it's in the appropriate files. But they are both the same for this section:

deDE:
    ['LOWLEVEL_BELOW'] = "< Show below level",
    ['LOWLEVEL_BELOW_DESC'] = "How many levels below your character to show. ( Default: %s )",
    ['LOWLEVEL_ABOVE'] = "Show below level >",
    ['LOWLEVEL_ABOVE_DESC'] = "How many levels above your character to show. ( Default: %s )",

enUS:
    ['LOWLEVEL_BELOW'] = "< Show below level",
    ['LOWLEVEL_BELOW_DESC'] = "How many levels below your character to show. ( Default: %s )",
    ['LOWLEVEL_ABOVE'] = "Show above level >",
    ['LOWLEVEL_ABOVE_DESC'] = "How many levels above your character to show. ( Default: %s )",

In my opinion the word below and above have to change in both Descriptions:

    ['LOWLEVEL_BELOW'] = "< Show below level",
    ['LOWLEVEL_BELOW_DESC'] = "How many levels above your character to show. ( Default: %s )",
    ['LOWLEVEL_ABOVE'] = "Show above level >",
    ['LOWLEVEL_ABOVE_DESC'] = "How many levels below your character to show. ( Default: %s )",

Maybe it's just missleading in the code and every things is fine ingame. Sorry cant's check because I'm waiting for classic xD and don't have an subscription now.

**Comment by sinkda** [comment]
So I think you are reading it as "show quests above level 10, and below level 20" but it's "show quests X levels above mine, and Y levels below mine"

**Comment by Nock-git** [comment]
When writing the following lines, I realized everything:

Let me point out my misunderstanding: 
If the player is level 15 LOWLEVEL_ABOVE (Show above level >) is maybe 20 (absolute), but the description reads it as the relative value 5

Okay so that's my fault both are relativ and everything seems right. 
Thank you for your help!
