### ISSUE TITLE
Unexpected Symbol

### ISSUE THREAD

**Issue by Demethir** [AeroScripts/QuestieDev#646]
I've installed about a dozen versions of Questie on the Elysium project and none work at all.  It shows up in the addon list as "Questie v4.0.9 Beta".  The in-game error reads:

...nterface/AddOns/Questie/Libs/CallbackHandler- 1.0/CallbackHandler- 1.0.lua:90: unexpected symbol near `...'

**Comment by AeroScripts** [comment]
You want 3.7.1, the last 1.12 relese. 4.x is for classic (1.13) which is very different

https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.1 here's a link

**Comment by Muehe** [comment]
Assumed solved, please re-open or create a new issue if you still have problems.
