### ISSUE TITLE
Add Russian localization

### ISSUE THREAD

**Issue by AvicusDelacroix** [AeroScripts/QuestieDev#649]
I have translated the addon to the most native Russian, omggga made a review and checked it, the PR is here: https://github.com/AeroScripts/QuestieDev/pull/647

**Comment by AvicusDelacroix** [comment]
Hmm I can not add a label "Non English" as required...

**Comment by AeroScripts** [comment]
I will look into all the pull requests at launch, thanks for your help <3

I think github only allows maintainers to add tags, not sure if we can change that

**Comment by AvicusDelacroix** [comment]
Can't you take the names from UI, like when you use %t ingame etc?

**Comment by BreakBB** [comment]
Fixed with #680
