### ISSUE TITLE
Questinfo tooltips in german client not working - ClassicWoW

### ISSUE THREAD

**Issue by Duffboon** [AeroScripts/QuestieDev#652]
Hello,

when playing with german localization, the questinfo are not shown in the tooltip of a mob.
its only working with text language: english

**Comment by BreakBB** [comment]
Localization is not included yet but well be soon. It is quite high on the priority list.

**Comment by bmagic** [comment]
If you try the master version, it will work. This is not perfect and some objectives can be reversed on the map but it allows you to display all quests.

**Comment by bmagic** [comment]
https://github.com/AeroScripts/QuestieDev/archive/master.zip
Extract into World of Warcraft\_classic_\Interface\AddOns\QuestieDev-master

**Comment by Duffboon** [comment]
thanks for the help.
It's still just working under english client. (Quest info in mob tooltips)
But we will see what that referenced issue will bring us.
Till a solution im just playing it in english.

**Comment by BreakBB** [comment]
Fixed with #680
