### ISSUE TITLE
The temple of the moon shows without being availble

### ISSUE THREAD

**Issue by magp3** [AeroScripts/QuestieDev#654]
See the screenshot. Can't take the quest but it shows on minimap

![WoWScrnShot_082719_205800](https://user-images.githubusercontent.com/17042992/63773377-9dc1ea80-c90d-11e9-96ba-dce6de5d15f6.jpg)

**Comment by BreakBB** [comment]
This is the wowhead link for it https://classic.wowhead.com/quest=2519/the-temple-of-the-moon

No requirements listed except the level

**Comment by bmagic** [comment]
I just looked at the DB it seems correct the nextQuestInChain is there.

Does a small /reload solve the problem?

**Comment by bmagic** [comment]
@BreakBB Look in the chat : Quest accepted : Tears of the Moon.

I think he just skipped the first quest, but it shouldn't show up.

**Comment by magp3** [comment]
@bmagic Thanks for the response. Oh just noticed the part about where I already accepted it. I guess I just got it directly from the priestess.
