### ISSUE TITLE
Questie with modern questwatch breaks the mqw addon.

### ISSUE THREAD

**Issue by SneakySphynx** [AeroScripts/QuestieDev#655]
Modern QuestWatch works byitself, And same with Questie.

But together they bug out.

**Comment by BreakBB** [comment]
@MysticalOS
No, the quest tracker of Questie is simply not implemented in the Classic version yet.

**Comment by BreakBB** [comment]
Any news on this @AeroScripts ?

**Comment by MysticalOS** [comment]
I don't have any real problems between the two, now that I know desync is caused by something else.

**Comment by BreakBB** [comment]
Please report if this is still an issue!
