### ISSUE TITLE
Non-english NPC and quest names

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#659]
There are some related issues already like #652 but I wanted to create a general issue about the topic, so we can keep track of the data we have

Currently we have the data for:
- English
- German

Partial data is available for many languages on wowhead, but lots is still missing. Some data is available in mangos forks

**Comment by BreakBB** [comment]
With the release of Classic I recognize that wowhead is filling up pretty good.

Most likely I can submit the data I scraped using the [Wowhead Scraper](https://github.com/BreakBB/wowhead_scraper) I built.

Those will include (in a first blob):

- English
- German
- French
- Spanish

And the information inside are:

- NPC names
- Quest titles
- Quest objectives
- Quest description

**Comment by merasil** [comment]
> There are some related issues already like #652 but I wanted to create a general issue about the topic, so we can keep track of the data we have
> 
> Currently we have the data for:
> 
> * English
> * German
> 
> Partial data is available for many languages on wowhead, but lots is still missing. Some data is available in mangos forks

U say tooltips should work for the german version? Cause it does not work for me. I just have Questie as addon. Is there a way to get the english (working) tt's with german client?

**Comment by omggga** [comment]
Good idea btw.

On non-english clients questie tooltip is not working even some of quests are on map and with english name.
Is it possible to make a temporarily feature to show in tooltip mobs and items dropped from mobs in global eng language, if localization doesnt exist yet?

**Comment by omggga** [comment]
Oh i found https://github.com/AeroScripts/QuestieDev/pull/680, sorry

**Comment by BreakBB** [comment]
Yes, this issue can most likely be closed because of #680
