### ISSUE TITLE
Add support for available quests again for 1.1

### ISSUE THREAD

**Issue by Logonz** [AeroScripts/QuestieDev#66]
Currently disabled, handling needs to be added as these notes are of a special type.

**Comment by Logonz** [comment]
Aero / Schaka if you write the logic and just add --"Add note here" ill do the note implementation into astrolabe!

**Comment by Schaka** [comment]
Aero did the AvailableQuests logic, so he should probably do that. I will take care of the tracker frame this weekend (that's the plan, at least).

**Comment by Sparh4wk** [comment]
Hi, I know u dont want us to, but Im trying latest commit.. using with metamaps and it works great so far.. just one thing.. is it possible to turn this off before you will fix it with other commits?
![ng9kwyx](https://cloud.githubusercontent.com/assets/7014826/7314923/8778589a-ea69-11e4-94a5-101c28980a82.png)

**Comment by Logonz** [comment]
Haha, the clock was 5am and i just added a good tooltip hook :P Fixed now!

**Comment by Sparh4wk** [comment]
just another error code right after quest pickup.. this time even with quest :)
![ng9kwyx](https://cloud.githubusercontent.com/assets/7014826/7319713/b78bb9ea-ea97-11e4-9fc9-0b3f00faaaef.png)

**Comment by Logonz** [comment]
Hmmmmmm, Nice that you put the quest in, will look into it now!

**Comment by Logonz** [comment]
Reproduced the error, but only once for some reason... added a safeguard for it tho!

**Comment by Sparh4wk** [comment]
great!! added :) btw after last update cant see objectives for two quests that I just added (Fuel for the Zapping and Zapped Giants) will report later  btw is it possible to log that questiedebug into txt file etc?

**Comment by Sparh4wk** [comment]
ok, just updated.. after restart and updated to latest commits, objectives are on minimap and some questie hook is even on tooltip
![1](https://cloud.githubusercontent.com/assets/7014826/7320993/0befdc8e-eaa0-11e4-83ca-ee8bda4b0d45.png)
![2](https://cloud.githubusercontent.com/assets/7014826/7320994/0bf1190a-eaa0-11e4-8459-5f7fdfdf8f23.png)

**Comment by Logonz** [comment]
I've been working on those as we speak!
Im going to run there and check so they work now.

**Comment by Sparh4wk** [comment]
sry for late response, was afk. yes, it seems much better and faster.

**Comment by Logonz** [comment]
Sure, add me as snorci on skype, (will edit out this as soon as you see it so tell me)
or Logon on ally (nost)

**Comment by Sparh4wk** [comment]
u can edit it out.. installing skype :)
