### ISSUE TITLE
Guarded Thunder Ale Barrel

### ISSUE THREAD

**Issue by mortelinnor** [AeroScripts/QuestieDev#662]
The quest "Garded Thunder Ale Barrel" in Dun Morogh (ID: 403) is not properly hidden when you complete the quests "Bitter Rivals" (ID: 310) and  "Return to Marleth" (ID: 311) without completing it (by giving the Thunder Ale directly to Jansen, without clicking the garded barrel).

It should be hidden, since the quest is no longer available after those quests are completed.

**Comment by Dcrielaard** [comment]
I think there might still be a bug with this quest. The quest (ID: 403) still shows as available, but the follow up quests have been completed (ID: 311). 

I checked by copying the contents of corrections.lua inside my game version of corrections.lua

**Comment by Dcrielaard** [comment]
It is fixed now! Thanks a lot

**Comment by arphox** [comment]
Please fix the title to "G**u**arded Thunder Ale Barrel"
It would help people who are searching for this exact phrase

**Comment by Dichotomia** [comment]
Do you plan to make a new release ? (4.0.11?).

**Comment by BreakBB** [comment]
Related to #641
