### ISSUE TITLE
Level 10 warrior quest - Ironband's Compound

### ISSUE THREAD

**Issue by hammerface** [AeroScripts/QuestieDev#663]
In classic warriors can do all 3 of the level 10 warrior quests regardless of their race. I am playing as a human, and the human and night elf quests both were indicated properly by Questie.

The Ironforge quest - Ironband's Compound, is available to me, but it is not being shown on the map by Questie.

I spoke with Aero about this, and he thought that it was probably flagged to be a race locked quest since private servers incorrectly had the quests race locked. If you change it to be available to all alliance races that should probably be good. You might also want to check that the human and night elf quests don't have an incorrect race lock, since I only tested with a human character. Thanks.

**Comment by BreakBB** [comment]
Fixed with 7e33a08c355213d60357b88962ce62628ae72205

**Comment by BreakBB** [comment]
I finally found the time to had a look at this quest and it seems our data looks just fine. The NPC is listed correct and the racelock is open to all Aliiance races.

You did try a `/reload` when you experienced this issue, right?

**Comment by hammerface** [comment]
Hi, I'm pretty sure I tried reloading, but this was 3 weeks ago so I can't remember perfectly. My usual approach before reporting a big was always to reload beforehand, since that tends to fix a lot of problems. Maybe its not related to race lock, but instead you have completing one of the 3 quests marks the other 2 as complete as well? I'm only speculating.

**Comment by BreakBB** [comment]
Could you run the follow commands and see what they return? The only thing left is that you might not require one of the prequests, but I think this is more related to the desync bug, since our data looks fine. Or maybe your level was too high for the quest to display?

`/dump IsQuestFlaggedCompleted(1679)`
`/dump IsQuestFlaggedCompleted(1678)`
`/dump IsQuestFlaggedCompleted(1680)`
`/dump IsQuestFlaggedCompleted(1681)`

**Comment by BreakBB** [comment]
Fixed with 529e93ee9be253a5b4d7b9daac593348472f2e33
