### ISSUE TITLE
Logging into another computer with Questie enabled shows previously completed quests on the map

### ISSUE THREAD

**Issue by im-bryan** [AeroScripts/QuestieDev#667]
Hi there!

Previously completed quests are marked on my minimap when I log in to WoW Classic when playing on a 2nd computer. 

So, I finished a bunch of quests on computer 1. I log into computer 2, and the quests show as both available and in progress on the minimap. The weird thing is –  that's why I'm opening this ticket – if I go into my adventure log, it can actually tell me what quests I have already completed. 

Isn't it then just an easy fix to get that list cached somewhere and update the map so it removes the markers?

**Comment by AeroScripts** [comment]
Hmm, something strange might be doing on with the quest DB. Someone had an issue with that earlier, and we're going to change the logic soon to prevent similar issues in the future 

You can reset questie's history by doing the following chat commands

/run Questie.db.char.complete = {}
/reload

That will make it ask the server for your quest history again

**Comment by bmeulmeester** [comment]
The reset worked, indeed. Curious to see what happened. I just relogged and it had the same effect as my original text, it showed quests I had already done as available. (@im-bryan is also me)

**Comment by Muehe** [comment]
@bmeulmeester In the latest release the desync should be fixed by logging in or using `/reload`. If you still encounter persistent errors with versions 4.0.12 please create a new issue containing the quest names, as it might be incorrect data.

Progression on the general bug will be tracked in #690
