### ISSUE TITLE
map changing, out of proportion to actual Elwynn Forest, Westfall areas

### ISSUE THREAD

**Issue by linda535** [AeroScripts/QuestieDev#669]
Yesterday playing classic - LOVE your Questie, it's helpful! Except when I'm going through Goldshire all day doing quests and the map details (roads, buildings, placenames) disappeared. Once was able to disable and enable Questie that worked for a while. Today, it seems very skewed and looks like all of mid-Eastern Kingdom is on the map without any area borders. The map quest goals are also "off". I'm standing in Goldshire and the map shows Westfall way west, as it is, but shows Westfall quest goals in Redridge Mountains. Again, no roads or placenames showing. I really appreciate your addon, as I'm directionally challenged. Thanks!

**Comment by BreakBB** [comment]
There is currently a bug in Questie which might be responsible for this. But just to male sure it is Questie you should try to disable all other addons.

**Comment by BreakBB** [comment]
Great you solved it! Would be great if you could close this issue then.

**Comment by linda535** [comment]
Great addon, thank you!
