### ISSUE TITLE
Questie not working after server shutdown

### ISSUE THREAD

**Issue by dulud** [AeroScripts/QuestieDev#671]
My questie was working fine until the server shutdown today on the 28th. When I traveled from the Dark Shore to Loch Modan the markers on the map stop working and never came back and then the arrow and the text for objectives also stop working. I tried /reload, game restart, I uninstalled and reinstalled Questie but the addon just doesnt work anymore and i can't figure out why :/

**Comment by BreakBB** [comment]
You should make sure if it is really Questie. Because there currently is not arrow in the Classic version.

Simply turn off all addons except Questie and see if it works.
