### ISSUE TITLE
[Quest] In Favor of the Light (5623)

### ISSUE THREAD

**Issue by Sulmog** [AeroScripts/QuestieDev#672]
Questie tracks this as if it has not been completed when it's completed.

**Comment by BreakBB** [comment]
Did you try to `/reload`?

**Comment by Sulmog** [comment]
Yes

**Comment by BreakBB** [comment]
And it is the same quest with "Speak to Priestess Josetta in Elwynn Forest."?

The thing is Questie askes the Blizzard API for all completed quests so such things shouldn't happen.
