### ISSUE TITLE
[Quest] Mazzranache missing

### ISSUE THREAD

**Issue by l3rahma** [AeroScripts/QuestieDev#674]
Continent: Kalimdor
Zone: Bloodhoof Village, Mulgore
Quest NPC name: Maur Raincaller
Quest NPC location: 47.00,57.07
Quest ID: 766 (Mazzranache)

Missing Exclamation to pick up quest as well as Question mark to turn in quest.

**Comment by AeroScripts** [comment]
This is likely the desync bug, /reload will clear it up until we find a proper fix

I just did this quest today, and it was working fine

**Comment by BreakBB** [comment]
Merging this with #860
