### ISSUE TITLE
When remaking a character that is already levelled up, questie doesnt reset history

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#675]
When a character is deleted and remade with the same name on the same server, questie uses it's internal db.char.complete and doesn't take into account the empty quest log of the new character. 

We should check on login, if db.char.complete doesnt at all match GetQuestsCompleted, reset it. Or maybe there is a better solution

**Comment by BreakBB** [comment]
This should be solved with https://github.com/AeroScripts/QuestieDev/blob/b1b6b60a7fd72217140bf09d593ffe034f96fc5e/Modules/QuestieQuest.lua#L52
