### ISSUE TITLE
"as water cascades" missing interact location

### ISSUE THREAD

**Issue by ssateneth** [AeroScripts/QuestieDev#679]
"as water cascades" is missing interact location on map + minimap for the red crystal after you have the moonwell water tube in darkshore. quest id 4812

**Comment by AeroScripts** [comment]
Thanks for posting these, we'll look through the quest data related issues soon. Currently busy working on the tracker

**Comment by BreakBB** [comment]
The items were missing and therefore Questie wasn't able to recognize that you've got the "Moonwell Water Tube" and finished the quest.
