### ISSUE TITLE
Request: Automatic tracking + more tracking

### ISSUE THREAD

**Issue by Treedot** [AeroScripts/QuestieDev#681]
Not sure if it's possible but auto-tracking of quests and the ability to track more than five would be incredible.

**Comment by BreakBB** [comment]
Questies tracker is not yet ported to the Classic version. The one you see currently ingame is the default one from Blizzard.

It is worked on!

**Comment by Megurine** [comment]
It means that on the world map (not in the right tracker) there is a limit on the display of objectives or quests.

I also think it's the most important thing to do now on the program. (and translation after ^^)

**Comment by ggregoire** [comment]
Alternative: https://www.curseforge.com/wow/addons/auto-track-quests

**Comment by Treedot** [comment]
Thanks for this!
  

  
  

  
  
>

**Comment by BreakBB** [comment]
With Questie v4.0.17+ this is a WIP feature which can be enabled by running:

````
/run Questie.db.char.trackerEnabled = true
/reload
```

@AeroScripts is working heavily on this and I think it will be included fully very soon!

*Most likely* those function will be included in a rightclick menu:
![image](https://user-images.githubusercontent.com/33514570/64554520-e0d38300-d33b-11e9-9a2a-b090379928fb.png)

**Comment by BreakBB** [comment]
Checkout the latest release to get the tracker functionalities!
