### ISSUE TITLE
Chen's Empty Keg

### ISSUE THREAD

**Issue by Akumies** [AeroScripts/QuestieDev#682]
Hello!

I found world drop quest Chnen's Empty Keg, and i did the quest. Still Seeing ! at the Ratchet...

https://i.imgur.com/TZkB2ss.png

It tho says its another same named quest (I need to do diffrent things when i Shif+mouseover it)

**Comment by BreakBB** [comment]
Chen's Empty Keg is a quest chain containing 3 quests https://classic.wowhead.com/quest=819/chens-empty-keg. So maybe you can complete more? Otherwise you should try to `/reload`.

**Comment by Akumies** [comment]
Can't see any quest given from the quest giver...

**Comment by BreakBB** [comment]
So did you just hand in the first quest? Like "Here is the keg"? Or did you do the others as well?

**Comment by AeroScripts** [comment]
if it said you need to do different things (with shift+mouseover) it was probably next step in the chain

**Comment by Akumies** [comment]
i returned first set of "things" after that it didint give me anything... but questie says i need another sets of things (diffrent)

**Comment by BreakBB** [comment]
According to the comments the last quest of this chain is (or used to be) repeatable: https://classic.wowhead.com/quest=822/chens-empty-keg#comments:id=2730856

**Comment by Akumies** [comment]
Yeap, well at least i dont have quest there at all after finishing first "gather things quest"

**Comment by BreakBB** [comment]
So you can't accept the third quest at all?

**Comment by Akumies** [comment]
correct

**Comment by BreakBB** [comment]
Could you run the following commands in your chat to see which of the quests has been marked as complete:

`/dump IsQuestFlaggedCompleted(819)`

`/dump IsQuestFlaggedCompleted(821)`

`/dump IsQuestFlaggedCompleted(822)`

Simply post a screenshot of the chat after you ran the commands.

**Comment by Akumies** [comment]
https://i.imgur.com/Uu1TajC.png

**Comment by BreakBB** [comment]
So if [Brewmaster Drohn](https://classic.wowhead.com/npc=3292/brewmaster-drohn) really has no quest for you, you should open up a ticket to Blizzard. The last quest should be available for you and therefore Questie shows it correctly.

**Comment by Akumies** [comment]
Okay, i send ticket to blizzard... will let you know what they answered.

**Comment by vana-wow** [comment]
What's your level?

According to most sources (e.g. wowhead) the quest requirs level is 11. Some sources (e.g. https://datenbank.classic-wow.org/?quest=822) tell that the required level is 15 ("Benötigt Stufe: 15" [Requires level: 15])

**Comment by Akumies** [comment]
i were lvl 24 when i last time checked does he gives the quest to me.

**Comment by bmagic** [comment]
'm doing my part. Indeed part 3 is not currently available in the game. I don't know if it's intentional or a blizzard omission.
https://eu.forums.blizzard.com/en/wow/t/chens-empty-keg-part-3/77160

**Comment by Akumies** [comment]
https://i.imgur.com/LR4tK9z.png

^ GM answer

**Comment by Scrooloose1** [comment]
Apparently Part 3 of Chen’s Empty Keg has not been included in the European version of WoW Classic due to legal issues with Alcohol, or so a GM told my friend.

**Comment by BreakBB** [comment]
Can you provide any proof of that "legal issues" a GM told your friend about?

We don't have any more information on this than the ticket says, sorry.

**Comment by Scrooloose1** [comment]
I will ask him and get back to you...

**Comment by Scrooloose1** [comment]
Sorry the GM would not give me any information about if the alcohol legal issues are the problem they just replied:

"At the moment since is still under investigation I’ve no details to share with you. We’re aware though that the quest is not in-game.

Keep an eye on the patch notes since all the changes will be posted there.

Should you have any further questions, please do not hesitate to contact us again. "

**Comment by Gogo1951** [comment]
Hey @Akumies ,

Is this still relevant, or can it be closed up?

**Comment by BreakBB** [comment]
I tested this again and was able to accept and complete this quest on a German server:

![image](https://user-images.githubusercontent.com/33514570/71766659-8e2d6080-2f02-11ea-9ae6-fb4fcac15646.png)
