### ISSUE TITLE
Release 4.0.11

### ISSUE THREAD

**Issue by Dichotomia** [AeroScripts/QuestieDev#683]
Hello !

Thanks for your great job.

Have you any plan to release a new version?

I'm interested in a lot of new fixes.

Best regards

**Comment by BreakBB** [comment]
Yes, there will be a 4.0.11 release shortly!

**Comment by AeroScripts** [comment]
Either tonight or tomorrow, just want to test it a bit more to make sure there aren't any bad bugs introduced.

You can use the latest github master if you want to test the latest fixes (that would be helpful actually, they need testing) just don't rename your folder. it should be QuestieDev-master if you download direct from github (download zip option)

**Comment by Dichotomia** [comment]
Ok thank you

**Comment by AeroScripts** [comment]
Fixed as of 12d56ca4c291d684edac1a0b8c5cabeeb971c2f4
