### ISSUE TITLE
Classic Completed Sync

### ISSUE THREAD

**Issue by pyromanci** [AeroScripts/QuestieDev#684]
While the the api function GetQuestsCompleted is not aviable, IsQuestFlaggedCompleted(<quest id>) is.

Is there a chance to add a button to maybe My journey so it takes the "Aviable Quests" and runs their ID's through that function. That way those of us who play on multi PC's can have a quick way to mark quests complete without having to deal with hassle of coping the saved variables around.

**Comment by BreakBB** [comment]
[GetQuestsCompleted](https://wow.gamepedia.com/API_GetQuestsCompleted) is available via the API. Questie heavily relies on it to get the quests a player already finished.

Not sure about the second part though. I think Questie should know which quests are completed even though you switched PCs.

**Comment by pyromanci** [comment]
For the wow classic version it does not. Switching between computers (i
play at home and work) it does not register quests completed when playing
on the other one. I saw an earlier issue from 2018 where it talked about it
not being able to sync like that.

**Comment by AeroScripts** [comment]
You can try /dump GetQuestsCompleted() in game to test, it is available in classic. The problem was with our logic

It should be fixed as of 4697e7af0c81a927321c2c8e271c5ccf365d6435

**Comment by pyromanci** [comment]
It did get mark them completed when i logged in on the second pc this morning. i did get a proper output from the dump.

**Comment by AeroScripts** [comment]
Hopefully it should be good now 🙏
