### ISSUE TITLE
Quest tracker is not moveable

### ISSUE THREAD

**Issue by Rockmaster1** [AeroScripts/QuestieDev#685]
I can't move the quest tracker.
I tried Control + Shift leftclick
Shift +Left
Control + left
Alt + left
middle drag
No option in the menu to unlock either

Additionally you can only track 5 quests.

The quest tracker looks like the default blizzard one to be honest.
Shouldnt it be replace by a special questie one?

My Guildmates confirmed the problem.

**Comment by BreakBB** [comment]
If you have a look at other issues already open and at the README you will see that the tracker (just as the arrow) is not included by Questie yet. It needs to be ported to Classic but should be done by the end of the week.

The tracker you see is the default Blizzard one.

**Comment by Rockmaster1** [comment]
I didnt see that. Thanks for the hint. CLosing the report.
