### ISSUE TITLE
Tirisfal Glade quests showing up after completion

### ISSUE THREAD

**Issue by pyoio** [AeroScripts/QuestieDev#688]
https://classic.wowhead.com/quest=431/candles-of-beckoning

and

https://classic.wowhead.com/quest=410/the-dormant-shade

are both showing on the map despite being completed, I tried a /reload (and `/run Questie.db.char.complete = {}`)

**Comment by BreakBB** [comment]
Related to #638 

The problem with those quests is that they're provided by an object and are repeatable. Thing is that the object can not be clicked once the quest is completed, but `IsQuestFlaggedCompleted` still returns `false`.

I can't think of a solution, can you @AeroScripts ?

**Comment by pyoio** [comment]
I updated to latest version (from github releases) and they went away, should've updated the issue, sorry!

**Comment by BreakBB** [comment]
I'm glad the issue is fixed for you!
