### ISSUE TITLE
Quest stuck in arrow/tracker

### ISSUE THREAD

**Issue by yolomite** [AeroScripts/QuestieDev#689]
Hello,

As a level 10 Orc Warrior; I turned in the "Finding the Antidote" quest and right after turning it in, the Quest Tracker for Questie stopped working and shows "Quests Missing: 816" within the field. The TomTom Arrow even vanished.

I've relogged, /reload and all. Still stuck in this state.

**Comment by AeroScripts** [comment]
Questie doesn't currently have a tracker or arrow :o this must be a different addon

**Comment by yolomite** [comment]
now it all makes sense LoL

**Comment by AeroScripts** [comment]
I'm going to leave this open for now as there have been about 5 other people who reported the same bug on discord

After some digging it seems it's azeroth autopilot.

**Comment by yolomite** [comment]
yes, that is exactly what it is...
