### ISSUE TITLE
Quest stuck on map or missing

### ISSUE THREAD

**Issue by Daefish** [AeroScripts/QuestieDev#690]
I have multiple quest icons showing up in Mulgore, at the starting city after the quests are completed.  I'm a Tauren Shaman on Smoulderthorn (US) if that matters.  

Please let me know if I can submit any further information

Seer Ravenfeather is the specific quest that is showing.  Apparently after reloading wow, several of the icons did disappear.

**Comment by HornyHealz** [comment]
Having the same issue as a Tauren Druid. Only one quest so far. Telling me to pick up Heeding the Call. I am currently lvl10.

**Comment by Muehe** [comment]
We have a desync bug that is temporarily fixed by using `/reload` in the chat, please try this and also make sure you upgrade to the latest version (4.0.12).

Apart from that we have had reports of quest (especially class related ones) staying even after a reload, we will look into that.

**Comment by BreakBB** [comment]
Merging this with #860
