### ISSUE TITLE
show you the level range on the world map in Classic

### ISSUE THREAD

**Issue by leviathan151** [AeroScripts/QuestieDev#691]
Is there any way to show the level range on the world map? If not, can you add please? This is for Classic btw.

**Comment by AeroScripts** [comment]
Currently the config UI slider being capped at 10 levels is unintended. Once we finish off the high priority tasks like the tracker/arrow this will be fixed

**Comment by Muehe** [comment]
Not sure but I think he means level range of the zones.

**Comment by AeroScripts** [comment]
You're right I totally misunderstood sorry about that.

That was a 1.12 feature right? We should be able to add it back

**Comment by leviathan151** [comment]
yes, thats what I mean.

**Comment by Gogo1951** [comment]
Hey @leviathan151 ,

Leatrix Maps (https://www.curseforge.com/wow/addons/leatrix-maps-classic) will do this. Is this still relevant to Questie? If not, can we close it?

**Comment by Gogo1951** [comment]
May be addressed as part of #2498 ; closing as it's not a high priority as a stand alone issue.
