### ISSUE TITLE
Automatic open/close loop

### ISSUE THREAD

**Issue by thadude3** [AeroScripts/QuestieDev#696]
I am not sure if this has been posted. I did a search and didn't find anything.

Steps to Reproduce
1. Have full quest log
2. Go to an NPC that has a new quest as well as a completed quest.
Specifically I was doing the Wharfmaster Dizzywig in Ratchet
3. Click the NPC

Expected Result
Completed quest is done first

Actual Result
It tries to get the new quest and says quest log is full and then closes the window.
You are unable to complete the quest and can't click anything because it closes too fast.

**Comment by Muehe** [comment]
This sounds like an error from another addon. Questie doesn't automatically accept/finish quest.

**Comment by AeroScripts** [comment]
Someone was having this before and it turned out to be classic codex
