### ISSUE TITLE
Being a GuildMaster and setting ranks

### ISSUE THREAD

**Issue by MaxHughes** [AeroScripts/QuestieDev#697]
Getting an issue with Questie when setting ranks in my guild, it creates an error and if i click ignore, then it sets any changes to the guild master. I have to disable questie to make any changes to the guild ranks.

**Comment by Muehe** [comment]
Seems familiar. Please make sure that:

1. you are using the [latest version](https://github.com/AeroScripts/QuestieDev/releases/latest) of Questie (4.0.12 currently).
2. Questie is the only addon enabled when this bug occurs.

Assuming you already created your guild we will try to reproduce on our own.

**Comment by AeroScripts** [comment]
Someone else had this issue when trying to leave a group, but it stopped happening after /reload

Not sure what causes this to happen as questie doesn't touch the guild or group UI

**Comment by BreakBB** [comment]
This issue was been fixed with 1f33a36d7e9c76bd7889d8a1dc3b09abc2bf804b .
