### ISSUE TITLE
"The Principal Source" does not have a tracker

### ISSUE THREAD

**Issue by Prankster855** [AeroScripts/QuestieDev#699]
When doing The Principal Source https://classic.wowhead.com/quest=6122/the-principal-source the mountain is not tagged where you should be going, aswell as the quest npc that finishes.

https://imgur.com/a/NsH5cEA

**Comment by Muehe** [comment]
We have a bug where sometimes quest progress doesn't get picked up. Try `/reload` in chat and make sure you are using the latest version (4.0.12).

**Comment by BreakBB** [comment]
The "itemObjective" for the quests of both factions seem to be missing in our "itemDB".

[Alliance quest](https://classic.wowhead.com/quest=6122/the-principal-source) and [Horde quest](https://classic.wowhead.com/quest=6127/the-principal-source)

The item IDs are 15845 (alliance) and 15843 (horde).
