### ISSUE TITLE
Extended Questlog

### ISSUE THREAD

**Issue by Schaka** [AeroScripts/QuestieDev#7]
Questie needs its own quest tracker, similar to Extended Questlog. You can only track 5 quests at a time regularly and overwriting the original quest tracker is the first step to having a list of quests to choose the currently tracked one from, which in turn is the first step to having an arrow pointing where you have to go.

**Comment by abennette32** [comment]
Seconded, definitely a needed addition to the addon.

**Comment by rsheep** [comment]
The only existing addon to have an "arrow pointing" somewhere, during vanilla, was BetterWayPoints.
At start it was a standalong addon, while later during vanilla it was integrated with MetaMap, becoming MetaMapBWP.

Here it is the "standalone" version:
BetterWaypoints_v2.51.zip
http://www28.zippyshare.com/v/irYG78Z7/file.html

**Comment by Schaka** [comment]
Thank you. I will look into that once my quest tracking hook is far enough advanced to be able to select a quest from the tracking frame for a GPS-like function.

**Comment by Schaka** [comment]
Works as of a2f1e76a8bce33d91746f82fbab2c5c3999cff34
