### ISSUE TITLE
[Classic] "The Hunter's Path" Ayanna Everstride is incorrect

### ISSUE THREAD

**Issue by kernighan** [AeroScripts/QuestieDev#700]
Questie says that at level 10 there is a quest to pick up from Ayanna Everstride called "The Hunter's Path", but she does not have a quest available.  Made sure I did not have the level 10 one from the hunter trainer in Dolanaar first.

**Comment by Muehe** [comment]
Just to be sure, you are a Nightelf hunter, right?

**Comment by kernighan** [comment]
Correct.  The ones listed in Darnassus do exist (I got it from Jocaste)

**Comment by Muehe** [comment]
Gotcha. Thanks for the report. :+1: We will look into it.

**Comment by kernighan** [comment]
I had not done the quest.  As I noted, I was able to pick it up from one of the other NPCs noted by Questie.  This NPC simply did not offer it. ;)
