### ISSUE TITLE
AddOn is too laggy.

### ISSUE THREAD

**Issue by euloanty** [AeroScripts/QuestieDev#702]
it will take 130ms per sec which is unacceptable.
https://i.imgur.com/zYpJrDk.png

**Comment by AeroScripts** [comment]
Try 4.0.12 and see if it improves performance for you. The map library was updated so it may help.

Some users have also reported poor performance with vsync turned off, can you try vsync and see how that impacts it?

**Comment by euloanty** [comment]
No use with updating. Why do I need to turn on vsync? I hate vsync

https://i.imgur.com/IJoKZy6.png

**Comment by euloanty** [comment]
with vsync on. the performance is still not good. 80ms per sec.
https://i.imgur.com/WLouqgo.png

**Comment by euloanty** [comment]
Please do not use OnUpdate script. Use C_Timer.NewTicker instead.

**Comment by euloanty** [comment]
I give you several tips on how to write high-performance add-ons.
1. Memory Usage should be as low as possible. Higher memory usage = higher cache miss + higher GC costs
2. You should apply a lot of stuff for Load On Demand like addon settings is no reason to be put into addon itself. Make it a separate addon.
3. Avoid hooking. Prefer events. Hooking is slow.
4. Use C_Timer.NewTicker/AceTimer-3.0 instead of OnUpdate script
5. Prefer using coroutine instead of events/callback. Callbacks are hard to make your logic clear and often bugged.

**Comment by euloanty** [comment]
The addon is too laggy even with vsync off.

**Comment by AeroScripts** [comment]
Most of the cpu time in this case is used up by HereBeDragons to recalculate minimap note positions, it's hard to avoid with quests like westfall stew where there are a crazy amount of notes in the zone

Performance is very important I agree, we've tried to keep things as performant as possible. If you have any suggestions for changes to the logic we're always open to PRs

**Comment by euloanty** [comment]
> Most of the cpu time in this case is used up by HereBeDragons to recalculate minimap note positions, it's hard to avoid with quests like westfall stew where there are a crazy amount of notes in the zone
> 
> Performance is very important I agree, we've tried to keep things as performant as possible. If you have any suggestions for changes to the logic we're always open to PRs

Don't use HereBeDragons. It sucks. C_Map.GetMapPosition returns a table is never an issue compared to the library HereBeDragons itself. These people have no idea how to optimize performance.

**Comment by AeroScripts** [comment]
Come to think of it, our fade logic could could also be causing trouble in this case, that runs on every update but it doesn't need to.

**Comment by euloanty** [comment]
> Come to think of it, our icon fade logic could could also be causing trouble in this case, that runs on every update but it doesn't need to.

Reason is simple. You are using events not coroutines. Events are notorious anti the logic of humans.

**Comment by euloanty** [comment]
Here is an example of how to use coroutine for dealing with WoW events.

https://bitbucket.org/ejsvifq_mabmip/lookingforgroup/src/default/SF/Core.lua

**Comment by euloanty** [comment]
Does your addon have a discord? I could provide you a further guideline of how to optimize performance

**Comment by AeroScripts** [comment]
Yeah it's linked in the readme.md 

Always appreciate help, I'm taking a couple days off myself though, gotta deal with some real life stuff

**Comment by wbzr** [comment]
I'm usually at 200 fps in Classic but suddenly went down to 20 fps, linked it to Questie. It only lags when I move my character. Removing the icon fade code didn't fix it, but when I removed onUpdate from HereBeDragons the fps went back to normal.

Looking forward to this being fixed, been working great so far before this FPS drop.

**Comment by BreakBB** [comment]
Any news on this @AeroScripts ?

**Comment by BreakBB** [comment]
@wbzr Could it be related to another addon? Are you using MinimapButtonBag?

**Comment by BreakBB** [comment]
The performance has been significantly increased with the release of 4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2
