### ISSUE TITLE
only display tracked quests ?

### ISSUE THREAD

**Issue by sigzegv** [AeroScripts/QuestieDev#704]
In previous versions, it was possible to only display tracked quests, it doesn't seem possible anymore, or is just the feature not yet implemented ?

**Comment by AeroScripts** [comment]
Not yet implemented yeah. The tracker as a whole hasn't been ported to classic yet, it's being worked on though. I wanted to get that in by sunday but that was a bit of an optimistic estimate. Now we've all gotta deal with some IRL stuff but, it will still be coming out very soon. Top priority right now

**Comment by coolacid** [comment]
Personally would love to see it integrated with MonkeyQuest instead of porting a full tracker if it moves the rock faster.

**Comment by BreakBB** [comment]
Merging this with #681 Have a look at the latest releases of Questie to get a WIP build of the tracker.
