### ISSUE TITLE
[Tirisfal Glades] Ask player to grind to lvl11 when player is already lvl11

### ISSUE THREAD

**Issue by lonelynineswords** [AeroScripts/QuestieDev#705]
After killing Captain Melrache and his 2 bodyguards at coord 79:25, Tirisfal Glades. Questie prompts "Grind Mobs to 8000xp into lvl11" "3037 exp to go!" While the player is already half past lvl11.

There is also no manual way to skip this prompt in the addon.

**Comment by AeroScripts** [comment]
Are you sure it's this addon? Questie doesn't have a guide

Possibly AAP?

**Comment by lonelynineswords** [comment]
Update: I decided to keep grinding toward lvl12 anyway. The result is, although the exp required for lvl12 is 8800 (lvl11 is 8000), the Questie's trigger to the next step is satisfied when my exp reached 8000 (note I am not lvl12 yet). 
And then Questie prompts me on the next step to Hearthstone back to town. I am glad I can grind my way out of the bug :D

**Comment by AeroScripts** [comment]
This really sounds like azeroth autopilot or similar, questie only adds icons to the map

**Comment by lonelynineswords** [comment]
Oh no, I totally mixed up the 2. I am totally sorry that I raised an unnecessary concern.
I best regard to you. Thank you for your work. :)

**Comment by AeroScripts** [comment]
its ok :D common mistake actually, glad thats cleared up
