### ISSUE TITLE
The Quest "The Fall of Ameth'aran" not showing

### ISSUE THREAD

**Issue by Jezz1e** [AeroScripts/QuestieDev#709]
This quest is from Darkshore, 40.30 59.73 (exact location of the npc, Sentinel Tysha Moonblade)

**Comment by Jezz1e** [comment]
Just to follow up, the icons after receiving the quest had no issues. Only the icon not showing up where to get the quest is not showing.

**Comment by Jezz1e** [comment]
I have not tried /reload but I believe this should be worth noting

**Comment by BreakBB** [comment]
We will check our data, but if anyone could try this it would be helpful

**Comment by BreakBB** [comment]
The data looks alright. Has most likely been caused by #860
