### ISSUE TITLE
The Temple of the Moon quest doesn't show as Completed after completing it.

### ISSUE THREAD

**Issue by Fokvest** [AeroScripts/QuestieDev#713]
There isn't a quest called The Temple of the Moon in My Journey, but it still shows on the map and in the Quests by Zone ( Kalimdor, Darnassus ) despite me completing it.

**Comment by BreakBB** [comment]
This was most likely because of the desync bug and should be fixed now

**Comment by BreakBB** [comment]
Related to #860
