### ISSUE TITLE
Quests from Sputtervalve Showing Up in Lakeshire On Minimap

### ISSUE THREAD

**Issue by EStheman** [AeroScripts/QuestieDev#715]
![WoWScrnShot_083119_143400](https://user-images.githubusercontent.com/54751015/64067837-099d9f00-cbfd-11e9-8e3c-e0a6f665c4a0.jpg)

**Comment by BreakBB** [comment]
Did you try `/reload`?

**Comment by EStheman** [comment]
Yes, /reload fixed it but I’m not sure why it was there in the first place
