### ISSUE TITLE
Stones of binding burning key wrong map icon

### ISSUE THREAD

**Issue by Tyriar** [AeroScripts/QuestieDev#716]
![image](https://user-images.githubusercontent.com/2193314/64069110-f89e5f00-cbf7-11e9-9400-c7d93a24a506.png)

Should be this:

![image](https://user-images.githubusercontent.com/2193314/64069113-0653e480-cbf8-11e9-9a41-ce6b19715a64.png)

**Comment by BreakBB** [comment]
@AeroScripts You made some fixes for this quest, didn't you?

**Comment by BreakBB** [comment]
Fixed with 1478fe1f111d12764c4d9ebd8911a36a34eaede5

**Comment by Tyriar** [comment]
Any chance of updating and expanding [this wiki page](https://github.com/AeroScripts/QuestieDev/wiki/Database-format-and-maintainence)? I tried to do this myself but gave up after 10 minutes or so due to the lack of docs.

**Comment by BreakBB** [comment]
We're currently just a few developers and have limited time. Updating the wiki is on the list though and some restructuring has already been done.

You can always contact us on Discord and we appreciate every help we get!

**Comment by Tyriar** [comment]
I imagine you're getting a bit swamped at the moment which is why I wanted to help out. While there's definitely a cost to investing in the documentation, it would likely pay for itself in the long run by letting people do PRs for things like this and helping them become contributors.

I'll probably join the Discord later on when something else like this pops up to see if I can action it 😃

**Comment by BreakBB** [comment]
Yes you're absolutely right. We should really invest the time 👍
