### ISSUE TITLE
Worth Its Weight in Gold doesn't track medicine pouches or shadow hunter knife

### ISSUE THREAD

**Issue by Tyriar** [AeroScripts/QuestieDev#717]
Medicine pouched should show up for this:

![image](https://user-images.githubusercontent.com/2193314/64069988-407ab180-cc0b-11e9-8989-b30e847f23d6.png)

Shadow hunter knife should show up for this:

![image](https://user-images.githubusercontent.com/2193314/64070018-2f7e7000-cc0c-11e9-92d5-15ab764f6db4.png)

They also don't show in the minimap or world map.

**Comment by AeroScripts** [comment]
Hmm looks like its database related ill check it. There's a lot of DB fixes we need to go through, ive been really busy with some IRL stuff and fixing more critical bugs. Gonna try to go through some of these tonight

Thanks for reporting <3

**Comment by Tyriar** [comment]
Is this actually a limitation of the addon? I was just doing The Lost Fragments where all 3 items drop off the same mobs and the same thing happened.

**Comment by AeroScripts** [comment]
hmm yeah something might have broken with the objective logic recently seems only 1 objective per NPC type. I'll look in to it

**Comment by Tyriar** [comment]
I'm on 4.0.12

**Comment by BreakBB** [comment]
Could this please be checked with 4.1.1 🙏

**Comment by Tyriar** [comment]
I finished it so won't be able to test again for a long time.

**Comment by BreakBB** [comment]
Reported to be fixed
