### ISSUE TITLE
Triage quest doesn't appear on map

### ISSUE THREAD

**Issue by Tyriar** [AeroScripts/QuestieDev#718]
I think the requirements are level 35+ and 225/225 first aid (the quest is presentin questDB.lua) https://classic.wowhead.com/quest=6624/triage

![image](https://user-images.githubusercontent.com/2193314/64070661-973bb780-cc1a-11e9-8254-a50a79a5e119.png)

**Comment by BreakBB** [comment]
Thanks for the report. We've blacklisted this quest for now since we haven't implemented a way to check the professions a user has. Merging this with #488
