### ISSUE TITLE
[44] Badlands Reagent Run II shows on map but is not available at level 40

### ISSUE THREAD

**Issue by Tyriar** [AeroScripts/QuestieDev#721]
I just finished [Badlands Reagent Run (A)](https://classic.wowhead.com/quest=2500/badlands-reagent-run) but the follow up is not available at level 40 apparently.

**Comment by AeroScripts** [comment]
It shows as available but isn't in game? Or it doesn't show but is available ingame

Wowhead says it requires level 40 anyway. The database has it flagged as requiring 40

**Comment by Tyriar** [comment]
Definitely wasn't available, I notice that there is no side indicator for the 44 elite one?

![image](https://user-images.githubusercontent.com/2193314/64071602-69fb0380-cc32-11e9-91e5-31d70baa8b87.png)

Maybe it doesn't actually exist?

**Comment by AeroScripts** [comment]
Hmm you're right, that could be it ill check the DB
Is there really no alliance part 2 of that quest? There's a part 1

**Comment by Tyriar** [comment]
I'll try check when i level

**Comment by Tyriar** [comment]
It's not there at level 41 either

**Comment by AeroScripts** [comment]
There probably is some other requirement that we don't know about, I dont think leveling up will unlock it. Gonna need to do a little digging online to figure out the correct behavior

**Comment by drejjmit** [comment]
According to Wowhead comments it requires 225 alchemy.

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/AeroScripts/QuestieDev/issues/750
