### ISSUE TITLE
Looting items from mailbox doesn't update quest progress

### ISSUE THREAD

**Issue by MysticalOS** [AeroScripts/QuestieDev#722]
lets say you have a cooking quest. you buy items off AH, the quest progress won't update if you buy items.

Is there any way you can monitor the loot message of opening mail, to track whether or not the acquired item is toward a quest progress?

**Comment by AeroScripts** [comment]
Hmm yeah we should be able to add something like that, I think there are other cases where it doesn't update the progress too. Kinda annoying that the blizzard tracker doesn't pick up on it (or does it?)

**Comment by MysticalOS** [comment]
Blizzard tracker does catch it actually.

But i wouldn't be surprised if it doesn't fire QUEST_LOG_UPDATED

**Comment by AeroScripts** [comment]
Ahh, if it does update in the quest log but doesn't fire the event, thattl be easier to fix

There's a function to update objectives which checks the quest log (used by tooltips) but that only affects tooltips, it won't remove icons from the map or add the finisher.

Not sure the best way to solve it but we can maybe make it update icons some time after objectives change, if there's still no QLU event. icons are only updated on that event currently

**Comment by MysticalOS** [comment]
That makes sense, updating icons willy nilly would be performance drain, so that's definitely something that should stay on an event. I'll run event trace next time i remember to loot quest items from mail to see if anything useful comes out of it

**Comment by SpareSimian** [comment]
Two other events to check are personal trades and buying a quest item from a vendor.

**Comment by BreakBB** [comment]
Please test this with v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2 We've updated our event system which might handle this as well.

**Comment by SpareSimian** [comment]
I got a chance to try it today. A moment after I collect a quest item from the mailbox the quest tracker shows it! I'm doing the Seasoned Wolf Kabobs quest in Darkshire and bought the Lean Wolf Flanks on the AH.

**Comment by BreakBB** [comment]
@SpareSimian Thanks for talking your time to response back. I will close this :ok_hand:
