### ISSUE TITLE
Can't find a way to show unavailable higher level quests

### ISSUE THREAD

**Issue by Booom3** [AeroScripts/QuestieDev#725]
This other quest addon I had had this really useful function to display quests that are currently unavailable because they required a few more levels to accept.
Currently this addon can not do that, it can only show higher level quests that I can accept right now.

Is this planned for the future?

**Comment by AeroScripts** [comment]
Yeah we've been planning on adding this, optional silver quest icons similar to what pfQuest does. Once we can sort through all these bugs and more critical missing things we'll be adding it

**Comment by BreakBB** [comment]
This has been implemented with v5.8.0
