### ISSUE TITLE
Click a quest which should be done in a cave when i'm in that cave will cause an error which can't be removed by click ok.

### ISSUE THREAD

**Issue by ayrb13** [AeroScripts/QuestieDev#73]
Click a quest which should be done in a cave when i'm in that cave will cause an error which can't be removed by click ok.

**Comment by Schaka** [comment]
Can you please screenshot the error and post it here? While it is great, that you described what caused the error, we also need to know what the error is - more importantly so.

**Comment by ayrb13** [comment]
k, I'll try to reproduce it tonight

**Comment by ayrb13** [comment]
While in that cave, i can only see whole world map when i clicked 'm'. I just wanted to know where that quest should be done and i clicked it in trackerfram, the error occured.
That cave is the primary entrance of uldaman dungeon, not back door of it.

**Comment by ayrb13** [comment]
sorry, i failed to reproduce that error.
you can close this issue temporarily

**Comment by ayrb13** [comment]
I'll reopen it when i get this error again
