### ISSUE TITLE
Touch of Weakness quest giver incorrect (undead)

### ISSUE THREAD

**Issue by Aelas** [AeroScripts/QuestieDev#730]
Questie shows the starting npcs for the Touch of Weakness quest for undead priests as Dark Cleric Beryl in Brill and Father Lankester in the Undercity, neither of which bestow the quest. The actual quest giver is Aelthalyste in the Undercity which isn't marked.

**Comment by BreakBB** [comment]
According to the Wowhead data all those NPCs are able to hand out those quests. And Aelthalyste is included in our data.

Did you try to `/reload`? And you were level 10 when looking in Brill?

**Comment by Zimmme** [comment]
Yeah its bugged, i aleardy finished the quest. U get the quest from Aelystha or something like that, the lvl 60 banshee-like priest triner in UC and she gives AND finishes the quest so all u have to do is go to her to get the skill.
Its just wrong in brill :)

**Comment by bmagic** [comment]
I confirm no-one give you the quest in Brill, you have to go to Aelthalyste.

**Comment by bjohnsonc** [comment]
Confirm that Dark Cleric Beryl in Brill does not give "Touch of Weakness". Aelthalyste in Undercity/War Quarter does.
![touchofweakness](https://user-images.githubusercontent.com/25837629/64130476-1b5f7d80-cd88-11e9-90b5-285f1668672f.png)

**Comment by AeroScripts** [comment]
Are you sure this is the best way to fix it? Quest is still available in undercity (or did you blacklist a different quest id?)

Sounds like we need to change the giver NPC, maybe I misunderstand the issue

**Comment by BreakBB** [comment]
There are breadcrumb quests leading to the NPC "Aelthalyste". And multiple people above reported that "Dark Cleric Beryl" in Brill doesn't give a breadcrumb quest even though it is listed on Wowhead. [This comment](https://classic.wowhead.com/quest=5661/touch-of-weakness#comments:id=3150381) states as well that there is no breadcrumb in Brill.

Therefore I blacklisted the quest starting in Brill :thinking:

**Comment by AeroScripts** [comment]
sounds ok to me, just wanted to make sure
