### ISSUE TITLE
[A] Tabetha's Task showing up in Thunder Bluff

### ISSUE THREAD

**Issue by Tyriar** [AeroScripts/QuestieDev#731]
![image](https://user-images.githubusercontent.com/2193314/64080996-ccdeb000-ccaf-11e9-8932-a97215c9c858.png)

Actually starts in Ironforge:

https://classic.wowhead.com/quest=2861/tabethas-task

Looks like just the zone ID is wrong

**Comment by drejjmit** [comment]
This quest is given by capital city mage trainers. Deino in Orgrimmar, Jennea Cannon in Stormwind, Bink in Ironforge, Anastasia Hartwell in Undercity and Ursyn Ghull in Thunder Bluff. Since they all have the same quest id it's currently not possible to filter out the Horde/Alliance versions.

**Comment by Tyriar** [comment]
Verified fixed in latest:

> Import new spawn database, including NPC faction data. This should fix quests that have a specific quest giver for each faction
