### ISSUE TITLE
Mulgore quests showing up but not actually eligible

### ISSUE THREAD

**Issue by bekerma2** [AeroScripts/QuestieDev#732]
- lvl 10: Kudo Hide Bag (shouldn't show up - reqs lvl10 leatherworking)
- lvl15: Until Death do us part (shows up not actually eligible at lvl12)

**Comment by BreakBB** [comment]
Professions are not filtered yet, sorry.

And "Until Death Do Us Part" can be accepted at level 12. Make sure you took inside the cave and not on top of it.
