### ISSUE TITLE
Quest log tracker limited to 5 unlike before

### ISSUE THREAD

**Issue by sk3ptyc** [AeroScripts/QuestieDev#735]
The current version of Questie does not allow more than the default 5 quests on the tracker. Would it be possible to remove this limiter and allow to add more than 5 quests to the tracker like in previous versions? Many thanks, sk3p

**Comment by BreakBB** [comment]
Have a look a the freshly create [FAQ for Classic](https://github.com/AeroScripts/QuestieDev/wiki/FAQ-for-Classic-(1.13)). The tracker hasn't been ported to the Classic version yet.

**Comment by sk3ptyc** [comment]
Thanks BreakBB!
