### ISSUE TITLE
Quest is missing from Darkshore list

### ISSUE THREAD

**Issue by ArcaneGoblin** [AeroScripts/QuestieDev#736]
https://classic.wowhead.com/quest=968/the-powers-below

This one is present in DB and can be found by Name or ID, but for some reason it's not on the list if you try to find it in 'Quests by Zone' tab.

**Comment by AeroScripts** [comment]
Currently there's no way to list quests that start from items on the map, we may be able to figure out a way though

At the very least, maybe we can add something like "Drops X which starts Y quest" in mob tooltips, for mobs that drop items like that (excluding very low drop rate / widespread items like OOX distress beacons)

**Comment by BreakBB** [comment]
Fixed with 66869b696ebc98ca05097892907f59a288bcc3d0
