### ISSUE TITLE
Quest List UI not showing quests after long use

### ISSUE THREAD

**Issue by alekmieczkowski** [AeroScripts/QuestieDev#739]
After you use questie for 5-10 different quests, the quest tasks stop showing up in overlay UI. Did a quick glance over the issue posts and didnt see one like it, sorry if dup.

**Comment by BreakBB** [comment]
Not sure what UI element you mean, but the quest tracker hasn't been ported to the Classic version yet. So you're most likely seeing the Blizzard quest tracker. Shift + leftclick on a quest in your questlog will add them to the tracker again.

**Comment by omggga** [comment]
The main feature i waiting for is questie tracker. Any chances i will be ported? Damn that blizz tracker with 5 limit :-1:

**Comment by BreakBB** [comment]
It is already in development, but since some severe issues came up with the Classic release the release of this feature has been delayed. Sorry about the frustration.

**Comment by BreakBB** [comment]
Checkout the latest Questie release. The tracker has been ported!
