### ISSUE TITLE
Sister Aquinne in Darnassus

### ISSUE THREAD

**Issue by paulthomas46** [AeroScripts/QuestieDev#740]
Hi

I'm level 12 Night Elf Hunter.

Questie shows that I have a quest available from Sister Aquinne (quest is called The Temple of The Moon and it is for level 10) in Darnassus as an exclamation mark is above her head on the map.

However, when I approach her she has no quest marker.

Thanks

Paul

**Comment by AeroScripts** [comment]
Can you try running this command and let me know what it says

/dump IsQuestFlaggedCompleted(2518)

**Comment by paulthomas46** [comment]
Just logged back in and without even doing the command the marker is no longer showing on the map

________________________________

**Comment by AeroScripts** [comment]
Hmm, its possible that today's update fixed it
