### ISSUE TITLE
Gelkis Alliance - question mark missing on the map

### ISSUE THREAD

**Issue by eFse7en** [AeroScripts/QuestieDev#741]
Missing question mark after completing classic quest "Gelkis Alliance": https://classicdb.ch/?quest=1368

**Comment by AeroScripts** [comment]
And it doesn't appear after /reload? Some have reported the desync issue is still present rarely when a quest is finished (But as before /reload fixed it)

Give that a try, if it doesn't fix it we have to fix the data. If it does, that should be fixed in the next few updates

**Comment by eFse7en** [comment]
Sadly i have already returned it, cannot check.

**Comment by AeroScripts** [comment]
Ok well thanks for reporting anyway, I'll check the data

**Comment by BreakBB** [comment]
Our data looks fine on this quest. Closing this for now.
