### ISSUE TITLE
Lost Deathstalkers Horde Quest may be unavailable.

### ISSUE THREAD

**Issue by deathisabove** [AeroScripts/QuestieDev#744]
*High Executor Hadrec* in *Silverpine Forest.* does not offer this quest if *Wild Hearts* has been completed beforehand. Due to [WowHead](https://classic.wowhead.com/quest=428/lost-deathstalkers)

And as you can't ignore quest in Questie - it becomes useless.

**Comment by AeroScripts** [comment]
Can you run /dump IsQuestFlaggedCompleted(429) ?

There was a fix for this quest added recently, it should lock out if you have or have completed Wild Hearts (429)

What build are you on?

**Comment by deathisabove** [comment]
![image](https://user-images.githubusercontent.com/13339874/64116079-7bbbe280-cdbb-11e9-81b1-4a2da490a4fa.png)

**Comment by deathisabove** [comment]
I've also tried to fully delete Questie folder and extract fresh one - no help =(

**Comment by AeroScripts** [comment]
You can shift+click to hide the quest for now, I will do some testing myself, sorry for the trouble & thanks for reporting

**Comment by Xarsen** [comment]
I'm having the same problem. Quest 429 returns true.  Questie is stuck as showing pick up quest Lost Deathstalkers.
Read that if you do Wild Heart quest, lost deathstalkers will never be offered.  Using version 4.0.14

Thanks

**Comment by BreakBB** [comment]
@Xarsen Sorry for the late response but Questie does not show anything like "pick up quest X". That most likely comes from AAP or a similar addon.

The data looks good on our side (listed as subQuest + `questExclusiveGroupFixes`). Any idea @AeroScripts ?

**Comment by BreakBB** [comment]
This has been fixed with 3a3fbeb8ef748dc24b1d9b87af0cbf9d2b738b81
