### ISSUE TITLE
Researching the Corruption (not shown on map)

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#745]
Gershala Nightwhisper is offering this quest in Auberdine, but nothing is shown on the map (I'm level 23).

**Comment by AeroScripts** [comment]
Hmm ill check the db, thanks for reporting

We're gonna take some time and go through the quest data bugs tomorrow

**Comment by pattax** [comment]
Not sure if 100% related but some quests are not being shown if the client is not set to english language. My friend is not seeing a lof of quests/quest objectives with the same questie version and settings. The only difference is him using the german client while I am using the english (en_GB) client.

**Comment by drejjmit** [comment]
@pattax Please try with the latest version. Many localization updates in v4.0.14. Report if you find any problems in this version.

**Comment by Painstormx** [comment]
I've tried the latest version. Quest is still not showing on map.
