### ISSUE TITLE
Trek to Ashenvale (shown on map, but not available)

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#746]
It is shown on the map, but Sentinel Selarin does not have any quest available. I'm level 23.

**Comment by BreakBB** [comment]
[This Wowhead comment](https://classic.wowhead.com/npc=3694/sentinel-selarin#comments:id=3153751) states that the quest is currently bugged.

**Comment by drejjmit** [comment]
https://us.battle.net/support/en/article/247288
This is on Blizzard to fix.
