### ISSUE TITLE
[43] Replacement Phial

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#749]
https://classic.wowhead.com/quest=3375/replacement-phial

Requires 
https://classic.wowhead.com/quest=2200/back-to-uldaman
or
https://classic.wowhead.com/quest=2201/find-the-gems

No longer available when 2201 - Find the Gems are turned in.

![unknown (10)](https://user-images.githubusercontent.com/15526476/64122353-a8fb9700-cda1-11e9-90f8-ccbcffc62e20.png)

![unknown (11)](https://user-images.githubusercontent.com/15526476/64122368-b57fef80-cda1-11e9-8fe0-a808330f3ff6.png)

**Comment by Andrioden** [comment]
Confirm, the quest indicator shows after completing the relevant related quest.

**Comment by BreakBB** [comment]
This has already been fixed with 7c45b7f1487f58aaaed4b6c026b70bb188ff913c
