### ISSUE TITLE
[44] Badlands Reagent Run II

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#750]
https://classic.wowhead.com/quest=2203/badlands-reagent-run-ii
and
https://classic.wowhead.com/quest=2501/badlands-reagent-run-ii

Alchemy only quests. Shows up for everyone.

**Comment by Tyriar** [comment]
This must be the reason I was seeing it here https://github.com/AeroScripts/QuestieDev/issues/721, I am alchemy but I guess I'm no high enough yet.

**Comment by drejjmit** [comment]
According to Wowhead comments it requires 225 alchemy.

**Comment by BreakBB** [comment]
With the release of 4.1.1 we've finally added the profession logic so this has been fixed.
