### ISSUE TITLE
[Classic Wow] Questie shows two quests as both completed and uncompleted.

### ISSUE THREAD

**Issue by Immuneity** [AeroScripts/QuestieDev#752]
The quests Candles of Beckoning and The Dormant Shade in Tirisfal Glades show up as uncompleted when searching for quests by zone but show completed under My Journey. I have already tried resetting My Journey through the commands in the FAQ and they still show up as if they can be accepted. I even went to the location to see if they could be accepted again and they are not. Thanks

**Comment by drejjmit** [comment]
The quest is repeatable. It's hidden when you complete 'Proving Allegiance' since you can't complete it after that. 
Fixed with this commit:
https://github.com/AeroScripts/QuestieDev/commit/8c14e09f13c1626c331353bc1d945651dad41b9e

**Comment by Immuneity** [comment]
Is there anyway to have it so it doesn't show up in game?

**Comment by drejjmit** [comment]
Get version v4.0.14 +

**Comment by Immuneity** [comment]
I have 4.0.14. Also while I have the comment chain open. In Silverpine Forest, the quest Lost Deathstalkers is uncompletable if you do the quest Wild Hearts first but it still shows up as an option.

**Comment by drejjmit** [comment]
Oh okay. Keep this issue open and we will take a look at it again. You can hide the quests in the meantime by holding shift and clicking them. Please report any other problems if you need to hide something :)

**Comment by Immuneity** [comment]
Ok thank you, much appreciated.

**Comment by AeroScripts** [comment]
You can shift+click to hide these quests as of 4.0.14 also. A proper fix for the wild hearts chain is being worked on today

**Comment by Immuneity** [comment]
Both have been fixed for me.
