### ISSUE TITLE
[Classic Wow] LUA Error

### ISSUE THREAD

**Issue by Edwin18** [AeroScripts/QuestieDev#753]
31x Questie\Modules\QuestieJourney.lua:556: bad argument #1 to 'ipairs' (table expected, got string)
[C]: in function `ipairs'
Questie\Modules\QuestieJourney.lua:556: in function `createObjectiveText'
Questie\Modules\QuestieJourney.lua:193: in function <Questie\Modules\QuestieJourney.lua:118>
[C]: ?
Mapster\Libs\AceGUI-3.0\AceGUI-3.0-39.lua:72: in function <Mapster\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
Mapster\Libs\AceGUI-3.0\AceGUI-3.0-39.lua:287: in function `Fire'
...ibs\AceGUI-3.0-39\widgets\AceGUIContainer-TreeGroup.lua:515: in function `SetSelected'
...ibs\AceGUI-3.0-39\widgets\AceGUIContainer-TreeGroup.lua:191: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:187>

![image](https://user-images.githubusercontent.com/8036656/64126345-0c8fbf80-cdb6-11e9-8805-11b4e0c5e971.png)

**Comment by AeroScripts** [comment]
This should be fixed in the latest v4.0.15 release. If not, please post back

**Comment by Edwin18** [comment]
41x Questie\Modules\QuestieJourney.lua:556: bad argument #1 to 'ipairs' (table expected, got string)
[C]: in function `ipairs'
Questie\Modules\QuestieJourney.lua:556: in function `createObjectiveText'
Questie\Modules\QuestieJourney.lua:193: in function <Questie\Modules\QuestieJourney.lua:118>
[C]: ?
Mapster\Libs\AceGUI-3.0\AceGUI-3.0-39.lua:72: in function <Mapster\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
Mapster\Libs\AceGUI-3.0\AceGUI-3.0-39.lua:287: in function `Fire'
...ibs\AceGUI-3.0-39\widgets\AceGUIContainer-TreeGroup.lua:515: in function `SetSelected'
...ibs\AceGUI-3.0-39\widgets\AceGUIContainer-TreeGroup.lua:191: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:187>

![image](https://user-images.githubusercontent.com/8036656/64201924-87310b80-ce98-11e9-850f-42877f302ce4.png)

**Comment by Edwin18** [comment]
again, today

**Comment by Edwin18** [comment]
And again)
![image](https://user-images.githubusercontent.com/8036656/64211866-39280200-ceb0-11e9-8239-3ded95619349.png)

**Comment by BreakBB** [comment]
@AeroScripts Any idea?

**Comment by BreakBB** [comment]
What's the state on this?

**Comment by BreakBB** [comment]
@Edwin18 Please checkout v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2 and report back if this is not fixed
