### ISSUE TITLE
Horde Quest Broken Tears missing location

### ISSUE THREAD

**Issue by xinux-lv** [AeroScripts/QuestieDev#754]
Quest_ID: 1369
Level: 33
Requires level 30
Side: Horde
Start: Warug
End: Warug
Sharable
Difficulty: 30  31  36  42
Added in patch 1.13.2.30682
Series
1.	Brutal Politics
2.	Magram Alliance Assault on the Kolkar
3.	Broken Tears
4.	Gizmo for Warug

You get the tears from the cave at 38.8 , 91.0

**Comment by AeroScripts** [comment]
Thanks for reporting ill add the spawn to the DB 👍

**Comment by BreakBB** [comment]
@AeroScripts Did you fix this?

**Comment by latusthegoat** [comment]
Doesn't look fixed yet. Still not showing up after last update. Object to be picked up is in cave at 38/91

**Comment by BreakBB** [comment]
The data looks totally fine on our side. Someone with this quest please share a screenshot and further information.

**Comment by BreakBB** [comment]
Please report back if this is not fixed with v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2
