### ISSUE TITLE
Missing question mark - Elixir of Agony

### ISSUE THREAD

**Issue by Skeptyk** [AeroScripts/QuestieDev#755]
I have all the objectives completed for "Elixir of Agony", but the question mark does not show on the map or mini map.  I've noticed this happening several times already, so please let me know how I can improve reporting these issues.  Thank you.  

https://classic.wowhead.com/quest=515/elixir-of-agony

**Comment by Skeptyk** [comment]
I checked a few other reported issues and I see that doing a /reload sometimes fixes this issue.  I did not try that earlier because I just learned of this.  It did just fix a similar issue I had with another quest just now.

**Comment by BreakBB** [comment]
You should update to v4.0.16 which should prevent such issues. The data on our side should be checked though
