### ISSUE TITLE
Warlock quest "The Binding" 

### ISSUE THREAD

**Issue by WildMonkeyLaura** [AeroScripts/QuestieDev#756]
Upon accepting The Binding quest, questie returned the following error: There was an error populating objectives for The Binding 1471 1 Interface\Addons\Questie\Modules\QuestieQuest.lua:630: bad argument #1 to 'pairs' (table expected, got nil).

**Comment by AeroScripts** [comment]
Should be fixed as of cb7ff5764ba604a51c3f9093e904bd358548099f

Along with many other quests where you need to kill a special named NPC spawned by an item or script

Fix will be in v4.0.16 release
