### ISSUE TITLE
Horde Quest Hand of Iruxos missing location

### ISSUE THREAD

**Issue by xinux-lv** [AeroScripts/QuestieDev#757]
entrance at 56,29 in desolace - actual crystal at 55,26

Quest_ID: 5381
Level: 38
Requires level 32
Side: Horde
Start: Taiga Wisemane
End: Taiga Wisemane
Not sharable
Difficulty: 32  34  36  41  47
Added in patch 1.13.2.30682
Series
1.	Hand of Iruxos
2.	Portals of the Legion

**Comment by Muehe** [comment]
Ah yes, we were missing the spawn point of [Demon Spirit](https://classic.wowhead.com/npc=11876/demon-spirit), it's probably summoned somehow. I'll overwrite it's spawn with what Wowhead has, thanks for reporting. :+1: Commit will be up in a minute.

FYI the fix will only be available in the development version until we upload the new release. If you want to test let me know here and I can explain how.
