### ISSUE TITLE
Error Portals of the Legion

### ISSUE THREAD

**Issue by xinux-lv** [AeroScripts/QuestieDev#758]
Questie: [ERROR] [QuestieQuest]: There was an error populating objectives for Portals of the Legion 5581 1 Interface\Addons\Questie\Modules\QuestieQuest.lua:630: bad argument #1 to 'pairs'; (table expected, got nil)

Here are coords for 3 of the portals 50,74 / 50,70 / 49,77

**Comment by AeroScripts** [comment]
Should be fixed as of cb7ff5764ba604a51c3f9093e904bd358548099f

It will be in v4.0.16 release
