### ISSUE TITLE
Earthen Arise acceptance shows error

### ISSUE THREAD

**Issue by erenn16** [AeroScripts/QuestieDev#759]
The Earthen Arise quest ( https://classic.wowhead.com/quest=6481/earthen-arise ) shows an error in chat upon acceptance.

<img width="568" alt="Screen Shot 2019-09-02 at 3 24 44 PM" src="https://user-images.githubusercontent.com/10402335/64134745-24efe200-cd96-11e9-8752-5717478b35e7.png">

**Comment by AeroScripts** [comment]
Should be fixed as of cb7ff5764ba604a51c3f9093e904bd358548099f

Along with many other quests where you need to kill a special named NPC spawned by an item or script
