### ISSUE TITLE
Gamefreeze on start

### ISSUE THREAD

**Issue by n0script** [AeroScripts/QuestieDev#76]
Hey there,

my game just freeze as soon as i enter the world. No altf4 possible so i have to kill it from task manager.
It just happens with questie addon active. The cartographer works fine.

All addons that i use:
!BugGrabber
!OmniCC
Ace2
AtlasLoot
Auctioneer
Bartender2
Bartender2_Dreamlayout
BugSack
Cartographer
CECB_Options
CEnemyCastBar
ClassicSnowFall
CompactLootFrames
Decursive
EnhTooltip
EQL3
Gatherer
GMail
GridEnhanced
Informant
KLHThreatMeter
MoveAnything
Prat
Questie
Recap
Stubby
SW_Stats
TinyTip
TinyTipExtras
TinyTipOptions
WIM
XLoot
_LazyPig

playing from win8.1 in compatibility mode (WIN7)

greetings and great work anyway :)

**Comment by Sparh4wk** [comment]
had the same problem yesterday.. just disable all addons, log in, then log out. then enable them again

**Comment by Schaka** [comment]
I'll have to try and reproduce that. Aero told me the same thing, but I wasn't able to reproduce it until now. So I'll have to try again and see if I can fix it.

**Comment by Schaka** [comment]
Fixed in master now
