### ISSUE TITLE
[37] Coolant Heads Prevail (A) says Frost Oil is attainable in Un'goro and Feralas

### ISSUE THREAD

**Issue by Tyriar** [AeroScripts/QuestieDev#760]
![image](https://user-images.githubusercontent.com/2193314/64141286-4f549600-cdbc-11e9-9119-dc465102fee2.png)
![image](https://user-images.githubusercontent.com/2193314/64141295-57143a80-cdbc-11e9-8af7-2eb74cf88aeb.png)

You can only get it from alchemists, and the recipe is sold in Alterac https://classic.wowhead.com/quest=713/coolant-heads-prevail

**Comment by AeroScripts** [comment]
lol that's a weird one, ill remove those spawns from the db... Wonder what it thinks drops them

**Comment by AeroScripts** [comment]
Should be fixed in the next release, fix is up on master now
