### ISSUE TITLE
QuestieQuest.lua bad argument #1 to 'pairs'

### ISSUE THREAD

**Issue by Tyriar** [AeroScripts/QuestieDev#761]
On first launch after upgrading to 4.0.15

![image](https://user-images.githubusercontent.com/2193314/64142952-fa684e00-cdc2-11e9-93a6-7256c7797d71.png)

Happens after `/console reloadui`

**Comment by AeroScripts** [comment]
This is another one that is fixed as of cb7ff5764ba604a51c3f9093e904bd358548099f

Fix will be in 4.0.16, but if you're using git try updating to the latest master

**Comment by BreakBB** [comment]
#756 is related
