### ISSUE TITLE
Questie stuck on a quest

### ISSUE THREAD

**Issue by psycostu** [AeroScripts/QuestieDev#764]
on world of warcraft the quest 'Mountaineer Stormpikes task' says pick up quest even though ive already completed it, and it wont move on.

**Comment by AeroScripts** [comment]
What do you mean by it wont move on? You may be thinking of AAP, questie doesn't have a step based guide, only adds icons

If the icon is still showing up, you can shift+click to hide it for now

**Comment by BreakBB** [comment]
Questie does not give any hints about which quest to pick up and in which order. So Questie can't "move on". I guess you're using the AAP addon which tells you to pickup a quest. You can run `/aap skip` in such a situation.

If I am wrong and it really is Questie which shows a Quest you already did then we will investigate our data.

**Comment by psycostu** [comment]
Sorry my fault it was an addon auto pilot!!!
