### ISSUE TITLE
Questie mistakes my class

### ISSUE THREAD

**Issue by Kranrok** [AeroScripts/QuestieDev#766]
Im getting class quests for priest when im warlock. perhaps i need to say i deleted a char and created a same name char for a different class.

**Comment by BreakBB** [comment]
This is a known issue. You can try the following command if you don't care about your journey entries (**those will be deleted**):

```
/run Questie.db.char.complete = {}
/reload
```

**Comment by Kranrok** [comment]
Thanks mate

**Comment by AeroScripts** [comment]
You should also make sure to update, because that shouldn't be an issue in v4.0.16
