### ISSUE TITLE
Speak with Shoni - not displayed

### ISSUE THREAD

**Issue by maleneff** [AeroScripts/QuestieDev#767]
Speak with Shoni (https://classic.wowhead.com/quest=2041/speak-with-shoni) not displayed on a city map, only on a region map.

**Comment by BreakBB** [comment]
Are you using the current version of Questie?

**Comment by maleneff** [comment]
Yes, 4.0.15b, downloaded today. 

Антон Маленев

вторник, 3 сентября 2019 г., 19:27 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by octopusnz** [comment]
I think it's the NPC themselves, have seen this with other quests they give. Looks like it thinks they're not in Ironforge but outside the city for some reason.

**Comment by AeroScripts** [comment]
Yeah, ironforge is it's own zone ID, we need to move the spawn into ironforge, looks like something went wrong with the calculation

**Comment by BreakBB** [comment]
This has been fixed with 985d873cca4c853dcb3b3b32dbc02a8884471f60
