### ISSUE TITLE
QuestieQuest.lua:630 bad argument#1

### ISSUE THREAD

**Issue by Tex42** [AeroScripts/QuestieDev#768]
Happens after completing Deep Run Rat Roundup
![Error](https://user-images.githubusercontent.com/34315398/64183334-08bd7500-ce6a-11e9-874e-e3b38ea808c4.PNG)

**Comment by mikwaldo** [comment]
Same Error in Darkshore
WANTED: Murkdeep and Plagued Lands

**Comment by BreakBB** [comment]
The fix is already on committed but we're waiting for some more to get the next release ready. Keep an eye up for v4.0.16

**Comment by BreakBB** [comment]
Also duplicate of #761
