### ISSUE TITLE
Questie error

### ISSUE THREAD

**Issue by groentelegger** [AeroScripts/QuestieDev#769]
Hello i just added the questie addon. When i log in i get an error that say 'interface/AddOns/Libs/Callbackhandler- 1.0/Callbackhandler- 1.0.lua:90: unexpected symbol near `...' 
I can't seem to fix it someone here who could help me please?

**Comment by BreakBB** [comment]
Could you try to disable all other addons and try again? Moreover are you using v4.0.15?

**Comment by groentelegger** [comment]
Questie is the only addon i am using. Yea i am using v4.0.15 atm.

**Comment by BreakBB** [comment]
Could you update to 4.0.16 and check again?
