### ISSUE TITLE
Quest "Retrieval for Mauren" not displayed in Stormwind

### ISSUE THREAD

**Issue by hopdenakker** [AeroScripts/QuestieDev#771]
The quest "Retrieval for Mauren" was not displayed on the Stormwind map. See quest details here: https://classic.wowhead.com/quest=1078/retrieval-for-mauren

**Comment by BreakBB** [comment]
Which version of Questie are you using and you fulfill the level 17 requirement, yes?

**Comment by BreakBB** [comment]
Data looks fine on our side. Please try again and reopen this if the quest still doesn't show up.
