### ISSUE TITLE
Dialog Box Missing

### ISSUE THREAD

**Issue by diggerauditor** [AeroScripts/QuestieDev#772]
I started back to wow for classic and wanted I quest helper since it's been so long since I started a new toon. I checked around for a quest helper and found Questie. It was great for a few days and now the dialog box that tells you what quest to take or skip is missing and I do not see any way of getting it back. I've deleted the addon and re-installed it, deleted WTF folder, deleted all addons but nothing. I was using v.4.0.15 beta. Any help would be appreciated.

**Comment by BreakBB** [comment]
That was never a feature of Questie, sorry. You should most likely have a look at the AAP (Azeroth Auto pilot) addon.
