### ISSUE TITLE
Reagents for Reclaimers Inc.

### ISSUE THREAD

**Issue by badtoaster** [AeroScripts/QuestieDev#777]
Questie shows mobs on map only for "Hatefury Claw" but not for "Hatefury Horn".

**Comment by BreakBB** [comment]
Which version of Questie are you using?

[Those mobs](https://classic.wowhead.com/item=6247/hatefury-horn) are included are listed in our data 🤔

**Comment by badtoaster** [comment]
I'm using 4.0.15 BETA. It's auto tracking as quest log but not appears at map and tooltip.

**Comment by Digifais** [comment]
Can confirm this is the case with 4.0.16 Beta as well.

**Comment by BreakBB** [comment]
There was a bug preventing to show more than 1 tooltip on a mob. This is fixed with v4.0.18!
