### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by OldSubSailor** [AeroScripts/QuestieDev#778]
Date: 2019-09-03 11:44:37
ID: 1
Error occured in: Global
Count: 1
Message: [string "Questie:OnUpdate"] line 1:
   attempt to call method 'OnUpdate' (a nil value)
Debug:
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
self = Questie {
 FlyoutBorderShadow = QuestieFlyoutBorderShadow {
 }
 HotKey = QuestieHotKey {
 }
 SpellHighlightAnim = <unnamed> {
 }
 NewActionTexture = <unnamed> {
 }
 cooldown = QuestieCooldown {
 }
 AutoCastShine = QuestieShine {
 }
 Border = QuestieBorder {
 }
 Flash = QuestieFlash {
 }
 AutoCastable = <unnamed> {
 }
 SpellHighlightTexture = <unnamed> {
 }
 Count = QuestieCount {
 }
 Name = QuestieName {
 }
 0 = <userdata>
 FlyoutArrow = QuestieFlyoutArrow {
 }
 icon = QuestieIcon {
 }
 FlyoutBorder = QuestieFlyoutBorder {
 }
}
elapsed = 0.016000
(*temporary) = nil
(*temporary) = QuestieLua {
 FlyoutBorderShadow = QuestieLuaFlyoutBorderShadow {
 }
 CheckPlayerInventory = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:208
 AstroGetFinishedQuests = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:723
 NewActionTexture = <unnamed> {
 }
 SanitisedQuestLookup = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:1035
 lastCollapsedCount = 0
 Border = QuestieLuaBorder {
 }
 Flash = QuestieLuaFlash {
 }
 OnLoad_QuestEvents = <function> defined @Interface\AddOns\!Questie\Questie.lua:225
 getQuestHash = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:1052
 icon = QuestieLuaIcon {
 }
 IsQuestFinished = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:1113
 AutoCastable = <unnamed> {
 }
 MarkQuestAsFinished = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:94
 CreateMinimapButton = <function> defined @Interface\AddOns\!Questie\Modules\QuestieGUI.lua:5
 collapsedThisRun = false
 ParseQuestLoot = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:186
 UpdateGameClientCache = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:292
 UpdateQuests = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:492
 HotKey = QuestieLuaHotKey {
 }
 LoadEQL3Fix = <function> defined @Interface\AddOns\!Questie\Modules\QuestieTracker.lua:693
 AstroGetQuestObjectives = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:795
 finishAndRecurse = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:234
 GetAvailableQuestHashes = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:1194
 AstroGetAllCurrentQuestHashesAsMeta = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:673
 RemoveUniqueSuffix = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:1042
 UpdateQuestIds = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:1006
 GetQuestIdFromHash = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:975
 AutoCastShine = QuestieLuaShine {
 }
 AstroGetAllCurrentQuestHashes = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:632
 FlyoutBorder = QuestieLuaFlyoutBorder {
 }
 SetupDefaults = <function> defined @Interface\AddOns\!Questie\Questie.lua:18
 CheckDefaults = <function> defined @Interface\AddOns\!Questie\Questie.lua:66
 SpellHighlightAnim = <unnamed> {
 }
 UpdateQuestInZone = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:533
 OnLoad = <function> defined @Interface\AddOns\!Questie\Questie.lua:204
 BlockTranslations = <function> defined @Interface\AddOns\!Questie\Questie.lua:195
 0 = <userdata>
 SpellHighlightTexture = <unnamed> {
 }
 CheckQuestLog = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:340
 OnQuestProgress = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:74
 DetectQuestItem = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:164
 Name = QuestieLuaName {
 }
 Count = QuestieLuaCount {
 }
 UpdateQuestsInit = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:600
 FlyoutArrow = QuestieLuaFlyoutArrow {
 }
 cooldown = QuestieLuaCooldown {
 }
 GetQuestObjectivePaths = <function> defined @Interface\AddOns\!Questie\Modules\QuestieQuest.lua:755
}
(*temporary) = nil
(*temporary) = "attempt to call
AddOns:
  Questie, v3.7.1
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  Informant, v8.2.6374 (SwimmingSeadragon)
  Scrap, v13.18
  ScrapSpotlight, v13.18
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=2e1)

**Comment by BreakBB** [comment]
Could you explain when exactly this message appeared? And just to make sure: Could you try to disable all addons except Questie and try again?
