### ISSUE TITLE
Echeyakee spawn missing

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#779]
The spawn of [Echeyakee](https://classic.wowhead.com/npc=3475/echeyakee) is missing in the spawnDB.

This effects [this quest](https://classic.wowhead.com/quest=881/echeyakee)

**Comment by AeroScripts** [comment]
Actually this spawn is in the DB, in Questie_SpecialNPCs.

The recent spawn DB update pulled in all entries (including ones with no spawns) and that prevented it from falling back to Questie_SpecialNPCs

I recently updated the logic to check that table if there are no spawns for the NPC and that has fixed the issue
