### ISSUE TITLE
Tooltips error when category is collapsed

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#78]
The tooltips error when the quest that has the relevant objective is in a category that is collapsed in the quest log. (Categories remain collapsed when the quest log is closed)

"QuestieAstro.lua:406: Usage: SelectQuestLogEntry(index)

**Comment by Schaka** [comment]
That same error isn't entirely linked to a collapsed category. I had the same problem with shift+clicking a random quest. 

Maybe we could replace that code with: 
```
QuestLog_SetSelection(id)
QuestLog_Update();
```

**Comment by AeroScripts** [comment]
This is fixed by this point (I THINK)
