### ISSUE TITLE
Quest "The Perenolde Tiara" (! mark) not showing on map

### ISSUE THREAD

**Issue by bm01** [AeroScripts/QuestieDev#781]
https://classic.wowhead.com/quest=543/the-perenolde-tiara

The (?) mark shows properly in Alterac though.

**Comment by BreakBB** [comment]
That's strange.

The data in our DB looks okay:

```lua
[543] = {"The Perenolde Tiara",{{2285,},nil,nil,},{{2285,},nil,},30,40,77,nil,{"Bring the Perenolde Tiara to Remington Ridgewell in Stormwind.",},nil,{nil,nil,{{3684,nil},},nil,},nil,nil,nil,nil,nil,nil,1519,nil,nil,nil,nil,nil,},
```

**Comment by bm01** [comment]
I relogged then abandoned the quest, and the exclamation mark appeared. Don't know why I wasn't seeing it the first time.

Anyway since it doesn't seem to be an issue related to this quest, I'll just close the ticket.

**Comment by ZioGio** [comment]
I'm experiencing this problem, too.  Relogging and abandoning the quest did _not_ make the exclamation mark appear on my map.
