### ISSUE TITLE
MacBook - green placeholder for icons on map

### ISSUE THREAD

**Issue by mol7os** [AeroScripts/QuestieDev#782]
Current Version have some trouble to show correct items. (there is still a placeholder, green square). Minimap + Map

Additional the tooltip extension does not work.

<img width="175" alt="Bildschirmfoto 2019-09-03 um 19 17 20" src="https://user-images.githubusercontent.com/26004218/64194828-57760980-ce80-11e9-8a8c-102d38755abe.png">
<img width="363" alt="Bildschirmfoto 2019-09-03 um 19 17 03" src="https://user-images.githubusercontent.com/26004218/64194838-58a73680-ce80-11e9-81c9-c300ce025644.png">

Version 4.0.14 looks fine regarding graphics.

**Comment by BreakBB** [comment]
Have a look at [the FAQ](https://github.com/AeroScripts/QuestieDev/wiki/FAQ-for-Classic-(1.13)). Your installation is broken.

**Comment by mol7os** [comment]
Ok, but whats about missing tooltip on Mac?

**Comment by BreakBB** [comment]
There is no functional difference between Windows, Mac or what so ever.

If you have problems with tooltips this is an indicator of using a non English WoW client. We have had a problem with the localization in v4.1.0 but that should be fixed with v4.1.1.
