### ISSUE TITLE
Plague lands quests not populated and each new quest

### ISSUE THREAD

**Issue by Anceane** [AeroScripts/QuestieDev#784]
Questie: [ERROR] [QuestieQuest]: There was an error populating objectives for Plagued Lands 2118 1 Interface\AddOns\Questie\Modules\QuestieQuest.lua:630: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by BreakBB** [comment]
Same as #756 , #761, #768 and #774 

It will be fixed in v4.0.16 which will be released soon ™️

**Comment by Anceane** [comment]
wonderful. As for now this error affect each quests i want to add
