### ISSUE TITLE
The Third Fleet - No icon on map for turn in

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#785]
What the title says.
It's the first part where you have to give him "Flagon of Dwarven Honeymead".

**Comment by BreakBB** [comment]
Are you using Questie v4.0.15?

Our data looks alright:

```lua
[288] = {"The Third Fleet",{{1239,},nil,nil,},{{1239,},nil,},22,27,77,nil,{"Buy First Mate Fitzsimmons a Flagon of Mead.",},nil,{nil,nil,{{2594,nil},},nil,},nil,nil,nil,nil,nil,nil,11,nil,nil,nil,nil,289,},
```

**Comment by Painstormx** [comment]
Yes, I'm using 4.0.15.
I occasionally have some issues with Questie, with wrong or missing icons for specific quests.
A "/console reloadui" usually helps.
Sadly I forgot to try that here before I turned the quest in :(

**Comment by BreakBB** [comment]
Ye, we're having an issue with some desync stuff. But with every version the chance for this will be reduced. Moreover a `/reload` does the same as your command :)

Maybe some other user will find this issue and report if it still exists
