### ISSUE TITLE
“Westbrook Garrison Needs Help!” not appearing on mini-map

### ISSUE THREAD

**Issue by pat0007** [AeroScripts/QuestieDev#789]

**Comment by pat0007** [comment]
<img width="1440" alt="Screen Shot 2019-09-03 at 5 04 14 PM" src="https://user-images.githubusercontent.com/54595000/64211950-7d45e300-ce6d-11e9-92df-b16b74f6d983.png">
<img width="1440" alt="Screen Shot 2019-09-03 at 5 05 09 PM" src="https://user-images.githubusercontent.com/54595000/64211991-90f14980-ce6d-11e9-902c-12503dde38d1.png">
<img width="1440" alt="Screen Shot 2019-09-03 at 5 04 44 PM" src="https://user-images.githubusercontent.com/54595000/64211997-98b0ee00-ce6d-11e9-9f03-fe12479ce4b0.png">

**Comment by AeroScripts** [comment]
Hmm thanks for the report, this presists after /reload right?

I'll check the DB

**Comment by BreakBB** [comment]
Can't find an issue for this. Was most likely #860
