### ISSUE TITLE
Missing quest tracking notes, I found the cause

### ISSUE THREAD

**Issue by ClownCake** [AeroScripts/QuestieDev#79]
I found out that resetting the UI using "AddOnOrganizer" Messes up the notes on worldmap, and it stays like that until WBD folder is removed.

**Comment by ClownCake** [comment]
I also found out that there is another addon that I still have that is causing this. I'm starting to wonder of resetting UI no matter addon causes this. This work to pinpoint what addon is causing what is a hell!

**Comment by Logonz** [comment]
Well, the mapnotes are by themselves frames, so if something is reseting the positon of all frames, it will also reset the mapnote frames.

I would guess a simple reload ui would fix the mapnotes? while this is a bug it may not really be something worth digging to deep into? I'll let you decide, please reply back.

**Comment by ClownCake** [comment]
The problem is that the notes dont get finnished when a quest is completed, and old notes can come back with always one unit missing. (2/3) and I connected this to reloading the UI. In other words, reloading UI causes the Bugg, I think.

**Comment by Sparh4wk** [comment]
this isnt reloadui related at all, its a known bug, was there even in 1.0 version.. devs knows about it and working on it :)

**Comment by ClownCake** [comment]
Are you certain? It's a major, damn annoying problem, if you ask me.

**Comment by Schaka** [comment]
This seems to be related reloading and isn't at all related to the issue we had before (Logonz fixed that a while ago). Though he can probably tell you more specifically what may cause this.

**Comment by ClownCake** [comment]
I've gotten into even more trouble now, questie is not working at all, I've deleted WTF and WDB. It is loaded but I can't see any notes and I can't track any quests. Is there any github-exclusive removal guides for this? Or just ctrl+del the wow directory? Why don't programmes like this come with uninstaller? Way off-topic, sorry. How do I get in touch with Logonz? Are you there logonz? I've got some more bugs to report to.

**Comment by AeroScripts** [comment]
Deleting WTF and WDB + the addons out of interface/addons deletes everything questie touches, if it's still not working past that then there's something else going on.

If you're using master you should definitely get a fresh copy, lots has been done today. (The big release update is coming out real soon)

**Comment by Logonz** [comment]
Well you can get a hold of me here on github, if you have more issues add more to the issue tracker!

From what you seem to be describing it's orphaned notes? Aka notes that never disapear? Or are you talking about them drawing in the wrong positions?

**Comment by ClownCake** [comment]
Never disappear, exactly. The strange thing is that it can go back to normal just like that. I'll investigate this more. I've been addoning my wow for two days, why not a third?

**Comment by AeroScripts** [comment]
This should be fixed with 2.0.0, closing for now
