### ISSUE TITLE
"Into The Scarlet Monastery" is not tracked by Questie

### ISSUE THREAD

**Issue by Firkraag8** [AeroScripts/QuestieDev#790]
This quest does not show up on the mini or world map, I have the latest version installed:
https://classic.wowhead.com/quest=1048/into-the-scarlet-monastery

![image](https://user-images.githubusercontent.com/41156706/64212686-82755300-ceaa-11e9-90a7-18462dfb70da.png)

**Comment by AeroScripts** [comment]
There seems to be a general issue with available dungeon quests at the moment, many others are also not showing as available ill look into it shortly

**Comment by BreakBB** [comment]
The data on our side looks alright.
