### ISSUE TITLE
Finding the antidote (9) remains showing after completion 

### ISSUE THREAD

**Issue by AcidDopeWave** [AeroScripts/QuestieDev#791]
Finding the antidote (9) remains showing after completion on v4.0.14 & v4.0.15. During the mission after reaching the guy in the city to request a potion and grabbing the stage of the quest to collect things it became available to grab the first part again, I didn't click it at the time due to being a timed mission - not sure if this was on the mod end or game end as could request the quest. After completing the quest went back, the marker still remains but the option to talk and re grab the second stage of the quest is no longer there.

**Comment by AeroScripts** [comment]
The reason for this is it's a repeatable quest, but only when you have the other quest in your log

There's a fix coming in .16 which is going up today. It should fix all repeatable subquests like this one

**Comment by BreakBB** [comment]
Please test again @AcidDopeWave This should be fixed
