### ISSUE TITLE
Destiny Call's

### ISSUE THREAD

**Issue by Ycatam** [AeroScripts/QuestieDev#792]
Hi,
A rogue night elf quest called destiny calls isn't tracked and don't show the location of the mob on the map. Attachments will help to solve this. Hope it helps.

![destiny calls location](https://user-images.githubusercontent.com/54875451/64221946-f3b20780-cea4-11e9-9027-bbd28ec3b34b.jpg)

**Comment by AeroScripts** [comment]
Hmm, looks to be an issue with "pickpocketed from" items, they don't show at all currently.

I'll try to figure out a general fix, should be good in the next update

**Comment by Ycatam** [comment]
Thanks for the quick reply! You are making an awesome work with this addon! I use the !Questie in vanilla private servers. I'm learning to code too, hope I'll help you somehow in the future.
