### ISSUE TITLE
Quest Missing: Finding the Antidote (813)

### ISSUE THREAD

**Issue by Bynrolan** [AeroScripts/QuestieDev#793]
Leveling in Durotar. This quest is tied to the timed quest to fetch 4 venom sacs to save a troll in 45 minutes.  The quest is left open in case you don't get there in time and need to try again.  I was able to complete it, and yet now Questie is stuck with the message "Quests Missing: Finding the Antidote (813)"  Can't pick up the quest again, as it is done, and even in my log in Questie.

**Comment by AeroScripts** [comment]
This is an AAP bug actually

**Comment by Jhandy93** [comment]
I'm not sure if its a real fix but I just clicked reset questie in the advanced tab and it worked for me
