### ISSUE TITLE
Quest little Bug : Durotar 'Need a Cure'

### ISSUE THREAD

**Issue by WFR79** [AeroScripts/QuestieDev#796]
It doesn' show the Question mark on the minimap for the thirst act of the quest which is bringing back the Antidote to Rhinag.

Regards.

**Comment by AeroScripts** [comment]
Hmm, something must be wrong with the data. Just to be totally sure, you tried /reload right?

What questie version are you on? I'm going to test this quest myself shortly to see whats up

**Comment by WFR79** [comment]
V4.0.12 Beta

**Comment by AeroScripts** [comment]
This may be fixed in 4.0.16, there were some changes to subquests and improvements to desync
