### ISSUE TITLE
Screecher Spirits

### ISSUE THREAD

**Issue by Phred88** [AeroScripts/QuestieDev#797]
The quest Screecher Spirits (as alliance player don't know if this matters) keeps giving me this error:

There was an error populating objectives for Screecher Spirits 3520 1
Interface\Addons\Questie\Modules\QuestieQuest.lua:630: bad argument #1 to 'pairs' (table expected, got nil)

Please fix :)
Kind regards

**Comment by AeroScripts** [comment]
Have you tried on v4.0.16? That contains a fix for "spawned by a script or item"-type mobs, and this seems to be one of them
