### ISSUE TITLE
Seperate icon toggles for map and minimap

### ISSUE THREAD

**Issue by mawmaw1** [AeroScripts/QuestieDev#799]
Would it be possible to implement seperate toggles for icons shown on map and minimap respectively?

For example I would like to disable quest objectives on the minimap, but keep Available / Completed quest icons.

**Comment by AeroScripts** [comment]
Yeah this was added in recent releases actually, main options tab now has separate "enable map icons" and "enable minimap icons" checkboxes

**Comment by mawmaw1** [comment]
Sorry I should have clarified. I already saw that update and appreciate it a lot!
But the thing I am requesting extends on that.

I would like to be able to individually toggle the different options seperately for the big map and the minimap.

Like for example only have the Available and Completed quest icons on the minimap, but ALL objects on the main map. That's not possible right now as far as I can see.

**Comment by AeroScripts** [comment]
Ahh, yeah that would be useful to have, we should be able to add it sorry for closing so quickly

**Comment by Gogo1951** [comment]
I think the toggles should be:

* Show on Minimap
* Show on Zone Map
* Show on World Map

The later is from here https://github.com/AeroScripts/QuestieDev/issues/896

**Comment by Jinnai** [comment]
Any update on this? I would appreciate the option to toggle icons separately for the zone and continent map.

**Comment by BreakBB** [comment]
@Jinnai Sorry for the late response on this. No we didn't target this yet. We are very limited in time and manpower.

**Comment by AeroScripts** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.
