### ISSUE TITLE
Addon Folder Layout

### ISSUE THREAD

**Issue by abennette32** [AeroScripts/QuestieDev#8]
In order to ease installation, the addon should be a single folder. I think this would help a little bit for explaining how to install. *(I wrote the guide on the wiki, but it's still a little confusing)*

**Comment by AeroScripts** [comment]
A lot of this stuff is still up in the air, it's possible at some point we'll be able to move it all into a single folder but for the time being it's making use of external mods, and merging together with them would cause a bit of chaos.

Ideally yes it would be better as a single folder, it's just not possible yet.

**Comment by Logonz** [comment]
No.
We are moving questie to a single folder install, but inside questie will always be several folders to help the developers organize.
