### ISSUE TITLE
Show quest rewards

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#802]
It would be nice if quest rewards would be shown in the journey and when hovering with shift over a quest.

**Comment by BreakBB** [comment]
Related to #316 and #420

**Comment by BreakBB** [comment]
XP reward has been added with: 37c64670c6332ab0dab42c3f3a88b4782ef896b6

Money reward has been added with: 464cf597e4b7cae69b250e6e773a94f2ea1f94a6

**Comment by Gogo1951** [comment]
Added money, added XP... showing items seems like a lot of work without a lot of reward.

Maybe we can revisit this in the future, but there are higher priority things we need to look at first.
