### ISSUE TITLE
Deeprun Rat Roundup bad argument

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#803]
Hello, 
 
while doing the Quest Deeprun Rat Roundup i recieved a message in my chat from Questie with the error

https://imgur.com/VaNEXSs

**Comment by BreakBB** [comment]
Did you use Questie v4.0.16 while this error appeared?

**Comment by reaper666735** [comment]
yes :), i always check for the latest version ^^

**Comment by AeroScripts** [comment]
I checked the data for this today, the spawns are excluded because theres currently no way to show icons (minimap or map) in instances

The error should probably not be shown in this case though

**Comment by BreakBB** [comment]
Closing this i favor of #837 We should really catch this error
