### ISSUE TITLE
Quests shown as available while already picked up

### ISSUE THREAD

**Issue by pejub** [AeroScripts/QuestieDev#804]
At Crossroads logging in for the first time today, and it seem many of the quests I've picked up  and completed are listed as available.

**Comment by pejub** [comment]
After awhile, I don't think I did anything. All looked as expected.

**Comment by Claisen10M** [comment]
I the same issue, many of the quests I had already picked up showed up on the map as available for pickup. I discovered I could resolve the issue by dropping / re-picking up the quest or just completing the quest, though for awhile, it cluttered up my map with a bunch of quests I had already picked up.

**Comment by AeroScripts** [comment]
Hmm, What version of questie are you using

This may be cleared up with /reloadS
Sorry to anyone experiencing this, we're looking in to it

**Comment by Claisen10M** [comment]
I'm currently on 1.13.2. I hadn't logged in 2 days, so its possible that the version updated between plays, and that led to the issue. Doing a /reload did resolve the issue though. So that is a quick workaround.

**Comment by AeroScripts** [comment]
What questie version though? We did push some fixes recently, if you're on a questie earlier than v4.0.14 that could be why

**Comment by Claisen10M** [comment]
Oh, I looked at the wrong version in the twitch Mod section. I'm on Questie-v4.0.13

**Comment by AeroScripts** [comment]
Ahh, try updating, v4.0.16 is on twitch but you might need to go to the versions tab

**Comment by Claisen10M** [comment]
Also, thanks for this Mod. Its been fantastic help with leveling. I was initially enjoying figuring out the quests, but I kept on missing too many quests and being very inefficient, so this has helped me not miss nearby quests.

**Comment by Claisen10M** [comment]
Issue did not reappear on updating to the latest version. Even if it does re-appear, the /reload worked to resolve it. Thanks much for the assistance.

**Comment by AeroScripts** [comment]
Sweet, good luck glad its figured out :D
