### ISSUE TITLE
Quest Trial of the Sea Lion (druid) shows wrong location

### ISSUE THREAD

**Issue by Hoesa** [AeroScripts/QuestieDev#807]
So for me an alliance druid, the quest Trial of the Sea Lion shows the horde location to get the Half Pendant of Aquatic Endurance. The alliance location is in westfall (18,33). The other half shows the correct location.

**Comment by algometric** [comment]
+1, it's showing at 68, 30 on my world map but should be off the coat of Westfall as noted above.

**Comment by AeroScripts** [comment]
I thought this was already reported on github but apparently not

I'll fix it shortly, there's something wrong with the faction requirement data for the objectives
