### ISSUE TITLE
Tracker bugs in 1.1beta

### ISSUE THREAD

**Issue by Sparh4wk** [AeroScripts/QuestieDev#81]
Hi, first I wanna thanks for overhaul of tracker, it seems much cleaner etc then it was before.
Second, I want to open this to submiting some bugs with tracker atm. (maybe u already know them)

1. Items and sometimes kills doesnt count right (As you can see I have 2 quest items already in my inventory, but tracker said otherwise) Tryed relog and deleting WTF questie files, didnt work.
![1](https://cloud.githubusercontent.com/assets/7014826/7495961/9725d09a-f411-11e4-9eae-8688afd9de51.png)

2. If you accept quest that have more then one line objective, tracker doesnt show them (it does if you manually remove that quest from tracker and readd it via shift+click)
![2](https://cloud.githubusercontent.com/assets/7014826/7495991/be0fb0a4-f411-11e4-984b-4a39362d2862.png)

3. Some quest are not displayed if you accept them, you must relog to be able to see them in tracker (cant make proper screenshot of this bug) They cant be even added manually, even that questiedebug window told me that "Added QuestInfo to Tracker - Time: 0ms".

I know tracker is WIP, but I rather report this to be sure.. if u know about all of this, just close it

**Comment by AeroScripts** [comment]
Yeah, I'd recommend trying the latest revisions, this issue -should- be fixed now.

We are aware of these issues, but thanks for reporting them anyway. I'll leave this open until I can verify that they're actually properly fixed.

**Comment by AeroScripts** [comment]
These still aren't fixed, work is being done on them now, will post back with info as they're fixed.

**Comment by Sparh4wk** [comment]
yep I know, just wanted to post these..
![1](https://cloud.githubusercontent.com/assets/7014826/7501384/bed8fed8-f433-11e4-9d26-4f9e5db959d8.png)
![2](https://cloud.githubusercontent.com/assets/7014826/7501383/bed89fd8-f433-11e4-9dd3-cea929bc2db4.png)
![3](https://cloud.githubusercontent.com/assets/7014826/7501382/bed7342c-f433-11e4-9d27-0a8ee86d5009.png)

**Comment by AeroScripts** [comment]
issue 1 and 2 should be fixed with 6962ea6cd2534a0d6d096b758ed532c884c79609 Still working on 3

**Comment by Sparh4wk** [comment]
yep, seems like it.. will test it more tommorow morning.. butw another issue.. its not exactly bug, but quests without objectives arent tracked.. I mean quests like: The Spirits of Stonetalon or Returning the Lost Satchel etc...

**Comment by AeroScripts** [comment]
I THINK all of these are fully fixed in the latest revisions now.

**Comment by MOUZU** [comment]
latest revision has a major bug, I just ended in an endless loop, lowering my fps so that I thought it could crash the client completely
![endlessloop](https://cloud.githubusercontent.com/assets/6463720/7533538/a2433f3c-f572-11e4-94a8-c801d52e774a.jpg)

**Comment by Sparh4wk** [comment]
almost perfect.. just adding new screenshot.. two quests are not tracked and cant be even manually
![1](https://cloud.githubusercontent.com/assets/7014826/7534840/da8875ae-f57e-11e4-9123-13dd86ba8179.jpg)

as you can see Report to Anastasia and Ziz Fizziks arent tracked..
btw is it possible to make EQL tracking detection? 
As you can see there are quests that I tracking atm but are not mark with checked in EQL :(

**Comment by Schaka** [comment]
We know what the bug is and it's gonna be fixed when we officially release 2.0 tonight
