### ISSUE TITLE
Curing the Sick

### ISSUE THREAD

**Issue by algometric** [AeroScripts/QuestieDev#814]
Druid class quest, level 14, Alliance, Classic (1.13.2), Questie v4.0.16 Beta.

[QuestieQuest]: There was an error populating objectives for Curing the Sick 6124 1 Interface\AddOns\Questie\Modules\QuestieQuest.lua:648: bad argument #1 to 'pairs' (table expected, got nil)

The objective of the quest is to use the Curative Animal Salve to cure 10 sickly deer. I'm assuming it tried populating the minimap with deer and failed?

**Comment by AeroScripts** [comment]
Hmm, database seems to be pointing to "cured deer" which has no spawn points, instead of sickly deer (which has spawns)

I'll fix that now, should be good in the next update thanks for reporting <3

**Comment by algometric** [comment]
Makes sense! They become cured after you use the item on them (and so are the actual quest objective). Thanks for the timely response!
