### ISSUE TITLE
The Black Shield extra quest at the end

### ISSUE THREAD

**Issue by xerxespersrex** [AeroScripts/QuestieDev#815]
The Black Shield questline says that there's a follow-up part 4 to bring the shield to Mosarn in Thunder Bluff. This is not appearing for me and Wowhead says that this quest step wasn't added until patch 4.0.1.12984. Source: https://www.wowhead.com/quest=27258/the-black-shield

**Comment by AeroScripts** [comment]
Hmm are you sure the quest isn't in classic? https://classic.wowhead.com/quest=1276/the-black-shield
it is on the classic wowhead, with a much lower quest ID (the one questie has)

We can hide the quest, but maybe there is some other requirement that's making it not be available in game (the quest does exist in the game files)

**Comment by AeroScripts** [comment]
Some of the old wowhead comments are suggesting you need to complete the other parts of the quest (the other items in the inn) before the final step is actually available, maybe that's whats going on

**Comment by xerxespersrex** [comment]
That would make sense, I haven't completed Questioning Reethe yet (too hard for me to do solo at the moment).

**Comment by AeroScripts** [comment]
hmm well if that is the case, ill add them as requiredquests for the final part, so it doesn't incorrectly show as available

**Comment by xerxespersrex** [comment]
I just finished Questioning Reethe and the quest to talk to Mosarn in TB popped up (had done all other available inn quests beforehand).

**Comment by BreakBB** [comment]
Thanks for keeping us updated @xerxespersrex I've added the prequest to the last part of The Black Shield.
