### ISSUE TITLE
Quest objective descriptions missing, only quest title and numbers on GameTooltip.

### ISSUE THREAD

**Issue by kuletco** [AeroScripts/QuestieDev#816]
I'm using Chinese client of Wow, but when I point to a quest unit in the world or on world map, the quest objectives descriptions missing and only left quest title and numbers on mouse tooltip.

So, I read your code and find a problem that the symbo ':' is different from English to Chinese.
**The bug point at Questie\Modules\QuestieQuest.lua:962**
May be other Language has the same language.

Questie version is v4.0.16

**_Then I try to fix this like below:_**
-- local itemName, numItems, numNeeded = string.match(description, "(.\*):%s*([%d]+)%s*/%s*([%d]+)");
local itemName, numItems, numNeeded = nil,nil,nil
if GetLocale() == "zhCN" then
        &emsp;-- string.match() can not properly split Chinese text.
        &emsp;-- keep the split '：' symbo in Chinese, it will at the end of desc.
        &emsp;itemName, numItems, numNeeded = string.match(description, "(.\*)%s*([%d]+)%s*/%s*([%d]+)");
        &emsp;-- cut off the end symbo '：'
        &emsp;itemName = string.sub(itemName, 1, -4);
else
        &emsp;itemName, numItems, numNeeded = string.match(description, "(.\*):%s*([%d]+)%s*/%s*([%d]+)");
end

**Comment by ayrb13** [comment]
your code could solve this problem

**Comment by tytannial** [comment]
Try this 😄 
`
itemName, numItems, numNeeded = string.match(description, "(.*)：%s*([%d]+)%s*/%s*([%d]+)");
`

**Comment by kuletco** [comment]
> 
> 
> Try this 😄
> `itemName, numItems, numNeeded = string.match(description, "(.*)：%s*([%d]+)%s*/%s*([%d]+)");`

I had try like this. But an unreadable symbol will appear at the end of itemName.
Therefore, I don't think string.match has perfect support for double-byte characters.

Perhaps we need to wait for the author to switch to UTF8 for strings.

**Comment by tytannial** [comment]
> > Try this 😄
> > `itemName, numItems, numNeeded = string.match(description, "(.*)：%s*([%d]+)%s*/%s*([%d]+)");`
> 
> I had try like this. But an unreadable symbol will appear at the end of itemName.
> Therefore, I don't think string.match has perfect support for multibyte characters.
> 
> Perhaps we need to wait for the author to switch to UTF8 for strings.

Exactly.

**Comment by BreakBB** [comment]
Sorry for not getting to this for so long. We updated our regex with 746491b7cb203107a5b9e7c25437c2af4025f04a . Please check again with 4.1.1 and report back!

**Comment by tytannial** [comment]
> Sorry for not getting to this for so long. We updated our regex with [746491b](https://github.com/AeroScripts/QuestieDev/commit/746491b7cb203107a5b9e7c25437c2af4025f04a) . Please check again with 4.1.1 and report back!

![20190921131733](https://user-images.githubusercontent.com/11215623/65368347-61667d80-dc72-11e9-94e3-05439b7bef61.png)
As you can see, there is a '?' at the end of the objective text in lang zhcn.

**Comment by kuletco** [comment]
> 
> 
> > Sorry for not getting to this for so long. We updated our regex with [746491b](https://github.com/AeroScripts/QuestieDev/commit/746491b7cb203107a5b9e7c25437c2af4025f04a) . Please check again with 4.1.1 and report back!
> 
> ![20190921131733](https://user-images.githubusercontent.com/11215623/65368347-61667d80-dc72-11e9-94e3-05439b7bef61.png)
> As you can see, there is a unexpected '?' at the end of the objective text in lang zhcn.
> 
> These quests are
> quest=228 morladim,
> quest=1363 mazens-behest,
> quest=659 hints-of-a-new-plague,
> quest=1387 centaur-bounty,
> quest=504 crushridge-warmongers.

**Comment by kuletco** [comment]
Sorry, I accidentally clicked close

**Comment by tytannial** [comment]
> Sorry, I accidentally clicked close

😂

**Comment by kuletco** [comment]
> 
> 
> Sorry for not getting to this for so long. We updated our regex with [746491b](https://github.com/AeroScripts/QuestieDev/commit/746491b7cb203107a5b9e7c25437c2af4025f04a) . Please check again with 4.1.1 and report back!

Thank you for your fix, perhaps we can replace "：" with ":".
I tried like this, it works fine.
![图片](https://user-images.githubusercontent.com/8363656/65370805-5e2dba80-dc8f-11e9-8294-3f9c9d8d041e.png)

**Comment by BreakBB** [comment]
Of cause we could do this, but I am not sure if this is a better solution than a regex with two possibilities. Since we would iterate the string more than once :thinking:

**Comment by tytannial** [comment]
quest=578, The Stone of the Tides
quest=201, investigate-the-camp
there is a ":" at end of the the questobject text.
![20190923115240](https://user-images.githubusercontent.com/11215623/65401162-d6fc5600-ddf8-11e9-904b-1f2c5db2fccc.png)

**Comment by kuletco** [comment]
> 
> 
> quest=578, The Stone of the Tides
> quest=201, investigate-the-camp
> there is a ":" at end of the the questobject text.
> ![20190923115240](https://user-images.githubusercontent.com/11215623/65401162-d6fc5600-ddf8-11e9-904b-1f2c5db2fccc.png)

I have found the cause of your problem, but I can't test it. If you can test it, please try my changes.
**Questie\Modules\QuestieTracker.lua**
![图片](https://user-images.githubusercontent.com/8363656/65441233-a2ba8100-de5c-11e9-8d0f-d767b0ab1c61.png)
I think the author has not considered the empty state of 'lineEnding'. Therefore, it is more appropriate to put ':' in 'lineEnding'.

**Comment by BreakBB** [comment]
Please let me know if this isn't fixed with v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2

**Comment by tytannial** [comment]
#1193 Unexpected "?".

**Comment by SqiChiu** [comment]
> Please let me know if this isn't fixed with v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2

no fix

**Comment by BreakBB** [comment]
@SqiChiu Sorry for the late response on this. We had a big flaw with fixing this, but it is fixed now on master and will be released with v4.1.3 very soon
