### ISSUE TITLE
Quests by Level Request

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#817]
This is actually a double-but-related request:
1) have the quests in the Quests by Zone tab be sorted by level (or have the option to do so, if there are other useful sorting options)
2) have another tab listing all available quests by level, regardless of zone

**Comment by Gogo1951** [comment]
Hey @Cerby3BR ,

Is this issue still relevant, if not please close. Thanks!

**Comment by BreakBB** [comment]
This issue is being closed because some or all of the requested functionality has already been addressed in other features or fixes.
