### ISSUE TITLE
wrong quest! 

### ISSUE THREAD

**Issue by zeon91** [AeroScripts/QuestieDev#82]
Quest= Recover the key! 
Problem=wrong objective ,questie show mark on booty bay on elite gorillaz.
qwest=Kill on sight :dark iron dwarves
Problem= questie show wrong mark on orgrimmar o_O
Quest= http://db.valkyrie-wow.org/?quest=3463 Set Them Ablaze!
Problem= missing in database  in questie

**Comment by AeroScripts** [comment]
This has been added along with 977 other missing quests in recent commits:
 ["Set Them Ablaze!"]={
  ["Set the North, South, East, and West Sentry Towers on fire by using the Torch of Retribution inside each of the buildings. \n"]={0,151727432},
 },

Fix will be included in the next release (that's coming out tonight)
