### ISSUE TITLE
Quest "Deviate Hides"

### ISSUE THREAD

**Issue by mMaxPnz** [AeroScripts/QuestieDev#822]
## Bug description
1. Quest "Deviate Hides" (Шкуры загадочных существ) not in Durotar.

## Screenshots
![WoWScrnShot_090519_192824](https://user-images.githubusercontent.com/3320989/64360834-ed8e6900-d013-11e9-9298-de9a738af6bb.jpg)

## Questie version
Questie v4.0.16 BETA

**Comment by BreakBB** [comment]
I can confirm this and [Deviate Eradication](https://classic.wowhead.com/quest=1487/deviate-eradication) is listed as well.

![image](https://user-images.githubusercontent.com/33514570/64443304-eb8adf80-d0d1-11e9-9b9d-e04d2eb98570.png)

**Comment by BreakBB** [comment]
Luna and I found out that this can be linked to issues in our database.

[Ebru](https://de.classic.wowhead.com/npc=5768/ebru) starts the Eradication quest but has spawn locations listed in Durotar, The Barrens and Mulgor.

And NPCs like [Deviate Coiler](https://classic.wowhead.com/npc=3630/deviate-coiler) are listed to spawn in all those three locations as well.

**Comment by BreakBB** [comment]
Fixed with 4be02d124cef1fa913bff24eef2a549c1365502c
