### ISSUE TITLE
Repeatable Hinterlands quest map marker:  Troll Necklace Bounty

### ISSUE THREAD

**Issue by AnnaManiac** [AeroScripts/QuestieDev#823]
## Description

The Dwarf NPC Fraggar Thundermantle offers the quest Troll Necklace Bounty to turn in 
5 Troll Tribal Necklaces.  It is repeatable and will continue to show on the map after more than one turn-in.

## Wowhead link

https://classic.wowhead.com/quest=2880/troll-necklace-bounty

## Screenshots
Screenshot attached.

## Questie version

Version 4.0.16 Beta
![World Of Warcraft Screenshot 2019 09 05 - 13 13 52 87](https://user-images.githubusercontent.com/54857214/64364031-139a1600-cfe0-11e9-95b3-a15f542f0b2c.png)

**Comment by BreakBB** [comment]
This should be fixed with the latest release v4.0.17 👍
