### ISSUE TITLE
Missing Gnomeregan quests on the map

### ISSUE THREAD

**Issue by dsumaneev** [AeroScripts/QuestieDev#825]
## Description
These quests are not showing neither on my map nor on my minimap. I can pick them up though.
1. Save Techbot's Brain!
2. Find Bingles
3. The Day After

## Wowhead link
1. https://classic.wowhead.com/quest=2922/save-techbots-brain
2. https://classic.wowhead.com/quest=2039/find-bingles
3. https://classic.wowhead.com/quest=2927/the-day-after

## Questie version
v4.0.16

**Comment by BreakBB** [comment]
Thanks for those reports! I have had a look into it and your 2. and 3. quest were related to a wrong spawn location of "Gnoarn" which has been fixed with 985d873cca4c853dcb3b3b32dbc02a8884471f60

For your first quest I couldn't find any issues except that we have a prequest listed. Could you run a command to see if you completed the quests up front?

`/dump IsQuestFlaggedCompleted(2923)`

**Comment by iBaldv5** [comment]
I ran into this issue as well and I've confirmed the breadcrumb quest [TinkMaster Overspark](https://classic.wowhead.com/quest=2923/tinkmaster-overspark) is not required for [Save Techbot's Brain](https://classic.wowhead.com/quest=2922/save-techbots-brain). There is also a comment on [TinkMaster Overspark](https://classic.wowhead.com/quest=2923/tinkmaster-overspark) mentioning that they believe this quest is no longer needed for [Save Techbot's Brain](https://classic.wowhead.com/quest=2922/save-techbots-brain).

I tested your command and confirmed it comes back false as I have not completed [TinkMaster Overspark](https://classic.wowhead.com/quest=2923/tinkmaster-overspark). Both [TinkMaster Overspark](https://classic.wowhead.com/quest=2923/tinkmaster-overspark) and [Save Techbot's Brain](https://classic.wowhead.com/quest=2922/save-techbots-brain) are available for me to pick up on my Level 24 character.

**Comment by BreakBB** [comment]
Thanks to @iBaldv5 the first reported quest should be fixed with  4509214 as well.
