### ISSUE TITLE
Elune's Grace

### ISSUE THREAD

**Issue by Lorimus** [AeroScripts/QuestieDev#828]
4.0.16

I reached level 20 as a Priest, and Questie appropriately showed me my Priest trainer had a quest, Elune's Grace for me.  However, I have completed the quest, but Questie is still showing it available.

**Comment by AeroScripts** [comment]
Usually with these sort of class quest bugs it ends up being extra IDs in the database (since there are copies of the quest for each priest race)

I'll check the data, should be an easy fix

**Comment by BreakBB** [comment]
Can't find an issue in our data. Most likely has been related to #860 

if this isn't fixed in the latest release please report back @Lorimus
