### ISSUE TITLE
Eitrigg's The New Horde

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#830]
[1] The New Horde, the breadcrumb quest that apparently should lead Tauren and Forsaken players to the Valley of Trials, is not available for my Tauren character. Could it have been scrapped, and if so, should it be removed from the Questie listings?

https://classic.wowhead.com/quest=787/the-new-horde

Using Questie 4.0.16
![WoW Questie Eitrigg The New Horde](https://user-images.githubusercontent.com/54936174/64391704-116ca180-d04a-11e9-9a2c-a91bda34926f.png)

**Comment by AeroScripts** [comment]
Hmm, and just to be sure, you haven't done any of the followups (your place in the world, cutting teeth)?

Possibly it was removed, but maybe it's being locked out by something else. Will test and figure out the correct behavior
For now you can shift+click the icon to hide it. Thanks for reporting 🎊

**Comment by Cerby3BR** [comment]
Nope, I specifically headed straight to Org from Mulgore to do the quests in the correct order. A few possibilities I have in mind are it being only for Forsaken for some reason, or having to complete some questline or other in Mulgore/Tirisfal. This may be a bitch to test, sorry. ^^'

**Comment by Cerby3BR** [comment]
Same deal with my Troll bank alt, who didn't do any quests at all: Eitrigg just says hello, yet Questie says the quest is available for her. Gonna roll a Forsaken and march it to Org for further testing.

**Comment by AeroScripts** [comment]
Actually it's not too bad since its a level 1 quest, much easier than most things actually.

The quest might actually be bugged also, there are some missing quests on classic atm which blizzard has confirmed (ex. #682 )

**Comment by Cerby3BR** [comment]
Yeah, but I'm a completionist like that. ^^' Anyway, ran a new Forsaken to Org, still nothing from Eitrigg. I agree, it's entirely possible it fell between the cracks like that repeatable Chen quest, in which case it might be a good idea to leave it in Questie for now in case they put it back in. I'll send a ticket to Blizz.

**Comment by AeroScripts** [comment]
Might want to wait on the ticket until it can be tested more. I just made a level 1 forsaken to see if I can pick it up, will post back shortly

**Comment by AeroScripts** [comment]
Yeah, it's also not available as a level 1 forsaken, and there seems to be a lot of stuff online that suggests it did exist in vanilla

**Comment by Cerby3BR** [comment]
Ok, I think I have an idea about what's going on.

The New Horde is one of two quests that lead to Cutting Teeth, the other breadcrumb being Your Place In The World which is given by Kaltunk right in front of new Orc and Troll characters.

TNH isn't being offered to any race, but YPITW is available for all 4.

I think that YPITW or TNH being offered is a mutually exclusive thing, where if you can do one the other is unavailable, but Blizzard messed up the tags and made YPITW show up for all Hordies. I'll try to confirm once a GM contacts my ticket.

Another, related thing, this time Questie-wise: TNH shows up on the map for all 4 races as soon as they spawn, but YPITW only shows up for new Orcs and Trolls even though it can be done by Tauren and Forsaken too... except it *does* show up on the map for my lvl5 Tauren. What's up with that?

**Comment by Cerby3BR** [comment]
![WoW Questie Eitrigg GM Response](https://user-images.githubusercontent.com/54936174/64541323-f89e0d80-d321-11e9-9fe8-e91341c2cfe1.png)

Got the response, The New Horde just plain isn't in the game anymore and has been replaced with You Place in the World for all Horde races.

**Comment by AeroScripts** [comment]
Wow interesting, ill correct it in the DB thanks for posting back
