### ISSUE TITLE
Quest "Kodo Hide Bag" requires leatherworking

### ISSUE THREAD

**Issue by nwn** [AeroScripts/QuestieDev#831]
[Kodo Hide Bag](https://classic.wowhead.com/quest=769/kodo-hide-bag) is being shown as available, but should not be without Leatherworking 10.

**Comment by BreakBB** [comment]
We're not yet checking the profession of a player, sorry. We will add it though.

Related to #488 , #732

**Comment by BreakBB** [comment]
This quest will be hidden for now.
