### ISSUE TITLE
Hovering over quest icons throws LUA error

### ISSUE THREAD

**Issue by AtairWoW** [AeroScripts/QuestieDev#832]
Hi there,
really great and helpful addon.

Unfortunately, there are several quests shown which:
a) I don't meet the requirements, e.g. the profession stuff (there are other bug reports for those) but also others.
b) I simply do not want to do.

I repeatedly catch myself running to those quests and then recognize it's the one quest I can't acceppt or don't want to do.

So, is it possible to add an option to ignore specific quests? Maybe vie context menu (similar to TomTom).

**Comment by AeroScripts** [comment]
If you encounter a quest that you can't actually accept its best to report it in the database

Recent updates added a way, you can now CTRL+Click available icons to hide them. v4.0.15 or newer can do this

**Comment by AtairWoW** [comment]
Ah, cool, that's what I needed, thanks.

Unfortunatly there's LUA errors on lots of quests with when hovering the icon with Shift pressed:

`Message: ...nterface\AddOns\Questie\Modules\QuestieFramePool.lua:462: bad argument #1 to 'pairs' (table expected, got string)
Time: Fri Sep  6 10:06:55 2019
Count: 5
Stack: ...nterface\AddOns\Questie\Modules\QuestieFramePool.lua:462: bad argument #1 to 'pairs' (table expected, got string)
[C]: in function `pairs'
...nterface\AddOns\Questie\Modules\QuestieFramePool.lua:462: in function `_rebuild'
...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:396: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:391>
[C]: ?
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ce\AddOns\Details\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\AddOns\Details\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>`



Not accepptable quest list so far:

- "Badlands Reagent Run II" in Thelsamar (requires alchemy iirc)
- "Replacement Phial" in IF (showed up before I was on "Back to Uldaman")

(the rest seems to have been fixed in the meantime, like the grave quest in Duskwood)

**Comment by AeroScripts** [comment]
Hmm and what version of questie are you on? I believe that bug is also fixed in v4.0.16 (If its not, its fixed in the next update coming out in a few hours)

Sorry it's been giving you so much trouble

**Comment by AeroScripts** [comment]
Thanks for reporting the quests ill check the data. I believe reagent run 2 is also fixed. Phial I haven't heard of yet ill look into the data <3

**Comment by AtairWoW** [comment]
I'm on 4.0.16

**Comment by AeroScripts** [comment]
Ahh my mistake, looks like it just missed the .16 update, should be good in .17

**Comment by BreakBB** [comment]
@AeroScripts Is this fixed?

**Comment by BreakBB** [comment]
Please report back if this isn't fixed in v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2
