### ISSUE TITLE
Missing Quest : 4921

### ISSUE THREAD

**Issue by Trozy** [AeroScripts/QuestieDev#833]
## Bug description
missing quest : 4921 - just cant get past this doesnt matter how many quest i complete

## Questie version
4.0.16
2019-09-03

**Comment by AeroScripts** [comment]
4921 is in questie's database, but "missing quest" sounds like azeroth autopilot.

If it is AAP, you may be able to fix it with /aap skip

**Comment by Trozy** [comment]
OMG, im blonde, THANK YOU... im so sorry i thought this was a questie problem... erf... thanks again

**Comment by AeroScripts** [comment]
Glad thats figured out lol
