### ISSUE TITLE
Missing Quest Tooltip on Mob (Westfall)

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#834]
## Description

just missing the Quest Tooltip added by Questie on the mobs related to the quest below :)

## Wowhead link

Quest:  https://classic.wowhead.com/quest=13/the-peoples-militia 

NPC's:  https://classic.wowhead.com/npc=589/defias-pillager ; https://classic.wowhead.com/npc=590/defias-looter

## Questie version

4.0.16

**Comment by AeroScripts** [comment]
Just to be sure, are you on english client or what language?

**Comment by reaper666735** [comment]
English :p

**Comment by AeroScripts** [comment]
Hmm, ill do some testing soon thanks for reporting

**Comment by reaper666735** [comment]
it could because there are 3 Quests in Westfall from the same series with the exact same name :p , only via QuestID and the objectives could you even differentiate them ^^

**Comment by BreakBB** [comment]
The data looks fine on this on our side. Maybe related to the desync bug @AeroScripts ?

**Comment by reaper666735** [comment]
well it was from the addon a phew versions back it could have been fixed by now :p

**Comment by BreakBB** [comment]
Assuming this is fixed
