### ISSUE TITLE
To Steal From Thieves

### ISSUE THREAD

**Issue by Leander30** [AeroScripts/QuestieDev#835]
The quest: To Steal From Thieves is not showing up as available in Undercity

https://classic.wowhead.com/quest=1164/to-steal-from-thieves

**Comment by stijnherreman** [comment]
It shows up for me at level 33.

**Comment by BreakBB** [comment]
Please update to v4.0.17 and try a `/reload` the data looks totally fine on our side, so it is most likely realted ot #860

**Comment by Leander30** [comment]
Should show up and is available at level 27, so perhaps the lvl requirement in questie is wrong.

**Comment by BreakBB** [comment]
@Leander30 We can't find any issues on our side. The data is setup correct at as @stijnherreman it does show up. Make sure to use the latest Questie release

**Comment by Leander30** [comment]
@BreakBB I'm on the latest version, It didn't show up on the map untill I hit level 30 today, so it's fine now. So no idea why it didn't show at 27/28/29. It's the only quest so far which had this problem.
