### ISSUE TITLE
My journey / Quest by zone

### ISSUE THREAD

**Issue by Leander30** [AeroScripts/QuestieDev#836]
Some quests that were recently fixed as showing as available on the world map when they were already completed by the player, are still showing as "available/incomplete" in the My journey/Quest by zone section. 
Would it be possible to somehow get an option to right click a quest and set it to complete in that section as well. (since im an extreme completionist :p)

**Comment by BreakBB** [comment]
Strange that they show up in your journey as incomplete, since the entry should have been made when you finished the quest. It shouldn't influence this if the quest was bugged before 🤔 

Which version of Questie are you using?

**Comment by Leander30** [comment]
I shift clicked completed them, since I already completed the Quests before the fix came in which hid them on the world map. Quests like "flawed power stones" and some other similar quests, which were fixed later. So the shift clicking messed it up in my journey.

**Comment by Leander30** [comment]
Im on the latest version btw.

**Comment by BreakBB** [comment]
@Leander30 Does this issue still exist for you?

**Comment by Leander30** [comment]
Only the flawed power stones is still visible while I did complete that quest line. And some of the repeatables, but I guess that's alright. 
![WoWScrnShot_103019_150324](https://user-images.githubusercontent.com/54747963/67864895-af4e8b00-fb26-11e9-9c7f-dbbc323a1df4.jpg)

**Comment by BreakBB** [comment]
As the text states "This is an automatic completion quest and does not contain an objective.". Those quests are marked as "repeatable" on our side.

The next release will change this and list the quests similar to this:

![image](https://user-images.githubusercontent.com/33514570/67866268-fccbf780-fb28-11e9-8af5-e568665e7177.png)

**Comment by Leander30** [comment]
Ok, that's great to hear! Thanks.
