### ISSUE TITLE
Quest: Deeprun Rat Roundup

### ISSUE THREAD

**Issue by Kiiraz** [AeroScripts/QuestieDev#837]
## Bug description
Error message in chat when quest is rendered

## Screenshots
![Capture06-09-2019-18 33 38](https://user-images.githubusercontent.com/54996055/64445556-0f045900-d0d7-11e9-88e7-659e77625270.png)

## Questie version
version 4.0.17

**Comment by artman41** [comment]
Same problem, playing classic
![image](https://user-images.githubusercontent.com/5568965/64473985-69e49180-d165-11e9-9189-a03b4c773f3c.png)
