### ISSUE TITLE
Toggle for Quests by type

### ISSUE THREAD

**Issue by aeonabyss** [AeroScripts/QuestieDev#839]
## Description

It would be nice to have the ability to filter quests by type from showing up on the maps, IE a checkbox for Dungeon Quests, Elite (non-dungeon)Quests , etc...

**Comment by emerick42** [comment]
It would be awesome! We could maybe start by adding a display in the quest window to show the type? (the type in parenthesis, abbreviated or not, or an icon)

**Comment by DaKrizzlyBear** [comment]
Hi all, not sure if anyone else has made any progress on this - but I'm making my first foray into LUA, and this seemed like a reasonable starting point. Still getting familiar with the codebase but will update as my implementation comes together!

**Comment by BreakBB** [comment]
@DaKrizzlyBear Sounds very good! Feel free to contact us on Discord if you have any question. Looking forward to your PR

**Comment by Gogo1951** [comment]
Hey @aeonabyss,

In-game dungeon quests are pretty well grouped by zone, and most elite quests have a + after the level. How's your LUA leveling going, you still working on this issue or can it be closed up?

**Comment by aeonabyss** [comment]
Close

**Comment by BreakBB** [comment]
This issue is being closed because some or all of the requested functionality has already been addressed in other features or fixes.
