### ISSUE TITLE
hilarys necklace

### ISSUE THREAD

**Issue by Leander30** [AeroScripts/QuestieDev#840]
https://classic.wowhead.com/quest=3741/hilarys-necklace

Shows available for the horde, should be alliance only.

**Comment by sinkda** [comment]
Per the comments on that link, this quest is available for the horde.  Now the horde still has to go into red ridge to get it but it is available to them.

**Comment by BreakBB** [comment]
Has anyone been to Redridge as Horde and could proof this?

**Comment by BreakBB** [comment]
According to [this comment](https://classic.wowhead.com/quest=3741/hilarys-necklace#comments:id=3162165) on Wowhead Horde can still complete this quest.
