### ISSUE TITLE
Tooltips duplicate

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#843]
## Bug description

Hovering over the "Strange Lockbox" in the Silverpine Forst shows more items in the tooltip than expected.

## Screenshots

![image](https://user-images.githubusercontent.com/33514570/64455949-43840f00-d0ef-11e9-9ea3-29c27f4ea0cc.png)

## Questie version

master branch commit 33c2c9bc4c0a4186aeb51a53f54a96fa69f33f95

**Comment by BreakBB** [comment]
Drejjmit found out it is in tooltips in general 
![image](https://user-images.githubusercontent.com/33514570/64456735-3cf69700-d0f1-11e9-8bc0-3f3ab62c7f0b.png)

**Comment by AeroScripts** [comment]
I've made changes to the tooltip logic to prevent this from happening, should hopefully be good now. I couldn't reproduce the issue myself in the first place so I cant be sure though

**Comment by BreakBB** [comment]
Thanks! We couldn't reproduce it either, so closing it for now
