### ISSUE TITLE
Enabling minimap icons drops my fps from 100 to 10

### ISSUE THREAD

**Issue by alecjpav** [AeroScripts/QuestieDev#844]
## Bug description

I installed Questie for the first time and noticed I was getting much lower framerate than I normally do, about 8-11 fps. I opened the options window and played with the settings. I found that disabling the "Enable Minimap Icons" option restores my framerate, but then I'm also no longer able to see icons on the minimap. Playing with the options in the Minimap Options tab while it was enabled did nothing for my framerate. 

## Screenshots

N/A

## Questie version

4.0.17

**Comment by BreakBB** [comment]
Could it be that you're using any kind of addon which collects all the minimap icons into one single icon. Like a dropdown menu or something similar?

**Comment by alecjpav** [comment]
> Could it be that you're using any kind of addon which collects all the minimap icons into one single icon. Like a dropdown menu or something similar?

Hello! Yes I am using MBB. Disabling it seems to have fixed it, but is there a way to fix the framerate issue while keeping it enabled?

I also just noticed disabling "Enable Objective Icons" also restores my framerate, however with both options enabled and MBB disabled my framerate is fine.

**Comment by BreakBB** [comment]
This should be fixed with b5743424842d8ce47c33c2ea0bdbdbf9d5c43d58 and will be included in the next release. Keep us updated if you have further issues.
