### ISSUE TITLE
[Classic WoW] Captain Sander's Treasure Map quest

### ISSUE THREAD

**Issue by kernighan** [AeroScripts/QuestieDev#845]
There is no indication on the World Map for Westfall about this quest at all.  I had the map that starts this quest drop from a Murloc Raider.

This is for Questie version 4.0.12

**Comment by BreakBB** [comment]
We're still looking for a way to bring quests which start from an item into Questie. We don't want to flood the map with icons of mobs that can possibly drop such an item

**Comment by BreakBB** [comment]
Related to #317
