### ISSUE TITLE
[Classic WoW] No indicator for Wanted: Lieutenant Fangor

### ISSUE THREAD

**Issue by kernighan** [AeroScripts/QuestieDev#846]
In Lakeshire, I had no indicator for the Wanted: Lieutenant Fangor wanted poster quest.  I was level 16 at the time, and it's a level 26 quest.  Just wanted to note that it is possible to pick up the quest at this level in case the database has it for a later level.  It's also possible the database is missing it entirely.

**Comment by MysticalOS** [comment]
By default, quests are filtered on map to only show for like 6 levels above your level and 4 levels below it. these are USER settings you can update to show quests earlier or for longer, if you choose. I believe I set mine ot show quests 7 levels below myself (the cutoff for quest stll being green and not gray) and 7 levels above on my own, for example. I honestly wouldn't recommend setting range to 10 levels above your level cause that'll clutter the world map view quite a bit and you generally just want world view to be a nice overview of "oh hey, these are areas that I can quest in right now"

**Comment by kernighan** [comment]
Yeah, I realized that a bit later.

What I'd really like is to have an option that just shows all non-grey quests that are available to me to pick up.

**Comment by BreakBB** [comment]
Sorry for the late response on this @kernighan What @MysticalOS wrote is totally correct. With the default configuration you don't get all quests shown which are possibly acceptable for you, since that would most likely be too much. Moreover a quest 10 level above your own can't be completed by you on your own.
