### ISSUE TITLE
Shadowglen Hallowed Sigil Quest

### ISSUE THREAD

**Issue by Sunitrema** [AeroScripts/QuestieDev#849]
Hello, I am a Night Elf Druid but Questie keeps showing Hallowed Sigil (A Priest Quest) as available for me.

I'm not sure if there is a setting on my end I need to change for the addon or if this is a bug.

Thanks!

**Comment by BreakBB** [comment]
It would be great if you could follow our issue rules and use a template. A [Wowhead link](https://classic.wowhead.com) could save us time to understand what your exact issue is and how we can improve

**Comment by Sunitrema** [comment]
https://classic.wowhead.com/quest=3119/hallowed-sigil

This is the quest I am referring to. It is a priest specific quest but is showing as available to me although I am a druid.

**Comment by BreakBB** [comment]
Are you using the latest version of Questie and does it still show up? Because the data looks alright on our data.

**Comment by Sunitrema** [comment]
All fixed, thank you!
