### ISSUE TITLE
[Alliance] Worth its weight in gold

### ISSUE THREAD

**Issue by MysticalOS** [AeroScripts/QuestieDev#850]
## Bug description
Quest doesn't show Medicine Pouch or Hunter Knife drops, only tusks. https://classic.wowhead.com/quest=691/worth-its-weight-in-gold

## Questie version
4.0.17

**Comment by AeroScripts** [comment]
There seems to be a general issue with tooltips for mobs that have more than 1 objective, gonna do some testing today

**Comment by BreakBB** [comment]
With the recent changes to the tooltip logic those issues should be fixed. Moreover I checked the data on out side and they seem fine for this quest.
