### ISSUE TITLE
Questie is stuck!!

### ISSUE THREAD

**Issue by dublk** [AeroScripts/QuestieDev#852]
Description
I was following questie in Wetlands, i took a quest in the armory or whatever, in the middle of Wetlands before i started using questie. Apparently i didnt do the quest before taking the other quest, so now all questie wants is for me to do a quest that isnt available.
I have tried deleting the addon, wtf, cache. Yet still its wants me to start "Report to Captain Stoutfist" which isn't possible.

 Wowhead link
https://classic.wowhead.com/quest=473/report-to-captain-stoutfist

![WoWScrnShot_090619_191741](https://user-images.githubusercontent.com/55008722/64468561-1463a280-d0db-11e9-8b1a-6188bf6a2a48.jpg)

Questie version
4.0.16

**Comment by AeroScripts** [comment]
This looks like azeroth autopilot actually, if it is AAP, you should be able to get past it with /aap skip

**Comment by dublk** [comment]
i guess i dont understand much, thannks
