### ISSUE TITLE
Load Lightening

### ISSUE THREAD

**Issue by amey1956** [AeroScripts/QuestieDev#853]
## Description

Turn in at Pozzik for Load Lightening at Mirage Raceway is a yellow dot instead of ?

## Wowhead link

/quest=1176/load-lightening

## Questie version
4.0.17

**Comment by BreakBB** [comment]
Did you try to `/reload`?

**Comment by BreakBB** [comment]
The data looks fine on our side for this quest. And the description of your problem sounds like a case of #860 Thanks for the report 👍
