### ISSUE TITLE
Error when loading Darkshore quest "WANTED: Murkdeep!"

### ISSUE THREAD

**Issue by L0G1C** [AeroScripts/QuestieDev#854]
## Bug description
If the player accepts the quest Questie displays this error in the chat window. Error is also displayed once the game world is loaded upon first logging in.

## Screenshots
![image](https://user-images.githubusercontent.com/1203115/64469654-06764780-d104-11e9-93a4-98f41fecbd96.png)

## Questie version
4.0.15

**Comment by AeroScripts** [comment]
This should be fixed in 4.0.16 or newer (current is 4.0.17) give the latest release a try

Thanks for reporting though <3
