### ISSUE TITLE
Crown of the Earth not showing on Mini Map

### ISSUE THREAD

**Issue by tylerrdavis** [AeroScripts/QuestieDev#855]
## Description
Crown of earth quest not showing completion or location to fill vile. 

## Wowhead link
https://classic.wowhead.com/quest=934/crown-of-the-earth

## Screenshots
![crownoftheearth](https://user-images.githubusercontent.com/11394358/64469814-7cbb7f80-d0ed-11e9-8cc0-48b98da44691.PNG)

## Questie version
4.0.17

**Comment by BreakBB** [comment]
Did you try a `/reload`?

**Comment by BreakBB** [comment]
Also related to #640

**Comment by BreakBB** [comment]
This should be fixed with 7548742
