### ISSUE TITLE
Quest Whelgar's Excavation `Uncovering the Past` where you turn in fragments `Ados, Modr, Golm, Neru` doesn't show turn in location

### ISSUE THREAD

**Issue by tilkinsc** [AeroScripts/QuestieDev#856]
## Description
 doesn't show turn in location, which is Prospector Whelgar in the cave.

## Wowhead link
https://www.wowhead.com/npc=41411/prospector-whelgar

## Screenshots
![image](https://user-images.githubusercontent.com/7494772/64470158-7983bc00-d10c-11e9-859f-5492fc819431.png)

![image](https://user-images.githubusercontent.com/7494772/64470159-81dbf700-d10c-11e9-9782-ec653079582a.png)

## Questie version
4.0.17

**Comment by tilkinsc** [comment]
Also related, questie doesnt seem to be showing the following sarltooth quest as well as location.

**Comment by AeroScripts** [comment]
Even after /questie reload ?
Will look in to this shortly, thanks for reporting

**Comment by BreakBB** [comment]
Our data looks totally fine on this. Please check again on this.

Moreover the correct NPC ID is https://classic.wowhead.com/npc=1077/prospector-whelgar

**Comment by tilkinsc** [comment]
It appears that questie needs reloaded after every quest turn in. I did all the quests from ashenvale, Darkshore, and Teldrassil and had constant problems almost every quest with markers appearing.

**Comment by BreakBB** [comment]
@tilkinsc Have you updated to v4.1.1?

**Comment by tilkinsc** [comment]
At the time of posting, my version was as recent as it could as far as I knew. I will update to the latest and monitor how it goes.
