### ISSUE TITLE
'Quests by Zone' tab improvements

### ISSUE THREAD

**Issue by jasonemann** [AeroScripts/QuestieDev#859]
Just a couple of simple improvements to the 'Quests by Zone' tab:

1. Sort the 'Select Your Zone' dropdown menu alphabetically.
2. Use character's current location as the default selection for the 'Select Your Continent' and 'Select Your Zone' dropdown menus.
3. Sort the resulting lists of quests by level.

**Comment by BreakBB** [comment]
1. Has been fixed with 320ee382e96e4e66cd82055ae27f81f427178fc7
2. Has been fixed with fd24a10c9b90c819e51634bb1c693993225db9e5
3. Has been fixed with 6e51c14bbe8d833661b15e0fe02adfa22a4e3369
