### ISSUE TITLE
Suggestion: Hiding all Minimap Markers on Death

### ISSUE THREAD

**Issue by MOUZU** [AeroScripts/QuestieDev#86]
It'll probably should not be much of a work, but I recently had problems seeing my corpse-arrow on the minimap because I was that far away that all those quest markers were occupying its visibility.

just like a trigger to hide all on death, and make them reappear on resurrecting?

**Comment by Sparh4wk** [comment]
Just press M and press Toggle Questie?

**Comment by MOUZU** [comment]
I know about that, but imo I'd implement this small thing anyways. who needs quest markers if they are dead? I don't want to toggle this manually everytime, by using the events PLAYER_DEAD and PLAYER_UNGHOST you could simply trigger this toggle function :)

**Comment by AeroScripts** [comment]
I wasn't aware that it rendered ontop of vanilla arrows, it should be an easy fix to just have them render underneath. Gotta look into it though.
