### ISSUE TITLE
Quests with multiple objectives on Russian locale

### ISSUE THREAD

**Issue by h671g** [AeroScripts/QuestieDev#861]
When doing such quests only one objective is shown on map and nameplates, for example quest https://classic.wowhead.com/quest=38/westfall-stew shows only Stringy Vulture Meat from Harvest Watchers. 
Screenshot below:
![image](https://user-images.githubusercontent.com/55016617/64472548-c4332180-d168-11e9-9a85-281eb3cbba21.png)

I tested Questie with English locale and it's working as intended

**Comment by AeroScripts** [comment]
Seems to be a problem with the german client also

**Comment by BreakBB** [comment]
Is this still an issue? I think there have been fixes for such cases

**Comment by Eveigh** [comment]
I have similar problem with same topic. Quests with multiply objectives  is shown on map as they in same place. For example https://classic.wowhead.com/quest=207/kurzens-mystery all legends in same point
![WoWScrnShot_092119_173219](https://user-images.githubusercontent.com/40161800/65374755-19f1e880-dc96-11e9-8cfe-7905024a2141.jpg)
Cant test in EN client unfortunaly.
Using version 4.1.1

**Comment by h671g** [comment]
> Is this still an issue? I think there have been fixes for such cases

Yes, this issue still exists. For example quest Westfall stew, which requires 4 type of items only shows Harvest Watchers on map and no nameplate hints for other 3 items:
![Безымянный](https://user-images.githubusercontent.com/55016617/65387306-c8596480-dd4e-11e9-83ee-0201d701ba83.jpg)

**Comment by BreakBB** [comment]
Merging this with #1071
