### ISSUE TITLE
Quest appears multiple time in tool tip when hovering an ennemy

### ISSUE THREAD

**Issue by Citillara** [AeroScripts/QuestieDev#865]
## Bug description
Saw it happens on hovering on a mob that is target to the quest "In defense of the King's lands"

## Screenshots
https://gyazo.com/459f81e22bf55d3132f33c1036445151

## Questie version
v4.0.17

**Comment by Citillara** [comment]
It's Classic wow btw

**Comment by BreakBB** [comment]
Related to #843 and should be fixed with the next release coming out very soon!
