### ISSUE TITLE
[ERROR] The Stave of Equinex

### ISSUE THREAD

**Issue by jfaulk** [AeroScripts/QuestieDev#867]
## Bug description
After accepting the quest [The Stave of Equinex](https://classic.wowhead.com/quest=2879/the-stave-of-equinex) the below errors appear (one for each objective of the quest?) in chat every load and the objectives are not marked on the map.
```
Questie: [ERROR] [QuestieQuest]: DEBUG_POPULATE_ERR ERROR: ...ce\AddOns\QuestieDev-master\Locale\QuestieLocale.lua:70: bad argument #4 to 'format' (string expected, got nil) 
Questie: [ERROR] [QuestieQuest]: DEBUG_POPULATE_ERR ERROR: ...ce\AddOns\QuestieDev-master\Locale\QuestieLocale.lua:70: bad argument #4 to 'format' (string expected, got nil) 
Questie: [ERROR] [QuestieQuest]: DEBUG_POPULATE_ERR ERROR: ...ce\AddOns\QuestieDev-master\Locale\QuestieLocale.lua:70: bad argument #4 to 'format' (string expected, got nil) 
Questie: [ERROR] [QuestieQuest]: DEBUG_POPULATE_ERR ERROR: ...ce\AddOns\QuestieDev-master\Locale\QuestieLocale.lua:70: bad argument #4 to 'format' (string expected, got nil) 
```

## Questie version
Dump: value=QuestieGetVersionString()
[1]="4.0.17"

**Comment by AeroScripts** [comment]
Hmm, were you using the git version? If so, try updating to latest commit (This was just fixed)

If this is bugged in the .17 release, then ill leave this open until .18 is up (which has the fix)
Thanks for reporting!

**Comment by jfaulk** [comment]
I was using the git version that was a few hours old. I just updated and it does indeed seem to be fixed.
There seems to be a lot of keyreg: spam in chat now. Not sure if that's intentional.

Thanks!

**Comment by AeroScripts** [comment]
Oh I wasnt supposed to commit that, ill fix that up now
