### ISSUE TITLE
Buggy since last update.

### ISSUE THREAD

**Issue by volostyle** [AeroScripts/QuestieDev#868]
## Bug description
After updating to latest version, all map objects dissappeared along with the tooltips showing quest info.  Reloading UI would not work, however CTRL + Click to reload questie seemed to work.  Even after doing that though, quest turn in question marks are not showing up on the map.

**Comment by AeroScripts** [comment]
Hmm, are you on english client?

**Comment by volostyle** [comment]
Yes

**Comment by volostyle** [comment]
I posted on curse as well, and it looks like someone else was having the same problem.

**Comment by jrtauschek** [comment]
.mm😥

. M .you. .
.  7 n..
M .  ,

**Comment by jsabin69** [comment]
Message: ...AddOns\QuestieDev-master\Modules\QuestieTooltips.lua:144: attempt to compare number with nil
Time: Sat Sep  7 13:22:46 2019
Count: 660
Stack: ...AddOns\QuestieDev-master\Modules\QuestieTooltips.lua:144: attempt to compare number with nil
[C]: ?
...AddOns\QuestieDev-master\Modules\QuestieTooltips.lua:144: in function <...AddOns\QuestieDev-master\Modules\QuestieTooltips.lua:140>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...face\AddOns\TradeSkillMaster\Core\Lib\TooltipLib.lua:80: in function <...face\AddOns\TradeSkillMaster\Core\Lib\TooltipLib.lua:78>
[C]: in function `SetInboxItem'
Interface\FrameXML\MailFrame.lua:313: in function <Interface\FrameXML\MailFrame.lua:309>
[C]: in function `InboxFrameItem_OnEnter'
[string "*:OnUpdate"]:2: in function <[string "*:OnUpdate"]:1>

Locals:

**Comment by AeroScripts** [comment]
@jsabin69 thanks for reporting! Should be good as of fe60a01081d8aba53a86bc190656c9b1f91206be (fix will be in v4.0.18 which will be up in a couple hours)

@volostyle I've made some changes to the code that should solve this issue for you, but I cant be sure as I couldn't reproduce it myself. Can you test v4.0.18 when its up and post back?

**Comment by AeroScripts** [comment]
This might have also been related to updating without restarting the game, come to think of it. The newest update has added a check to warn users if this happens in the future (Restarting the game on update is only needed when we add new source files, like in .17)

**Comment by BreakBB** [comment]
@volostyle Could you update to v4.1.1 and check if this still is an issue?

**Comment by volostyle** [comment]
Everything seems to be working now.

**Comment by BreakBB** [comment]
Great, thanks for your fast response! Closing this for now.
