### ISSUE TITLE
Questie shows an unavailable quest "Jungle Secrets" at NPC "Private Thorsen"

### ISSUE THREAD

**Issue by arphox** [AeroScripts/QuestieDev#869]
## Description
Questie indicates on the minimap that I have an available quest **"[Jungle Secrets](https://classic.wowhead.com/quest=215/jungle-secrets)"** from NPC **[Private Thorsen](https://classic.wowhead.com/npc=738/private-thorsen)**, but the NPC does not offer this quest. I am level 33.

## Screenshots
**Minimap saying the quest is available:**
![kép](https://user-images.githubusercontent.com/17320094/64477524-e6df2d80-d19c-11e9-8a18-a6550fdb135e.png)

**But it is not:**
![kép](https://user-images.githubusercontent.com/17320094/64477535-070eec80-d19d-11e9-83c4-4ca18fed57a6.png)

## Questie version
**4.0.17**

**Comment by MysticalOS** [comment]
I think it's misleading WHERE it's shown. it should really show the ! down the road where you can actually get quest (after ambush event)

Context: This quest is only offered about once per hour, i think about 15 minute after hour is when I was able to get it. When he goes ona patrol. during this patrol, he gets ambushed. If you save him from ambush,the quest appears and he stands there offering quest for a few minutes. After which he walks back to camp until his next patrolan hour later.

I could be mistaken on how often patrol is, it might be a random between x and y value, but I know it's definitely a 30 min or more wait.

**Comment by BreakBB** [comment]
This is really kind of tricky to solve, since the spawn of the NPC is where it is now. I think when we include the patrolling route data this will be much clearer.
Very special quest though.

**Comment by BreakBB** [comment]
With the release of [v5.0.0](https://github.com/AeroScripts/QuestieDev/releases/tag/v5.0.0) quest NPCs now have the pathing drawn which will add more information to quests like this.
