### ISSUE TITLE
Tooltip quest objective spam

### ISSUE THREAD

**Issue by readybeta** [AeroScripts/QuestieDev#870]
Multiple lines of quest objective

![WoWScrnShot_090719_185516](https://user-images.githubusercontent.com/6419437/64478754-df238700-d1a4-11e9-9752-94aedfd6d66c.jpg)

**Comment by AeroScripts** [comment]
This has been fixed on master and will be good in 4.0.18, which should be up in a couple hours. Thanks for reporting, sorry it gave you trouble D:

/questie reload can also temporarily clear it up in .17

**Comment by readybeta** [comment]
Ty. Keep up the good work!
