### ISSUE TITLE
[Classic WoW] The Warsong Reports

### ISSUE THREAD

**Issue by mMaxPnz** [AeroScripts/QuestieDev#872]
## Bug description
The Warsong Reports https://classic.wowhead.com/quest=6543/the-warsong-reports
Not mark at map NPC:
- Warsong Scout https://classic.wowhead.com/?npc=12862
- Warsong Runner https://classic.wowhead.com/?npc=12863
- Warsong Outrunner https://classic.wowhead.com/?npc=12864

UPD: They are marked, but as new quests.

## Questie version
Questie v4.0.17 BETA

**Comment by BreakBB** [comment]
Since the subquests are shown correctly there is no issue here. Other quests behave the same and the you get the updates from a real quest and no drop/object.
