### ISSUE TITLE
Every npc in every zone tells me i can get a mission called "Chicken/CLUCK!" from them

### ISSUE THREAD

**Issue by MikeLUL** [AeroScripts/QuestieDev#874]
## Description
Well basically it shows on the map that i can get the quest called chicken from every npc, even though i completed it too, because i wanted to see if that makes it go away. It actually worked but when i restarted the game it came back again.

## Wowhead link
https://classic.wowhead.com/quest=3861/cluck

## Questie version
Latest

**Comment by AeroScripts** [comment]
Hmm can you run this chat command
```
/dump QuestieDB:GetQuest(3861).Hidden
```
and let me know if it prints true or false? That quest has been flaged as hidden for quite some time, something funky is going on with the logic

**Comment by BreakBB** [comment]
A flawed refactoring lead to this bug. It is fixed in v4.0.18.
