### ISSUE TITLE
They Call Him Smiling Jim (Theramore) - Not shown on map

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#875]
Quest is missing on map.
/reload doesn't help.

**Comment by BreakBB** [comment]
Related to #815

**Comment by BreakBB** [comment]
@Painstormx Could you run the following commands to check something for us? [They Call Him Smiling Jim](https://classic.wowhead.com/quest=1282/they-call-him-smiling-jim) is actually exclusive to [James Hyal](https://classic.wowhead.com/quest=1302/james-hyal) according to our data and Wowhead. So you might have completed the other one. But maybe in Classic this changed.

`/dump IsQuestFlaggedCompleted(1282)`
`/dump IsQuestFlaggedCompleted(1301)`
`/dump IsQuestFlaggedCompleted(1302)`

**Comment by Painstormx** [comment]
I have already completed They Call Him Smiling Jim, but here are the results:
1282=true
1301=false
1302=true
