### ISSUE TITLE
Upgraded from 4.0.10 to 4.0.17

### ISSUE THREAD

**Issue by Telkwa** [AeroScripts/QuestieDev#876]
## Bug description
Upgraded from 4.0.10 to 4.0.17 after launching game all the quest icons I previously had on the map disappeared.  Even abandoning a quest and retaking it didn't work.  I had to go back to 4.0.10.

## Questie version
4.0.17

**Comment by AeroScripts** [comment]
Hmm, can you send your addon list? It could be a conflict with changes we've made (should be an easy fix if we can track it down)

.18 is coming out shortly but im not sure if it will fix this issue (it does fix a number of issues in .17 though)

**Comment by Telkwa** [comment]
Here's my list.  It might be mapster or one of the other map ones.  I could test to see which.

ATLASLOOTCLASSIC
ATLASLOOTCLASSIC_COLLECTIONS
ATLASLOOTCLASSIC_CRAFTING
ATLASLOOTCLASSIC_DUNGEONSANDRAIDS
ATLASLOOTCLASSIC_FACTIONS
ATLASLOOTCLASSIC_OPTIONS
ATLASLOOTCLASSIC_PVP
AUCTIONATOR
BAGBROTHER
BARTENDER4
CLASSICAURADURATIONS
CLASSICCASTBARS
CLASSICCASTBARS_OPTIONS
CLASSICSPELLACTIVATIONS
CLASSICTHREATMETER
CLIQUE
DBM-AQ20
DBM-AQ40
DBM-AZEROTH
DBM-BWL
DBM-CORE
DBM-DEFAULTSKIN
DBM-GUI
DBM-MC
DBM-NAXX
DBM-ONYXIA
DBM-PARTY-CLASSIC
DBM-STATUSBARTIMERS
DBM-ZG
DEJAMARK
EMA-CLASSIC
GRID2
GRID2LDB
GRID2OPTIONS
GRID2RAIDDEBUFFS
GRID2RAIDDEBUFFSOPTIONS
INVENTORIAN
ISBOXER
LEATRIX_MAPS
LEATRIX_PLUS
MAPSTER
OUTFITTER
POSTAL
PRAT-3.0
PRAT-3.0_LIBRARIES
QUESTICONDESATURATION
QUESTIE
QUESTLOGEX
RECOUNT
SPEEDYAUTOLOOT
VENDORPRICE

**Comment by AeroScripts** [comment]
If you dont mind testing and figure it out post back, should be easy to figure out whats going on once we can reproduce the issue

I can't see any in the list that stand out but it likely is map related

**Comment by BreakBB** [comment]
Any news on this? @Telkwa Are you running Questie now fine?
