### ISSUE TITLE
Quest: Identifying the Brood. quest id 1169

### ISSUE THREAD

**Issue by latusthegoat** [AeroScripts/QuestieDev#878]
## Description
The quest requires 15 of Searing Tongue and 15 of Searing Heart. Both of those drop from the searing whelps and hatchlings, but only the Tongue is indicated by Questie.  Need to add the searing heart as a drop from the whelp/hatchling.

## Wowhead link
https://classic.wowhead.com/item=5841/searing-heart
https://classic.wowhead.com/item=5840/searing-tongue

https://classic.wowhead.com/npc=4324
https://classic.wowhead.com/npc=4323

## Questie version
v4.0.17 Beta

**Comment by AeroScripts** [comment]
This could be related to the "multiple quest objectives on the same mob only shows 1 objective in the tooltip" bug, which should be good in .18

I'll check the data shortly anyway as it might still be wrong, but it sounds like that bug. Finishing things up for the release (it should be out in about an hour)

Thanks for reporting!

**Comment by BreakBB** [comment]
Our data looks good on this. As Aero already stated your issue was most likely connected to a bug which has been fixed inv 4.0.18
