### ISSUE TITLE
New quests sometimes add no notes to QuestieHandledQuests

### ISSUE THREAD

**Issue by Schaka** [AeroScripts/QuestieDev#88]
This probably happens because we only draw notes for quests marked as tracked in QuestieTrackedQuests. Therefore, if we check whether a quest is marked as such, before it is actually marked, the above happens.

Haven't been able to make out where exactly this happens. @Logonz will probably know this best.

**Comment by Schaka** [comment]
This is fixed by toggling Questie (on the map) twice. Needs a proper programmatic fix

**Comment by Schaka** [comment]
Upon double checking this, I didn't manage to reproduce the bug (though it happens frequently when playing). 
When AddQuestToTracker is called, it redraws notes by the end of it and that drawing mechanism checks whether a quest is tracked (the status is just changed before this function is called, so it's definitely tracked).

What I don't understand is, why sometimes it will not draw the notes, as if the quest isn't tracked. My best bet is, that by the time RedrawNotes() is called, notes aren't in QuestieHandledQuests yet. So if that is the case, this seems to be an issue with the custom delay system that needs to be looked into.

**Comment by AeroScripts** [comment]
Fixed as of v2.0.10, though it's a "temporary fix" that needs to be done properly.
