### ISSUE TITLE
The Mindless Ones

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#882]
The quest isn't showing up on the minimap despite being both available and marked as such in the Quests by Zone list.

https://classic.wowhead.com/quest=364/the-mindless-ones

![WoW Questie The Mindless Ones Absent](https://user-images.githubusercontent.com/54936174/64487962-ccab5b00-d241-11e9-86cb-9992a82fca23.png)

4.0.18

**Comment by AeroScripts** [comment]
Hmm, I'm assuming you haven't done "Rude Awakening"? 

Seems its not a requirement for non-forsaken, or maybe opened up by another quest? Normally its unlocked by finishing rude awakening

**Comment by Cerby3BR** [comment]
I can't do Rude Awakening as a non-undead, seems likely that they only coded RA as a requirement for Forsaken characters.

**Comment by Cerby3BR** [comment]
Actually no, I just checked with a new Forsaken character and Rude Awakening isn't required to do The Mindless Ones.

**Comment by AeroScripts** [comment]
oh ok, well it's flagged as being required in the DB
Easy fix then 🎊
