### ISSUE TITLE
Fool's Stout showing up as available when it's been completed

### ISSUE THREAD

**Issue by Tyriar** [AeroScripts/QuestieDev#884]
## Description
Fool's Stout showing up as available when it's been completed

## Wowhead link
https://classic.wowhead.com/quest=1127/fools-stout

## Screenshots
![image](https://user-images.githubusercontent.com/2193314/64491218-99090a80-d21a-11e9-9a55-f44c2886bdb5.png)
![image](https://user-images.githubusercontent.com/2193314/64491220-9d352800-d21a-11e9-97f4-66f09527c464.png)

## Questie version
4.0.17

**Comment by Digifais** [comment]
Can confirm this is t he case with v4.0.18 as well.
