### ISSUE TITLE
Questie does not show available quest: "Zanzil's Secret" from "Crank Fizzlebub"

### ISSUE THREAD

**Issue by arphox** [AeroScripts/QuestieDev#886]
## Description
The NPC **[Crank Fizzlebub](https://classic.wowhead.com/npc=2498/crank-fizzlebub)** offers the quest **[Zanzil's Secret](https://classic.wowhead.com/quest=621/zanzils-secret)**, but Questie does not show it on the map/minimap. I tried reloading but did not help. I am a level 35 priest on a PvE server.

## Screenshots
![WoWScrnShot_090819_195649](https://user-images.githubusercontent.com/17320094/64492293-d4372800-d272-11e9-9927-32b04f86a6a5.jpg)

## Questie version
4.0.17

Here is my Questie.lua file from path `\_classic_\WTF\Account\MYACCOUNTID\SavedVariables\` for easier debugging (maybe quest dependencies?):
[Questie.lua.txt](https://github.com/AeroScripts/QuestieDev/files/3587851/Questie.lua.txt)

**Comment by BreakBB** [comment]
Sorry for the late response on this. We've had to figure some stuff out about this quest.

For us it is listed to be only acceptable if you completed "Zanzil's Secret" and "Back to Booty Bay". Could you run the following commands to check our data?

`/dump IsQuestFlaggedCompleted(621)`
`/dump IsQuestFlaggedCompleted(1118)`
`/dump IsQuestFlaggedCompleted(1119)`

**Comment by arphox** [comment]
> Could you run the following commands to check our data?
> `/dump IsQuestFlaggedCompleted(621)`
> `/dump IsQuestFlaggedCompleted(1118)`
> `/dump IsQuestFlaggedCompleted(1119)`

```
false
false
false
```

**Comment by BreakBB** [comment]
Thanks for coming back to this so fast. A fix will be included in the next release!
