### ISSUE TITLE
Questie does not show available quest: "The Captain's Chest" from "Captain Hecklebury Smotts"

### ISSUE THREAD

**Issue by arphox** [AeroScripts/QuestieDev#887]
## Description
The NPC **[Captain Hecklebury Smotts](https://classic.wowhead.com/npc=2500/captain-hecklebury-smotts)** offers the quest **The Captain's Chest** (there are two quests with the same name, check the NPC's wowhead website for those ids), but Questie does not show it on the map/minimap. I tried reloading but did not help. I am a level 35 priest on a PvE server.

## Screenshots
![WoWScrnShot_090819_200548](https://user-images.githubusercontent.com/17320094/64492434-13b24400-d274-11e9-9c75-72adaaaed5af.jpg)

## Questie version
4.0.17

Here is my Questie.lua file from path `\_classic_\WTF\Account\MYACCOUNTID\SavedVariables\` for easier debugging (maybe quest dependencies?):
[Questie.lua.txt](https://github.com/AeroScripts/QuestieDev/files/3587851/Questie.lua.txt)

**Comment by BreakBB** [comment]
Those quests are marked for level 47. By default Questie only shows quests 7 level above your own, so this was most likely the issue here. Or did you change those sliders?

**Comment by arphox** [comment]
This should be the case. :-)
