### ISSUE TITLE
Available quest isn't showing: James Hyal, ID 1302

### ISSUE THREAD

**Issue by haggen** [AeroScripts/QuestieDev#889]
## Description
I have the quest James Hyal (part 2, given by Vincent Hyal) available to me in-game, but Questie isn't showing an icon for it. Wowhead, as well as the database file (line 1206), say it requires part 1 (ID 1301) but I've never completed that quest. Even `/dump IsQuestFlaggedCompleted(1301)` returns `false`. I have filed as a potential bug in the game as well: https://us.forums.blizzard.com/en/wow/t/quest-requirement-for-james-hyal/291458

## Wowhead link
https://classic.wowhead.com/quest=1302/james-hyal

## Screenshots
![image](https://user-images.githubusercontent.com/270076/64492534-367c3280-d24b-11e9-8269-569095cbfc8c.png)

## Questie version
4.0.17

**Comment by BreakBB** [comment]
Waiting for a response of Blizzard on this

**Comment by haggen** [comment]
Hey @BreakBB look what I found: a comment supposedly from 2005 on the old Thotbot, imported to current Wowhead: https://classic.wowhead.com/quest=1302/james-hyal#comments:id=2725846

> This quest is a bit unusual because you can pick it up in the middle without doing step 1. You get some tantalizing clues in Theramore about the 'burned down Inn' but after finding the Inn I couldnt find any clues or quests to continue the investigation. [...]

Perhaps it's been a bug since then, or perhaps it was never designed to require part 1, but seeing evidence that this was the case, shouldn't simply assume that'd the expected behavior and change the quest database (i.e. add to corrections) that the second part **does not** require the first? i.e. remove the dependency from one another?

**Comment by BreakBB** [comment]
@haggen Ye that sounds like a good solution for now. But as stated in the referenced ticket if this quest requires cooking we're better of hiding it for now. Since the first quest requires cooking it is very likely that the second one does as well 🤔

**Comment by haggen** [comment]
Rather than hiding wouldn't it be more helpful to show it but with the additional information that it requires skill?

**Comment by BreakBB** [comment]
Could you run `/dump IsQuestFlaggedCompleted(1282)`?

**Comment by haggen** [comment]
Oh I see because this quest (1302), just like part 1, is also a simple pointer to the real deal, [They Call Him Smiling Jim](https://classic.wowhead.com/quest=1282/they-call-him-smiling-jim) (1282).

So the whole deal is any of these quests (1301, 1302, and 1282) are mutually exclusive.

**Comment by BreakBB** [comment]
In our data 1282 is exclusive to 1302 which could be the issue you're facing. Like our data is wrong since you can complete both 🤔

**Comment by haggen** [comment]
I'm pretty sure I checked and I haven't done 1282 either.

**Comment by BreakBB** [comment]
@haggen Did you check again on this?

**Comment by haggen** [comment]
I'm a little late but yea, it's fixed now. Thanks!
