### ISSUE TITLE
Issues with tracker not showing

### ISSUE THREAD

**Issue by Schaka** [AeroScripts/QuestieDev#89]
Some people have issues with the tracker not showing up, even after deleting all Questie files in their WTF folder. After debugging this for someone on stream today, I found out that QuestieConfig will sometimes be nil. This is despite it being loaded as the VERY FIRST file and instantly setting a table. 

I think it's linked to some bullshit Win7/8 does with applications on the C:\ drive, where it creates a copy of the World of Warcraft folder under AppData/VirtualStore.

All other SavedVariables work fine, so I think we should move the config to an ADDON_LOADED event to prevent issues in the future. I cannot guarantee that will fix it, as I cannot even reproduce the issue myself. But it is better to be safe than sorry.

**Comment by AeroScripts** [comment]
Moving it to ADDON_LOADED would be an easy fix, but for cases when it can't actually write to savedvariables, it might be usefull to use this glitch to warn the user that savedvariables aren't working

**Comment by Schaka** [comment]
With v2.0.8 on my brother's laptop (literally copied my wow folder) the trackerframe refused to show - no errors. REALLY weird.

**Comment by GeoffWhatley** [comment]
Not sure if the same issue, but I had an issue on 2.0.4 where the Tracker wouldn't show - it turned out I was adding quest levels to the log with 2 seperate addons (EQL & Minimalist), which prevented the quests from being parsed. Disabling the 'add quest level' feature in both addons resolved my issue.

**Comment by AeroScripts** [comment]
I think I figured out what was causing this, it should be fixed in v2.0.9

The tracker now moves it's self back onto the screen if it ever (for whatever reason) goes outside it.

Leaving this open for now though
