### ISSUE TITLE
Cyclonian is now showing Life Root as a drop off pretty much every mob I see.

### ISSUE THREAD

**Issue by MysticalOS** [AeroScripts/QuestieDev#893]
## Description
Cyclonian (https://classic.wowhead.com/quest=1712/cyclonian) is now showing Life Root as a drop off pretty much every mob I see. this is new to the .18 version. Probably related to new tooltip code to that shows even when objectives not cluttering map. The issue though, is that it sets a false expectation. A mob that has like a 0.001% chance to drop a liferoot (basically just a very low chance world drop herb), shouldn't be added to tooltips. Someone using this mob shouldn't go "oh I can grind tigers in STV for liferoot" when that's worst idea possible.

I like the new tooltip feature that lets it show without clutting map with objectives, but it needs important thresholds to ensure it's only showing productive tooltips and not red herrings that will be damaging to a players experience should they follow them.

## Questie version
4.0.18

**Comment by MysticalOS** [comment]
Actually, checking wowhead data, it's showing tooltip on mobs that don't even drop it. for some reason, it simply things liferoot drops off every mob in game, and shows tooltips on ALL hostile enemies.

**Comment by AeroScripts** [comment]
Hey thanks for reporting. Seems a lot of the herbs have a bunch of mobs in the drop table, which really doesn't make sense to show. I've already fixed a few of them but it seems we need to go through and check all the herbs

**Comment by BreakBB** [comment]
Please check again with the next release or using the master branch 😃 The commit above should fix most issues
