### ISSUE TITLE
Add more granular options for map icons

### ISSUE THREAD

**Issue by ShaunDreclin** [AeroScripts/QuestieDev#896]
I'd like to have Questie icons shown on zone maps, but not on the continent/world maps.

Either individual toggle buttons or having the Hide/Show Questie button only apply to the level of map you're currently looking at would work.

Edit: An option to only show completed quests on the continent/worlds maps but show everything on zone maps would be great too

**Comment by Gogo1951** [comment]
Hey @ShaunDreclin ,

Added your request here. https://github.com/AeroScripts/QuestieDev/issues/799

We should be good to close this issue.

**Comment by ShaunDreclin** [comment]
Awesome! 😁
