### ISSUE TITLE
Duplicated tooltip annotation 4 times

### ISSUE THREAD

**Issue by Tyriar** [AeroScripts/QuestieDev#898]
## Bug description
Part way through quest showing multiple tooltip annotations

## Screenshots
![image](https://user-images.githubusercontent.com/2193314/64500837-c59d4080-d273-11e9-9cec-3c39f9272768.png)
![image](https://user-images.githubusercontent.com/2193314/64500844-cc2bb800-d273-11e9-9ff3-141d0d463de0.png)

## Questie version
4.0.17

**Comment by AeroScripts** [comment]
This has been fixed in v4.0.18 give that a try 

Thanks for reporting though! (There are a few important bugs fixed in .18, really recommend updating)

**Comment by Tyriar** [comment]
Upgraded and verified, cheers.
