### ISSUE TITLE
Supplies for the Crossroads not displayed

### ISSUE THREAD

**Issue by nwn** [AeroScripts/QuestieDev#899]
The quest [Supplies for the Crossroads](https://classic.wowhead.com/quest=5041/supplies-for-the-crossroads) does not show up on the map, though Thork's other quest, [Disrupt the Attacks](https://classic.wowhead.com/quest=871/disrupt-the-attacks), does. It also is not displayed as available in the "Quests by Zone" window. I'm level 11, so it should be available.

**Comment by BreakBB** [comment]
It would be great if you followed the issue template. What version of Questie are you running or were you running when you encountered this issue?

**Comment by nwn** [comment]
Sorry about that, it's version 4.0.16.
