### ISSUE TITLE
Quest Not Tracked: The Escape

### ISSUE THREAD

**Issue by abennette32** [AeroScripts/QuestieDev#9]
No tracker on map for Tommy.

**Comment by AeroScripts** [comment]
[The quest text on this one is confusing me](http://www.wow-one.com/database/index.php?quest=114) Was the objective of the quest actually to go to tommy? The progress string seems to elude to that, but the objective just says to take the invisibility liquor to maybell

**Comment by abennette32** [comment]
Closed, the marker SHOULD be on Maybell but there is actually no marker. My bad.

**Comment by Schaka** [comment]
Should be fixed with changes to how quest finishers behave
