### ISSUE TITLE
NPC voice spam "More work" when interacting with any NPC

### ISSUE THREAD

**Issue by ZhollTas** [AeroScripts/QuestieDev#900]
Updated to latest version, everytime I interact with an NPC or open a game menu i hear the dullard npc voice  "more work". Disabling questie removes the issue

**Comment by ZhollTas** [comment]
I've actually found its everytime I hit the esc key

**Comment by BreakBB** [comment]
Could you try to disable all addons except Questie and see if the problem still exists? Sounds like a conflict with some other addon.

**Comment by Teranoll** [comment]
Conflict with Monkey Quest.  If you have the Work Complete sounds enabled in Monkey Quest and Questie installed, you'll get a "More Work" audio spam on Escape press.

**Comment by ZhollTas** [comment]
Thanks!

**Comment by AeroScripts** [comment]
I'll look in to figuring out a fix, might be something we can do on our end

**Comment by Elehiggle** [comment]
Also sometimes when I expand a zone in MonkeyQuest, "More Work" will also play.

**Comment by BreakBB** [comment]
Any news on this?
