### ISSUE TITLE
Quest Book of the Ancients - missing icon on map

### ISSUE THREAD

**Issue by jeremy560** [AeroScripts/QuestieDev#901]
Quest Book of the Ancients - missing icon on map

Once you obtain the item "Gem of the Serpent", a completed quest icon should probably appear at 28,6 in Desolace.  You use it on the statue to summon the final boss.  View attached screenshots for more info.

![questie-a](https://user-images.githubusercontent.com/46708298/64529009-0024dd00-d349-11e9-9966-584c2c32d6f7.png)
![questie-b](https://user-images.githubusercontent.com/46708298/64529010-0024dd00-d349-11e9-80d2-af02df49abe6.png)
![questie-c](https://user-images.githubusercontent.com/46708298/64529011-00bd7380-d349-11e9-928d-c385d53ae356.png)
![questie-d](https://user-images.githubusercontent.com/46708298/64529013-00bd7380-d349-11e9-807c-511148df29bb.png)

**Comment by BreakBB** [comment]
Which version are you using?
