### ISSUE TITLE
The Everstill Bridge (Redridge) wrong mobs added to drop list

### ISSUE THREAD

**Issue by reaper666735** [AeroScripts/QuestieDev#903]
## Description

so basically Questie is showing on the map that all Gnolls below and above Lakeshire (Redridge) can drop the Iron Pike/Rivets, but unfortunately only the Higher level one's on the Northern side of Lakeshire can drop them :)

## Wowhead link

Quest : https://classic.wowhead.com/quest=89/the-everstill-bridge#comments

Items + Dropped by : https://classic.wowhead.com/item=2856/iron-pike#dropped-by , https://classic.wowhead.com/item=1013/iron-rivet 

## Screenshots

wrong location:
![image](https://user-images.githubusercontent.com/33514570/64923279-b3be1f00-d7d8-11e9-91d8-924781a15723.png)

actual drop location:
![image](https://user-images.githubusercontent.com/33514570/64923280-bcaef080-d7d8-11e9-81a0-64fe0f6bf74c.png)

## Questie version

4.0.18

**Comment by BreakBB** [comment]
Thanks for the report. The spawns you saw in the south were from the rare mob "Ribchaser". I've removed him from the drop list since there is not much sense in showing a rare for a quest ^^
