### ISSUE TITLE
Conflict to TitanPanel

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#904]
## Bug description

Questie currently seems to have a conflict to TitanPanel v1.0.5.11302

On their issue tracker on CurseForge I found [this ticket](https://sourceforge.net/p/titan-panel-classic/tickets/10/) which indicated they're using the `L_Create_UIDropDownMenu` replacement of Ace. Could be something around this.

## Screenshots

![image](https://user-images.githubusercontent.com/33514570/64551267-f1ccc600-d334-11e9-88c0-f0357754a3af.png)

## Questie version

Latest master commit

**Comment by AeroScripts** [comment]
I dont think its related to L_UIDropDownMenu, ours is totally renamed into a new space to prevent issues like that (LQuestie_UIDropDownMenu) but ill do some testing

**Comment by AeroScripts** [comment]
Should be fixed in latest revision, and we weren't using LibUIDropDownMenu in v4.0.18 so im closing this for now
