### ISSUE TITLE
Horde Trauma not added

### ISSUE THREAD

**Issue by jerge** [AeroScripts/QuestieDev#905]
## Description

The first aid quest Horde Trauma was not showing up on the minimap or regular map. It did however show where I was suppose to turn it in. I was level 35 and had 225 in first aid. It might only show up if you're lvl 40, seems to be some misconceptions where people only believe they can take it in lvl40. However I could take it in lvl 35.

## Wowhead link

https://classic.wowhead.com/quest=6623/horde-trauma

## Questie version

4.0.17

**Comment by Asinin3** [comment]
It doesn't show up even if you're level 40 I can confirm this issue though.

**Comment by BreakBB** [comment]
We're hiding this quest intentionally because we currently can't check the profession of a player. Merging this with #488
