### ISSUE TITLE
FPS drop when in WestFall

### ISSUE THREAD

**Issue by tic-toc-developer** [AeroScripts/QuestieDev#906]
## Bug description
Using Alliance Human Paladin, doing quests in westfall, enabling this add-on will cause immediately FPS drop when moving, standing still won't cause the drop

## Questie version
V4.0.18

**Comment by AeroScripts** [comment]
Do you mind testing if this happens with all other addons disabled? It's questie's fault but may be related to #880 

Also, can you post back if turning off/on vsync changes things? Not a solution, but would be useful to know for debugging

**Comment by BreakBB** [comment]
it could be related to #844 as well. @tic-toc-developer do you use "MinimapButtonBag" or any similar addons?

**Comment by tic-toc-developer** [comment]
> Do you mind testing if this happens with all other addons disabled? It's questie's fault but may be related to #880
> 
> Also, can you post back if turning off/on vsync changes things? Not a solution, but would be useful to know for debugging

I've tried to disable all add-ons and enable it one by one , finally I found the questie is the one that cause this fps drop situation, enable\disable V-sync won't affect the fps drop
It's weird because this situation only appears in Westfall, not Elwynn Forest, not Stormwind(Don't know if appears in other situation, cause I'm not high level enough to wander around)

BTW I'm playing the Classic Version

**Comment by tic-toc-developer** [comment]
@BreakBB Yes, I'm using the "MinimapButtonBag", and the FPS drop stopped after I disable it and enable the "Questie"

**Comment by AeroScripts** [comment]
Oh jeez. Will look into MinimapButtonBag bug today, a few people have had trouble, and there's probably something we can do on our end to prevent it from grabing the questie minimap icons

**Comment by tic-toc-developer** [comment]
What’s more, enabling the Questie in Westfall will cause FPS drop even disabled “MinimapButtonBag”, from 75(which is locked by me) to about 40

**Comment by AeroScripts** [comment]
The FPS drop is likely due to minimap icon fade/glow. It's really inefficient right now and likely the source of the non-MBB lag

Another developer wrote some code to improve the fade logic but I haven't had the chance to properly test/include it yet (he didn't want to make a PR)

**Comment by BreakBB** [comment]
Glad we at least found one source of your issue. We already talked about MinimapButtonBag internally which somehow collects all the Questie icons instead of leaving them be.
As aero already stated other users have the same problem with this addon and we hope we can remove this conflict on our site.

**Comment by BreakBB** [comment]
This should be fixed with b5743424842d8ce47c33c2ea0bdbdbf9d5c43d58 and will be included in the next release. Keep us updated if you have further issues.
