### ISSUE TITLE
[30] Sully Balloo's Letter

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#909]
## Description
Missing startedBy
44,93 Arathi Highlands map

## Wowhead link
https://classic.wowhead.com/quest=637/sully-balloos-letter

## Screenshots
![image](https://user-images.githubusercontent.com/15526476/64614819-9ef91a00-d3d9-11e9-8069-f18db7ac50e1.png)

## Questie version
v4.0.18

**Comment by drejjmit** [comment]
More info:
https://github.com/AeroScripts/QuestieDev/commit/58874a5a9c60c3ac76c8a74477001174c803cb60

**Comment by BreakBB** [comment]
This is related to #317

**Comment by BreakBB** [comment]
Merging with #317
