### ISSUE TITLE
Error message when clicking +/- in questlog

### ISSUE THREAD

**Issue by ClownCake** [AeroScripts/QuestieDev#91]
Here we go:

Error:  attempt to concatenate field `formatUnits' (a nil value)
AddOn: Questie
File: QuestieTracker.lua
Line: 299
Count: 1

**Comment by Schaka** [comment]
We do not support Questie 1.0 anymore. Please update to 2.0.

**Comment by ClownCake** [comment]
When was it released and wherw is it?

**Comment by ClownCake** [comment]
Found it.

**Comment by Schaka** [comment]
When you switch, you might have to clear your WTF folder of all "Questie.lua" and "Quesite.lua.bak" files (before you start WoW). Otherwise it MIGHT cause issues (it didn't for our testers, but some people complained).

**Comment by ClownCake** [comment]
As usual. :)
