### ISSUE TITLE
Quest "Give Gerard a Drink" won't get marked as completed

### ISSUE THREAD

**Issue by arphox** [AeroScripts/QuestieDev#915]
## Description
I completed all quests in Elwynn Forest, but the quest (**[Give Gerard a Drink](https://classic.wowhead.com/quest=16/give-gerard-a-drink)**) is not marked as done when I finish it (it is a repeatable quest). I am an alliance player.
I tried to somehow mark it as completed manually, but could not (no right click menu, etc).

## Screenshots
![kép](https://user-images.githubusercontent.com/17320094/64635121-3e7cd380-d3ff-11e9-9e37-25f3957908b3.png)

## Questie version
**4.0.18**

**Comment by BreakBB** [comment]
With v5.1.0 repeatable quests got their own list in the "Quests by Zone" tab. However there was an issue which has been fixed with c852806ad9bc6ffe1dc4ae9c7556e807ff064597. The next release will list such quests just fine.
