### ISSUE TITLE
Unfinished string bug in latest commit

### ISSUE THREAD

**Issue by jsabin69** [AeroScripts/QuestieDev#916]
Error upon loading as follows:

Message: Interface\AddOns\QuestieDev-master\Locale\frFR\config.lua:170: unfinished string near '",'
Time: Tue Sep 10 11:40:16 2019
Count: 1
Stack: Interface\AddOns\QuestieDev-master\Locale\frFR\config.lua:170: unfinished string near '",'

Locals: >

**Comment by BreakBB** [comment]
Did you restart WoW after you updated to the latest commit? We can't reproduce this bug
