### ISSUE TITLE
Questie shows an unavailable quest "James Hyal" (part 1) at NPC "Connor Rivers"

### ISSUE THREAD

**Issue by arphox** [AeroScripts/QuestieDev#917]
## Description
Questie indicates on the map and minimap that I have an available quest **"[James Hyal](https://classic.wowhead.com/quest=1301/james-hyal)"** from NPC **[Connor Rivers](https://classic.wowhead.com/npc=5081/connor-rivers)**, but the NPC does not offer this quest. I am level 36.

## Screenshots
**Minimap saying the quest is available:**
![kép](https://user-images.githubusercontent.com/17320094/64636282-ab916880-d401-11e9-9d38-d5e1ac1acae3.png)

**But it is not:**
![kép](https://user-images.githubusercontent.com/17320094/64636319-bea43880-d401-11e9-995a-2e1330703614.png)

## Questie version
**4.0.18**

Here is my Questie.lua file, maybe it can be useful for debugging: [Questie.lua.txt](https://github.com/AeroScripts/QuestieDev/files/3596991/Questie.lua.txt)

**Comment by BreakBB** [comment]
Related to #889

**Comment by haggen** [comment]
Another case where the old comments from Thotbot, now on Wowhead, may shed light: https://classic.wowhead.com/quest=1301/james-hyal#comments

From what I gather there's a Cookie level requirement for it to be available.

@arphox Could you check again with the NPC and tell us what's your Cooking skill?

**Comment by arphox** [comment]
My cooking skill is 225/225.

**Comment by BreakBB** [comment]
If @arphox has 225/225 cooking this seems to be something else for this quest 🤔 @haggen Could you check if you can accept the quest? Kind of strange if the second part can just be accepted but the first part requires cooking

**Comment by haggen** [comment]
@BreakBB Yes I have the part 1 available to me as well. Also I've got 184/225 Cooking. 

@arphox Could you do us another favor? Could you type the following in-game and tell us what it shows?
```
/dump {IsQuestFlaggedCompleted(1301), IsQuestFlaggedCompleted(1302)}
```

**Comment by arphox** [comment]
> 
> 
> @BreakBB Yes I have the part 1 available to me as well. Also I've got 184/225 Cooking.
> 
> @arphox Could you do us another favor? Could you type the following in-game and tell us what it shows? Oh and how much reputation you have towards Stormwind?
> 
> ```
> /dump {IsQuestFlaggedCompleted(1301), IsQuestFlaggedCompleted(1302)}
> ```
```
[1]={
  [1]=false,
  [2]=true
}
```

**Comment by haggen** [comment]
@arphox Thank you!
@BreakBB Well there we go. He's already completed part 2 which makes part 1 kind of obsolete since it only exists to direct you to part 2. I'm might be wrong but wouldn't it be the case to simply add part 1 (1301) to the exclusivity group of part 2 (1302)?

**Comment by BreakBB** [comment]
@haggen Yes, you're absolutely correct for this part! Fixed the requirements
