### ISSUE TITLE
The Restless Souls bug

### ISSUE THREAD

**Issue by Mrhgb** [AeroScripts/QuestieDev#919]
https://i.imgur.com/3agsZAd.jpg

**Comment by BreakBB** [comment]
Please follow the issue template!

We need to know which version of Questie you're using to help with the issue.

**Comment by Mrhgb** [comment]
4.0.18

**Comment by AeroScripts** [comment]
Yeah looks like npc 11122 is missing from the DB, we'll need to manually define it

**Comment by Asinin3** [comment]
Yeah same issue here.

**Comment by BreakBB** [comment]
Should be fixed with 376661f6f4d8157358cef11ce041ad338a9f78d6
