### ISSUE TITLE
There's no straight way to remove quest from trackerframe

### ISSUE THREAD

**Issue by ayrb13** [AeroScripts/QuestieDev#92]
I opened an issue few days ago and i suggest to add a right click menu to remove quest from trackerframe instead of shift+click in native questlog.

**Comment by Schaka** [comment]
There used to be a menu that got removed again and will be re-added in time. 
The quests currently always re-add to log if you have auto-tracking enabled, so that needs to go as well.

**Comment by ayrb13** [comment]
How do I set auto-tracking enable/disable?

**Comment by Schaka** [comment]
ESC -> Interface -> Automatically Track New Quests (or something)

**Comment by ayrb13** [comment]
k, I know that, I thought it should be set in addons menu or something.
