### ISSUE TITLE
Group minimap/map icons by proximity

### ISSUE THREAD

**Issue by indiewhite** [AeroScripts/QuestieDev#920]
Personally, a dozen icons on the minimap is distracting but I also like seeing the icons without opening the main map for when I'm in contested zones. It'd be nice to have the option to see icons showing objectives for the same quest grouped when they are close by to each other. My request is primarily for the minimap icons, but it'd also be helpful for the world map as well.

**Comment by Muehe** [comment]
The "clustering" of notes you describe is already active in Questie, but it is not configurable as far as I know. You could manually set the radius higher in the code, but that would get overwritten on every update.

**Comment by BreakBB** [comment]
@indiewhite Yes this is already implemented with the "clustering" and there is a slider in the General tab which lets you set a value of how much close icons should be clustered together. A high value means less icons. You might wanna play around with it to find the best value for you!
