### ISSUE TITLE
Quest Locked Away 

### ISSUE THREAD

**Issue by Nimbix-wow** [AeroScripts/QuestieDev#922]
## Description

Quest 5060, Locked Away still showing after completion.

## Wowhead link

https://classicdb.ch/?quest=5060

## Questie version

v4.0.18

**Comment by Kopo942** [comment]
Have you tried to /reload? Might be related to #860.

**Comment by Nimbix-wow** [comment]
I have used this command several times:

/run Questie.db.char.complete = {}
/reload

And its still showing.

If querying the server for this quest (5060) it tells me I have completed it.

**Comment by AeroScripts** [comment]
<https://classicdb.ch/?search=Locked+Away>
Looks like there are actually 2 quests with this name, maybe the other one is showing? Can you check IsQuestFlaggedCompleted for that one? (5059)

**Comment by Nimbix-wow** [comment]
5059 is a repeatable quest it seems, you can't complete 5060 without doing 5059,

**Comment by Asinin3** [comment]
I am getting this issue too, the one that's still showing is from the outhouse. Also There's another issue with this quest where, before you complete it. It shows 2 quest markers as available even though you haven't done the first quest which is from the diary https://classic.wowhead.com/quest=5058/mrs-dalsons-diary

What should happen is it should only show the Diary quest as available, and then once you complete it should tell the player that the first Locked Away quest is available.
