### ISSUE TITLE
Questie does not show available quest: "I Know A Guy..." from "Daryl Riknussun"

### ISSUE THREAD

**Issue by arphox** [AeroScripts/QuestieDev#924]
## Description
The NPC **[Daryl Riknussun](https://classic.wowhead.com/npc=5159/daryl-riknussun)** offers the quest **[I Know A Guy...](https://classic.wowhead.com/quest=6612/i-know-a-guy)**, but Questie does not show it on the map/minimap. I tried reloading but did not help. I am a level 37 priest with 225/225 cooking.
This may be important since this is the quest that you need for Artisan Cooking.

## Screenshots
![WoWScrnShot_091119_081311](https://user-images.githubusercontent.com/17320094/64672522-03fd5000-d46c-11e9-8695-dcce517048c4.jpg)

## Questie version
4.0.18

**Comment by AeroScripts** [comment]
All profession quests are hidden currently, so its not specific to this quest
We need to add logic to check professions so we can enable them, going to work on that soon

**Comment by arphox** [comment]
> 
> 
> All profession quests are hidden currently, so its not specific to this quest
> We need to add logic to check professions so we can enable them, going to work on that soon

Alright I am sorry, didn't know. Thanks for letting me know.

**Comment by BreakBB** [comment]
This has been fixed with the release of 4.1.1
