### ISSUE TITLE
[52] The Hunter's Charm

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#925]
## Description
This quest requires reputation from Timbermaw (Felwood) according to Wowhead comments. Can't pick it up. Nothing completed in Felwood.
Hunter trainer in Stormwind and Darnassus doesn't offer it as well.

## Wowhead link
https://classic.wowhead.com/quest=8151/the-hunters-charm#comments:id=2977361

## Screenshots
![image](https://user-images.githubusercontent.com/15526476/64677251-7b84ac80-d477-11e9-8a7c-3e8db8c5d910.png)

## Questie version
v4.0.18

**Comment by BreakBB** [comment]
We aren't checking reputation yet. But will soon after professions have already been implemented this should be easy

**Comment by BreakBB** [comment]
This is one of the Sunken Temple class quests and will be blacklisted till phase 4 21d045c6faf6deff995d4a3c68e190ab705f3509
