### ISSUE TITLE
Filter quests by quest name.

### ISSUE THREAD

**Issue by holland11** [AeroScripts/QuestieDev#932]
It would be a nice QoL improvement if we could filter certain quests by their name to hide them from the map/minimap. Maybe have 2 options: blacklist quest by name, whitelist quest by name. 

If blacklist quest by name is active, show all quests except the ones on the blacklist.

If whitelist quest by name is active, only show the quests on the whitelist.

Just an idea!

**Comment by Muehe** [comment]
By now hiding a quest is possible by shift-clicking it on the map or by searching it in the journey window and setting the checkbox. Assumed solved.
