### ISSUE TITLE
Quest - Dig Rat Stew

### ISSUE THREAD

**Issue by VoronGlass** [AeroScripts/QuestieDev#933]
## Description
Missing this quest. Please Add.

## Wowhead link
https://classic.wowhead.com/quest=862/dig-rat-stew

**Comment by AeroScripts** [comment]
Are you on v4.0.18? Make sure you're updated, this has been fixed in recent versions (thanks for posting though!)

**Comment by VoronGlass** [comment]
yes 4.0.18 and this quest was "hide"
p.s. i hope you understand my english :)

ср, 11 сент. 2019 г. в 23:43, AeroScripts <notifications@github.com>:

**Comment by AeroScripts** [comment]
Hmm, maybe I didn't fix it correctly, wasn't able to test it at the time ill check it out

**Comment by BreakBB** [comment]
This is a cooking quest and therefore blacklisted for now. After 4.1 we will most likely include profession quest pretty soon ™️

**Comment by BreakBB** [comment]
4.1.1 introduces the profession logic which solves this issue.
