### ISSUE TITLE
After completing Mrs. Dalson's Diary, questie should show where the key drops

### ISSUE THREAD

**Issue by Asinin3** [AeroScripts/QuestieDev#934]
When you complete the https://classic.wowhead.com/quest=5058/mrs-dalsons-diary quest it becomes possible to loot the key from the Wandering Skeleton https://classic.wowhead.com/npc=10816/wandering-skeleton While this isn't exactly a "quest", the key is needed in order to accept the quest nearby from the outhouse https://classic.wowhead.com/quest=5059/locked-away

I still think it should be on the map personally, since it's not exactly clear who drops the key and knowing that it's the wandering skeleton (which may also not be spawned at that time) would be helpful for players.

**Comment by BreakBB** [comment]
Not sure how we could add this into Questie. Maybe @AeroScripts has an idea?

**Comment by Gogo1951** [comment]
Yeah... we could show the quest on the skeleton, but it's not clear what to do with the key since it's not a "this item starts a quest" item. 

Another thing for the "catch all" text bucket idea. 

https://github.com/AeroScripts/QuestieDev/issues/317#issuecomment-564613358

**Comment by BreakBB** [comment]
Closing this in favor of #317
