### ISSUE TITLE
Finding the Antidote subquest still tagged as available

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#935]
Finding the Antidote is a subquest for Need for a Cure, but although Need for a Cure has been completed and is in the Completed Quests section of Durotar quests, Finding the Antidote is still in the Available Quests section of Orgrimmar.

https://classic.wowhead.com/quest=813/finding-the-antidote

4.0.18

**Comment by BreakBB** [comment]
Merging with #791
