### ISSUE TITLE
WC quests in incorrect zone lists

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#936]
Deviate Eradication and Deviate Hides are in the Barrens, Mulgore and Durotar lists, despite being located entirely within the Barrens & Wailing Caverns. 

https://classic.wowhead.com/quest=1487/deviate-eradication
https://classic.wowhead.com/quest=1486/deviate-hides

4.0.18

**Comment by BreakBB** [comment]
Merging this with #822
