### ISSUE TITLE
Add sharing of objectives with party members

### ISSUE THREAD

**Issue by ShaunDreclin** [AeroScripts/QuestieDev#937]
This would be great when you're questing with friends so you don't have to keep asking how many more _____ they need! It could be added to the tooltip under your own objectives, I think that's how it's done on retail.

An option to show party members' quest objectives even if you've finished them/aren't on them at all would be useful too.

**Comment by BreakBB** [comment]
That is a great idea even though I can't tell if this will be possible with the changes to the API which prevent Classic-LFG.

**Comment by ShaunDreclin** [comment]
afaik those changes are targeted at the faction-wide addon channels, party/guild channels should still function fine.

**Comment by BreakBB** [comment]
This is implemented with v5.0.0
