### ISSUE TITLE
Quests "Mantle of the Dawn" and "Chromatic Mantle of the Dawn" showing available

### ISSUE THREAD

**Issue by Asinin3** [AeroScripts/QuestieDev#939]
These quests require Argent Dawn Reputation in order to be picked up. The Mantle of the Dawn quests are available once you are Revered and the Chromatic Mantle of the Dawn quest is available once you are exalted.

Note that this is actually 6 quests in total:
https://classic.wowhead.com/search?q=mantle%20of%20the%20dawn#quests

I'm using v4.0.18

**Comment by BreakBB** [comment]
Just as with professions we currently don't check the requirements for those quests. But we will and come back to this issue. Thanks for the report 😄

**Comment by BreakBB** [comment]
Fixed with 6829244438e07b1ee4486fcb771a41f93551ad7f and will be included in v4.1.3
