### ISSUE TITLE
Quest "Love Potion" incorrectly showing Gromsblood mouse-over marker on many mobs

### ISSUE THREAD

**Issue by Asinin3** [AeroScripts/QuestieDev#940]
When I have the quest "Love Potion" https://classic.wowhead.com/quest=4201/the-love-potion

Questie Shows the objective and "Gromsblood 0/4" On the mouse-over for many mobs such as the Tar Lords in Un'Goro Crater, or Monstrous Plague Bats in Eastern Plaguelands https://classic.wowhead.com/npc=8602/monstrous-plaguebat and even certain bosses. The droprate of gromsblood is so low that mobs should generally not be listed to begin with (IMO). And it seems that according to wowhead these mobs don't even have Gromsblood on their loot table.

![image](https://user-images.githubusercontent.com/15137035/64744986-24e5a400-d545-11e9-87e4-166e0d9ed7c2.png)

v4.0.18

**Comment by BreakBB** [comment]
The fix for this is already on the master branch and will be released with 4.1 which should be released soon :tm:

**Comment by BreakBB** [comment]
This has been fixed with the release of 4.1
