### ISSUE TITLE
No turn in ? on map for turn in of "Elemental Bracers" in ashenvale

### ISSUE THREAD

**Issue by tilkinsc** [AeroScripts/QuestieDev#941]
## Description
No turn in ? on map for turn in of "Elemental Bracers" in ashenvale

## Wowhead link
https://classic.wowhead.com/npc=3885/sentinel-velene-starstrike

## Questie version
4.0.17

**Comment by hopdenakker** [comment]
This quest still has issues. Required a /reload for the quest turn in to appear. Also, the objective icons for "Intact Elemental Bracer" do not disappear after obtaining the Divined Scroll.

**Comment by tilkinsc** [comment]
I can't say I had the later problem.
