### ISSUE TITLE
Quest #8798 is still showing after completion

### ISSUE THREAD

**Issue by Nimbix-wow** [AeroScripts/QuestieDev#945]
## Description

Quest #8798: A Yeti of your own is still showing after completion.

Tried using the /run Questie.db.char.complete = {} and /reload but still showing.

## Wowhead link

https://classicdb.ch/?quest=8798

## Questie version

v4.0.18

**Comment by BreakBB** [comment]
Could you run `/dump IsQuestFlaggedCompleted(8798)` in the chat and report the response? Beside that this quests requires engineering I can't find out anything unusual on this. Will hide it for now.

**Comment by Nimbix-wow** [comment]
This quest rewards a yeti companion with three charges if you dont have engineering. Which I have recieved.

If i run /dump IsQuestFlaggedCompleted(8798) it returns a 'false'.

**Comment by BreakBB** [comment]
Sorry for the late response, but I have two things:

1. Can you repeat this quest? Because it is not listed as repeatable in our data
2. Do I understand you correct that no Engineering is required to complete this quest?

Moreover Wowhead lists the item you linked only to the quest [Are We There, Yeti?](https://classic.wowhead.com/quest=5163).

**Comment by Nimbix-wow** [comment]
1. No, this quest is not repeatable.

2.There are no engineering requirements for this quests. It rewards a Tranquil Mechanical Yeti https://classicdb.ch/?item=15778 if you dont have the engineering profession.

If you are a engineer it also rewards the schematic to make said yeti.

**Comment by BreakBB** [comment]
Sorry for the late response on this. I did some more research!

If you complete the last quest of [Are We There, Yeti?](https://classic.wowhead.com/quest=5163/are-we-there-yeti) it will unlock [A Yeti of Your Own](https://classic.wowhead.com/quest=8798/a-yeti-of-your-own) if you have engineering as well.

So basically this quest line has 4 quests for engineers, but only 3 for everyone else. With the release of 4.1.1 we handle profession quests correctly so this should be fixed. @Nimbix-wow Please report back if the quest still shows up with 4.1.1
