### ISSUE TITLE
A Lesson to Learn map bug

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#948]
A Lesson to Learn still shows up as available on the map and minimap after accepting it.

https://classic.wowhead.com/quest=27/a-lesson-to-learn

![WoW Questie A Lesson to Learn Map Bug](https://user-images.githubusercontent.com/54936174/64826464-ff967b80-d5c0-11e9-80a9-fb6f051fe7a3.png)

4.0.18

**Comment by Cerby3BR** [comment]
![WoW Questie A Lesson to Learn Mixup Error](https://user-images.githubusercontent.com/54936174/64863789-f98eb200-d635-11e9-8043-ec2c60f02e56.png)

I found out what's going on, y'all mixed up the Alliance and Horde sides of the quests. In your database, quest n°26 is the Horde side, but what I actually completed with my Tauren was quest n°27.

**Comment by Cerby3BR** [comment]
Gonna do the rest of the questline to see what's what.

**Comment by BreakBB** [comment]
Thanks for investigating the issue :+1: I will have a look at our data very soon and if you're right it will be an easy fix!

**Comment by Cerby3BR** [comment]
![WoW Questie A Lesson to Learn Trial of the Lake Completion](https://user-images.githubusercontent.com/54936174/64864615-d238e480-d637-11e9-9e1e-08daf23f1394.png)

So 26 and 29 are Alliance, while 27 and 28 are Horde. The rest of the line will take a bit more time, sorry.

**Comment by Cerby3BR** [comment]
Finished the questline, everything else is fine and dandy. The only mistake is with A Lesson to Learn.

**Comment by BreakBB** [comment]
Thanks for your very detailed report. This is fixed now!
