### ISSUE TITLE
Questie button position on metamap

### ISSUE THREAD

**Issue by nycter79** [AeroScripts/QuestieDev#95]
![image](https://cloud.githubusercontent.com/assets/10027713/7616769/4f1f740e-f9a7-11e4-82d2-48259e39b30f.png)

"toggle questie" button seems to be kinda out of the map (metamap)

**Comment by Sparh4wk** [comment]
yep, it was designed for cartographer, so thats why :)

**Comment by nycter79** [comment]
I thought it should work with all map addons ---> "We have since moved away from Cartographer and now support all mapping addons, making us a standalone QuestHelper. We just draw frames on the world map ourselves"

But its not a big deal, just cosmetic issue

**Comment by Sparh4wk** [comment]
well its working, or not? I just told you that button is off, cause that button was designed for cartographer... its still works..

**Comment by nycter79** [comment]
sure, q tracking works fine, just wanted to report this visual bug

**Comment by AeroScripts** [comment]
Thanks for reporting it, shouldn't be too difficult to fix
