### ISSUE TITLE
Show prerequisites for quests in the "Quests by Zone" search

### ISSUE THREAD

**Issue by MrBrax** [AeroScripts/QuestieDev#957]
## Description

Would be very useful if you're coming into an area with a higher level and have no quests, or you think you've done all quests in an area but there are prerequisites and quest chains going on.

I would code this myself, but there's a lot of code and logic to learn in this addon.

**Comment by Gogo1951** [comment]
Hey @MrBrax ,

Did you want to take a stab at writing the code for this? Lots going on, would be helpful if you had time to contribute. Thanks!

**Comment by Gogo1951** [comment]
I think this issue could be solved with this idea too.

https://github.com/AeroScripts/QuestieDev/issues/317#issuecomment-564613358

**Comment by MrBrax** [comment]
> 
> 
> Hey @MrBrax ,
> 
> Did you want to take a stab at writing the code for this? Lots going on, would be helpful if you had time to contribute. Thanks!

Nah i dropped WoW, too much grinding. Haven't really thought about it since.

**Comment by AeroScripts** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.
