### ISSUE TITLE
Vilebranch Hooligans missing multiple locations for Slagtree's Lost Tools

### ISSUE THREAD

**Issue by xerxespersrex** [AeroScripts/QuestieDev#961]
Slagtree's Lost Tools are given only one location in latest Questie and they are not spawning there for me on top of Skull Rock. According to Wowhead comments, there's multiple spawns, so those multple spawns should also be shown on the map icons. Using Questie 4.0.18, here's a link to wowhead comments giving multiple coordinate locations for the item: https://classic.wowhead.com/item=19033/slagtrees-lost-tools#comments

**Comment by xerxespersrex** [comment]
I wrote this pretty poorly... Basically the tools can spawn in many locations, and Questie only has one of them.

**Comment by BreakBB** [comment]
Thanks for your report! You were right we've had only one spawn in our data.
