### ISSUE TITLE
Chen's Empty Keg

### ISSUE THREAD

**Issue by Rezzme** [AeroScripts/QuestieDev#962]
## Description
Chen's empty keg is a repeatable quest. Questie keeps telling me to go back and pick it up. I have already done it three times in an attempt to make Questie stop sending me back to Ratchet. I cannot clear it even by abandoning the quest. 

## Wowhead link
https://classic.wowhead.com/quest=822/chens-empty-keg

## Screenshots
![WoWScrnShot_091319_152805](https://user-images.githubusercontent.com/55296923/64889523-8a1bc100-d63b-11e9-96fc-630135cdc07b.jpg)

## Questie version
4.0.08 is the Questie version.
![WoWScrnShot_091319_152805](https://user-images.githubusercontent.com/55296923/64889469-6e181f80-d63b-11e9-8814-d608643be814.jpg)

**Comment by BreakBB** [comment]
Sorry but the issue you experience is from the AAP addon and not Questie. Run `/aap skip`.
