### ISSUE TITLE
The Lost Dwarves Quest ID 2398 Wrong Completion location.

### ISSUE THREAD

**Issue by Napsterbater** [AeroScripts/QuestieDev#963]
## Description
The Lost Dwarves Quest ID 2398 Wrong Completion location, should be At/in Uldaman instance, Shows at Dustwind Gulch in Badlands

## Wowhead link
https://classic.wowhead.com/quest=2398/the-lost-dwarves#comments

## Screenshots
![WoWScrnShot_091319_202132](https://user-images.githubusercontent.com/18711451/64901190-95371700-d664-11e9-86a1-47a8e3c26283.jpg)
![WoWScrnShot_091319_202134](https://user-images.githubusercontent.com/18711451/64901191-97997100-d664-11e9-8d48-a78f261c8229.jpg)
Edit: Added 2 SSs, Seems there is two markers, one at the instance is ok, the other is not.                   

## Questie version
4.0.18

**Comment by drejjmit** [comment]
That's the back entrance. A is in the North and B is in the East
![image](https://user-images.githubusercontent.com/15526476/65275366-ceb8c800-db25-11e9-82ae-74b9c47642ed.png)
