### ISSUE TITLE
gadgetzan water survey - missing location to use item

### ISSUE THREAD

**Issue by ssateneth** [AeroScripts/QuestieDev#968]
## Description

no map icon to show where to use "untapped dowsing widget"

## Wowhead link

https://classic.wowhead.com/quest=992/gadgetzan-water-survey

## Questie version

4.0.18

**Comment by ssateneth** [comment]
also questie desynced and didnt show turnin location until after i /reload ui

**Comment by BreakBB** [comment]
This is fixed with 4.1 however now there is a different error #1013 Merging this and will fix the error later this day.
