### ISSUE TITLE
Unable to hand in quest

### ISSUE THREAD

**Issue by Bugreport101** [AeroScripts/QuestieDev#97]
Hi,

I completed the quest "Doctor Theolen Krastinov, the Butcher" from "Eva Sarkhoff" outside Scholomance, but not able to hand it in.

When speaking to NPC, she only tells the pre-story, after that nothing happens.
I've deleted WDB and WTF folder, same issue.
Tried abandon quest and take it again, but now I'm not even to pick up the quest, only listen to the story.

Could you please help me out?
Thanks in advance!

**Comment by Schaka** [comment]
That sounds like a server issue to me, nothing that has to do with Questie at all. Can you turn in the Quest, when Questie is turned off?

**Comment by Bugreport101** [comment]
No.

I'll report to server.

Thank you!
