### ISSUE TITLE
Quest missing: Soothing Turtle Bisque

### ISSUE THREAD

**Issue by melvintj** [AeroScripts/QuestieDev#970]
## Description
The ! mark is missing for the quest: Soothing Turtle Bisque
As horde you can start the quest in Tarren mill at the Tradesman "Christoph Jeffcoat".

## Wowhead link
https://vanilla-twinhead.twinstar.cz/?quest=7321

## Screenshots
![Missing_quest](https://user-images.githubusercontent.com/32409042/64906179-4aa8af80-d6e3-11e9-8bd1-858f47426225.png)

## Questie version
v4.0.18 Beta

**Comment by BreakBB** [comment]
This quest has been blacklisted till 4.1.1 since it is a profession quest. The latest release finally includes the required logic to handle such quests.
