### ISSUE TITLE
The Glowing Fruit shows up despite having prerequisites

### ISSUE THREAD

**Issue by Ultroman** [AeroScripts/QuestieDev#971]
## Bug description
The quest "The Glowing Fruit" in Darnassus shows as being available, even though the two quests "Timberling Seeds" (https://classic.wowhead.com/quest=918/timberling-seeds) and "Timberling Sprouts" (https://classic.wowhead.com/quest=919/timberling-sprouts) are actually prerequisites for the quest. They are not "logged" as such in the Wowhead database. I only learned about it from a comment on Wowhead.

## Questie version
4.0.18 BETA

**Comment by anon1231823** [comment]
For anyone reading this in the future, I discovered that only 918 is the prerequisite. 919 is not a prerequisite for either glowing fruit or shimmering frond. Tested on Classic Era.
