### ISSUE TITLE
[36] Claim Rackmore's Treasure!

### ISSUE THREAD

**Issue by tolsadus** [AeroScripts/QuestieDev#974]
## Description
Showing only the naga to kill for the gold key, but not location of the Drysnap Pincer and Drysnap Crawler for the silver key.

## Wowhead link
https://classic.wowhead.com/quest=6161/claim-rackmores-treasure

## Questie version
v4.0.18

**Comment by BreakBB** [comment]
Are you using an English client?

**Comment by tolsadus** [comment]
Sadly no, it's the french one.

**Comment by BreakBB** [comment]
Alright I am merging this ticket with #819 then. Looks like we have a general logic issue for non English clients. Thanks for the fast response 😃
