### ISSUE TITLE
Mouse over quest icon = Highlight all icons belonging to same quest

### ISSUE THREAD

**Issue by holland11** [AeroScripts/QuestieDev#975]
Could be a neat feature where if you put your mouse over a quest icon on the map, all the icons from the same quest get highlighted / become bigger / all other icons become more transparent / smaller.

**Comment by BreakBB** [comment]
Yes, that sounds like a good idea and some requirements are already fulfilled for this. For now you can also "Focus" a quest with the Tracker to fade out objectives that don't belong to this quest.
