### ISSUE TITLE
Mini map can't show

### ISSUE THREAD

**Issue by a2140666** [AeroScripts/QuestieDev#980]
## Bug description
  Mini map can't show Mission objectives and can accept mission

**Comment by BreakBB** [comment]
Could you provide some more details about your issue? What version of Questie do you use? Are you sure the option for the minimap is turned on? You can check it in the Questie config.

**Comment by a2140666** [comment]
> 你能提供一些关于你的问题的更多细节吗？您使用的是什么版本的Questie？您确定已启用小地图的选项吗？您可以在Questie配置中进行检查。
![QQ截图20190916100517](https://user-images.githubusercontent.com/52083485/64931230-cb91b380-d869-11e9-9796-575dadcf96a2.png)
![QQ截图20190916100525](https://user-images.githubusercontent.com/52083485/64931231-cc2a4a00-d869-11e9-927d-128465ccb7cd.png)
![QQ截图20190916100602](https://user-images.githubusercontent.com/52083485/64931233-cc2a4a00-d869-11e9-9ef7-b43e8a64ce85.png)
I am sure i check the settings.I open the mini map. When i open the game,it can show 10 secends but after moment ,they disappear

**Comment by BreakBB** [comment]
It looks like you're using an addon for minimap icons (to bind all icons into one).
Which addon is this?
![image](https://user-images.githubusercontent.com/33514570/65377378-5419b500-dcab-11e9-9b6b-ea32db8c85cd.png)

If you disable it, do the icons appear?

**Comment by BreakBB** [comment]
@a2140666 Any news on this?

**Comment by BreakBB** [comment]
Assuming this is fixed
