### ISSUE TITLE
[42] Shadowshard Fragments level requirement issue

### ISSUE THREAD

**Issue by Magrit** [AeroScripts/QuestieDev#984]
## Description
The quest shows as available for lvl 38, but it is available first at 39

## Wowhead link
https://classic.wowhead.com/quest=7070/shadowshard-fragments

## Questie version
4.0.18

**Comment by BreakBB** [comment]
Duplicate of #951 This will be fixed with the soon released v4.1.0 😄

**Comment by Magrit** [comment]
Does this fix both the alliance and horde version of the same-named quest though? :) Thanks!

**Comment by BreakBB** [comment]
I didn't know there was a version per faction :open_mouth: The issues only pointed out the quest with ID 7070. Thanks for pointing this out! I just fixed the Horde version in 57e26c3aa937248b78fbf8f71cf88987920bdf02
