### ISSUE TITLE
[60] Lorax's Tale

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#988]
## Description
Blacksmithing quest.

## Wowhead link
https://classic.wowhead.com/quest=5126/loraxs-tale

## Screenshots
![image](https://user-images.githubusercontent.com/15526476/64925695-f130a580-d7f4-11e9-880d-6e1a655812d1.png)

## Questie version
v4.1.0

**Comment by BreakBB** [comment]
Fixed with 4.1.1
