### ISSUE TITLE
[53] Expedition Salvation

### ISSUE THREAD

**Issue by Detoxicity** [AeroScripts/QuestieDev#990]
## Description
The quest is not displaying the location of the "Crate of Foodstuffs" which is reported to be located at 68.4, 36.5 in Un'goro Crater.

## Wowhead link
https://classic.wowhead.com/quest=3881/expedition-salvation

## Screenshots
![image](https://user-images.githubusercontent.com/33514570/65017252-8e3f2b80-d926-11e9-9c62-a03be7671502.png)

## Questie version
4.0.18

**Comment by ssolidus** [comment]
its 68,38. just did the quest
