### ISSUE TITLE
Reload Questie ignoring Focused/Unfocused icons.

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#994]
## Bug description
Ctrl + Left Click: Reload Questie does not redraw unfocused quest objectives with alpha/fade. Only /reload does.

## Questie version
v4.1.0

**Comment by BreakBB** [comment]
I just tested this and all icons are drawn again, but it seems the focus is kind of reset for the icons. The focused quest stayes as focused (meaning the tracker indicated "Unfocus") though.

Guess the reset of Crtl + left click does too much.

**Comment by BreakBB** [comment]
Fixed with b4b13a3985fa1cf71c492c65a758ac9af60d8e7f
