### ISSUE TITLE
Toggle quest level display in tooltips / tracker

### ISSUE THREAD

**Issue by S1nn1cle** [AeroScripts/QuestieDev#995]
## Description

Currently quests are displayed in the tooltips and on the tracker as such [35] Raptor Mastery.

Id love an option to toggle the level on or off so the title displays Raptor Mastery.

(If this functionality already exists, im sorry and im clearly blind)

**Comment by BreakBB** [comment]
I've added an option for this and it will be included in our next update.

You will be able to toggle it for tooltips and for the tracker individually.
