### ISSUE TITLE
Limit number of tracked quests

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#998]
## Description

Suggested on [Curseforge](https://www.curseforge.com/wow/addons/questie?comment=498) it would be good to limit the quests the tracker contains.
Some config to set the max amount of quests on the tracker so the "Auto track quests" option can stay enabled.
Moreover the background tint should be configurable.

**Comment by AeroScripts** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.
